### ISSUE TITLE
[Feature request] Add option to batch download

### ISSUE THREAD

**Issue by paniash** [pystardust/ani-cli#10]
Hi!

Wonderful script to stream and download anime. Currently the script supports downloading only one episode at a time. It would be great if a batch download option would be available. For example to download episodes 1 to 10

```
ani-cli -d shingeki no kyojin --episodes 1:10 
```

I think this would be a great feature welcomed by everyone. Keep up the good work!

**Comment by pystardust** [comment]
that sounds good, but it would be better to have the anime_id instead of the anime name ( the id that pops up in search). What if in the cli itself, there is a prompt asking the episode range to download?

**Comment by paniash** [comment]
Yeah, that would be great but from an interactivity perspective. If people want to script something, I guess something like the one I suggested would be nice. But it's upto you.

**Comment by pystardust** [comment]
9792a65144a6dc1f883f031312665ada27acec91

I have added bacth download  facility interactively, check the readme for usage

**Comment by paniash** [comment]
Awesome! Thanks 😃

**Comment by ninko76** [comment]
> [9792a65](https://github.com/pystardust/ani-cli/commit/9792a65144a6dc1f883f031312665ada27acec91)
> 
> I have added bacth download facility interactively, check the readme for usage

can you post an example i cant get this to work 😢
