### ISSUE TITLE
shuf: command not found

### ISSUE THREAD

**Issue by JorgePAJ** [pystardust/ani-cli#1000]
**Metadata (please complete the following information)**
Version: latest
OS: macos
Shell: zsh

**Describe the bug**
the script works, but im just getting this printed 
`/opt/homebrew/bin/ani-cli: line 255: shuf: command not found`

**Steps To Reproduce**

1. Run `ani-cli`

**Expected behavior**
should not show that

**Screenshots (if applicable; you can just drag the image onto github)**
<img width="511" alt="Screenshot 2023-01-26 at 12 32 16" src="https://user-images.githubusercontent.com/66725751/214932209-b9937230-31bd-4198-bd15-15a3ffc42fbb.png">

**Additional context**

**Comment by Antabuse-does-something** [comment]
You just have to install `coreutils` as described here : 
https://apple.stackexchange.com/questions/142860/install-shuf-on-os-x

**Comment by port19x** [comment]
We'll likely get rid off shuf as a requirement anyway
