### ISSUE TITLE
referer needed for some requests

### ISSUE THREAD

**Issue by NepKitsune** [pystardust/ani-cli#1004]
**Metadata (please complete the following information)**
Version: [4.0.3]
OS: [MacOS Ventura 13.0]
Shell: [zsh]
Terminal: [kitty]
Anime: [Any] 

**Describe the bug**
Playing any anime results 'Episode Not Released'

**Steps To Reproduce**

1. Run `ani-cli [ any anime ]`
2. Choose any

**Expected behavior**
Downloading/watching should work

**Screenshots (if applicable; you can just drag the image onto github)**
![Screenshot 2023-01-30 at 5 30 11 PM](https://user-images.githubusercontent.com/71800980/215425975-39e47a4f-ed57-47b1-829d-ef1f7ae7c109.jpg)

**Comment by Veroniclover** [comment]
This is currently happening with my side, when trying with my isp internet [Japan IP] it didn't work, while week ago it's running smoothly with my ISP internet.

This is probably because of their cloudflare raise of security when using Japan IP.
Specification: specially in this url `https://allanime.site/watch/Mk8Z4bqjYq9FNeRDS/episode-13-sub`
![Screenshot_20230131_234511](https://user-images.githubusercontent.com/73184907/215792567-98f8e27c-38a1-4711-b877-3b6a456aec48.JPG)

**Comment by Veroniclover** [comment]
> This is currently happening with my side, when trying with my isp internet [Japan IP] it didn't work, while week ago it's running smoothly with my ISP internet.
> 
> This is probably because of their cloudflare raise of security when using Japan IP. Specification: specially in this url `https://allanime.site/watch/Mk8Z4bqjYq9FNeRDS/episode-13-sub` ![Screenshot_20230131_234511](https://user-images.githubusercontent.com/73184907/215792567-98f8e27c-38a1-4711-b877-3b6a456aec48.JPG)

I solved this by using `Referer` header to `https://allanime.site` for all wget requests, should i make pr for it?

**Comment by CoolnsX** [comment]
nope don't, we are switching back to curl so ur PR will be ur time waste

**Comment by Kroxlyn** [comment]
> > This is currently happening with my side, when trying with my isp internet [Japan IP] it didn't work, while week ago it's running smoothly with my ISP internet.
> > This is probably because of their cloudflare raise of security when using Japan IP. Specification: specially in this url `https://allanime.site/watch/Mk8Z4bqjYq9FNeRDS/episode-13-sub` ![Screenshot_20230131_234511](https://user-images.githubusercontent.com/73184907/215792567-98f8e27c-38a1-4711-b877-3b6a456aec48.JPG)
> 
> I solved this by using `Referer` header to `https://allanime.site` for all wget requests, should i make pr for it?

Please make it for me I am a noob and doesn't know how to do it .
