### ISSUE TITLE
Change quality while watching

### ISSUE THREAD

**Issue by ZulluBalti** [pystardust/ani-cli#1006]
I think it would be a very useful feature to be able to change the quality of video in the middle of watching an anime.

Currently when I press 'q' while a video is playing it takes me to a FzF menu with the following options

* quit
* select
* previous
* next
* reply

Another option of "change quality" would be nice.

**Comment by Derisis13** [comment]
This used to be a function, we removed it for the sake of "streamlineing". @port19x should we consider adding it back?

**Comment by port19x** [comment]
I'm skeptical. Isn't that something constant? Or do people have sudden bandwidth drops between EPs. Just kinda feels odd

**Comment by port19x** [comment]
Eh whatever, let's leave this for someone eager to contribute. Should be like 5 loc at most

**Comment by candrapersada** [comment]
![image](https://user-images.githubusercontent.com/36833664/216196005-af7cddf6-f2c7-4bcb-9a19-ef8a14633047.png)
