### ISSUE TITLE
gogoanime.vc is being blocked by Indian Govt.

### ISSUE THREAD

**Issue by Albonycal** [pystardust/ani-cli#101]
https://gogoanime.vc/ is blocked by Govt. Of India (;-;)
![image](https://user-images.githubusercontent.com/67057319/139916381-36976906-5ff2-4785-865c-5e82618b6a73.png)
ISP: airtel xstream
I think we'll have to use another instance ??

**Comment by Dink4n** [comment]
This was fixed in #46. We're now scraping https://gogoanime.pe

**Comment by Albonycal** [comment]
:+1:
