### ISSUE TITLE
Name Anime

### ISSUE THREAD

**Issue by candrapersada** [pystardust/ani-cli#1014]
are there any options to use the name `Majin Bone Episode 40.mp4` like v3 from `ani-cli` without
```
name=majin-bone-episode-40-sub.mp4 mv $name "$( echo $name | sed -e 's/\(\w\)\(\w*\)-/\U\1\L\2 /g' -e 's/ sub//' )"
```

**Comment by port19x** [comment]
I have no idea what you're talking about

**Comment by candrapersada** [comment]
what I mean about the name of the anime
`ani-cli` v3 `Majin Bone Episode 40.mp4` in `ani-cli` v4 `majin-bone-episode-40-sub.mp4`

**Comment by candrapersada** [comment]
so I asked for an option to auto rename from `majin-bone-episode-40-sub.mp4` to `Majin Bone Episode 40.mp4`

**Comment by Derisis13** [comment]
Why this naming scheme and not any other?

I don't think we'll implement it unless it provides something extra (eg. trackma compatibility, like in previous versions). I suggest you use a bulk-renaming tool eg. Thunar (GUI) or mmv (cli)
