### ISSUE TITLE
Add options to change the current providers

### ISSUE THREAD

**Issue by prorounak2005** [pystardust/ani-cli#1017]
**Metadata (please complete the following information)**
Version: [e.g. 2.0.2] -> 4.0.3
OS: [e.g. Windows 10 / Linux Mint 20.3] ->  Arch Linux x86_64
Shell: [e.g. zsh, run `readlink /bin/sh` to get your shell] -> bash
Anime: [e.g. flcl] (if applicable) -> Koe no katachi / Silent voice (DUB)

**Describe the bug**
I want to watch Koe no katachi (silent voice) in dub but whenever I try to search for the anime using the `--dub` parameter. It shows the name of the anime but when I click on it, it doesn't launch mpv or vlc. Try it for yourself if you don't believe me. Koe no katachi (silent voice) dub version is already there in gogoanime.
**Steps To Reproduce**

1. Run the command `ani-cli --dub koe no katachi`
2. Choose both the links
3. The first link doesn't launch mpv or vlc and the second link says `Episode has not been released yet`.

**Expected behavior**
It should launch the mpv or vlc application.

**Screenshots (if applicable; you can just drag the image onto github)**
N/A

**Additional context**
The dub version of the anime is already there in gogoanime. We should have the option to change the current providers in ani-cli.

**Comment by port19x** [comment]
Was resolved in #1016

**Comment by candrapersada** [comment]
but not working for download like `ani-cli -d -e 1-12`
