### ISSUE TITLE
History does not store dub correctly

### ISSUE THREAD

**Issue by rakusan2** [pystardust/ani-cli#1022]
**Metadata**
Version: 4.0.8
OS: Ubuntu 22.04.1
Shell: dash
Anime: any dubbed

**Describe the bug**
History stores the same name as the sub version

**Steps To Reproduce**

1. Run `ani-cli overlord --dub`
2. Close player
3. Quit
4. Run `ani-cli -c`

**Expected behavior**
Should play the dub version

**Comment by Derisis13** [comment]
Not bug, feature. You can still play the dubbed version with the dub flag. This means you can switch between the two modes anytime.
If you only want to see the dubbed versions, I suggest taking a look at the environment variables in the man page
