### ISSUE TITLE
Episode not playing 

### ISSUE THREAD

**Issue by r4vanan** [pystardust/ani-cli#1025]
Steps to reproduce
1. ani-cli 
2. Search for one piece
3. Episode 818
 Tool says episode not released. But I think you know what I mean. One piece having 1000+ episode 
I am not trying to play dubbed version

Note:
It showing only for few episode then it shows again like that. I don't know it is tool problem or website problem please check this!

**Comment by Derisis13** [comment]
Is it dub or sub? Some episodes of one piece weren't dubbed at all iirc

**Comment by Derisis13** [comment]
Also please fill out an issue template, we can't do much without that information...

**Comment by RaynardGerraldo** [comment]
> Steps to reproduce
> 
>     1. ani-cli
> 
>     2. Search for one piece
> 
>     3. Episode 818
>        Tool says episode not released. But I think you know what I mean. One piece having 1000+ episode
>        I am not trying to play dubbed version
> 
> 
> Note: It showing only for few episode then it shows again like that. I don't know it is tool problem or website problem please check this!

website/api problem, its working again
