### ISSUE TITLE
Support --proxy

### ISSUE THREAD

**Issue by casualdegenerate** [pystardust/ani-cli#1029]
**Is your feature request related to a problem? Please describe.**
Is it possible you can add proxy support to ani-cli?
Whenever my ISP/Admin bans a site, I can't access it unless I use a proxy.

**Describe the solution you'd like**
Please add a param `--proxy [protocol://]host[:port]` (And please allow support for socks5 I'd prefer Tor)

**Describe alternatives you've considered**
? Nocom? (I don't understand what to write here. Just posting a feature I'd expect in this program.)

**Additional context**
I've looked at the source code, and it seems you use wget.
When doing `proxychains wget https://ident.me` it will use the proxy I set(which was socks5://127.0.0.1:9050 in this case)
Curious if you can check if the user set a proxy, and if they did you will proxychain the wget so they can circumvent censorship. 

Smiley face.

**Comment by Derisis13** [comment]
Is a network-wide proxy out of question? Seems much simpler than changing every web request... 
Alternative is to use a wps, some providers have free tiers which have plentyful resources for a vpn server

**Comment by port19x** [comment]
There might also be some terminal program that routes outgoing requests of a specific program through said proxy.
Implementing this here wouldn't make much sense
