### ISSUE TITLE
[windows] vlc not opening

### ISSUE THREAD

**Issue by UltimateLight** [pystardust/ani-cli#103]
after this:
![image](https://user-images.githubusercontent.com/63460105/139999894-5d28809c-757d-4d18-b392-8d4d25769b86.png)
it does nothing. vlc doesn't open or play anything.

also the downloading problem seems to be something wrong with gogoanime since some linux users seem to be facing the same issue too.

**Comment by Dink4n** [comment]
`vlc` didn't work for me either. I think it's better to use `mpv`
I already made a PR #38 for the download issue.

**Comment by UltimateLight** [comment]
the download issue is fixed now, but even after trying to use it with mpv, it's still not working, maybe I'm doing something wrong

**Comment by Dink4n** [comment]
What's you `setsid` version
```Console
setsid -V
```

If the version is lower than 2.32 `setsid` won't have the `-f` flag

**Comment by Dink4n** [comment]
How did you switch to mpv?

**Comment by UltimateLight** [comment]
> 
> 
> How did you switch to mpv?

I changed the `player_fn=vlc` in the ani-cli-win file to `player_fn=C:\Stuff\mpv\mpv.exe` and added the mpv folder to my windows environment path

**Comment by Dink4n** [comment]
Replace this line with
https://github.com/pystardust/ani-cli/blob/e22ab611c179c5c89876aaf2ef0b7d5afd2644e3/ani-cli-win#L248
This
```Console
$player_fn --http-header-fields="Referer: $embedded_video_url" "$video_url" >/dev/null 2>&1 &
```

**Comment by UltimateLight** [comment]
yoo it worked, thanks man

**Comment by DigitalNXZ** [comment]
@Dink4n hi! need some help here~
for me MPV doesn't open at all even by doing all this stuff here. (don't really like VLC since I know MPV)
1. player_fn="C:\Program Files (x86)\MPV\mpv.exe"
2. $player_fn --http-header-fields="Referer: $embedded_video_url" "$video_url" >/dev/null 2>&1 &
- Path Variables for system tried: C:\Program Files (x86)\MPV\ & once C:\Program Files (x86)\MPV\mpv.exe

Is there something wrong? any information I can provide? may u have an idea what the problem could be? ^^

best regards~

**Comment by Dink4n** [comment]
@DigitalNXZ How did you install `mpv`?

**Comment by Dink4n** [comment]
Hey @DigitalNXZ, Take a look at the GoGoAnime page for [Tian Yu](https://gogoanime.cm/category/tian-yu).
The episode count is weird :0

**Comment by DigitalNXZ** [comment]
> Hey @DigitalNXZ, Take a look at the GoGoAnime page for [Tian Yu](https://gogoanime.cm/category/tian-yu). The episode count is weird :/

OHHHH I SEE DAMN

Looked for the others I randomly chose and the most of them have similar problem holy..
Thats my bad and my luck lol
