### ISSUE TITLE
Ani-cli won't work with mpv installed from a different source in SteamDeck

### ISSUE THREAD

**Issue by DanSM-5** [pystardust/ani-cli#1030]
**Metadata (please complete the following information)**
Version: 4.0.3
OS: SteamOS 3.3.3
Shell: zsh
Anime: any

**Describe the bug**
I installed `mpv` through nix package manager and I get an error asking me to install the flatpack version of mpv.

```bash
Program "mpv (flatpak)" not found. Please install it.
```

**Steps To Reproduce**

1. Install nix package manager (requires to disable read-only file system for installation)
2. Install ani-cli `nix-env -iA nixpkgs.ani-cli`
3. Search for an anime `ani-cli vinland saga`

**Expected behavior**
ani-cli should allow using `mpv` from different sources in SteamDeck, not only mpv (flatpak).

**Additional context**
I think it could be worth adding an additional check for the presence of the `mpv` command for users that uses flatpak alternatives like nix or brew that can work in the read-only filesystem of steamdeck. I'd like to avoid installing a flatpak for the single use of ani-cli.

**Comment by Derisis13** [comment]
We didn't consider nix when implementing steamdeck support, however you can overwrite the default player by setting the environment variable `ANI_CLI_PLAYER` to `mpv` (eg. in your *shrc: `export ANI_CLI_PLAYER=mpv`). More info on available env vars can be found in the manpage

**Comment by DanSM-5** [comment]
I undestand. I can also confirm that the variable `ANI_CLI_PLAYER` is helping to override the default. Thanks for the help. I will close the ticket.

**Comment by candrapersada** [comment]
and how to keep using the settings `ANI_CLI_PLAYE` when updating `ani-cli`?

**Comment by 71zenith** [comment]
put it in ur shellrc(.bashrc/.zshrc) like `export ANI_CLI_PLAYER=mpv`

**Comment by candrapersada** [comment]
how to use shellrc(.bashrc/.zshrc in windows

**Comment by 71zenith** [comment]
`echo export ANI_CLI_PLAYER=mpv >> ~/.bashrc` run this in gitbash

**Comment by candrapersada** [comment]
why linux flatpak can"t use `export ANI_CLI_PLAYER=flatpak_mpv`?

**Comment by Derisis13** [comment]
> why linux flatpak can"t use `export ANI_CLI_PLAYER=flatpak_mpv`?

Could you ellaborate? If it's a separate issue, please open a new one for it.

**Comment by candrapersada** [comment]
what i mean is how to use ani-cli of flatpak mpv in linux

**Comment by Derisis13** [comment]
> what i mean is how to use ani-cli of flatpak mpv in linux

Please open a separate issue, fill in the template to provide context. I don't want to reopen this one.
