### ISSUE TITLE
ani-cli command scheduled with Windows' Task Scheduler won't work after v4 update

### ISSUE THREAD

**Issue by kuba300game** [pystardust/ani-cli#1033]
**Metadata (please complete the following information)**
Version: 4.0.3
OS: Windows 10 22H2
Shell: cmd/scoop
Anime: any [ for example "flcl" ]

**Describe the bug**
Before Animixplay was shut down, I had a scheduled task in Windows Task Scheduler that would run ani-cli once a week and download a new episode of the anime I was watching. After the v4 update, the script has completely broken down and is not finding any anime.

**Steps To Reproduce**

1. Run `ani-cli -a -1 -q best -d -p %USERPROFILE%/Downloads/ flcl`
2. It will return `No results found!`

**Expected behavior**
The script should work and automatically download new episode to provided location

**Screenshots (if applicable; you can just drag the image onto github)**
- Old script
![obraz](https://user-images.githubusercontent.com/57316323/218562576-816b6613-647b-44f0-a633-3e693c42d2ac.png)

- Script after some updates 
`ani-cli -e -1 -q best -d flcl`
![obraz](https://user-images.githubusercontent.com/57316323/218563086-cb39e532-fbeb-468a-bf5c-4d30edcc2839.png)

- Script when passing more than one argument in download
![obraz](https://user-images.githubusercontent.com/57316323/218563452-20a3eac2-f9f1-44b6-9aad-058264de1eaa.png)

**Additional context**
I've looked at available arguments and:
- the last episode argument `-e -1` returns `Episode not released!`,
- if more arguments are added, instead of automatic download it shows lists of anime, then after selecting it will start the download (with 1 argument works as it should),
- selecting download location argument doesn't even exists.

**Comment by Derisis13** [comment]
Getting the last episode with -1 is not implemented in v4. @justchokingaround do you think it's worth implementing?

**Comment by justchokingaround** [comment]
yes

**Comment by port19x** [comment]
Told ya `-1` was important :stuck_out_tongue: 

Btw `-q best` is default.
Awesome that you were able to use this for automation either way.
Was this hardcoded to run weekly or did you check for a new rss entry?

**Comment by kuba300game** [comment]
> Btw -q best is default.

Huh, good to know :)

The task was set to run at 5am every Sunday. So, yes, it was hardcoded.
