### ISSUE TITLE
No result found

### ISSUE THREAD

**Issue by docfaizal** [pystardust/ani-cli#1036]
[**Metadata]
![2023-02-16-184548_1366x768_scrot](https://user-images.githubusercontent.com/107258640/219376042-993f2301-f1cd-444b-a314-73f7784f1d6e.png)
Version: 4.0.9
OS: Gentoo
Shell: fish
Anime: Every

**Describe the bug**
No result found
**Steps To Reproduce**

1. Run `ani-cli (any anime)`

**Expected behavior**
there should be an episode selecting fzf menu

**Comment by breddie-is-rookie** [comment]
Experienced the same error, it was working fine a few hours ago

**Comment by CdRGit** [comment]
same error, was working fine yesterday

**Comment by Coregod360** [comment]
Experiencing the same issue any search comes back with no results found!

**Comment by trueauracoral** [comment]
I believe https://allanime.site is down. I can't access it.

**Comment by devraza** [comment]
Can confirm, allanime.site is down.
