### ISSUE TITLE
`-U` command Update "Connection Error"

### ISSUE THREAD

**Issue by nightwolf3140** [pystardust/ani-cli#1039]
**Metadata**
Version: 4.1.0
OS: Windows 10
Shell: Powershell
Anime: N/A

**Describe the bug**
When running script update command (ani-cli -U) it returns "Connection error"
It says something about an unsupported protocol, see screenshot.
![image](https://user-images.githubusercontent.com/125090843/219976361-7ab6721e-dc40-4125-8e10-cf6b2b8a9ee0.png)

**Steps To Reproduce**

1. Run `ani-cli -U`
**Expected behavior**
Script updated from GitHub

**Additional context**
Everything else works just fine.  I have also tried using my VPN however it did not change the outcome.
![image](https://user-images.githubusercontent.com/125090843/219976476-3be942d2-7f13-4ca1-a6ec-569c3712f458.png)

**Comment by Reaper176** [comment]
Note that uninstalling and reinstalling with 'yay -S ani-cli' fixes this issue and it becomes non-reproducible after

**Comment by FilipLac** [comment]
I have the same issue on terminal with ubuntu as a core...

**Comment by justchokingaround** [comment]
https://github.com/pystardust/ani-cli/commit/7f6740bbf1ca8215e1fa45ac97bfbc5c27192fee
should fix it
