### ISSUE TITLE
minimal install

### ISSUE THREAD

**Issue by RSerejo** [pystardust/ani-cli#1041]
any way to do a minimal install just to download ? or i will need to do a samba shared what will be a problem.

**Comment by justchokingaround** [comment]
you can't really go more minimal than this installation:
```sh
sudo curl -sL github.com/pystardust/ani-cli/raw/master/ani-cli -o /usr/local/bin/ani-cli &&
sudo chmod +x /usr/local/bin/ani-cli
```

**Comment by RSerejo** [comment]
> 

thanks but the main problem is the ffmpeg dependency, it was trying to install 600MB dependency like mesa, x11 etc.. i edited ani-cli script to don't asky for ffmpeg but it make the script broken.

**Comment by justchokingaround** [comment]
https://github.com/pystardust/ani-cli/blob/master/ani-cli#L326

in this line, just remove  `"ffmpeg"`  and it won't check for it being installed as a dependency

**Comment by RSerejo** [comment]
> 


it works, thanks
