### ISSUE TITLE
No anime is available

### ISSUE THREAD

**Issue by stonedseeker** [pystardust/ani-cli#1046]
**Metadata (please complete the following information)**
Version: 4.0.3
OS: Linux Vanilla OS 22.10
Shell: fish
Anime: All of them

**Describe the bug**
When i search for any anime, it searches for the dependencies and shows -> "no results found"

**Screenshots (if applicable; you can just drag the image onto github)**
![image](https://user-images.githubusercontent.com/93109628/220988688-2dc69ae0-3111-4ee0-9a38-4cc1a23ba29f.png)

**Additional context**

**Comment by 71zenith** [comment]
Update to the latest version
use `sudo ani-cli -U`

**Comment by pusherplayer** [comment]
happening to me as well not too sure if it has anything to do with the providers?

**Comment by 71zenith** [comment]
> happening to me as well not too sure if it has anything to do with the providers?

what version are u running?

**Comment by pusherplayer** [comment]
> what version are u running?
 4.0.5

**Comment by pusherplayer** [comment]
tried updating but gave me this error 
![Screenshot from 2023-02-23 18-04-32](https://user-images.githubusercontent.com/49151242/220992252-3839fbf3-447a-4dc6-b9f5-1bf74d872203.png)

**Comment by 71zenith** [comment]
install  `patch` through ur package manager

**Comment by pusherplayer** [comment]
> install `patch` through ur package manager


@71zenith  that worked, all good now, thanks a lot  GOAT.

**Comment by mirkokral** [comment]
> > install `patch` through ur package manager
> 
> @71zenith that worked, all good now, thanks a lot GOAT.

Please close this issue.
