### ISSUE TITLE
Choosing episode range after selecting anime

### ISSUE THREAD

**Issue by 4wojtek5** [pystardust/ani-cli#1049]
in version 3.4 you could select episode range after choosing anime, now in version 4 i need to choose before i select anime, so first i need to spot an anime episodes and then run second time ani-cli to select range for download. It's sometimes frustrating and i miss that feature.

**Comment by BeauTaapken** [comment]
i thought i would have the same issue, but you can just give a range like 1-9999999 and it will download all episodes and stop after it can't find a next one

**Comment by Derisis13** [comment]
You **can** choose an episode range after selecting an anime. If you hit `tab` on an episode number, it'll be selected for ranged download.  Select a second one, then press enter, everything in between will be downloaded. This is how fzf multi-select works, for more info see the manpage: `man fzf`.

**Comment by Derisis13** [comment]
> i thought i would have the same issue, but you can just give a range like 1-9999999 and it will download all episodes and stop after it can't find a next one

We were actually thinking of implementing a `first` and `last` episode to the program argument. Would it be any help to your usecase?

**Comment by port19x** [comment]
Or would you perhaps like a flag where you get prompted two times, once for first and once for last ep of the range?

**Comment by 4wojtek5** [comment]
sorry for late reply, Derisis13 I didn't know about fzf capabilities in this sort, and program argument would be nice, Thanks!
