### ISSUE TITLE
Queries made to the api not working

### ISSUE THREAD

**Issue by CaffeineB34r** [pystardust/ani-cli#1055]
**Metadata (please complete the following information)**
Version: 4.1.x
OS: Ubuntu 22.04.2 LTS/Windows 11
Shell: any
Anime: any

**Describe the bug**
  When calling the curl function to the allanime api it passes the hash: `1f0a5d6c9ce6cd3127ee4efd304349345b0737fbf5ec33a60bbc3d18e3bb7c61`
  argument of  persisted queries, but it only works with the hash:
`c4305f3918591071dfecd081da12243725364f6b7dd92072df09d915e390b1b7`

**Steps To Reproduce**
Maybe use a vpn to portugal. I've tried multiple computers and none of them work either, even in friend's houses, so seems like a location issue. 

**Expected behavior**
ani-cli will not find any anime until i `sed` the hash in, maybe just having `curl 1 || curl 2` or just have a variable for it.   

**Screenshots (if applicable; you can just drag the image onto github)**

![what its trying to curl](https://user-images.githubusercontent.com/62663698/224518884-e5a81e93-ffbb-4af0-9e2b-f53747deb0a6.png)
![different hash sections](https://user-images.githubusercontent.com/62663698/224518689-16f419a1-da9f-45da-bf99-c51d38440c97.png)

**Additional context**
solving this might also help some people with  #issue1050 but since it seems like a different thing i separated it
bellow are all the available hashes for the different sections here:
1. c4305f3918591071dfecd081da12243725364f6b7dd92072df09d915e390b1b7
2. 563c9c7c7fb5218aaf5562ad5d7cabb9ece03a36b4bc94f1384ba70709bd61da
3. 99bef954c5216ab07c37915fde39a29ff53e495b5d282dc01f70e5f864cf20a6

**Comment by CaffeineB34r** [comment]
at the time of writing I had managed to fix the search_anime by changing it's hash and i thought that would be goo enough, but the hashes are different
episode_list hash: `f73a8347df0e3e794f8955a18de6e85ac25dfc6b74af8ad613edf87bb446a854`
get_episode_url hash: `919e327075ac9e249d003aa3f804a48bbdf22d7b1d107ffe659accd54283ce48`

**Comment by CoolnsX** [comment]
Already gone through this...
It's not worthy..
Checkout 
#1054

**Comment by CaffeineB34r** [comment]
totally my bad, i had checked it out, but missed that it doesn't require hashes at all.
