### ISSUE TITLE
MPV not opening after selecting Ep - OpenSuse

### ISSUE THREAD

**Issue by santi014** [pystardust/ani-cli#106]
I have all the dependencies installed but its not opening.
#43 Pretty similar case but for Linux in this case.
![Screenshot_20211104_024740](https://user-images.githubusercontent.com/80226768/140264294-4332b7b9-4c6c-47c6-bb66-7d0f457c7486.png)
New to github sorry for any mistake

**Comment by Dink4n** [comment]
What is your version of `setsid`?
```Console
setsid -V
```

**Comment by santi014** [comment]
Hi its, util-linux 2.36.2

**Comment by Dink4n** [comment]
Add this flag `--log-file=debug.log` just before `--http-header-fields` in the script
https://github.com/pystardust/ani-cli/blob/babcc68a48705b67f593e2775286a95dcf2b072e/ani-cli#L255

Try to use `ani-cli` now. It should create a `debug.log` file
Can you print the contents of the file.

**Comment by kd00r** [comment]
I think I got some valuable information for you. I have the exact same problem as santi014. I added the flag `--log-file=debug.log` but the log was not to be found anywhere. After about 45 minutes of troubleshooting, I landed on changing the line to `setsid $player_fn --http-header-fields="Referer: $embedded_video_url" "$video_url" >/dev/null 2>&1 `

By removing the `-f` it now works properly for me. `-f ` doesn't seem to be a valid flag for `setsid`.

I have version `setsid from util-linux 2.31.1` running `Ubuntu 18.04` if that helps.

**Comment by santi014** [comment]
> Add this flag `--log-file=debug.log` just before `--http-header-fields` in the script
> 
> https://github.com/pystardust/ani-cli/blob/babcc68a48705b67f593e2775286a95dcf2b072e/ani-cli#L255
> 
> Try to use `ani-cli` now. It should create a `debug.log` file Can you print the contents of the file.
This is my debug.log
[debug.log](https://github.com/pystardust/ani-cli/files/7477617/debug.log)





> I think I got some valuable information for you. I have the exact same problem as santi014. I added the flag `--log-file=debug.log` but the log was not to be found anywhere. After about 45 minutes of troubleshooting, I landed on changing the line to `setsid $player_fn --http-header-fields="Referer: $embedded_video_url" "$video_url" >/dev/null 2>&1 `
> 
> By removing the `-f` it now works properly for me. `-f ` doesn't seem to be a valid flag for `setsid`.
> 
> I have version `setsid from util-linux 2.31.1` running `Ubuntu 18.04` if that helps.

I just try the recommended solution of kd00r but i didnt work for my bad luck

**Comment by kd00r** [comment]
santi014, could you verify that you have the non-free media decoders installed?
`Failed to initialize a decoder for codec 'h264'.` implies you do not.

**Comment by kd00r** [comment]
It's either that or your mpv was compiled without support for those.

See: https://github.com/mpv-player/mpv/issues/4087 for your error

**Comment by santi014** [comment]
FIXED
This post provided by kd00r
[https://forums.opensuse.org/showthread.php/522863-Tumbleweed-H264-Codec](url)
Command Used
`zypper addrepo -f http://packman.inode.at/suse/openSUSE_Tumbleweed/ packman
`
`zypper install vlc vlc-codecs k3b-codecs ffmpeg lame gstreamer-plugins-libav gstreamer-plugins-bad gstreamer-plugins-ugly gstreamer-plugins-good gstreamer-fluendo-mp3 libdvdcss2
`
`zypper dist-upgrade --from packman
`

**Comment by OishikGuha** [comment]
This is my debug.log file, I am trying to run steins;gate but for some reason it isn't playing
[debug.log](https://github.com/pystardust/ani-cli/files/7721914/debug.log)

**Comment by Vaisakhkm2625** [comment]
for me also not working... it just showing this
![image](https://user-images.githubusercontent.com/68694876/147500996-05cab3e4-57bf-46ec-9470-f5b853b9cf68.png)

**Comment by poiu477** [comment]
[debug.log](https://github.com/pystardust/ani-cli/files/7792202/debug.log)
I am also dealing with this, here is my debug log

**Comment by poiu477** [comment]
Just to note, ytfzf and other CLI video streamers work just fine, it's JUST ani-cli I am having difficulty with

**Comment by poiu477** [comment]
Nevermind I just needed to update I am a noob and a loser
