### ISSUE TITLE
Detective Conan supposed to have 1085 episode but it won't show in fzf menu

### ISSUE THREAD

**Issue by ttx99** [pystardust/ani-cli#1065]
![1](https://user-images.githubusercontent.com/95531944/225608703-35b82eb9-e6bf-408e-abec-d6c10582e4d3.png)
![3](https://user-images.githubusercontent.com/95531944/225609088-41ad185e-6f71-48dc-96b2-973ce1426556.png)
![2](https://user-images.githubusercontent.com/95531944/225608912-2af36440-bba2-47b1-94a2-abf8bacbb9f6.png)

**Comment by 71zenith** [comment]
The remaining episodes are point episodes
Try searching `.` in the search bar 
![image](https://user-images.githubusercontent.com/92977828/225611630-9e2301b9-8fd9-4694-b168-e666fc9ba4c6.png)
We didnt account for having multiple digits after the point. Therefore its not working currently. A fix will be pushed shortly

**Comment by ttx99** [comment]
selected 124.125 then this
![a](https://user-images.githubusercontent.com/95531944/225615049-17345168-0b37-4c8b-b3a7-bd45c678cb66.png)

**Comment by 71zenith** [comment]
>  We didnt account for having multiple digits after the point. Therefore its not working currently. A fix will be pushed shortly

**Comment by ttx99** [comment]
just a question how do I even episode 1085 where is that in the menu?

**Comment by 71zenith** [comment]
The total episode count accounts for point episodes as well. The latest episode as of now is 1076

**Comment by ttx99** [comment]
okay, copy.
