### ISSUE TITLE
Windows - Git Bash not needed? Instructions out of date?

### ISSUE THREAD

**Issue by Jammrock** [pystardust/ani-cli#1068]
**Metadata (please complete the following information)**
Version: 4.2
OS: Windows 11 22H2
Shell: Windows Terminal
Anime: N/A

**Describe the bug**

It appears that Git Bash is not needed anymore, and doesn't work. At least not in Windows 11 22H2 (the newest version for Linux users). But ani-cli works fine in PowerShell 7 via scoop.

**Steps To Install On Windows 11 22H2**

These steps might work on other versions of Windows with Terminal and PowerShell 7 installed. No git bash or WSL2 needed.

1. Open the Microsoft Store. Use the icon on the taskbar or Start > Microsoft Store.
2. Update all apps (Library (bottom left) > Update All or Get Updates). 
   a. [Win11 22H2] This step is needed to ensure that Windows Terminal is updated.
   b. [Older Windows] Use the store to install Windows Terminal and PowerShell.
   c. [Optional] Install PowerShell.
   c. CLI alternate: 
         i. Get "App Installer" from the Microsoft Store.
         ii. Open Windows PowerShell.
         iii. Install Windows Terminal and PowerShell through winget.

```powershell
winget install microsoft.powershell 
winget install microsoft.windowsterminal
```

Notes:
- To find your version of Windows run "winver" (if you know how), go to Settings > System > About, or press Win+X and select System from the menu.
- There are two versions of PowerShell. Windows PowerShell is the older, legacy version that is untested with ani-cli. PowerShell, or PowerShell 7, is the new version that is known to work with ani-cli. At least on Windows 11 it works.

3. Open Windows Terminal (Start menu, or Win+X > Terminal). Do not open as admin!
   a. [Recommended] The tab title should say PowerShell and not Windows PowerShell.
   b. Click the down arrow on the tab/title bar.
   c. Settings
   d. Use the "Default profile" drop down to change from Windows PowerShell to PowerShell. (Restart Terminal if PowerShell doesn't appear in the list.)
   e. Relaunch Terminal
4. Install scoop using the instructions from https://scoop.sh
5. Run the following commands to install all the required components:

```powershell
scoop install git
scoop bucket add extras
scoop install fzf mpv ani-cli
```

6. Run ani-cli and enjoy!

```powershell
ani-cli
```

**Expected behavior**
I guess git bash should work, but doesn't anymore...? At least on Windows 11 22H2. Not sure.

**Comment by port19x** [comment]
why do you need 7zip btw? That isn't a dependency of ours

**Comment by CoolnsX** [comment]
Well need to confirm with our tester

**Comment by Jammrock** [comment]
@port19x - 7zip is a dependency of mpv in scoop. It gets installed by mpv, so I kicked it out to the install command to prevent prompts.

@CoolnsX - Thanks! Let me know if the tester runs into any issues. Here's a screenshot of it working on my system.

![image](https://user-images.githubusercontent.com/5922742/225993217-cf13a4c5-7915-4047-85f6-b7c17e66bc66.png)

**Comment by Jammrock** [comment]
Or possibly you need Git Bash, but PowerShell in terminal can run bash shell scripts now... I'm not sure. I was kind of surprised to see a bash script running in PowerShell.

I'll have to build a clean VM and run some testing now.

**Comment by Jammrock** [comment]
Updated steps in OP. Confirmed working on a clean install of Win11 22H2.

Scoop requires git, that step was added.

It also works on Windows PowerShell. Though PowerShell is better, and I made that an optional step.

**Comment by port19x** [comment]
Could you elaborate on the difference between `Windows PowerShell` and `PowerShell`? Those sound like the same thing

**Comment by CoolnsX** [comment]
> Could you elaborate on the difference between `Windows PowerShell` and `PowerShell`? Those sound like the same thing

windows powershell as name implies comes as default with windows, which not updated and barebones..

the new Powershell is updated frequently..

kinda like cmd and terminal in windows.. 

Terminal in windows is better..  and supports other prompt like cmd, powershell etc

**Comment by Jammrock** [comment]
The story is a little complex. @CoolnsX has the gist of it. Here's the history lesson version.

Windows PowerShell is a Windows-only version of PowerShell. It's based on the Windows-only .NET Framework, through version 4.x. The final version of Windows PowerShell was 5.1. It's kept around in Windows for legacy purposes, because a lot of automation relies on it. 

Think of Windows PowerShell as Python 2. It's works well, lots of things still need it, but there is better and newer, like Python 3 out there.

When the .NET Core/Mono project came out, which is cross platform .NET, the PowerShell people decided to build new PowerShell on top of that and make it cross-platform. Where .NET goes, so does PowerShell. Thus PowerShell Core came and and was immediately shelved because it and .NET Core had to many backward incompatibility issues with legacy .NET and Windows PowerShell.

.NET Core was renamed to .NET with version 7, which caused PowerShell to drop the "Core" and move up to version 7. Version 7 focused on backwards compat first and foremost, then moved on to optimization and features. The current stable branch of .NET and PowerShell are 7.x. They are both cross platform (Windows, Linux, macOS) and with Windows Terminal, Windows now has a CLI tool that is close to, or in parity with, any Linux terminal.

Windows Terminal, as you might guess, was built to give people a terminal/MUX-like feel on Windows. It's a mutli-CLI terminal manager (PowerShell, Git Bash, WSL2, Azure Cloud, CMD, etc.) with support for all kinds of customizations and goodies. The combo of PowerShell (or pwsh for short) and Windows Terminal gives Windows a more *nix-like experience, which a lot of devs these days need.

Since Terminal and pwsh are built for cross platform, and Git includes bash, it appears that this allows ani-cli to run native on Windows. Which might be mildly mid-blowing. I know I was surprised. But here we are.

**Comment by Davestar2048** [comment]
No, Scoop installs Git Bash as a dependency for Ani-Cli. Git Bash is still needed as its what runs the script, not Terminal itself.

**Comment by Jammrock** [comment]
@Davestar2048 That was my assumption, too. 

It turns out scoop has a "shim" under scoop/shim/ani-cli.cmd. This launches the ani-cli shell script using bash. That turned out to be the magic sauce. Idk if the shim was created by ani-cli or scoop, but it's there.

```shell
@rem C:\Users\<user>\scoop\apps\ani-cli\current\ani-cli
@"C:\Users\jammr\<user>\apps\git\current\bin\bash.exe" "C:\Users\<user>\scoop\apps\ani-cli\current\ani-cli"  %*
```

Which explains why this works with either version of PowerShell. You still need git bash, but you don't have run ani-cli directly from the Git Bash shell.

**Comment by trueauracoral** [comment]
That makes a lot more sense. For me on windows 10 using powershell it didn't work.

**Comment by Jammrock** [comment]
@trueauracoral If you have Git bash installed and want to use PowerShell to launch ani-cli, without using scoop, you can do something like this. I tested this on Win11, but it should work on Win10.

- Install Windows Terminal (see OP).
- Open Windows Terminal.
- Set your preferred version of PowerShell (see OP).
- Install Git SCM for Windows, if not already installed: 
   - https://git-scm.com/downloads
   - OR ... use winget from PowerShell:
   - winget install git.git 
- Install fzf: ```winget install junegunn.fzf```
- Install mpv.
   - Install manually and add the mpv path to System or User path environment variable.
  
 https://sourceforge.net/projects/mpv-player-windows/files/

- Add bash to the user path
   ```powershell
   $userPath = [System.Environment]::GetEnvironmentVariable('path', 'User')
   $userPath = "$userPath;%ProgramFiles%\Git\bin"
   [System.Environment]::SetEnvironmentVariable('path',$userPath, 'User')
   ```

- Edit your PowerShell profile.
   - Run this command: ```notepad $PROFILE```
   - Or, if you have vscode installed: ```code $PROFILE```
-  Add this to your PowerShell profile:

```powershell
function get-ani-cli {
   $anicliURI = 'https://raw.githubusercontent.com/pystardust/ani-cli/master/ani-cli'
   $anicliPath = "$env:LocalUserData\ani-cli"
   $null = mkdir "$anicliPath" -Force

   Invoke-WebRequest $anicliURI -OutFile "$anicliPath\ani-cli"
}

function ani-cli {
   $anicliPath = "$env:LocalUserData\ani-cli"
   bash "$anicliPath\ani-cli" $args
}
```

- Relaunch terminal for the new profile and path variable to apply.
- Download the latest ani-cli with this command: ```get-ani-cli```
- Run ani-cli with this command: ```ani-cli```b

I can script the entire process out and send in a PR, if people are interested. The ani-cli function would need some TLC to handle arguments properly.

**Comment by port19x** [comment]
> @Davestar2048 That was my assumption, too.
> 
> It turns out scoop has a "shim" under scoop/shim/ani-cli.cmd. This launches the ani-cli shell script using bash. That turned out to be the magic sauce. Idk if the shim was created by ani-cli or scoop, but it's there.
> 
> ```shell
> @rem C:\Users\<user>\scoop\apps\ani-cli\current\ani-cli
> @"C:\Users\jammr\<user>\apps\git\current\bin\bash.exe" "C:\Users\<user>\scoop\apps\ani-cli\current\ani-cli"  %*
> ```
> 
> Which explains why this works with either version of PowerShell. You still need git bash, but you don't have run ani-cli directly from the Git Bash shell.

It's from scoop

**Comment by ttx99** [comment]
Just a question. Is it even possible to use alias for commands in windows 10/11 just like in bashrc in linux?

**Comment by Jammrock** [comment]
@ttx99 Yes! Two options.

For something more complex use a function. A function being a names block of code (scriptblock data type in pwsh). See my posts above for an example.

For a regular alias use New-Alias, or its alias "nal".

https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/new-alias?view=powershell-7.3

To change an alias use Set-Alias, or the alias sal.

https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/new-alias?view=powershell-7.3


Aliases are why you can use Get-ChildItem (the core pwsh cmdlet), gci, dir, or ls to get the contents of a directory.

```powershell
Get-Alias -Definition Get-Childitem

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Alias           dir -> Get-ChildItem
Alias           gci -> Get-ChildItem
Alias           ls -> Get-ChildItem
```

**Comment by vvirtues** [comment]
I never used git bash for ani-cli except for when I had to use the fuk-allanime branch. Even the update after that, I still don't use it and only use Terminal (Powershell)
