### ISSUE TITLE
Search results caps at 40 results

### ISSUE THREAD

**Issue by breddie-normie** [pystardust/ani-cli#1070]
Version: 4.2.1
OS: Artix Linux
Shell: fish
Anime: Monster

Search results are capped at 40 results. No more results is found. This is problematic when I am trying to watch anime whose name is pretty ubiqutous and buried under 50 results. In my case, Monster anime is not found in first 40 results (which is taken over by pokemon and digimon). To your info, it is available in allanime.to

1. Run `ani-cli Monster`
2. You get it

Expected behavior: Should display more results, so I can choose the right one

![image](https://user-images.githubusercontent.com/127048853/226416493-03037db6-c1c6-48aa-ad26-bdb483041ee1.png)

**Comment by port19x** [comment]
As a workaround you might use the Japanese name for such anime.
Not sure if we can or should fix this. 
Depends on whether we arbitrarily cut off search results at 40, or the endpoint doesn't give us more.

**Comment by CoolnsX** [comment]
it's the endpoint max limit of results
we can't go any further

**Comment by 71zenith** [comment]
specifically in the case of monster, u can search for `monster 2004` and it will select the original anime

**Comment by breddie-normie** [comment]
> specifically in the case of monster, u can search for `monster 2004` and it will select the original anime

Thanks, it works now
