### ISSUE TITLE
Bump to guru overlay

### ISSUE THREAD

**Issue by TheRealOne78** [pystardust/ani-cli#1073]
Can we get newest ani-cli version on the guru overlay please? 👉👈

**Comment by trueauracoral** [comment]
I searched up twitch guru and got https://www.twitch.guru/ . Do you want to basically stream ani-cli interactively on twitch or something? Who's stopping you except for twitch and copyright.

**Comment by TheRealOne78** [comment]
No, the Gentoo Overlay. I tought it's clear enough, sorry.

[![Packaging status](https://repology.org/badge/vertical-allrepos/ani-cli.svg?minversion=4.0)](https://repology.org/project/ani-cli/versions)

It's still at 4.0, which ofc doesn't work

**Comment by port19x** [comment]
Is there a way to contact the maintainer?
Let me see if I can dig up a contact on my end

**Comment by port19x** [comment]
I pinged him, should be fixed soon-ish, idk depends on him

**Comment by medanisjbara** [comment]
Hey @TheRealOne78, I apologize for not keeping the ebuild on guru up to date, but I wanted to let you know that it should be available soon once the dev branch is merged to master. In the meantime, you can still use the 9999 ebuild, which is always up to date and should work fine. Let me know if you have any questions or concerns!

Also, sorry for the late response.

**Comment by TheRealOne78** [comment]
Oh nice, thanks. Also thanks for letting me know that there's a 9999 version as well, that's pretty useful.

**Comment by medanisjbara** [comment]
@port19x feel free to close the issue now.

**Comment by medanisjbara** [comment]
The 9999 ebuild is visible on `https://repology.org/project/ani-cli/versions` but not the status badge. @port19x I'm not sure if it's possible to make it visible. 

If it's possible, can you please add it ? Otherwise I will submit a PR that adds gentoo installation instructions to the README.md with a small note about this (Same as the arch section in the README.md)

**Comment by port19x** [comment]
> The 9999 ebuild is visible on `https://repology.org/project/ani-cli/versions` but not the status badge. @port19x I'm not sure if it's possible to make it visible.
> 
> If it's possible, can you please add it ? Otherwise I will submit a PR that adds gentoo installation instructions to the README.md with a small note about this (Same as the arch section in the README.md)

This is likely due to caching. Wait a few hours

**Comment by port19x** [comment]
In fact it already updated.
It's githubs image caching at work

**Comment by TheRealOne78** [comment]
> This is likely due to caching. Wait a few hours
> In fact it already updated. It's githubs image caching at work

I believe medanisjbara was referring to the fact that even if the version 9999 exits in [https://repology.org/project/ani-cli/versions](https://repology.org/project/ani-cli/versions), the version 9999 does not get displayed in github's native packages image.

![image](https://user-images.githubusercontent.com/53640879/229349017-79362d33-2430-40de-bd36-a3536f9c8032.png)

![image](https://user-images.githubusercontent.com/53640879/229349038-73787d55-0ffc-4148-aef3-2192732c3cb5.png)

**Comment by medanisjbara** [comment]
Correct. That's what I meant. But since that's also the case with ani-cli-git on the AUR (in the case of arch). I guess there's nothing to do about this.
