### ISSUE TITLE
is not able to downlad episode 650 one piece (dub) 

### ISSUE THREAD

**Issue by yash-10x** [pystardust/ani-cli#1078]
**Metadata (please complete the following information)**
Version: [4.2.1]
OS: [WSL ubuntu 20.24]
Shell: [bash]
Anime: one piece(dub)
episode 650
**Describe the bug**
Downloading is broken.

![Screenshot (2)](https://user-images.githubusercontent.com/98729131/229338944-a5932319-1c19-47ca-94bd-39e4361d3893.png)

**Comment by RubenPonce** [comment]
Looks like it's working now. 
![image](https://user-images.githubusercontent.com/43939942/230254767-0b3dd31d-70b3-430e-956d-024a2fc9acef.png)

**Comment by port19x** [comment]
Works for me too
![2023-04-06_06-42](https://user-images.githubusercontent.com/82055622/230273832-38803e37-1489-489b-af22-6adfa3fef682.png)

**Comment by yash-10x** [comment]
Thank you
