### ISSUE TITLE
Anime sources return unplayable links

### ISSUE THREAD

**Issue by nondotxyz** [pystardust/ani-cli#1085]
**Metadata (please complete the following information)**
Version: 4.2.1
OS: Arch Linux
Shell: Zsh
Anime: Onimai

**Describe the bug**
While watching the episode 6 and specifically episode 6 of onimai, it seems there's not many sources that provided the episode and one of the sources (either vrv or gogoanime couldn't tell) are returning an invalid link to play. After inspecting on vlc which provides error log output, vlc is trying to load a file with the m3u8 extension.
I'm surprised there's no countermeasure on unplayable links, since you know, you can't trust the sources sometimes.
This issue is quite hard to identify with no presence of a verbose flag or any logging file that I'm aware of.

**Steps To Reproduce**

1. Run `ani-cli -v onimai`
2. Choose episode 6 

**Expected behavior**
The episode would run just fine on mpv and vlc

**Additional context**

**Comment by realitymolder** [comment]
> > **Metadata (please complete the following information)** Version: 4.2.1 OS: Arch Linux Shell: Zsh Anime: Onimai
> > **Describe the bug** While watching the episode 6 and specifically episode 6 of onimai, it seems there's not many sources that provided the episode and one of the sources (either vrv or gogoanime couldn't tell) are returning an invalid link to play. After inspecting on vlc which provides error log output, vlc is trying to load a file with the m3u8 extension. I'm surprised there's no countermeasure on unplayable links, since you know, you can't trust the sources sometimes. This issue is quite hard to identify with no presence of a verbose flag or any logging file that I'm aware of.
> > **Steps To Reproduce**
> > ```
> > 1. Run `ani-cli -v onimai`
> > 
> > 2. Choose episode 6
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > **Expected behavior** The episode would run just fine on mpv and vlc
> > **Additional context**
> 
> Our verbose flag is `sh -x ani-cli`. That generates plenty of helpful output tracing the whole program execution. Putting that in a pastebin is a great way to give us more relevant data to investigate.

https://pastebin.com/4ax69PG3
command was : `sh -x ani-cli ani-cli one piece`

**Comment by nondotxyz** [comment]
> > **Metadata (please complete the following information)** Version: 4.2.1 OS: Arch Linux Shell: Zsh Anime: Onimai
> > **Describe the bug** While watching the episode 6 and specifically episode 6 of onimai, it seems there's not many sources that provided the episode and one of the sources (either vrv or gogoanime couldn't tell) are returning an invalid link to play. After inspecting on vlc which provides error log output, vlc is trying to load a file with the m3u8 extension. I'm surprised there's no countermeasure on unplayable links, since you know, you can't trust the sources sometimes. This issue is quite hard to identify with no presence of a verbose flag or any logging file that I'm aware of.
> > **Steps To Reproduce**
> > ```
> > 1. Run `ani-cli -v onimai`
> > 
> > 2. Choose episode 6
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > **Expected behavior** The episode would run just fine on mpv and vlc
> > **Additional context**
> 
> Our verbose flag is `sh -x ani-cli`. That generates plenty of helpful output tracing the whole program execution. Putting that in a pastebin is a great way to give us more relevant data to investigate.

Quite expected that there be an implemented debug function, despite the -x flag being on my perspective totally unreadable but this works too.

https://pastebin.com/VUzUT7Jx
`sh -x ani-cli onimai`

**Comment by rbjnazz** [comment]
also invalid links on one piece episode 1057 1058
`https://www049.vipanicdn.net/streamhls/0b594d900f47daabc194844092384914/ep.1057.1681007207.m3u8: Server returned 403 Forbidden (access denied)`

**Comment by CoolnsX** [comment]
this issue is fixed in PR #1165, as I can see the links playing.

**Comment by CoolnsX** [comment]
fixed in PR #1171
