### ISSUE TITLE
Correct the number of available episodes of seasonal anime titles from history when watching it

### ISSUE THREAD

**Issue by andrempiva** [pystardust/ani-cli#1088]
While watching seasonal anime over its release, the number of available episodes end up displaying the wrong number.

It is common to have an anime title saved on the history with the number of episodes of when you first started watching it, and have it show nonsensical information after a couple weeks.
For example: `Isekai Nonbiri Nouka (8 episode) - episode 11`

It would be convenient if the title updated with the right number of episodes when watching the anime with the `-c` option.

I've looked into doing it myself but I wasn't able to, so now I'm hoping if a more experienced member of the community would like to take a look into this.
Thanks!

**Comment by andrempiva** [comment]
It seems the pluralization of `episode` is also a hit or miss. Half of my history has the wrong pluralization. The example above is copied from my history but it should have displayed `(8 episodes)` and not `(8 episode)`.

But I don't know if this was corrected previously and this is just an artifact of the previous bug or not.

**Comment by Derisis13** [comment]
I think this is possible with rewriting the regex in `update_history`, although that won't update the title until you actually play the episode. I'll look into the possibility of doing it when fetching the history entry
