### ISSUE TITLE
Pls add progress bar while using -d

### ISSUE THREAD

**Issue by cezkot** [pystardust/ani-cli#109]
A progress bar would be very useful. You know, especially when you want to download something larger than 20 min ep like full movie.

**Comment by r4vanan** [comment]
i got resolved this but i dont know how to send to the developer

**Comment by jnishwanth** [comment]
@r4vanan ,

1.  Fork this repository (pystardust/ani-cli)
2. Make changes to the repository in your account now (r4vanan/ani-cli)
3. Send a pull request

**Comment by r4vanan** [comment]
done

**Comment by jnishwanth** [comment]
PR #113 
Very cool! But I would have preferred not to have any more dependencies, so is it possible to make a simple script which will do the same? Let me know if that might be a worse off solution.

**Comment by r4vanan** [comment]
just now i am try to one

**Comment by r4vanan** [comment]
there is python file to do that so i added another one try that

**Comment by r4vanan** [comment]
i think its can done with makefile

**Comment by Haikal-Ravendy** [comment]
PR #113 
I tried using it locally but it keep giving me "ffpb: command not found" 
I have already edited my makefile. I also even do "pip install --user ffpb" manually but still doesn't work

**Comment by r4vanan** [comment]
can you show me that errror as screenshot please
if you dont mind

**Comment by Haikal-Ravendy** [comment]
> can you show me that errror as screenshot please if you dont mind export PATH=${PATH}:~/.local/bin may be it will help

this is what I have done

**makefile**
![image](https://user-images.githubusercontent.com/55172693/144352095-7ebde61d-eb1c-4b14-8544-2c42cea4c778.png)

**ani-cli-win**
![image](https://user-images.githubusercontent.com/55172693/144352282-5874d6aa-af56-4b16-9814-1b84ddd8d866.png)

and this is the error that I got
![image](https://user-images.githubusercontent.com/55172693/144352505-2aa35217-697c-4df4-b483-473e9fc2db1a.png)

**Comment by jnishwanth** [comment]
> Where should I add that to?
Pretty sure you should add that to your `.bashrc` file in your home directory.

**Comment by Haikal-Ravendy** [comment]
> Pretty sure you should add that to your .bashrc file in your home directory.
That is weird, I can't find the `.bashrc` in my ani-cli-win home directory

**Comment by jnishwanth** [comment]
Oh wait im being stupid here. You are using windows, u wont have bash anywhere. Not sure how to proceed in that case. Maybe @r4vanan can help.

**Comment by r4vanan** [comment]
> > Pretty sure you should add that to your .bashrc file in your home directory.
> 
> That is weird, I can't find the `.bashrc` in my ani-cli-win home directory. I am using this in windows
> 

In your home/user directory

**Comment by r4vanan** [comment]
> > Pretty sure you should add that to your .bashrc file in your home directory.
> 
> That is weird, I can't find the `.bashrc` in my ani-cli-win home directory. I am using this in windows
> 
    I dont know about windows i created for linux.

**Comment by Haikal-Ravendy** [comment]
> > > Pretty sure you should add that to your .bashrc file in your home directory.
> > 
> > 
> > That is weird, I can't find the `.bashrc` in my ani-cli-win home directory. I am using this in windows
> 
> ```
> I dont know about windows i created for linux.
> ```

Ah, that's fair. I thought that would work for windows too. Cheers

**Comment by r4vanan** [comment]
Dont worry i will try one thing for windows

**Comment by ura43** [comment]
This is a pretty good idea for an optional dependency. Like mentioned above, make a PR and I'll likely merge it

**Comment by ura43** [comment]
Solved by #165
