### ISSUE TITLE
cant install on pop os

### ISSUE THREAD

**Issue by AmethystAimi** [pystardust/ani-cli#1091]
i cant install it on pop os and when i run the install command for the debian as pop os is debian based it doesnt work

**Comment by AmethystAimi** [comment]
![image](https://user-images.githubusercontent.com/79480486/232556666-04f80f80-8491-43eb-8749-b6050825d323.png)

**Comment by 71zenith** [comment]
PopOS is not directly based on Debian, hence it doesn't share the same repositories. It has its own repos. You can try installing ani-cli by the manual method

**Comment by AmethystAimi** [comment]
Thank you
