### ISSUE TITLE
unable to upgrade to fedora 38

### ISSUE THREAD

**Issue by carlosgermanhurtado** [pystardust/ani-cli#1093]
**Metadata (please complete the following information)**
Version: 4.2
OS:fedora 38
Shell: bash
Anime: 

**Describe the bug**
when updating system via dnf get error 404 for the Corp repo for ani-cli

**Steps To Reproduce**

run sudo dnf update

**Expected behavior**
update system

error appears as follows:"Copr repo for ani-cli owned by derisis13        219  B/s | 341  B     00:01    
Errors during downloading metadata for repository 'copr:copr.fedorainfracloud.org:derisis13:ani-cli':
  - Status code: 404 for https://download.copr.fedorainfracloud.org/results/derisis13/ani-cli/fedora-38-x86_64/repodata/repomd.xml (IP: 2600:9000:250c:7e00:4:bbc1:1840:93a1)
Error: Failed to download metadata for repo 'copr:copr.fedorainfracloud.org:derisis13:ani-cli': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
"

**Comment by 71zenith** [comment]
Please try again. We've added a package for Fedora 38

**Comment by carlosgermanhurtado** [comment]
Thank you for the update. The manual install worked for me in the mean time.
