### ISSUE TITLE
iSH workaround with raspberry pi

### ISSUE THREAD

**Issue by nightwolf3140** [pystardust/ani-cli#1094]
So its known that theres no iOS support through iSH or other emulators. https://github.com/pystardust/ani-cli/issues/988

**Description of the workaround**

So ive made a really stupid workaround that involves a headless raspberry pi with ani-cli installed with ssh enabled. Using a bash script in iSH it ssh's to the server where you use ani-cli like normal and it downloads it to a and copies it locally to iSH's directory

```bash
#!/bin/bash

# Define variables for SSH connection and remote file location
remote_host="your_remote_host"
remote_user="your_remote_user"
remote_file_path="path_to_remote_file"
local_dir_path="path_to_local_directory"

# SSH into remote server and execute ani-cli command to select episode and download video
ssh -t $remote_user@$remote_host "ani-cli"

# SCP the downloaded files from remote server to local folder
scp -r $remote_user@$remote_host:$remote_file_path $local_dir_path
```
got help from chat-gpt cause im not great with bash (but it works)

**Additional context**
This is not a real solution for everyone and its why im calling it a workaround

**Comment by Derisis13** [comment]
so you can move files out of iSH into shared storage?

**Comment by Lockl00p** [comment]
I added support for iSH into the script itself. If my PR doesn't get approved, you can check my repo I guess.
