### ISSUE TITLE
Episodes not released yet!

### ISSUE THREAD

**Issue by Mason-17** [pystardust/ani-cli#1095]
**Metadata (please complete the following information)**
Version: [e.g. 4.2]
OS: [Alyx (Arch)]
Shell: [zsh]
Anime: [All of them]

**Describe the bug**
Can't watch anything. I get to the series selection page, but after I select a series, it says episodes haven't been released yet.

**Steps To Reproduce**

1. Run `ani-cli`
2. Search any anime
3. Select any of the options 

**Expected behavior**
Watch anime

**Screenshots (if applicable; you can just drag the image onto github)**
![image](https://user-images.githubusercontent.com/82055622/151030428-2e78d15f-4ba9-4d86-b6f3-8307557b4b29.png)

**Additional context**

**Comment by 71zenith** [comment]
what version are u running?
use `ani-cli -V`

**Comment by Mason-17** [comment]
> what version are u running?
> 
> use `ani-cli -V`

I'm using 3.2.2, which actually spawns another issue: running `sudo ani-cli -U` updates the software, but it is no longer usable. Trying to run ani-cli post update reports that ani-cli isn't in /bin

**Comment by 71zenith** [comment]
Ye, so actually we reverted back from the modular file approach. So your best bet is to reinstall the program completely either from ur package manager (if it has ani-cli) or just by cloning the repo
```bash
sudo rm -rf "/usr/local/share/ani-cli" "/usr/local/bin/ani-cli" "/usr/local/bin/UI" /usr/local/bin/player_* #If some of these aren't found, it's not a problem
git clone "https://github.com/pystardust/ani-cli.git"
sudo cp ani-cli/ani-cli /usr/local/bin
rm -rf ani-cli
```

**Comment by Mason-17** [comment]
> Ye, so actually we reverted back from the modular file approach. So your best bet is to reinstall the program completely either from ur package manager (if it has ani-cli) or just by cloning the repo
> 
> ```bash
> 
> sudo rm -rf "/usr/local/share/ani-cli" "/usr/local/bin/ani-cli" "/usr/local/bin/UI" /usr/local/bin/player_* #If some of these aren't found, it's not a problem
> 
> git clone "https://github.com/pystardust/ani-cli.git"
> 
> sudo cp ani-cli/ani-cli /usr/local/bin
> 
> rm -rf ani-cli
> 
> ```

I'll try cloning the repo, since I've already tried re-installing via yay

**Comment by Mason-17** [comment]
Issue persists, even after following your instructions

**Comment by Mason-17** [comment]
Nevermind it works! Thanks a bunch
