### ISSUE TITLE
SEARCH ANIME  FUNCTION DOES NOTHING

### ISSUE THREAD

**Issue by landon1433** [pystardust/ani-cli#1097]
**Metada**Metadata (please complete the following information)*ta (please complete the following information)**
Version: [e.g. 2.0.2]
OS: Windows 10
Shell: gitbash
Anime: Any

**Describe the bug**
whenever i go to choose what anime i want to search i dont get anything and I'm not sure if im putting something in wrong or missing something

**Steps To Reproduce**

1. Run ani-cli
2. Choose Anime: One Piece
3. *Nothing Happens*

**Expected behavior**
Pull up an episode list or some way to choose an episode of One Piece

**Screenshots (if applicable; you can just drag the image onto github)**

![image](https://user-images.githubusercontent.com/62925676/233874789-6c293698-72d6-4b5a-b5c0-651af1e075f0.png)

**Comment by Derisis13** [comment]
[this](https://github.com/pystardust/ani-cli#Windows)

**Comment by port19x** [comment]
please reopen should your issues persist
