### ISSUE TITLE
Use mpv's playlist feature

### ISSUE THREAD

**Issue by obj-obj** [pystardust/ani-cli#1098]
Using mpv's playlists allow selecting the episode inside mpv, while also removing the need for the episode selector or continue option (as mpv will remember its position in the playlist)

I may make a PR for this when I have time

**Comment by port19x** [comment]
> Using mpv's playlists allow selecting the episode inside mpv, while also removing the need for the episode selector or continue option (as mpv will remember its position in the playlist)
> 
> I may make a PR for this when I have time

This is feasible for range selection with the only reason for us not using it for that being that we pass all links as args for now.

I believe you imply we should use mpv playlists by default for everything else too.
This isn't feasible, as we need to request links on a per-episode basis, the links have a short lifetime and spamming allanime with requests would be rude

**Comment by obj-obj** [comment]
> > Using mpv's playlists allow selecting the episode inside mpv, while also removing the need for the episode selector or continue option (as mpv will remember its position in the playlist)
> > I may make a PR for this when I have time
> 
> This is feasible for range selection with the only reason for us not using it for that being that we pass all links as args for now.
> 
> I believe you imply we should use mpv playlists by default for everything else too. This isn't feasible, as we need to request links on a per-episode basis, the links have a short lifetime and spamming allanime with requests would be rude

Ah, yeah that's an issue

**Comment by obj-obj** [comment]
A workaround would probably be hosting a local web server and only fetching the url from allanime when a request is made to that server, but hosting a web server is kind of overcomplicated

**Comment by Derisis13** [comment]
I did try to implement this at one point, but it would have been only possible with major compromises. My biggest issue was that playlists would have been implemented differently for each player, and with the old codebase that would have been very difficult. I might revisit the idea, to see if it's better after the 4.0.0 rewrite but no promises
