### ISSUE TITLE
[Feature Request] Please make the search box available within script..

### ISSUE THREAD

**Issue by CoolnsX** [pystardust/ani-cli#11]
You can check the link provided below... I have done some forking into your script like:
1. make the search available within script at start and after watching an anime...
2. changed the media player to vlc..

P.S. = I am very new to shell scripting so please ignore the errors...
[Link](https://github.com/CoolnsX/ani-cli-vlc)

**Comment by pystardust** [comment]
I have added the search box within script and the ability to change the video player

9792a65144a6dc1f883f031312665ada27acec91
