### ISSUE TITLE
ani-cli -c stuck on "Checking dependencies..."

### ISSUE THREAD

**Issue by JustGerard** [pystardust/ani-cli#1100]
**Metadata (please complete the following information)**
Version: 4.2.2
OS: Pop!_OS 20.04
Shell: zsh
Anime: Bleach

**Describe the bug**
After playing some episodes, for example with `ani-cli bleach -e "1 -1"` and stopping. If you run `ani-cli -c` it shows `Checking dependencies...` and doesn't do anything.

![image](https://user-images.githubusercontent.com/23108448/234262469-546abd30-b665-4e20-871a-8f77976b9c2e.png)

**Steps To Reproduce**

1. Watch some episodes of an anime
2. Stop the script
3. Run `ani-cli -c`

**Expected behavior**
`ani-cli -c` should continue playing next episode from history.

**Comment by JustGerard** [comment]
`fzf --version` gives me `0.20.0`

**Comment by Medvednavel** [comment]
I also had this bug on archlinux latest ```ani-cli-git ``` version of the package from AUR, I was able to fix it by replacing it with regular ```ani-cli``` package.

**Comment by Derisis13** [comment]
I could reproduce the issue, I'll see what I can do

**Comment by Derisis13** [comment]
Found the issue, there was something "lost in translation"...
This:
```sh
read -r ep_no id title <<-EOF
		$result
	EOF
```
became this
```sh
        read -r ep_no id title result
```
ofc it won't run.
