### ISSUE TITLE
m3u8 files that do not have m3u8 in the name are ignored and will fail to download

### ISSUE THREAD

**Issue by RubenPonce** [pystardust/ani-cli#1108]
**Metadata**
Version: [4.2.5]
OS: [PopOS]
Shell: [bash]
Anime: [Kono Subarashii Sekai ni Bakuen wo!]

**Describe the bug**
When the `download` method receives an m3u8 file without m3u8 in the name, it defaults to aria2c and fails.

**Steps To Reproduce**

1. Run `ani-cli -d -S 1 -e 1 kono-subarashii`
2. The mp4 downloaded will be an HLS playlist
3. The file aria2c attempts to download in this example is `https://news.kaavid.lol/st/ep_JhgwqSa9KnTMLhhjz_1_sub`

**Expected behavior**
There needs to be logic to check if the url is an m3u8 other than checking the extension.

**Screenshots**
![image](https://user-images.githubusercontent.com/43939942/236288041-97f80afc-2654-4717-a346-9a58b148fe97.png)

**Comment by port19x** [comment]
Can confirm the issue
