### ISSUE TITLE
Script Not Working!

### ISSUE THREAD

**Issue by sarveshhiwase** [pystardust/ani-cli#111]
When I choose an anime with a episode number it's just prints getting data for episode number and stays like that forever...
Can anyone tell what's the reason?
![Screenshot from 2021-11-06 09-04-22](https://user-images.githubusercontent.com/69983214/140596641-6362ff1a-2bda-4e3b-8212-117eaba877f2.png)
Nothing really happens, neither the mpv is working nor vlc..

**Comment by Dink4n** [comment]
Possible duplicate of #106

**Comment by sarveshhiwase** [comment]
Thanks buddy #106  helped me solving my bug..
if -f flag in setsid..
i removed now everything is working fine.
