### ISSUE TITLE
Can't find the dubs

### ISSUE THREAD

**Issue by HiddenLeveI** [pystardust/ani-cli#1110]
**Metadata (please complete the following information)**
Version: [Most recent]
OS: [e.g. Pop_OS!]
Shell: Dash
Anime: [All of them)

**Describe the bug**
I can't find out to access the dubs. Every anime for me is a sub and I can't find no dub anime anywhere. I even searched for an anime that I KNEW had dubs (because of the YT video that I watched, showing they had dubs on this app) yet I only found the sub for them as well. Is there a certain setting that I need?

**Steps To Reproduce**

1. Run `ani-cli -d flcl`
2. Choose 2 (fooly-cooly)
3. Choose episode 1

**Expected behavior**
Downloading should work

**Screenshots (if applicable; you can just drag the image onto github)**
![image](https://user-images.githubusercontent.com/82055622/151030428-2e78d15f-4ba9-4d86-b6f3-8307557b4b29.png)

**Additional context**

**Comment by HiddenLeveI** [comment]
Linux won't let me drag and drop the video I took into here and I don't know how to upload it through the website.

**Comment by wcrabtree9** [comment]
You need to add --dub to get the dubs. So this should work:
`ani-cli -d --dub flcl`

**Comment by port19x** [comment]
I highly doubt you're using the latest version.
Your screenshot implies you're running sth before v4
![2023-05-06_09-39](https://user-images.githubusercontent.com/82055622/236610331-a42e6a0d-43d7-404a-9c66-f7db8565c5cd.png)

**Comment by HiddenLeveI** [comment]
> I highly doubt you're using the latest version. Your screenshot implies you're running sth before v4 ![2023-05-06_09-39](https://user-images.githubusercontent.com/82055622/236610331-a42e6a0d-43d7-404a-9c66-f7db8565c5cd.png)

that screenshot was there automatically, I can't figure how to upload the video I took because dragging and dropping the video doesn't do anything.

**Comment by HiddenLeveI** [comment]
> You need to add --dub to get the dubs. So this should work: `ani-cli -d --dub flcl`

so I don't actually have the ani-cli command. I couldn't figure out how to download it on pop_os so I ended up downloading the file through Githubs website, and now I have to change my directory and run ./ani-cli for it to work. So I can't do that command.

**Comment by HiddenLeveI** [comment]
https://user-images.githubusercontent.com/110350004/236633455-6eb762ab-34dd-4e3c-badf-0defc0bce8ea.MP4

I think I got my video to work

**Comment by port19x** [comment]
> > You need to add --dub to get the dubs. So this should work: `ani-cli -d --dub flcl`
> 
> so I don't actually have the ani-cli command. I couldn't figure out how to download it on pop_os so I ended up downloading the file through Githubs website, and now I have to change my directory and run ./ani-cli for it to work. So I can't do that command.

Yes you can. Just do `./ani-cli -d --dub flcl` instead of `ani-cli -d --dub flcl`
I also don't install ani-cli through a package manager, since I need to have the repo around to maintain anyway

**Comment by HiddenLeveI** [comment]
I'm not trying to download dubs, just play them online. How can I do that? I can't even find the dubs point blank.

**Comment by HiddenLeveI** [comment]
Oh shit, doing ./ani-cli --dub gets it to work, thanks!
