### ISSUE TITLE
no search results found

### ISSUE THREAD

**Issue by leaf-ts** [pystardust/ani-cli#112]
Hi,
I installed the app as described but I get a "No search results found", no matter what 
This happens on both my Mac and Linux machines. On the Mac with older version it was working like 2 weeks ago, but I deleted that , to install the new version since you guys made some pretty nice additions 

thanks

**Comment by shwetammvbsc** [comment]
> Hi, I installed the app as described but I get a "No search results found", no matter what This happens on both my Mac and Linux machines. On the Mac with older version it was working like 2 weeks ago, but I deleted that , to install the new version since you guys made some pretty nice additions
> 
> thanks

the address changed to gogoanime.cm

**Comment by leaf-ts** [comment]
I must be doing something wrong
I went to the script and changed the 3 entries that were there from goganime.pe to gogoanime.cm
still nothing though. 
do I have to do something else?

**Comment by Dink4n** [comment]
Fixed in 34748e71a58feab8b57b2ac3de700c30a55430cc

**Comment by Dink4n** [comment]
@leaf-ts Does it work for you now?

**Comment by leaf-ts** [comment]
yes it works!!!
wow that was a fast response and fix!!
Thank you
