### ISSUE TITLE
Option to choose scraping source

### ISSUE THREAD

**Issue by Sarvasv-0** [pystardust/ani-cli#1120]
**Is your feature request related to a problem? Please describe.**
I was watching Anime normally when I found that Some anime like "Naruto" have no more than one quality option
i.e. only one quality you can play the video in for naruto it was 360p
![The Screenshot for the same](https://github.com/pystardust/ani-cli/assets/81177923/cb4d5958-a8ad-4afd-bb52-abb101c7d598)

**Describe the solution you'd like**
Please choose a source for file scraping which has more quality options

**Describe alternatives you've considered**
Maybe just use gogoanime again by default, since it has support for multiple quality options 

**Additional context**
It won't be much difficult, since ani-cli earlier used it

**Comment by Derisis13** [comment]
#1119 includes a solution for this, exposing all links trough the quality change option

**Comment by Sarvasv-0** [comment]
> #1119 includes a solution for this, exposing all links trough the quality change option

so can I change the source with it?

**Comment by port19x** [comment]
> 

Then that should be selected at a higher priority than non-hd sources anyway.
If it doesn't that's a bug

**Comment by Derisis13** [comment]
This was fixed in release 4.3, you can do this using the `change quality` menu point. Reopen the issue if you don't see the options even after upgrading
