### ISSUE TITLE
Can't watch or download anything since the last update

### ISSUE THREAD

**Issue by Rosenette** [pystardust/ani-cli#1132]
Version: 4.3.0
OS: [macOS Big Sur 11.6.5
Shell: zsh
Anime: any

Searching titles via keywords gives "No results found".
I can't watch or download anything.

1. Run `ani-cli -e 4 jigokuraku`
2. Run `ani-cli ouran`
3. Run `ani-cli -d neko`

1. Fetching links should pop up in the terminal, then IINA should open and start playing the episode
2. Should show the list with entries having 'ouran' keyword
3. Should show the list with entries having 'neko' keyword and expect me to select range of episodes to download

<img width="574" alt="Screenshot 2023-05-21 at 12 43 49" src="https://github.com/pystardust/ani-cli/assets/112899452/314972f2-d9f6-460b-94bd-b41d036eff61">

I've already reinstalled both homebrew and ani-cli. Ani-cli itself is up to date

**Comment by Sarvasv-0** [comment]
ani-cli is most probably not allowed to use the internet or you don't have internet at all, try checking your firewall settings, internet connection, other than that, I cannot help you since I know very less about macOS

**Comment by Rosenette** [comment]
I have stable internet and I've also disabled firewall just to check whether it was affecting ani-cli, but it still shows "checking dependencies... No results found!" no matter if I use the -e or -d command with any title. It was working perfectly on 18th of May (last Thursday). 
Thanks for replying either way

**Comment by Sarvasv-0** [comment]
can you please try and execute with the verbose command `bash -x ani-cli <anime name>` or `sh -x ani-cli <anime name>` and post the logs?

**Comment by Rosenette** [comment]
Reinstalled but that didn't change the issue

bash -x ani-cli <anime name>
<img width="1280" alt="Screenshot 2023-05-22 at 12 28 56" src="https://github.com/pystardust/ani-cli/assets/112899452/fb806eac-b1fd-43e0-a3f1-78990cbe9d81">
<img width="1280" alt="Screenshot 2023-05-22 at 12 29 24" src="https://github.com/pystardust/ani-cli/assets/112899452/7e380523-5082-466e-a7bd-c9e9c3e52fb6">

sh -x ani-cli <anime name>
<img width="1280" alt="Screenshot 2023-05-22 at 12 30 13" src="https://github.com/pystardust/ani-cli/assets/112899452/e1bfd7a7-502a-43b3-b771-e8b5f46bb600">
<img width="1280" alt="Screenshot 2023-05-22 at 12 30 25" src="https://github.com/pystardust/ani-cli/assets/112899452/76f40a22-d2ed-482a-b588-668807f17aa4">

**Comment by Sarvasv-0** [comment]
Ah, I see, looks like your ISP or DNS has blocked the scraping source try going to [Allanime](allanime.to) from a browser and see if that works

**Comment by Rosenette** [comment]
I can access this website on my browser and watching an episode of random series works too lol
Also I haven't added any site to DNS blocked list so I have no idea what's going on. My system integrity protection is disabled too.

**Comment by port19x** [comment]
We most likely broke something for mac coreutils, noteably that last sed command visible in your debug logs should be looked into.
This is imo unlikely to be a network issue

**Comment by Rosenette** [comment]
So the command standalone doesn't show anything
<img width="1280" alt="Screenshot 2023-05-25 at 00 10 26" src="https://github.com/pystardust/ani-cli/assets/112899452/5aab98aa-a568-4f6b-886b-426dc0597efc">

And adding ani-cli before only shows that I don't have syncplay installed I never used it (can install it tho if it's required)
<img width="1280" alt="Screenshot 2023-05-25 at 00 11 34" src="https://github.com/pystardust/ani-cli/assets/112899452/7d0d01c0-3931-4833-b4d2-7ae21231bed8">

Still getting the 'no results found' error
<img width="1280" alt="Screenshot 2023-05-25 at 00 14 51" src="https://github.com/pystardust/ani-cli/assets/112899452/99097ffb-1eb2-4155-bc8a-4bd14485c8cf">

**Comment by Derisis13** [comment]
First one is what I was interested in.
It appears allanime isn't answering at all to your curl calls at all. This points towards a networking error, try doing a `traceroute api.allanime.to` and `ping -c api.allanime.to` to diagnose this.

**Comment by Rosenette** [comment]
This doesn't spark joy
<img width="1280" alt="Screenshot 2023-05-28 at 12 44 36" src="https://github.com/pystardust/ani-cli/assets/112899452/53ef2912-a302-4dc2-a4de-bc2469551098">
It's funny how the website works normally in the browser. 

When I opened api there it shows this:
<img width="1279" alt="Screenshot 2023-05-28 at 12 46 45" src="https://github.com/pystardust/ani-cli/assets/112899452/162432cb-b792-4a72-b259-8bdb4d4306c7">

Also when I added parts of the script to the url it shows this:
<img width="1280" alt="Screenshot 2023-05-28 at 12 48 46" src="https://github.com/pystardust/ani-cli/assets/112899452/fcc81863-040f-40ba-aabc-0ec62c5ab8cf">

**Comment by Derisis13** [comment]
Actually it's my bad the ping command should be `ping -c 5 api.allanime.to`

**Comment by Rosenette** [comment]
<img width="521" alt="Screenshot 2023-05-30 at 22 15 19" src="https://github.com/pystardust/ani-cli/assets/112899452/9c6fb88b-080d-432c-a869-e8c88a55dd72">
no issues from what I see

**Comment by scarlet-storm** [comment]
You can try passing `-i` and `-v` to curl command which will print the response. Probably it is dropped by cloudflare ?
```
curl -i -v -e "https://allanime.to" -s --cipher "AES256-SHA256" -G "https://api.allanime.to/allanimeapi" --data-urlencode 'variables={"search":{"allowAdult":false,"allowUnknown":false,"query":"nekopara"},"limit":40,"page":1,"translationType":"sub","countryOrigin":"ALL"}' --data-urlencode 'query=query(        $search: SearchInput        $limit: Int        $page: Int        $translationType: VaildTranslationTypeEnumType        $countryOrigin: VaildCountryOriginEnumType    ) {    shows(        search: $search        limit: $limit        page: $page        translationType: $translationType        countryOrigin: $countryOrigin    ) {        edges {            _id name availableEpisodes __typename       }    }}' -A "Mozilla/5.0 (Windows NT 6.1; Win64; rv:109.0) Gecko/20100101 Firefox/109.0"
```

**Comment by Rosenette** [comment]
It shows this:
<img width="1280" alt="Screenshot 2023-05-31 at 11 36 37" src="https://github.com/pystardust/ani-cli/assets/112899452/d62af29a-f516-4fdd-8a75-4e136198a9fe">

**Comment by scarlet-storm** [comment]
What version of curl are you using ? can you share
```
curl --version
```
Looks like you are using some old version of curl from the macos toolchain which doesn't support tls 1.3 ?
You should update your macos toolchain to the newest version.
Alternatively you can install curl from homebrew and add it to your path manually, as curl won't be linked automatically by homebrew.

**Comment by Rosenette** [comment]
I have curl 7.64.1
<img width="846" alt="Screenshot 2023-05-31 at 17 35 08" src="https://github.com/pystardust/ani-cli/assets/112899452/2b6eb8c8-4a0a-452c-aaf0-579bbe7095fe">

I did brew upgrade curl and it showed this:
<img width="1279" alt="Screenshot 2023-05-31 at 17 42 07" src="https://github.com/pystardust/ani-cli/assets/112899452/f2efca1e-477e-42e8-90b1-ff2dbc4a57e7">

But the curl version is still shown as 7.64.1 for some reason:
<img width="1280" alt="Screenshot 2023-05-31 at 17 43 13" src="https://github.com/pystardust/ani-cli/assets/112899452/3f0152d5-434a-4c17-9280-121cccc0b16c">

**Comment by scarlet-storm** [comment]
Yes, as I mentioned by default homebrew would not symlink it's curl to `/usr/local/bin` as it would break stuff which depends on the macos toolchain. Refer the instructions under caveat in your screenshot.
You will want to manually add curl to your path by doing what it says
`echo 'export PATH="/usr/local/opt/curl/bin:$PATH"' >> ~/.profile`
And then reload the shell so the changes are picked up. After that using `curl --version` in your shell should refer to the homebrew binary.

**Comment by Rosenette** [comment]
Now it finally works! Thank you very much!!
