### ISSUE TITLE
Problem with new downloader

### ISSUE THREAD

**Issue by AzmuthForger** [pystardust/ani-cli#1133]
Hey there, after recent change I saw that the downloader seems to have changed like previously it used to have standred aria2 download but now it shows frames, size(in KB), time and bitrate. It also doesn't seems to show download speed. Please change it like how it previously was. I think download speed has been effected as well.
Thanks

**Comment by 71zenith** [comment]
The downloader hasn't changed. We occasionally get m3u8 links, which `aria2c` cannot download, therefore `ffmpeg` is used as a fallback. For regular mp4 files, `aria2c` is automatically selected.
As for the slow download speed for said m3u8 links, we are currently discovering options to speed up the process.

**Comment by AzmuthForger** [comment]
Is there any way to get mp4 file instead of m3u8 links.

**Comment by 71zenith** [comment]
`mp4` links are always preferred when available, but some episodes don't have them unfortunately. hence the fallback

**Comment by candrapersada** [comment]
> As for the slow download speed for said m3u8 links, we are currently discovering options to speed up the process.

related to #1113 and #1011

**Comment by port19x** [comment]
closing in favor of the now reopened #1011
