### ISSUE TITLE
Episode not released!

### ISSUE THREAD

**Issue by NextGenRyo** [pystardust/ani-cli#1138]
When using ani-cli I keep getting "Episode not released!" I've tried the anime Demon slayer aka kimetsu and Naruto. All give me that mession when selecting to download. I'm using an updated script from trhe github download page. Is this known?

**Comment by SHReSTH9O** [comment]
Yeah, Same issue here too
Solve it! pls

**Comment by cyb3r-anarch** [comment]
there is probably a problem with the current server api, they might've updated their endpoints

**Comment by kirill-dudchenko** [comment]
Same here with haibane renmei. In other cases it stops executing after 'checking dependencies'

**Comment by THEGOLDENPRO** [comment]
From what I understand allanime change their mechanism so the scrapper broke but chockerman said it will be fixed soon and here is a dirty workaround they made: https://discordapp.com/channels/931186431215435807/942523450927493121/1113987476491612193

**Comment by Lucifer25x** [comment]
Same here

**Comment by the-real-ale** [comment]
> From what I understand allanime change their mechanism so the scrapper broke but I think it will be fixed soon and here is a dirty workaround chockerman made: https://discordapp.com/channels/931186431215435807/942523450927493121/1113987476491612193

What channel is that in? The link isn't working for me.

**Comment by mixalis1987** [comment]
Just tried the link also. I confirm it's not working too.

**Comment by Benjamin5678** [comment]
Search "dirty workaround" in degeneral

**Comment by mixalis1987** [comment]
> Search "dirty workaround" in degeneral

Thank you. That works.

**Comment by THEGOLDENPRO** [comment]
> Search "dirty workaround" in degeneral

yeah I was just about to say this thank you

**Comment by justchokingaround** [comment]
then release it!

**Comment by justchokingaround** [comment]
@CoolnsX can u fix this ot should we switch providers? (ik u have exams, it's just that if we switch providers i can implement it now,)

**Comment by justchokingaround** [comment]
nvm, #1139 should be functional by now, please test it out

**Comment by port19x** [comment]
I'll make a release tomorrow during class

**Comment by matiasdante** [comment]
> I'll make a release tomorrow during class

TY <3
