### ISSUE TITLE
Playback failed

### ISSUE THREAD

**Issue by nightwolf3140** [pystardust/ani-cli#1147]
Version: 4.4.3
OS: iOS 16.5 (Alpine linux emulator)
Shell: iSH (BusyBox v1.33.1)
Anime:Dr stone (New World): Ep 10

**Describe the bug**
Downloading/steaming is broken
**Steps To Reproduce**

1. Run `ani-cli -q best
2. Choose Dr. srone
3. Choose episode 10

**Expected behavior**
Steam to VLC

![image](https://github.com/pystardust/ani-cli/assets/125090843/6499f0ec-3d94-4aec-a65d-d7f12ce151b6)

**Additional Context**
Downloading results in an empty unplayable file

**Comment by nightwolf3140** [comment]
> Could this be the m3u8 incompatibility of vlc?

It also doesnt work if downloaded. It just downloads an empty file >180mb

**Comment by Derisis13** [comment]
I'd try checking trough all the links using `change quality`, it'll let you see if one link is dead, or all of them

**Comment by nightwolf3140** [comment]
> I'd try checking trough all the links using `change quality`, it'll let you see if one link is dead, or all of them

Still getting the same issue

**Comment by nightwolf3140** [comment]
It seems to have fixed itself
