### ISSUE TITLE
Episode not released for every anime

### ISSUE THREAD

**Issue by orb-277** [pystardust/ani-cli#1148]
**Metadata (please complete the following information)**
Version: [4.4.0]
OS: [ubuntu 20.04]
Shell: [dash]
Anime: For every anime

**Describe the bug**
Whenever I start any anime it says Episode not found

**Steps To Reproduce**
1. Run `ani-cli `
2. choose one piece
3. Choose Episode 1

**Expected behavior**
The video player should start

**Screenshots (if applicable; you can just drag the image onto github)**

[
![Screenshot from 2023-06-11 16-37-44](https://github.com/pystardust/ani-cli/assets/73741375/38286d36-c291-4750-8797-7a859c0ff5d9)
](url)

**Comment by 71zenith** [comment]
Please update to the latest version(as of now `v4.4.3`). `v4.4.0` is known to not work with strictly POSIX shells such as dash. It is fixed in later revisions. Use `sudo ani-cli -U` to update

**Comment by Derisis13** [comment]
Either when a lot of changes happen or something functional gets changed or when the last release was long ago (and there are changes to be released)

**Comment by port19x** [comment]
Or, like in 4.4, when there is a full breakage

**Comment by orb-277** [comment]
Yes thank you it worked.
