### ISSUE TITLE
Haruna Media Player

### ISSUE THREAD

**Issue by Xenonus** [pystardust/ani-cli#1159]
**Is your feature request related to a problem? Please describe.**
In my opinion, there is a far better player for basic users than mpv, because it's easier to configure.

**Describe the solution you'd like**
Please add a flag allowing to use it.

**Describe alternatives you've considered**
I'm not considering any other alternatives.

**Additional context**
Haruna Media Player shouldn't be too hard to implement because it's mpv frontend.

**Comment by justchokingaround** [comment]
just add this line in you shell config: 
```sh
export ANI_CLI_PLAYER=haruna
```
i still believe in mpv supremacy

![image](https://github.com/pystardust/ani-cli/assets/44473782/9baf76ea-ec2a-45d4-949d-a7b7eb79d2ab)
