### ISSUE TITLE
Requests not working

### ISSUE THREAD

**Issue by Nycz-lab** [pystardust/ani-cli#1163]
**Metadata (please complete the following information)**
Version: Newest
OS: Linux Mint 20.3
Shell: Bash

**Describe the bug**
AllAnime Base has changed from "allanime.to" to "allanime.day"

**Steps To Reproduce**

1. Run `ani-cli`
2. Search for anything

**Expected behavior**
Search Results pop up

**Comment by Derisis13** [comment]
Duplicate of #1164, please discuss there

**Comment by port19x** [comment]
actually it's being discussed at #1161
