### ISSUE TITLE
No results found!

### ISSUE THREAD

**Issue by VasuRamani** [pystardust/ani-cli#1166]
**Metadata (please complete the following information)**
Version: [4.4.5]
OS: [Garuda Linux (based on Arch linux)]
Shell: [fish]

When i search any of the anime it says no result found i have stable internet connection still it says no results found.
**Steps To Reproduce**

1. Run `ani-cli'
2. search for any of the anime.

**Expected behavior**
Downloading should work

**Comment by JuanDuarte2003** [comment]
Version: [4.4.5]
OS: [Ubuntu 22.04.2]

Same here, I tried removing and installing again but the issue continues. Tried installing the app on Android using Termux (Version 4.4.5) and the same.

**Comment by Coregod360** [comment]
Experiencing the same issue.

**Comment by Sarvasv-0** [comment]
> **Metadata (please complete the following information)** Version: [4.4.5] OS: [Garuda Linux (based on Arch linux)] Shell: [fish]
> 
> When i search any of the anime it says no result found i have stable internet connection still it says no results found. **Steps To Reproduce**
> 
> 1. Run `ani-cli'
> 2. search for any of the anime.
> 
> **Expected behavior** Downloading should work

Hello, @VasuRamani. Can you please mention the source of installation?

**Comment by xezo360hye** [comment]
Seems like there was a change in API or something on servers' side. I tried 3 latest releases from GitHub "Releases" page as well as v4.4.5 `ani-cli` package from AUR and none worked so far, neither with search nor with history continuation

**Comment by CoolnsX** [comment]
closing in favour of #1161, please continue your discussion there, also PR #1165 is there
