### ISSUE TITLE
Unable to Find Anime When Searching with ani-cli

### ISSUE THREAD

**Issue by Carlos12001** [pystardust/ani-cli#1167]
**Metadata (please complete the following information)**
    - Version: 4.4.5
   -  OS: Manjaro Linux x86_64
    - Shell: zsh 5.9
    - Anime: anyone
    

**Describe the bug**
When using the `ani-cli onimai` command to search for an anime, the program fails to find any results and returns the message "No results found!"

**Steps To Reproduce**

1. Run `ani-cli onimai`

**Expected behavior**
The ani-cli program should display the search results for the specified anime.

**Screenshots (if applicable; you can just drag the image onto github)**
![image](https://github.com/pystardust/ani-cli/assets/62664256/1c77b678-221a-404a-b5cf-57df998b14ee)

**Additional context**
The ani-cli package was installed from the AUR repository using the package ani-cli-git r653.94e78d5-1.

**Comment by CoolnsX** [comment]
Closing in favour of #1161

**Comment by CoolnsX** [comment]
Please continue your discussion there
