### ISSUE TITLE
Ani-Cli 4.4.5 Not results Found

### ISSUE THREAD

**Issue by 3DGAR-XD** [pystardust/ani-cli#1169]
Version: 4.4.5
OS: MIUI 14 (Android 13) & Windows 10
Shell: Android (Termux), Windows (Git Bash in Terminal Preview),

When i update the script, and search an anime, in windows and android the script says 'not results found', I have seen answers that say to add a line in the script which is ```base_url=https://gogoanime.cm``` I am not sure in which line to place this code, the following image appears both in Windows and Android 

To get this I correctly install the script and run the following 
1. ```ani-cli  -U``` # to updte the script
2. ```ani-cli  -V ``` # updated to 4.4.5
3. ```ani-cli naruto```

![Screenshot_2023-07-06-03-55-51-761_com termux](https://github.com/pystardust/ani-cli/assets/85646467/09e154a5-4b31-485f-b3dc-9d828958ea81)

**Comment by 71zenith** [comment]
The script is broken atm. We are working on a fix. Follow this PR for updates https://github.com/pystardust/ani-cli/pull/1165

**Comment by 3DGAR-XD** [comment]
in the discord server i found this

```sh
sh <(curl -s "https://raw.githubusercontent.com/pystardust/ani-cli/hex_decryption/ani-cli")
```
And it's wotking
anyway thanks :D
