### ISSUE TITLE
External runscripts for starting mpv

### ISSUE THREAD

**Issue by Lukasz825700516** [pystardust/ani-cli#117]
I don't often switch episodes while still watching current one, so separate terminal window bugs me a little.

So I would like to add `-r runscript` option that would allow starting mpv through user defined runscript. In my case i would use this option with devour, or other "hiding current window until program exits" program.

This however would assume that some of runscripts would not fork to background, as it currently is.

**Comment by Derisis13** [comment]
Would changing the variable `player-fn` in line 5 solve your problem? If so, it'd be super simple to add an extra argument.

**Comment by Lukasz825700516** [comment]
Like `player-fn="run_script_and_mpv.sh"`? I think it would be a bit inconvenient as then I would need to have these custom made scripts in some known location, and that could collide with future features that could possibly set player-fn to something else + that would make eventual porting into windows more harder.

**Comment by Derisis13** [comment]
I was thinking taking a -r argument that contains the video player too, but what you did in #120 is actually better.

**Comment by ura43** [comment]
How is that PR not merged yet? 
Remind me in like a week if I haven't merged it by then

**Comment by ura43** [comment]
But yes, having a player option is a good idea

**Comment by ura43** [comment]
> But yes, having a player option is a good idea

It's not if you think it through. The code should be easy enough to be easily modifyable by anyone who has the competence to write his external runscript
