### ISSUE TITLE
Ani-cli always returns No results found!

### ISSUE THREAD

**Issue by tpratty** [pystardust/ani-cli#1170]
**Metadata (please complete the following information)**
OS: Arch Linux
Shell: fish
Anime: any

**Describe the bug**
when i type in the anime into the search anime section I always have "No results found!" as the result no matter the anime I type.

**Steps To Reproduce**

1. Run `ani-cli -d flcl`
2. type in naruto for example

**Expected behavior**
Would show list of episodes 

**Additional context**
I have tried downloading and reinstalling multiple times through different methods. E.g from the aur and also manually built.

**Comment by Raif1** [comment]
The issue is already reported #1161 and fixed. Please update the script.
