### ISSUE TITLE
wrong video load

### ISSUE THREAD

**Issue by woolw** [pystardust/ani-cli#1173]
**Metadata (please complete the following information)**
Version: 4.5.0
OS: Arch Linux x86_64
Kernel: 6.4.2-arch1-1
Shell: bash
Anime: full metal alchemist brotherhood

**Describe the bug**
when selecting to play the second episode of fmab, it starts playing a camrip version of suzume no tojimari instead

**Steps To Reproduce**

1. run `ani-cli`
2. input `fmab` in the search 
3. select episode 2

**Expected behavior**
should play second episode of fmab

**Screenshots (if applicable; you can just drag the image onto github)**
![image](https://github.com/pystardust/ani-cli/assets/58121540/c89ea727-e8f2-4c41-9847-2799fbdca541)

**Comment by port19x** [comment]
Tested both with and without dub.
Can't reproduce

**Comment by woolw** [comment]
[ani-cli_bug.txt](https://github.com/pystardust/ani-cli/files/12004696/ani-cli_bug.txt)

**Comment by foxTr0t1178** [comment]
I had a similar bug, I had searched for hidamari sketch episode 1 a while ago and then searched for other anime, but now everything I search for just brings me the first episode of hidamari sketch

**Comment by foxTr0t1178** [comment]
To clarify, I've had not trouble retrieving the names and episodes of other anime I search for, it's just that when I try to select an episode the intended anime doesn't play, just Hidamari Sketch and only the first episode

**Comment by woolw** [comment]
for me it only seems to have replaced the second episode of fmab.... every other anime seems to work fine

**Comment by port19x** [comment]
> [ani-cli_bug.txt](https://github.com/pystardust/ani-cli/files/12004696/ani-cli_bug.txt)

Nothing out of the ordinary to be seen. Strange

**Comment by woolw** [comment]
works after deleting cache

Here is the output after deleting the cache and history.
[ani-cli_working.txt](https://github.com/pystardust/ani-cli/files/12016943/ani-cli_working.txt)

**Comment by foxTr0t1178** [comment]
I'm still facing this issue

**Comment by foxTr0t1178** [comment]
How would I delete the cache? 

> works after deleting cache
> 
> Here is the output after deleting the cache and history. [ani-cli_working.txt](https://github.com/pystardust/ani-cli/files/12016943/ani-cli_working.txt)

**Comment by foxTr0t1178** [comment]
![Uploading 2023-07-11T171017-0500.png…]()

**Comment by woolw** [comment]
> 

rm -rf ~/.cache/ani-cli/ 
at least on linux... no idea about other os

**Comment by woolw** [comment]
@port19x  anything suspicious when comparing the two files?

**Comment by port19x** [comment]
Haven't checked yet, will do in the afternoon

**Comment by Derisis13** [comment]
I have experienced this once while developing the latest allanime fix, it was cache for me as well. The cache can get "corrupted" if you kill ani-cli during the retereival of episode links.
Solution for users: clear cache by `rm -rf ${XDG_CACHE_HOME:~/.cache}/ani-cli/` or cange quality (at least one should work).
Solution to get rid of the bug: clear cache in a sigint trap (IIRC we had a trap function in v2 and v1 and maybe in v3)

**Comment by port19x** [comment]
I'm sceptical of the way we handle cache right now either way.
I don't see a point of a persistent cache over a per-run `mktemp -d`

**Comment by port19x** [comment]
#1178 is also related to cache :skull:
