### ISSUE TITLE
Speed Increase Issue

### ISSUE THREAD

**Issue by stonedseeker** [pystardust/ani-cli#1176]
**Metadata (please complete the following information)**
Version: [e.g. 2.0.2]
OS: EndeavorOS  
Shell: fish/bash

**Describe the bug**
When i increase the speed of the anime it can go up to a hundred but while reducing it, the speed is reduced in (original_speed) / 2, so 100 / 2 ->  50 / 2-> 25 / 2 -> 12.5 / 2 ... and so on, this way if i reach 100, it gets impossible to make  the speed come back to 1x or reduce it further to 0, as it does not get lower than 0.1

**Steps To Reproduce**

1. Run `ani-cli flcl`
2. Play an episode 
3. Try to change the speed by `Shift + [` and `Shift + ]`  

**Expected behavior**
You should notice the abnormally in the speed change. 

**Screenshots (if applicable; you can just drag the image onto github)**
![image](https://github.com/pystardust/ani-cli/assets/93109628/271d37e8-5525-4391-897b-1b6026f5b1ce)

**Additional context**
I would like to work on this myself actually, will be my way of contributing to ani-cli : )

**Comment by port19x** [comment]
Good luck getting that sorted out with mpv
