### ISSUE TITLE
"No search results found" after using yesterday

### ISSUE THREAD

**Issue by DFireTech** [pystardust/ani-cli#118]
I was searching for the anime, "Another" and I have a feeling that the old gogoanime has changed servers. I am fairly certain I changed to the new one, but, still no search results.

**Comment by ShakurovR** [comment]
Same problem for the anime "komi san", worked yesterday but no results today.

**Comment by XRaTiX** [comment]
Having the same issue,looks like something changed indeed.

**Comment by Puzzlers100** [comment]
Came across the same error, changing the line from "curl -s "https://gogoanime.pe//search.html" \" to https://gogoanime.cm//search.html" \" appears to have fixed it. If you did so, them make sure to recompile it if you use ani-cli as a command, otherwise it's still the same version

**Comment by Puzzlers100** [comment]
That fixes the search function, however all the other functions are still broken. since the URL for the base site is not a variable, you have to change it from the .pe domain to the .cm domain in all 3 or 4 places it's used

**Comment by DFireTech** [comment]
> That fixes the search function, however all the other functions are still broken. since the URL for the base site is not a variable, you have to change it from the .pe domain to the .cm domain in all 3 or 4 places it's used

This appears to have fixed the issue! Thanks, Puzzlers! Ill go ahead and close this issue.
