### ISSUE TITLE
no search results found no matter what title I type in (windows) 

### ISSUE THREAD

**Issue by FlameDevil1** [pystardust/ani-cli#119]
ani-cli doesn't work for me for some reason. I would try and reinstall but idk how

**Comment by Haikal-Ravendy** [comment]
It happens to me, a few days ago it works perfectly fine.

**Comment by TristanCarey** [comment]
same here, on linux tho

**Comment by catsanddo** [comment]
The issue seems to be the gogoanime url itself. Visiting the one in the script redirects you to a different domain now. You could try replacing the url in the script with the url it redirects you to for a quick fix.

**Comment by Haikal-Ravendy** [comment]
Yeah, just found out apparently gogoanime.pe moved to gogoanime.cm, so you can try open the ani-cli file with any text editor and find gogoanime link there and change pe to cm.

**Comment by Austinrocket** [comment]
Can confirm changing .pe to .cm fixes that but now I get a funny issue where it says choose episode [1-0] and then it gets upset at "unary operator expected"

**Comment by Dink4n** [comment]
@Austinrocket You have to change every occurrences of gogoanime.pe

Fixed in ad80e575105820f73518dbef7d2a73a81a1809e8

**Comment by Dink4n** [comment]
Is it working now? (Currently I don't have a windows machine)

**Comment by Austinrocket** [comment]
> @Austinrocket You have to change every occurrences of gogoanime.pe
> 
> Fixed in [ad80e57](https://github.com/pystardust/ani-cli/commit/ad80e575105820f73518dbef7d2a73a81a1809e8)

ah that's on me for not checking to see if it had multiple occurrences. 
Also yes that fixed it. We can probably close out this issue now

**Comment by FlameDevil1** [comment]
thanks its fixed now, sorry for the late response
