### ISSUE TITLE
Can't search for anime on android.

### ISSUE THREAD

**Issue by Luciousdev** [pystardust/ani-cli#1194]
**Metadata**
Version: 4.4.0
OS: android 13 (thermux)
Shell: bash

**Describe the bug**
When searching for an anime it will always show "no results found". On desktop (linux and windows) this issue doesn't happen.

**Steps To Reproduce**

1. Run `ani-cli`
2. Type the anime of your choice

**Expected behavior**
Should show the anime, and episodes etc.

**Screenshots**

![Screenshot_20230809_212652_Termux.jpg](https://github.com/pystardust/ani-cli/assets/69113679/4a2d9021-693f-431d-a718-68e628a580b7)

**Additional context**
I tried reinstalling but the issue still stays.

**Comment by romanovj** [comment]
update script

ani-cli -U

**Comment by port19x** [comment]
The current release is version 4.5, which for some reason is not yet available from the termux repos.
I'll check with termux to see if I can get an update to their repos.
`ani-cli -U` will also fix the issue, tho then you'll be deprived of the benefits of a native installation

**Comment by Luciousdev** [comment]
Ah okay, that did indeed fix my issue. Thanks a lot for the help!
