### ISSUE TITLE
Crashes on android

### ISSUE THREAD

**Issue by rbjnazz** [pystardust/ani-cli#1195]
**Metadata (please complete the following information)**
Version: 4.5.6
OS: Android
Shell: termux + zsh

**Describe the bug**
vlc auto close upon reaching the buffer
I'm certain that it is not a vlc problem (because I always use vlc for streaming movies) maybe it is m3u8 is the problem.

**Comment by port19x** [comment]
Possibly just an early victim of #1196 outage.
We shouldn't work on this issue before a #1196 fix will be tested

**Comment by port19x** [comment]
@rbjnazz do you still have the issue?

**Comment by port19x** [comment]
Open a new issue with further context if this is still an issue.
