### ISSUE TITLE
Full outage - perfectly timed

### ISSUE THREAD

**Issue by aysilu-kitsune** [pystardust/ani-cli#1196]
**Metadata (please complete the following information)**
Version: v4.5
OS: Linux Mint 21.2
Shell: bash
Anime: any

**Describe the bug**
streaming is broken, it says Episode not released! even if it's an anime from the 00s
I think it has to do something with allanime changing their domain to allmanga.to/anime
I have tried replacing the domain in the code, didn't work

**Steps To Reproduce**

1. Run `ani-cli lucky star` (for example)
2. Choose 1 `Lucky Star1
3. Choose episode 1

**Expected behavior**
It should play the episode

**Screenshots (if applicable; you can just drag the image onto github)**
![image](https://github.com/pystardust/ani-cli/assets/134463137/1a92db41-d0fc-4d3c-b6f2-3ecbf92c0964)

**Additional context**
none

**Comment by MysteriousLounger** [comment]
I'd just like to corroborate that I'm also experiencing this outage as of this morning. Of course, downloading is also broken. Cheers and thanks for all the hard work

**Comment by port19x** [comment]
Was about time for v4.6 anyway and also on a friday. Very good timing for an outage :smile:

**Comment by akyag** [comment]
I can confirm as well.

**Comment by justchokingaround** [comment]
ask the script politely and it will work just fine

**Comment by tintinTra** [comment]
i also confirm its not working

**Comment by jkcdarunday** [comment]
Same here. Looks like the API endpoint at https://api.allanime.day/ that ani-cli uses is down.

**Comment by port19x** [comment]
Please test the available fix

**Comment by Fosox** [comment]
First time using it, was indeed broken and the fix worked for me. Thanks.

**Comment by rahulkarmakar2023cse** [comment]
I can also confirm I have tried one piece for example and its showing episode is not released
![image](https://github.com/pystardust/ani-cli/assets/136659657/20d25ec4-5087-4dee-9506-e7ba8af60e54)
