### ISSUE TITLE
Increase search results cap

### ISSUE THREAD

**Issue by selfdivision** [pystardust/ani-cli#1199]
For instance, if you do a search for monster, and you're looking for "Monster" from 2004, you will not find it through ani-cli, because it's beyond the search cap of 40. The only way to find it is to know how it's titled from the website, which defeats the purpose of this tool.

Maybe consider adding pages of 40 search results until it runs out. Or just increase to show all search results.

**Comment by justchokingaround** [comment]
i refuse

**Comment by justchokingaround** [comment]
also, just look up `monster 2004` lol

**Comment by selfdivision** [comment]
I would only know that if I was to visit the site the cli is scraping from. Which, again, defeats the purpose.

**Comment by justchokingaround** [comment]
monster is the only edge case this comes up with, and tbh it's the website's search engine's fault the the anime isn't queried properly
