### ISSUE TITLE
Packaging

### ISSUE THREAD

**Issue by port19x** [pystardust/ani-cli#1203]
*time to make a new issue for this*

## Package mainlining

*Existing packages outside the distros main repos. If you have the connections, please lobby for inclusion.*

- [ ] Arch Linux (See [AUR Package](https://aur.archlinux.org/packages/ani-cli))
- [ ] Fedora (See [COPR Package](https://copr.fedorainfracloud.org/coprs/derisis13/ani-cli/))
- [ ] Gentoo (See [Guru Package](https://gpo.zugaina.org/Overlays/guru/app-misc/ani-cli))

## Important missing packages

- [ ] Homebrew (MacOS)

## Unimportant missing packages

- [ ] xbps (Void)
- [ ] apk (Alpine)
- [ ] eopkg (Solus)

## Package Metadata

Name: `ani-cli`
Description: `A cli tool to browse and play anime`
License: `GPLv3`
URL: `https://github.com/pystardust/ani-cli`
[Dependencies](https://github.com/pystardust/ani-cli#dependencies-1)

---

Here are a all known package recipes:

- [Arch User Repository (Stable)](https://aur.archlinux.org/packages/ani-cli)
- [Arch User Repository (Rolling)](https://aur.archlinux.org/packages/ani-cli-git)
- [Termux (Android)](https://github.com/termux/termux-packages/tree/1f7f11ec7/packages/ani-cli)
- [Scoop (Windows)](https://github.com/ScoopInstaller/Extras/blob/master/bucket/ani-cli.json)
- [NixOS Nixpkgs](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/applications/video/ani-cli/default.nix)
- [Debian 13](https://sources.debian.org/src/ani-cli/4.5-1/)
- [Gentoo Overlay Guru](https://gpo.zugaina.org/Overlays/guru/app-misc/ani-cli)
- [LigurOS](https://gitlab.com/liguros/liguros-repo/-/tree/stable/app-misc/ani-cli)
- [Slackware Slackbuilds](https://slackbuilds.org/repository/15.0/network/ani-cli/)
- [PacStall (Ubuntu)](https://github.com/pacstall/pacstall-programs/blob/master/packages/ani-cli-bin/ani-cli-bin.pacscript)
- [MPR (Debian)](https://mpr.makedeb.org/packages/ani-cli)
- [COPR (Fedora)](https://copr.fedorainfracloud.org/coprs/derisis13/ani-cli/)

---
[old issue](https://github.com/pystardust/ani-cli/issues/697) - [repology](https://repology.org/project/ani-cli/versions)

**Comment by nicodebo** [comment]
Hello,
I made one for Guix that's working fine so far. (but still has some problems about tput missing command). I'm fairly new to guix and still learning so I won't contribute soon but will probably do it once I'm more knowledgeable. If someone wants to do it, feel free to take this recipe.

```scheme
(define-module (ani-cli)
  #:use-module (guix licenses)
  #:use-module (guix packages)
  #:use-module (guix git-download)
  #:use-module (gnu packages video)
  #:use-module (gnu packages curl)
  #:use-module (gnu packages terminals)
  #:use-module (guix build-system copy))

(define-public ani-cli
  (let ((commit "c7e6838647b57411d791bd250417eb0925d74cca")
        (revision "0"))
    (package
      (name "ani-cli")
      (version (git-version "master" revision commit))
      (source (origin
                (method git-fetch)
                (uri (git-reference
                      (url "https://github.com/pystardust/ani-cli")
                      (commit commit)))
                (file-name (git-file-name name version))
                (sha256
                 (base32
                  "1ni9pzjb5qh87iz7c8252bx79qadr1qx6jnkqvvjcqrchh7q473a"))))
      (build-system copy-build-system)
      ;; TODO: why does (inputs) does not work. I have to put the dependencies as propagated-inputs.
      ;; TODO: tput command not found
      (propagated-inputs
	(list yt-dlp curl fzf))
      (arguments
       `(#:install-plan
         '(("ani-cli" "bin/")
           ("ani-cli.1" "share/man/man1/"))))
      (home-page "https://github.com/pystardust/ani-cli")
      (synopsis "A cli to browse and watch anime.")
      (description "A cli to browse and watch anime (alone AND with friends). This tool scrapes the site allanime.")
      (license gpl3))))
```

**Comment by port19x** [comment]
> Hello, I made one for Guix that's working fine so far. (but still has some problems about tput missing command). I'm fairly new to guix and still learning so I won't contribute soon but will probably do it once I'm more knowledgeable. If someone wants to do it, feel free to take this recipe.
> 
> ```scheme
> (define-module (ani-cli)
>   #:use-module (guix licenses)
>   #:use-module (guix packages)
>   #:use-module (guix git-download)
>   #:use-module (gnu packages video)
>   #:use-module (gnu packages curl)
>   #:use-module (gnu packages terminals)
>   #:use-module (guix build-system copy))
> 
> (define-public ani-cli
>   (let ((commit "c7e6838647b57411d791bd250417eb0925d74cca")
>         (revision "0"))
>     (package
>       (name "ani-cli")
>       (version (git-version "master" revision commit))
>       (source (origin
>                 (method git-fetch)
>                 (uri (git-reference
>                       (url "https://github.com/pystardust/ani-cli")
>                       (commit commit)))
>                 (file-name (git-file-name name version))
>                 (sha256
>                  (base32
>                   "1ni9pzjb5qh87iz7c8252bx79qadr1qx6jnkqvvjcqrchh7q473a"))))
>       (build-system copy-build-system)
>       ;; TODO: why does (inputs) does not work. I have to put the dependencies as propagated-inputs.
>       ;; TODO: tput command not found
>       (propagated-inputs
> 	(list yt-dlp curl fzf))
>       (arguments
>        `(#:install-plan
>          '(("ani-cli" "bin/")
>            ("ani-cli.1" "share/man/man1/"))))
>       (home-page "https://github.com/pystardust/ani-cli")
>       (synopsis "A cli to browse and watch anime.")
>       (description "A cli to browse and watch anime (alone AND with friends). This tool scrapes the site allanime.")
>       (license gpl3))))
> ```

Missing tput is actually a posix violation of ani-cli that is currently unfixed. It also affects alpine linux

**Comment by nicodebo** [comment]
thanks for tput info. I'll submit a patch and let you know once it's done.

**Comment by Rucadi** [comment]
I have created a PR on the nixpkgs repo: https://github.com/NixOS/nixpkgs/pull/302094

which allows to add the dependencies (Any of the supported players or cast / sync)

Example of it right now:

nix run github:rucadi/nixpkgs/ani-cli#ani-cli.withSync
nix run github:rucadi/nixpkgs/ani-cli#ani-cli.withCast
nix run github:rucadi/nixpkgs/ani-cli#ani-cli.withSyncCast

and supports all the players with:
nix run github:rucadi/nixpkgs/ani-cli#ani-cli.withMpv
nix run github:rucadi/nixpkgs/ani-cli#ani-cli.withVlc
nix run github:rucadi/nixpkgs/ani-cli#ani-cli.withIina


and supports:

nix run github:rucadi/nixpkgs/ani-cli#ani-cli.withMpvAndSync
nix run github:rucadi/nixpkgs/ani-cli#ani-cli.withMpvAndCast
nix run github:rucadi/nixpkgs/ani-cli#ani-cli.withMpvAndSyncCast

nix run github:rucadi/nixpkgs/ani-cli#ani-cli.withVlcAndSync
nix run github:rucadi/nixpkgs/ani-cli#ani-cli.withVlcAndCast
nix run github:rucadi/nixpkgs/ani-cli#ani-cli.withVlcAndSyncCast

nix run github:rucadi/nixpkgs/ani-cli#ani-cli.withIinaAndSync
nix run github:rucadi/nixpkgs/ani-cli#ani-cli.withIinaAndCast
nix run github:rucadi/nixpkgs/ani-cli#ani-cli.withIinaAndSyncCast

It makes it easier to test and use.

**Comment by justchokingaround** [comment]
good

**Comment by port19x** [comment]
Packaging is good enough nowadays

**Comment by NSExceptional** [comment]
I see. Why not make your own "tap"? No testing requirements that way

**Comment by NSExceptional** [comment]
Would you accept a PR that adds a tap? It's almost no additional work once you have it set up, and it would really tidy up the macOS install instructions, making it a one-liner. I don't love the idea of manually copying stuff into the homebrew folder.

**Comment by port19x** [comment]
Sure, we can add a link to a tap
