### ISSUE TITLE
Not Working on Android termux

### ISSUE THREAD

**Issue by Auxia** [pystardust/ani-cli#1205]
**Metadata (please complete the following information)**
Version: 4.4
OS: Android 14
Shell: bash (Using Termux)
Anime: N/A

**Describe the bug**
Searching for any anime results in "No Result Found!"

**Steps To Reproduce**

1. Run `ani-cli`
2. Enter name of anime to search - In these example Naruto.

**Expected behavior**
Return a list of Anime matching the search query.

**Screenshots (if applicable; you can just drag the image onto github)**

![Screenshot_20230818-011815.png](https://github.com/pystardust/ani-cli/assets/67852952/26a0fbd4-3960-4c6f-8d4c-813afc323b4b)

**Additional context**
I am using Termux version 0.118. I am also on a beta version of Android 14 on a Pixel 6, however I tested it on another device running Android 12 and it results in the same error.

**Comment by Luciousdev** [comment]
Could you try running the command "ani-cli -u"?

That can sometimes fix issues since it updates the script, and I just checked on my phone running android 13 and I don't have the issue. And the version you're running 4.4.0 is outdated, the newest version is 4.6.0

**Comment by Auxia** [comment]
Thanks for the quick reply, the update worked. For some reason termux package manager installs version 4.4. However, the episode does not open in mpv/vlc. It just says, `playing episode 1 of {anime} ...` as shown in this screenshot:
![WhatsApp Image 2023-08-18 at 16 03 37](https://github.com/pystardust/ani-cli/assets/67852952/b403a9fa-f7f5-4225-aecc-cb824117c2a8)

P.S: Do you want me to create a separate issue for this? Because technically the original issue is solved.

**Comment by Luciousdev** [comment]
Make sure that you have mpv player installed from the google play store. If that doesn't help I think you should make a different issue so it will be a bit more organized.

**Comment by Auxia** [comment]
I have the mpv player installed from the google play store. I will try reinstalling everything and see if it works. If not I will create a new issue and close this one to keep things clear.

**Comment by Auxia** [comment]
Did not seem to work, will create a separate issue with more context. Thanks for solving the initial problem.
