### ISSUE TITLE
ani-cli on android does not open anime in mpv

### ISSUE THREAD

**Issue by Auxia** [pystardust/ani-cli#1206]
**Metadata (please complete the following information)**
Version: 4.6
OS: Android 14
Shell: bash (Using Termux)
Anime: N/A - general bug

**Describe the bug**
Anime does not open directly on mpv.
Just gives the prompt of playing the episode and options to go next, previous, select, etc.

**Steps To Reproduce**

1. Run `ani-cli`
2. Enter anime name: `Horimiya`
3. Choose 3: `Horimiya (13 episodes)`
4. Choose episode 1

**Expected behavior**
mpv should open and anime starts streaming

**Screenshots (if applicable; you can just drag the image onto github)**

![WhatsApp Image 2023-08-18 at 16 03 37](https://github.com/pystardust/ani-cli/assets/67852952/2c695778-4786-4f3a-85ce-d3bd2f98cd34)

**Additional context**
Using termux 0.118 on Android 14 on a Pixel 6.

**Comment by THEGOLDENPRO** [comment]
interesting, I just tested right now on my `Google Pixel 4a 5G` running Android 13 and it works just like always.

**Comment by Auxia** [comment]
Could it be because of the android version I am running? I am running Android 14 beta 5. I installed termux from their Github Assets and mpv from the play store.

**Comment by THEGOLDENPRO** [comment]
> 

it would be, we need someone else with this new version of android to test it too

**Comment by THEGOLDENPRO** [comment]
@Auxia bad news, I just upgraded to Android 14 and now I'm having the same problem. mpv command is returning ``aborted``. I think this is going to be a massive issue.

Device: Google Pixel 4a 5G

Just updated to Android 14 as of 15 October.

**Comment by THEGOLDENPRO** [comment]
@Auxia nevermind, found a fix: https://github.com/termux/termux-app/issues/3647#issuecomment-1763563028

**Comment by yrustamjon** [comment]
11
