### ISSUE TITLE
Year information after title or names and prefetch links when downloading in batch 

### ISSUE THREAD

**Issue by devvratmiglani** [pystardust/ani-cli#1208]
It's very hard for Non-Japanese like me to remember names like "Nanatsu no Taizai: Ensa no Edinburgh" and remember which part or chapter it is.
Please add year after title names, it will be great help to Identify what chapter to watch! Thanks in advance!

I mean something like this:
![Screenshot 2023-08-23 235834](https://github.com/pystardust/ani-cli/assets/120363612/84ccb829-883a-4c94-bb8b-36921417abd3) 

------------------------|------------------------|------------------------|------------------------|------------------------|--------------

Also another thing I noticed that fetching links takes longer when in downloading batch, so can we prefetch links of next episode when an episode is downloading and simultaneously for all, kind of like an optimization.

**Comment by port19x** [comment]
I guess it would be much easier to remember what comes after the `:`, not sure if there is much we can do.
We can however definitely prefetch the next link during batch downloads

**Comment by devvratmiglani** [comment]
> I guess it would be much easier to remember what comes after the `:`, not sure if there is much we can do. We can however definitely prefetch the next link during batch downloads

Yes, you are right I just felt convenience using my last downloader when year is mentioned, but that doesn't work anymore.
Also that downloader saves all links to text file and then performs batch download using aria2c ; `It was lightning fast`.
I guess prefetch would do it, I mean fetching while downloading. 


Link to my last downloader: https://github.com/niveK77pur/gogoanime
(It only fetches episode names; do not fetch links or say it is broken now)

**Comment by port19x** [comment]
Thanks for referencing that downloader. That way we can inspect it's code

**Comment by devvratmiglani** [comment]
All the way, tbh its author recommended me ani-cli 😄

**Comment by CoolnsX** [comment]
> Thanks for referencing that downloader. That way we can inspect it's code

It uses selenium (out of scope of our project, but a good starting point for anyone coming into web-scraping)

**Comment by devvratmiglani** [comment]
Well then how do Ani-cli does that without selenium or any automation, cookie handler stuff. Any resources would be a great help.

I only know the way to do is reusing cookies.

**Comment by CoolnsX** [comment]
simple, using scraping disguising techniques to make the request looks like it's coming from browser like 
-- User-agent
-- setting Cipher-suite (for bypassing most of the cloudflare bot protection, except the latest one,it runs JS to calculate something on browser side)
-- Referrer
-- TLS (some cloudflare enabled website also check this)

and many other techniques, like using cookies as you mentioned

**Comment by devvratmiglani** [comment]
I guess its time to sit on chair for long

**Comment by justchokingaround** [comment]
the main source i recommending starting with is `scraping-tutorial`. i take no credit for this repo, i just made a fork of it with a few shellscript examples that i added:
https://github.com/justchokingaround/scraping-tutorial/tree/shellscript

the best resources for webscraping with shellscript imo is already existing code, from which you can get inspired, here are a few useful repos i recommend u take a look at. if u got any questions or need some help just ping, or write to us in the discord server (i'm always glad to help):

https://github.com/CoolnsX/repos_scripts/blob/master/ani-new
https://github.com/sh-dlp/sh-dlp/tree/main/extractors
https://github.com/justchokingaround/zoro-cli/blob/main/zoro.sh

**Comment by ninko76** [comment]
> It's very hard for Non-Japanese like me to remember names like "Nanatsu no Taizai: Ensa no Edinburgh" and remember which part or chapter it is. Please add year after title names, it will be great help to Identify what chapter to watch! Thanks in advance!
> 
> I mean something like this: ![Screenshot 2023-08-23 235834](https://private-user-images.githubusercontent.com/120363612/262768779-84ccb829-883a-4c94-bb8b-36921417abd3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMwNzQyMTksIm5iZiI6MTcxMzA3MzkxOSwicGF0aCI6Ii8xMjAzNjM2MTIvMjYyNzY4Nzc5LTg0Y2NiODI5LTg4M2EtNGM5NC1iYjhiLTM2OTIxNDE3YWJkMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxNFQwNTUxNTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMzU5OTRlZjhmMDJhMWQ1NTE5OTQ1Nzg2OTU0MTg2NmJjYWQyOThmYTJiYzlmNWQxODhmODZmNjRhMWFlNDg4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.E4anHBxTcfN4RIWrr22VzDfew6YMXhEoqK_uqA2yc1Q)
> 
> ------------------------|------------------------|------------------------|------------------------|------------------------|--------------
> 
> Also another thing I noticed that fetching links takes longer when in downloading batch, so can we prefetch links of next episode when an episode is downloading and simultaneously for all, kind of like an optimization.

What command do you use to download a batch for example?

**Comment by devvratmiglani** [comment]
> > It's very hard for Non-Japanese like me to remember names like "Nanatsu no Taizai: Ensa no Edinburgh" and remember which part or chapter it is. Please add year after title names, it will be great help to Identify what chapter to watch! Thanks in advance!
> > I mean something like this: ![Screenshot 2023-08-23 235834](https://private-user-images.githubusercontent.com/120363612/262768779-84ccb829-883a-4c94-bb8b-36921417abd3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMwNzQyMTksIm5iZiI6MTcxMzA3MzkxOSwicGF0aCI6Ii8xMjAzNjM2MTIvMjYyNzY4Nzc5LTg0Y2NiODI5LTg4M2EtNGM5NC1iYjhiLTM2OTIxNDE3YWJkMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxNFQwNTUxNTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMzU5OTRlZjhmMDJhMWQ1NTE5OTQ1Nzg2OTU0MTg2NmJjYWQyOThmYTJiYzlmNWQxODhmODZmNjRhMWFlNDg4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.E4anHBxTcfN4RIWrr22VzDfew6YMXhEoqK_uqA2yc1Q)
> > ------------------------|------------------------|------------------------|------------------------|------------------------|--------------
> > Also another thing I noticed that fetching links takes longer when in downloading batch, so can we prefetch links of next episode when an episode is downloading and simultaneously for all, kind of like an optimization.
> 
> What command do you use to download a batch for example?

this screenshot was with different scr-aper not ani-cli
--->  https://github.com/niveK77pur/gogoanime
