### ISSUE TITLE
integer overflow? or confusion

### ISSUE THREAD

**Issue by Crisp-Casper** [pystardust/ani-cli#1210]
**Metadata (please complete the following information)**
Version: [e.g. 2.0.2]
OS: android 13
Shell: termux
Anime: one piece

**Describe the bug**
Numbering appears broken after episode 1000
Going instead to episode 1029

**Steps To Reproduce**

1. Run `ani-cli one piece
2. Choose 3 (1p)
3. Choose episode 1000
4. Press next

**Expected behavior**
Episode 1001

**Screenshots
![Screenshot_20230828-200016](https://github.com/pystardust/ani-cli/assets/88099085/f8342831-2d65-4e42-b132-494298dce174)

**Additional context**
Appears to work great regardless

**Comment by 71zenith** [comment]
![image](https://github.com/pystardust/ani-cli/assets/92977828/a729171e-719b-463f-b0bd-c3a6aad6b2de)

allanime doesn't seem to have the in-between episodes(or it might be that these are named incorrectly)
there is nothing we can do about it. also from next time please specify if u used dubs

**Comment by devvratmiglani** [comment]
Actually some episodes in dubbed versions are combined in previous one and don't show the numbers of next one.

For example: Avatar : The last air bender - Fire (Book 3) has 16-17 combined, and results in greater video length.

You can check if the same case is here.
