### ISSUE TITLE
Unable to play videos

### ISSUE THREAD

**Issue by ashhad** [pystardust/ani-cli#1215]
**Metadata (please complete the following information)**
Version: installed from source 
OS: Android 13
Shell: termix
Anime: any anime

**Describe the bug**
After selecting episode video player is not launched

**Steps To Reproduce**

1. Run `ani-cli`
2. Select anime and episode
3. No video

**Expected behavior**
Media playback should start
![Screenshot_2023-09-10-02-49-55-40_84d3000e3f4017145260f7618db1d683](https://github.com/pystardust/ani-cli/assets/7990188/1210b37e-8ff9-4279-87c3-078fd862aa30)
![Screenshot_2023-09-10-02-49-55-40_84d3000e3f4017145260f7618db1d683](https://github.com/pystardust/ani-cli/assets/7990188/437270c0-ab6d-4e02-af31-52e76742d464)
![Screenshot_2023-09-10-02-49-55-40_84d3000e3f4017145260f7618db1d683](https://github.com/pystardust/ani-cli/assets/7990188/906ff90b-ab96-4947-9ffa-2f189ffdc5ed)

**Screenshots (if applicable; you can just drag the image onto github)**
![image](https://user-images.githubusercontent.com/82055622/151030428-2e78d15f-4ba9-4d86-b6f3-8307557b4b29.png)

**Additional context**

**Comment by justchokingaround** [comment]
pls specify the version number, also @CoolnsX can u check if the termux version is working?

**Comment by port19x** [comment]
That menu is *old*.
Like pre-fzf days.
So thats 3.x or possibly even older

**Comment by port19x** [comment]
Nvm, this genius included his own screenshots above the screenshots section and left an old one there :facepalm:

**Comment by CoolnsX** [comment]
> pls specify the version number, also @CoolnsX can u check if the termux version is working?

403 : request denied

**Comment by justchokingaround** [comment]
bitch

**Comment by CoolnsX** [comment]
Everything works fine, I am on latest version, watching anime using termux and casting on TV

**Comment by ashhad** [comment]
So I installed Termux's F-droid version, installed ani-cli using the PKG
command and it gave a new error message this time.

Attaching it for your reference

**Comment by CoolnsX** [comment]
Can you try ``` ani-cli -U ```

**Comment by ashhad** [comment]
So I uninstalled it, cloned the got repo and it worked from there.

Thanks for your time guys. Key takeaway were to use F-droid termux and
clone the repo.

Not sure why the PKG command didn't work though

**Comment by Derisis13** [comment]
Reason is that the termux package is outdated
(https://repology.org/project/ani-cli/versions)
Who gave them the bump last time?

**Comment by CoolnsX** [comment]
since this program uses the logic that is constantly updated, package manager can't keep up with this as their end goal is stability
