### ISSUE TITLE
bug: rofi multi select if run from interactive shell not working out of the box

### ISSUE THREAD

**Issue by AzureOrange404** [pystardust/ani-cli#1225]
**Metadata (please complete the following information)**
Version: 4.6.1
OS: Arch Linux 6.5.6
Shell: dash
Anime: any

**Describe the bug**
If invoking `ani-cli --rofi` from an interactive shell, without any env variables set, I cannot select multiple episodes to watch.

**Steps To Reproduce**

1. Run `ani-cli --rofi` from an interactive shell
2. Search any anime
3. Choose any anime
4. No multi-select possible
5. Check command using `ps aux | grep rofi`
6. rofi gets a `-m` flag instead of `-multi-select`

**Expected behavior**
Rofi gets a `-multi-select` flag and supports selecting multiple episodes if run from an interactive shell.

**Additional context**

Pull request for a simple fix is already made.

**Comment by justchokingaround** [comment]
9ab1c5a57c21d10c57dfac9da09b3401a46d2791
