### ISSUE TITLE
Mark EP as "Already Watched"

### ISSUE THREAD

**Issue by chikachika1** [pystardust/ani-cli#1229]
Would be great if we could add tags to the eps.

**Comment by port19x** [comment]
We have a history feature, I don't get what you're requesting.
Please elaborate

**Comment by chikachika1** [comment]
> We have a history feature, I don't get what you're requesting. Please elaborate

Oh, Sorry for the confusion.

I'm suggesting something like a text highlighting or another way to indicates that you already clicked/watched some episode.
