### ISSUE TITLE
Incompatible with M1 Mac

### ISSUE THREAD

**Issue by jaymothra** [pystardust/ani-cli#123]
"sudo make" will not work for me, citing "no such directory". I'm using a new Apple Silicon Mac with homebrew just installed.

Seems like the issue is with it trying to copy from /usr/local/bin, but local folder is empty, doesn't even have a bin folder. As of now ani-cli copies to my Home folder, running the command to have it copy into a self-made /usr/local/bin folder didn't help.

Quite new to this kind of thing, any help would be greatly appreciated.

<img width="571" alt="Screen Shot 2021-11-07 at 5 15 59 PM" src="https://user-images.githubusercontent.com/38904612/140663749-2a514847-7b9a-41ec-844a-356b330ed23a.png">
.

**Comment by shulkk** [comment]
@Dink4n could we pin this issue

**Comment by youngkaneda** [comment]
it looks like that homebrew packages are on ``/opt/homebrew/bin``, you can look at your ``.bashrc`` file to see if it's on your PATH variable, if it is, you can clone this repo, change on the makefile the PREFIX vavriable to ``/opt/homebrew``

**Comment by jaymothra** [comment]
Getting close I think! 
FYI I am using zsh, not sure if this affects directions.
I edited the .zshrc to add that line (which was blank to begin with), as well as editing the PREFIX variable in the MAKEFILE. Sudo make worked without a hitch and I could see my /opt/homebrew/bin became populated with the ani-cli program, but I'm not able to make progress further than that. I'm getting this error message as linked in the image. Like I said, I'm a rookie, so you can see me try to run the program a couple different ways that I had seen from online tutorials (such as 'making the file executable' which isn't in the readme but I see people do in every video tutorial), but no dice.

Thanks for the help!

<img width="780" alt="Screen Shot 2021-11-08 at 2 59 10 PM" src="https://user-images.githubusercontent.com/38904612/140810022-4092d1a7-829e-428a-8ba4-668c35b7195a.png">

**Comment by youngkaneda** [comment]
it's really strange, the ``/opt/homebrew/bin`` must really exist on M1 devices, anyway to run the script you can create the directory that is asking to you ``mkdir ~/.cache/ani-hsts`` will solve

**Comment by jaymothra** [comment]
Unfortunately no dice! 

Getting this result when running mkdir ~/.cache/ani-hsts :


" mkdir: /Users/drewatz/.cache: No such file or directory "


Was able to get it to work when running mkdir ~/.cache first then running mkdir ~/.cache/ani-hsts, but running ani-cli now just gives me:

" /opt/homebrew/bin/ani-cli: line 149: /Users/drewatz/.cache/ani-hsts: Is a directory "

**Comment by youngkaneda** [comment]
@jaymothra ooh sorry I'm really dumb 😤 .cache is a dir you need to create, ani-hsts is just a file on the .cache dir, just do "touch ani-hsts" inside .cache and will work, for the last, I promise haha

**Comment by jaymothra** [comment]
Ahh! Amazing thanks so much! That totally fixed the issue. If anyone reading this is in a similar boat to me, it also seemed like I needed to install tmux before being able to get video output. Can't believe this is a real program what a dream come true :3

**Comment by youngkaneda** [comment]
> Ahh! Amazing thanks so much! That totally fixed the issue. If anyone reading this is in a similar boat to me, it also seemed like I needed to install tmux before being able to get video output. Can't believe this is a real program what a dream come true :3

Glad that it worked but I'm really curious where your programs are installed, try to search it, and just replace the path on makefile, it will be better, but this way works fine too

**Comment by jaymothra** [comment]
Aren't the installed in /opt/homebrew/bin? Changing the prefix variable in the makefile was how I got it to work minus the missing .cache dir and ani-hsts file, I didn't use the chmod +777 workaround.

**Comment by DanielToubul** [comment]
Did you find a solution? it looks like it is building in my Mac, but I cannot seem to run it.
![image](https://user-images.githubusercontent.com/26459151/143718942-015861af-6781-4c0d-b4a0-8df4d3fdcf2a.png)

**Comment by samsara636** [comment]
The build process is just moving the script to your $PATH so you can use it from anywhere
Do this yourself without sudo make
By typing `echo $PATH` and moving ani-cli file there and giving it exec permissions `chmod u+x $PATH/ani-cli`

**Comment by ura43** [comment]
@0x8ff @Dink4n I hope its okay to unpin this for the time being since the gogoanime url issues as well as the parsing seem to affect a lot more users

**Comment by ura43** [comment]
Is` /opt/homebrew/bin` not existing on M1 default behaviour?

**Comment by HenryQuan** [comment]
`/opt/homebrew/bin` should exist on M1 (`brew` is in it) unless it is installed on a terminal running on Rosetta 2.
```shell
if [[ "${UNAME_MACHINE}" == "arm64" ]]
  then
    # On ARM macOS, this script installs to /opt/homebrew only
    HOMEBREW_PREFIX="/opt/homebrew"
    HOMEBREW_REPOSITORY="${HOMEBREW_PREFIX}"
  else
    # On Intel macOS, this script installs to /usr/local only
    HOMEBREW_PREFIX="/usr/local"
    HOMEBREW_REPOSITORY="${HOMEBREW_PREFIX}/Homebrew"
  fi
```
This is the script to determine where the folder should be used by Homebrew.

**Comment by Tractor0** [comment]
i still how i get it to work i am sorry can someone explain very easy for me since i cant understand the above

**Comment by tennyson-mccalla** [comment]
> i still dont know how i get it to work i am sorry can someone explain very easy for me since i cant understand the above

@Tractor0 Please tell us what issues you're having. Describe it in terms of things that have popped up for you while following the instructions etc.

**Comment by Tractor0** [comment]
I have already fixed it i am sorry i forgot to update @tennyson-mccalla

**Comment by tennyson-mccalla** [comment]
> I have already fixed it i am sorry i forgot to update @tennyson-mccalla

@Tractor0  you should probably still give the gist of your problem and solution for the benefit of the community. You don’t have to but it will help someone else along the way when Google lands them here.

**Comment by Tractor0** [comment]
(i am on mac)
hey guys when i do ./ani-cli 
/Users/owner/.cache/ani-hsts: Is a directory
This is the error now i do the steps to fix

ani-hsts is basically the file where it saves the history of the anime you've watched with ani-cli
are you ok with deleting your history? and if did the commands the history will be removed

cd /Users/owner/.cache/
then
rm -rf ani-hsts

then do 
ani-cli 
to run 

and if u wanna run it do ani-cli on terminal to run it

**Comment by tennyson-mccalla** [comment]
Nice. Thanks for that!

**Comment by Tractor0** [comment]
no problem :)

**Comment by ura43** [comment]
@tennyson-mccalla Since you're on the m1 max mac, did you have any notable issues during setup? Does the script generally work?
I would like to make the mac badge in the readme green.
Please tell me if from a "clean slate" you can install and use ani-cli given the instructions in the readme.
If there is anything to add or adapt in the readme or makefile, I'd welcome a PR

**Comment by tennyson-mccalla** [comment]
Everything worked without issue for me though it wasn't a truly clean environment. I'll try and uninstall everything and reinstall to make sure.

The issue I had previously was that location 0 (iirc?) had my username but the latest version no longer had that problem.

I think it's definitely Mac ready.

**Comment by tennyson-mccalla** [comment]
First called sudo make uninstall (this removes /usr/local/bin/ani-cli). Then made and went to a new directory. Executed install instructions:

git clone https://github.com/pystardust/ani-cli.git
cd ani-cli
sudo make

Executed which -a ani-cli revealing only one on the path at /usr/local/bin/ani-cli. Opened a new terminal window and called ani-cli. It works as expected. I tried default, iina, and vlc.

If that's all it takes I think you can make the Mac badge green.
