### ISSUE TITLE
Monster anime is not there?

### ISSUE THREAD

**Issue by manorit2001** [pystardust/ani-cli#1232]
**Metadata (please complete the following information)**
OS: Manjaro 64 bit
Shell: zsh
Anime: Monster (https://g.co/kgs/1LtsTP)

**Describe the bug**
Can't find anime.... 

**Steps To Reproduce**

1. Run `ani-cli monster`
2. Try to find and give up
3. Repeat step 1

**Expected behavior**
All anime should be able to find it!!

**Screenshots (if applicable; you can just drag the image onto github)**
![sad tenma](https://media.tenor.com/qBjm7ca0ojUAAAAd/tired-tenma.gif)

**Additional context**

**Comment by port19x** [comment]
Can confirm, not sure if there is much we can do about it tho

**Comment by bertugmirasyedi** [comment]
Search with the year "monster 2004"
