### ISSUE TITLE
Could we add a makefile that could be run on mac.

### ISSUE THREAD

**Issue by arafatiqbal** [pystardust/ani-cli#1234]
**Is your feature request related to a problem? Please describe.**
Can we add a makefile that mac users can run, and have an easy way of installing all dependencies.

**Describe the solution you'd like**
Create a makefile instead of manually doing the dependency install

**Comment by port19x** [comment]
![image](https://github.com/pystardust/ani-cli/assets/82055622/ea9e1b08-00de-4474-9450-8b256e34eedd)
