### ISSUE TITLE
MPV not found - but installed

### ISSUE THREAD

**Issue by Lemming8** [pystardust/ani-cli#1236]
**Metadata (please complete the following information)**
Version: 4.6.0
OS: Windows 10
Shell: Git bash in Terminal Preview
Anime: /

**Describe the bug**
When trying to start ani-cli it states, that mpv is missing, but ``which mpv.exe`` resolves. 
``sh -x $(which ani-cli) naruto -N -e 1 &>ani-cli.log`` logs only the following line:
``sh: /c/Users/Samuel: No such file or directory``
This is probably due to my Username having a space in its name.

**Steps To Reproduce**

1. Have a space in your username
2. Run `ani-cli`
3. Be confused
4. run which mpv.exe
5. See it resolve
6. run sh -x $(which ani-cli) naruto -N -e 1 &>ani-cli.log
7. See the error

**Expected behavior**
Should be ok with Spaces in Username

**Additional context**

**Comment by Lemming8** [comment]
After reinstalling everything globally i get the same error but different log:
[ani-cli.log](https://github.com/pystardust/ani-cli/files/13404546/ani-cli.log)

**Comment by port19x** [comment]
Quoting issue, what I'm surprised by is that it doesn't work without `sh -x $(which ani-cli)` either

**Comment by port19x** [comment]
What's the output of which mpv.exe btw?
Installing mpv through scoop may help since that resolves to a spaceless path as per your attached log

**Comment by Lemming8** [comment]
```which mpv.exe
/c/ProgramData/scoop/apps/mpv/current/mpv.exe```

**Comment by Lemming8** [comment]
And mpv is installed through scoop :)

**Comment by 71zenith** [comment]
> it works outside of git cli, in the terminal preview (the normal command prompt in terminal preview)

so ure trying to run ani-cli through git bash?

**Comment by Lemming8** [comment]
i was, yes
i was following the readme on that one

**Comment by pmavro** [comment]
Had this problem. I fixed it by manually adding the mpv.exe PATH to my Environment Variables. Not sure why the scoop download didn't get recognised, but now it works!

**Comment by Sarvasv-0** [comment]
> Had this problem. I fixed it by manually adding the mpv.exe PATH to my Environment Variables. Not sure why the scoop download didn't get recognised, but now it works!

Scoop would have probably complained about the directory not being in PATH, if not the scoop devs should do smth to inform the user if the directory is not in PATH
