### ISSUE TITLE
No search results found

### ISSUE THREAD

**Issue by VSuki3581** [pystardust/ani-cli#124]
It was fine a couple days ago but for some reason when i tried to watch naruto today because i was feeling nostalgic it told me no search results found. I already reinstalled ani-cli and restarted my system. No dice, I'm really confused because everything seems like it should be working.
Thank you in advance.

**Comment by duncanjake1** [comment]
Also having this issue. I pulled the latest commits from this repo, but still not getting any search results when I run.

**Comment by duncanjake1** [comment]
@VSuki3581 can you open up the ani-cli file on your machine and see if the following line is included? Should be on line 9.
```
base_url="https://gogoanime.cm"
```
It looks like the gogoanime URL they were using in previous versions no longer works, so they had to change over to this one a couple days ago. If that line isn't present, try running 
```
git pull
```
followed by
```
sudo make
```

**Comment by Anky209e** [comment]
I was also facing this just pull the latest changes by above command. It will work fine.

**Comment by VSuki3581** [comment]
Thanks! It works now :D

**Comment by teymurov27** [comment]
thanks it worked xD

**Comment by ArekkusuMagni** [comment]
I am getting an error  when I issue the git pull command. Any help would be appreciated. 

$ git pull
fatal: not a git repository (or any of the parent directories): .git

**Comment by duncanjake1** [comment]
@ArekkusuMagni Are you issuing the command while inside the ani-cli directory?

**Comment by ArekkusuMagni** [comment]
@duncanjake1 Thank you so much, as soon as you posted that question it clicked in my mind that I need to "cd ani-cli" first. 

instructions for future users: 

cd ani-cli
git pull
sudo make

**Comment by King-Crimson76** [comment]
@ArekkusuMagni when i type in "sudo make" it says:
sudo: make: command not found

**Comment by duncanjake1** [comment]
@King-Crimson76 Seems like 'make' isn't installed by default on your disto of linux (or it got removed somehow). Look up how to install it on your distro and try again.

**Comment by King-Crimson76** [comment]
@duncanjake1 Installed it, typed in cd ani-cli and then sudo make since i already did git pull, this came up:

cp ani-cli /usr/local/bin/ani-cli
chmod 0755 /usr/local/bin/ani-cli

**Comment by duncanjake1** [comment]
@King-Crimson76 That means it worked! Try running the script.

**Comment by King-Crimson76** [comment]
@duncanjake1 Yep! It did! Thank you so much!

**Comment by SaleeSlx** [comment]
You should pin this post.... or add a "How to update" in the .readme or something

**Comment by zergreen** [comment]
I try to do like @duncanjake1  already
but It show same > " No search found "

my list file in /ani-cli

ani-cli  CONTRIBUTING.md  LICENSE  Makefile  README.md

**Comment by ura43** [comment]
The README could definitely use more verbose instructions

**Comment by yuanjv** [comment]
cd: not a directory: ani-cli ???

**Comment by iamchokerman** [comment]
these instructions are outdated, what are you trying to do?

**Comment by yuanjv** [comment]
> 

No search results found on my mac

**Comment by iamchokerman** [comment]
`ani-cli -U` to update

**Comment by MrkwkG** [comment]
![image](https://user-images.githubusercontent.com/122441223/211769652-56373cbc-f042-4509-80af-3cebed339913.png)

**Comment by xahilg18** [comment]
its happening again . on termux it works but does not seem to work on linux . doing ani-cli -U does nothing .

**Comment by FuckOBS** [comment]
> these instructions are outdated, what are you trying to do?
it werked for me

**Comment by Treweyerdv** [comment]
> `ani-cli -U` to update

thanks. it's works
