### ISSUE TITLE
Fedora: make packages for aarch64 or make them noarch.

### ISSUE THREAD

**Issue by vasyl-damian** [pystardust/ani-cli#1246]
Hello,
there are no packages for aarch64, but I noticed that the application works if it is installed from source with no need for recompiling.
Is it possible to add aarch64 packages or change them to noarch on copr?

**Comment by Derisis13** [comment]
Hi, the package itself is built as multiarch, but there's no "multiarch" chroot, so I couldn't make a multiarch repo. Can you add the repo on aarch64, or you downloaded the package manually?

**Comment by vasyl-damian** [comment]
I downloaded the source, since I can't install packages that are not aarch64.

**Comment by Derisis13** [comment]
I found that noarch repos are still in triage: https://github.com/fedora-copr/copr/issues/972
Should I make an aarch64 chroot in the meantime? I don't know when it'll be added

**Comment by vasyl-damian** [comment]
I understand. It is fine by me.

**Comment by Derisis13** [comment]
I'm closing the issue because copr is not likely to implement this feature soon. I'm keeping the offer to add any requested chroot open to anyone interested.
