### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by Pirulinha** [pystardust/ani-cli#125]
No search found

**Comment by CPT-Damian** [comment]
Yeah. It's worked fine for me, but some minutes ago, I tried it and it didn't work. I got the same error message.

`$ ./ani-cli 
Search Anime: Attack on Titan
No search results found`

**Comment by VSuki3581** [comment]
this was happening to me yesterday, just cd into the file and use 

git pull 

then

 sudo make
 
 it worked for me

**Comment by Pirulinha** [comment]
> this was happening to me yesterday, just cd into the file and use `git pull` then `sudo make` it worked for me

Thanks, it worked for me too!
