### ISSUE TITLE
patch tool missing from dependency for Fedora

### ISSUE THREAD

**Issue by specarino** [pystardust/ani-cli#1258]
**Metadata**
Version: 4.7.3
OS: Fedora Workstation 39
Shell: zsh
Installation Method: Through the Fedora Copr by `derisis13/ani-cli`

**Describe the bug**
The update command does not work due to missing the `patch` CLI tool.

**Steps To Reproduce**

1. Run `sudo ani-cli -U`

**Expected behavior**
```
/usr/bin/ani-cli: line 91: patch: command not found
Can't update for some reason!
```

**Additional context**
A simple `sudo dnf install patch` fixed it, but it can just be added within the dependencies while installing for better user experience.

![image](https://github.com/pystardust/ani-cli/assets/53807940/a145ae45-4a80-48ef-8b49-d968efd7d62b)

**Comment by Derisis13** [comment]
Thanks, I was not aware. I'm lagging a little behing with fedora releases because of various reasons but I'll get soon to it.
I'll add patch as an optional dependency, but not as a hard one. Ideally you shouldn't need to update manually. If only I got around to automating the whole process of updating the copr repo with a gh webhook

**Comment by CoolnsX** [comment]
@port19x @Derisis13 
best thing to do here is add a dep_ch "patch" in update function, it will check if the "patch" is installed, and will output that u need to manually install it, temporary workaround for this issue. so fedora users don't open issue regarding this in future.

Also, what the heck is going on with fedora XD.

**Comment by port19x** [comment]
Why not add `patch` to the list of always checked dependencies on line 381?

**Comment by CoolnsX** [comment]
:shrug: Your choice.

**Comment by 71zenith** [comment]
> @port19x @Derisis13 best thing to do here is add a dep_ch "patch" in update function, it will check if the "patch" is installed, and will output that u need to manually install it, temporary workaround for this issue. so fedora users don't open issue regarding this in future.
> 
> Also, what the heck is going on with fedora XD.
would rather have the burden on the system and package rather than ani-cli

**Comment by Nannk** [comment]
Ill side with Port on this one because patch is not installed by default on Steam Deck either.

**Comment by port19x** [comment]
We can also add a dep_ch only in the updating subroutine, that way it works without patch, but a better error message is thrown if the user tries to update without it installed

**Comment by Derisis13** [comment]
I added the dependency for the rpm package, as a hard one now, might change it to recommendation only in the next build.
I'll close the issue now, but we can discuss it further.
