### ISSUE TITLE
Add a --no-detach option

### ISSUE THREAD

**Issue by germaniuss** [pystardust/ani-cli#1261]
**Is your feature request related to a problem? Please describe.**
This is an awesome project, however there is one use case where it is currently lacking. That is allowing to do cursed things such as setting your mpv variables to:
```
vo=kitty
```
or
```
vo=sixel
```
to run everything in the terminal, or do
```
vo=gpu
gpu-context=drm
```
such as this [issue](https://github.com/pystardust/ani-cli/issues/140) suggests in order to watch anime in the tty without a display server or compositor.

The blocker for both of these issues is in the pesky `nohup` that detaches the mpv process. In the first scenario the video isn't correctly shown and in the seccond the mpv controls don't work.

**Describe the solution you'd like**
By allowing to run in `--no-detach` mode we can finally watch anime on a production server with no graphical environment.

**Describe alternatives you've considered**
I can always modify the ani-cli script in order to do this madness, since it's only a line of code.

**Comment by germaniuss** [comment]
Though this issue is mostly a joke it would definitely be cool to be able to do this. Awesome project!

**Comment by port19x** [comment]
I'm impressed, I think I requested that feature like 2 years ago at mpv and they didn't want to

**Comment by port19x** [comment]
God I love open source software
- `https://github.com/mpv-player/mpv/issues/9605`
- `https://github.com/mpv-player/mpv/pull/11002`
- `https://github.com/mpv-player/mpv/commit/874e28f4a41a916bb567a882063dd2589e9234e1`

**Comment by germaniuss** [comment]
> God I love open source software
> 
>     * `https://github.com/mpv-player/mpv/issues/9605`
> 
>     * `https://github.com/mpv-player/mpv/pull/11002`
> 
>     * `https://github.com/mpv-player/mpv/commit/874e28f4a41a916bb567a882063dd2589e9234e1`

Same haha, its awesome they actually did it.
