### ISSUE TITLE
No Results Found

### ISSUE THREAD

**Issue by FsuPsycho** [pystardust/ani-cli#1265]
**Metadata (please complete the following information)**
Version: 4.7
OS: Windows 10
Shell: Powershell profile inside Terminal Preview and GitBash
Anime: All

No matter what anime I search, i still get "no Results found". This is a fresh install of ani-cli.  I have tried to do "ani-cli -u" and says its  all upto date, scoop status says up to date and everything is ok!  This is also my first time trying to figure something like this out and have tried to follow the install guide and a few videos and i don't know if i'm just stupid and forgot a minor thing or just something and would just like some help whenever someone gets a chance, Thank you :D

**Comment by aaron777collins** [comment]
I also have this issue. Note that I freshly installed windows, scoop, etc. (freshly re-installed windows). I didn't have this issue before I reset.

**Comment by EnryuNeedle** [comment]
I have also gotten this issue... I'm in the same situation as aaron777

**Comment by zwab** [comment]
ani-cli -U

This fixed it for me on Windows 10.

**Comment by EnryuNeedle** [comment]
It didn't for me... it got rid of "no results found" message but it just doesn't load video

**Comment by aaron777collins** [comment]
`ani-cli -U` worked. I completely forgot about that command when installing.

**Comment by aaron777collins** [comment]
> It didn't for me... it got rid of "no results found" message but it just doesn't load video

Hmmm maybe you're missing some of the dependencies? I used scoop to install it, along with all the other recommended dependencies. I also used git bash for all of this too.

**Comment by EnryuNeedle** [comment]
I've try from scratch and reinstall..

**Comment by ZeroTwo911** [comment]
> ani-cli -U
> 
> This fixed it for me on Windows 10.

Work 4 me thanks ^^
