### ISSUE TITLE
Asks for Windows dependencies when inside WSL 2

### ISSUE THREAD

**Issue by tekunikaru** [pystardust/ani-cli#1266]
**Metadata**
Version: 4.7-1 (From AUR)
OS: Arch Linux on Windows 10 x86_64
Shell: zsh

It doesn't work properly on Arch WSL. When executed, it thinks I'm on Windows (which is technically true).
It gives the following output:
```zsh
$ ani-cli
Checking dependencies...
Program "mpv.exe" not found. Please install it.
```

**Steps To Reproduce**

1. Start Arch WSL
2. Install `ani-cli` from AUR (I used `yay`)
3. Run `ani-cli`

**Expected behavior**
Dependency check should not ask for Windows applications when inside WSL

**Screenshots**
![image](https://github.com/pystardust/ani-cli/assets/20996279/81ab3adb-f7df-4dc8-ada3-efea0e9c4087)

**Additional context**
I use Arch WSL 2 on Windows 10 with an X server service for GUI

**Comment by Vergenter** [comment]
Hello,

As a contributor who implemented the change to use Windows' mpv.exe for video playback with ani-cli under WSL, I wanted to clarify the rationale behind this approach:

**Why Use Windows' mpv.exe with ani-cli in WSL:**

- Stability & Performance: Running GUI Linux applications like mpv in WSL can lead to stability issues. Using Windows' native mpv.exe ensures a smoother video playback experience.
- Practicality: This workaround leverages the strengths of both environments—ani-cli for fetching streams in WSL and Windows for reliable playback—without the need for complex configurations or additional code to address compatibility issues.


**How to use it:**

- Install mpv.exe on Windows.
- Install ani-cli on wsl
- Enjoy stable video playback using the best tools from both WSL and Windows.

This solution is designed to optimize the user experience by providing a practical and stable setup for enjoying videos with ani-cli. Your understanding and support in this matter are greatly appreciated.

To revert this change it is enough to remove from ani-cli `| *WSL2*` in two places.
https://github.com/pystardust/ani-cli/blob/0a00507115d557fcba64c087dabeaef9f626e789/ani-cli#L303
https://github.com/pystardust/ani-cli/blob/0a00507115d557fcba64c087dabeaef9f626e789/ani-cli#L325

Pull request for context: https://github.com/pystardust/ani-cli/pull/1190

**Comment by shoya-129** [comment]
┌──(shoya㉿Soham-Riki)-[/mnt/c/Users/clash/ani-cli]
└─$ ani-cli lain
Specified quality not found, defaulting to best
Episode is released, but no valid sources!
Fix it please

**Comment by port19x** [comment]
> ┌──(shoya㉿Soham-Riki)-[/mnt/c/Users/clash/ani-cli] └─$ ani-cli lain Specified quality not found, defaulting to best Episode is released, but no valid sources! Fix it please

This is a totally separate thing, please make an issue of your own or comment under an applicable issue that isn't years old

**Comment by shoya-129** [comment]
> > ┌──(shoya㉿Soham-Riki)-[/mnt/c/Users/clash/ani-cli] └─$ ani-cli lain Specified quality not found, defaulting to best Episode is released, but no valid sources! Fix it please
> 
> This is a totally separate thing, please make an issue of your own or comment under an applicable issue that isn't years old

Okay it's just i searched on internet and get this issue and I just add my issue here. Sorry if i did anything wrong. I will create a new issue.
