### ISSUE TITLE
MPV not opens

### ISSUE THREAD

**Issue by Rajala1404** [pystardust/ani-cli#1267]
Version: 4.7.4
OS: Arch Linux x86_64 (6.7.0-arch3-1)
Shell: fish
Anime: Spy x Family

**Describe the bug**
Video not Playing

**Steps To Reproduce**

1. Run ani-cli
2. Search for Spy x Family
3. Choose episode 1

**Expected behavior**
MPV player opens and plays

**Screenshots (if applicable; you can just drag the image onto github)**
![image](https://github.com/pystardust/ani-cli/assets/115874847/9d36324d-736a-4131-b4be-efcc67c277aa)

**Additional context**
If i start it with vlc ani-cli -v it opens vlc but the default (mpv) not works

Logs:
[log.txt](https://github.com/pystardust/ani-cli/files/14074273/log.txt)

**Comment by Nithish-Surya** [comment]
Can you explain how you solved the issue?
