### ISSUE TITLE
need help with ani-cli on steam deck 

### ISSUE THREAD

**Issue by lildaze** [pystardust/ani-cli#1268]
**Metadata (please complete the following information)**
Version: 4.7
OS: steam deck
Shell: [e.g. zsh, run `readlink /bin/sh` to get your shell]
Anime: [e.g. flcl] (if applicable)

Warning: Could not find 'ani-cli', starting '/bin/bash' instead.  Please check your profile settings.

ERROR: ld.so: object '/home/deck/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/deck/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
bash: export: `/usr/local/sbin:/usr/local/bin:/usr/bin:/home/deck/.local/share/flatpak/exports/bin:/var/lib/flatpak/exports/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl=/home/deck/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/home/deck/.local/share/flatpak/exports/bin:/var/lib/flatpak/exports/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl': not a valid identifier
pid 169961 != 169955, skipping destruction (fork without exec?)
pid 169965 != 169955, skipping destruction (fork without exec?)
pid 169966 != 169955, skipping destruction (fork without exec?)
pid 169968 != 169955, skipping destruction (fork without exec?)
pid 169969 != 169955, skipping destruction (fork without exec?)
ERROR: ld.so: object '/home/deck/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
(deck@steamdeck Steam)$

**Comment by Nannk** [comment]
are you running it from the "game mode" or Desktop mode?
Did you use the "copypaste" script provided in the readme?

**Comment by Nannk** [comment]
For now working .desktop file can be generated by:
```
echo '[Desktop Entry]
Encoding=UTF-8
Type=Application
Exec=bash -c "source $HOME/.'$(echo $SHELL | sed -nE "s|.*/(.*)\$|\1|p")'rc && konsole --fullscreen -e ani-cli"
Name=ani-cli' > $HOME/.local/share/applications/ani-cli.desktop
```
Please dont forget to readd (remove old one and add new one) the file to Steam.

**Comment by lildaze** [comment]
Sorry for my late reply yes i copypasted the script from the readme and I'm running it only on desktop mode, tried the .zshrc to modify the last line but this is the only line that was in there any other solutions thanks i really appreciated also it runs great on windows
/home/deck/.zshrc
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

**Comment by Nannk** [comment]
then please run 
```
echo "export PATH=$HOME/.local/bin:\$PATH" >> $HOME/.$(echo $SHELL | sed -nE "s|.*/(.*)\$|\1|p")rc
```
This will add `export PATH=/home/deck/.local/bin:$PATH` to .your_shellrc file.

You can add it manually too.
.your_shellrc depends on what shell you are using. I misread the information you have provided, to i thought it was .zshrc. Please use `echo $SHELL` to get what shell you are using.

**Comment by lildaze** [comment]
Wow man thanks it works I appreciate Nannk
