### ISSUE TITLE
Missing latest tag and release

### ISSUE THREAD

**Issue by Technetium1** [pystardust/ani-cli#1275]
## **Make sure you are on the latest version by running `ani-cli -U`**

**Metadata (please complete the following information)**
- https://github.com/pystardust/ani-cli/releases/latest

**Describe the bug**
- https://github.com/pystardust/ani-cli/commit/129244adb471082b72f3835303fe5e5472f4b2d0 was pushed to master branch Dec 13, but a release was not created since then.

**Steps To Reproduce**
- `N/A`

**Expected behavior**
- `4.7.1` Should have been tagged and released already as the version was bumped in the commit; however, at this point I believe `4.7.2` is due as well.

**Additional context**
- The [`ani-cli` AUR package](https://aur.archlinux.org/packages/ani-cli) is unable to get this latest GitHub release to update, and patching between releases would be unreasonable to expect.
- This is resulting in a pending removal from [Chaotic-AUR](https://aur.chaotic.cx/): https://github.com/chaotic-aur/packages/issues/2614

**Comment by port19x** [comment]
Can confirm `v4.7` broken on arch linux.
Will draft a release shortly, prior to #1274

**Comment by port19x** [comment]
[v4.8](https://github.com/pystardust/ani-cli/releases/tag/v4.8) out now, thank you for raising this issue
