### ISSUE TITLE
Add URL Grab

### ISSUE THREAD

**Issue by nickstienz** [pystardust/ani-cli#1279]
**Is your feature request related to a problem? Please describe.**
No, the feature I’d love to see added to ani-cli is some sort of URL grabber that outputs the stream URL to the stdout.

**Describe the solution you'd like**
Something like a '-g' flag would be cool because then you could use the link elsewhere as I like the simple  implementation of ani-cli as it is.

**Describe alternatives you've considered**
Maybe add a display info option or simple show the URL with the title.

If I knew more shell then I would love to add this myself but I’m not confident enough in my shell skills yet so I’ll rely on others for this one.

**Comment by CoolnsX** [comment]
Prepend ```ANI_CLI_PLAYER=debug``` variable before ```ani-cli```
```sh
ANI_CLI_PLAYER=debug ani-cli <anime_name>
```

**Comment by nickstienz** [comment]
Thanks for the help @CoolnsX !
