### ISSUE TITLE
Add option for showing if episode failed to download

### ISSUE THREAD

**Issue by FilipLac** [pystardust/ani-cli#1281]
**Is your feature request related to a problem? Please describe.**
When downloading multiple episodes, if it fails with one that is not last one, show somehow if it failed downloading it. 

**Describe the solution you'd like**
Either using text at the end with count "Downloaded 12/12", or creating .txt file with output of the error.
Without this, if it failed with downloading episode 7, it just continues without showing at the end that the episode is missing, and checking for it isn't optimal. 

**Describe alternatives you've considered**
Creating .txt file with the same name as the failed episode.
Showing at the end number of downloaded files and number of failed downloads, or which specifically failed.

**Additional context**
Yes, it shows for a brief moment that it failed, but with fast internet and downloading on second monitor, I was able to miss the error that shows, and the script continues downloading.
So the only way for me to tell that one episode is missing is by counting files and checking how many episodes shoul've been downloaded.

**Comment by port19x** [comment]
Good idea, is the problem that the download logs get so big that the error scrolls out of sight?
Or is the screen cleared by our menu afterwards?
I'd like to fix this, but preferably in a way that isn't much effort on my end

**Comment by FilipLac** [comment]
For me, it is cleared when downloading next episode. 

Because I just set it to download whole season to watch it when I'm offline, I then notice, that there are less files, than episodes (like count of my files were 10 but final episode was 13 with the Realist Hero). It would be nice, to come back to the terminal and find some sort of clue, that it didn't download all files, just some.

**Comment by FilipLac** [comment]
So either cancel the download and keep there the last failed log, or at least create .txt file with the same name and pipe the error log there. That would be better since it would download what it can and still show for each of them what failed for later debugging
