### ISSUE TITLE
antivirus blocking connections

### ISSUE THREAD

**Issue by FsuPsycho** [pystardust/ani-cli#1282]
Metadata (please complete the following information)
Version: 4.7
OS: Windows 10
Shell: Powershell profile inside Terminal Preview and GitBash
Anime: All

No matter what anime I search, i still get "no Results found". This is a fresh install of ani-cli. I have tried to do "ani-cli -u" and says its all upto date, scoop status says up to date and everything is ok! This is also my first time trying to figure something like this out and have tried to follow the install guide and a few videos and i don't know if i'm just stupid and forgot a minor thing or just something and would just like some help whenever someone gets a chance, Thank you :D

**Comment by port19x** [comment]
the scoop package is slightly outdated and will be for a few more days.
I am surprised that `ani-cli -U` does not find a `4.8.x` version

**Comment by FsuPsycho** [comment]
no just says 'Checking dependencies..... No results found"

**Comment by port19x** [comment]
Are you perhaps supplying a lowercase `-u` instead of an uppercase one? (`-U`)
If lowercase, it will treat it like a normal search term and ofc not find anything

**Comment by FsuPsycho** [comment]
I think I got it, just uninstalled everything, reinstalled everything - and had to turn off web shield on Avast to bring up the anime list, everytime I put the web shield on, it just says  No results found

**Comment by KiRa937** [comment]
I have the same problem. My anti-virus blocks the connection. "No results found" on anime search and "Connection error" on -U. How can I add it to the exceptions?

**Comment by FilipLac** [comment]
> I think I got it, just uninstalled everything, reinstalled everything - and had to turn off web shield on Avast to bring up the anime list, everytime I put the web shield on, it just says No results found

Yea, Avast is really hard to do anything with, it doesn't have good detection, but it has great false positives. For me, it was crashing GPU because it thought that legitimate radeon drivers were bad. I would recommend switching to windows defender, or kaspersky.

**Comment by KiRa937** [comment]
> Yea, Avast is really hard to do anything with, it doesn't have good detection, but it has great false positives. I would recommend switching to windows defender, or kaspersky.

I'm using kaspersky - it has the same problem with ani-cli.
