### ISSUE TITLE
Filter anime by genre

### ISSUE THREAD

**Issue by WynandVStaden** [pystardust/ani-cli#1286]
I'm a noob and this is kind of a big feature or maybe it exist. But I want to filter the anime by genre. Like by action or isekai  and such. Also maybe be ranking by popularity for each or something. I'm going to see if I can modify the src to do this for me.

Edit: I saw the animdl/jerry repositories. And maybe that already does filtering? So maybe this needs to be closed. Will see.

**Comment by justchokingaround** [comment]
neither support that feature, but ani-cli will for sure not have this, as it's focused on minimalism. feel free to open an issue in those repos

**Comment by WynandVStaden** [comment]
ok thx

**Comment by WynandVStaden** [comment]
> neither support that feature, but ani-cli will for sure not have this, as it's focused on minimalism. feel free to open an issue in those repos

ok thx
