### ISSUE TITLE
Next and Previous Playback Options not Working Without Quitting IINA

### ISSUE THREAD

**Issue by stavguo** [pystardust/ani-cli#1291]
Version: 4.8.0
OS: macOS 14.2.1
Shell: zsh

After watching any episode, selecting "next" or "previous" from the playback options doesn't work unless I right-click and close IINA. If I don't quit out of IINA, my terminal stalls after successfully checking dependencies.

1. Run `ani-cli` and watch one episode of any anime.
2. Choose "next" or "previous" from the playback options.

I would expect it to close my current episode's window and open the next (or previous) episode in a new window, all while still having IINA open and not having to completely quit out of it.

**Comment by Derisis13** [comment]
This is the way it works, it was always like this. I suggest you take a look at the options for ramge selection if you wish to binge.

With that said, I'd love if we could improve this behavior, but in my experience it's very hard or even impossible in shell. Regardless, I'm open for solutions.

**Comment by stavguo** [comment]
@Derisis13 thanks for following up, I had a feeling that this is just how it is. I'll look into using the range selection.

**Comment by Derisis13** [comment]
This one's on me: you either use the `-e` or `-r` flags (see the help or the manpage) or you select multiple entries in fzf (in the episode selection dialogue), everything between the two outer-most eps will be queued. You still need to close your player between eps, but the next one is started automatically. The default key for multi selection in fzf is `<tab>`.
