### ISSUE TITLE
Scoob unable to find ani-cli manifest.

### ISSUE THREAD

**Issue by DynamicCatalyst** [pystardust/ani-cli#1292]
**Metadata (please complete the following information)**
Version: 4.8
OS: Windows 11 
Shell: windows powershell, git bash

**Describe the bug**
scoop is not unable to find ani-cli.

**Steps To Reproduce**

1. $ scoop install ani-cli
Couldn't find manifest for 'ani-cli'.

2. $ scoop install mpv
Couldn't find manifest for 'mpv'.

**Expected behavior**
ani-cli should install 

**Additional context**
scoop is installed using admin privilege, ani-cli is not shown in cli search.

**Comment by 71zenith** [comment]
have u added the extras repo through `scoop bucket add extras`

**Comment by DynamicCatalyst** [comment]
> have u added the extras repo through `scoop bucket add extras`

Yes.
