### ISSUE TITLE
mpv.net

### ISSUE THREAD

**Issue by coldhandsnomatterwhat** [pystardust/ani-cli#1293]
**Is your feature request related to a problem? Please describe.**
There is a better player for Win users than mpv.
It's called mpv.net.
It bugs me that I can't use it yet.

**Describe the solution you'd like**
Please add mpv.net maybe through a `-i` flag analogous to the vlc `-v` flag

**Describe alternatives you've considered**
Maybe support any player string by the user.
But I assume thats drastically more difficult.

**Comment by port19x** [comment]
You can! Just set the environment variable `ANI_CLI_PLAYER` to the path of mpv.net.
You can then persist the setting in your shell configuration file
