### ISSUE TITLE
can't update

### ISSUE THREAD

**Issue by Zm94ZGV2** [pystardust/ani-cli#1295]
Version: 4.8.0
OS: NixOS 24.05pre587158.cbc4211f0aff (Uakari) x86_64
Shell:  nushell

Why I can't do update
![Snapshot_2024-02-27_18-09-25](https://github.com/pystardust/ani-cli/assets/112862918/b4885551-33cb-45b7-af60-ce1ec463df10)

**Comment by mrfluffy-dev** [comment]
Don't do `ani-cli -U` on nixos, nixos is immutable so you cant change things in the /nix/store. Do `nixos-rebuild --upgrade boot` if you use flakes then rebuild your system as normal but delete your flake.lock file then do it.

**Comment by port19x** [comment]
Also you may need to select the unstable channel for ani-cli

**Comment by Zm94ZGV2** [comment]
ok thanks >_<
