### ISSUE TITLE
Ability to watch and search for raw anime

### ISSUE THREAD

**Issue by caliarch** [pystardust/ani-cli#1297]
There should be a -r option to watch and search for raw anime. 

You could get the s-sub providers from aniwave for example, but they don't have a large selection of anime that have that, an alternative could be scraping hianime.to or 4anime.gg. They both have this vidstreaming provider on sub section that has toggleable subtitles.

**Comment by port19x** [comment]
What is a raw anime?

**Comment by 71zenith** [comment]
those without any hardcoded subs

**Comment by 71zenith** [comment]
> There should be a -r option to watch and search for raw anime.

the site we scrape (https://allanime.to) only provides anime with hard coded subs. so there isnt a way to get raw anime in ani-cli

**Comment by Derisis13** [comment]
Does none of the implemented (or possible) providers offer soft-subs? If that was the case, maybe a hack could be implemented to get from those providers only. It'd be very confusing unless the search results also reflect if softsubs are available, and I don't see how that could be done easily
