### ISSUE TITLE
can you make it compatible for andriod and ios (which can  be embedded in an app)

### ISSUE THREAD

**Issue by amad3us47** [pystardust/ani-cli#1299]

**Comment by CoolnsX** [comment]
Wow, a perfect way to invite DMCA

**Comment by Derisis13** [comment]
If I were to do this, I'd use whatever shell interfacing utility is provided by java or swift to open a shell, then have it run the script (if it's possible). The current env vars and non-interactive options should give you enough utility to use the script as a quasi library.

I'm not even sure what the OP is really thinking.
