### ISSUE TITLE
Continue download if failed abruptly

### ISSUE THREAD

**Issue by paniash** [pystardust/ani-cli#13]
Youtube-dl has the ability to continue downloading from the same point if it fails abruptly. `ani-cli` currently does not support this, i.e. if my download is at 50% and I kill it and set it to download again, it does not continue from 50% but from 0%.

It would be nice if this support is added to it. :-)

**Comment by pystardust** [comment]
you could do this with `curl -C -`
I have added this functionality in the last commit
