### ISSUE TITLE
no sound in windows

### ISSUE THREAD

**Issue by amad3us47** [pystardust/ani-cli#1304]
no sound  output when ani cli is downloaded by scoop 
it  can be fixed by using choco for installing ani-cli

**Comment by port19x** [comment]
Can you elaborate what you mean by using choco for installing ani-cli?

**Comment by thecursehunter** [comment]
How did you install it with chocolatey? it is not found in the package manager

**Comment by port19x** [comment]
I suppose this is fixed then? The occasional "no sound" issues are always tough to troubleshoot
