### ISSUE TITLE
"-ash: ani-cli: Permission denied" when trying to

### ISSUE THREAD

**Issue by nkozon** [pystardust/ani-cli#1307]
## **Make sure you are on the latest version by running `ani-cli -U`**

**Metadata (please complete the following information)**
Version: latest (installed on 29/03/2024) - can't perform ani-cli -v because of issue
OS: iOS 15.8.2
Shell: ash (iSH app)
Anime: <non applicable>

**Describe the bug**
I can't run any ani-cli commands because it returns the error "Permission denied", and adding "sudo" doesn't work.

**Steps To Reproduce**

1. Run any 'ani-cli' command, and you get the Permission denied issue.

**Expected behavior**
Ani-Cli should run without issues.

**Screenshots (if applicable; you can just drag the image onto github. remove the following line if not needed)**
![IMG_0007](https://github.com/pystardust/ani-cli/assets/96018531/e433490b-6883-46cf-b397-1830f5744234)

**Additional context**
I followed every line on the readme.md file, except the cp line didn't work (got ommiting error), and after browsing a little online i found out that I had to add -rf in the cp command and i could skip the last line of command (rm -rf), so I did.

**Comment by Packjackisback** [comment]
Can you reinstall and show the errors and the commands you ran?

**Comment by port19x** [comment]
This is probably due to the executable bit not being set on the ani-cli script for some reason.
Not sure how that happened, but a `chmod +x` should do the trick.

![image](https://github.com/pystardust/ani-cli/assets/82055622/5f6a3ce9-4c3f-4e6f-b0b9-b27fb4549f2c)

Please reopen if this doesn't fix your issue
