### ISSUE TITLE
"Program "vlc" not found. Please install it." but it already is

### ISSUE THREAD

**Issue by LagaceEtienne** [pystardust/ani-cli#131]
If perfectly followed every instruction for ani-cli-win but it doesn't seem do detect vlc for some reason. help?

**Comment by LagaceEtienne** [comment]
Changing the player_fn fixed the problem, but now trying to play something just indefinitely says "getting data"
![image](https://user-images.githubusercontent.com/70211017/142255930-bf64814a-efea-4dee-8979-3b72daddffaa.png)

This definitely isn't caused by a poor connection because my download is around 800mbps

Could the problem be in either :

```
get_embedded_video_link() {
	# get the download page url
	anime_id=$1
	ep_no=$2

	# credits to fork: https://github.com/Dink4n/ani-cli for the fix
	curl -4 -s "$base_url/$anime_id-episode-$ep_no" |
	sed -n -E '
		/^[[:space:]]*<a href="#" rel="100"/{
		s/.*data-video="([^"]*)".*/https:\1/p
		q
		}'
}
```

or this : 

```
get_links () {
	embedded_video_url="$1"
	video_url=$(curl -4 -s "$embedded_video_url" |
	sed -n -E '
		/^[[:space:]]*sources:/{
		s/.*(https[^'\'']*).*/\1/p
		q
		}
		')

	video_quality=$(get_video_quality "$embedded_video_url" "$video_url")

	# Replace the video with highest quality video
	printf '%s' "$video_url" | sed -n -E "s/(.*)\.m3u8/\1.$video_quality.m3u8/p"
}
```

or could I be missing a dependency or something?

> 
> 
> Hi! is it in your Variable Path? And Second if it is how and what did you write in? Third: ani-cli-win file line 5, what is in it? player_fn="vlc"? if yes could u try to replace it to player_fn="C:\Program Files (x86)\VLC\vlc.exe" or where ever your vlc file is? well not exatly what I wrote but ya "the file path to the exe"
> 
> Also there a multiple duplicates to ur issue~ ^^

**Comment by LagaceEtienne** [comment]
> 
> 
> Hi! is it in your Variable Path? And Second if it is how and what did you write in? Third: ani-cli-win file line 5, what is in it? player_fn="vlc"? if yes could u try to replace it to player_fn="C:\Program Files (x86)\VLC\vlc.exe" or where ever your vlc file is? well not exatly what I wrote but ya "the file path to the exe"
> 
> Also there a multiple duplicates to ur issue~ ^^

Changing the player_fn fixed the problem, but now trying to play something just indefinitely says "getting data"
![image](https://user-images.githubusercontent.com/70211017/142255930-bf64814a-efea-4dee-8979-3b72daddffaa.png)

This definitely isn't caused by a poor connection because my download is around 800mbps

Could the problem be in either :

```
get_embedded_video_link() {
	# get the download page url
	anime_id=$1
	ep_no=$2

	# credits to fork: https://github.com/Dink4n/ani-cli for the fix
	curl -4 -s "$base_url/$anime_id-episode-$ep_no" |
	sed -n -E '
		/^[[:space:]]*<a href="#" rel="100"/{
		s/.*data-video="([^"]*)".*/https:\1/p
		q
		}'
}
```

or this : 

```
get_links () {
	embedded_video_url="$1"
	video_url=$(curl -4 -s "$embedded_video_url" |
	sed -n -E '
		/^[[:space:]]*sources:/{
		s/.*(https[^'\'']*).*/\1/p
		q
		}
		')

	video_quality=$(get_video_quality "$embedded_video_url" "$video_url")

	# Replace the video with highest quality video
	printf '%s' "$video_url" | sed -n -E "s/(.*)\.m3u8/\1.$video_quality.m3u8/p"
}
```

or could I be missing a dependency or something?

**Comment by DigitalNXZ** [comment]
Hi! sadly im stuck here to~ its not getting data, it seems its already try to play something but cant open the Player! 
I'll someone with better understanding than me could help us any time soon ^^ I use mpv but mpv doesnt want to open

**Comment by DigitalNXZ** [comment]
but what u could try, I completely forgot about this, may this works for you?
https://github.com/pystardust/ani-cli/issues/103#issuecomment-961817822

**Comment by Dink4n** [comment]
Change `$player_fn` in this line
https://github.com/pystardust/ani-cli/blob/ad80e575105820f73518dbef7d2a73a81a1809e8/ani-cli-win#L249
to `"$player_fn"`

Basically add quotes around `$player_fn`

**Comment by LagaceEtienne** [comment]
> 
> 
> Change `$player_fn` in this line
> 
> https://github.com/pystardust/ani-cli/blob/ad80e575105820f73518dbef7d2a73a81a1809e8/ani-cli-win#L249
> 
> to `"$player_fn"`
> 
> Basically, add quotes around `$player_fn`

That fixed it, thanks for your help!
