### ISSUE TITLE
"Program "mpv.exe" not found. Please install it" on Kali Linux AAHAHAHAHAHAAHAHHA

### ISSUE THREAD

**Issue by SPAWNRYS-ban** [pystardust/ani-cli#1310]
**Metadata**
Version: 4.8.3
OS: Kali Linux on WSL2 (Windows 10)
Shell: Bash

**Describe the bug**
I started laughing when it asked for mpv.exe even though it's running under Kali. Why is it even asking for an exe in the first place

**Screenshots**
![изображение](https://github.com/pystardust/ani-cli/assets/68144848/072b61d2-b1cc-409e-90b8-3d9ad7dd3f26)

**Comment by WildanBusiness** [comment]
type this on kali-linux terminal
`
sudo nano /usr/local/bin/ani-cli
`
and then Look for the line that mentions mpv.exe in the file, and change it to just mpv

**Comment by Derisis13** [comment]
Install mpv on your windows host. WSL2 has the ability of calling windows exacutables from the shell, that's why it wants to open mpv.exe

Alternatively run ani-cli on the windows host, it's also supported

**Comment by ykhan21** [comment]
Read the WSL install instructions on the README.
