### ISSUE TITLE
Mac M1 not fetching certain links correctly

### ISSUE THREAD

**Issue by PIshiyama** [pystardust/ani-cli#1315]
Version: 4.8.5
OS: macOS Sonoma 14.4.1
Shell: zsh 5.9 (x86_64-apple-darwin23.0)
Anime: [e.g. flcl] (if applicable)

**Describe the bug**
Certain episodes are returning "Episode not released!" 

**Steps To Reproduce**

1. Run `ani-cli`
2. Search `slime` or `konosuba`
3. Select `Tensei shirata Slime Datta Ken Season 3` or `Kono Subarashii Sekai ni Shukufuku wo! 3` 
4. For Reincarnated as a Slime, episode 1 or 2. Konosuba all episodes don't work. 

**Expected behavior**
Episode should fetch link and play episode. 

**Additional context**
The links are fetched properly when using Windows Terminal Preview on my Windows 10 computer. Most episodes of other shows work as expected and other currently releasing shows, like Spice and Wolf work properly. So far I've only noticed it for Reincarnated as a Slime S3 and Konosuba S3

**Comment by somewhat69** [comment]
``it happens for all anime in my windows pc apparently

**Comment by port19x** [comment]
Can't reproduce your issues with the newest konosuba season.
This is odd, especially that it would break on mac but work on windows

**Comment by PIshiyama** [comment]
This is the output I'm getting when selecting Konosuba Season 3. 
I do find it odd how it's only broken for some titles and not others. 
My next attempt will be to uninstall and reinstall ani-cli and see if that resolves the issue

`p*****@P**** ~ % ani-cli konosuba
sed: 1: "s|^#.*x||g; s|,.*|p|g;  ...": unterminated substitute pattern
gogoanime Links Fetched
Specified quality not found, defaulting to best
Episode not released!
p******@P**** ~ % `

**Comment by PIshiyama** [comment]
Update: Same issue with 2018 i5 MacBook Pro when trying Konosuba S3. The output is identical to the M1 MacBook terminal. Also updated script to 4.8.5. Attempted to run using bash-5.2 and same issue persists

**Comment by port19x** [comment]
Thank you for the debugging effort.
Can you send us a more detailed debug log of the konosuba case?
`sh -x $(command -v ani-cli) > debug.log` should give you one, even on mac

**Comment by PIshiyama** [comment]
[debug.log](https://github.com/pystardust/ani-cli/files/14968401/debug.log)

**Comment by PIshiyama** [comment]
And thank you very much for looking into this!

**Comment by PIshiyama** [comment]
Update: Reincarnated as a Slime is now working for all episodes. Konosuba season still has same issue.
Here is the log for the successful link fetching for Reincarnated as a Slime if a comparison between the two helps at all. Maybe this is one of those weird self-resolving issues or maybe something about my ISP's DNS? 

[debug2.log](https://github.com/pystardust/ani-cli/files/14969612/debug2.log)

**Comment by PIshiyama** [comment]
REJOICE! KONOSUBA WORKS! (For Episode 1. Episode 2 is still broken) I'm gonna take a guess that this might not be the fault of the ani-cli script and must be something else
