### ISSUE TITLE
Site Request: Anplay.in, Animedekho.com, toonworld4all

### ISSUE THREAD

**Issue by dewxo** [pystardust/ani-cli#1319]
**Is your feature request related to a problem? Please describe.**

Requesting Animedekho.com and AnPlay.in better Toonwrold4all.me for multilingual content.
Includes South Asian/Indian Languages including:-
HIndi/Urdu,Tamil, Telgu, Malyalam, English, Japanese etc.

**Describe the solution you'd like**

Doesn't matter if you guys create a *separate repository* for that!
(I'm sure usage will be greater--- better an android app, its ok if a cli but to have is the thing)

**Describe alternatives you've considered**
Alternates are Hexated Repository which scrapes many many sites and works as a cloudstream plugin, and it really is a very great convenience to watch on an android tv, (doesn't matter i can user termux anytime)
They usually maintain `animedekho` and anplay extension is broken, and there is no support for toonworld4all.

https://github.com/hexated/cloudstream-extensions-hexated

**Additional context**
Availability of content in South Asian languages is very limite, and it's my request to please support our involvement too!

Thanks in Advance!

**Comment by port19x** [comment]
Idk man, very hard sell.
I'll leave this open for a day in case another maintainer wants to start a project

**Comment by devvratmiglani** [comment]
Maybe those 1.5B would rush in, seems to have scope.

**Comment by dewxo** [comment]
> Idk man, very hard sell. I'll leave this open for a day in case another maintainer wants to start a project

Thankyou very much to reply!

Let's hope!

**Comment by ajpaulzt** [comment]
these are good sites

https://toonworld4all.boats
https://animedekho.site
