### ISSUE TITLE
Add support for android with termux

### ISSUE THREAD

**Issue by pokurt** [pystardust/ani-cli#132]
Hi, i been recently experimenting with the bash script and i managed to get it work with termux, vlc for android (playstore version), and streamlink from python modules. I'd like to know if you anyone is interested in it

a demo cause stoopid github on phone not letting me upload lmfao: https://telegra.ph/ani-cli-on-android-11-18

**Comment by DigitalNXZ** [comment]
Yes someone already telled on reddit that it works
feel free to make a PR since pystardust seems interested too~
![image](https://user-images.githubusercontent.com/53005759/142333424-bc9e9479-a6d4-4376-9ef0-00af624c7ecc.png)

**Comment by pokurt** [comment]
heres the current commit: https://github.com/pokurt/ani-cli/commit/babe4ef78736e19afcb8a3e46290314746bb45ee

not ready for production use yet-

however people who are reading this, you can follow this reddit post from step 1 to 6: https://www.reddit.com/r/Streamlink/comments/cfno18/guide_streamlink_on_android_termux_vlc

ill find a way to automate it via Makefile were it detects if the shell is being used on an android, install python and setup streamlink, open playstore link for vlc so that user can install if not installed.

**Comment by Shulkk** [comment]
we should make an android branch for this if we ever get official support for this

**Comment by ura43** [comment]
Closing in favor of #153
