### ISSUE TITLE
Anime doesn't start and directly open menu after choosing episode

### ISSUE THREAD

**Issue by jimlyas** [pystardust/ani-cli#1320]
**Metadata (please complete the following information)**
Version: 4.8.5
OS: Android 14
Shell: zsh
Anime: One Piece

**Describe the bug**
After installing VLC and termux from Play Store, and following the installation guide... ani-cli still can't play the anime as intended and instead direcly open end menu 

**Steps To Reproduce**

1. Run `ani-cli one piece`
2. Choose 2 
3. Choose episode 2

**Expected behavior**
Downloading should work

**Screenshots**
https://github.com/pystardust/ani-cli/assets/33854739/49e938bc-18ca-4938-936f-45d79ba0506f

**Additional context**

**Comment by CoolnsX** [comment]
Also don't use termux from Play Store, install it from Fdroid or their official GitHub repo.

**Comment by jimlyas** [comment]
@port19x should I not install mpv from Play store too?

**Comment by port19x** [comment]
With mpv it should work either way

**Comment by jimlyas** [comment]
After installing the latest version of termux from f-droid and mpv from play store, it work as intended.

Thank you~

**Comment by CoolnsX** [comment]
> After installing the latest version of termux from f-droid and mpv from play store, it work as intended.
> 
> Thank you~

you can install mpv from either repos, but termux only recommends f-droid ones and haven't updated the play store one.

**Comment by CoolnsX** [comment]
termux readme --
```
NOTICE: It is highly recommended that you update to v0.118.0 or higher ASAP for various bug fixes, including a critical world-readable vulnerability reported [here](https://termux.github.io/general/2022/02/15/termux-apps-vulnerability-disclosures.html). Also reminding [again](https://www.reddit.com/r/termux/comments/pkujfa/important_deprecation_notice_for_google_play) to users who have installed termux apps from google playstore that playstore builds are [deprecated](https://github.com/termux/termux-app#google-play-store-deprecated) and no longer supported. It is recommended that you shift to F-Droid or GitHub releases.
```
