### ISSUE TITLE
/bin/bash: C:\Users\TrojanHorse.exe\scoop\apps\ani-cli\current\ani-cli: No such file or directory

### ISSUE THREAD

**Issue by JumpIn-Git** [pystardust/ani-cli#1327]
## **Make sure you are on the latest version by running `ani-cli -U`**

**Metadata (please complete the following information)**
4.8
Windows 10
Windows terminal

**Describe the bug**
It was working perfectly and then out of nowhere i got this error:Error code: Bash/0x80070422.
Luckily ive fixed this but know i get:/bin/bash: C:\Users\TrojanHorse.exe\scoop\apps\ani-cli\current\ani-cli: No such file or directory
but i have checked, the file is right there on the same path, scoop isnt recognizing it or something

**Steps To Reproduce**
just "ani-cli"

**Expected behavior**
It should work since there is a file in the directory

**Comment by ykhan21** [comment]
This seems like Windows' WSL bash.exe is trying to run `ani-cli` instead of Git Bash's bash.exe.
Uninstall `ani-cli`, and reinstall it according to the new Windows installation guide in the README.

**Comment by port19x** [comment]
TrojanHorse.exe

are you kidding me?

**Comment by JumpIn-Git** [comment]
> TrojanHorse.exe
> 
> are you kidding me?

i couldnt think of anything lol

**Comment by JumpIn-Git** [comment]
> Impressive how long this stayed open

i think i uninstalled windows after this and forgot, lmao
