### ISSUE TITLE
Download failed for any anime [Windows]

### ISSUE THREAD

**Issue by Haikal-Ravendy** [pystardust/ani-cli#133]
I tried to download an episode but it keep giving me 
"Download Failed Episode" 

How to fix this? I have pulled the newest version for the windows version

**Comment by pwn64** [comment]
Update Line #9 of the ani-cli script to www1.gogoanime.cm

**Comment by Haikal-Ravendy** [comment]
> Update Line #9 of the ani-cli script to www1.gogoanime.cm

I have changed it and I still got the same problem
![image](https://user-images.githubusercontent.com/55172693/144000455-8d1a9331-b894-4882-8959-fe8a5184d116.png)

There is no pause between the "downloading episode 1 ...." and the "download failed episode"

**Comment by Dink4n** [comment]
Did you install `ffmpeg`?

**Comment by Haikal-Ravendy** [comment]
> Did you install `ffmpeg`?

Ah, wasn't aware that I need to install that. Thank you, it is working now
