### ISSUE TITLE
ani-cli on WIndows asking for WSL

### ISSUE THREAD

**Issue by GatewayStar** [pystardust/ani-cli#1330]
When I have WSL disabled it works as normal, but when I have it enabled, it gives me this error.
![Screenshot 2024-05-07 125123](https://github.com/pystardust/ani-cli/assets/144630266/893315a6-c407-4c2b-a990-dbe6aa37f637)

**Comment by fallmake** [comment]
When WSL is installed `bash` is directed to the default WSL environment. Assuming you installed ani-cli using the install instructions with scoop, the scoop shim is a `.cmd` file that calls `bash <path to ani-cli script>` which causes windows to try running it in WSL. As your WSL setup isn't ready to run, you get the message. I suppose the easiest way is changing the line executing bash in the shim at `C:\Users\<yourusername>\scoop\shims\ani-cli.cmd` to something like

`@"%USERPROFILE%\scoop\apps\git\current\bin\bash.exe" -c '"/c/Users/ken/scoop/apps/ani-cli/current/ani-cli" %*'`

This assumes you installed git with scoop from the instructions and explicitly uses the bash executable that comes with git so it doesn't get "hijacked" by WSL.

If you update your WSL environment and get it to run, you could run ani-cli through WSL. To do that you'd need to install the dependencies like fzf and mpv in it manually and wouldn't have to change the shim as described above.

**Comment by ykhan21** [comment]
You could try running `ani-cli` in Git Bash. This should not get hijacked by wsl.
Git Bash could be added as an entry to your Windows Terminal:
![image](https://github.com/pystardust/ani-cli/assets/51864191/d35eec3e-4d20-44ca-b1bd-1715de4d119d)

Instructions:
https://stackoverflow.com/a/70699006/8917573
(If you install git with scoop, replace `C:\Program Files\Git\bin\bash.exe` with `C:\Users\USERNAME\scoop\apps\git\current\bin\bash.exe` and `C:\Program Files\Git\mingw64\share\git\git-for-windows.ico` with `C:\Users\USERNAME\scoop\apps\git\current\mingw64\share\git\git-for-windows.ico`.)

**Comment by ykhan21** [comment]
@GatewayStar, see the updated Windows guide in the README. This should solve your issue. Raise a new issue if you have any errors.
