### ISSUE TITLE
Specified quality not found, defaulting to best

### ISSUE THREAD

**Issue by d4xata** [pystardust/ani-cli#1339]
Sometime can't get the 360p video.

`ani-cli -d -e 6 -q 360p kaiju`

Output:
```
sharepoint Links Fetched
dropbox Links Fetched
gogoanime Links Fetched
Specified quality not found, defaulting to best

and than ani-cli downloading the best quality video
```

But using other tool, I can get the link.

`eren -g -q 360p kaiju`

After selected the episode 6 and quit the tool.
Output:
`https://www038.vipanicdn.net/streamhls/blablabla/ep.6.1716046320.360.m3u8`

I think ani-cli and eren using the same web provider. (or not?)

eren: https://github.com/Based-Programmer/eren

System:
- Arch linux
- Gnome
- kgx (Terminal default Gnome)

**Comment by Derisis13** [comment]
-q will search for whatever is given as its argument. In this case, you want -q 360 instead of -q 360p. (You can also probably use it to prefer mp4 with -q .mp4, I never tried...)

And yes, eren seems to be a rust reimplementation of ani-cli. The results should be the same.
