### ISSUE TITLE
VLC input cannot be opened

### ISSUE THREAD

**Issue by blueking1122** [pystardust/ani-cli#134]
everything works fine in git bash until i try to play something, then vlc opens up and shows this

![image](https://user-images.githubusercontent.com/74525651/142379676-5ca02958-0871-4ecc-87ee-5a3ca020b2d0.png)

**Comment by StenlySaid** [comment]
Have you found a fix yet? I have the same error and it seems that the issue isn't with the VLC but with the URL itself. It leads to a page that doesn't exist.

**Comment by Shrinidhi1904** [comment]
Re-Install your VLC media player

**Comment by StenlySaid** [comment]
> Re-Install your VLC media player

Still doesn't work on my end.

**Comment by blueking1122** [comment]
well reinstalling it worked
thanks for the advice
