### ISSUE TITLE
Stuck after "Search anime: " prompt in windows git-bash

### ISSUE THREAD

**Issue by DhruvSinha2003** [pystardust/ani-cli#1340]
Continuing from issue #1336, my actual issue is solved, the only other problem is that when i try to run ani-cli in git bash on my windows 11 machine after entering the name of the anime and hitting enter, nothing happens.

the cursor moves below but the script does not work.

![image](https://github.com/pystardust/ani-cli/assets/120670739/e80794e3-5c89-4084-85c0-0ea5a278e02b)

So far I have tried reinstalling and changing the ani-cli.cmd file at "C:\Users\dhruv\scoop\shims\ani-cli.cmd"

![image](https://github.com/pystardust/ani-cli/assets/120670739/74839b4c-a828-4d39-bf4e-96ba03ced156)

**Comment by justchokingaround** [comment]
most likely an fzf issue, we do not support git bash, use windows terminal with bash instead
<img width="813" alt="windows_terminal_instructions" src="https://github.com/pystardust/ani-cli/assets/44473782/36f46bf3-f8af-4cfc-b472-c4306e56d97c">
