### ISSUE TITLE
Add mx player support 

### ISSUE THREAD

**Issue by Kamanati** [pystardust/ani-cli#1342]
Please add the feature to play videos using MX Player in your next update. The command for MX Player video playback is provided below. It works well in Termux.
```sh
am start -a android.intent.action.VIEW -d https://www110.vipanicdn.net/streamhls/053189c337f6799792c485c08ed11764/ep.7.1716138243.720.m3u8 -t video/mp4 -n com.mxtech.videoplayer.ad/.ActivityScreen
```
Here Re more command 

## single video 
-- with Custom Title 
```
am start -a android.intent.action.VIEW -d "https://example.com/path/to/your/video.mp4" -t "video/mp4" -n "com.mxtech.videoplayer.ad/.ActivityScreen" --es title "one piece episode 1 "
````

## multiple video 
-- with custom title 
```
am start -a android.intent.action.VIEW -d "https://example.com/path/to/video1.mp4" -t "video/mp4" -n "com.mxtech.videoplayer.ad/.ActivityScreen" --es "video_list" '["https://example.com/path/to/video1.mp4", "https://example.com/path/to/video2.mp4"]' --es "video_list.name" '["Custom Title 1", "Custom Title 2"]'
```

# And here his more 

```
am start \
    -a android.intent.action.VIEW \
    -d file:///path/to/your/video.mp4 \
    --ei decode_mode 1 \
    --eu video_list file:///path/to/video1.mp4 file:///path/to/video2.mp4 file:///path/to/video3.mp4 \
    --eu subs file:///path/to/sub1.srt file:///path/to/sub2.srt \
    --eu title "Your Video Title" \
    --eu position 0 \
    --ez return_result true \
    --ez fast_mode true \
    --ez video true \
    --ez video_list_is_explicit true \
    --ei video_zoom 1 \
    --es headers "User-Agent" "Mozilla compatible/1.0" "Authorization" "(Access Token)" \
    --ez suppress_error_message true \
    --ez secure_uri true \
    --ei orientation 0 \
    --ei keys.dpad_up_down 0 \
    -n com.mxtech.videoplayer.pro/com.mxtech.videoplayer.ActivityScreen

```

Thank you!

**Comment by CoolnsX** [comment]
Seeing MX player getting shit ton of features to the point it's going downhill.

It used to be a great player, now it's an app full of ads and features that should not be there as being a video player

**Comment by 71zenith** [comment]
You can try forking the program and adding the player or using `ANI_CLI_PLAYER` env variable but our default choices will only be mpv and vlc.
From what i can see, its not OSS? even more of a reason to not adopt it

**Comment by Cherry-Android** [comment]
I cannot use decode_mode option in MXPlayer app

Command:
am start -a android.intent.action.VIEW -d /sdcard/h264_hp_l41_800x600_30p_40Mbps.mp4 --ei decode_mode 4 -n com.mxtech.videoplayer.ad/.ActivityScreen 

Log:
09-13 17:40:25.508  3079  3079 V MX.Screen/Dump:  1) decode_mode=4
09-13 17:40:25.539  3079  3079 W Bundle  : Key decode_mode expected Byte but value was a java.lang.Integer.  The default value 0 was returned.
09-13 17:40:25.541  3079  3079 W Bundle  : Key decode_mode expected Byte but value was a java.lang.Integer.  The default value 0 was returned.
