### ISSUE TITLE
scoop couldn't manifest for 'ani-cli'

### ISSUE THREAD

**Issue by weebshura** [pystardust/ani-cli#1344]
when
```
scoop install ani-cli
Couldn't find manifest for 'ani-cli'.
```
and
 ```
scoop update
Updating Scoop...
Updating Buckets...
INFO  Converting 'main' bucket to git repo...
Checking repo... error: RPC failed; curl 92 HTTP/2 stream 5 was not closed cleanly: CANCEL (err 8)
error: 1915 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output
OK
The main bucket was added successfully.
'main' is not a git repository. Skipped.
'java' is not a git repository. Skipped.
'okibcn_ScoopMaster' is not a git repository. Skipped.
Scoop was updated successfully!
```
and 

> Name               Source                             Updated Manifests
> ----               ------                             ------- ---------
> main               ~\scoop\buckets\main                               0
> java               ~\scoop\buckets\java                               0
> okibcn_ScoopMaster ~\scoop\buckets\okibcn_ScoopMaster                 0
> 

i've aslo added 'extras' bucket and still says 0 manifests.
i'm on windows 10 using windows preview terminal and installed scoop from
```
 Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser
Invoke-RestMethod -Uri https://get.scoop.sh | Invoke-Expression

```

any help?

**Comment by 71zenith** [comment]
Can u try to reinstall scoop

**Comment by weebshura** [comment]
it was a connection problem.
