### ISSUE TITLE
result not showing up after running ani-cli

### ISSUE THREAD

**Issue by Pojann008** [pystardust/ani-cli#1345]
Version: 4.8.0
OS: Windows 11

![Screenshot 2024-05-24 000527](https://github.com/pystardust/ani-cli/assets/170657858/aaf1491e-82f9-4f72-8024-a9ac87cb39fc)

its been like that for at least 15 minutes and my connection is good

**Comment by 71zenith** [comment]
do not use git bash. we specify to have windows terminal preview on your system due to compatibilty issues on git bash

**Comment by ykhan21** [comment]
fzf doesn't properly work with some versions of the mintty terminal (the Git Bash Terminal), but it should soon work (see https://github.com/junegunn/fzf/issues/3809#issuecomment-2126358071).

If you really want to use mintty, you can set `export MSYS=enable_pty` before running ani-cli (or set it in ~/.bashrc). You do not have to set this if you use bash in a different terminal (see https://github.com/pystardust/ani-cli/issues/1330#issuecomment-2109081038).
