### ISSUE TITLE
Syncing watchlist across devices

### ISSUE THREAD

**Issue by storm546** [pystardust/ani-cli#1347]
There would be nice to see a feature allowing you to sync the episodes you've watched as well as new episodes for previously wwatched series.

There could be an option for making and signing into an account, or simply generating a code, which if then inputted on another device or instance would link them, simillar to brave browser's sync feature.

**Comment by justchokingaround** [comment]
unlock this feature for the small price of $9.99/month

**Comment by 71zenith** [comment]
Out of scope for ani-cli. We aim to only provide the bare minimum. You may try to use external tools such as syncthing to sync the history file
