### ISSUE TITLE
Can't display on kali linux

### ISSUE THREAD

**Issue by yanfd** [pystardust/ani-cli#1348]
Version: 4.7.6
OS: Kali GNU/Linux Rolling
Shell: zsh
Anime: eva

**Describe the bug**

the video can be correctly open, but all i can see is a green screen. (but the music is able to hear)

**Expected behavior**
play the video

**Screenshots (if applicable; you can just drag the image onto github. remove the following line if not needed)**

<img width="761" alt="Screenshot 2024-05-25 at 16 22 25" src="https://github.com/pystardust/ani-cli/assets/70418161/a7ebef2f-655b-461a-9712-ed366620d345">

**Comment by Derisis13** [comment]
4.7.6 is old, latest is 4.8.8. Please upgrade and tell us if the issue persists

**Comment by port19x** [comment]
I'd like to add that with this failure mode, the culprit is likely to be a codec issue.
Especially since the player does open *something* and you're even able to hear the audio.
Worst case your VPU (part of the GPU) might be damaged, but that's far less likely than codec troubles

**Comment by yanfd** [comment]
> 4.7.6 is old, latest is 4.8.8. Please upgrade and tell us if the issue persists

I already upgraded.

**Comment by yanfd** [comment]
> I'd like to add that with this failure mode, the culprit is likely to be a codec issue. Especially since the player does open _something_ and you're even able to hear the audio. Worst case your VPU (part of the GPU) might be damaged, but that's far less likely than codec troubles

dude maybe you're right. i just figure out that other video cant be play on kali too. its my problem not codes. sorry to bother
