### ISSUE TITLE
unable to use ani-cli.

### ISSUE THREAD

**Issue by weebshura** [pystardust/ani-cli#1349]
unable to stream using ani-cli
powershell and cmd both show
 ```
ani-cli love is war
'bash' is not recognized as an internal or external command,
operable program or batch file.
```
i'm on windows 10.

**Comment by 71zenith** [comment]
> First, you'll need windows terminal preview. [(Install)](https://apps.microsoft.com/store/detail/windows-terminal-preview/9N8G5RFZ9XK3?hl=en-us&gl=US) It comes preinstalled with Windows 11

use windows terminal. its mentioned in the readme

**Comment by weebshura** [comment]
i've tried using it and it's the same

**Comment by Derisis13** [comment]
You went out of your way to delete the issue template. We cannot elaborate on your issues unless those details are provided which were supposed to be filled in

**Comment by ykhan21** [comment]
@weebshura, please see the updated documentation [here](https://github.com/pystardust/ani-cli/blob/7045f88249efe7017e1c234a3e6d8ec6b688f28d/README.md).
