### ISSUE TITLE
Wrong Error Message when connection refused

### ISSUE THREAD

**Issue by SaleeSlx** [pystardust/ani-cli#135]
It worked perfectly when I last used ani-cli about a week ago, but now whatever I search in ani-cli the the output is always "No search results found"

**Comment by SaleeSlx** [comment]
Solved**
In terminal do:

cd ani-cli 
git pull
sudo make

**Comment by CubeyAlchemist** [comment]
I had the same problem, however the version of the repo wasn't the problem for me.

After checking for updates and a few other bits; I tried to access the website normally, and found that it was being blocked by the WiFi provider. Unfortunately this causes the same 'error' message to appear in terminal as a genuine 'no results found'.

If the above fix by SaleeSix doesn't work, try loading gogoanime on your browser. If it has a 'PR_CONNECT_RESET_ERROR', then that means no anime for you my friend.

**Comment by zergreen** [comment]
same problem like you

**Comment by ura43** [comment]
I encountered this due to a rate limit after testing >10 different anime in a short timeframe

**Comment by ura43** [comment]
Error handling should be a lot better now. When connection is refused, the curl error gets printed
