### ISSUE TITLE
Outplayer Support (iOS)

### ISSUE THREAD

**Issue by bbb651** [pystardust/ani-cli#1351]
**Is your feature request related to a problem? Please describe.**
(It's funny how perfect the issue template is for this issue)
There is a better player for iOS users than VLC.
It's called [Outplayer](https://apps.apple.com/us/app/outplayer/id1449923287) and is a mpv frontend written in swift.
It bugs me that I can't use it without manually editing the script, which is a bit annoying to do on iOS.

**Describe the solution you'd like**
Add support for outplayer links, maybe with a generic `-p` for player flag rather than a player specific `-v` (e.g. `-pvlc`, `-poutplayer`) that would trigger player specific logic for known players, or a warning and generic opening logic (`<player> <stream>` for desktop, `<player>://<stream>` link on iOS) for unknown players (maybe with an additional option to only allow known players for security).
The uri of outplayer is identical to vlc, so even the generic support is enough.

**Describe alternatives you've considered**
Replace VLC as the default on iOS (could also be done in addition to the flag).

**Additional context**
Outplayer is **MUCH** better designed than VLC on iOS, and a lot more lightweight (also half the size). It's not open source but it has no collected data and it's fully functional and never a bugs without the full version.

**Comment by Derisis13** [comment]
While we work on this, you can set the environment variable `ANI_CLI_PLAYER` to the path or command to outplayer.
We might take a while since none of us has an iphone to test on. If you have a working solution, a PR would be appreciated.

**Comment by Derisis13** [comment]
Since Outplayer is iOS only, it should be treated like iina on macos

**Comment by port19x** [comment]
I'm closing this in favor of #1350, so we can have a centralized discussion there.
Thank you for contributing to better support for iOS
