### ISSUE TITLE
Ani-cli not working at all on Windows 11 (Installed with Scoop)

### ISSUE THREAD

**Issue by potatofinder** [pystardust/ani-cli#1353]
I downloaded ani-cli and all of the other recommended packages from scoop, but when I try to run it, it says
 "/bin/bash: C:\Users\myname\scoop\apps\ani-cli\current\ani-cli: No such file or directory"
This happens on both powershell and the normal command prompt. The program is installed, because when I run the command in git bash, it works. But it doesn't fully work, it goes up to when it asks me to pick an episode and never loads. What's happening?

**Comment by potatofinder** [comment]
Powershell and command prompt still not working, but I got git bash to work.

**Comment by ykhan21** [comment]
@potatofinder, replace `@bash` with `@"C:\Users\<user>\scoop\apps\git\current\bin\bash.exe"` in the ani-cli.cmd file if you want to run it with powershell.

* This assumes you install git with scoop. If you installed git with the installer, replace `@bash` with `@"C:\Program Files\Git\bin\bash.exe"`

**Comment by DRSDavidSoft** [comment]
Not relevant but I personally went with the no-scoop method and installed from source: #1357, it was better for me since I already had all the required components on my system
