### ISSUE TITLE
Ability to specify a dub language

### ISSUE THREAD

**Issue by Somfic** [pystardust/ani-cli#1354]
Hi!

I’d like the watch the italian dub instead of the english dub for a show. Is this possible?

**Comment by port19x** [comment]
Italian dub is very specific, you'd be lucky to find torrents of it, let alone a piracy streaming provider.
Italian sub should be a little easier to source if that's sufficient, look for "multisub" torrents.

Making italian dub available in ani-cli is not feasible and even if it was would require more effort than it's worth

**Comment by TheN-7** [comment]
Would be possible to have the ENG dub version of animes that have them ?
Like Gundam 00, Fairy Tail, Heroic age etc they all have the dub version.
