### ISSUE TITLE
Daily list of new episodes

### ISSUE THREAD

**Issue by MrDraxs** [pystardust/ani-cli#1359]
if only ani-cli is put into the terminal instead on enter into a search anime window it would display a list of new anime episodes for you to chose that would be daily updated.
example

ani-cli naruto
naruto s1
naruto s2
naruto s3

ani-cli

New and hot 🔥

Sasayaku You ni Koi wo Utau — 08
480p720p1080pXDCC
	New!
Kimetsu no Yaiba - Hashira Geiko-hen — 04
480p720p1080pXDCC
	New!
Mushoku Tensei S2 — 20
480p720p1080pXDCC
	New!
Tensei Kizoku, Kantei Skill de Nariagaru — 09
480p720p1080pXDCC
	New!
Jiisan Baasan Wakagaeru — 09
480p720p1080pXDCC
	New!
Vampire Dormitory — 09
480p720p1080pXDCC
	New!
Shinigami Bocchan to Kuro Maid — 33
480p720p1080pXDCC
	New!
Hibike! Euphonium S3 — 09
480p720p1080pXDCC
	New!
Captain Tsubasa S2 — 35
480p720p1080pXDCC
	New!
One Piece — 1107
480p720p1080pXDCC
	Jun 1st
Wonderful Precure! — 18
480p720p1080pXDCC
	Jun 1st
Tonari no Youkai-san — 09
480p720p1080pXDCC
	Jun 1st
Karasu wa Aruji wo Erabanai — 09
480p720p1080pXDCC
	Jun 1st
The New Gate — 08
480p720p1080pXDCC
	Jun 1st
Nijiyon Animation — 15
480p720p1080pXDCC
	Jun 1st
Nijiyon Animation — 14
480p720p1080pXDCC
	Jun 1st
Nijiyon Animation — 13
480p720p1080pXDCC
	Jun 1st
Yoru no Kurage wa Oyogenai — 09
480p720p1080pXDCC
	Jun 1st
Dragon Raja — 12
480p720p1080pXDCC
	Jun 1st
Kuroshitsuji - Kishuku Gakkou-hen — 08
480p720p1080pXDCC
	Jun 1st

**Comment by CoolnsX** [comment]
no, won't be implemented, ani-cli is a search and watch anime script. these are all tracking features. we won't change the core functionality, which makes it useable for new users.

**Comment by CoolnsX** [comment]
and trust me, most of new users won't even check the help menu, and instead ask directly for the feature that is already there, this will make all the user spamming -- how to search for anime in support server.

**Comment by port19x** [comment]
Shouldn't it be possible via some elaborate hack to use current ani-cli for this?
But it's not something I'd be willing to add

**Comment by MrDraxs** [comment]
why not add as a feature then?
ani-cli -n(n of new)

**Comment by CoolnsX** [comment]
@MrDraxs for check which anime is ongoing by searching it using ani-cli -N
![image](https://github.com/pystardust/ani-cli/assets/76195824/de7d4847-acf4-4d2b-a6ab-f8e34822f381)

**Comment by CoolnsX** [comment]
ani-cli -n shows which are released recently --
![image](https://github.com/pystardust/ani-cli/assets/76195824/1e707e67-d4a7-4fa6-8a2b-9e8d0180e01e)

**Comment by MrDraxs** [comment]
ani-cli -h needs to be updated
![image](https://github.com/pystardust/ani-cli/assets/67723468/a0f1838c-5580-4fb6-ab8d-4c68b4afe92e)
![image](https://github.com/pystardust/ani-cli/assets/67723468/8d0a31e7-cce6-4da2-9922-58227de3a983)

**Comment by MrDraxs** [comment]
-n and -N doesn't show daily releases tough

**Comment by mittal-gunjit** [comment]
i do agree with help needing an update. i stumbled my way here after not finding the desired flag. Another thing is it possible to default to the normal search if the name is not in the top 40 even when using -n flag. I tried searching for an anime only to find it is not in top 40 releases and then i had exit and run the command again without -n to fulfill my purpose

**Comment by port19x** [comment]
Would it have helped to include a note in the help text that the man page has more advanced options?
