### ISSUE TITLE
log anime playback

### ISSUE THREAD

**Issue by port19x** [pystardust/ani-cli#1363]
**Is your feature request related to a problem? Please describe.**

Some people don't yet use a plattform like anilist to track their anime.
Assuming users don't distrohop all the time, having info in the systemd log could be useful.

**Describe the solution you'd like**

We can extend our player mechanics to do a `logger -t ani-cli $NAMEofEP` before playback.
The tag `ani-cli` means users can then review via `journalctl -t ani-cli`
An opt-out environment variable would also be a good idea.

**Describe alternatives you've considered**

We could also just not

**Additional context**

`logger` is part of util-linux

**Comment by 71zenith** [comment]
I don't get how this is supposed to be used. Mind expanding on this

**Comment by 71zenith** [comment]
looks like this is also available for mac os

**Comment by 71zenith** [comment]
what do u think should trigger this? any type of invocation(download, debug links) or just playback?

**Comment by port19x** [comment]
Good question. I believe just playback is enough

**Comment by 71zenith** [comment]
i'd prefer a builtin flag for a `journalctl` and `log` wrapper . smth like this
```sh
        -l | --logview)
            case "$(uname -s)" in
                Darwin*) log show --predicate 'eventMessage contains "ani-cli"' --info ;;
                Linux*) journalctl -t ani-cli ;;
            esac
            exit 0
            ;;

```

**Comment by port19x** [comment]
That would really round off the feature, yes.
This should then make it into the help text and man page as well

**Comment by 71zenith** [comment]
i have the basic structure ready, i can start off after merging #1366

**Comment by justchokingaround** [comment]
i'm highly in favor of this
