### ISSUE TITLE
Bug with selecting episode

### ISSUE THREAD

**Issue by mgogitidze** [pystardust/ani-cli#1364]
## **Make sure you are on the latest version by running `ani-cli -U`**

**Metadata (please complete the following information)**
Version: [4.8.8]
OS: [Macos m3 max 14.1.2 (23B2091))
Shell: [zsh]
Anime: [any] (if applicable)

**Describe the bug**
Selecting next episode is broken.
There is nothing happening 
its not changing episode and cli gets stuck.
You can check screenshot
<img width="1512" alt="Screenshot 2024-06-06 at 23 35 51" src="https://github.com/pystardust/ani-cli/assets/61056656/91669686-c9f0-41bb-b4b8-4ff0f192d8cd">
**Steps To Reproduce**

1. Run `ani-cli`
2. Choose any anime
3. Choose episode 1
4. Press next or select episode

**Expected behavior**
Episode should change

**Additional context**

**Comment by mgogitidze** [comment]
update

I found, that's the problem with closing previous Iina instance
When I select "next" option, nothing happening, but if I full close Iina instance (not episode window, like I exit app completly from app bar), then its opening next episode without problems.

Can you suggest what I should do to close Iina app automatically

**Comment by 71zenith** [comment]
Does IIna not automatically exit when u close the "episode window" or will it stay in the app bar?
I dont know much but u can try setting `keep-open` to `no` in iina settings? This will exit iina when the playback is completed

**Comment by mgogitidze** [comment]
ye, its helped. Now I need only close video window and its working fine, thank you
