### ISSUE TITLE
Download multiple anime(one after another) & airing 

### ISSUE THREAD

**Issue by Kamanati** [pystardust/ani-cli#1365]
#### Feature 1: Sequential Download of Multiple Animes
Please add a feature that allows users to download multiple animes sequentially. Users should be able to select specific animes or use a range to choose episodes of each anime, and the system should download them one by one (i.e., once one anime is downloaded, the next one starts automatically).

#### Feature 2: Airing Anime Selection and Automatic Download
Please add a feature that prompts users to select airing animes. For the selected airing animes, the script should automatically download the newest episodes as they become available. This will ensure that users always have the latest episodes ready for viewing.
(If possible)

**Comment by 71zenith** [comment]
the main focus seems to be on bulk download so ill advice to rely on a torrent setup since allanime quality is quite sub par
