### ISSUE TITLE
Change default player

### ISSUE THREAD

**Issue by IvanCodeslol** [pystardust/ani-cli#1367]
**Is your feature request related to a problem? Please describe.**
I want to be able to change my default player to vlc.

**Describe the solution you'd like**
A config file you edit that contains default player.
Optionally also a command like this:
```sh
ani-cli --config default_player vlc 
```
that edit's the config instead of doing it by hand

**Describe alternatives you've considered**
- Making an alias
- Writing a 2nd script that calls ani-cli and appends the vlc flag where appropriate

**Additional context**
No

**Comment by 71zenith** [comment]
u can put `export ANI_CLI_PLAYER=vlc` in ur shell config.
u can also check the man page for other configurable variables
