### ISSUE TITLE
Allow ani-cli -c to continue dubbed anime

### ISSUE THREAD

**Issue by ykhan21** [pystardust/ani-cli#1371]
**Is your feature request related to a problem? Please describe.**
To continue watching something dubbed, you need to run `ani-cli -c --dub`, instead of just `ani-cli -c`

**Describe the solution you'd like**
Add a fourth column to the history file that keeps track of the `mode`, which "dub" or empty for sub.

**Describe alternatives you've considered**
...

**Additional context**
One may prefer watching some stuff dubbed and some stuff subbed.

**Comment by Yuzuru-Yamazaki** [comment]
can't you use `ani-cli -c --dub` ?

**Comment by port19x** [comment]
Normalization issue, as I said in the PR
