### ISSUE TITLE
cant find anime:Monster ( the one where the mc is johan libert)

### ISSUE THREAD

**Issue by Darkrai533** [pystardust/ani-cli#1373]
## **Make sure you are on the latest version by running `ani-cli -U`**

**Metadata (please complete the following information)**
Version: [e.g. 4.7.6, run `ani-cli -V` to find out]
OS: [e.g. Windows 10 / Linux Mint 20.3]
Shell: [e.g. zsh, run `readlink /bin/sh` to get your shell]
Anime: [e.g. flcl] (if applicable)

**Describe the bug**
Downloading is broken.
It says something about an unsupported protocol, see screenshot.

**Steps To Reproduce**

1. Run `ani-cli -d flcl`
2. Choose 2 (fooly-cooly)
3. Choose episode 1

**Expected behavior**
Downloading should work

**Screenshots (if applicable; you can just drag the image onto github. remove the following line if not needed)**
![image](https://user-images.githubusercontent.com/82055622/151030428-2e78d15f-4ba9-4d86-b6f3-8307557b4b29.png)

**Additional context**

**Comment by 71zenith** [comment]
fill out the metadata, you arent helping rn

**Comment by 71zenith** [comment]
try searching for monster 2004

**Comment by Darkrai533** [comment]
thanks,i got it

**Comment by Darkrai533** [comment]
hello

**Comment by Derisis13** [comment]
Just reinstall, that looks like 2-3 major versions prior to the current one...
