### ISSUE TITLE
Arm64 Support/Package manager binaries

### ISSUE THREAD

**Issue by micr0-dev** [pystardust/ani-cli#1374]
**Is your feature request related to a problem? Please describe.**
`Repository 'fedora-40-aarch64' does not exist in project 'derisis13/ani-cli'.`

**Describe the solution you'd like**
i would like an arm64 package for fedora (and possibly other distros and package managers) in 'derisis13/ani-cli'  

**Describe alternatives you've considered**
for the time being i will just use the source

**Additional context**
linux on arm is becoming more and more popular for laptops, from Asahi linux to the Windows on arm movement.

also great project i love it and use in on my desktop all the time :3

**Comment by micr0-dev** [comment]
update: works great after installing all the dependencies (they all already exist as aarch64 packages)

```
sudo dnf install sed mpv curl yt-dlp fzf patch ffmpeg-free
```
```
git clone "https://github.com/pystardust/ani-cli.git"
sudo cp ani-cli/ani-cli /usr/local/bin
rm -rf ani-cli
```
all that is needed is to add the aarch64 variant to the `derisis13/ani-cli` repo and it will work

**Comment by Derisis13** [comment]
The package built in copr is noarch, but since there's no noarch chroot, I choose to build it only on x86.
It sucks that I need to enable other chroots explicitly, but if that's how it works I can only comply. Since I have to update copr anyway, next release will have arm repositories too
