### ISSUE TITLE
Adding the option to get the direct link in plain text 

### ISSUE THREAD

**Issue by sudo-userv2** [pystardust/ani-cli#1377]
Adding the option to get the direct link would allow the user to play the video on any video player they wish, or use the download manager they like + it is really convenient for sharing 

It seems very easy to implement and I see no reason to not do that, of course it is not high priority but having it would be cool

**Comment by CoolnsX** [comment]
```
ANI_CLI_PLAYER=debug ani-cli <your_anime>
```

**Comment by sudo-userv2** [comment]
Can't we add it as a flag

**Comment by Derisis13** [comment]
Please elaborate why having range selection and raw url output would be an improvement
If you want URLs, you're either making a wrapper script, in which case I'd recommend doing the range selection on your own, outside of ani-cli, and if you want to use a player we directly not support, check the environment variables in the manpage.

Having debug mode (as we often refer to raw link output) as a flag is a feature we don't wish to implement. It's too nieche and it'd confuse more than help.
