### ISSUE TITLE
Do you know the query to get anime titles?

### ISSUE THREAD

**Issue by Baerbeisser** [pystardust/ani-cli#1379]
**Is your feature request related to a problem? Please describe.**
Sousou no Frieren (and others) have nowhere a episodes list for the anime online. So i just put a `| tee episodes.txt` in `episodes_list` function. Sadly, it's still only id's and i can't figure out the query to get titles in `episodes_list_gql`.

I guess you have a way to get allanime's json? Site blocks developer console and you can't copy the title in a practical fashion.

Optional feature request: add episode title to the downloaded file.

**Describe alternatives you've considered**
GraphQL schema, but can't make heads or tails of it.

**Comment by CoolnsX** [comment]
I read tities 🙃

**Comment by Baerbeisser** [comment]
Well, if you have no way to get the titles. It would have been convenient.

Could you tell me how you got the queries? Maybe i could do myself.

**Comment by port19x** [comment]
I'm pretty sure you're looking for `search_anime`
https://github.com/pystardust/ani-cli/blob/master/ani-cli#L188-L193
