### ISSUE TITLE
No support for extra episodes, episode like 6.5 or 2.5

### ISSUE THREAD

**Issue by fold-squirrel** [pystardust/ani-cli#138]
Epesodes like 6.5 or 2.5 are not shown in the epesode number list when selecting an anime. like in 86 season 2 where at this moment has 7ep and one extra (6.5) so it should be 8 in total, yet the script only shows the 7ep and doesn't accept input like 6.5 or 6-5.
Trying to find how many ep a show has including extras isn't worth the effort but allow users to input 6.5 and traslate it to 6-5 in the link.

![Screenshot from 2021-11-21 17-52-23](https://user-images.githubusercontent.com/90027154/142769139-bb251fd6-a5b7-43da-a94e-7aa15ccb9757.png)

**Comment by Shulkk** [comment]
I think it's a GoGo API issue, not ani-cli's problem.

**Comment by drabart** [comment]
> I think it's a GoGo API issue, not ani-cli's problem.

nope it's entirely ani-cli problem

After many tries I kinda implemented it in my fork, but doing it "the proper way" would require whole code to be rewritten as there are multiple correctness checks (not having them on other hand would cause other problems). Also bash is not as forgiving with comparing, and handling numbers that are not integers so entire system handling episode selection would need to be based on strings.

**Comment by ura43** [comment]
I assume this is a parsing problem that will be fixed on accident while solving larger issues.
Lets see what the future holds
