### ISSUE TITLE
Steam Deck detection not working right [Fix in Description]

### ISSUE THREAD

**Issue by basicJavaCoder** [pystardust/ani-cli#1381]
## **Make sure you are on the latest version by running `ani-cli -U`**

**Metadata (please complete the following information)**
Version: 4.8.10
OS: SteamOS 3.6.8
Shell: bash
Anime: [e.g. flcl] (if applicable)
Install method: The One-Copy code in the main repo page for Steam Deck

**Describe the bug**
Ani-cli is checking for the wrong output for SteamOS using ``uname -a``,
the code checks for ``steamdeck`` in the output of this command but it does not exist.
This causes ani-cli to tell the user that mpv is not installed, despite having mpv as flatpak installed on the Deck.

**Steps To Reproduce**

1. Run `ani-cli`
2. Get told mpv was not found, install it.

**Expected behavior**
mpv is installed and should be detected, allowing ani-cli to work like normal.

**My fix to the issue**
I fixed the issues by editing ``.local/bin/ani-cli``

Here are the steps I took to fix the issue:
 1. Open ani-cli code
 2. Go to line 327, where the code checks output of ``uname -a`` for the ``*steamdeck*``output and change it to ``*neptune*``
 3. Save file
 4. Launch ani-cli again

**Screenshots**

![AniFix1](https://github.com/user-attachments/assets/a54bede4-b999-48af-a069-f19977d1811f)
![AniFix2](https://github.com/user-attachments/assets/466c6673-5ab2-4920-b847-8f04b0b33c07)
![AniFix3](https://github.com/user-attachments/assets/dda2b977-bd06-4161-bec1-a73e082bcb35)

**Comment by Nannk** [comment]
Nice, thank you.
I think the confusion came from default username being `steamdeck`.

**Comment by basicJavaCoder** [comment]
Yeah, for sure! It is the default Deck hostname :D
Most people do not bother to change this typically!

**Comment by Nannk** [comment]
Can you make a PR?

**Comment by basicJavaCoder** [comment]
> Can you make a PR?

Ok, done
