### ISSUE TITLE
Can video subtitles be changed in language?

### ISSUE THREAD

**Issue by three3in** [pystardust/ani-cli#1384]
I want to change the English subtitles to Chinese,I searched through ani-cli -h and couldn't find a way to do it, I think I tried.QAQ

**Comment by CoolnsX** [comment]
Straight Answer --- NO

why? -- cause the site we scrape from doesn't provide it, only english sub and dub.

**Comment by three3in** [comment]
Thank you,It turned out to be a direct crawl of the site, and I understand the name.

**Comment by yaoniplan** [comment]
> I want to change the English subtitles to Chinese

@three3in I wrote a small tool that can play online anime with embedded Chinese subtitles.
- Based on Chinese source provider (of course, you can customize it with the help of artificial intelligence, based on source provider in other languages).

<img width="1366" height="768" alt="Image" src="https://github.com/user-attachments/assets/546fd52e-9dc7-4ec0-8ea5-f9f66ae9cd19" />

- https://github.com/yaoniplan/dotfiles/tree/master/.local/src/ani
