### ISSUE TITLE
WSL 1 ani-cli not recognizing MPV in path

### ISSUE THREAD

**Issue by mmamdouh4370** [pystardust/ani-cli#1387]
## **Make sure you are on the latest version by running `ani-cli -U`**

**Metadata (please complete the following information)**
Version: 4.8.11
OS: Windows 10, WSL 1 Ubuntu
Shell: dash, Windows Terminal 
Anime: Any

**Describe the bug**
MPV seems to not be accessible by ani-clu even after installing mpv in multiple ways (Windows Store, Sourceforge, Scoop, Chocolately) both prior and after mpv not being read correctly. All other dependencies are installed, I can run ani-cli perfectly fine in Git Bash, running mpv.exe in WSL opens a mpv windows but running mpv gives a command not found. Even setting mpv as an alias to mpv.exe still gives the error from ani-cli "Program "mpv" not found. Please install it." Below are screenshots for my paths, ani-cli working in Git Bash, and all the errors described happening in WSL. 

**Steps To Reproduce**

1. Run `ani-clil`

**Expected behavior**
Ani-cli should detect mpv.

**Screenshots (if applicable; you can just drag the image onto github. remove the following line if not needed)**
![image](https://github.com/user-attachments/assets/25fd4003-9c00-4b4e-b51b-eee203b75ee9)
![image](https://github.com/user-attachments/assets/a0250b28-d1c4-4a89-bd2e-4e0c8c1f9b5d)
![image](https://github.com/user-attachments/assets/62a62ee5-fb7e-4f74-80f0-29e541e4019b)
![image](https://github.com/user-attachments/assets/b20e64b7-a9b4-45f6-b7ab-23c9efc17fb2)

**Comment by Derisis13** [comment]
WSL 1 is not supported, WSL 2 is. Upgrade to it, or keep using git bash.
