### ISSUE TITLE
An option to list name of all anime matching the query

### ISSUE THREAD

**Issue by adityavishwakarma69** [pystardust/ani-cli#1390]
**Purpose**
This will make ani-cli easy to use with dynamic menus other than rofi

**Description**
Please add a -l or --list flag which lists the name of all anime matching the query

**Additional context**
This will make it possible to write simple scripts to enable the use of different dynamic menus 
one can run the script two times
something like this

```
#!/bin/bash
anime=$(ani-cli -l)|<your dynamic menu>)
ep=$(<your dynamic menu>)
ani-cli $anime -e $ep

```

**Comment by port19x** [comment]
Not easily implemented and I don't see this being all that useful really
