### ISSUE TITLE
I can't update the ani-cli

### ISSUE THREAD

**Issue by Ungotable** [pystardust/ani-cli#1392]
It says "Connection error" even tho I have good conncetion, and when I tried to 
scoop bucket add extras 
scoop update ani-cli

it returns ERROR Failed to clone 'https://github.com/ScoopInstaller/Extras' to 'C:\Users\user\scoop\buckets\extras'.

Error given:

Please check the repository URL or network connection and try again.

Updating Scoop...
Updating Buckets...
INFO  Converting 'main' bucket to git repo...
ERROR 'main' bucket not found.
Failed to remove local 'main' bucket.

**Comment by port19x** [comment]
@ykhan21 can you please verify this is not a packaging bug, just in case?

**Comment by ykhan21** [comment]
@Ungotable, can you re-install scoop? It looks like a scoop error.

**Comment by Ungotable** [comment]
@ykhan21 I'll try it when I got home later

**Comment by Ungotable** [comment]
$ scoop uninstall scoop
WARN  This will uninstall Scoop and all the programs that have been installed with Scoop!
Are you sure? (yN): y
Uninstalling '7zip'
WARN  Couldn't remove ~\scoop\apps\7zip: Cannot remove item C:\Users\user\scoop\apps\7zip\24.07\Codecs: Access to the path 'Codecs' is denied..Exception
Uninstalling 'ani-cli'
Invoke-Installer : Cannot validate argument on parameter 'ProcessorArchitecture'. The argument "" does not belong to
the set "32bit,64bit,arm64" specified by the ValidateSet attribute. Supply an argument that is in the set and then try
the command again.
At C:\Users\user\scoop\apps\scoop\current\bin\uninstall.ps1:45 char:76
+ ... $dir -Manifest $manifest -ProcessorArchitecture $architecture -Uninst ...
+                                                     ~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Invoke-Installer], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Invoke-Installer

WARN  Couldn't remove ~\scoop\apps\ani-cli: Cannot remove item C:\Users\user\scoop\apps\ani-cli\current: Access to the path 'current' is denied..Exception
Uninstalling 'ffmpeg'
WARN  Couldn't remove ~\scoop\apps\ffmpeg: Cannot remove item C:\Users\user\scoop\apps\ffmpeg\7.0.2\fonts: Access to the path 'fonts' is denied..Exception
Uninstalling 'fzf'
Invoke-Installer : Cannot validate argument on parameter 'ProcessorArchitecture'. The argument "" does not belong to
the set "32bit,64bit,arm64" specified by the ValidateSet attribute. Supply an argument that is in the set and then try
the command again.
At C:\Users\user\scoop\apps\scoop\current\bin\uninstall.ps1:45 char:76
+ ... $dir -Manifest $manifest -ProcessorArchitecture $architecture -Uninst ...
+                                                     ~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Invoke-Installer], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Invoke-Installer

WARN  Couldn't remove ~\scoop\apps\fzf: Cannot remove item C:\Users\user\scoop\apps\fzf\current: Access to the path 'current' is denied..Exception
Uninstalling 'git'
Invoke-Installer : Cannot validate argument on parameter 'ProcessorArchitecture'. The argument "" does not belong to
the set "32bit,64bit,arm64" specified by the ValidateSet attribute. Supply an argument that is in the set and then try
the command again.
At C:\Users\user\scoop\apps\scoop\current\bin\uninstall.ps1:45 char:76
+ ... $dir -Manifest $manifest -ProcessorArchitecture $architecture -Uninst ...
+                                                     ~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Invoke-Installer], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Invoke-Installer

WARN  Couldn't remove ~\scoop\apps\git: Cannot remove item C:\Users\user\scoop\apps\git\current: Access to the path 'current' is denied..Exception
Uninstalling 'mpv'
WARN  Couldn't remove ~\scoop\apps\mpv: Cannot remove item C:\Users\user\scoop\apps\mpv\0.38.0\portable_config: Access to the path 'portable_config' is denied..Exception
Uninstalling 'windows-terminal'
WARN  Couldn't remove ~\scoop\apps\windows-terminal: Cannot remove item C:\Users\user\scoop\apps\windows-terminal\1.20.11781.0\settings: Access to the path 'settings' is denied..Exception
Couldn't remove ~\scoop\apps: Cannot remove item C:\Users\user\scoop\apps\7zip\24.07\Codecs: Access to the path 'Codecs' is denied.

**Comment by ykhan21** [comment]
Can you open a cmd window as Administrator and uninstall scoop?
Search cmd in the Windows search bar, right-click it, and select "Run as administator". Then uninstall scoop.
If that doesn't work, do it in a powershell window as administrator.
