### ISSUE TITLE
why is there no Soukyuu no Fafner: Dead Aggressor episode 26?

### ISSUE THREAD

**Issue by candrapersada** [pystardust/ani-cli#1394]
`ani-cli -e 26 "Soukyuu no Fafner: Dead Aggressor"` not found
https://gogoanime3.co/soukyuu-no-fafner-dead-aggressor-episode-26

**Comment by Derisis13** [comment]
Congratulations, you removed the issue template, which was supposed to help us figure out the solution for you. If you can't put in this minimum effort of collaboration, I feel no obligation to help you.
