### ISSUE TITLE
why is there no Soukyuu no Fafner Dead Aggressor episode 26

### ISSUE THREAD

**Issue by candrapersada** [pystardust/ani-cli#1395]
why is there no Soukyuu no Fafner Dead Aggressor episode 26?
`ani-cli -e 26 "Soukyuu no Fafner Dead Aggressor"` not found
https://gogoanime3.co/soukyuu-no-fafner-dead-aggressor-episode-26

**Comment by port19x** [comment]
I can reproduce this, but see nothing special in debug output.

This tool does not scrape gogoanime, so the episode just might not be available on allanime

**Comment by 71zenith** [comment]
![image](https://github.com/user-attachments/assets/7f4a4d9c-a725-4657-9244-b9c6f87aec01)
https://anilist.co/anime/75/Soukyuu-no-Fafner/
There are only 25 official episodes

**Comment by candrapersada** [comment]
![image](https://github.com/user-attachments/assets/71c66c7c-35e7-4b78-95ec-5e2e78128e99)
https://anilist.co/anime/75/Soukyuu-no-Fafner/watch

**Comment by candrapersada** [comment]
@71zenith
why is the anime played by ani-cli different from the anime on gogoanime for example
`gogoanime` `Bakusou Kyoudai Let's & Go WGP`
![image](https://github.com/user-attachments/assets/7d80021b-a5e6-45f6-a729-cfffff68e89e)
but in `ani-cli -e 1 "Bakusou Kyoudai Let's & Go WGP"` only displayed as `Bakusou Kyoudai Let's & Go`?

**Comment by port19x** [comment]
> why is the anime played by ani-cli different from the anime on gogoanime for example

Because we don't scrape gogoanime and haven't since v3.0
