### ISSUE TITLE
use on MPV Framebuffer mode

### ISSUE THREAD

**Issue by kaonkaon** [pystardust/ani-cli#140]
thank you for the great tools, now i able to watch anime from my X-less linux setup

only thing is, the tools play anime perfectly, but my mpv lost its keyboard control. when its playing, mpv wont accept any control so i cant pause, change volume or quit it. i didnt add anything to code, i only added `vo=gpu` and `gpu-context=drm` to mpv config file. the mpv itself run perfectly with those config when i use it by itself or use it with pipe-viewer.

is there someway to fix it? 

thank you

**Comment by ura43** [comment]
As far as I know mpv doesn't support framebuffer mode by default on most distros.
Have you compiled it with support for it?
This seems like its 99% an mpv issue. Please look into their great docs, but I might be able to help you if you give me some more context

**Comment by ura43** [comment]
I'll close this now. Please comment with your solution if you solve this

**Comment by kaonkaon** [comment]
sorry for late replies

so what i wanted to do  was running ani-cli using mpv on tty (not using X or Wayland, just those terminal thing you got if you installed arch). i know its not something it supposed to do but i think its fun if its works

mpv does work on (was) my setup without gui, im using it with pipe-viewer and its working great, playing youtube without gui blown my mind. because its working on its own and with pipe-viewer, so i tried it with ani-cli

it play the anime though, but its not controllable. the mpv refuse to accept the controll what so ever, i cant even quit the mpv using `q` button because it wont accept any controll if tried using ani-cli

i dont know if this mpv issue, its working on it self and with pipe-viewer tho

**Comment by Derisis13** [comment]
> just so you know theres multiple ways to handle this like via an IPC socket or even playerctl commands

Probably outside of the scope of our project
