### ISSUE TITLE
feat: quality selection before playback

### ISSUE THREAD

**Issue by eeelbrens** [pystardust/ani-cli#1400]
**Is your feature request related to a problem? Please describe.**
Sometimes the standard quality settings (in terms of resolution, 360p, 480p, 720p...) aren't available at all, and defaults to the first one listed. Could there be a tag to select quality before episode playback?

**Describe the solution you'd like**
`-Q` tag or passing `-q` with no arguments

**Describe alternatives you've considered**

**Additional context**

**Comment by port19x** [comment]
https://github.com/pystardust/ani-cli/blob/master/ani-cli#L157-L165

As a little easteregg, you could technically do a regex for quality.
That could help if you want either 360p or 480p but don't care for either.
Also `worst` is a valid option.
Default is indeed best quality.

Does this cover your usecase?

**Comment by Derisis13** [comment]
Another thing to consider is that allanime usually has qualities without the p (or i), like 1080, 720, 480, etc. which does also select 1080p, 720p, 480p, etc. respectively.

**Comment by eeelbrens** [comment]
> As a little easteregg, you could technically do a regex for quality. That could help if you want either 360p or 480p but don't care for either. Also `worst` is a valid option. Default is indeed best quality.

@port19x then, any examples for how to do a regex for quality (for example, selecting any of 360p or 480p, or 1080p or 720p for older anime entries)?

**Comment by port19x** [comment]
> selecting any of 360p or 480p, or 1080p or 720p

You just listed all the qualities. I still don't understand what your actual usecase is here

**Comment by eeelbrens** [comment]
i mean either selecting between the two worst and the two best
but even then `-q worst ` can output 720p content on some episodes and 360p on others (e.g. Hellsing). I'm conscious of my data usage (my ISP still enforces relatively small data quotas on me), so it's impossible to know which quality I actually selected without ending up preloading mostly the whole episode

**Comment by port19x** [comment]
Didn't think of data quotas, that makes sense.
The problem is that even if you were to specify the two worst options explicitly, it would fall back to the best available one if those are not available.
So this would indeed need a whole seperate feature.

Alternatively, there might be some mpv setting you can use to limit download bandwidth, giving you time to react without wasting much of your quota

**Comment by eeelbrens** [comment]
I added `cache-secs=30` to my `mpv.conf` for limiting preloading to 1 minute (sans a few seconds). Still, if there's any incentive to add pre-playback quality selection as a feature let me know.

**Comment by port19x** [comment]
Perhaps you can bulk download via public wifi somewhere?
