### ISSUE TITLE
No Results found consistent

### ISSUE THREAD

**Issue by KitsuneKode** [pystardust/ani-cli#1404]
Version: 4.8.11
OS : Arch Linux x86_64
Shell:zsh

**Describe the bug**
There is a consistent no results found error that is being returned. I have used the script for like like 5-6 months but have never faced this issue,

 see screenshot.

**Steps To Reproduce**

1. Run `ani-cli slime`

**Expected behavior**
It should play the episode upon searching the db.
**Screenshots**
![image](https://github.com/user-attachments/assets/a42d9b11-2284-49e3-a8dd-f8b315624078)

**Comment by KitsuneKode** [comment]
![image](https://github.com/user-attachments/assets/02000d40-46fa-4ee7-a1bb-a54978c9bc58)
api seems to be down

**Comment by port19x** [comment]
Should be back up, I can play `flcl`

**Comment by gjyotin305** [comment]
Same issue here

![image](https://github.com/user-attachments/assets/a5739a22-9c85-498f-b686-42009784de48)

**Comment by KitsuneKode** [comment]
> Should be back up, I can play `flcl`

I tried it again doesn't work!!

**Comment by port19x** [comment]
For me it still works. Also v4.8.11.
Tested one piece, flcl and slime

**Comment by 71zenith** [comment]
The api will always show that its down until u provide a working schema

**Comment by 71zenith** [comment]
Can u access allanime.to normally through browser?
If you have access to a vpn, i'd like to see the result

**Comment by KitsuneKode** [comment]
> Can u access allanime.to normally through browser? If you have access to a vpn, i'd like to see the result

actually i have configured my chrome so thatt it bypasses all the checks and through chrome, I can access allanime.to but through firefox i can't do the same, I have seen the agent is been set to firefox, changing it to chrome will help?

**Comment by 71zenith** [comment]
you can certainly try
Also can u send the output of `sh -x $(which ani-cli) serial lain -e 5`

**Comment by gjyotin305** [comment]
Here is the output of 
```bash
sh -x $(which ani-cli) serial lain -e 5
```

Output:
```bash
+ version_number=4.8.11
+ agent='Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/121.0'
+ allanime_refr=https://allanime.to
+ allanime_base=allanime.day
+ allanime_api=https://api.allanime.day
+ mode=sub
+ download_dir=.
+ quality=best
+ case "$(uname -a)" in
++ uname -a
+ player_function=mpv
+ no_detach=0
+ exit_after_play=0
+ use_external_menu=0
+ skip_intro=0
+ skip_title=
+ '[' -t 0 ']'
+ hist_dir=/home/gjyotin305/.local/state/ani-cli
+ '[' '!' -d /home/gjyotin305/.local/state/ani-cli ']'
+ histfile=/home/gjyotin305/.local/state/ani-cli/ani-hsts
+ '[' '!' -f /home/gjyotin305/.local/state/ani-cli/ani-hsts ']'
+ search=scrape
+ '[' 4 -gt 0 ']'
+ case "$1" in
++ printf %s ' serial'
++ sed 's|^ ||;s| |+|g'
+ query=serial
+ shift
+ '[' 3 -gt 0 ']'
+ case "$1" in
++ printf %s 'serial lain'
++ sed 's|^ ||;s| |+|g'
+ query=serial+lain
+ shift
+ '[' 2 -gt 0 ']'
+ case "$1" in
+ '[' 2 -lt 2 ']'
+ ep_no=5
+ '[' -n '' ']'
+ shift
+ shift
+ '[' 0 -gt 0 ']'
+ '[' 0 = 0 ']'
+ multi_selection_flag=-m
+ '[' 0 = 1 ']'
+ printf '\33[2K\r\033[1;34mChecking dependencies...\033[0m\n'
Checking dependencies...
+ dep_ch curl sed grep
+ for dep in "$@"
+ command -v curl
+ for dep in "$@"
+ command -v sed
+ for dep in "$@"
+ command -v grep
+ '[' 0 = 1 ']'
+ '[' -z '' ']'
+ dep_ch fzf
+ for dep in "$@"
+ command -v fzf
+ case "$player_function" in
+ dep_ch mpv
+ for dep in "$@"
+ command -v mpv
+ case "$search" in
+ '[' 0 = 0 ']'
+ '[' -z serial+lain ']'
+ '[' scrape = nextep ']'
++ printf %s serial+lain
++ sed 's| |+|g'
+ query=serial+lain
++ search_anime serial+lain
++ search_gql='query(        $search: SearchInput        $limit: Int        $page: Int        $translationType: VaildTranslationTypeEnumType        $countryOrigin: VaildCountryOriginEnumType    ) {    shows(        search: $search        limit: $limit        page: $page        translationType: $translationType        countryOrigin: $countryOrigin    ) {        edges {            _id name availableEpisodes __typename       }    }}'
++ curl -e https://allanime.to -s -G https://api.allanime.day/api --data-urlencode 'variables={"search":{"allowAdult":false,"allowUnknown":false,"query":"serial+lain"},"limit":40,"page":1,"translationType":"sub","countryOrigin":"ALL"}' --data-urlencode 'query=query(        $search: SearchInput        $limit: Int        $page: Int        $translationType: VaildTranslationTypeEnumType        $countryOrigin: VaildCountryOriginEnumType    ) {    shows(        search: $search        limit: $limit        page: $page        translationType: $translationType        countryOrigin: $countryOrigin    ) {        edges {            _id name availableEpisodes __typename       }    }}' -A 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/121.0'
++ sed 's|Show|\
|g'
++ sed -nE 's|.*_id":"([^"]*)","name":"([^"]*)".*sub":([1-9][^,]*).*|\1	\2 (\3 episodes)|p'
+ anime_list=
+ '[' -z '' ']'
+ die 'No results found!'
+ printf '\33[2K\r\033[1;31m%s\033[0m\n' 'No results found!'
No results found!
+ exit 1
```

**Comment by 71zenith** [comment]
Does this produce any tangible output 
```
curl -e https://allanime.to -s -G https://api.allanime.day/api --data-urlencode 'variables={"search":{"allowAdult":false,"allowUnknown":false,"query":"serial+lain"},"limit":40,"page":1,"translationType":"sub","countryOrigin":"ALL"}' --data-urlencode 'query=query(        $search: SearchInput        $limit: Int        $page: Int        $translationType: VaildTranslationTypeEnumType        $countryOrigin: VaildCountryOriginEnumType    ) {    shows(        search: $search        limit: $limit        page: $page        translationType: $translationType        countryOrigin: $countryOrigin    ) {        edges {            _id name availableEpisodes __typename       }    }}' -A 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36'
```

**Comment by KitsuneKode** [comment]
` vim /usr/bin/ani-cli
❯ sh -x $(which ani-cli) serial lain -e 5
+ version_number=4.8.12
+ agent='Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/121.0'
+ allanime_refr=https://allanime.to
+ allanime_base=allanime.day
+ allanime_api=https://api.allanime.day
+ mode=sub
+ download_dir=.
+ quality=best
+ case "$(uname -a)" in
++ uname -a
+ player_function=mpv
+ no_detach=0
+ exit_after_play=0
+ use_external_menu=0
+ skip_intro=0
+ skip_title=
+ '[' -t 0 ']'
+ hist_dir=/home/kitsunekode/.local/state/ani-cli
+ '[' '!' -d /home/kitsunekode/.local/state/ani-cli ']'
+ histfile=/home/kitsunekode/.local/state/ani-cli/ani-hsts
+ '[' '!' -f /home/kitsunekode/.local/state/ani-cli/ani-hsts ']'
+ search=scrape
+ '[' 4 -gt 0 ']'
+ case "$1" in
++ printf %s ' serial'
++ sed 's|^ ||;s| |+|g'
+ query=serial
+ shift
+ '[' 3 -gt 0 ']'
+ case "$1" in
++ printf %s 'serial lain'
++ sed 's|^ ||;s| |+|g'
+ query=serial+lain
+ shift
+ '[' 2 -gt 0 ']'
+ case "$1" in
+ '[' 2 -lt 2 ']'
+ ep_no=5
+ '[' -n '' ']'
+ shift
+ shift
+ '[' 0 -gt 0 ']'
+ '[' 0 = 0 ']'
+ multi_selection_flag=-m
+ '[' 0 = 1 ']'
+ printf '\33[2K\r\033[1;34mChecking dependencies...\033[0m\n'
Checking dependencies...
+ dep_ch curl sed grep
+ for dep in "$@"
+ command -v curl
+ for dep in "$@"
+ command -v sed
+ for dep in "$@"
+ command -v grep
+ '[' 0 = 1 ']'
+ '[' -z '' ']'
+ dep_ch fzf
+ for dep in "$@"
+ command -v fzf
+ case "$player_function" in
+ dep_ch mpv
+ for dep in "$@"
+ command -v mpv
+ case "$search" in
+ '[' 0 = 0 ']'
+ '[' -z serial+lain ']'
+ '[' scrape = nextep ']'
++ printf %s serial+lain
++ sed 's| |+|g'
+ query=serial+lain
++ search_anime serial+lain
++ search_gql='query(        $search: SearchInput        $limit: Int        $page: Int        $translationType: VaildTranslationTypeEnumType        $countryOrigin: VaildCountryOriginEnumType    ) {    shows(        search: $search        limit: $limit        page: $page        translationType: $translationType        countryOrigin: $countryOrigin    ) {        edges {            _id name availableEpisodes __typename       }    }}'
++ curl -e https://allanime.to -s -G https://api.allanime.day/api --data-urlencode 'variables={"search":{"allowAdult":false,"allowUnknown":false,"query":"serial+lain"},"limit":40,"page":1,"translationType":"sub","countryOrigin":"ALL"}' --data-urlencode 'query=query(        $search: SearchInput        $limit: Int        $page: Int        $translationType: VaildTranslationTypeEnumType        $countryOrigin: VaildCountryOriginEnumType    ) {    shows(        search: $search        limit: $limit        page: $page        translationType: $translationType        countryOrigin: $countryOrigin    ) {        edges {            _id name availableEpisodes __typename       }    }}' -A 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/121.0'
++ sed 's|Show|\
|g'
++ sed -nE 's|.*_id":"([^"]*)","name":"([^"]*)".*sub":([1-9][^,]*).*|\1	\2 (\3 episodes)|p'
+ anime_list=
+ '[' -z '' ']'
+ die 'No results found!'
+ printf '\33[2K\r\033[1;31m%s\033[0m\n' 'No results found!'
No results found!
+ exit 1`

**Comment by gjyotin305** [comment]
> Does this produce any tangible output
> 
> ```
> curl -e https://allanime.to -s -G https://api.allanime.day/api --data-urlencode 'variables={"search":{"allowAdult":false,"allowUnknown":false,"query":"serial+lain"},"limit":40,"page":1,"translationType":"sub","countryOrigin":"ALL"}' --data-urlencode 'query=query(        $search: SearchInput        $limit: Int        $page: Int        $translationType: VaildTranslationTypeEnumType        $countryOrigin: VaildCountryOriginEnumType    ) {    shows(        search: $search        limit: $limit        page: $page        translationType: $translationType        countryOrigin: $countryOrigin    ) {        edges {            _id name availableEpisodes __typename       }    }}' -A 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36'
> ```

Empty output as you can see in the screenshot below.
![image](https://github.com/user-attachments/assets/22b1332b-0e35-4251-a7fe-c151c2d025ab)

**Comment by 71zenith** [comment]
ok then changing user agent also doesnt work

**Comment by gjyotin305** [comment]
yup

**Comment by KitsuneKode** [comment]
> ok then changing user agent also doesnt work

same issue with me

**Comment by 71zenith** [comment]
can u try with a vpn

**Comment by KitsuneKode** [comment]
> can u try with a vpn

Firefox blocks all the webacess on the use of vpn, and yea I connected to my phones data, it worked! 

Is there any way to remove firefox from the script from all way it is being used?

**Comment by 71zenith** [comment]
try removing firefox from user agent

**Comment by port19x** [comment]
I'm closing this as we can still not reproduce the issue

**Comment by KitsuneKode** [comment]
@port19x can we have the proxy urls for curl fetching the videos?
