### ISSUE TITLE
why is the anime on ani-cli not the same as on gogoanime?

### ISSUE THREAD

**Issue by candrapersada** [pystardust/ani-cli#1405]
Why is the anime playing on `ani-cli` not the same as on `gogoanime`?
for example
`ani-cli -e 1 "Bakusou Kyoudai Let's & Go WGP"`
https://gogoanime3.co/bakusou-kyoudai-lets-go-wgp-episode-1

**Comment by Derisis13** [comment]
Because we do not scrape gogoanime. If you check the script, `base_url` is set to `allanime.day`

**Comment by candrapersada** [comment]
but why can't play `Bakusou Kyoudai Let's & Go WGP` in a`ni-cli`?

**Comment by Derisis13** [comment]
You're the best troll we had as you are the first and only one.

**Comment by candrapersada** [comment]
why is the anime played by ani-cli different from the anime on gogoanime for example
`gogoanime` `Bakusou Kyoudai Let's & Go WGP`
but in `ani-cli -e 1 "Bakusou Kyoudai Let's & Go WGP"` only displayed as `Bakusou Kyoudai Let's & Go`?
