### ISSUE TITLE
flag for disabling subtitles

### ISSUE THREAD

**Issue by hatosu** [pystardust/ani-cli#1407]
**Is your feature request related to a problem? Please describe.**
There is no option to turn off subtitles. As a speaker of the language, I don't need both English and Japanese.

**Describe the solution you'd like**
A flag used specifically for disabling subtitles.

**Describe alternatives you've considered**
I have tried finding other CLI tools that would scrape shows/anime for me and not force subtitles, but all have proven to be finicky and not as smooth as ani-cli :(

**Additional context**
If this feature was implemented, it would be very nice :)

(thank you in advance)

**Comment by Derisis13** [comment]
Unfortunately the source of the anime (allanime) provides them with hardsubs, and thus it's impossible to turn them off.
