### ISSUE TITLE
Use flatpak mpv on other distros

### ISSUE THREAD

**Issue by randomazzy11** [pystardust/ani-cli#1408]
**Is your feature request related to a problem? Please describe.**

I use fedora silverblue, which is immutable like steamos
and i used the install script for steamos to install ani-cli
but then mpv didnt work, and i quickly looked at the code and saw
that flatpak mpv is only used when steamos is detected.

**Describe the solution you'd like**

Maybe check first for mpv in the regular path first
and then maybe if its not there check for
flatpak.

**Describe alternatives you've considered**

Add a flatpak flag (since i didnt see any) to force
using flatpak mpv.
I also considered modifying a line in the code by changing
the normal mpv under "linux" to be flatpak mpv but i realised
that an update might wipe my changes.
I also would be able to just download an episode
and play it that way but thats not really elegant

**Additional context**

I could install the ani-cli package using rpm-ostree (which is like dnf but for silverblue) 
but i dont really like using rpm-ostree and i only install apps using it if i really have to

**Comment by Derisis13** [comment]
It surprises me that we don't have an argument for flatpak, I'll implement it once I get home. 
While I do that, use the env var `ANI_CLI_PLAYER` as a workaround.
`env ANI_CLI_PLAYER="flatpak_mpv" ani-cli`

**Comment by randomazzy11** [comment]
Thanks :) some people need that flatpak argument

**Comment by randomazzy11** [comment]
Thanks :) some people need that flatpak argument
