### ISSUE TITLE
FEAT:Continue where you left off

### ISSUE THREAD

**Issue by urizennnn** [pystardust/ani-cli#1409]
**Is your feature request related to a problem? Please describe.**
So it is sort of related to a problem that i would love you work on or try at least. I just get tired looking through where i stopped somthing similar to vlc feature.

**Describe the solution you'd like**
So basically when a user comes back to their anime sesh, if a user has already made some progress on a certain anime it should ask to continue watching from that anime's episode

**Additional context**
I would love to work on it.

**Comment by Derisis13** [comment]
Is this about continuing episodes from where it was stopped?
If so, we tried implementing it twice, but never finised it because we found the solutions to be too complex for our small script.
Still we'll listen to your input on this feature but I can make no promises on it being merged.

**Comment by urizennnn** [comment]
> Is this about continuing episodes from where it was stopped? If so, we tried implementing it twice, but never finised it because we found the solutions to be too complex for our small script. Still we'll listen to your input on this feature but I can make no promises on it being merged.
Can i be in the on the contribution?
and also what's the opinion on add an external script to handle that.

**Comment by urizennnn** [comment]
And i sort of have an idea on something what if the the app writes to the users disk with   a json file with animes user has visitied and then saves its episode how about that

**Comment by port19x** [comment]
You don't mean `ani-cli -c`, do you?
Continuing an episode where it left off already works and is default behaviour of the iina player.
I suspect there is an mpv option to enable this for you as well

**Comment by urizennnn** [comment]
> You don't mean `ani-cli -c`, do you? Continuing an episode where it left off already works and is default behaviour of the iina player. I suspect there is an mpv option to enable this for you as well

no not that, although its related but not on point. If an unhinged individual such as myself views 2 animes at once and i viewed anime1 now ```ani-cli -c``` could work if i want to visit back/continue from anime1 but what if i want to continue anime2?. That's where the whole feature request spawns from.

**Comment by urizennnn** [comment]
> You don't mean `ani-cli -c`, do you? Continuing an episode where it left off already works and is default behaviour of the iina player. I suspect there is an mpv option to enable this for you as well

oh wait that works
