### ISSUE TITLE
VLC can’t open the file

### ISSUE THREAD

**Issue by bokcho2** [pystardust/ani-cli#1412]
## **Make sure you are on the latest version by running `ani-cli -U`**

**Metadata (please complete the following information)**
Version: [e.g. 4.7.6, run `ani-cli -V` to find out]
OS: [e.g. Windows 10 / Linux Mint 20.3]
Shell: [e.g. zsh, run `readlink /bin/sh` to get your shell]
Anime: [e.g. flcl] (if applicable)

**Describe the bug**
Downloading is broken.
It says something about an unsupported protocol, see screenshot.

**Steps To Reproduce**

1. Run `ani-cli’
2. search for anime
3. Choose episode
4. press vlc link

**Expected behavior**
video should play in vlc
![IMG_8737](https://github.com/user-attachments/assets/9aa8f703-b7cb-47c9-b5fe-f8746a9dd55f)

**Comment by Derisis13** [comment]
Please fill in the informations in the template. It's very hard to guess them.

**Comment by port19x** [comment]
The metadata would help, yes.
We can see that you're on iOS using iSH as your shell.
Since iOS support is somewhat recent, we can also be sure you're using an at least reasonably up-to-date version.

What I'm most interested in is what anime this was and if it is reproducible with other anime

**Comment by bokcho2** [comment]
sorry, i wasn’t sure how to go about explaining that i was using iSH and that it using “ani-cli -v” was resulting in an anime search instead of showing the version.

but as for anime’s, it’s anything. i tried inuyasha, sailor moon, yowamushi pedal, dungeon meshi… nothing seems to work.

**Comment by Lockl00p** [comment]
> sorry, i wasn’t sure how to go about explaining that i was using iSH and that it using “ani-cli -v” was resulting in an anime search instead of showing the version.
> 
> but as for anime’s, it’s anything. i tried inuyasha, sailor moon, yowamushi pedal, dungeon meshi… nothing seems to work.

Are you sure you’re on the latest version? This issue was recently fixed.
Also, try ‘ani-cli -V’

**Comment by bokcho2** [comment]
i’m on this version
![IMG_8851](https://github.com/user-attachments/assets/c2a5ee51-69fd-4846-b350-858744821e36)

**Comment by Lockl00p** [comment]
Ah, I see. You are on an old version.
Try running “apk add patch”, run “ani-cli -U”, then try it again!

**Comment by bokcho2** [comment]
worked beautifully 😭😭 thanks so much

**Comment by port19x** [comment]
Thx @Lockl00p
