### ISSUE TITLE
Keeps showing no results found even after updating and re-installing everything (Mac)

### ISSUE THREAD

**Issue by miniPilot1800** [pystardust/ani-cli#1414]
## **Make sure you are on the latest version by running `ani-cli -U`**

**Metadata (please complete the following information)**
Version: 4.9.0
OS: Mac Sonoma 14.6.1
Shell: zsh
Anime: All

**Describe the bug**
It's been happening for a while, but no matter what I anime I look for it says no results found

![Screenshot 2024-09-07 at 10 18 07 PM](https://github.com/user-attachments/assets/2bc3eab7-2f90-4cd6-a2e5-6c1a69f0d187)

**Steps To Reproduce**

1. Run `ani-cli -d flcl`
2. Choose 2 (fooly-cooly)
3. Choose episode 1

**Expected behavior**
Episode list should show up

**Additional context**
I've deleted homebrew, ani-cli, and java from my system and redownloaded it all as that normally helps, but it keeps showing that no results are found.

**Comment by 71zenith** [comment]
can u report the output of `sh -x $(which ani-cli) serial lain -e 5`

**Comment by 71zenith** [comment]
> Additional context
I've deleted homebrew, ani-cli, and java from my system and redownloaded it all as that normally helps, but it keeps showing that no results are found.

java :sob:

**Comment by Lockl00p** [comment]
> > Additional context
> > I've deleted homebrew, ani-cli, and java from my system and redownloaded it all as that normally helps, but it keeps showing that no results are found.
> 
> java 😭

Let’s be fair here, People like Minecraft (and some are masochistic enough to try to make a Minecraft Mod.)

**Comment by miniPilot1800** [comment]
Here is the output of sh -x $(which ani-cli) serial lain -e 5

![Screenshot 2024-09-08 at 6 04 38 PM](https://github.com/user-attachments/assets/d0837288-1256-4193-b754-84d79603ff23)

About the Java, ani-cli always gives me heck over the java runtime thing (I'm not super techy)

**Comment by 71zenith** [comment]
Can you access allanime.to = from your browser

**Comment by JowMK** [comment]
I also get the same error
But the `-U` option gives me error too
![imagen](https://github.com/user-attachments/assets/fbfb6416-6fff-4a2f-a79c-e2ccffc87128)

> Can you access allanime.to = from your browser

I can access `allanime.to` from my browser, but it redirects to `allmanga.to`. Never used the site before so I don't know if normal.

**Comment by ykhan21** [comment]
@JowMK, open a new issue for WSL. Also, reinstall ani-cli and follow the ani-cli installation guide for WSL in the README.

**Comment by JowMK** [comment]
Reinstalling it 6-7 times did the trick, maybe something got corrupted

**Comment by port19x** [comment]
Closing this since OP hasn't reported back within a month
