### ISSUE TITLE
--quality flag picks only 1080p

### ISSUE THREAD

**Issue by Sx1Fl0NdqlkM6N4s2pswXKUI0k9FKTaOckLbNXu** [pystardust/ani-cli#1417]
## **Make sure you are on the latest version by running `ani-cli -U`**

**Metadata (please complete the following information)**
Version: 4.9.0 (from source)
OS: Debian Testing
Shell: zsh 5.9
Anime: any old/new (allanime website has quality options for the same anime)

**Describe the bug**
ani-cli --quality 720 "Isekai Shikkaku"
ani-cli --quality worst "Isekai Shikkaku"
as well as changing quality after selecting episode in fzf menu with 3 different available options.

All above launch 1080p video (mpv info screenshoot, under "Video:", "Resolution:" section).

**Screenshots**
![image1](https://github.com/user-attachments/assets/97f78c6b-4c4a-4632-8742-7fdc9151df57)
![image2](https://github.com/user-attachments/assets/db10f927-0980-4924-b55b-1ba4db57f1ce)

**Comment by Derisis13** [comment]
As you figured out, this episode has only 1080p links. This is not a limitation of ani-cli, but allanime. There's nothing we can do about this.
