### ISSUE TITLE
Input can't be opened

### ISSUE THREAD

**Issue by Pacutacatete100** [pystardust/ani-cli#142]
Whenever I try to watch an episode using this CLI, I get an error from VLC saying "Your input can't be opened: VLC is unable to open the MRL ".  I've already tried resetting VLC preferences, reinstalling, and turning windows firewall off and nothing seems to be working. 
![screenshot of error](https://user-images.githubusercontent.com/35910179/142981925-c5e5058e-c11c-409a-a3f3-b429ccca5333.PNG)

**Comment by joshualagat** [comment]
Try Dink4n's fix on #139

**Comment by Pacutacatete100** [comment]
Unfortunately, that did not work :(

**Comment by Dink4n** [comment]
Possible duplicate of #134

**Comment by ura43** [comment]
Probably duplicate of #134 
Closing
