### ISSUE TITLE
Receive "Episode not released!" even though the episode is released on allanime.to

### ISSUE THREAD

**Issue by Lugas7** [pystardust/ani-cli#1429]
Version: 4.9.0
OS: Arch Linux
Shell: bash
Anime: Kami No Tou (Tower of god season 2)

** description **

Get "Episode not released!" when the episode is realeased on allanime.to.

**Steps To Reproduce**

Happens when I try to watch an episode which is tracked in ani-cli and can thence be selected, but it fails. Think it has something to do with the episode only recently being released (as of my attempt, the episode has only been released 5 hours ago on allanime.to)

**Expected behavior**
Should be able to watch episode

**Comment by HirschBerge** [comment]
Also happening on 4.9.0 on NixOS unstable. Has been happening with every episode released in the last 24-36 hours or so that I'm watching. Tower of God, Monogatari, Fairy Tail 100YQ, etc.
Saw something similar a few weeks ago that eventually resolved itself I believe.

**Comment by 71zenith** [comment]
We scrape only a small subset of video providers from allanime. Most of the times when a new episode is released it only has providers we dont scrape.

**Comment by Lugas7** [comment]
Ah ok, is there an issue for increasing the number of providers scraped? I might be interested in attempting developing that at some point when I have time

**Comment by 71zenith** [comment]
> Ah ok, is there an issue for increasing the number of providers scraped? I might be interested in attempting developing that at some point when I have time

No mostly, as long as the code isnt too complicated. 
you can start by looking at the current scrapers https://github.com/pystardust/ani-cli/blob/5daa876a3c88544ee7a21aac4704e14be519c25a/ani-cli#L131-L197

**Comment by 71zenith** [comment]
Generally we don't add more cause the current providers are the most stable and don't break unexpectedly

**Comment by Lugas7** [comment]
One quick improvement would be to change the error message in this event, it is in fact incorrect to say that the episode is not released yet. Perhaps something along the lines of: "episode has not been released in a provider we support" may be better.

I would not have made this issue as a bug if I got a better error message.
