### ISSUE TITLE
overriding mode 0444 (r--r--r--)?

### ISSUE THREAD

**Issue by port19x** [pystardust/ani-cli#1431]
### Discussed in https://github.com/pystardust/ani-cli/discussions/1430

<div type='discussions-op-text'>

<sup>Originally posted by **amolvyas-6** September 26, 2024</sup>
Whenever i am playing an episode, the video is getting played but i am also getting this error message:
```
cp: cannot create regular file '/c/Users/<myUserName>/.local/state/ani-cli/ani-hsts.new': Permission denied
/c/Users/<myUserName>/scoop/apps/ani-cli/current/ani-cli: line 240: /c/Users/<myUserName>/.local/state/ani-cli/ani-hsts.new: Permission denied
mv: replace '/c/Users/<myUserName>/.local/state/ani-cli/ani-hsts', overriding mode 0444 (r--r--r--)?
```
BTW i am using windows 11 and have downloaded ani-cli with scoop.</div>

**Comment by ykhan21** [comment]
@port19x, isn't this fixed. @amolvyas-6 replied to your comment saying so.

**Comment by port19x** [comment]
I didn't have internet for a little while
