### ISSUE TITLE
[Feature Proposal] Trakt integration

### ISSUE THREAD

**Issue by azureorangexyz** [pystardust/ani-cli#1432]
As time is something we anime-watchers don't have, I think it's fair to point out that it is too time consuming to log watched episodes to trakt manually. That's why I think an integration of a trakt client would be something nice.

**Describe the solution you'd like**
Add a flag that enables ani-cli to send information about the watched episodes to an external trakt client.

**Describe alternatives you've considered**
An alternative would be to do this the old-school way - e. g. manually.

**Additional context**
Trakt is an online service to track what you watched and when you did it.

This is just a suggestion and I'd like to see what response this issue gets.
If this feature is something that is wished by the people, I could imagine implementing it myself.

**Sidenote**: I did not yet find a terminal trakt client that would suit the idea, so if anyone has suggestions or uses trakt in the terminal, let me know.

**Comment by port19x** [comment]
We do integrate nicely with [trackma](https://github.com/z411/trackma), would that cover your usecase?

**Comment by port19x** [comment]
Also, if you don't have any online profiles for anime tracking, ani-cli comes with it's own history system out of the box that would be enough for single-device usage.
see `ani-cli -c`
