### ISSUE TITLE
bug: quit not working as intended

### ISSUE THREAD

**Issue by Surajsm60720** [pystardust/ani-cli#1433]
## *Make sure you are on the latest version by running ani-cli -U*

*Metadata (please complete the following information)*
Version: 4.9.2
OS: Fedora 39
Shell: Bash
Anime: Any anime

*Describe the bug*
even after choosing quit the video still plays

*Steps To Reproduce*

1. Run ani-cli
2. Write any anime name
3. Choose any episode
4. before the video loads press quit

*Expected behavior*
it should not play the video

*Screenshots (if applicable; you can just drag the image onto github. remove the following line if not needed)*

*Additional context*
when the video is playing it should close te video but it simply exits the ani-cli command

**Comment by 71zenith** [comment]
this is by design

**Comment by port19x** [comment]
Yep, this is behaving as intended
