### ISSUE TITLE
Both English subtitle and dub

### ISSUE THREAD

**Issue by jonnjonnjo** [pystardust/ani-cli#1439]
**Problem**
I've tried to use the ani-cli in both eng-sub and eng-dub. I know that the subtitle is baked into the video. When using the eng-sub one, the only option of audio is only the japanese one. I want to try to have both eng-dub and eng-sub. Is that possible ?

**Solution**
I think the feasible one is to add additional audio option in the eng-sub one.

**Comment by HirschBerge** [comment]
FAQ

**Comment by jonnjonnjo** [comment]
hmnn i'm sorry for bothering you again, is it not possible? because I don't see it in faq ....

**Comment by port19x** [comment]
Well this one is actually feasible, but will not be a part of ani-cli.
What you could do is download an anime in advance and then use a free tool like ffmpeg to overlay the audio of the dub version over the video of the sub version

**Comment by HirschBerge** [comment]
> Well this one is actually feasible, but will not be a part of ani-cli.
> What you could do is download an anime in advance and then use a free tool like ffmpeg to overlay the audio of the dub version over the video of the sub version

So I have actually tried this. There's a few shows where I like the sun and would just prefer to be able to AFK a game or something and watch on a second screen. So I thought I'd just add a second audio track so I can choose my language. In theory, it works. What I ran into is that even if you get sub and dub from the same source, what happens is that it doesn't line up correctly the majority of the time. This is often from languages just being different and that the little intro from the streaming platform and/or distribution company don't line up 1:1 so you could be a second or more off. Which is fixable, but rather a manual PITA.

**Comment by port19x** [comment]
Ah, I could see how that would be an issue

**Comment by port19x** [comment]
Either way, this ain't gonna happen
