### ISSUE TITLE
MPV Not open after selecting an episode 

### ISSUE THREAD

**Issue by wibube** [pystardust/ani-cli#144]
Hi, I'm new to linux, and now i'm confused at what to do to solved this, even thou i have install all the dependencies. Did i do something wrong or ? 

fyi i have read the other post that talk about the same problem, but tbh idk how to do that (i mean to executed the solution that been given in that post)

**Comment by jnishwanth** [comment]
Then you could wait till the the changes suggested by @Dink4n and made by @Derisis13(in the other post you talked about #139) are approved and the main script is updated to use the app.

If you are interested in fixing it, it is just copying and pasting a few lines of text into the ani-cli file after opening it in a text editor before installing or following other instructions that you maybe have done before. Make sure to uninstall before you do this as well.

If you don't want to install, you could just run the script without installing by going to the ani-cli folder you cloned/downloaded in a terminal, using `cd` command,
then type in `chmod +x ani-cli`, then to finally run it, `./ani-cli`

**Comment by wibube** [comment]
alright thank you for the suggestion, imma try to do that

**Comment by Reaper176** [comment]
Wibube, Did you ever manage to get this working. If not I would be more than happy to help you out over a discord. I know how annoying it can be to come to Linux expecting a little bit of help and then being told rtfm. XD
