### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by sandibabsel** [pystardust/ani-cli#1442]
## **Make sure you are on the latest version by running `ani-cli -U`**

**Metadata (please complete the following information)**
Version: [4.9.2]
OS: [android]
Shell: [e.g. zsh, run `readlink /bin/sh` to get your shell]
Anime: [Naruto ] (if applicable)

**Describe the bug**
Cant coonect to media player
Checking of players on Android is disabled
logger: cannot connect: Permission denied

**Steps To Reproduce**

1. Run `ani-cli -d flcl`
2. Choose 2 (fooly-cooly)
3. Choose episode 1

**Expected behavior**
Downloading should work

**Screenshots (if applicable; you can just drag the image onto github. remove the following line if not needed)**
![image](https://user-images.githubusercontent.com/82055622/151030428-2e78d15f-4ba9-4d86-b6f3-8307557b4b29.png)
![Screenshot_2024-10-16-12-33-17-98_84d3000e3f4017145260f7618db1d683](https://github.com/user-attachments/assets/1ab3a8fc-6ee9-4765-bb37-b0a3b375b9ad)

**Additional context**

**Comment by 71zenith** [comment]
default image that he forgot to remove

**Comment by sandibabsel** [comment]
I need mpv? To use ani-cli?

**Comment by sandibabsel** [comment]
Thanks its worked

**Comment by port19x** [comment]
Nice
