### ISSUE TITLE
ani-cli not working on Windows 10

### ISSUE THREAD

**Issue by somewhat69** [pystardust/ani-cli#1444]
## **Make sure you are on the latest version by running `ani-cli -U`**

**Metadata (please complete the following information)**
Version: ani-cli 4.9 given by scoop
OS: Windows 10
Shell: Windwos Powershell
Anime: [e.g. flcl] (if applicable)

**Describe the bug**
it just doesn't open
![image](https://github.com/user-attachments/assets/64f1c027-29f6-4273-babd-b2e4d24352b2)

**Steps To Reproduce**

1. Run `ani-cli`

**Expected behavior**
It should normally work

**Additional context**
i updated fzf and ani-cli yesterday and this happened

**Comment by ykhan21** [comment]
@somewhat69, uninstall ani-cli (just to be safe) and follow the Windows guide in the README.
You should be accessing ani-cli through bash + Windows Terminal. scoop + powershell causes WSL to hijack sh scripts.

If you really want to use ani-cli with powershell or cmd, edit `C:/Users/USERNAME/scoop/shims/ani-cli.cmd` in notepad so it looks like this:

- If you installed git via scoop:
```cmd
@"%USERPROFILE%\scoop\apps\git\current\bin\bash.exe" "%USERPROFILE%\scoop\apps\ani-cli\current\ani-cli" %*
```

- If you installed git via the installer or winget:
```cmd
@"C:\Program Files\Git\bin\bash.exe" "%USERPROFILE%\scoop\apps\ani-cli\current\ani-cli" %*
```

Why?

When installed with scoop, running `ani-cli` in powershell or cmd runs `C:/Users/USERNAME/scoop/shims/ani-cli.cmd`. This is a scoop-constructed shim, which the ani-cli maintainers have no control over. It also changes randomly.
This `ani-cli.cmd` shim runs the actual `ani-cli` sh file located at `C:/Users/USERNAME/scoop/apps/ani-cli/current/ani-cli`.
However, the cmd shim uses WSL bash in the to run the actual sh file.
It needs to use Git Bash's bash.

**Comment by ykhan21** [comment]
Open a new issue if this does not work.

**Comment by somewhat69** [comment]
thanks it worked
