### ISSUE TITLE
next/previous options don't work on macOS

### ISSUE THREAD

**Issue by ketsomp** [pystardust/ani-cli#1451]
## **Make sure you are on the latest version by running `ani-cli -U`**

**Metadata (please complete the following information)**
Version: 4.9.5
OS: macOS 15.1
Shell: /bin/zsh
Anime: -

**Describe the bug**
when an episode is playing, upon selecting the "next" or "previous" option, the terminal window redirects to the previous page, displays the "Links Fetched" message thrice, but fails to open a new IINA window for the requested episode.

**Steps To Reproduce**

1. Run ani-cli -c
2. Choose an episode
3. Select next/previous

**Expected behavior**
the next/previous episode plays once the corresponding option is selected

**Screenshots (if applicable; you can just drag the image onto github. remove the following line if not needed)**
<img width="576" alt="Screenshot 2024-11-09 at 5 15 41 PM" src="https://github.com/user-attachments/assets/35dd4088-5fed-4bee-8cb3-37ca0e7c3403">

**Additional context**

**Comment by port19x** [comment]
Can't reproduce on Linux with flcl.
Both next and previous work for me

**Comment by Derisis13** [comment]
Next and previous won't play until the current player is closed. Consider this a limitation of our script (it makes implementing range selection much easier) or a feature (limit of players open at any given time), whichever makes you sleep better.

**Comment by port19x** [comment]
Oh yeah, that is true as well. Have you run into this?

**Comment by ketsomp** [comment]
You're right, next and previous work perfectly fine when I close that instance of IINA. I just assumed that it would work when the current player was open, since the replay button worked as I expected. Thanks for the clarification!
