### ISSUE TITLE
Permission Denied

### ISSUE THREAD

**Issue by oksvuz** [pystardust/ani-cli#1452]
Trying to download but I am a little lost

Heres the message I keep getting: 

Cloning into 'ani-cli'...
remote: Enumerating objects: 2452, done.
remote: Counting objects: 100% (747/747), done.
remote: Compressing objects: 100% (249/249), done.
remote: Total 2452 (delta 625), reused 583 (delta 498), pack-reused 1705 (from 1)
Receiving objects: 100% (2452/2452), 11.70 MiB | 14.82 MiB/s, done.
Resolving deltas: 100% (1467/1467), done.
cp: /usr/local/bin/ani-cli: Permission denied

I looked for the file using the find command and heres what I got: 
omarcamara@RamatouayesiMac ani-cli % pwd
/Users/omarcamara/.local/state/ani-cli
omarcamara@RamatouayesiMac ani-cli % ls /Users/omarcamara/.local/state/ani-cli

ani-hsts

<img width="567" alt="Screenshot 2024-11-10 at 23 28 55" src="https://github.com/user-attachments/assets/8a55e539-85ec-4bf8-9c38-f741f1f4ce97">

**Comment by 71zenith** [comment]
u will need to append the cp function with sudo for elevated privilages

**Comment by oksvuz** [comment]
> u will need to append the cp function with sudo for elevated privilages

Do I just change cp with sudo? Also do I do this in the ani-cli directory? Thanks

**Comment by CoolnsX** [comment]
He wanted to say -- prepend cp with sudo, so --

sudo cp ./ani-cli /usr/local/bin/ani-cli
