### ISSUE TITLE
Search recently aired anime

### ISSUE THREAD

**Issue by Kamanati** [pystardust/ani-cli#1455]
It would be a valuable enhancement to add a feature that enables users to view recently aired anime episodes. This functionality would make it significantly easier to watch and download episodes without the need to manually search for recently aired anime. Implementing this feature would improve the overall user experience and save valuable time.

While I came across the website https://allmanga.to/search-anime?year=2024, it may be necessary to explore its API to retrieve the required information. The API should provide data in the desired order, making this feature feasible to implement.

And make like this 

ani-cli -r -d
<fzf> # assume it's fzf interface
anime 1 (episode number)
Anime 2 (episode number)
<fzf>

Thank you for considering this suggestion.

**Comment by CoolnsX** [comment]
ani-cli -n

**Comment by Kamanati** [comment]
Thanks man
