### ISSUE TITLE
Showing result not found even when the given prompt is correct

### ISSUE THREAD

**Issue by MegaCode-byte** [pystardust/ani-cli#1460]
## **Make sure you are on the latest version by running `ani-cli -U`**

**Metadata (please complete the following information)**
Version: [e.g. 4.7.6, run `ani-cli -V` to find out]
OS: [e.g. Windows 10 / Linux Mint 20.3]
Shell: [e.g. zsh, run `readlink /bin/sh` to get your shell]
Anime: [e.g. flcl] (if applicable)

**Describe the bug**
Downloading is broken.
It says something about an unsupported protocol, see screenshot.

**Steps To Reproduce**

1. Run `ani-cli -d flcl`
2. Choose 2 (fooly-cooly)
3. Choose episode 1

**Expected behavior**
Downloading should work

**Screenshots (if applicable; you can just drag the image onto github. remove the following line if not needed)**
![image](https://user-images.githubusercontent.com/82055622/151030428-2e78d15f-4ba9-4d86-b6f3-8307557b4b29.png)

**Additional context**

**Comment by MegaCode-byte** [comment]
I tried search for everything, but shows No result found everytime

**Comment by port19x** [comment]
You're supposed to fill out the issue template, this doesn't really help

**Comment by port19x** [comment]
Working with flcl for both master branch and v4.9
