### ISSUE TITLE
[FR] skim support

### ISSUE THREAD

**Issue by werdahias** [pystardust/ani-cli#1461]
**Is your feature request related to a problem? Please describe.**
[skim](https://github.com/skim-rs/skim) is a fzf-like program written in Rust. It would be nice if ani-cli supported using skim instead of fzf for selection, e.g. with an option . The logic is pretty much the same so this shouldn't be too hard to implement. I might look into this

**Comment by 71zenith** [comment]
There are no benefits to providing skim as an alternative in our case, at least none that I can think of. moreover fzf is more widely available.
