### ISSUE TITLE
Should not error out when mpv ins not installed

### ISSUE THREAD

**Issue by werdahias** [pystardust/ani-cli#1462]
Version: 4.9
OS: Debian Sid
Shell: bash

ani-cli works with both vlc and mpv. When I just run ani-cli check-dependencies fails with "mpv not installed". Since it works with either would it be possible to create check to use vlc if mpv is not found ?

**Comment by port19x** [comment]
I mean in theory yes, but there is the `-v` option to use vlc, which should work just fine
