### ISSUE TITLE
No results found error on some searches

### ISSUE THREAD

**Issue by Navanrep** [pystardust/ani-cli#1467]
**Metadata (please complete the following information)**
Version: [ 4.9.6]
OS: [Linux Mint 22]
Shell: [dash]
Anime: [All; except Pokemon] (if applicable)

**Describe the bug**
Whenever I try to search for an anime it returns "No results found"; I've tried popular titles such as Naruto, Gintama, One Piece, etc in different styles of cases (upper case, lower case, mixed,etc), and encounter this issue. Pokemon works tho and returns a search result, but it does not allow the video to be played.

**Steps To Reproduce**

1. Run `ani-cli ` and search for any anime

**Expected behavior**
Should return no results found

**Screenshots (if applicable; you can just drag the image onto github. remove the following line if not needed)**

![image](https://github.com/user-attachments/assets/bc7629aa-a48e-4e71-b5be-ca435b1958a9)

**Additional context**

**Comment by Torphedo** [comment]
I'm having the same issue, watching One Piece right now and it suddenly stopped working. But right after I searched for Pokemon like you said, the One Piece search started working (and the video is fine). Maybe a temporary outage with whatever site is hosting the content?

**Comment by MegaCode-byte** [comment]
the issue got solved for me, apparently. The problem was that my net blocked the URL it was using to access. Using another WIFI now and it works
