### ISSUE TITLE
Selecting next episode from CLI does not open episode in existing MPV/VLC Window.

### ISSUE THREAD

**Issue by ishaanparlikar** [pystardust/ani-cli#1468]
## **Make sure you are on the latest version by running `ani-cli -U`**

**Metadata (please complete the following information)**
Version: 4.9.6
OS: Endeavour OS Hyprland
Shell: zsh
Anime: 1 piece
 
**Describe the bug**
If you select next in the cli while episode is running CLI does not replace new episode in current MPV/VLC window. Current window has to be closed to open new one

**Steps To Reproduce**

1. Run `ani-cli`
2. search  one piece
3. Choose a episode
4. let mpv open
5. select next from CLI.

**Expected behavior**
Downloading should work

**Additional context**

**Comment by Derisis13** [comment]
This is intentional. It's required for range playback to not open all episodes at once.
