### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by ritwikrst** [pystardust/ani-cli#147]
not working

![Screenshot from 2021-11-28 23-46-48](https://user-images.githubusercontent.com/53421950/143780778-92d60ced-7b29-4f31-91a9-21df816383ab.png)

![Screenshot from 2021-11-28 23-52-20](https://user-images.githubusercontent.com/53421950/143780941-0a868f1d-8b83-4a6a-8dbd-aea1188d5fba.png)

**Comment by FernandoVT10** [comment]
You just need to change the `base_url` variable to `https://www1.gogoanime.cm/`.

**Comment by samsara636** [comment]
> 

I just came her to write that :+1: 
So basically in your /usr/local/bin/ani-cli file on the line 9, change the base_url variable.

**Comment by BloodThearch** [comment]
I cannot seem to see the specified file in the specified path, i.e. /usr/local/bin/ani-cli 
Just incase, I will tell you guys that I installed ani-cli using the command "yay -S ani-cli-git"
![image](https://user-images.githubusercontent.com/88053172/143786036-8dae3e7a-d11b-4ae0-94c7-08435b5475f0.png)

**Comment by BloodThearch** [comment]
nevermind, I found the file in /usr/bin/

**Comment by samsara636** [comment]
> nevermind, I found the file in` /usr/bin/`

ah yes, it's your path. or where-ever the ani-cli file is. I can also place it in my `.local/bin/ `and it would still work.

**Comment by BloodThearch** [comment]
I think this issue should be closable now. Also many thanks for the creator for this wonderful gift, I already love ani-cli so much. Used it first time today.
