### ISSUE TITLE
No search result??

### ISSUE THREAD

**Issue by DevKn1ght** [pystardust/ani-cli#149]
I've just done a pull request to try this script. I've also installed it the correct way, sudo make, and verified the base URL.

However, it keeps saying "No search result". I've simply tried searching a simple title like, one piece, naruto, or dragon ball. Simple titles.

Nothing works. "No search result" persists.

**Comment by drabart** [comment]
see issue #147 there's an answer

**Comment by DevKn1ght** [comment]
> 

Thanks, it works perfectly now! :)

**Comment by Javets70** [comment]
I tried the given solution to that but it still doesnt work for some reason. 
Keeps showing no search results found

**Comment by Smidge88** [comment]
> I tried the given solution to this problem but it still doesnt work for some reason. Keeps showing no search results found

same here, Dosent work for me , checked if it was blocked by my ISP but it isnt.

**Comment by Dink4n** [comment]
Try to use the latest version

**Comment by Smidge88** [comment]
> Try to use the latest version
Thanks! works for me, i can watch nichijou now :)

**Comment by G-Utopia** [comment]
I tried everything mentioned above, even getting the newest version but it doesnt work for me and says no search results found. It was also a little bit akward  since I could still run ani-cli although the files are deleted. Any suggestions?

**Comment by hexad** [comment]
Same for me, "No Search Results found".

**Comment by ura43** [comment]
#228 is an attempt to fix this permanently
