### ISSUE TITLE
[Feature Request] More sites to scrap

### ISSUE THREAD

**Issue by AlphaS-C** [pystardust/ani-cli#15]
Right now the script scraps gogoanime's website, but I find quite often that the quality is very low (Lets say My Neighbor Totoro) in comparison to other streaming websites (like 9anime.to). 
I know that adding another website option might be basically like writing another script, so take this suggestion as something in late future.
Love your work, keep it up!

**Comment by CoolnsX** [comment]
We can add torrent website.. but it will give only latest episode released in a week...(subsplease.org)

**Comment by ura43** [comment]
No.
If anything, a torrent mode could be implemented in the future.
The way I look at it is if you seriously care about quality, you'll torrent and if you don't, gogoanime is fine
