### ISSUE TITLE
MPV not opening after selecting episode

### ISSUE THREAD

**Issue by WaberHoruhe** [pystardust/ani-cli#151]
Hello, i really cant watch any episode, when I select the episode it just stays in this screen im adding as a picture :)
<img width="694" alt="Screen Shot 2021-11-28 at 7 51 16 p m" src="https://user-images.githubusercontent.com/66725751/143796816-a36888b4-beb1-402d-bbe5-7f2d718457a7.png">

**Comment by WaberHoruhe** [comment]
Forgot to add, im currently on mac os monterey on a macbook pro m1

**Comment by joshualagat** [comment]
See D4nkin's fix on #139.

**Comment by card0z** [comment]
> Forgot to add, im currently on mac os monterey on a macbook pro m1

Did you manage to get it to work?

**Comment by ura43** [comment]
Do you have util-linux installed?
Otherwise this is probably either due to current gogoanime url extraction problems or, if you can play some series but not others, a parsing problem.
Since this provides no additional info, I wont link it to the other tickets.
