### ISSUE TITLE
Termux support 

### ISSUE THREAD

**Issue by JotaroKujo0525** [pystardust/ani-cli#153]
Hello! This is just a question. Can I install ani-cli in termux? If yes, how?

**Comment by BloodThearch** [comment]
> Hello! This is just a question. Can I install ani-cli in termux? If yes, how?

It should be possible to install ani-cli on Termux. But I do not how you will run video though. 
Also to install any git-package on termux, you need a rooted device.
If your phone is rooted, just make sure have curl and mpv already installed.
Then try these steps to install it:
> git clone https://github.com/pystardust/ani-cli.git
> cd ani-cli
> tsu make
I was not able to complete the last step because my device was not rooted and also currently, do not plan to root it.

**Comment by jnishwanth** [comment]
**Not sure** about this, but you apparently do this like so:
1. Install [mpv-andoid](https://play.google.com/store/apps/details?id=is.xyz.mpv) from the Playstore
2. Put the following into ~/bin/mpv,
     ```shell
     #!/data/data/com.termux/files/usr/bin/sh
     am start --user 0 -a android.intent.action.VIEW -d "$1" -n is.xyz.mpv/.MPVActivity
     ```
3. Add execute permissions to it,
     ```shell
     chmod +x ~/bin/mpv
     ```

After this, you should be just able to play videos on termux with ani-cli.

There were also a few other suggestions in the post which i referred to, do check them out if they suit you better.
_Source: [r/termux](https://www.reddit.com/r/termux/comments/gjbjs2/run_mpv_video_player_from_termux/)_

**Comment by truboxl** [comment]
@jnishwanth 
It doesn't work. Seems like there's a need to pass or mpv-android can't open. Opening that URL without will get error 403 Forbidden.
mpv-android needs to allow some form

**Comment by truboxl** [comment]
@jnishwanth 
It doesn't work. There's a need to pass both URL and HTTP header field "Referer" or mpv-android cannot stream.
https://github.com/pystardust/ani-cli/blob/1a1909b1f7bced503cd9173e433d9a712eae137c/ani-cli#L280
Directly open video URL in the browser will get error 403 Forbidden which probably cause mpv-android to close itself.

There doesn't seem to be any other method to pass extra command line options via "am" command to mpv-android yet. https://github.com/mpv-android/mpv-android/issues/427

**Comment by jnishwanth** [comment]
> It doesn't work. There's a need to pass both URL and HTTP header field "Referer" or mpv-android cannot stream.
Yeah you do need headers to be passed for gogoanime. Thought mpv-android just accepted same parameters as mpv.
Let's see if there is any other solution or workaround.

**Comment by Fmert24** [comment]
Ihave a poblem in termux to when ı try to use make 
u0_a3160@localhost ~/g/ani-cli (master) [2]> make          cp ani-cli /usr/local/bin/ani-cli                          cp: cannot create regular file '/usr/local/bin/ani-cli': No such file or directory                                    make: *** [Makefile:6: install] Error 1                    u0_a3160@localhost ~/g/ani-cli (master) [2]>

I just reset termux this day ı was xapable of runing ani-cli whitout root ı just need to remmember how ı changed pre fix of make coment

**Comment by Fmert24** [comment]
> > It doesn't work. There's a need to pass both URL and HTTP header field "Referer" or mpv-android cannot stream.
> 
> Yeah you do need headers to be passed for gogoanime. Thought mpv-android just accepted same parameters as mpv. Let's see if there is any other solution or workaround.

Ok then vlc can stream?

**Comment by JotaroKujo0525** [comment]
> @jnishwanth It doesn't work. There's a need to pass both URL and HTTP header field "Referer" or mpv-android cannot stream.
> 
> https://github.com/pystardust/ani-cli/blob/1a1909b1f7bced503cd9173e433d9a712eae137c/ani-cli#L280
> 
> 
> Directly open video URL in the browser will get error 403 Forbidden which probably cause mpv-android to close itself.
> There doesn't seem to be any other method to pass extra command line options via "am" command to mpv-android yet. [mpv-android/mpv-android#427](https://github.com/mpv-android/mpv-android/issues/427)

Yep, it said "No file 

> @jnishwanth It doesn't work. There's a need to pass both URL and HTTP header field "Referer" or mpv-android cannot stream.
> 
> https://github.com/pystardust/ani-cli/blob/1a1909b1f7bced503cd9173e433d9a712eae137c/ani-cli#L280
> 
> 
> Directly open video URL in the browser will get error 403 Forbidden which probably cause mpv-android to close itself.
> There doesn't seem to be any other method to pass extra command line options via "am" command to mpv-android yet. [mpv-android/mpv-android#427](https://github.com/mpv-android/mpv-android/issues/427)

Yep, it says "No file found, exiting"

**Comment by truboxl** [comment]
The other issue seems promising (use streamlink): https://github.com/pystardust/ani-cli/issues/132

For now I just stick to download and `termux-open` the file, added a PR so that we don't have to install mpv in Termux if we are downloading: https://github.com/pystardust/ani-cli/pull/190

**Comment by CoolnsX** [comment]
https://github.com/CoolnsX/and-scripts/raw/main/ani-cli

Use this link if you want to use it on termux..

**Comment by ura43** [comment]
We can make termux support official if you want to make a PR and write instructions for the README.
Do we need to introduce aria support with it or can we implement that seperately before giving official termux support?

**Comment by ura43** [comment]
@CoolnsX Would you like to become a maintainer?

**Comment by CoolnsX** [comment]
I will.. but ai will not be active as much... Because of exams going on...

**Comment by CoolnsX** [comment]
> We can make termux support official if you want to make a PR and write instructions for the README. Do we need to introduce aria support with it or can we implement that seperately before giving official termux support?

We can introduce aria support with it.. I am using aria in Termux-script too...

**Comment by John-Russel** [comment]
I made it work on my phone 

This is what i did

I install [mpv for android](https://play.google.com/store/apps/details?id=is.xyz.mpv)

I remove the mpv in termux
`apt remove mpv -y`

Create mpv file for mpv for android
`cd`
`nano  ../usr/bin/mpv`

> #!/data/data/com.termux/files/usr/bin/sh
> am start --user 0 -a android.intent.action.VIEW -d "$2" -e "http-header-fields" "$1"  -n is.xyz.mpv/.MPVActivity

Save it
`CTRL+x+y+ENTER`
`chmod +x ../usr/bin/mpv`

Thats it

> sorry for poor english
