### ISSUE TITLE
Downloaded anime is to be sent to a designated folder

### ISSUE THREAD

**Issue by Haikal-Ravendy** [pystardust/ani-cli#154]
Currently, when you download an anime, the anime will be stored within the "ani-cli" folder. Is there a way to change the location of where the downloaded anime is stored? If so, which line should I edit and what kind of edit should I do?

**Comment by Haikal-Ravendy** [comment]
> 

Tried using this but somehow the anime keeps getting stored at "/directory" with the name of "directory{anime_id}-4.mkv" while what I want is to be saved at "/directory/directory" with the name of "naruto-4.mkv"

**Comment by ura43** [comment]
Please reopen if you need further support

**Comment by AlexBastola** [comment]
Why not implement downloading to specified folder as a feature?

**Comment by rahulkarmakar2023cse** [comment]
I have downloaded an anime but the video is not showing
