### ISSUE TITLE
Changing name

### ISSUE THREAD

**Issue by McUberStein** [pystardust/ani-cli#162]
Would it be possible to change what ani-cli names files? Like for example, if I was watching Nagatoro, would it be possible to name the file Ijiranaide, Nagatoro-san ep.001, or something like that? I'm trying to get ani-cli to work with Tundra, and I think the reason it isn't working is the name of the m3u8 file. I'm sure there's some way to do it, but I'm still a Linux noob and I have no idea what I'm doing.

**Comment by McUberStein** [comment]
I tried downloading the episode first, and watching it with mpv with the MPRIS plugin, and that worked, but it'd be cool if I didn't have to download the episodes.

**Comment by TheGlockMisc** [comment]
If you're talking about the m3u8 HLS link..
No you can't because the of the files are stored in their Database, only have access can change that.. if you download it the answer is simple, Change it.

**Comment by McUberStein** [comment]
That's too bad. Thanks for the the reply though.

**Comment by ura43** [comment]
Doesn't seem possible, or at least not worth the effort it would take. Closing this
