### ISSUE TITLE
Resuming (-H) behavior

### ISSUE THREAD

**Issue by RefinedAnarchy** [pystardust/ani-cli#163]
If I close mpv and ani-cli then I when I come back to watch later using ani-cli -H, it plays the next episode instead of resuming where I left off

**Comment by ura43** [comment]
This could be an mpv issue

**Comment by ura43** [comment]
Let me correct myself
This should be an mpv issue

**Comment by ura43** [comment]
Hmmm, not sure what we can do about it.
Also there is another -H bug.
If you do -H you can select sth you already finished, giving you the classic episode out of range error

**Comment by Dink4n** [comment]
> If I close mpv and ani-cli then I when I come back to watch later using ani-cli -H, it plays the next episode instead of resuming where I left off

Actually, this is how it's supposed to behave.

**Comment by ura43** [comment]
Then the bug fix would be adjusting the help text to more closely match what it does.
Can't fault the user for interpreting "resume where you left of" as applicable to episode interruptions as well

**Comment by Rohit-Rangaraj** [comment]
@ura43 @Dink4n Is there a way to make it resume from the current episode. That would be a really useful feature.
