### ISSUE TITLE
Downloader not working

### ISSUE THREAD

**Issue by isitpride** [pystardust/ani-cli#166]
I'm not able to download episodes anymore(streaming works tho), opening links greets you with 403 forbitten.

**Comment by TheGlockMisc** [comment]
Yes Vidstream will Naturally Gives you 403 if you send the request without a proper Header (thats why MPV exist). if downloading using ani-cli doesn't work, the problem is from gogoanime or streams are overloaded, give it a try again.

**Comment by isitpride** [comment]
It still fails downloading, is the error on my machine? I'm on Fedora and I've installed the dependencies

**Comment by isitpride** [comment]
It works now. I'm dumb, my device was missing ffmpeg
