### ISSUE TITLE
Seems not to be working

### ISSUE THREAD

**Issue by mazylol** [pystardust/ani-cli#167]
It runs but searching The Melancholy of Haruhi Suzumiya it says no search results found. I also tried naruto and no dice. It was working perfectly for them both a few days ago.

(I am using the archlinux aur package)

**Comment by mazylol** [comment]
Just uninstalled the aur package and built the git repo. It works. Still no dice on the aur package though.

**Comment by shulkk** [comment]
URL has been changed yet again

**Comment by gamedevCloudy** [comment]
I am having the same issue, everything works but MPV doesn't start.

**Comment by sgtxd** [comment]
As far as i know AUR helpers don't update development (-git) packages automatically.

To update development packages with yay you need to run `yay -Syu --devel`, and to have yay do this automatically without `--devel` you would need to run `yay -Syu --devel --save` once.

**Comment by ura43** [comment]
See #202
