### ISSUE TITLE
Translate the REAMDE in french

### ISSUE THREAD

**Issue by Nathor69** [pystardust/ani-cli#168]
Hi, do you think I could translate the README into French to make life easier for French users?

**Comment by ura43** [comment]
I'm not sure how that would work. Would we link to localized READMEs on the top of the main README?
If we can sensible integrate localized READMEs into the project I'm not against it

**Comment by ura43** [comment]
That could be sth for the repo's wiki maybe?
Idk, it seems like more trouble than it's worth to be completely honest.
If you want to take responsibility for the localization and work on it, reopen the issue and we can reevaluate that descision
