### ISSUE TITLE
Keep asking user for episode number when there's no valid episode [1-0]

### ISSUE THREAD

**Issue by mizuday** [pystardust/ani-cli#170]
Anime: SWORD ART ONLINE: PROGRESSIVE MOVIE - HOSHI NAKI YORU NO ARIA
![image](https://user-images.githubusercontent.com/68516528/144758105-78ceab8e-e879-45cb-bebb-29b1f3aece2a.png)

**Comment by TheGlockMisc** [comment]
Possible Duplicate of #152

**Comment by ura43** [comment]
Closing in favor of #152
