### ISSUE TITLE
open_episode and macOS

### ISSUE THREAD

**Issue by chaoskanzlerin** [pystardust/ani-cli#174]
For me, episodes don't open on macOS, but downloading works: `setsid` isn't a thing on macOS (as far as I'm aware), so removing the `setsid -f` in line 280 has fixed episodes not opening for me, in case anyone runs into the same issue :)

(though you have to quit MPV to access the control selection)

**Comment by KermitPurple** [comment]
Also on mac here,
running `brew install util-linux`
and adding
```
export PATH="/opt/homebrew/opt/util-linux/bin:$PATH"
export PATH="/opt/homebrew/opt/util-linux/sbin:$PATH"
```
to the zshrc fixed the problem for me.

**Comment by elliot0319** [comment]
> Also on mac here, running `brew install util-linux` and adding
> 
> ```
> export PATH="/opt/homebrew/opt/util-linux/bin:$PATH"
> export PATH="/opt/homebrew/opt/util-linux/sbin:$PATH"
> ```
> 
> to the zshrc fixed the problem for me.

I'm on Mac, and this works for me. Thank 👍

**Comment by chaoskanzlerin** [comment]
> Also on mac here, running `brew install util-linux` and adding
> 
> ```
> export PATH="/opt/homebrew/opt/util-linux/bin:$PATH"
> export PATH="/opt/homebrew/opt/util-linux/sbin:$PATH"
> ```
> 
> to the zshrc fixed the problem for me.

that seems like a great fix, i'll use that instead. thank you!

**Comment by ura43** [comment]
Just opened #222 
This should really be documented
