### ISSUE TITLE
"No search results found"

### ISSUE THREAD

**Issue by Comet-Z** [pystardust/ani-cli#176]
I'll say this right away, I tried changing the `base_url` variable to `https://www.gogoanime.cm` and `https://www1.gogoanime.cm`, still no results.

The Issue is that when I try to search for any anime title it simply doesn't find anything
![Screenshot_2021-12-08-01-56-45_1366x768](https://user-images.githubusercontent.com/66474636/145196739-a2e1fc62-5a83-499b-b221-ce9461e721b0.png)

All dependencies are installed. Though I have to say that on my first installation which happened a week ago, it worked just fine. Perhaps there are problems with the website itself? It seems to work fine for me.

My ani-cli file:
![Screenshot_2021-12-08-01-55-12_1366x768](https://user-images.githubusercontent.com/66474636/145196514-a9066fe5-1c0b-480c-8005-247c06792f74.png)

Any help would be appreciated.

**Comment by Dink4n** [comment]
Try using the latest version

**Comment by Comet-Z** [comment]
> Try using the latest version

Is there a command for that or do I just reinstall it? Because I tried reinstalling and still nothing

**Comment by Comet-Z** [comment]
> > Try using the latest version
> 
> Is there a command for that or do I just reinstall it? Because I tried reinstalling and still nothing

Seems like it fixed itself, LOL
