### ISSUE TITLE
Can someone please make it work with MPV for windows?

### ISSUE THREAD

**Issue by punishedzoomer** [pystardust/ani-cli#181]
VLC really Kinda sucks and it keeps buffering and stopping on my windows machine. It works perfectly with MPV on Linux, Top tier experience, can't say the same for Windows.

**Comment by Dr-S-Otter** [comment]
Follow these steps https://www.reddit.com/r/mpv/comments/lrprsu/how_to_open_mpv_command_line/
And change `player_fn="mpv"` to `player_fn="mpv.exe"`

The only thing not working for me is downloading anime but I'm figuring that out atm
