### ISSUE TITLE
Can't increase readahead/buffer?

### ISSUE THREAD

**Issue by maxxxed69** [pystardust/ani-cli#183]
I am seriously loving this app, but I can't seem to find a config file or a way to increase the buffer for mpv?

**Comment by sivhui** [comment]
I think the buffer is bounded by `demuxer-max-bytes` which is `157286400 (150MB)` by default. to increase the buffer,

1. you need to locate the config file. for Linux,

> The system-wide configuration file `mpv.conf` is in your configuration directory (e.g. `/etc/mpv` or `/usr/local/etc/mpv`), the user-specific one is `~/.config/mpv/mpv.conf`.

2. add `demuxer-max-bytes={BYTES}` to the file, where `{BYTES}` is the maximum bytes you want.

you can find out more in [the manual](https://mpv.io/manual/stable/).

**Comment by maxxxed69** [comment]
> I think the buffer is bounded by `demuxer-max-bytes` which is `157286400 (150MB)` by default. to increase the buffer,
> 
>     1. you need to locate the config file. for Linux,
> 
> 
> > The system-wide configuration file `mpv.conf` is in your configuration directory (e.g. `/etc/mpv` or `/usr/local/etc/mpv`), the user-specific one is `~/.config/mpv/mpv.conf`.
> 
>     2. add `demuxer-max-bytes={BYTES}` to the file, where `{BYTES}` is the maximum bytes you want.
> 
> 
> you can find out more in [the manual](https://mpv.io/manual/stable/).

Can you do this in seconds?

**Comment by sivhui** [comment]
yes. for duration, it is bounded by `cache-secs` with default value `3600000`. I guess you may add `cache-secs={SECONDS}` to the file. however, you may still need to set the `demuxer-max-bytes` to some large value otherwise it would only buffer the video up to `150MB`.

**Comment by ura43** [comment]
I assume your issue has been resolved. Reopen if you need further help setting up mpv
