### ISSUE TITLE
support for gogoanime duplicates?

### ISSUE THREAD

**Issue by notprash** [pystardust/ani-cli#184]
Sometimes when using ani-cli. The episodes can be laggy overall. Does ani-cli support [gogoanime.wiki](https://gogoanime.wiki/) or any other gogoanime duplicates.

**Comment by CoolnsX** [comment]
Yup it works on duplicates.. as I am too using gogoanime.wiki for streaming/downloading

**Comment by ura43** [comment]
Works perfectly fine with duplicates afaik. Maybe we should make this a launchflag? 
Like  `-u url` ?

**Comment by ura43** [comment]
see #228 
Closing now
