### ISSUE TITLE
ani-cli 150: cannot create /home/scuttler/.cache/ani-hsts: directory nonexistent 

### ISSUE THREAD

**Issue by Scuttler2k** [pystardust/ani-cli#186]
I've had this issue many times yet everything I go through the installation it returns that when I cd it then run it after doing doing make.

**Comment by TheGlockMisc** [comment]
try creating directory manually
sudo mkdir /home/scuttler/.cache

**Comment by Scuttler2k** [comment]
> try creating directory manually `mkdir /home/scuttler/.cache`

I tried this doing this returns the same thing but it just says that it exists instead of it being nonexistent.

**Comment by Scuttler2k** [comment]
> try creating directory manually `mkdir /home/scuttler/.cache`

It fixed using another distro thanks
