### ISSUE TITLE
"No results found"

### ISSUE THREAD

**Issue by TCMOREIRA** [pystardust/ani-cli#189]
It was working flawlessly two weeks ago, but now every time I anime-search it always returns "No results found" even when searching for very obvious stuff, for testing purposes, such as "Naruto" or "Dragon Ball".

**Comment by sgtxd** [comment]
Have you updated ani-cli to the latest commit? Alternatively please check that `base_url="https://www1.gogoanime.cm"` inside ani-cli.

If you have installed ani-cli over the AUR (Arch User Repository) your AUR helper might not update -git packages automatically. In this case you should refer to your AUR helpers documentation.

**Comment by TCMOREIRA** [comment]
Hi! At the time of writing that question, 3 days ago, I had removed ani-cli and then downloaded and compiled from source a couple of times without success. I'm on Pop-OS (Debian) so the issue isn't AUR related. Next time I'll check if the url is the problem! Thanks for the response!
