### ISSUE TITLE
Stopped working all of a sudden

### ISSUE THREAD

**Issue by Hellboy913** [pystardust/ani-cli#19]
Scrapes and gives me options to choose from. After I choose the episode numbers, it says "Currently playing", but nothing else happens. The internet usage during this time is zero. Only spikes up during "Getting data for episode" 

Update: I tried downloading an episode and the below text was the output
```
$ anime -d
Search Anime: dr. stone
[1] dr-stone
[2] dr-stone-dub
[3] dr-stone-stone-wars
[4] dr-stone-stone-wars-dub
[5] dr-stone-stone-wars-kaisen-zenya-special-eizou
Enter number: 2
Range of episodes can be specified: start_number end_number
Choose episode [1-24]: 1
Getting data for episode 1
Downloading episode 1 ...

curl: (3) URL using bad/illegal format or missing URL
Download failed episode: 001
```

**Comment by Dink4n** [comment]
Mine isn't working either. There is CAPTCHA now

**Comment by sgtxd** [comment]
If that's the case then i guess we'll have to scrape from a different website then

**Comment by pystardust** [comment]
Suggest sites that have download feature

**Comment by pystardust** [comment]
9anime.vim looks like a good candidate

**Comment by Hellboy913** [comment]
By the way, lemme just say.
I absolutely what you guys have done, and pystartdust's ytfzf project is actually a part of my daily life. Along with this one. STarted wathing anime with this :)
Thankful, people.

**Comment by sgtxd** [comment]
kiss-anime.ws also seems pretty good

> 9anime.vip looks like a good candidate

**Comment by Dink4n** [comment]
> Suggest sites that have download feature

maybe picotube.online

**Comment by pystardust** [comment]
https://github.com/pystardust/ani-cli/commit/b8c033dc72ee5b795225444062dc8340c2632569

Its functional but needs a lot more work

**Comment by Dink4n** [comment]
The videos are being downloaded from vidstreaming.io. We only need the anime id from the url.
I tried a hack and it's working for me

```sh
sed -n -E '
/^[[:space:]]*<li class="dowloads">/{
s_.*href="https://streamani.net/([^&]*).*_https://vidstreaming.io/\1_p
q
}'
```

**Comment by pystardust** [comment]
@Dink4n 
Is this from the download page? 
Which ID are you talking about the episode id in the current script?

**Comment by fossimprove** [comment]
Check [this](https://piracy.moe) site out, it has multiple sites official links, basically an index.
But Nice work pystar! Thank you very much!

My take on sites scraping suggestion would be
 4anime.to | Shiro.is | Zoro.to (has external subs) | AnimeTwist 
 Try out the sites from that Index

**Comment by Dink4n** [comment]
> Is this from the download page?
> Which ID are you talking about the episode id in the current script?

It's from the old implementation, For example instead of `https://streamani.net/download?id=NzAxNTk=&typesub=Gogoanime-SUB&title=One+Punch+Man+Episode+12` we can extract the ID `id=NzAxNTk=` and directly go to the download page `https://vidstreaming.io/download?id=NzAxNTk=`

But current implementation seems to have better quality

**Comment by Albonycal** [comment]
9anime and less anime's available..
gogo had all pokemon episodes

**Comment by Albonycal** [comment]
So what are we going to do?

**Comment by Dink4n** [comment]
I fixed the old ani-cli implementation.
This is the fork [ani-cli](https://github.com/Dink4n/ani-cli).
