### ISSUE TITLE
Not really an issues, but I wanted to ask is using this illegal and could get someone using this into legal trouble?

### ISSUE THREAD

**Issue by VG08** [pystardust/ani-cli#199]

**Comment by punishedzoomer** [comment]
I don't think you'd be the one getting into legal trouble since this program scrapes from **gogoanime**.
I think it's fair to assume the **gogoanime** owners would be the ones in legal trouble.

**Comment by sdaqo** [comment]
I don't know where you live, but in the EU it is, even when you are only watching the content. But the chance that you are going to get into legal issues is probably about 0% since you are one of many doing this and also because you are watching anime and the chance that the boomers looking into your network traffic for anime is very slim, they would rather look for someone who pirates rl series. The chance is higher when you download/torrent content or even host it yourself. But note that it's always a good idea to surf the web with a VPN.

**Comment by VG08** [comment]
hmm ok, I live in india btw if that could give you an idea of if I would get into trouble

**Comment by VG08** [comment]
> good idea to surf the web with a VPN.

well I don't have a vpn bought and I don't really trust free ones

**Comment by TheGlockMisc** [comment]
Technically GogoAnime is Illegal, But yeah if Governments here in Japan or other Anime Services/Company sends an Cease and Desist Letter. They would shutdown the website as soon as possible, Before something bad happen. Plus the Gogoanime Website have ads so they're gaining revenue without Author's permission which is illegal, but lets enjoy what we have right now. (Sorry for my Bad English)

**Comment by VG08** [comment]
@TheGlockMisc but this would only impact the owner or it could have something on the users too?

**Comment by TheGlockMisc** [comment]
> @TheGlockMisc but this would only impact the owner or it could have something on the users too?

It depends, but its impossible to catch them all.. Some of Users are Underaged, But surely this will have impact to owner of the site like what happened to Kissanime.

**Comment by ura43** [comment]
I don't think you'll get in trouble for it. Its about on the same level of illegal as walking a red light. As others have mentioned, the ones hosting those websites are the ones who could get into serious trouble. Even in the extremely unlikely event that you would get caught using it, you'd probably only get a slap on the wrist.
Thats speaking as a german citizen.

Maybe someone can comment on the specifics in india

**Comment by ura43** [comment]
Added a disclaimer and linked to it at the bottom of the readme.
It's a shameless copy of [animdl](https://github.com/justfoolingaround/animdl)'s disclaimer.
I think its safe to close it with that
