### ISSUE TITLE
Possible incompatibility with Item or Mac OS X

### ISSUE THREAD

**Issue by Aurelian-Shuttleworth** [pystardust/ani-cli#2]
First, off this the last thing I would have expected in a bash script and I love it XD

Second, In Item on OSX, I do no get a video window when playing an episode as you demonstrated in your Reddit post. Is there any dependency not listed in your read me?

**Comment by pystardust** [comment]
do you have mpv installed?
I should have added mpv as a dependency in the script too.
If you dont have mpv then replace mpv with vlc in the script

**Comment by joshvasquez** [comment]
`setsid` is not included in MacOS by default.

You can install it with homebrew with `brew install util-linux` or you can just deleted `setsid -f` from the script and it should also work.

**Comment by Sackbuoy** [comment]
Personally, on MacOS I had to run 
```
brew install --cask mpv
brew install util-linux
 echo 'export PATH="/usr/local/opt/util-linux/bin:$PATH"' >> ~/.zshrc
 echo 'export PATH="/usr/local/opt/util-linux/sbin:$PATH"' >> ~/.zshrc
```
and then refresh my shell, then it worked perfectly

**Comment by ghyatzo** [comment]
Instead of installing `util-linux` I made it work by substituting `setsid -f` with `nohup ... &` in the script directly.
That is
```
nohup $player_fn --http-header-fields="Referer: $embedded_video_url" "$video_url" >/dev/null 2>&1 &
```
The behaviour is the same.
process tree after changing the line reads as
```
zsh
|_ sh ani-cli
    |_ mpv ...
```
this on mac os 11.6

**Comment by ura43** [comment]
This is solved by [PR 137](https://github.com/pystardust/ani-cli/pull/137)
