### ISSUE TITLE
There is a glitch were the video is unwatchable for a small duration

### ISSUE THREAD

**Issue by TheHighGroundWins** [pystardust/ani-cli#201]
On every anime and every episode there's a moment where the video becomes broken and unplayable even when the whole video has finishing caching the rest of the episode before and after the glitchy part is watchable. I tried the same episode on gogoanime and 9anime but there was no such issues on those websites.

this also sometimes happens multiples times spread throughout an episode as well

**Comment by ura43** [comment]
Very likely an mpv configuration issue. 
While the download cache might be full, low spec hardware can struggle with mpv some times.
Please verify this isn't the cause by playing a downloaded episode in mpv

**Comment by TheHighGroundWins** [comment]
In terms of hardware I have a good high spec hardware for Linux.

This happens even when the whole video is cached.

Videos locally available not cached do not have this problem with mpv.

**Comment by Quicksilver151** [comment]
this normally happens to me when my internet connection speed drops
if my internet connection is constant, the video is not broken
otherwise, it often has these glitches that TheHighGroundWins is describing

**Comment by ura43** [comment]
> In terms of hardware I have a good high spec hardware for Linux.
> 
> This happens even when the whole video is cached.
> 
> Videos locally available not cached do not have this problem with mpv.

Can you try opening a youtube url with mpv?
Wondering if youtube-dl has the same issue or if there is actually something we can do about this
