### ISSUE TITLE
VLC Support (-v) not working

### ISSUE THREAD

**Issue by RRFroste** [pystardust/ani-cli#204]
Attempting to use the -v flag to watch using VLC returns `/usr/local/bin/ani-cli: illegal option -- v`. When I type `ani-cli -v $AMINE`, it still outputs the error and launches the specified episode in MPV. I am using a fresh install as of 2021-12-19 installed as per the download and install instructions.

**Comment by ura43** [comment]
Launching `ani-cli -v`, searching for and then playing flcl progressive, I can't reproduce this issue as of today.
Launching `ani-cli -v flcl progressive` doesn't reproduce it either.
It may have been resolved as a sideeffect of another issue being solved.

**Comment by ura43** [comment]
Since it output "illegal option", it is safe to assume option parsing was temporarily broken when you had this issue
