### ISSUE TITLE
"VLC is not installed" issue

### ISSUE THREAD

**Issue by Ziekoss** [pystardust/ani-cli#206]
I followed all the directions correctly, and checked it many times over, but it kept saying vlc was uninstalled when I tried to run the app. I kinda wasted an hour and some change of my time trying to get it to work, any solutions?

**Comment by Dink4n** [comment]
Are you using Windows?

**Comment by Ziekoss** [comment]
> Are you using Windows?

Yeah, of course

**Comment by Dink4n** [comment]
Possible duplicate of #131

**Comment by Ziekoss** [comment]
> Possible duplicate of #131

Just spent a good amount of time setting the player_fn to the direct file location of vlc, I did: player_fn="C:\Program Files\VideoLAN\VLC" but it's still saying that VLC isn't installed.

**Comment by Dink4n** [comment]
You have to set it to the path of the executable
`player_fn="C:\Program Files\VideoLAN\VLC\vlc.exe"`

**Comment by Ziekoss** [comment]
> You have to set it to the path of the executable `player_fn="C:\Program Files\VideoLAN\VLC\vlc.exe"`

Yeah I had tried that the first time like DigitalNXZ did when they showed an example and it didn't work, but I'll try it again.

**Comment by Ziekoss** [comment]
> You have to set it to the path of the executable `player_fn="C:\Program Files\VideoLAN\VLC\vlc.exe"`

It worked! I suppose I must've made a typo or something the last time, thanks a bunch, I was really just trying to be patient with the process. I've literally spend a good few hours trying to get this working.

**Comment by Ziekoss** [comment]
Well apparently it's only working halfway so far, I try to play the episode but it won't actually show anything. I'll look at previous issues to see what the problem is and to try to fix it.

**Comment by Ziekoss** [comment]
I've been reading up on other issues, and I'm pretty sure it has to do with my video player, and line 4 of ani-cli-win says: video_player ( needs to be able to play urls ), as well as -4 video_player at line 3 (dependencies).

**Comment by Dink4n** [comment]
Change `$player_fn` in this line
https://github.com/pystardust/ani-cli/blob/ad80e575105820f73518dbef7d2a73a81a1809e8/ani-cli-win#L249
to `"$player_fn"`

Basically, add quotes around `$player_fn`

**Comment by Ziekoss** [comment]
> Change `$player_fn` in this line
> 
> https://github.com/pystardust/ani-cli/blob/ad80e575105820f73518dbef7d2a73a81a1809e8/ani-cli-win#L249
> 
> 
> to `"$player_fn"`
> Basically, add quotes around `$player_fn`

![image](https://user-images.githubusercontent.com/81887879/147203575-f2db87a5-4559-45bd-be5b-a600ed307031.png)

**Comment by Ziekoss** [comment]
> > Change `$player_fn` in this line
> > https://github.com/pystardust/ani-cli/blob/ad80e575105820f73518dbef7d2a73a81a1809e8/ani-cli-win#L249
> > 
> > to `"$player_fn"`
> > Basically, add quotes around `$player_fn`
> 
> ![image](https://user-images.githubusercontent.com/81887879/147203575-f2db87a5-4559-45bd-be5b-a600ed307031.png)
> 
> I did that, and tried to play an episode but now whenever I try to search something it messes up

I'll try setting the base url on line 9 to ww2 gogoanime to see if it works since it said they moved to a new website

**Comment by Ziekoss** [comment]
> > > Change `$player_fn` in this line
> > > https://github.com/pystardust/ani-cli/blob/ad80e575105820f73518dbef7d2a73a81a1809e8/ani-cli-win#L249
> > > 
> > > to `"$player_fn"`
> > > Basically, add quotes around `$player_fn`
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/81887879/147203575-f2db87a5-4559-45bd-be5b-a600ed307031.png)
> > I did that, and tried to play an episode but now whenever I try to search something it messes up
> 
> I'll try setting the base url on line 9 to ww2 gogoanime to see if it works since it said they moved to a new website

Yeah still not working

**Comment by Ziekoss** [comment]
> > > > Change `$player_fn` in this line
> > > > https://github.com/pystardust/ani-cli/blob/ad80e575105820f73518dbef7d2a73a81a1809e8/ani-cli-win#L249
> > > > 
> > > > to `"$player_fn"`
> > > > Basically, add quotes around `$player_fn`
> > > 
> > > 
> > > ![image](https://user-images.githubusercontent.com/81887879/147203575-f2db87a5-4559-45bd-be5b-a600ed307031.png)
> > > I did that, and tried to play an episode but now whenever I try to search something it messes up
> > 
> > 
> > I'll try setting the base url on line 9 to ww2 gogoanime to see if it works since it said they moved to a new website
> 
> Yeah still not working

I'll set it back

**Comment by Dink4n** [comment]
Can you try it again?
But set `base_url="https://www2.gogoanime.cm"`

**Comment by Ziekoss** [comment]
> Can you try it again?
> 
> Also, set `base_url` to the correct domain `base_url="https://www2.gogoanime.cm"`

I tried it again with the url as ww2, and the problem is the episode selection, it just won't let me find any episodes

**Comment by ura43** [comment]
So its basically windows + vlc being weird?

**Comment by ura43** [comment]
Continue discussion in #222 if nescessary
