### ISSUE TITLE
no search results found

### ISSUE THREAD

**Issue by erastag** [pystardust/ani-cli#208]
Same issue as other users : I can't find any anime (even basic searches such as  "naruto" returns "no results found").
I tried :
cd ani-cli
git pull
sudo make 

Tried to change the base URL to "https://ww1.gogoanime2.org/" (first link i've found on google, no idea which one is supposed to be correct), and tried changing the URL from gogoanime.cm to gogoanime.pe too, but it didn't work either (i compiled with sudo make in each case).
Not sure what else I should try.

**Comment by Davidlinuxnoob** [comment]
if you go inside the code of ani-cli where it says the base url it got changed form www1 to www2

**Comment by erastag** [comment]
it does work thanks mate, changing the 1 to 2 in "ww1.gogoanime.cm"fixed the issue for me. Where did you read the line that you have to change it from 1 to 2 ? I can't seem to find it in case I need to do this another time

**Comment by Davidlinuxnoob** [comment]
> 

i saw another chat that change the base url and i got curious and click on the link and open. and their i saw that it did not have a 1 but a 2.

**Comment by erastag** [comment]
Ah thanks, I just couldn't find that specific one. Glad you were there mate, I'll be closing this issue.

**Comment by kaumidere** [comment]
i tried changing the code from ww1 to ww2.gogoanime.cm and it still didn't seem to work. was there anything else that needs changing?

**Comment by osbm** [comment]
> i tried changing the code from ww1 to ww2.gogoanime.cm and it still didn't seem to work. was there anything else that needs changing?

hmm, this line works for me
`base_url="https://www2.gogoanime.cm"`

**Comment by Davidlinuxnoob** [comment]
that was all i did and it's working for me.

**Comment by erastag** [comment]
> i tried changing the code from ww1 to ww2.gogoanime.cm and it still didn't seem to work. was there anything else that needs changing?

did you "sudo make" after changing the line ?

**Comment by kaumidere** [comment]
Oh wait now it works
