### ISSUE TITLE
current base url does not work.

### ISSUE THREAD

**Issue by Kungger-git** [pystardust/ani-cli#210]
I'm using ani-cli for a couple of days now, and it's working fine. Though I encountered a problem where
I cannot get any results anymore.

I tried the base url in the browser and it re-directed me to `www2.gogoanime.cm` instead of the base url, and it worked!
I'm not sure if this also happened for most users, but that's just what I did to fix my issue.

I just replaced the base url with: `www2.gogoanime.cm`

**Comment by photon-niko** [comment]
This also happened to me and changing the url to `www2.gogoanime.cm` fixed it too

**Comment by Kungger-git** [comment]
Pull Request: #209 is the one to go with instead.

**Comment by ProgrammerJaneki** [comment]
tried it but still doesn't work. I wonder what's the problem  :/

**Comment by Fmert24** [comment]
www1.gogoanime is down?

**Comment by shulkk** [comment]
[There’s a PR fix in the works](https://github.com/pystardust/ani-cli/pull/209)

**Comment by ura43** [comment]
Tagging low because the fix also fixes another: #221

**Comment by ura43** [comment]
Closing because definitely fixed by [PR 209](https://github.com/pystardust/ani-cli/pull/209)

**Comment by ura43** [comment]
Continue discussion on #221 if necessary
