### ISSUE TITLE
Japanese captions

### ISSUE THREAD

**Issue by CarlosLoboxyz** [pystardust/ani-cli#211]
Recently i've found this site called [animelon.com](https://animelon.com) which allows you to view a lot of series with the kanji/katakana/hiragana subtitles, is worth mentioning this because it could be a good place to take the japanese captions. 

Wonder if some of you would be interest in working in this feature.

**Comment by TheGlockMisc** [comment]
Yeah but its a Blog Type. i dont think they will manage to up it in Longest Time possible.

But i agree.

**Comment by ura43** [comment]
This would be like supporting another site entirely and would probably break down the line.
Something like this should be a seperate project
