### ISSUE TITLE
No search  results found

### ISSUE THREAD

**Issue by Ananay-g** [pystardust/ani-cli#213]
for every anime search it gives **no search result found**
![ani-cli](https://user-images.githubusercontent.com/77975605/147362391-cb170212-e764-4076-bef1-03f7a1bcc113.png)
![ani-cli2](https://user-images.githubusercontent.com/77975605/147362447-07a21913-657c-460a-9356-b08a1783c4a4.png)

**Comment by TheGlockMisc** [comment]
maybe you havent downloaded the latest yet,
Try:
```
cd ani-cli
git pull
sudo make
```

**Comment by Komefumi** [comment]
[#209](https://github.com/pystardust/ani-cli/pull/209)

Like @TheGlockMisc said, getting the latest release should fix that specific problem

**Comment by Ananay-g** [comment]
ah, this worked.
thanks!
