### ISSUE TITLE
Cannot download or watch any episode

### ISSUE THREAD

**Issue by grobocop12** [pystardust/ani-cli#215]
variable video_url seems to be empty

**Comment by wh1ter4bb1t-js** [comment]
duplicate of #202, #207 and #192

**Comment by SM1SHi** [comment]
Same here

> duplicate of #202, #207 and #192

also this

**Comment by i0bz** [comment]
same here 
when i download it wont show  the link it's downloading from and it gives a download fail
i cant play or download anything i tried 8 different series but still nothing

**Comment by dilavni** [comment]
after selecting the episode to play (getting data for episode) the video doesn't start. debug from that point:
$base_url was "https://www2.gogoanime.cm/"
$video was empty
$video_url was empty

**Comment by ura43** [comment]
Once again #221
