### ISSUE TITLE
Unsupported URL

### ISSUE THREAD

**Issue by H4mxa** [pystardust/ani-cli#22]
When i select episode number, it give me an error saying:

`[ytdl_hook] ERROR: Unsupported URL: https://yare3.yare.wtf/vidstreaming/animefrenzy/MTU3ODI4 
[ytdl_hook] youtube-dl failed: unexpected error ocurred 
Failed to recognize file format.

Exiting... (Errors when loading file)
`

**Comment by nasseef20** [comment]
Can confirm, happened to me as well. Not for all anime tho, it happened when I tried to watch season 3 of Attack on Titan. I tried other stuff such as Moriarty the patriot, bokuben, or konosuba movie - and these worked fine
