### ISSUE TITLE
no results found

### ISSUE THREAD

**Issue by Anarchyserver** [pystardust/ani-cli#220]
this has happened before when changing the base url to https://www1.gogoanime.cm would fix it but it broke again and is displaying "no results found" i checked the ani-cli file and the base url is https://www1.gogoanime.cm. im on a kali linux vm.
![Screenshot_2021-12-27_17-29-03](https://user-images.githubusercontent.com/84468874/147470031-07263b18-eb24-45e3-ba86-3c80c84559df.png)

**Comment by JotaroKujo0525** [comment]
Change it to `https://www2.gogoanime.cm`

**Comment by Anarchyserver** [comment]
> Change it to `https://www2.gogoanimealready tried it after i saw the website changed but still nothing

**Comment by JotaroKujo0525** [comment]
Uhh do you mean `https://www2.gogoanime.cm `

**Comment by IllusiveAldebaran** [comment]
I had the same issue. Thought it couldn't be that since I had just pasted the url to https://www1.gogoanime.cm, but if you go to the website you'll see it now redirects you to  https://www2.gogoanime.cm as soon as you open it.

**Comment by Vit0rg** [comment]
Go to ani-cli folder, open the ani-cli file with some text editor, search for $base_url (usually line 9), change it for base_url="https://www2.gogoanime.cm", save.

Then just go to terminal and type:
cd ani-cli/ 
sudo make

**Comment by Anarchyserver** [comment]
> Go to ani-cli folder, open the ani-cli file with some text editor, search for $base_url (usually line 9), change it for base_url="https://www2.gogoanime.cm", save.
> 
> Then just go to terminal and type: cd ani-cli/ sudo make

thank you i completely forgot about the sudo make part.
