### ISSUE TITLE
codec error?

### ISSUE THREAD

**Issue by DeZeeKees** [pystardust/ani-cli#223]
![Screenshot 2021-12-28 180501](https://user-images.githubusercontent.com/92569623/147589950-0cbd6fff-589e-4e31-a600-b88bdb5a258c.png)

**Comment by guilhermicas** [comment]
i think ani-cli is not currently working due to the site's implementation of some blocking protection, and the stream is not being able to be opened. for a alternative you could use a node based CLI that needs some polishing, but works well enough. -> https://github.com/MeemeeLab/node-anime-viewer

**Comment by DeZeeKees** [comment]
> i think ani-cli is not currently working due to the site's implementation of some blocking protection, and the stream is not being able to be opened. for a alternative you could use a node based CLI that needs some polishing, but works well enough. -> https://github.com/MeemeeLab/node-anime-viewer

this works thanks
