### ISSUE TITLE
Add proper error messages

### ISSUE THREAD

**Issue by ura43** [pystardust/ani-cli#227]
"MPV doesn't open" has been the theme of the day for me looking through old issues.
Most of these weren't actually mpv issues, but rather issues with parsing or with url / url extraction.
Adding proper error messages could make identifying duplicates easier and minimize end user confusion

**Comment by RaynardGerraldo** [comment]
#209 7b0d01440bd905be3c4f64890a2907aa57a92c68

**Comment by ura43** [comment]
Thanks for the quick reaction. PR is reviewed
