### ISSUE TITLE
Provide option to specify url

### ISSUE THREAD

**Issue by ura43** [pystardust/ani-cli#228]
Many issues are due to gogoanime being mean and get resolved by using a gogoanime duplicate.
Providing an option, i.e. `-u url` and documenting alternatives to main gogoanime would help.
The user shouldn't have to edit the script to make it work

**Comment by ura43** [comment]
If I understand correctly, we currently check where the standard gogoanime domain redirects us and then use that domain.
As long as that functions, gogoanime can change their url all they want and we would still get to it.
This would make this issue invalid.
@RaynardGerraldo how high of an impact has gogoanime changing their url after your recent improvements?

**Comment by RaynardGerraldo** [comment]
> If I understand correctly, we currently check where the standard gogoanime domain redirects us and then use that domain.
> As long as that functions, gogoanime can change their url all they want and we would still get to it.
> This would make this issue invalid.
> @RaynardGerraldo how high of an impact has gogoanime changing their url after your recent improvements?

Honestly its still going well ,i saw some comments that gogoanime changed their url to .wiki, .tv, .co ,etc but it all leads to that gogoplay1 link which is the source of the videos. So it doesnt make a difference which domain gogoanime uses as long as it leads to gogoplay1

**Comment by ura43** [comment]
In that case I'll close this issue.
Fingers crossed they keep leading to gogoplay1
