### ISSUE TITLE
Update Contributing.md

### ISSUE THREAD

**Issue by ura43** [pystardust/ani-cli#229]
This goes out especially to my fellow maintainers.
I'm thinking of adding a few things:

- reffering to shellcheck for current point 1
- reffering to the [pure-sh-bible](https://github.com/dylanaraps/pure-sh-bible) for current point 3
- advise users to make sure they don't open a duplicate issue
- the suggestion for new contributors to work on feature requests first, since those can be worked on without deep understanding of the inner workings of the script

Anything you miss or you disagree with?
Making it easier for our users to contribute will definitely help

I also feel like this is a good opportunity to introduce myself to you.
I'm a sysadmin with a little extra time on his hands. 
I know my way around shellscripts and web scraping.
I have extensive experience in writing technical documentation and know a good bit about project management.
I hope to enable us all to make ani-cli greater than ever and hope I'm welcome :smiley:

**Comment by Fmert24** [comment]
> This goes out especially to my fellow maintainers. I'm thinking of adding a few things:
> 
> * reffering to shellcheck for current point 1
> * reffering to the [pure-sh-bible](https://github.com/dylanaraps/pure-sh-bible) for current point 3
> * advise users to make sure they don't open a duplicate issue
> * the suggestion for new contributors to work on feature requests first, since those can be worked on without deep understanding of the inner workings of the script
> 
> Anything you miss or you disagree with? Making it easier for our users to contribute will definitely help
> 
> I also feel like this is a good opportunity to introduce myself to you. I'm a sysadmin with a little extra time on his hands. I know my way around shellscripts and web scraping. I have extensive experience in writing technical documentation and know a good bit about project management. I hope to enable us all to make ani-cli greater than ever and hope I'm welcome 😃

Pls add when we press q any point ani-cli quits whit out posting err

**Comment by ura43** [comment]
@Fmert24 I'm not sure I know what you mean.
After updating to the latest version, check if you still have that issue and if you do, open an issue

Closing this in favor of #235
