### ISSUE TITLE
Anime episode not starting

### ISSUE THREAD

**Issue by MGkillergamer007** [pystardust/ani-cli#231]
i downloaded ani-cli i did sudo make

then ani-cli i searched the anime that i want to watch i select the episode it says

![Screenshot from 2021-12-29 21-12-16](https://user-images.githubusercontent.com/81156826/147695889-ff7d38b6-bf73-4d96-9b03-c5b54edf8998.png)

and the episode isnt opening with mpv, nothing happens

i am using ubuntu 20.04

**Comment by ura43** [comment]
Does the same issue occur a few other series?

**Comment by MGkillergamer007** [comment]
> Does the same issue occur a few other series?

idk i tried one piece, death note and aot

**Comment by ura43** [comment]
In that case it's due to url handling aka #221 
Please check out [PR 209](https://github.com/pystardust/ani-cli/pull/209) and report if that works for you

**Comment by MGkillergamer007** [comment]
ok thanks

**Comment by MGkillergamer007** [comment]
uh i dont understand what should i do???

**Comment by ura43** [comment]
Oh, no worries.
Please install from here https://github.com/RaynardGerraldo/ani-cli
Do you understand what I mean?

**Comment by MGkillergamer007** [comment]
oh ok should i remove the old version ?

**Comment by ura43** [comment]
> oh ok should i remove the old version ?

Yes, that would be safer.
After trying it out, please report on #221 
I just reported `PR 209 didn't solve the issue for me. Tested on debian unstable, wanted to watch flcl progressive ep 1`

**Comment by MGkillergamer007** [comment]
hey nvm i installed the new one now i get an error
![Screenshot from 2021-12-29 21-57-55](https://user-images.githubusercontent.com/81156826/147698977-2fe5e8c2-9d07-4924-81a9-25f7919f2d69.png)
r

**Comment by ura43** [comment]
Yeah, that version temporarily requires lynx. You can just install it through your package manager, its a small programm

**Comment by MGkillergamer007** [comment]
ok

**Comment by ura43** [comment]
If you don't get it to work today, check in a week. This issue is our number 1 priority and we're actively working on it

**Comment by MGkillergamer007** [comment]
thank you very much you are a lifesaver it works now

**Comment by ura43** [comment]
Wait what

**Comment by MGkillergamer007** [comment]
what?

**Comment by ura43** [comment]
I mean thats neat, could you tell me what show so I can try to reproduce?

**Comment by MGkillergamer007** [comment]
one piece

**Comment by ura43** [comment]
yep works :)

**Comment by ura43** [comment]
Awesome

**Comment by MGkillergamer007** [comment]
yeah

**Comment by MGkillergamer007** [comment]
again thanks
