### ISSUE TITLE
Searching simply doesn't work at all

### ISSUE THREAD

**Issue by Ubuntufanboy** [pystardust/ani-cli#233]

**Comment by ura43** [comment]
Good timing. What series didin't work, and does one piece work?
Can you provide further info?

**Comment by ura43** [comment]
Also, try PR 232. To do so, install ani-cli like you would normally but git clone https://github.com/RaynardGerraldo/ani-cli instead.
Please report your success

**Comment by ura43** [comment]
Closing as duplicate. If it still doesn't work in an hour or later, and after updating, please reopen

**Comment by Ubuntufanboy** [comment]
So when I copy and paste the exact anime that was found on the sight it says that the anime was not found. Is there a way to do a quarry?
