### ISSUE TITLE
Searching for an anime containing a special character doesn't work

### ISSUE THREAD

**Issue by Ubuntufanboy** [pystardust/ani-cli#240]
When I search for an anime with a special character it just returns "No search results found" I made sure to copy and paste it the EXACT same way it was listed on _gogo anime's_ website. I tried many aliases to the anime's name but nothing seems to work

**Comment by ura43** [comment]
You are running the latest version?
Could you tell me what Anime so I can reproduce the issue?

**Comment by TheGlockMisc** [comment]
> When I search for an anime with a special character it just returns "No search results found" I made sure to copy and paste it the EXACT same way it was listed on _gogo anime's_ website. I tried many aliases to the anime's name but nothing seems to work

probably the "special character" must be url encoded after passing to variable

**Comment by ura43** [comment]
Yeah, is there a builtin thing with curl that can do that?

**Comment by Quicksilver151** [comment]
> You are running the latest version? Could you tell me what Anime so I can reproduce the issue?

i got the same usse as well
for the second season of an anime called "Saenai Heroine no Sodatekata ♭"
its got that weird charachter "♭"
in the list after searching for "saenai" with this program, the second result (which is the above mentioned season 2) shows "[2] saenai-heroine-no-sodatekata-2"
selecting episodes from this gives the error message: Download failed episode: 001 , please retry or check your internet connection

**Comment by ura43** [comment]
Nice, let's use that anime for troubleshooting

**Comment by RaynardGerraldo** [comment]
> > You are running the latest version? Could you tell me what Anime so I can reproduce the issue?
> 
> i got the same usse as well for the second season of an anime called "Saenai Heroine no Sodatekata ♭" its got that weird charachter "♭" in the list after searching for "saenai" with this program, the second result (which is the above mentioned season 2) shows "[2] saenai-heroine-no-sodatekata-2" selecting episodes from this gives the error message: Download failed episode: 001 , please retry or check your internet connection

just fixed this on pr #244 , turns out these special character animes have different links than the normal ones, 

special character animes : title-episodenumber
normal character animes : title-episode-episodenumber

**Comment by TheGlockMisc** [comment]
I did some Experimentation it seems that if you type uppercased Query theres no Results..



> > > You are running the latest version? Could you tell me what Anime so I can reproduce the issue?
> > 
> > 
> > i got the same usse as well for the second season of an anime called "Saenai Heroine no Sodatekata ♭" its got that weird charachter "♭" in the list after searching for "saenai" with this program, the second result (which is the above mentioned season 2) shows "[2] saenai-heroine-no-sodatekata-2" selecting episodes from this gives the error message: Download failed episode: 001 , please retry or check your internet connection
> 
> just fixed this on pr #244 and tested with saenai , turns out these special character animes have different links than the normal ones,
> 
> special character animes : title-episodenumber normal character animes : title-episode-episodenumber

I see.. I didn't notice that lol thanks for enlightening me.
