### ISSUE TITLE
sudo make not working

### ISSUE THREAD

**Issue by Bancsis** [pystardust/ani-cli#241]
<img width="452" alt="Screenshot 2021-12-31 at 13 41 23" src="https://user-images.githubusercontent.com/56519024/147826232-0b6c99af-5222-46de-95f4-58209b525644.png">

Before this most recent update sudo make was working fine, however, I couldn't watch anime after a certain point for some reason. I can now watch anime it's only the sudo make not working.

FYI this is on Mac.

**Comment by Dink4n** [comment]
Try adding empty quotes `""` after `-i` option in this line
https://github.com/pystardust/ani-cli/blob/6e860f40905127c96ff555d455bee7f88710feaf/Makefile#L11

Like this: `-i""`

**Comment by Bancsis** [comment]
> Try adding empty quotes `""` after `-i` option in this line
> 
> https://github.com/pystardust/ani-cli/blob/6e860f40905127c96ff555d455bee7f88710feaf/Makefile#L11
> 
> Like this: `-i""`

Same error

**Comment by ura43** [comment]
That change of the makefile was added as part of the update checking PR.
Works on my linux system, but that doesn't make it less of a bug.
@Dink4n do you have a mac by chance? Will be hard to troubleshoot this otherwise.

Try replacing `'2s}.*}ORIGINAL_DIR=$(CURRENT_DIR)}'` with `"2s}.*}ORIGINAL_DIR=$(CURRENT_DIR)}"`
Eplanation: This is supposed to do shell expansion, but the shell only expands things in double quotes and always treats things in single quotes as literal strings

**Comment by Bancsis** [comment]
> That change of the makefile was added as part of the update checking PR. Works on my linux system, but that doesn't make it less of a bug. @Dink4n do you have a mac by chance? Will be hard to troubleshoot this otherwise.
> 
> Try replacing `'2s}.*}ORIGINAL_DIR=$(CURRENT_DIR)}'` with `"2s}.*}ORIGINAL_DIR=$(CURRENT_DIR)}"` Eplanation: This is supposed to do shell expansion, but the shell only expands things in double quotes and always treats things in single quotes as literal strings

<img width="458" alt="Screenshot 2021-12-31 at 14 31 30" src="https://user-images.githubusercontent.com/56519024/147828363-dd8b65bd-90fc-4e61-bad0-48afca2d0a85.png">

So if I was to revert back to the previous makefile that you had a couple days ago, that wouldn't work anymore?

**Comment by ura43** [comment]
Very likely, but that is a good time to check if the dev who implemented it followed proper etiquette and made it an optional feature.
Please try it with the old makefile

**Comment by Bancsis** [comment]
Ah yes, seems to be working fine with the older makefile! Thanks!

**Comment by ura43** [comment]
Do you get any weird, unexpected output?

**Comment by Bancsis** [comment]
Nope, working perfectly as of right now.
