### ISSUE TITLE
make fails if a space exists in the name of any directory in the path to the directory where the repository is cloned to

### ISSUE THREAD

**Issue by tekmyndaspy** [pystardust/ani-cli#242]
working directory: `~/Git Repos/ani-cli`
attempted command: `sudo make`
response: 
```
# writes ORIGINAL_DIR variable to ani-cli file
sed -i '2s}.*}ORIGINAL_DIR='/root/Git Repos/ani-cli'}' ./ani-cli
sed: -e expression #1, char 28: unterminated `s' command
make: *** [Makefile:11: install] Error 1
```
workaround: do not clone the repository to a directory where a space exists in the name of any directory in the path to the directory

**Comment by Dink4n** [comment]
Fixed in 4b1f505

Reopen if issue persists
