### ISSUE TITLE
Better quality?

### ISSUE THREAD

**Issue by maxxxed69** [pystardust/ani-cli#243]
Is there any plans on adding other sites? 9anime, etc.

also, would it be feasable to add before watching the episode a quality selection? or maybe somehow make that toggleable?

**Comment by drabart** [comment]
I believe there aren't any plans for adding more sites as  it would require entirely different parsing. Also there already is quality selection option which I believe is enough.

**Comment by ura43** [comment]
There are even plans for giving a quality selection menu in interactive mode.

As for supporting more sites, it is not planned and not desireable for this program.
But I have a vague idea for introducing torrent support. Meaning smoke index + nyaa, downloaded through aria2

**Comment by ura43** [comment]
That would give the user a "all or nothing" choice when it comes to quality and bandwidth use
