### ISSUE TITLE
[Feature Request] Add an option to specify download directory 

### ISSUE THREAD

**Issue by Yeashu** [pystardust/ani-cli#245]

**Comment by Yeashu** [comment]
Please provide an option to specify download directory when downloading an anime.
like :-    `ani-cli -d  jujutsu-kaisen-tv   -downloadDirectory /home/anime/jujutsu-kaisen-tv  `

**Comment by ura43** [comment]
You're in luck. #96 adds that feature and I was gonna merge it today anyways

**Comment by Yeashu** [comment]
Thank you
