### ISSUE TITLE
when installed as described in bug #242 ani-cli produces errors

### ISSUE THREAD

**Issue by tekmyndaspy** [pystardust/ani-cli#246]
working directory: `~`
attempted command: `ani-cli`
response: 
```
/usr/local/bin/ani-cli: line 2: Repos/ani-cli: No such file or directory
/usr/local/bin/ani-cli: line 140: [: !=: unary operator expected
Search Anime:
```
\
caveats: the script works as expected after the errors are produced and nothing immediately seems to be broken. as such, this may be more of a polish or quality assurance measure.
possible causes: the script does not expect spaces in any paths, such as the path to the 'true' ani-cli that the symlink in /usr/local/bin points to
\
bug mentioned in title for ease of access: #242

**Comment by Dink4n** [comment]
Try to use the latest version

**Comment by tekmyndaspy** [comment]
everything is working as expected after updating to the latest version and running `sudo make uninstall` then `sudo make install`. thank you so much for the repeated aid!
