### ISSUE TITLE
Easier way to update 

### ISSUE THREAD

**Issue by etisHere** [pystardust/ani-cli#247]
Use to be able to just delete the original folder and re download/make the entire thing to update but now to update i need to go into usr/local/bin and delete the file there.

A small bash script that could delete both the dir you clone and the file that is made while then also cloning the file after and making it would be EXTREMELY handy for every time there is a update.

**Comment by ura43** [comment]
I 100% agree and am annoyed by that myself.
I will update the makefile today so that updating, wether by deleting the folder and re-downloading or via a git pull, works again and works well

**Comment by ura43** [comment]
Closing, as linked to #251 and maybe made obsolete by #255
