### ISSUE TITLE
Smooth some rough edges

### ISSUE THREAD

**Issue by ura43** [pystardust/ani-cli#250]
- [x] Update and sort helptext (L22-40)
- [x] Sort getopts and case $OPT (L386-430)
- [ ] Dry `get_embedded_video_link` (L94-118)
- [x] Make dep_ch not die, but fail. Adapt dep_ch section to test and die after. Enabling optional feature checking (L163-169, 432)
- [x] Dry `case $player_fn` (L333-353)
- [ ] Convert current -p into an optional argument for -d (L401)
- [x] Check update: supress git output (L148-161)
~Check update: advise force pull (L158)~ superseded by #255
- [x] Makefile: symlink with force (L13)
- [x] Makefile: unlink on uninstall (L19)
~Fix Makefile (L1-L21)~ superseded by #255 
~Lastly: Expand this list~ better open another issue in a few weeks

**Comment by ura43** [comment]
Dry = "don't repeat yourself" btw

**Comment by Dink4n** [comment]
Cool

**Comment by ura43** [comment]
I'll let you go at it @Dink4n

**Comment by ura43** [comment]
Are you still on it or should I finish today?

**Comment by Dink4n** [comment]
>  Convert current -p into an optional argument for -d (L401)

command-line options with optional args seems to be [discouraged explicitly](https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap12.html#tag_12_02)

> Guideline 7: Option-arguments should not be optional.

**Comment by ura43** [comment]
That is interesting, let me look into it

**Comment by ura43** [comment]
"Some of the standard utilities do not conform to all of these guidelines"
if gnu sed decides to not conform, we might as well not either.

For me its mostly about keeping, or rather moving towards, mnemonic shortcuts. So if you're really uncomfortable with optional arguments, let's make it an uppercase D.
-p is way more suited to become an option to specify the player
