### ISSUE TITLE
could we get some more maintainers

### ISSUE THREAD

**Issue by crypticC0der** [pystardust/ani-cli#26]
you did a great job but are rarely around for pull requests and there are tons of updates ignored

**Comment by crypticC0der** [comment]
i can help if needed

**Comment by pystardust** [comment]
I usually do comment on PR, sorry If i have missed out of some.
@nasseef20  seems to have active participation, I have invited them as a collaborator

**Comment by ura43** [comment]
I really like labels :smile: 
More maintainers are definitely welcome, but I'll unpin this until url extraction and parsing work again

**Comment by ura43** [comment]
Considering the tremendous progress of the past two days, I'll close this issue.
Maintainers and contributions are always welcome, but its not a problem anymore
