### ISSUE TITLE
--dub option broken

### ISSUE THREAD

**Issue by ura43** [pystardust/ani-cli#261]
`ani-cli --dub flcl progressive` still makes me chose between `flcl-progressive` and `flcl-progressive-dub`.
I suspect this option broke along the way.
Would be cool to have it working again, but consider it a low priority

**Comment by ura43** [comment]
Using latest version.
Can someone confirm the issue is not just on my end?

**Comment by RaynardGerraldo** [comment]
> Using latest version. Can someone confirm the issue is not just on my end?

can you try and select the non dub option with --dub ? i want to confirm that this dub option starts working after the anime is selected, meaning that the 2 outcomes from this is either it just doesnt play anything or it actually plays the dub version regardless of the choice

**Comment by ura43** [comment]
> it actually plays the dub version regardless of the choice

**Comment by RaynardGerraldo** [comment]
> > it actually plays the dub version regardless of the choice

Yea the current dub version just doesnt do anything other than play dub version regardless of the choice.

Might have to do something like check if the search returns 2 options(only the anime and dub version) then play dub and not show option,else if it shows more than 2,lets say theres a movie version, then show option and let user pick

Idk if this could actually be implemented,havent actually looked at it,but ill try sometime later

**Comment by ura43** [comment]
Would be worth playing around with for sure. But if it adds too much complexity we can just leave it for now
