### ISSUE TITLE
Flag for specifying download directory is not working 

### ISSUE THREAD

**Issue by Yeashu** [pystardust/ani-cli#265]
After last merges this feature[#96 ] has stopped working , now it just downloads the video in the ani-cli directory instead of the specified directory.

**Comment by muhi03** [comment]
<img width="1107" alt="Screenshot 2022-01-03 at 00 25 13" src="https://user-images.githubusercontent.com/49244280/147892191-b770a2a2-ca2f-4f1c-b753-787a59a4b47c.png">

This helped for me...

**Comment by Yeashu** [comment]
Thank you
It worked but i had to remove the `-#` .
