### ISSUE TITLE
(Windows) No search results found

### ISSUE THREAD

**Issue by MrMeugh** [pystardust/ani-cli#268]
I'm using ani-cli via git bash on windows 10, having followed the windows install directions to the letter. When I type in my query, it always returns "No search results found"

Examples pasted from git bash: 
```
$ ./ani-cli-win
Search Anime: Dragon Ball
No search results found

$ ./ani-cli-win hokuto no ken
No search results found
```

I cloned ani-cli about an hour ago (January 2nd, 2022 ~9 pm EST) so it shouldn't be a matter of just pulling it and trying again. I also tested the RaynardGerraldo fork with the exact same results.

I've tried ani-cli before a few times before (have never quite gotten it to work). I suspect the issue is with my computer, since this result seems consistent on my machine across attempts (the last one being about a month ago).
Any help with this would be appreciated. I really want this to work.

**Comment by hicor13** [comment]
I have the same problem right now on Git Bash:
`$ ani-cli Mob Psycho 100 II`
`No search results found`

**Comment by Dink4n** [comment]
Fixed in the latest commit. Can you try to use it now?

**Comment by MrMeugh** [comment]
> Fixed in the latest commit. Can you try to use it now?

It's working now! Thank you so much, I didn't think this would get resolved this quickly!

**Comment by hicor13** [comment]
> Fixed in the latest commit. Can you try to use it now?

Working on mine too!
