### ISSUE TITLE
Unable to build on MacBook Pro 2015 (Intel)

### ISSUE THREAD

**Issue by Rohit-Rangaraj** [pystardust/ani-cli#275]
I tried building ani-cli on Mac, and it seems to throw me this weird error. It works flawlessly on my Arch Linux system, though.
Please let me know what to do.
<img width="597" alt="Screenshot 2022-01-03 at 4 56 26 PM" src="https://user-images.githubusercontent.com/20149534/147925571-37c1ed9b-65c6-4bf4-bdd4-b1b1ba7d8cf1.png">

**Comment by Dink4n** [comment]
Duplicate of https://github.com/pystardust/ani-cli/issues/205#issuecomment-1003579678

**Comment by ura43** [comment]
Just sed working differently on mac os than on linux. It's a known issue

**Comment by ura43** [comment]
> Duplicate of [#205 (comment)](https://github.com/pystardust/ani-cli/issues/205#issuecomment-1003579678)

You wanna fix that makefile?

**Comment by ura43** [comment]
As in disable our update checking and make the thing cp again because ln incompatibility

**Comment by ura43** [comment]
Fixed with [b808651](https://github.com/pystardust/ani-cli/commit/b80865148aa80939e1def1ff7294a166c35c5297)

**Comment by Rohit-Rangaraj** [comment]
Thanks! It works flawlessly now!
