### ISSUE TITLE
VLC media player unable to play video

### ISSUE THREAD

**Issue by Anarchyserver** [pystardust/ani-cli#276]
i was trying to run the updated version of the tool and using vlc as my video player and this error message pops up.
Your input can't be opened:
VLC is unable to open the MRL 'file:///home/windows/Downloads/anipy-cli-master/src/__init__.py'. Check the log for details.
Your input can't be opened:
VLC is unable to open the MRL 'file:///home/windows/Downloads/anipy-cli-master.zip#!/anipy-cli-master/src/__init__.py'. Check the log for details.
(windows is my account name and its a linux vm)

**Comment by Dink4n** [comment]
Are you using `ani-cli`?

**Comment by RaynardGerraldo** [comment]
> i was trying to run the updated version of the tool and using vlc as my video player and this error message pops up. Your input can't be opened: VLC is unable to open the MRL 'file:///home/windows/Downloads/anipy-cli-master/src/**init**.py'. Check the log for details. Your input can't be opened: VLC is unable to open the MRL 'file:///home/windows/Downloads/anipy-cli-master.zip#!/anipy-cli-master/src/**init**.py'. Check the log for details. (windows is my account name and its a linux vm)

We have no "init.py"

**Comment by Anarchyserver** [comment]
> > i was trying to run the updated version of the tool and using vlc as my video player and this error message pops up. Your input can't be opened: VLC is unable to open the MRL 'file:///home/windows/Downloads/anipy-cli-master/src/**init**.py'. Check the log for details. Your input can't be opened: VLC is unable to open the MRL 'file:///home/windows/Downloads/anipy-cli-master.zip#!/anipy-cli-master/src/**init**.py'. Check the log for details. (windows is my account name and its a linux vm)
> 
> We have no "init.py"

as in you dont have the file

**Comment by Anarchyserver** [comment]
> Are you using `ani-cli`?

yes

**Comment by Dink4n** [comment]
You should report your issue on [anipy-cli](https://github.com/sdaqo/anipy-cli)

**Comment by ura43** [comment]
Nope, you are using anipy-cli. Report your issue there
