### ISSUE TITLE
Running `sudo make` gives errors.

### ISSUE THREAD

**Issue by yathy2007** [pystardust/ani-cli#277]
Running `sudo make` after pulling the changes from the repo.
![ani-cli](https://user-images.githubusercontent.com/95642891/147932605-6c6bc3e5-b0b2-40ba-9c87-ca0cd7096ab0.png)

**Comment by yathy2007** [comment]
Running `sudo make uninstall` then `sudo make` fixes the problem.

**Comment by Quicksilver151** [comment]
i got the same issue
