### ISSUE TITLE
Update Synopsis

### ISSUE THREAD

**Issue by Malertach** [pystardust/ani-cli#278]
Some options, like -u and -n, are mutually exclusive (to be more precise, the last option overwrites prior options), while others, like -v and -k can be used in addition to other options.

The user should be informed about this.
The `help_text`printed with the -h option and the [usage section of the README.md](https://github.com/pystardust/ani-cli/blob/28d180665e8979167337706e4b7ecd3eb9b1ec73/README.md?plain=1#L18) need an update.

According to [POSIX argument syntax](https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap12.html) I propose something like this:
  ```
Usage:
    ani-cli [-kv] [--dub] [-q <quality>] [-d] [<query>]
    ani-cli [-kv] [--dub] [-q <quality>] -u | -n | -H
    ani-cli -h | -D
Options
    -u shows anime from history with unwatched episodes
    -n show recent anime
    -h show helptext
    -d download episode
    -H continue with next unwatched episode from history of watched series
    -D delete history
    -q set video quality (best|worst|360|480|720|1080)
    -k on keypress navigation (previous/next/replay/quit episode)
    --dub play the dub version if present
    -v use VLC as the media player
  
Episode selection:
    Add 'h' on beginning for episodes like '6.5' -> 'h6'
  
    Multiple episodes can be chosen given a range
      Choose episode [1-13]: 1 6
      This would choose episodes 1 2 3 4 5 6
  ```
Some formatting is needed to indicate the default of the -q option.

The ["bloated-ani-cli" branch](https://github.com/pystardust/ani-cli/tree/bloated-ani-cli) would benefit from this update. As some feature reduction was discussed in #255, the options used in the master branch may change soon.

PS:
Change the line https://github.com/pystardust/ani-cli/blob/28d180665e8979167337706e4b7ecd3eb9b1ec73/ani-cli#L9
to `prog=$0` so the `help_text` matches the program call:
```
╭─malertach@Kepler in ~/Dokumente
╰─λ ./GitHub/ani-cli/ani-cli -h
USAGE: ./GitHub/ani-cli/ani-cli <query>
-u      shows anime from history with unwatched episodes
-n      show recent anime
...
```

**Comment by Dink4n** [comment]
Can you do a PR?

**Comment by Malertach** [comment]
> Can you do a PR?

Yes. To which branch do you recommend.

**Comment by ura43** [comment]
Merged

**Comment by ura43** [comment]
Actually merged into master too. Great synopsis
