### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by the-anonymous-raven** [pystardust/ani-cli#28]
Irrespective of what search query I put, it shows 'no search results'. Also, on entering no search query, I get 'no search result'.

Is there a problem with the script or any reason why it is happening?

**Comment by Dink4n** [comment]
The fault is with the site ani-cli is scraping 9anim.vip. They recently changed their site name to 99anime.me. So changing 9anim.vip to 99anime.me should work.

You can always use my fork of ani-cli that uses the old gogoanime implementation [ani-cli](https://github.com/dink4n/ani-cli).

**Comment by the-anonymous-raven** [comment]
Thanks, I just noticed you can modify script to make curl to follow redirect url(via -L flag) and it works too.

**Comment by DencenDab** [comment]
I tried your form of ani-cli on the ubuntu app of windows but it says that mpv does not exist even though I even set it as the default video player. Is there a way to fix it?

**Comment by VarLad** [comment]
@pystardust Not working again!

**Comment by Dink4n** [comment]
I think the old script before the captcha is working now
