### ISSUE TITLE
Garbage in output when watching episode, probably &> bashism fault

### ISSUE THREAD

**Issue by ejkozan** [pystardust/ani-cli#281]
I found out that when after choosing episode when player starts, there is additional garbage output in terminal:

```
$HOME/bin/ani-cli: 346: kill: Illegal number:

Video playingerror: garbage option

Usage:
 ps [options]

 Try 'ps --help <simple|list|output|threads|misc|all>'
  or 'ps --help <s|l|o|t|m|a>'
 for additional help text.

For more details see ps(1).
```
I am using dash as POSIX compliant shell. If I run ani-cli using bash, there are no problems at all. I suppose it can be connected with this bit:
```

if ps "$PID" &> /dev/null; then
             ^----------^ SC3020 (error): In dash, &> is not supported.
```
With can be seen on bashism website as bash thing (also on shellcheck):

Redirect both stdout and stderr

Change:
`>& and &>`

To:
`command > file 2>&1 or command 2>&1 | othercommand`

And by the way: great job with ani-cli! Keep going guys!

**Comment by ura43** [comment]
Thats why we need shellcheck asap.
Oh wait, that was my job to implement :sweat_smile: 

Glad you like our script. We should find our way back to full posix compliance in the following days
