### ISSUE TITLE
cannot reach servers

### ISSUE THREAD

**Issue by GetKeijo** [pystardust/ani-cli#282]
![Kuvakaappaus 2022-01-03 23-32-08](https://user-images.githubusercontent.com/83073733/147982909-421f391d-52e2-4e04-b22a-7c4aa4e7858e.png)

**Comment by mazylol** [comment]
I just got the same error.

**Comment by kaumidere** [comment]
same

**Comment by Gokurockx9** [comment]
Having the same error.

**Comment by Tiggax** [comment]
same

**Comment by demrich** [comment]
I'm getting a `403: Forbidden` when trying to hook the video directly to mpv. Seems like it may require an API key now...

**Comment by Cricketjds3** [comment]
OK, so I got the error to go by following Dink4n's QA branch and merging it into the master, this stopped the "Cannot reach servers!" but no luck in mpv playing anything. Am hoping it's as simple as a line of code out of place but if demrich is right I'm SOL.

**Comment by 4cecoder** [comment]
<img width="622" alt="image" src="https://user-images.githubusercontent.com/88108711/147994963-fe5dd9b9-0dee-448c-95c1-741ca6a1612b.png">

**Comment by Yeashu** [comment]
Got the same error .
`curl: (3) URL using bad/illegal format or missing Url`

**Comment by bestpeople105** [comment]
phew, i thought i am the only one who have this error

**Comment by tarkerin** [comment]
i got the same error xd

**Comment by HenryQuan** [comment]
This might be potentially broken by #209 because the referrer is missing. However, I am not very sure.

**Comment by RaynardGerraldo** [comment]
like @HenryQuan said, yes, it needs to have --referer again to work, but it is now opening the videos really slow, because the current link available in gogoanime download page is a download stream `https://gogo-cdn.com/download.php?url=aHR0cHM6LyAdeqwrwedffryretgsdFrsftrsvfsfsr9jZG4zNCURASDGHUSRFSJGYfdsffsderFStewthsfSFtrftesdf5hbmljZG4uc3RyZWFtL3VzZXIxMzQyLzFjN2QzMjI2NDc0Yjg2ODQ5ZTcxY2Y4NzI4YmNlOGFmL0VQLjEyLnYwLjE2NDEyMjYwODIuMzYwcC5tcDQ/dG9rZW49S1dkZm50UFdKMFJYRTJKZE5pQ3VMdyZleHBpcmVzPTE2NDEyNzk3NjAmaWQ9MTc3NTUz`

The actual video link is hidden in this download stream,which if accessed will return 403 forbidden `https://cdn34.anicdn.stream/user1342/1c7d3226474b86849e71cf8728bce8af/EP.12.v0.1641226082.360p.mp4?token=RRtgLqhiJOLDtBEXEn-0Uw&expires=1641278260&id=177553` , i tried using a referer, it still returns 403 forbidden

**Comment by Dink4n** [comment]
Fixed in the latest commit. Can you try to use it now?

**Comment by RaynardGerraldo** [comment]
> Fixed in the latest commit. Can you try to use it now?

its playing really slow for me, how about you?

**Comment by Yeashu** [comment]
download is not working.

**Comment by bestpeople105** [comment]
same here, download doesnt work properly

**Comment by ypo777** [comment]
> > Fixed in the latest commit. Can you try to use it now?
> 
> its playing really slow for me, how about you?

Same here. It is really slow.

**Comment by ksyasuda** [comment]
adding `-e "$dpage_link"` to the curl command fixes downloads.  Really slow though even for small file like isekai quartet.

`curl -L -# -C - -e "$dpage_link" "$video_url" -o "${anime_id}-${episode}.mp4" &&`

**Comment by HenryQuan** [comment]
@RaynardGerraldo I am using a different gogoanime fork and it works for me. This is my [implementation](
https://github.com/HenryQuan/AnimeGo-Re/blob/168b1f94be79556a3b23d9288d69a5b85f617fa9/project/lib/ui/page/EpisodePage.dart#L376). I am not so sure how ani-cli is getting the link. I am doing a simple replace of the streaming link to get the download link and then, I parse links from it. However, it is a little bit slower now. It was almost instant when it is streaming. Now, it takes a few seconds before it could load the video.

**Comment by RaynardGerraldo** [comment]
> adding `-e "$dpage_link"` to the curl command fixes downloads. Really slow though even for small file like isekai quartet.
> 
> `curl -L -# -C - -e "$dpage_link" "$video_url" -o "${anime_id}-${episode}.mp4" &&`



> -e "$dpage_link"

this is the same approach as playing a video, and both are moving really slowly, they might have did something to limit the bandwidth

**Comment by RaynardGerraldo** [comment]
> @RaynardGerraldo I am using a different gogoanime fork and it works for me. This is my [implementation](https://github.com/HenryQuan/AnimeGo-Re/blob/168b1f94be79556a3b23d9288d69a5b85f617fa9/project/lib/ui/page/EpisodePage.dart#L376). I am not so sure how ani-cli is getting the link. I am doing a simple replace of the streaming link to get the download link and then, I parse links from it. However, it is a little bit slower now. It was almost instant when it is streaming. Now, it takes a few seconds before it could load the video.

does it play slow too? the method you mentioned is also what we are doing

**Comment by Dink4n** [comment]
Fixed downloading and increased speed in the latest commit. Try to use it now

**Comment by HenryQuan** [comment]
@RaynardGerraldo By slow, do you mean it is slow for VLC to load or it is slow while streaming (like taking time to load). As I said, it is slower while loading the video (about 2 - 6 seconds, was instant). For 1080P videos, it does lag once a while so I started using 720P and it works fine.

**Comment by RaynardGerraldo** [comment]
> Fixed downloading and increased speed in the latest commit. Try to use it now

downloading still moving at 0.1 %  per second for me, but i just tried using aria2c and it speeds it up, not as fast as a couple of days ago tho

**Comment by HenryQuan** [comment]
I tried downloading from the website and it was like 400kb/s (because this is why it lags on 1080P). Now, it is a bit faster around 1mb - 2mb per second. Maybe, this is a problem of the streaming website since there are more people using it.

**Comment by ura43** [comment]
Please check if PR #290 solves the issues

**Comment by GetKeijo** [comment]
> ![Kuvakaappaus 2022-01-03 23-32-08](https://user-images.githubusercontent.com/83073733/147982909-421f391d-52e2-4e04-b22a-7c4aa4e7858e.png)

it started to work for me after doing git clone again, though its kinda laggy.

**Comment by RaynardGerraldo** [comment]
can anyone help me confirm that streaming is slow?

**Comment by ura43** [comment]
> can anyone help me confirm that streaming is slow?

Slower than usual

**Comment by CoolnsX** [comment]
It will be like that now... in streaming we can't do anything... But in downloading we should switch to aria2c.. atleast it's download speed is better than curl.. 

I know it will be adding another program as dependency..

**Comment by RaynardGerraldo** [comment]
Yea i think because the direct link for the videos that we have right now is a download stream,its streaming at a downloading pace, and btw the vidstreamingcdn link that we used to stream is still there and its fast as ever but havent found a way to access it yet

**Comment by CoolnsX** [comment]
> Yea i think because the direct link for the videos that we have right now is a download stream,its streaming at a downloading pace, and btw the vidstreamingcdn link that we used to stream is still there and its fast as ever but havent found a way to access it yet

can you mention in which anime are you getting vidstreamingcdn.. I want to check it myself..

**Comment by RaynardGerraldo** [comment]
> > Yea i think because the direct link for the videos that we have right now is a download stream,its streaming at a downloading pace, and btw the vidstreamingcdn link that we used to stream is still there and its fast as ever but havent found a way to access it yet
> 
> can you mention in which anime are you getting vidstreamingcdn.. I want to check it myself..

I used Dragon ball to test that

**Comment by lunicarus** [comment]
it stopped to work again my friends
