### ISSUE TITLE
Very slow downloads occasionally

### ISSUE THREAD

**Issue by PhantomDerp** [pystardust/ani-cli#289]
Sometimes it takes upwards of 5-30 seconds of wait for one second of video. Much slower than going to gogoanime directly.

**Comment by PhantomDerp** [comment]
When it does this, I can watch the same videos with no delays by going to gogoanime directly, so it isn't my internet or the servers

**Comment by ura43** [comment]
Yep, can 100% confirm.
**occasionally** it downloads like a snail. Other times it preloads a whole episode in the blink of an eye

**Comment by ura43** [comment]
Indirect duplicate of #282

**Comment by fazecasdavid** [comment]
Most episodes are downloading with good speeds (30MB/s), but for some episodes (let's say one in ten) the downloading speed drops to a few Kb/s
