### ISSUE TITLE
Not working again

### ISSUE THREAD

**Issue by CoolnsX** [pystardust/ani-cli#29]
fetching dead-links instead...

**Comment by 3hree6ix0** [comment]
I'm having the same issue, i cross checked the links in the script and goganime, seems fine, but still doesnt work, wierd.

**Comment by CoolnsX** [comment]
I modified the script and almost reached to this stage

**href="https://storage.googleapis.com/323211/KFV89KYGYVDY/st22_kobayashi-san-chi-no-maid-dragon-s-episode-10-HD.mp4" download>Download**

Now I want to extract link... I am new to shell scripting and I reached to this point... using some reverse engineering with script... now I have to extract link..

**Comment by CoolnsX** [comment]
# replace the get_links() function to this one

get_links () {
    # get the download page url
    anime_id=$1
    ep_no=$2

    dpage_url=$(
    curl -s "https://gogoanime.pe/$anime_id-episode-$ep_no" |
    sed -n -E 's_^[[:space:]]*<li class="dowloads"><a href="([^"]*)".*_\1_p')

    curl -s "$dpage_url" |
    sed -n -E 's/^[[:space:]]*href="([^"]*)"\ download>Download/\1/p' | sed 1q
}

**Comment by CoolnsX** [comment]
`dpage_url=$(
    curl -s "https://gogoanime.pe/$anime_id-episode-$ep_no" |
    sed -n -E 's_^[[:space:]]*<li class="dowloads"><a href="([^"]*)".*_\1_p')

    curl -s "$dpage_url" |
    sed -n -E 's/^[[:space:]]*href="([^"]*)"\ download>Download/\1/p' | sed 1q`
