### ISSUE TITLE
unable to select quality of video

### ISSUE THREAD

**Issue by Quicksilver151** [pystardust/ani-cli#291]
program now only downloads the highest quality regardless of selected quality

even the anime i previously downloaded in a lower resolution with this program cannot be downloaded in anything but the highest resolution now

it keep saying `Current video quality is not available (defaulting to highest quality)`

is this an issue due to the servers not providing quality?
i doubt it

**Comment by ura43** [comment]
I doubt it too. 
Removing quality selection is planned in the following weeks, please check the bloated-ani-cli branch and report if the issue remains.
Also, what anime? I want to reproduce the issue

**Comment by Quicksilver151** [comment]
wait what

you're removing quality selection?

thats like the most important part for me who has crap internet connection
and i dont think selecting quality is enough of a change to make it bloated. its a pretty standard function

as for, anime.. take fruits basket second season for example. i once downloaded an episode with and old version of this code in 480 pixels. now im unable to download it in 480 pixels again

**Comment by RaynardGerraldo** [comment]
> wait what
> 
> you're removing quality selection?
> 
> thats like the most important part for me who has crap internet connection and i dont think selecting quality is enough of a change to make it bloated. its a pretty standard function
> 
> as for, anime.. take fruits basket second season for example. i once downloaded an episode with and old version of this code in 480 pixels. now im unable to download it in 480 pixels again

yea gogoanime completely changed the direct video link, and the quality tag that we used to get quality is no longer there
