### ISSUE TITLE
scrape sbplay2 for streaming and downloading.. in gogoanime downloads section..

### ISSUE THREAD

**Issue by CoolnsX** [pystardust/ani-cli#296]
I think a found a way to scrape sbplay2 in gogoanime's download page..
how??
E.g. :-

curl "https://sbplay2.com/d/owxufky778yc" -o temp
there are lines

a href="#" onclick="download_video('owxufky778yc','n','17072097-160-202-16413
13048-14515e036be2aba23233a4d2b63381e8')">Normal quality</a></td><td>1280x720, 164.0 MB</td></tr>
        
a href="#" onclick="download_video('owxufky778yc','h','17072097-160-202-16413
13048-14515e036be2aba23233a4d2b63381e8')">High quality</a></td><td>1920x1080, 285.7 MB</td></tr>       

a href="#" onclick="download_video('owxufky778yc','l','17072097-160-202-16413
13048-14515e036be2aba23233a4d2b63381e8')">Low quality</a></td><td>640x360, 72.8 MB

Onclicking on one of the following links in browser lets say "High quality" will give us this link

https://sbplay2.com/dl?op=download_orig&id=owxufky778yc&mode=h&hash=17072097-160-202-1641313161-fd5d52dcc704c5c15f47dcf441496366

found something similar??.. if yes.. then you got everything... we just need to write another function to extract those values from download video function.. and replace the values with it..

on using curl on above link we can extract download link.. which looks like this

https://pr13.sbcdnvideo.com/tysxfzbnzc6oj6cdaapbjqcghm4gab5fkew7ac2oeixjolaifhbkywmwqfaq/kimetsu-no-yaiba-yuukaku-hen-episode-51641172622.0.mp4

this link is fast and doesn't require referer link.. the above link is valid for 3 hours.. and can be used as scraping and downloading.. you can try it.. by clicking on it.. and also passing it in mpv directly..

and if we pass it in aria2c we will get 4-5 times the download speed we get in browser.. i checked it..

**Comment by RaynardGerraldo** [comment]
> I think a found a way to scrape sbplay2 in gogoanime's download page.. how?? E.g. :-
> 
> curl "https://sbplay2.com/d/owxufky778yc" -o temp there are lines
> 
> a href="#" onclick="download_video('owxufky778yc','n','17072097-160-202-16413 13048-14515e036be2aba23233a4d2b63381e8')">Normal quality1280x720, 164.0 MB
> 
> a href="#" onclick="download_video('owxufky778yc','h','17072097-160-202-16413 13048-14515e036be2aba23233a4d2b63381e8')">High quality1920x1080, 285.7 MB
> 
> a href="#" onclick="download_video('owxufky778yc','l','17072097-160-202-16413 13048-14515e036be2aba23233a4d2b63381e8')">Low quality640x360, 72.8 MB
> 
> Onclicking on one of the following links in browser lets say "High quality" will give us this link
> 
> https://sbplay2.com/dl?op=download_orig&id=owxufky778yc&mode=h&hash=17072097-160-202-1641313161-fd5d52dcc704c5c15f47dcf441496366
> 
> found something similar??.. if yes.. then you got everything... we just need to write another function to extract those values from download video function.. and replace the values with it..
> 
> on using curl on above link we can extract download link.. which looks like this
> 
> https://pr13.sbcdnvideo.com/tysxfzbnzc6oj6cdaapbjqcghm4gab5fkew7ac2oeixjolaifhbkywmwqfaq/kimetsu-no-yaiba-yuukaku-hen-episode-51641172622.0.mp4
> 
> this link is fast and doesn't require referer link.. the above link is valid for 3 hours.. and can be used as scraping and downloading.. you can try it.. by clicking on it.. and also passing it in mpv directly..
> 
> and if we pass it in aria2c we will get 4-5 times the download speed we get in browser.. i checked it..

wow this is a nice step forward, we could try and build the link from the ground up with those button elements, but in your example we are missing some arguments in the link "161-fd5d52dcc704c5c15f47dcf441496366" 

based on this 
> a href="#" onclick="download_video('owxufky778yc','h','17072097-160-202-16413 13048-14515e036be2aba23233a4d2b63381e8')">High quality1920x1080, 285.7 MB

**Comment by CoolnsX** [comment]
> wow this is a nice step forward, we could try and build the link from the ground up with those button elements, but in your example we are missing some arguments in the link "161-fd5d52dcc704c5c15f47dcf441496366"
> 
> based on this

that maybe changed during the testing I was doing earlier.. anyway I checked it and it is working flawlessly...

**Comment by CoolnsX** [comment]
Anyone interested in making the functions based on above testing.. because tomorrow is my exam... and I will be free after 2 pm tomorrow...

**Comment by RaynardGerraldo** [comment]
> > wow this is a nice step forward, we could try and build the link from the ground up with those button elements, but in your example we are missing some arguments in the link "161-fd5d52dcc704c5c15f47dcf441496366"
> > based on this
> 
> that maybe changed during the testing I was doing earlier.. anyway I checked it and it is working flawlessly...

yes just confirmed that we can use the numbers as the hash , i can try to implement this to the fix but unfortunately its night time here and I got school , maybe @Dink4n ?

**Comment by CoolnsX** [comment]
> I think a found a way to scrape sbplay2 in gogoanime's download page.. how?? E.g. :-
> 
> curl "https://sbplay2.com/d/owxufky778yc" -o temp there are lines
> 
> a href="#" onclick="download_video('owxufky778yc','n','17072097-160-202-16413 13048-14515e036be2aba23233a4d2b63381e8')">Normal quality1280x720, 164.0 MB
> 
> a href="#" onclick="download_video('owxufky778yc','h','17072097-160-202-16413 13048-14515e036be2aba23233a4d2b63381e8')">High quality1920x1080, 285.7 MB
> 
> a href="#" onclick="download_video('owxufky778yc','l','17072097-160-202-16413 13048-14515e036be2aba23233a4d2b63381e8')">Low quality640x360, 72.8 MB
> 
> Onclicking on one of the following links in browser lets say "High quality" will give us this link
> 
> https://sbplay2.com/dl?op=download_orig&id=owxufky778yc&mode=h&hash=17072097-160-202-1641313161-fd5d52dcc704c5c15f47dcf441496366
> 
> found something similar??.. if yes.. then you got everything... we just need to write another function to extract those values from download video function.. and replace the values with it..
> 
> on using curl on above link we can extract download link.. which looks like this
> 
> https://pr13.sbcdnvideo.com/tysxfzbnzc6oj6cdaapbjqcghm4gab5fkew7ac2oeixjolaifhbkywmwqfaq/kimetsu-no-yaiba-yuukaku-hen-episode-51641172622.0.mp4
> 
> this link is fast and doesn't require referer link.. the above link is valid for 3 hours.. and can be used as scraping and downloading.. you can try it.. by clicking on it.. and also passing it in mpv directly..
> 
> and if we pass it in aria2c we will get 4-5 times the download speed we get in browser.. i checked it..

one thing to note here.. we can get different quality download links just by changing "mode" value in the sbplay2.com link..

**Comment by ura43** [comment]
Great catch!
This can wait until tomorrow,
good luck on your exam

**Comment by CoolnsX** [comment]
`
#!/bin/sh

link=$(curl -s "$1" | sed -n -E 's/.*a href="#" onclick="download_video([^"]*)".*/\1/p' | head -1)
echo "$link"

m="n"
i=$(printf "$link" | cut -d\' -f2)
h=$(printf "$link" | cut -d\' -f6)

url=$(curl -s "https://sbplay2.com/dl?op=download_orig&id=${i}&mode=${m}&hash=${h}" | sed -n -E 's/<a href="([^"]*.mp4)".*/\1/p')
echo "$url"
mpv "$url"
`
shell code... saved it and execute it by providing sbplay link as from gogoanime download page... and it will open the link into mpv
like
prog_name "sbplay link"

**Comment by CoolnsX** [comment]
sbplay2 faq's..

![2022-01-05-0227](https://user-images.githubusercontent.com/76195824/148123180-14120726-a8f1-495c-84a8-ac9e34db4754.png)

so we will get gogoanime every video link here... glad I chose to scrape sbplay2..

**Comment by CoolnsX** [comment]
Made the PR... 
@RaynardGerraldo @ura43 @Dink4n 
Please check it..
