### ISSUE TITLE
VLC can't open link

### ISSUE THREAD

**Issue by ellischung** [pystardust/ani-cli#298]
I was using ani-cli on windows fine until I ran into this error on VLC when running it recently. I tried going to the URL on a browser but it led to a 403 error. I reinstalled VLC but it didn't fix the issue. Any suggestions on what I should do?
![12341](https://user-images.githubusercontent.com/45402390/148143328-1e312cc9-cebb-42e4-9538-8452ba4d48f3.png)

**Comment by JRCdev** [comment]
I've encountered the same issue today.
My workaround was to modify line 237 of `ani-cli-win` to the following:
```
$player_fn "$video_url" --http-referrer="$dpage_link" --http-user-agent="Mozilla/5.0" --adaptive-use-access  >/dev/null 2>&1
```
and then rerunning the `chmod` and `install` commands from the readme.

Why might adding the `http-referrer` argument work? Not entirely sure, but I picked up on that being the issue when playing around with [this links page](https://gogoplay1.com/download?id=MzE3MzA=&typesub=Gogoanime-SUB&title=Legend+of+the+Galactic+Heroes+Episode+1) that the script would get the final link from and right click + opening the first download link in a new tab (started a download) versus copying that link and opening in a new window (403 error).

Could be some anti-scraping measure on their side ;)
