### ISSUE TITLE
Quality control of anime

### ISSUE THREAD

**Issue by Developer-walnoot** [pystardust/ani-cli#3]
The possibility of streaming anime in 720p or 1080p would be awesome from within ani-cli, what is your main focus for now?

**Comment by pystardust** [comment]
Currently ani-cli gets the first downloadable link possible, which is the highest downloadable quality and show it. If no downloadable link is available then it scrapes streamtape for the  it. There could a possibility of downgrading the quality but I don't thing we could make the quality any better. Unless we look into other anime site.
What I figured out is most anime sites use the same video streams, so even that possibility is unlikely. But do let me know if you find other anime sites which provide higher res than gogoanimw.

**Comment by dustxyz** [comment]
> Currently ani-cli gets the first downloadable link possible, which is the highest downloadable quality and show it. If no downloadable link is available then it scrapes streamtape for the it. There could a possibility of downgrading the quality but I don't thing we could make the quality any better. Unless we look into other anime site.
> What I figured out is most anime sites use the same video streams, so even that possibility is unlikely. But do let me know if you find other anime sites which provide higher res than gogoanimw.

This script can be modified to work with AnimeFLV?

**Comment by sanjublk** [comment]
is there a way to watch episodes in 360p.current videos quality i am getting is 1080ps

**Comment by CoolnsX** [comment]
> is there a way to watch episodes in 360p.current videos quality i am getting is 1080ps

Just change "sed 1q" in get links() function to "
'grep "sd" ' and it will play 480p or less resolution videos if available..
