### ISSUE TITLE
403 Forbidden on www01.anicdn.stream because of missing header

### ISSUE THREAD

**Issue by Almo7aya** [pystardust/ani-cli#30]
Hello,
I think gogoanime.vc added some checks to verify the origin of the requests using the `Referer` header
this can easily bypassed by hard-coding the required header value

I edited the line 209 and now it's working fine
```sh
setsid -f $player_fn --http-header-fields='Referer: https://streamani.io/' "$video_url" >/dev/null 2>&1
```

**Comment by supersuryaansh** [comment]
Can share your whole ani-cli code, line 211 is not the line that you mentioned also, I tried setup what you said but that did not work either.

**Comment by supersuryaansh** [comment]
This does not work either, no mp4 file is returned instead an m3u8 file is returned

**Comment by supersuryaansh** [comment]
Yes it worked, thank you

**Comment by Dink4n** [comment]
Current videos are of low quality. Previously we fetched HD videos but it's now encrypted
You can use the [old-ani-cli](https://github.com/pystardust/ani-cli/tree/old-ani-cli) branch (which seems to be working now) to get High Quality videos

**Comment by Almo7aya** [comment]
@Dink4n I'm getting HD videos with the fix I mentioned in the issue

**Comment by CoolnsX** [comment]
my fork of ani-cli is working fine and I added support for watching and downloading anime in low quality ( perfect for mobile data users)

[link](https://raw.githubusercontent.com/CoolnsX/repos_scripts/master/ani-cli)
