### ISSUE TITLE
Cannot Reach Servers

### ISSUE THREAD

**Issue by MGkillergamer007** [pystardust/ani-cli#311]
it says cannot reach servers and video playing 
![Screenshot from 2022-01-07 10-19-04](https://user-images.githubusercontent.com/81156826/148513809-7c36da92-253b-4089-a672-a7288d1e2ade.png)

it doesnt open mpv

**Comment by MGkillergamer007** [comment]
now it says video playing but it doesnt open mpv

also it says normal quality doesnt exist falling back to normal quality

**Comment by ura43** [comment]
Closing in favor of #312
