### ISSUE TITLE
Normal quality doesn't exist, falling back to normal quality

### ISSUE THREAD

**Issue by TripleK2004** [pystardust/ani-cli#312]
Issue while Downloading
```
normal quality doesn't exist, falling back to normal quality
Downloading episode 148 ...

Exception caught
Exception: [download_helper.cc:451] errorCode=1 Unrecognized URI or unsupported protocol: 

Download failed episode: 148 , please retry or check your internet connection
```

**Comment by ura43** [comment]
I have the same issue

**Comment by MGkillergamer007** [comment]
m2

**Comment by TheGlockMisc** [comment]
Yes because they implement some sort of "Invisible Captcha"

**Comment by ProgrammerJaneki** [comment]
Same issue except it's not just for download. I lowered the quality as well and still not working.

**Comment by Lawhito** [comment]
me too, and mpv wont open, i've tried change quality to low,high,normal and that doesn't work

```
Getting data for episode 1

high quality doesn't exist, falling back to normal quality


Video playing
Currently playing one-piece-3d2y-dub episode 1/1
[r] replay current episode
[a] search for another anime
[h] search history
[q] exit
Enter choice:
```

**Comment by CoolnsX** [comment]
> Yes because they implemented some sort of "Invisible ReCaptcha", in download page.. Same as VidAsia Hope this insight helps figuring out the cause of problem.

yup I am still working on it..

**Comment by CoolnsX** [comment]
> yup I already figured out the problem in the morning and still working on it..

working again.. now the script takes the sbplay link directly from episode page.. and this increased the speed of script..

**Comment by stonemonkey56** [comment]
The thing is gogoanime.cm just yoinked the download page. now the download links section on the download page is JavaScript Rendered meaning it is loaded when u open the page in a browser. Which means nor this program neither mine python version. can download episodes normally.

**Comment by ura43** [comment]
Can't confirm working again.
But retrying with `[r] replay current episode` seems to be a viable strategy for now.
I get a video to play about 50% of the time

**Comment by CoolnsX** [comment]
> would you mind explaining how you got it to work again? mine still doesn't seem to play

here's my bash -x debugging looks like

```
Getting data for episode 210
++ get_dpage_link boruto-naruto-next-generations 210
++ anime_id=boruto-naruto-next-generations
++ ep_no=210
+++ curl -s https://www3.gogoanime.cm//boruto-naruto-next-generations-210
++ anime_page='<whole page>'
++ sed -n -E 's/.*rel="13" data-video="([^"]*)".*/\1/p'
++ cut -d/ -f5
+ dpage_link=o5ylzsftdekn
++ get_video_quality o5ylzsftdekn
++ dpage_url=o5ylzsftdekn
+++ curl -s https://sbplay2.com/d/o5ylzsftdekn
+++ sed -n -E 's/.*a href="#" onclick="download_video([^"]*)".*/\1/p'
+++ head -1
++ video_links='('\''o5ylzsftdekn'\'','\''n'\'','\''9687251-160-202-1641569178-163aac640c92c50ece52fd1881817a4c'\'')'
+++ printf hi
+++ cut -c1
++ m=h
+++ printf '('\''o5ylzsftdekn'\'','\''n'\'','\''9687251-160-202-1641569178-163aac640c92c50ece52fd1881817a4c'\'')'
+++ cut '-d'\''' -f6
++ h=9687251-160-202-1641569178-163aac640c92c50ece52fd1881817a4c
+++ curl -s 'https://sbplay2.com/dl?op=download_orig&id=o5ylzsftdekn&mode=h&hash=9687251-160-202-1641569178-163aac640c92c50ece52fd1881817a4c'
+++ sed -n -E 's/<a href="([^"]*.mp4)".*/\1/p'
++ video_link=https://www113.akamai-cdn-content.com/tysxfvucl666j6cdadmr5qaehie6x4pk2hkgqhx4up2o2bi4ijre77jretfa/boruto-naruto-next-generations-episode-2101628413981.0.mp4
++ '[' -z https://www113.akamai-cdn-content.com/tysxfvucl666j6cdadmr5qaehie6x4pk2hkgqhx4up2o2bi4ijre77jretfa/boruto-naruto-next-generations-episode-2101628413981.0.mp4 ']'
++ printf %s https://www113.akamai-cdn-content.com/tysxfvucl666j6cdadmr5qaehie6x4pk2hkgqhx4up2o2bi4ijre77jretfa/boruto-naruto-next-generations-episode-2101628413981.0.mp4
+ video_url=https://www113.akamai-cdn-content.com/tysxfvucl666j6cdadmr5qaehie6x4pk2hkgqhx4up2o2bi4ijre77jretfa/boruto-naruto-next-generations-episode-2101628413981.0.mp4
+ referer_link=https://sbplay2.com
+ '[' 0 -eq 1 ']'
+ '[' 0 -eq 0 ']'
+ sed -E '
			s/^boruto-naruto-next-generations\t[0-9]+/boruto-naruto-next-generations\t211/
		' /home/tanveer/.cache/ani-hsts
+ printf '%s\n' https://www113.akamai-cdn-content.com/tysxfvucl666j6cdadmr5qaehie6x4pk2hkgqhx4up2o2bi4ijre77jretfa/boruto-naruto-next-generations-episode-2101628413981.0.mp4
https://www113.akamai-cdn-content.com/tysxfvucl666j6cdadmr5qaehie6x4pk2hkgqhx4up2o2bi4ijre77jretfa/boruto-naruto-next-generations-episode-2101628413981.0.mp4
+ kill ''
+ case $player_fn in
+ PID=153823
+ printf '\033[1;32m\nVideo playing'

Video playing+ mv /home/tanveer/.cache/ani-hsts.new /home/tanveer/.cache/ani-hsts
+ nohup mpv --http-header-fields=Referer:https://sbplay2.com https://www113.akamai-cdn-content.com/tysxfvucl666j6cdadmr5qaehie6x4pk2hkgqhx4up2o2bi4ijre77jretfa/boruto-naruto-next-generations-episode-2101628413981.0.mp4
+ episode=210
```

ofcourse I am showing edited version of bash output..

**Comment by CoolnsX** [comment]
> ofcourse I am showing edited version of bash output..

the script instead of extracting download page link from episode page link... it's extracting sbplay mirror link directly from episode page...

On every episode page, there are choose server options just below the video..
One of them is sbplay which looks like this 
```
<a href="#" rel="13" data-video="https://sbplay2.com/e/xagw6r10npvz">
            <i class="iconlayer-streamsb"></i>Streamsb<span>Choose this server</span></a>
```
the script is extracting this particular link from data-video... but we can't use this link directly....
because "https://sbplay2.com/e/ytbu13p9frce" is for embedding video..
and "https://sbplay2.com/d/ytbu13p9frce" is for downloading video...
the d and e in sbplay link outputs different page...

and what we need here is https://sbplay2.com/e/(xagw6r10npvz) <- this part only.. its the id of episode..
so the function get_dpage_link() is only giving this output -> ytbu13p9frce
now we pass the output in get_video_quality...
in which its appending in a template https://sbplay2.com/d/[ytbu13p9frce] <- this is the download link we usually get from gogoanime download page...

**Comment by ura43** [comment]
Could it be that extracting the id doesn't work reliably?
I know that whenever the "normal quality doesn't exist" pops up, the [ -z ] test is empty

**Comment by CoolnsX** [comment]
> Could it be that extracting the id doesn't work reliably? I know that whenever the "normal quality doesn't exist" pops up, the [ -z ] test is empty

no no.. in your bash debugging comment... the script was able to get the sbplay id correctly.. but after that it doesn't generate the download link in your case....

**Comment by CoolnsX** [comment]
```
+++ get_video_quality https://sbplay2.com/d/xo8vwjg5o3zh
+++ dpage_url=https://sbplay2.com/d/xo8vwjg5o3zh
++++ curl -s https://sbplay2.com/d/xo8vwjg5o3zh
++++ sed -n -E 's/.*a href="#" onclick="download_video([^"]*)".*/\1/p'
++++ head -1
+++ video_links='('\''xo8vwjg5o3zh'\'','\''n'\'','\''1855550-138-100-1641464346-9b605927c6cd9bf68993db795d9bd98a'\'')'
++++ printf normal
++++ cut -c1
+++ m=n
++++ printf '('\''xo8vwjg5o3zh'\'','\''n'\'','\''1855550-138-100-1641464346-9b605927c6cd9bf68993db795d9bd98a'\'')'
++++ cut '-d'\''' -f2
+++ i=xo8vwjg5o3zh
++++ printf '('\''xo8vwjg5o3zh'\'','\''n'\'','\''1855550-138-100-1641464346-9b605927c6cd9bf68993db795d9bd98a'\'')'
++++ cut '-d'\''' -f6
+++ h=1855550-138-100-1641464346-9b605927c6cd9bf68993db795d9bd98a
++++ curl -s 'https://sbplay2.com/dl?op=download_orig&id=xo8vwjg5o3zh&mode=n&hash=1855550-138-100-1641464346-9b605927c6cd9bf68993db795d9bd98a'
++++ sed -n -E 's/<a href="([^"]*.mp4)".*/\1/p'
+++ video_link=
+++ '[' -z '' ']'
+++ err 'normal quality doesn'\''t exist, falling back to normal quality'
+++ printf '\033[1;31m%s\033[0m\n' 'normal quality doesn'\''t exist, falling back to normal quality'
normal quality doesn't exist, falling back to normal quality
++++ curl -s 'https://sbplay2.com/dl?op=download_orig&id=xo8vwjg5o3zh&mode=n&hash=1855550-138-100-1641464346-9b605927c6cd9bf68993db795d9bd98a'
++++ sed -n -E 's/<a href="([^"]*.mp4)".*/\1/p'
+++ video_link=
+++ printf %s ''
++ video_url=
```
this is from your bash debugging comment... you can see that script on your side is trying to ping to the sbplay server after getting hash and id from sbplay2 link.. but it's unable to get it... and hence empty video url..

**Comment by ura43** [comment]
Oh, I see. I'm not sure if there is anything we can do about that

**Comment by aflyingpumpkin** [comment]
I found a horrible work around, you can use firefox in headless mode with a python script in order to bypass the captcha.

Example:
```py
from selenium import webdriver
import sys

try:
    fireFoxOptions = webdriver.FirefoxOptions()
    brower = webdriver.Firefox()

    brower.get(sys.argv[1])
    print(brower.page_source)
finally:
    try:
        brower.close()
    except:
        pass
```
```sh
MOZ_HEADLESS=true python captchasolver.py
```

**Comment by ura43** [comment]
I'm sorry but thats like having your windshield broken and instead of fixing your windshield you just hop in a tank.

While we should avoid python entirely, or switch 100% to it, its really geckodriver firefox and selenium that are very heavyweight.
I hope we find a proper fix

**Comment by aflyingpumpkin** [comment]
Yeah, that's what I guessed.

**Comment by chbo70** [comment]
i have the same issue although it seems like some episodes will still start. except i dont know what quality it is 720p or 1080p

**Comment by ura43** [comment]
Fuck sbplay, we're going back to the source.
#217

**Comment by epeuu** [comment]
After updating ani-cli, there is still "doesn't exist" error. Hope you make this work soon...
Thanks on your hard work, kings. 
Have a nice day!
