### ISSUE TITLE
Change architecture to download first and then play

### ISSUE THREAD

**Issue by ura43** [pystardust/ani-cli#313]
We currently play links directly with mpv unless downloading.
Due to heavy throttling, we recently switched to aria2 for downloads, but that doesn't work for streams because none of our dependencies ever wanted to implement support.
For streams we now scrape one of gogo's download mirrors: sbplay. But that has proven to be unreliable for some users, including myself.
From a UX standpoint, would it be reasonable to first download a whole episode and then play it?

Regarding bandwidth there are 3 cases to be aware of here:
1 Users with high bandwidth that can buffer an entire episode in seconds
2 Users with medium bandwidth that buffer faster than the playback
3 Users with low bandwidth that buffer slower than the playback

Group 1 and 3 would benefit from the change while 2 would take a hit in usability

**Comment by CoolnsX** [comment]
yup... I download every episode first and then watch it.. but the gogoanime download page got recaptcha by google.. so its not working..
I did a temporary workaround for myself.. by opening gogo's download page in browser.. manually copy the sbplay link and manually paste link in the script..
**Our first priority is to bypass google's recaptcha...**

**Comment by ura43** [comment]
We may do this as part of something else some day, but for now this doesn't seem that desireable anymore
