### ISSUE TITLE
episodes don't load

### ISSUE THREAD

**Issue by kaumidere** [pystardust/ani-cli#315]
just like before, the episode simply doesn't start. at first i thought it was because of the servers, but at least then, the episode would start eventually. now it doesn't even start at all.

**Comment by ura43** [comment]
Can you try a few times and see if you get consistent results?
also check #312

**Comment by CoolnsX** [comment]
i found a way to extract sbplay link without going to download page..

making a pr for it..

**Comment by CoolnsX** [comment]
> i found a way to extract sbplay link without going to download page..
> 
> making a pr for it..

working again.. check #312

**Comment by ura43** [comment]
Closing in favor of #312
