### ISSUE TITLE
mpv not opening

### ISSUE THREAD

**Issue by jherzstein** [pystardust/ani-cli#32]
I can search for shows just fine, but when I try to play an episode it doesn't open. When I try to download an episode the mp4 file data reads as follows:

```
<html>
<head><title>403 Forbidden</title></head>
<body bgcolor="white">
<center><h1>403 Forbidden</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

I already implemented @Almo7aya 's fix to bypass gogoanime's checks from a week ago, but this didn't change anything.

**Comment by Almo7aya** [comment]
@jherzstein
Yes it's not working even on my end, I'll check what's happening

**Comment by jherzstein** [comment]
Oh, that's great, thanks.

**Comment by Almo7aya** [comment]
@jherzstein 
They changed the `Referer` header to https://goload.one/ I'll open a PR

**Comment by Almo7aya** [comment]
@jherzstein This #33 should work

**Comment by jherzstein** [comment]
@Almo7aya Thanks for the fix!

**Comment by Almo7aya** [comment]
@jherzstein I'm sure it will break soon, we have to figure out a way to fix it permanently

**Comment by pavanbhat1999** [comment]
@Almo7aya  Ya It broke again

**Comment by Almo7aya** [comment]
@pavanbhat1999 not sure what they did I'll give it a try later

**Comment by Ananay-g** [comment]
yeah, it's not working for me. the mpv isn't opening

**Comment by YogeshLamichhane** [comment]
@pavanbhat1999 gogoanime has added [blob urls](https://stackoverflow.com/questions/30864573/what-is-a-blob-url-and-why-it-is-used#30881444) to their videos

**Comment by Dink4n** [comment]
Working now #34

**Comment by ThalesCarl** [comment]
HI guys. I don't know if it is related with this issue, but the mpv player did not lauch for me as well. Instead I got the following hexadecimal string: \x1B[2J\x1B[1;1H    followed by the next/previous/select/replay/exit menu.
