### ISSUE TITLE
vlc not found even after installing and adding path environment 

### ISSUE THREAD

**Issue by awesomec26** [pystardust/ani-cli#320]
i keep on getting an error saying "Program "vlc" not found. Please install it." when its clearly installed on my computer and its on the path environment
![image](https://user-images.githubusercontent.com/49694491/148552965-7f43f89d-0531-4955-8bb5-e7acbfae8601.png)

**Comment by zowws** [comment]
vlc is on the vlc environment. not the path environment

**Comment by awesomec26** [comment]
> vlc is on the vlc environment. not the path environment

ok, i watched a youtube tutorial on enviorment variables and the instructions were unclear so... yeah. it works now.

**Comment by awesomec26** [comment]
> > vlc is on the vlc environment. not the path environment
> 
> ok, i watched a youtube tutorial on enviorment variables and the instructions were unclear so... yeah. it works now.

ok new problem, everytime when i select an episode it plays random files on my pc instead

**Comment by ura43** [comment]
okay wtf?

We really need a dedicated maintainer just for the windows branch

**Comment by awesomec26** [comment]
> okay wtf?
> 
> We really need a dedicated maintainer just for the windows branch

yeah, im uninstalling gitbash, im going to use this program on a linux vm or something.

**Comment by CoolnsX** [comment]
> okay wtf?
> 
> We really need a dedicated maintainer just for the windows branch

okay I will start working on windows branch after my exams... so maybe after 12 jan..
and also I am thinking about ani-cli on android since most of the people using termux on android(including me).. 
and I already have ani-cli for termux on my github repos.. which is cut-down version of ani-cli.. and also has a feature of casting the link to android TV.. here is the link..
https://github.com/CoolnsX/and-scripts

**Comment by CoolnsX** [comment]
> > okay wtf?
> > We really need a dedicated maintainer just for the windows branch
> 
> yeah, im uninstalling gitbash, im going to use this program on a linux vm or something.

you can use WSL2.. it's more faster and featureful.. than setting up vm..

**Comment by AlparslanAbdikoglu** [comment]
Hi! 
Mine finds it but won't open Vlc for some reason

**Comment by reason-to-fork** [comment]
same issue, placed in path 100%, tried reinstalling everything and no luck lol. i dual boot so ill just use it on my arch partition

**Comment by awesomec26** [comment]
> > > okay wtf?
> > > We really need a dedicated maintainer just for the windows branch
> > 
> > 
> > yeah, im uninstalling gitbash, im going to use this program on a linux vm or something.
> 
> you can use WSL2.. it's more faster and featureful.. than setting up vm just for watching anime..

i have tried to install WSL2 on my PC, but because of microsofts incapability to make windows stable, everytime when i install the virtual machine engine which is required for WSL2, windows will not boot, it gives me a black screen.

**Comment by JotaroKujo0525** [comment]
installing wsl2 worked for me!

**Comment by AlparslanAbdikoglu** [comment]
> installing wsl2 worked for me!

I will try it :p

**Comment by Arctic-Circle-System** [comment]
It works in Windows Subsystem for Linux because when you install WSL you're basically installing a Linux distribution that Windows attaches to itself. ~Cherri

**Comment by ura43** [comment]
@CoolnsX any update on the windows branch?

**Comment by ura43** [comment]
accidentaly closed, sry

**Comment by ura43** [comment]
Seems like just forwardporting the crossplattform stuff, especially in the makefile, to master is the way to go
