### ISSUE TITLE
Sugestão Adcionar novos sites na lista de raspagem

### ISSUE THREAD

**Issue by KitsuneSemCalda** [pystardust/ani-cli#321]
Em alguma nova versão, o script ani-cli poderia raspar sites como animefire animesorion ou superanimes

**Comment by CoolnsX** [comment]
podemos, mas isso tornará o script mais complexo como escrever um script inteiro para cada site do zero....

traduzido pelo Google

**Comment by KitsuneSemCalda** [comment]
porque não usar uma lista de sites que buscaria pelo mirror mais rapido

**Comment by CoolnsX** [comment]
mirrors também requer... que o site mirror seja descartado... Igual ao caso acima... requerendo cada script para cada site...
atualmente estamos raspando um dos espelhos do gogoanime "sbplay" pois a página de download do gogoanime foi recaptcha ..

**Comment by KitsuneSemCalda** [comment]
você poderia evitar a raspagem capturando o tempo do ping das página, ou criando um pequeno daemon que verificaria a cada x minutos, e gerasse um file cache com o url mais rapido dentre as opções ...

**Comment by ura43** [comment]
@CoolnsX was this thing completed
