### ISSUE TITLE
After gathering data for an episode VLC launches but closes right after

### ISSUE THREAD

**Issue by Chiroyasumi** [pystardust/ani-cli#323]
Everything works seamlessly until showing the episode. I use windows and VLC, there is a video attached

https://user-images.githubusercontent.com/51413351/148646919-7e6b0d15-2d48-4103-9de9-3a9585456897.mp4

**Comment by JRCdev** [comment]
Seems to be an issue with getting the video_url from dpage_link

**Comment by ura43** [comment]
As JRCdev said, this might just be vlcs symptoms of #312

**Comment by Chiroyasumi** [comment]
> As JRCdev said, this might just be vlcs symptoms of #312

Ooh okay, sorry for the duplicate then

**Comment by ura43** [comment]
No worries. Keep an eye out for a fix, it might take a few days this time
