### ISSUE TITLE
quality defaults to lowest

### ISSUE THREAD

**Issue by D0nnieD4rk0** [pystardust/ani-cli#324]
damn this script has gotten so trash

**Comment by ura43** [comment]
Blame gogoanime. Webscraping is an armsrace between developers and the website provider and in the past week, gogo seems to be doing its homework, making our life hard

**Comment by ura43** [comment]
Also, it currently defaults to "normal" as defined by sbplay.
That's because many anime only have a "normal" quality option.
If you prefer having high quality by default, set an alias: `alias ani-cli='ani-cli -q high'`

**Comment by D0nnieD4rk0** [comment]
yeah i was in kind of a bad mood im sorry
although still on high it only does 720p

**Comment by Duoslow** [comment]
> damn this script has gotten so trash

damn then write it yourself from scratch 🥴

**Comment by ura43** [comment]
> > damn this script has gotten so trash
> 
> damn then write it yourself from scratch woozy_face

Actually, please don't :joy:

**Comment by leaf-ts** [comment]
is there a workaround for this issue?
I do set -q high but it falls back to normal

**Comment by ura43** [comment]
There is cryptography and there is hope, but I'm afraid there is no short term workaround I can provide you with

**Comment by leaf-ts** [comment]
> There is cryptography and there is hope, but I'm afraid there is no short term workaround I can provide you with

hehehe, no worries just checking. ani-cli was a god send app, so I have hopes you guys will figure out something :-)

**Comment by ura43** [comment]
I'm sure we will
