### ISSUE TITLE
No sound for some reason

### ISSUE THREAD

**Issue by awesomec26** [pystardust/ani-cli#325]
everytime when i run this as a normal user it says /usr/local/bin/ani-cli: 159: cannot create /home/charl/.cache/ani-hsts: Permission denied but when i run it as sudo there is no sound

**Comment by ura43** [comment]
It's expected behavior that you can't create that as a normal user.
Could you expand on what you mean with no sound?

**Comment by awesomec26** [comment]
> It's expected behavior that you can't create that as a normal user. Could you expand on what you mean with no sound?

I literally mean, the video plays, but there is no sound. I even checked all the volume settings, but no sound.

**Comment by ura43** [comment]
Can you reproduce that with another anime? What anime was this? Also, what OS are you on?

**Comment by ura43** [comment]
Closing, as this is stale. Please reopen if you choose to provide further context
