### ISSUE TITLE
Mac version not Working

### ISSUE THREAD

**Issue by Eeman1113** [pystardust/ani-cli#331]
/usr/local/bin/ani-cli: line 159: /Users/eemanmajumder/.cache/ani-hsts: No such file or directory
 this bus the error

**Comment by 0x8FF** [comment]
Are you on Apple Silicon?

**Comment by ura43** [comment]
Because if you are on Apple Silicon, this duplicates #123 
Please tell us your platform

**Comment by ura43** [comment]
Closing under the assumption that you are on the M1 mac. 
Please reopen if this is incorrect

**Comment by Tractor0** [comment]
How to fix pls

**Comment by Eeman1113** [comment]
Yes I am sorry I was inactive yes i have a M1 Mac

**Comment by Eeman1113** [comment]
Could you please sum up what I have to do to fix it i read the duplicate it was too scattered information to understand

**Comment by 0x8FF** [comment]
change the makefile so that it installs on /opt
```make
PREFIX := /opt

#install by default
all: install

install:
	# copies ani-cli file to /opt/ani-cli, which should be in path
	cp ani-cli $(DESTDIR)$(PREFIX)/ani-cli
	# marks ani-cli executable
	chmod 0755 $(DESTDIR)$(PREFIX)/ani-cli

uninstall:
	rm -rf $(DESTDIR)$(PREFIX)/ani-cli

.PHONY: all install uninstall
```
