### ISSUE TITLE
Android version not working

### ISSUE THREAD

**Issue by Fmert24** [pystardust/ani-cli#332]
Getting data for episode 1
360 quality doesn't exist, falling back to normal quality
Downloading episode 1 ...

Exception caught
Exception: [/home/builder/.termux-build/aria2/src/src/download_helper.cc:451] errorCode=1 Unrecognized URI or unsupported protocol:
 
Im using termux so
Home folder at /data/data/com.termux/files/home
And bin folder at /data/data/com.termux/files/home/bin
Or data/data/com.termux/files/usr/bin
So for exeption to be valid i must root my phone

I get this error because of wrong path?
Then how can ı change path folder of this error? So it will be fixed?
Or some thing else?
Because ı downloaded 20 episode of sword art online till gtc+3  ~17:00...

**Comment by CoolnsX** [comment]
did you read the README properly.. now its -q (low | normal | high) or ( lo | norm | hi)...
by default it selects the normal.. there is no resolution option.. only these three.. 
because gogoanime put google captcha on their downloading site.. so script is currently scraping gogoanime download mirror

And for minimalistic ani-cli without any features ( no quality selection, no history file, or any new feature).. go to this link
only downloading and casting and streaming is the feature...  

https://github.com/CoolnsX/and-scripts/blob/main/ani-cli

**Comment by Fmert24** [comment]
> did you read the README properly.. now its -q (low | normal | high) or ( lo | norm | hi)... by default it selects the normal.. there is no resolution option.. only these three.. because gogoanime put google captcha on their downloading site.. so script is currently scraping gogoanime's download mirror (streamsb server)
> 
> And for minimalistic ani-cli without any features ( no quality selection, no history file, or any new feature).. go to this link only downloading and casting and streaming is the feature...
> 
> casting requires python module (catt) installed... and downloading requries aria... and sending links to external applications requires both termux-api (as an app and command) install in your phone
> 
> https://github.com/CoolnsX/and-scripts/blob/main/ani-cli

u0_a3160@localhost ~/bin> ani-cli -d sword-art-online-alicization

Getting data for episode 15
normal quality doesn't exist, falling back to normal quality
Downloading episode 15 ...

Exception caught
Exception: [/home/builder/.termux-build/aria2/src/src/download_helper.cc:451] errorCode=1 Unrecognized URI or unsupported protocol:

Download failed episode: 015 , please retry or check your internet connection

Currently playing sword-art-online-alicization episode 15/24
[n] next episode
[p] previous episode
[s] select episode
[r] replay current episode
[a] search for another anime                                                                         [h] search history
[q] exit

And this is the minimalistic script

u0_a3160@localhost ~/bin> ani-clii -d sword-art-online-alicization
[1] sword-art-online-alicization
[2] sword-art-online-alicization-dub
[3] sword-art-online-alicization-war-of-underworld
[4] sword-art-online-alicization-war-of-underworld-dub
[5] sword-art-online-alicization-war-of-underworld-2nd-season
[6] sword-art-online-alicization-war-of-underworld-2nd-season-dub
Enter number: 1
Range of episodes can be specified: start_number end_number
Choose episode [1-24]: 15

Getting data for episode 15


Downloading episode: 15 ...
Exception caught
Exception: [/home/builder/.termux-build/aria2/src/src/download_helper.cc:451] errorCode=1 Unrecognized URI or unsupported protocol:

Download failed episode: 015

**Comment by CoolnsX** [comment]
yup.. checked right now.. they put google recaptcha on gogoanime's mirror links(sbstream)...

so it's showing that..

**Comment by Fmert24** [comment]
Well this problem will be fixed next week maybe sooner maybe later
