### ISSUE TITLE
ani-cli stopped working overnight after a system upgrade ?

### ISSUE THREAD

**Issue by evanescente-ondine** [pystardust/ani-cli#333]
Hi.
I'm on endeavoros.
I installed ani-cli yesterday from the AUR repository (git version: aur/ani-cli-git r251.75409cc-6 (+16 4.77) (Installé : r273.37de427-1) so I think the same as on here), and it worked well.
I try today, after an update and reboot: the same exact anime don't work anymore. It always says: normal quality doesn't exist, falling back to normal quality; Video playing" yet nothing plays, neither in mpv or vlc with the -v option.
I use sway, foot and fish, but it's been the case yesterday too

**Comment by raiden076** [comment]
Exactly same problem for me too, nothing is helping..

**Comment by CoolnsX** [comment]
now they put google recaptcha on gogoganime's mirror(streamsb) from which we are scraping anime currently... 

so gogoanime is doing some work there..

**Comment by evanescente-ondine** [comment]
Huh, over the night. Lucky me!!

**Comment by RonFusaishi** [comment]
> now they put google recaptcha on gogoganime's mirror(streamsb) from which we are scraping anime currently...

oh no bros, how will this script recover?

**Comment by minecraftfromsans** [comment]
must've been me bulk downloading animes I'll never finish (or start!)

**Comment by CoolnsX** [comment]
1. animekaizoku.com (packs every anime season in a zip file and stores it on Google drive like anime_name_season_1.zip)
2. anidl.org (same as animekaizoku but stores all the file on Mega drive)
3. subsplease.org (gives latest anime episodes using torrent, but has limited database, best horriblesubs alternative)
4. nyaa.si (best anime website ever, using torrent to store anime, has every anime in its database even NSFW anime..)

**Comment by RaynardGerraldo** [comment]
> 1. [animekaizoku.com](https://animekaizoku.com) (packs every anime season in a zip file and stores it on Google drive like anime_name_season_1.zip, good site and less redirects..)
> 2. [anidl.org](https://anidl.org) (same as animekaizoku but stores all the file on Mega drive, good site but lots of redirects..)
> 3. [subsplease.org](https://subsplease.org) (gives latest anime episodes using torrent, but has limited database, best horriblesubs alternative, no redirects)
> 4. [nyaa.si ](https://nyaa.si)(best anime website ever, using torrent to store anime, has every anime in its database even NSFW anime..)
> 
> Note :- use vpn if any of these site is blocked in your region... it's worth checking...

Can any of these websites be used as a replacement for gogoanime?

**Comment by TheGlockMisc** [comment]
> > 1. [animekaizoku.com](https://animekaizoku.com) (packs every anime season in a zip file and stores it on Google drive like anime_name_season_1.zip, good site and less redirects..)
> > 2. [anidl.org](https://anidl.org) (same as animekaizoku but stores all the file on Mega drive, good site but lots of redirects..)
> > 3. [subsplease.org](https://subsplease.org) (gives latest anime episodes using torrent, but has limited database, best horriblesubs alternative, no redirects)
> > 4. [nyaa.si ](https://nyaa.si)(best anime website ever, using torrent to store anime, has every anime in its database even NSFW anime..)
> > 
> > Note :- use vpn if any of these site is blocked in your region... it's worth checking...
> 
> Can any of these websites be used as a replacement for gogoanime?

I prefer kickassanime..
It has Google Server too also its so easy to scrape because the stream links are exposed.

**Comment by Soviena** [comment]
> I prefer [kickassanime](https://www2.kickassanime.ro).. It has Google Server too also its so easy to scrape because the stream links are exposed.

Yes, kickassanime is quite easy to scrap. im currently making a scraper for it in python [kaa.si-cli](https://github.com/Soviena/kaa.si-cli)

**Comment by ura43** [comment]
> > now they put google recaptcha on gogoganime's mirror(streamsb) from which we are scraping anime currently...
> 
> oh no bros, how will this script recover?

There is a pinned issue with a solution that just needs to get integrated

**Comment by ura43** [comment]
Closing in favor of #217
