### ISSUE TITLE
Some episodes open, some not

### ISSUE THREAD

**Issue by epeuu** [pystardust/ani-cli#339]
I tried to open some older episodes of anime "Detective Conan" and they doesn't open in media player.
Some open, some not.
We get a link which work if you open via browser, but the problem is that media player doesn't play and media.

Here is a video:
https://user-images.githubusercontent.com/86723533/149586945-f8d8fff3-71f5-4aac-a2e0-2b045886918d.mp4

I tried to open episode 1 of Detective Conan, and that one doesn't open via media player, but I tried and open link I got of a episode and open it via browser, and link works fine.
Picture: ![Screenshot from 2022-01-14 22-26-36](https://user-images.githubusercontent.com/86723533/149587670-2867d681-18a9-457e-9b60-1cd3f91e6b45.png)

**Comment by galloway** [comment]
@CoolnsX  https://github.com/pystardust/ani-cli/blob/42a5f636ce61a96e7c3869e2f4f4f11c7fe8aa52/ani-cli#L138  probably isn't supposed to have the time as 69  420 69 1337 8008135 (BOOBIES on a calculator)...

**Comment by kaumidere** [comment]
1. cd ani-cli
2. sudo rm -f /usr/local/bin/ani-cli
3. sudo make 
4. chmod +x ani-cli

it should work from here on
