### ISSUE TITLE
Cannot download episodes

### ISSUE THREAD

**Issue by Yeashu** [pystardust/ani-cli#342]
I am not able to download episode 
Screenshot below:-
![Screenshot_2022-01-15-01-05-06_1920x1080](https://user-images.githubusercontent.com/67820770/149613840-7cd22dec-a315-4628-a3a5-20ce9d4ba718.png)

**Comment by Yeashu** [comment]
I am able to download by using  curl instead of aria2c
![Screenshot_2022-01-15-01-14-30_1920x1080](https://user-images.githubusercontent.com/67820770/149614081-3c7c00cf-a2fd-477f-9340-4006604ca334.png)

**Comment by ura43** [comment]
Can't reproduce. Downloads fine with aria2 using the same anime, same episode

**Comment by Fmert24** [comment]
![Screenshot_20220115-130926_Termux](https://user-images.githubusercontent.com/89682488/149618034-bebdb924-8df0-46dd-9dc2-65105f90ee19.jpg)
I am not able to download  episode

**Comment by TripleK2004** [comment]
```
Getting data for episode 290
normal quality doesn't exist, falling back to normal quality
Downloading episode 290 ...

Exception caught
Exception: [download_helper.cc:451] errorCode=1 Unrecognized URI or unsupported protocol: 

Download failed episode: 290 , please retry or check your internet connection
```
Im getting something like this

**Comment by CoolnsX** [comment]
> ```
> Getting data for episode 290
> normal quality doesn't exist, falling back to normal quality
> Downloading episode 290 ...
> 
> Exception caught
> Exception: [download_helper.cc:451] errorCode=1 Unrecognized URI or unsupported protocol: 
> 
> Download failed episode: 290 , please retry or check your internet connection
> ```
> 
> Im getting something like this

update your ani-cli version
`sudo ani-cli -U`

**Comment by CoolnsX** [comment]
> ![Screenshot_20220115-130926_Termux](https://user-images.githubusercontent.com/89682488/149618034-bebdb924-8df0-46dd-9dc2-65105f90ee19.jpg) I am not able to download episode

Install openssl on termux
apt install openssl-tool

**Comment by ura43** [comment]
The initial issue seems to have been aria2 failing to reach vidstreamingcdn.com while curl did reach it shortly after. Since I couldn't reproduce the issue I'll assume a second of DNS downtime struck at a bad moment.
If the problem persists, or anyone else can reproduce the issue please reopen.
If the issue is not related to not reaching vidstreamingcdn.com open another issue
