### ISSUE TITLE
Cannot play episode

### ISSUE THREAD

**Issue by KouranliKe** [pystardust/ani-cli#343]
The script will just return me this error message when trying to play an episode (tried it with 3 different animes and it just sends me the same message). I use Fedora 35.

`Getting data for episode 1
/usr/local/bin/ani-cli: line 135: openssl: command not found
parse error: Invalid numeric literal at line 1, column 5
https://gogoplay.io/embedplus?id=MjI0NjU=&token=OQXxZUxqFX9Lj8y5ayq6Uw&expires=1642246526

Video URL not found
`

**Comment by Fmert24** [comment]
> The script will just return me this error message when trying to play an episode (tried it with 3 different animes and it just sends me the same message). I use Fedora 35.
> 
> `Getting data for episode 1 /usr/local/bin/ani-cli: line 135: openssl: command not found parse error: Invalid numeric literal at line 1, column 5 https://gogoplay.io/embedplus?id=MjI0NjU=&token=OQXxZUxqFX9Lj8y5ayq6Uw&expires=1642246526
> 
> Video URL not found `

Im getting same error

![Screenshot_20220115-130926_Termux](https://user-images.githubusercontent.com/89682488/149620346-4490522d-fb11-4797-bea8-af14c74ebe03.jpg)

**Comment by kaumidere** [comment]
is this a pine phone or something? how are you watch this on a mobile?

**Comment by Fmert24** [comment]
> is this a pine phone or something? how are you watch this on a mobile?

Its not pine phone its Termux a terminal emulator (you can download from f-droid(as they advice)) i can only download because termux creates problem about watching and im to lazy to fix them

**Comment by kaumidere** [comment]
I have termux as well but it still doesn’t seem to
Work on my end… Then again I was using an alternative to ani-cli (anime_cli). I’ll give it a go and see what I can do.

**Comment by kaumidere** [comment]
if you could run me through how you got that on your phone perhaps i can get it to work... i use grapheneos

**Comment by TheGlockMisc** [comment]
> The script will just return me this error message when trying to play an episode (tried it with 3 different animes and it just sends me the same message). I use Fedora 35.
> 
> `Getting data for episode 1 /usr/local/bin/ani-cli: line 135: openssl: command not found parse error: Invalid numeric literal at line 1, column 5 https://gogoplay.io/embedplus?id=MjI0NjU=&token=OQXxZUxqFX9Lj8y5ayq6Uw&expires=1642246526
> 
> Video URL not found `

You need to install OPENSSL first probably they forgot to add OpenSSL as essential dependencies
```
sudo dnf install openssl
```

**Comment by Fmert24** [comment]
> if you could run me through how you got that on your phone perhaps i can get it to work... i use grapheneos

You need to change make file contents(prefix pointing root section but whit this its pointing termux home bin) to this



PREFIX := /data/data/com.termux/files/home

all: install

install:
        cp ani-cli $(DESTDIR)$(PREFIX)/bin/ani-cli
        chmod 0755 $(DESTDIR)$(PREFIX)/bin/ani-cli

uninstall:
        $(RM) $(DESTDIR)$(PREFIX)/bin/ani-cli

.PHONY: all install uninstall

**Comment by Fmert24** [comment]
> > The script will just return me this error message when trying to play an episode (tried it with 3 different animes and it just sends me the same message). I use Fedora 35.
> > `Getting data for episode 1 /usr/local/bin/ani-cli: line 135: openssl: command not found parse error: Invalid numeric literal at line 1, column 5 https://gogoplay.io/embedplus?id=MjI0NjU=&token=OQXxZUxqFX9Lj8y5ayq6Uw&expires=1642246526
> > Video URL not found `
> 
> You need to install OPENSSL first probably they forgot to add OpenSSL in checking dependencies
> 
> ```
> sudo dnf install openssl
> ```

Thank you sir

**Comment by kaumidere** [comment]
Are these the commands to input into termux?

Still sorta new to this.

**Comment by CoolnsX** [comment]
> > is this a pine phone or something? how are you watch this on a mobile?
> 
> Its not pine phone its Termux a terminal emulator (you can download from f-droid(as they advice)) i can only download anime because termux creates problem about watching and im to lazy to fix them

That is the reason I am not creating termux (android) branch.. I only use termux for downloading anime.. because the majority of audience only streams anime.. not download them..

**Comment by ura43** [comment]
Anyway, added it as an explicit dependency and added it to the dependency check

**Comment by kaumidere** [comment]
if someone can run me through the commands to add this so i can download anime on my phone that'll be neat
