### ISSUE TITLE
Video URL not found

### ISSUE THREAD

**Issue by Rukfa** [pystardust/ani-cli#345]
Every time i try to watch en episode this message shows up and i don't know how to fix it. Can someone help me

![image](https://user-images.githubusercontent.com/97807427/149636355-cf2aed1f-37e7-4500-bb70-e13942d4bf45.png)

**Comment by yathy2007** [comment]
@Rukfa did you pull the latest changes and compiled the scripts again?

**Comment by TimInLasVegas** [comment]
For some reason, sometimes ani-cli won't give you an error that you are missing a dependency and it causes a break. Please check if you have jq openssl git and other dependencies and try again.

Also run "sudo ani-cli -U" to update ani-cli first.

Dependency Install commands:
Debian/Ubuntu: "sudo apt update; sudo apt -y install jq openssl git sed jq curl grep aria2"
Fedora/Rocky: "sudo dnf install jq openssl git sed curl grep aria2"
Arch: "sudo paman -S jq openssl git sed curl grep aria2"
etc...

**Comment by ura43** [comment]
> For some reason, sometimes ani-cli won't give you an error that you are missing a dependency and it causes a break. Please check if you have jq openssl git and other dependencies and try again.
> 
> Also run "sudo ani-cli -U" to update ani-cli first.
> 
> Dependency Install commands: Debian/Ubuntu: "sudo apt update; sudo apt -y install jq openssl git sed jq curl grep aria2" Fedora/Rocky: "sudo dnf install jq openssl git sed curl grep aria2" Arch: "sudo paman -S jq openssl git sed curl grep aria2" etc...

That shouldn't happen :sweat_smile: 
git is no longer a dependency and the readme should be up to date on nescessary and optional dependencies.
You should be able to use ani-cli without a video player if you just download, or without aria2 if you just stream

**Comment by ura43** [comment]
I'm assuming this is resolved. Please reopen if you need further assistance
