### ISSUE TITLE
Cannot download episodes, please help.

### ISSUE THREAD

**Issue by nerdawitz** [pystardust/ani-cli#350]
When I put in this command "ani-cli -p /mnt/Other/Detective_Conan detective-conan", it works as intended and proceeds to show me options, and then leads to entering the episodes to download, I enter the episodes I want, and it works fine there as well, but when it says that it's getting data, it displays this message:
"normal quality doesn't exist, falling back to normal quality"
and after that, moves on to the next episode and does the same and doesn't download anything. It makes the directory at the specified path so that's working fine. For some reason, it is not getting the data to download it I guess? any suggestions on how to fix it? Thank you.

**Comment by ura43** [comment]
This should be fixed in the latest version, could you pull the latest version?

**Comment by ura43** [comment]
Since your error message was the primary symptom of a recent-ish bug, I'll assume that updating fixed your problem.
Please reopen if this wasn't the case
