### ISSUE TITLE
Exception: episode URL parse error if empty string is used after nonexistend/not aired episode

### ISSUE THREAD

**Issue by ejkozan** [pystardust/ani-cli#351]
Something found by chance.
After trying to play not aired yet episode (or putting number out of range) and then just hitting enter, this is spit out (tested on 40 episode of Shaman king 2021 and on episode of FLCL dub:

```
Episode out of range
Choose episode [1-39]:
/home/ejkozan/bin/ani-cli: 304: [: Illegal number:
/home/ejkozan/bin/ani-cli: 304: [: Illegal number:
Getting data for episode
parse error: Invalid numeric literal at line 1, column 5


Video URL not found
```
Probably just some special edge case.
As always dash is used as POSIX shell

**Comment by ura43** [comment]
It says Episode out of range, isn't this expected behaviour?

**Comment by ejkozan** [comment]
Yes, but I meant second part when script crashes after showing errors. I know this is very special case and I found it only because I was too fast with pressing enter.
