### ISSUE TITLE
[FEATURE REQUEST] Kodi / LibreElec port

### ISSUE THREAD

**Issue by JVGA8837** [pystardust/ani-cli#355]
It would be more convenient to have ani-cli ported to Kodi as an add-on so you could just type it in and watch it there.

**Comment by ura43** [comment]
This would be a good idea for a thirdparty fork

**Comment by ura43** [comment]
But yeah, this is vastly out of scope. 
Consider porting it yourself if Kodis add-on system is documented well enough
