### ISSUE TITLE
usage of -i on mac is broken

### ISSUE THREAD

**Issue by iamchokerman** [pystardust/ani-cli#357]
here's an overview of the inconsistency of the -i argument:

1. "ani-cli -i"  
will simply not work

2. "ani-cli -i naruto" 
will prompt "Search Anime:" without looking up naruto already, as it would if you do "ani-cli naruto", basically it does what "ani-cli -i" should, and it then opens up in iina and works properly

3. "ani-cli -i -k"  
also does what "ani-cli -i" should, and it then opens up in iina and works properly

Here's a screenshot:

<img width="992" alt="issueiina" src="https://user-images.githubusercontent.com/44473782/150108905-08f58cad-3303-4da4-bbd0-65a2ebf28984.png">

**Comment by tennyson-mccalla** [comment]
@iamchokerman what happened with this?

**Comment by iamchokerman** [comment]
> @iamchokerman what happened with this?
@ura43 fixed it, so it's working properly now

**Comment by DaBantableGamer** [comment]
Hi, I'm still having this problem on an M1 MacBook Air where the '-I' argument doesn't work but instead outputs '/usr/local/bin/ani-cli: illegal option -- i' followed by the help text. 

It seems to do this with any combination after the '-i' argument unlike in the original screenshots by @iamchokerman (e.g. ani-cli -i-k outputs illegal argument and the same with ani-cli -i [anime name]).

**Comment by 0x8FF** [comment]
Have you updated the script? Update it by running ``ani-cli -U`` and try again maybe

**Comment by DaBantableGamer** [comment]
Hi, yeah just updated and that works now haha, but now I'm getting the grep: invalid repetition counts error which I know is already being looked at. Thanks and sorry for the inconvenience.
