### ISSUE TITLE
gogoanime.vc blocked in India?

### ISSUE THREAD

**Issue by Dink4n** [pystardust/ani-cli#36]
I was unable access gogoanime.vc. Anybody else facing this issue?

**Comment by Venkad000** [comment]
The Website has been blocked as per the Order of Ministry of Electronics and Information Technology under IT Act, 2000.
Use a vpn or something

**Comment by SteveGremory** [comment]
Yeah about that, gogoanime.pe is working so i guess we should just have a file with "mirrors", perhaps?
So that if one fails, the other is used automatically. Might make a PR.

**Comment by 64-Tesseract** [comment]
> 
> 
> Yeah about that, gogoanime.pe is working so i guess we should just have a file with "mirrors", perhaps? So that if one fails, the other is used automatically. Might make a PR.

It's blecked where I am too. I spent half an hour trying to get a proxy working with `curl`... and then you come along with a mirror that works XD

**Comment by DannyParker0001** [comment]
`sudo vim /etc/resolv.conf `
add a
`nameserver 8.8.8.8`
just werks

**Comment by ExistingProgrammer** [comment]
Here is how to fix it:
1. Edit the shell script.
2. Find and Replace gogoanime.vc with gogoanime.pe everywhere. Works flawlessly after this

**Comment by prirai** [comment]
I'm in India and gogoanime.vc works here. 
Could you provide some details?

**Comment by prorounak2005** [comment]
> Yeah about that, gogoanime.pe is working so i guess we should just have a file with "mirrors", perhaps? So that if one fails, the other is used automatically. Might make a PR.

I am in gogoanime discord server and this are the domain they have 
![unknown](https://user-images.githubusercontent.com/69617708/137585296-e957b44f-d845-4f99-8f8a-84670f5798f9.png)

**Comment by prorounak2005** [comment]
Green are the working domains. Yellow are the redirecting ones and red are dead ones. And gogoanime changes their domain continuosly because Indian government blocks the website thats why. If u want more information u can visit gogoanime discord server- https://discord.com/invite/XMGaBCm

**Comment by thexavier666** [comment]
Works fine in India, provided you are using 3rd party DNS service instead of your ISP's DNS service. I'm using Cloudflare DNS over DoH.
