### ISSUE TITLE
Search is not working when using -p flag

### ISSUE THREAD

**Issue by Yeashu** [pystardust/ani-cli#363]
![Screenshot_2022-01-20-07-39-54_1920x1080](https://user-images.githubusercontent.com/67820770/150254525-a83edbd4-5fde-4b86-99ad-b4775d0eb132.png)

**Comment by Yeashu** [comment]
After last 2 merge i started having this issue

**Comment by ura43** [comment]
![cantreproduce](https://user-images.githubusercontent.com/82055622/150286862-5c9d058a-db84-461b-92f2-5c78a8683602.png)

Can't reproduce

**Comment by ura43** [comment]
Maybe the edgecase will be fixed when I merge -d and -p

**Comment by ura43** [comment]
Please reopen if you can provide me with more context

**Comment by Yeashu** [comment]
This issue was fixed  after the last merge.
Thank You
