### ISSUE TITLE
Cannot choose episode which is 0-numbered

### ISSUE THREAD

**Issue by JungerBoyo** [pystardust/ani-cli#369]
Hello, I tried to watch Re:Zero anime (1st season), on gogoanime. The very first episode is 0. The allowed range to choose anime episode from is from 1 to x, so simply it is not possible to watch the 0 episode.

**Comment by ura43** [comment]
Did you try `h0`?
I assume you're running the latest, or a recent version on linux

**Comment by JungerBoyo** [comment]
Yes, ubuntu 20.04, the newest version of ani-cli. I do not know what you mean by `h0`. I tried to type it as an episode number but it throws an error.

**Comment by ura43** [comment]
Yeah thats what I meant

**Comment by ura43** [comment]
rezero-kara-hajimeru-isekai-seikatsu?
https://anilist.co/anime/21355/ReZero-Kara-Hajimeru-Isekai-Seikatsu/
Should be ep 1-25, right?

**Comment by JungerBoyo** [comment]
Yes

**Comment by StrawberryMahjong** [comment]
I was just about to write an issue about this, good thing someone else found this, hope it gets fixed soon.
