### ISSUE TITLE
App crashes when choosing invalid option in main episode view

### ISSUE THREAD

**Issue by YairZiv5951** [pystardust/ani-cli#377]
I'm using 2 languages on my keyboard, sometimes I don't notice and write in the main language I use.
If possible, can you make it so that in the switch case statement at the end of the file, when choosing something outside of the available choices it print the error "invalid token" but not kill the app? Just let you choose another?

Thanks!

**Comment by CoolnsX** [comment]
It's possible.. but line of code will increase..

**Comment by 71zenith** [comment]
That would be a long rewrite tho

**Comment by ura43** [comment]
Fixed in #384 
Was literally a 2 line addition btw
