### ISSUE TITLE
Request for a new branch

### ISSUE THREAD

**Issue by 71zenith** [pystardust/ani-cli#379]
Since the main script has to be run in multiple OSes, the dependencies are made tight. So a lot of features aren't included in it.
I feel like there should be a seperate branch which has extra features at the cost of portability. Like support for external launchers.
**TLDR**
BLOAT

**Comment by 0x8FF** [comment]
Imo it’s annoying maintaining multiple branches

**Comment by ura43** [comment]
We should have less branches, not more. Maintaining separate branches is annoying af

**Comment by 71zenith** [comment]
I get it. Its a huge pa in to split time into working in multiple branches. However may I know why legacy ani-cli and trinity is maintained. I don't know what trinity is meant to do. Others has self-explanatory names

**Comment by ura43** [comment]
They both aren't.
I have no idea why old-ani-cli is still there, but wouldn't want to delete it myself.
Trinity is a feature branch where I fiddle with the makefile to unite master, windows-vlc, and android-termux

**Comment by 71zenith** [comment]
Trinity then should be renamed to feature or experimental or something. Or just put a comment in the script to tell what it does. Closing this issue
