### ISSUE TITLE
Downloaded videos not working

### ISSUE THREAD

**Issue by Galm007** [pystardust/ani-cli#38]
When I download anime episodes using `ani-cli -d <query>` it actually downloads the episodes but when I try to open them, it doesn't work. It says "text/html decoder is required to play the file, but is not installed". Is there a missing dependency that I have to install?

![0](https://user-images.githubusercontent.com/63294460/137567555-9c9576a5-fe7f-4bab-84d6-b87a2236588a.png)

edit: I use Ubuntu 20.04 LTS. When I tried opening one of the downloaded episodes using a text editor, I got this:
![1](https://user-images.githubusercontent.com/63294460/137567929-189dd421-be52-4bcc-b05f-f1d9df8eb22c.png)

**Comment by ctv99** [comment]
How do we download 720p or 1080p

**Comment by ctv99** [comment]
got it had to set on site then its working correct

**Comment by Nyaaboron** [comment]
make sure that the lines 218 - 224 look like this:
![0](https://user-images.githubusercontent.com/63294460/138006562-29c5f513-815e-4f48-b7f6-a081b41ba934.png)

**Comment by Abhiwa6** [comment]
nothing is working now.
