### ISSUE TITLE
Issue with Mac: MPV not found 

### ISSUE THREAD

**Issue by ThamognyaKodi** [pystardust/ani-cli#382]
I currently tested this program on a mac and got this error message. I have mpv installed on my system but I still get this error message: `Program "mpv" not found. Please install it.` when I execute the command. I never got this error on a Linux build.

**Comment by iamchokerman** [comment]
i think reinstalling mpv with homebrew fixed the issue for me. also you can use iina, which is also a great player (only for mac)

**Comment by ThamognyaKodi** [comment]
Thank you for the suggestion. Mpv is now working as a cli instead of an application so `ani-cli` is working.
