### ISSUE TITLE
[enhancement] choose another provider

### ISSUE THREAD

**Issue by realitymolder** [pystardust/ani-cli#383]
An option to choose another provider for example 9anime.to

**Comment by ura43** [comment]
I'm highly in favor of nyaa.si and a torrent mode

**Comment by WizSaint** [comment]
Yeah nyaa.si torrent mode would be great. I recall there is a GitHub project that let's you stream torrent and magnet links in vlc. 
https://github.com/johang/vlc-bittorrent

**Comment by Albnu14** [comment]
Please don't especialy not 9anime (it seems to break easily from what other projects concluded) , i know it is appealing but all the other projects which add +10 providers end up not following whatever updates the site has which breaks everything, only to abandon the provider and search for another one with worse quality,

Concentrating on one or two providers so they don't break easily should be the priority which was what i liked about this project (gogoanime is good)

**Comment by ura43** [comment]
> Please don't especialy not 9anime (it seems to break easily from what other projects concluded) , i know it is appealing but all the other projects which add +10 providers end up not following whatever updates the site has which breaks everything, only to abandon the provider and search for another one with worse quality,
> 
> Concentrating on one or two providers so they don't break easily should be the priority which was what i liked about this project (gogoanime is good)

I fully agree. Another provider makes sense, but any additional provider better have very real benifits *and* be easy to scrape

**Comment by ura43** [comment]
I'll just dump some relevant context pieces here
[aria2 torrent docs](https://aria2.github.io/manual/en/html/README.html#bittorrent)
[notflix](https://github.com/Bugswriter/notflix)
[nyon-stream](https://github.com/Nixuge/nyon-stream)
[seadex-api](https://github.com/DhanrajHira/seadex_api)
Predictable Streaming Issue: [aria2 #911](https://github.com/aria2/aria2/issues/911)

**Comment by ura43** [comment]
If aria2 #911 would get fixed, that plus `mktemp` plus `nohup` or `&` would enable true streaming

**Comment by freezboltz** [comment]
> I'm highly in favor of nyaa.si and a torrent mode
can be implemented 
1. search-query
2. curl -s nyaa.si
3. some logic
4. fetch top 10 torrent with high seed matching search_query and grab magnet
5. user inputs
6. play with peerflix npm package (this is external dependency we need)

**Comment by ura43** [comment]
This should be a separate project.
If we consider how challenging ani-cli is to maintain as is, I don't think it makes sense to baloon the code with like 200 more lines, while also including more dependencies.

Some day our gogo scraping may break.
When that happens we have no choice but to fix the scraping or change providers, since you won't be able to test any unrelated changes.
Let's work on fixes and code quality while we can. Scraping won't always be this easy.

**Comment by port19x** [comment]
With the 3 key changes in the past 24 hours I'm considering reopening this issue

**Comment by realitymolder** [comment]
> With the 3 key changes in the past 24 hours I'm considering reopening this issue

what key changes?

**Comment by iamchokerman** [comment]
> > With the 3 key changes in the past 24 hours I'm considering reopening this issue
> 
> what key changes? 

gogo changed their encryption keys 3 times in 24 hours

**Comment by port19x** [comment]
and they already changed it again.
Time to reopen

**Comment by Raif1** [comment]
Is it possible to use animekisa.tv and animixplay.to? Although animixplay uses gogo as its backend . And i think animekisa has less anime . I think then there should be multiple providers . like If ones broken use another and vice versa .

**Comment by realitymolder** [comment]
> Is it possible to use animekisa.tv and animixplay.to? Although animixplay uses gogo as its backend . Does sites have the same problems with the encryption keys ? And i think animekisa has less anime . I think then there should be multiple providers . like If ones broken use another and vice versa .

im not the best weeb 
but they say that for anime piracy 9anime.to is the best.
Does it make sense?

**Comment by iamchokerman** [comment]
9anime is too complex to scrape, more so in bash

**Comment by Raif1** [comment]
> 

Uh wouldnt that make it really hard to browse and choose anime episodes according to series. Episodes will get unorganized.

**Comment by port19x** [comment]
> Is it possible to use animekisa.tv and animixplay.to? Although animixplay uses gogo as its backend . Does sites have the same problems with the encryption keys ? And i think animekisa has less anime . I think then there should be multiple providers . like If ones broken use another and vice versa .

animixplay has been an early favorite

**Comment by Raif1** [comment]
> animixplay has been an early favorite
>
You plan to do use this site ?

**Comment by CoolnsX** [comment]
> Is it possible to use animekisa.tv and animixplay.to? Although animixplay uses gogo as its backend . Does sites have the same problems with the encryption keys ? And i think animekisa has less anime . I think then there should be multiple providers . like If ones broken use another and vice versa .

No these sites uses embedded link of gogoanime.. u can also use embedded link to run video in browser..

**Comment by Raif1** [comment]
> > Is it possible to use animekisa.tv and animixplay.to? Although animixplay uses gogo as its backend . Does sites have the same problems with the encryption keys ? And i think animekisa has less anime . I think then there should be multiple providers . like If ones broken use another and vice versa .
> 
> No these sites uses embedded link of gogoanime.. u can also use embedded link to run video in browser..

pretty sure animekisa isnt

**Comment by icedgreen** [comment]
What about [](https://lite.animevibe.se/ )? It's a backup site for [](https://animevibe.se/) and is very lightweight.

**Comment by KodiCraft** [comment]
> What about https://lite.animevibe.se/ ? It's a backup site for https://animevibe.se/ and is very lightweight.

Looks like it also uses embedded links from gogoanime, which coincidentally seems to not be allowed anymore all of a sudden

**Comment by MysteriousK69** [comment]
What about something like a torrenting mode? Maybe we could use a torrenting website like SubsPlease or Nyaasi.

**Comment by MysteriousK69** [comment]
nvm this has been mentioned above in the thread.

**Comment by Spaxly** [comment]
pr #677 fixes gogo's encryption key issue

**Comment by port19x** [comment]
> pr #677 fixes gogo's encryption key issue

Fixes one issue. They have proven to change their keys rather quickly

**Comment by port19x** [comment]
> > Is it possible to use animekisa.tv and animixplay.to? Although animixplay uses gogo as its backend . Does sites have the same problems with the encryption keys ? And i think animekisa has less anime . I think then there should be multiple providers . like If ones broken use another and vice versa .
> 
> No these sites uses embedded link of gogoanime.. u can also use embedded link to run video in browser..

according to KR, if you have gogo embeds you need to dig deeper

**Comment by realitymolder** [comment]
wait, why is it closed, what is the resolution?

**Comment by port19x** [comment]
> wait, why is it closed, what is the resolution?

gogo anime seems to have stopped their key juggleing madness

**Comment by CoolnsX** [comment]
> wait, why is it closed, what is the resolution?

Check for this discussion..
https://github.com/pystardust/ani-cli/discussions/685

**Comment by ArnabGamerz1000** [comment]
probably add kickassanime and ditch gogoanime lol
