### ISSUE TITLE
Menu in Loop has hardcoded colors

### ISSUE THREAD

**Issue by Derisis13** [pystardust/ani-cli#385]
It appears when playing the first/last episode of any anime. Tried to fix it, but couldn't do it in a POSIX-compliant way.

**Comment by 71zenith** [comment]
Can you explain it a bit? I can't reproduce the error.

**Comment by ura43** [comment]
> Can you explain it a bit? I can't reproduce the error.

Check out his PR and run any episode 1 of any anime

**Comment by pystardust** [comment]
@Derisis13 
What about not coding it even and odd, but use one function for menu, which tweaks a global variable on and off making it alternate
