### ISSUE TITLE
It cannot find VLC when it is downloaded in the correct spot

### ISSUE THREAD

**Issue by X3non101** [pystardust/ani-cli#387]
I'm trying to install this software, from what I can tell, I've imputed all the code correctly, and have VLC up to date and located in the correct spot. Although when I go to test the software, it claims that it could not find VLC. Did I miss any steps?

I'm on windows btw in case it matters.

**Comment by 71zenith** [comment]
> I'm trying to install this software, from what I can tell, I've imputed all the code correctly, and have VLC up to date and located in the correct spot. Although when I go to test the software, it claims that it could not find VLC. Did I miss any steps?
Whats the output when you run the script?

**Comment by ura43** [comment]
> I'm trying to install this software, from what I can tell, I've imputed all the code correctly, and have VLC up to date and located in the correct spot. Although when I go to test the software, it claims that it could not find VLC. Did I miss any steps?
> 
> I'm on windows btw in case it matters.

Do a make uninstall and then reinstall using the new instructions in the readme

**Comment by X3non101** [comment]
> 

Program "vlc" not found. Please install it.
^this is the output when I run the script

**Comment by X3non101** [comment]
> > I'm trying to install this software, from what I can tell, I've imputed all the code correctly, and have VLC up to date and located in the correct spot. Although when I go to test the software, it claims that it could not find VLC. Did I miss any steps?
> > I'm on windows btw in case it matters.
> 
> Do a make uninstall and then reinstall using the new instructions in the readme

I just tried that, at least I think I did, still trying to figure out this coding stuff. But the issue was not resolved

**Comment by ura43** [comment]
Btw `Program "vlc" not found` means you have installed ani-cli itself successfully, just our documentation could be a bit more descriptive with how to add vlc to path, or should at least point to a good guide

**Comment by RaynardGerraldo** [comment]
@X3non101 is vlc in env path? https://www.vlchelp.com/add-vlc-command-prompt-windows/ a guide to follow

@ura43 maybe we could just link that in the docs?
