### ISSUE TITLE
Non-interactive usage through flags

### ISSUE THREAD

**Issue by 4cecoder** [pystardust/ani-cli#389]
if you know the choice/anime_id and episode:
`ani-cli  boruto -a 3 -e 2`

searches for boruto looks for (english sub) and chooses episode 2 if exists then plays into mpv 

NO prompt asking to select episode!
Goes right to playing!

**Comment by ura43** [comment]
Excuse the title edit, but this is way too long

**Comment by 71zenith** [comment]
I also would agree on this. The only thing I would have allowed is the passing of arguments to the player. Since it is tedious to set them after the player is opened through keybindings.

**Comment by pystardust** [comment]
I think it would be great to have minimal non interactive usage like this. (Unless it gets complicated it) Here we just auto select  and die if the options don't exist
