### ISSUE TITLE
Search Broken because values are not being set properly

### ISSUE THREAD

**Issue by 71zenith** [pystardust/ani-cli#392]
The **prompt** function takes input and stores it in two variables. While searching some anime, I and i guess many put spaces. and the function stores those words in two different variables. So the first part gets stored in the first variable which is **REPLY**(see line no. 222) So the searching only takes the first variable.
Keep in mind that it is not a complete bug since the prompt function is made that way for selecting multiple episodes(see line no. 296) but since function is shared, all others who use it have their variables seperate.

**Comment by ura43** [comment]
You said in the duplicate #394 that substituting spaces with hyphens makes it work again?
Perhaps we only need to adapt documentation?

**Comment by 71zenith** [comment]
yes it does cause then the whole thing is put into the first variable

**Comment by Derisis13** [comment]
PR #395 should fix it
