### ISSUE TITLE
Not being able to find shows

### ISSUE THREAD

**Issue by patgamer351** [pystardust/ani-cli#394]
I have been using ani-cli for a few months but now whenever I use ani-cli and enter in the show name "One Piece" and others like "Ijiranide nagatoro" i kept on getting prompted "No search results found". I use Ubuntu 20.04 LTS, grep 3.4, sed 4.7, curl 7.68.0, openssl 1.1.1f..., jq 1.6, aria2c 1.35.

**Comment by 71zenith** [comment]
There is a bug currently which has problems with spaces. If you need to watch no matter what then replace the spaces with -

**Comment by patgamer351** [comment]
hmm, still happens without spaces

**Comment by ura43** [comment]
> hmm, still happens without spaces

Good thinking, but sadly its not that simple

**Comment by patgamer351** [comment]
uhuh going to gogoanime.pe just says that "Access to this website has been disabled by an order of the Federal Court of Australia because it infringes or facilitates the infringement of copyright." damn

**Comment by ura43** [comment]
Don't just go closing the issue with that

How about its other domains, like gogoanime.wiki?
How about a proxy / vpn?
Any further context you can give?

**Comment by ura43** [comment]
*sigh* the site still works in germany.
Yeah I guess we can close it, best of luck @patgamer351 at reclaiming your digital freedom

**Comment by patgamer351** [comment]
ayy, i changed the gogoanime.cm to gogoanime.wiki in the program and now it works thanks you so much!!
