### ISSUE TITLE
[enhancement] choose another video player

### ISSUE THREAD

**Issue by RealityMolder** [pystardust/ani-cli#397]
an option in the configuration of the program to choose another video program for example the open source modern IINA.

**Comment by ura43** [comment]
Ahem...
![image](https://user-images.githubusercontent.com/82055622/150985890-cad04552-4848-43bf-9a2d-530c3fa33278.png)

**Comment by RealityMolder** [comment]
seems like i wasn't using ani-cli for a while ;) thanks
