### ISSUE TITLE
Smart TV

### ISSUE THREAD

**Issue by Mercyfulsin** [pystardust/ani-cli#40]
Not sure of this is possible, but can we attempt this on a smart TV? I have a Samsung with GooglePlay store and downloaded Termux. There I installed the dependencies and cloned the repo. I was able to get everything working but when playing only the audio is heard and the video doesn't seem to appear. I'm assuming because normally the application opens another terminal or splits the current one but doesn't seem to work on Smart TV. Any ideas on what we could do here?

**Comment by 3hree6ix0** [comment]
Two things here: 
1. The script uses mpv  which is a linux based multimedia player.
2. Audio will be played through pulseaudio/alsa/pipewire.

considering these two things, a smart tv will need a display protocol that mpv supports and an audio stream that mpv supports as well, so try installing pulse audio xserver etc, but I doubt that it seriously will work. the concept tho is big brane.

**Comment by chirag-droid** [comment]
You need to start a xserver if you want to see the display. read about here https://wiki.termux.com/wiki/Graphical_Environment
I am currently experimenting with android mpv player, it opens but can't pass the http header to it, which makes it unable to play video.

**Comment by sdshan8** [comment]
> Not sure of this is possible, but can we attempt this on a smart TV? I have a Samsung with GooglePlay store and downloaded Termux. There I installed the dependencies and cloned the repo. I was able to get everything working but when playing only the audio is heard and the video doesn't seem to appear. I'm assuming because normally the application opens another terminal or splits the current one but doesn't seem to work on Smart TV. Any ideas on what we could do here?
 

First you need to install mpv-x instead of mpv
Then put `vo=x11` in /data/data/com.termux/files/usr/etc/mpv/mpv.conf

**Comment by ura43** [comment]
What's the status on this? Sounds exciting

**Comment by ura43** [comment]
> What's the status on this? Sounds exciting

Actually sounds like a very error prone way to support an obscure plattform. I believe there are better projects out there to achieve Anime on Smart TV
