### ISSUE TITLE
Downloading broken due to bad -e

### ISSUE THREAD

**Issue by ura43** [pystardust/ani-cli#406]
**Metadata (please complete the following information):**
Version: 1.3.0
OS: Linux Mint 20.3
Shell: zsh

**Describe the bug**
Downloading is broken and spits out `Exception: [download_helper.cc:451] errorCode=1 Unrecognized URI or unsupported protocol`
This is due to a missing emptiness check from a new feature introduced today

**To Reproduce**
1. Run `ani-cli -d flcl`
2. Choose 2 (fooly-cooly)
3. Choose episode 1

**Expected behavior**
Downloading should work

**Screenshots**
What a normal user sees
![image](https://user-images.githubusercontent.com/82055622/151030428-2e78d15f-4ba9-4d86-b6f3-8307557b4b29.png)

Debugging with `bash -x`
![Bug](https://user-images.githubusercontent.com/82055622/151030324-084e43f1-f768-4e5d-86b8-d4524fd5e017.png)

**Additional context**
-

**Comment by ura43** [comment]
![image](https://user-images.githubusercontent.com/82055622/151545201-794c186a-c953-4674-9fe7-85313704abfd.png)

**Comment by ura43** [comment]
We somehow reintroduced the error

**Comment by 71zenith** [comment]
Cause the check for whether player_arguments exists is removed somehow
