### ISSUE TITLE
uname: illegal option -- o

### ISSUE THREAD

**Issue by iamchokerman** [pystardust/ani-cli#416]
**Metadata (please complete the following information):**
Version: [1.4.0]
OS: [Mac Catalina v10.15.6 && Mac BigSur v11.6]
Shell: [fish-shell && zsh]

**Describe the bug**
when running ```sudo make``` it outputs:
uname: illegal option -- o
usage: uname [-amnprsv]
Failed to detect Platform

**To Reproduce**
1. Run `sudo make`

**Expected behavior**
should copy ani-cli to /usr/local/bin/ and chmod

**Screenshots (if applicable)**
<img width="316" alt="Screen Shot 2022-01-26 at 3 57 39 PM" src="https://user-images.githubusercontent.com/44473782/151187181-2ca1387e-828b-486d-8c57-f310bce7d3b0.png">

**For fixing**
On mac ```uname -o``` is not a command, it's just ```uname``` instead, which outputs Darwin

**Comment by 0x8FF** [comment]
I'm not sure what you're dealing with, ``uname -o`` works fine for me on my Apple Silicon Mac.

**Comment by sadkris** [comment]
Due to lack of OS on my part, do you mind commenting the output of `uname -s`?

**Comment by iamchokerman** [comment]
> Due to lack of OS on my part, do you mind commenting the output of `uname -s`?

uname -s works properly, and prints out Darwin

**Comment by ura43** [comment]
> > Due to lack of OS on my part, do you mind commenting the output of `uname -s`?
> 
> uname -s works properly, and prints out Darwin

`uname -s` is "Linux" for both android and gnu/linux, effectively solving nothing

**Comment by pystardust** [comment]
`uname -o` is not posix. These are the only posix options
```
-a
Behave as though all of the options -mnrsv were specified.
-m
Write the name of the hardware type on which the system is running to standard output.
-n
Write the name of this node within an implementation-defined communications network.
-r
Write the current release level of the operating system implementation.
-s
Write the name of the implementation of the operating system.
-v
Write the current version level of this release of the operating system implementation.
```
