### ISSUE TITLE
Change the install process

### ISSUE THREAD

**Issue by ura43** [pystardust/ani-cli#417]
**In what category does your enhancement fall? [choose: safety, speed, ux, qa, other]**
qa

**Status Quo**
We currently document seperate install processes for each of the different plattforms we support, but still chose to refactor the Makefile to the point where now it is just a very verbose way of copying or removing ani-cli from PATH.

**The Enhancement**
Instead we could simply modify the install documentation to tell people to copy ani-cli to the path themselves + the mpv special case for termux.
This would change that step from being a black box ("oh cool, they have a makefile that installs it for me") to be more transparent ("I see, thats how I can run it from anywhere") and also more adaptable since users with weird M1 issues can easily just copy the file to the different PATH location.

**Additional context**
In the past month, issues surrounding installation and/or the makefile have caused a conservative estimate ~25% of the total issues, 90% of support inquiries, and at least 20 hours of work distributed amongst the maintainers.
It's easy to let yourself be dragged down by sunken cost.
If anyone can convince me how a `sudo make` oneliner is superior from a user perspective than a `sudo cp ani-cli /usr/local/bin/ani-cli`, I may reconsider my stance

**Comment by ura43** [comment]
Slight correction: The makefile also marks ani-cli as executable. Doesn't change my opinion tho

**Comment by sgtxd** [comment]
To also say something, the AUR package completely disregards the Makefile anyway and does the same thing as copying it into /bin and making it an executable.

**Comment by Derisis13** [comment]
I personally never understood (why it exists) nor used the makefile... It also adds an extra dependency for the installation: `build-essential` (although it's pretty common to have it)

**Comment by Xathros1** [comment]
if you want to work without the makefile, ok, but with the frequency of updates it is quite annoying to copy the file all the time.
Therefore I would suggest to work directly with a symlink.

So instructions for linux (other) would look like this:

```
git clone https://github.com/pystardust/ani-cli
cd ani-cli
chmod +x ani-cli
sudo ln -s /home/<username>/ani-cli/ani-cli /usr/local/bin
```

Uninstallation would then look like this:

`sudo unlink /usr/local/bin/ani-cli`

**Comment by 0x8FF** [comment]
we have already tried symlinks, so lol no @Xathros1

**Comment by Xathros1** [comment]
As written, this was only a suggestion. In any case, it works.

**Comment by sadkris** [comment]
On a tangent, Windows instructions need to be rewritten.

Git Bash doesn't allow users to use `$(WINDIR)` to reference environment variables.

This requires the installation instructions to be rewritten as such:
```
git clone https://github.com/pystardust/ani-cli.git
cd ani-cli
mkdir -p "$USERPROFILE/.cache"
cp ani-cli $WINDIR/system32/ani-cli
```

**Comment by ura43** [comment]
> we have already tried symlinks, so lol no @Xathros1

100% what I would have answered

**Comment by r4vanan** [comment]
but we can do with ~/.local/bin right. 
because most of the people having that

**Comment by justchokingaround** [comment]
no
