### ISSUE TITLE
grep: invalid repetition count(s)

### ISSUE THREAD

**Issue by iamchokerman** [pystardust/ani-cli#418]
**Metadata (please complete the following information):**
Version: [v1.4.0]
OS: [Mac OS Big Sur and Catalina]
Shell: [zsh and fish]

**Describe the bug**
Does not play video after episode is selected, tested with naruto, one piece, code geass...

**To Reproduce**
1. Run `ani-cli naruto`
2. Select episode 1

**Expected behavior**
Video should open. Also tested for iina with -i flag, same results.

**Screenshots (if applicable)**
<img width="374" alt="Screen Shot 2022-01-26 at 5 46 30 PM" src="https://user-images.githubusercontent.com/44473782/151207877-b6a441ce-88ac-4403-bf0a-be0f28e7569d.png">

**Additional context**

**Comment by pystardust** [comment]
This is due to using variable with grep with bad regular expression.
```
grep "$variable"
```
maybe the grep was meant to search for string and not regex but it has the format of a bad regex. We should use `-F` flag to inform grep that it's a string we are searching. 
line 335 and 187 are such lines

**Comment by pystardust** [comment]
@ura43 any progress on this? I can't reproduce this error

**Comment by RaynardGerraldo** [comment]
> @ura43 any progress on this? I can't reproduce this error

are you in mac? because this is a mac only bug

**Comment by RaynardGerraldo** [comment]
@iamchokerman 

i dont have a mac,so i need you to test this regex out

`grep -Eo 'https?:\/\/(www)?[-a-zA-Z0-9@:%._\+~#=]{1,256}[a-zA-Z0-9()]{1,6}([-a-zA-Z0-9()@:%_\+.~#?&\/\/=]*)`

replace the regex in line 176 with this

**Comment by iamchokerman** [comment]
@RaynardGerraldo didnt change anything
