### ISSUE TITLE
[Feature Request] Ability to change Video Quality in Streams and Downloads

### ISSUE THREAD

**Issue by ZN0N15** [pystardust/ani-cli#42]
Is it possible to have the ability to change the video quality of the anime? I'm pretty sure Gogoanime has a Multiquality Server that lets you pick what quality to choose when watching. Currently ani-cli just defaults to 1080p/720p which I don't really use because streaming it is slow and sometimes get tearing/artifacting issues, and it uses lots of disk space to download. I always go for the Multiquality Server on Gogoanime to manually choose 360p when streaming or downloading. Please consider having the option to choose video quality if Possible.

**Comment by EsmailELBoBDev2** [comment]
i agree, i want this feature too

**Comment by Dink4n** [comment]
You give the quality like
```console
ani-cli -q 360
```

**Comment by ZN0N15** [comment]
It works well. Thanks! 

Also I'm curious, was the change in URL necessary? I saw you changed from `https://gogoanime.vc` to `https://gogoanime.pe`, which I didn't know that domain existed. I always went to .vc which still included the Multiquality video server. Does the .pe domain default to the Multiquality video?

**Comment by stl3** [comment]
> It works well. Thanks!
> 
> Also I'm curious, was the change in URL necessary? I saw you changed from `https://gogoanime.vc` to `https://gogoanime.pe`, which I didn't know that domain existed. I always went to .vc which still included the Multiquality video server. Does the .pe domain default to the Multiquality video?

Maybe the other can be used as a 'failover' with a timeout that cycles between them if one cannot be reached

**Comment by Dink4n** [comment]
@ZN0N15  In my region `https://gogoanime.vc` is blocked. So I have to use the `https://gogoanime.pe` to get it to work.

**Comment by Dink4n** [comment]
Merged #46. Closing
