### ISSUE TITLE
Bugged menu when using `-c`

### ISSUE THREAD

**Issue by Derisis13** [pystardust/ani-cli#422]
**Metadata (please complete the following information)**
Version: 1.4.1
OS: Pop!_OS 21.10
Shell: bash
Anime: Anything I try

**Describe the bug**
Menu in loop is broken when starting the script with `-c`. It doesn't reset on `n`, `p` or `r` but does go away on any other option. Regular search mode is OK as far as I have seen.

**Steps To Reproduce**

1. Run `ani-cli -c` with a non-empty history
2. Choose any anime
3. Broken menu is displayed

**Expected behavior**
Options `previous episode` and `replay episode` should be instead of the error messages.

**Screenshots (if applicable)**
![image](https://user-images.githubusercontent.com/66648475/151270481-1292da4b-d706-4398-b8f3-d898bcd4c0bb.png)

**Additional context**
Probably a variable is not set that is being checked, but that's just a guess...

**Comment by Rafaeruo** [comment]
Introduced in 7fd16374fca464b4b4aa723828c5ba05aa46dc60

**Comment by 71zenith** [comment]
I'll try to look into it

**Comment by 71zenith** [comment]
Found the problem, opening a pr
