### ISSUE TITLE
mpv not opening

### ISSUE THREAD

**Issue by Zy-XD** [pystardust/ani-cli#43]
cli shows that the anime is currently playing, but didnt open mpv at all, i do not know if this is a windows only problem or what

**Comment by Samip-Karki** [comment]
Same problem in Ubuntu mate 21.04

**Comment by luntovsky** [comment]
Same problem here,  couldn't get `setsid` working on my mac (big sur 11.6)
Fixed the problem by removing the `setsid` command on line: 
https://github.com/pystardust/ani-cli/blob/7d9ae36e3eee6a7e0ed479715862cf0adc0c901f/ani-cli#L213
and running just the `mpv` command in the background.
Also added kill process for closing the player when next / prev episode is played:

![image](https://user-images.githubusercontent.com/33714789/137597653-3d5282ff-b7ba-4c1f-a7f3-786272f22d53.png)


not pretty but it works ^^

**Comment by slcheungcasado** [comment]
`setsid` isn't in macos by default so `brew install util-linux` and add it to your PATH.

**Comment by mohammadash** [comment]
> I thought I was going to run into this problem, but I waited for a bit and eventually mpv launched. I was doing this on a raspberry pi4 B+ 8gb, in dietpi. The only issue I had was buffering issue but that is something seperate.

Yes, mpv launches but it's like 1-5% chance that it will launch after clicking or manually opening mpvPlayer, not automatically as it should be.

**Comment by Dylan-bit247** [comment]
> > It's a compatibility issue. Please print your version of `setsid`
> > ```
> > setsid -V
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Older version of `setsid` doesn't have the argument -f
> 
> is there a library / site to download from that is convenient for windows?

im using setsid from util-linux 2.34 but finding same issue. is this version not recent enough?

**Comment by Dink4n** [comment]
@Dylan-bit247  Your version is recent enough. The `setsid -f` flag was introduced in [util-linux 2.32](https://mirrors.edge.kernel.org/pub/linux/utils/util-linux/v2.32/v2.32-ReleaseNotes).
Can you give more info about your OS?

**Comment by SmellsNice** [comment]
> > > It's a compatibility issue. Please print your version of `setsid`
> > > ```
> > > setsid -V
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Older version of `setsid` doesn't have the argument -f
> > 
> > 
> > is there a library / site to download from that is convenient for windows?
> 
> im using setsid from util-linux 2.34 but finding same issue. is this version not recent enough?

I am also using util-linux 2.37.2 on EndeavourOs. I can't really figure out why this happens as setsid seems to work perfectly fine but I have to open an mpv window every time for it to load.

**Comment by Ellana42** [comment]
> Here's an easy copy and paste fix if you have brew & zsh:
> 
> ```shell
> brew install util-linux
> echo 'export PATH="/usr/local/opt/util-linux/bin:$PATH"' >> ~/.zshrc
> echo 'export PATH="/usr/local/opt/util-linux/sbin:$PATH"' >> ~/.zshrc
> export LDFLAGS="-L/usr/local/opt/util-linux/lib"
> export CPPFLAGS="-I/usr/local/opt/util-linux/include"
> export PKG_CONFIG_PATH="/usr/local/opt/util-linux/lib/pkgconfig"
> ```

These worked for me

**Comment by ura43** [comment]
Long story short: setsid is terrible and we should move to nohup quickly.
See #2 and the linked PR #137 
Continue discussion there
