### ISSUE TITLE
Can we have a homebrew package

### ISSUE THREAD

**Issue by ura43** [pystardust/ani-cli#432]
**Is your feature request related to a problem? Please describe.**
There are still occasional reports of weird installation problems from some mac users.
Apart from that, this would obviously be better UX.
Native packages are always best.

**Describe the solution you'd like**
Someone create and maintain a homebrew package of ani-cli.
I'll happily supply all the metadata you need.

**Describe alternatives you've considered**
We could leverage the wiki to document edge cases and their workarounds.
But that seems like bad form

**Additional context**
Homebrew is the dominant package manager over on mac os

**Comment by iamchokerman** [comment]
on it

**Comment by ura43** [comment]
Tracking PR from homebrew core: https://github.com/Homebrew/homebrew-core/pull/94169

**Comment by ura43** [comment]
It seems like it will be very difficult to get ourselves included, considering their testing policy

**Comment by 4cecoder** [comment]
> It seems like it will be very difficult to get ourselves included, considering their testing policy

It seems to me that we could organize the project that would make our repo tap-able 
`brew tap <direct_repo_url> && brew install <your repo program>`
Lets reference: https://docs.brew.sh/Taps

**Comment by 4cecoder** [comment]
@iamchokerman  let me know more about your fork and how it merges

**Comment by iamchokerman** [comment]
> @iamchokerman let me know more about your fork and how it merges

you can find my fork at [](https://github.com/iamchokerman/homebrew-ani-cli/)
basically to merge it with homebrew-core it's required to have a test it can pass (one that you make yourself inside the ruby file), to test whether or not it's working properly after the install. however idk how it can be possible to create such a test for ani-cli specifically. i created testdata at some point to compare the output of ani-cli -h with the text in testdata but that didn't work :(
feel free to checkout this PR for more feedback / info : [](https://github.com/Homebrew/homebrew-core/pull/94169#pullrequestreview-867657397)

**Comment by ThamognyaKodi** [comment]
Thank you. It works on my macOS build.

**Comment by ura43** [comment]
I think we can consider this resolved, right?

**Comment by iamchokerman** [comment]
> I think we can consider this resolved, right?

yeah, we can probably close the issue for now
