### ISSUE TITLE
Konosuba is broken (...?)

### ISSUE THREAD

**Issue by farchord** [pystardust/ani-cli#435]
**Metadata (please complete the following information)**
Version: 1.5.0
OS: Fedora Workstation 35
Shell: zsh
Anime: konosuba

**Describe the bug**
Shows a list of results to a search, then says the number is invalid (see screenshot)

**Steps To Reproduce**

1- Run ani-cli and search for konosuba (Lower case)
2- Select #7 (Also does it on #5 for me)
3- "Invalid number entered"

**Expected behavior**
For it to find the show

**Screenshots (if applicable)**
![Screenshot_20220127_181311](https://user-images.githubusercontent.com/1653443/151459830-19f6c35e-3236-48ba-8ddf-85c5eb18f828.png)

**Additional context**

**Comment by pystardust** [comment]
fixed in above commit

**Comment by 71zenith** [comment]
Just close the issue
