### ISSUE TITLE
Non-integer episodes broken

### ISSUE THREAD

**Issue by ura43** [pystardust/ani-cli#441]
**Metadata (please complete the following information)**
Version: v1.5.1
OS: Linux Mint 20.3
Shell: zsh
Anime: arifureta-shokugyou-de-sekai-saikyou

**Describe the bug**
When trying to watch episode 5.5 through our `h5` convention it exits saying `Invalid number entered`

**Steps To Reproduce**

1. Run `ani-cli arifureta`
2. Choose 1 (arifureta-shokugyou-de-sekai-saikyou)
3. Choose episode 1

**Expected behavior**
For non-integer Episodes to be support 
**Screenshots (if applicable)**
![image](https://user-images.githubusercontent.com/82055622/151543766-335c09f8-e225-4649-92e9-84fc3c104a77.png)

**Additional context**
Looking for more non-integer episode anime to list in the Testing section of contributing.md

**Comment by RaynardGerraldo** [comment]
> **Metadata (please complete the following information)** Version: v1.5.1 OS: Linux Mint 20.3 Shell: zsh Anime: arifureta-shokugyou-de-sekai-saikyou
> 
> **Describe the bug** When trying to watch episode 5.5 through our `h5` convention it exits saying `Invalid number entered`
> 
> **Steps To Reproduce**
> 
>     1. Run `ani-cli arifureta`
> 
>     2. Choose 1 (arifureta-shokugyou-de-sekai-saikyou)
> 
>     3. Choose episode 1
> 
> 
> **Expected behavior** For non-integer Episodes to be support **Screenshots (if applicable)** ![image](https://user-images.githubusercontent.com/82055622/151543766-335c09f8-e225-4649-92e9-84fc3c104a77.png)
> 
> **Additional context** Looking for more non-integer episode anime to list in the Testing section of contributing.md

this was fixed in #429

**Comment by ura43** [comment]
Duplicate of #428

**Comment by ura43** [comment]
I have no idea what happened but now I can't reproduce the error anymore.
Could have sworn that was on master.
Guess I'll close
