### ISSUE TITLE
Disable link printing for -c

### ISSUE THREAD

**Issue by ura43** [pystardust/ani-cli#442]
**Metadata (please complete the following information)**
Version: v1.5.1
OS: Linux Mint 20.3
Shell: zsh

**Describe the bug**
When running ani-cli with the -c flag, the programm still prints the links to gogoplay and vidstreamingcdn.

**Steps To Reproduce**

1. Run `ani-cli flcl`
2. Choose 1 (flcl-dub)
3. Choose episode 3

**Expected behavior**
Output should be as consistent as possible and -c shouldn't be different from non-c in that regard.

**Screenshots (if applicable)**
![image](https://user-images.githubusercontent.com/82055622/151544623-f170cffa-3ecf-4f90-b87a-538332a954f0.png)

**Additional context**
This exists because we missed something during the large refactor by Derisis13

**Comment by 71zenith** [comment]
It doesn't print for me though

**Comment by RaynardGerraldo** [comment]
> It doesn't print for me though

same here

**Comment by ura43** [comment]
> > It doesn't print for me though
> 
> same here

same here

**Comment by ura43** [comment]
My `ani-cli` isn't my `./ani-cli` and that might have tripped me up. 
I'll make double sure to be on the latest version in future tests
