### ISSUE TITLE
video doesn't open on mac

### ISSUE THREAD

**Issue by iamchokerman** [pystardust/ani-cli#447]
**Metadata (please complete the following information)**
Version: [1.5.5]
OS: [Mac OS Big Sur]
Shell: [zsh]
Anime: [all anime] (if applicable)

**Describe the bug**
mpv and iina both don't open any video after episode selection

**Steps To Reproduce**

1. Run `ani-cli naruto`or `ani-cli -i naruto`
2. Select episode 1

**Expected behavior**
Videos opens up

**Screenshots (if applicable)**
![image](https://user-images.githubusercontent.com/44473782/151583179-237e95df-dfd5-4de2-b35d-700c3a08ce30.png)

**Additional context**

**Comment by NOX2912** [comment]
It worked for me if you just open the vlc player in the background first and then run ani-cli.

**Comment by 71zenith** [comment]
> It worked for me if you just open the vlc player in the background first and then run ani-cli.

It may work but that is not a good UX

**Comment by GamaG27** [comment]
> It worked for me if you just open the vlc player in the background first and then run ani-cli.

you dont even need to have vlc in the background

**Comment by raywang999** [comment]
I had the same issue, also running same specs (macOS big sur, ani-cli v. 1.5.5, shell: zsh) 
I'm thinking it might be something with zsh or xargs (v. 1.7) Reason: 
For me, I'm using iina, so I managed to work around it by deleting first few characters of line 438 of the `ani-cli` script:
`echo "$player_arguments" | xargs "$player_fn" --referrer="$dpage_link" "$video_url" --title="ani-cli: $anime_id ep $episode" > /dev/ null 2>&1`
to 
`"$player_fn" --referrer="$dpage_link" "$video_url" --title="ani-cli: $anime_id ep $episode" > /dev/null 2>&1`

Not sure if this helps, but thought it might narrow the issue down.

**Comment by 71zenith** [comment]
> Not sure if this helps, but thought it might narrow the issue down. Also, yeah rip options, but I don't really use them so...

Thank you for informing, I will try to get rid of xargs as soon as possible
