### ISSUE TITLE
Can we have a scoop package?

### ISSUE THREAD

**Issue by ura43** [pystardust/ani-cli#448]
**Is your feature request related to a problem? Please describe.**
The Windows Installation is currently the most error prone by far.

**Describe the solution you'd like**
Having a native, managed package for it could remedy that.

**Describe alternatives you've considered**
I prefer scoop over chocolatey, but if chocolatey packages are easier to create and maintain I'm open to that too
Or we do #446 which is a ton of work.

**Additional context**
This issue is the windows equivalent of #432
[Scoop](https://github.com/ScoopInstaller/Scoop)
[Chocolatey](https://github.com/chocolatey/choco)

**Comment by RaynardGerraldo** [comment]
https://github.com/ScoopInstaller/Extras/commit/2a02434f58dbead3921b91be0307bd131b1dca87

We in
