### ISSUE TITLE
Only plays in background on Termux on Android

### ISSUE THREAD

**Issue by dsivasuthan** [pystardust/ani-cli#449]
**Metadata (please complete the following information)**
Version: 1.5.5
OS: Android
Shell: bash on Termux
Anime: Not applicable

**Describe the bug**
I installed following instruction on README (I had to manually create the bin files but that's not an issue)
I installed mpv via Termux.
Even though all the command ran without any error, I wasn't able to run `ani-cli` by itself, so I ran `./ani-cli` from the git folder and that worked
I searched for Silver Spoon and it found the anime but it started playing in the background.
How do I make it play via mpv from F-Droid?

Thanks for creating this script. I got it to work on my laptop but not on my phone. Any help is appreciated. Thanks.

**Comment by CoolnsX** [comment]
First install termux-tools
```apt install termux-tools```
Then replace line 426 with
```termux-open --content-type video "$video_url"```

**Comment by CoolnsX** [comment]
Keep in mind that auto play doesn't work in termux.. so don't give the range while watching episode..

**Comment by RaynardGerraldo** [comment]
This issue can be closed by aa2fe797a7cdfd6773439d5475480e0ac6805009 @CoolnsX right?

**Comment by ura43** [comment]
Probably resoved by aa2fe79
