### ISSUE TITLE
Tried changing mpv with vlc but still not working

### ISSUE THREAD

**Issue by prorounak2005** [pystardust/ani-cli#45]
I tried to change it with vlc instead on mpv but the script was not working 

#!/bin/sh

\# dependencies: grep sed curl video_player
\# video_player ( needs to be able to play urls )
player_fn="vlc"

prog="ani-cli"
logfile="${XDG_CACHE_HOME:-$HOME/.cache}/ani-hsts"

c_red="\033[1;31m"
c_green="\033[1;32m"
c_yellow="\033[1;33m"

**Comment by prorounak2005** [comment]
I want to run it on vlc because I personally dont like mpv and it is trash .

**Comment by NoRMaNxLLy** [comment]
was it working with mpv ?

**Comment by avidhy-chan** [comment]
> 
> 
> was it working with mpv ?

Yup working fine with mpv. Test in windows and can confirm it's working.

**Comment by nabakolu** [comment]
I think the problem is in line 213:  
`setsid -f $player_fn --http-header-fields="Referer: $embedded_video_url" "$video_url" >/dev/null 2>&1`  
But vlc does not have the cli option `http-header-fields`. Instead you could use the option `--http-referrer` provided in vlc.  
It should look something like this:
`setsid -f $player_fn --http-referrer="$embedded_video_url" "$video_url" >/dev/null 2>&1`

**Comment by prorounak2005** [comment]
> was it working with mpv ?

Yes it was working with mpv fine. But i discovered a weird thing in vlc. Whenever press ctrl + n in vlc and try to put in a video link for ex a youtube link it says. MRL not found. And the problem is not from my end i checked it with different pcs.

**Comment by prorounak2005** [comment]
> I think the problem is in line 213: `setsid -f $player_fn --http-header-fields="Referer: $embedded_video_url" "$video_url" >/dev/null 2>&1` But vlc does not have the cli option `http-header-fields`. Instead you could use the option `--http-referrer` provided in vlc (look at [the documentation](https://wiki.videolan.org/VLC_command-line_help/)). It should look something like this: `setsid -f $player_fn --http-referrer="$embedded_video_url" "$video_url" >/dev/null 2>&1`

It opens the vlc player but doeswnt play the video :(

**Comment by nabakolu** [comment]
Then I'd recommend echoing one of these links and trying to get it to work manually

**Comment by Glitcher85** [comment]
> Do you need any further support?

Nope, it seems like they added a vlc option as well.

**Comment by ura43** [comment]
Good to hear @Glitcher85 :smiley: 

Full vlc support was implemented 2 weeks ago in PR #172 
Update to the latest version
If you still have issues, don't hesitate to open another issue
