### ISSUE TITLE
Downloading doesn't work

### ISSUE THREAD

**Issue by FatahChan** [pystardust/ani-cli#451]
**Metadata (please complete the following information)**
Version: 1.5.5
OS: [WSL (Ubuntu 20.04) on Windows 11
Shell: powershell/bash
Anime: all

**Describe the bug**
Downloading is broken.
 CUID#7 - Download aborted.
 
**Steps To Reproduce**

1. Run `ani-cli -d <any anime>`
2. Choose any number
3. Choose any episodes 

**Expected behavior**
Downloading should work

**Screenshots (if applicable)**
![image](https://user-images.githubusercontent.com/30260221/151647050-997b9172-19c0-4fbc-a8e8-68d218635c7c.png)

**Additional context**

**Comment by 71zenith** [comment]
I can't reproduce the error

**Comment by FatahChan** [comment]
@71zenith what additional information, that might help this case

**Comment by 71zenith** [comment]
Does it repeat, or only one time

**Comment by FatahChan** [comment]
happens every time with different anime as well, keep in mind Ii just updated ani-cli to the current version

**Comment by CoolnsX** [comment]
It's the problem on your network... As it's working here..

**Comment by 71zenith** [comment]
I was just thinking the same

**Comment by FatahChan** [comment]
why streaming works but not downloading

**Comment by RaynardGerraldo** [comment]
@FatahChan its working just fine for me, can you try and update the script and re run it?

**Comment by FatahChan** [comment]
@RaynardGerraldo Thanks testing, seems result.

I am trying to install it on windows via git bash, I will report back once it is installed

**Comment by AlparslanAbdikoglu** [comment]
HI I just did a reinstall with gitbash and its works :)

**Comment by FatahChan** [comment]
@AlparslanAbdikoglu can you tell me how to install the dependencies on git bash, I was not able to install the dependencies

**Comment by ura43** [comment]
Closing. The new install process through scoop should be easier
