### ISSUE TITLE
Won't work with Powershell 7

### ISSUE THREAD

**Issue by markpaul099** [pystardust/ani-cli#454]
**Metadata**
Version: ani-cli 1.5 
OS: Windows 11
Shell: Powershell 7

**Describe the bug**
I followed the Windows Installation but when I run ani-cli or ./ani-cli on the directory but a prompt (How do you want to open this file) keeps opening

**Expected behavior**
ani-cli should work

**Screenshots**
![image](https://user-images.githubusercontent.com/32875542/151687270-6d99a003-f5cb-4870-8a1a-5e40c08d1b80.png)

**Comment by 71zenith** [comment]
pls read the readme

**Comment by sgtxd** [comment]
ani-cli does not work with Powershell, you require git bash to run it. As the person above said i advise to read the Windows install instructions.

**Comment by markpaul099** [comment]
I thought install "git bash" so i can clone the repository that's why I used PowersShell even though I already have git bash, instructions unclear I guess, 

I am using it on Ubuntu wsl2 now
