### ISSUE TITLE
iina doesn't work on mac

### ISSUE THREAD

**Issue by iamchokerman** [pystardust/ani-cli#461]
Version: [v1.6.0]
OS: [Mac OS Big Sur]
Shell: [zsh]
Anime: [any anime]

**Describe the bug**
iina doesn't open videos properly

**Steps To Reproduce**

1. Run `ani-cli -i naruto`
2. Choose 1
3. Choose episode 1

**Expected behavior**
Video should open

**Screenshots (if applicable)**
<img width="1669" alt="Screen Shot 2022-01-31 at 9 38 48 AM" src="https://user-images.githubusercontent.com/44473782/151762562-8065a889-46c2-40df-ae28-8898b3858bbe.png">

**Additional context**

**Comment by RealityMolder** [comment]
Same issue to me.

![image](https://user-images.githubusercontent.com/26459151/152534378-56d30a43-bb98-4927-9563-eb67df391f29.png)

**Comment by iamchokerman** [comment]
Unfortunately our best efforts to make it work reliably have failed. The flag -i will also be removed as an option soon. Hopefully we can bring iina back with the official release of iina+.

**Comment by RealityMolder** [comment]
> Unfortunately our best efforts to make it work reliably have failed. The flag -i will also be removed as an option soon. Hopefully we can bring iina back with the official release of iina+.

thats sad :( What is iina+ ?

**Comment by iamchokerman** [comment]
@RealityMolder for now it's a fork of iina, but it will basically be the next version of iina. you can check it out here: https://github.com/iina-plus/iina
