### ISSUE TITLE
archtorify doesn't work with ani-cli

### ISSUE THREAD

**Issue by brvn0** [pystardust/ani-cli#463]
**Metadata (please complete the following information)**
Version: 1.6.0
OS: arch linux
Shell: /bin/bash

**Describe the bug**
yo uhm nothing works when my traffic is routed through the tor network, ig it's a protection by gogoanime
it works fine when disabling tor :P 

**Steps To Reproduce**
1. install archtorify from their github
2. run both tools combined
```bash
$ sudo archtorify --tor
$ ani-cli
    Search Anime: code geass
    No search results found
```

**Expected behavior**
searching should work

**Comment by ura43** [comment]
Good to know. I assumed sth like this could happen. Blocking Tor traffic is way too common.
I'm closing this, but it's good to have this documented in an issue.
Sadly nothing we can do about it
