### ISSUE TITLE
video quality selection

### ISSUE THREAD

**Issue by Duoslow** [pystardust/ani-cli#464]
**In what category does your enhancement fall? [choose: safety, speed, ux, qa, other]**
ux
![image](https://user-images.githubusercontent.com/16846504/151902976-9927d924-44cd-4d13-8e53-bcdfdc652b69.png)

sometimes animes in best video quality so much freezing and caching. video quality selection would be great here instead of restarting the script for select lower video quality

**Comment by 71zenith** [comment]
Will try to find a way

**Comment by ura43** [comment]
related to #462 

I'll write a UML behaviour diagram of our current UX soon, no tweaks will be merged before then
