### ISSUE TITLE
mpv & termux-open issue

### ISSUE THREAD

**Issue by git-anaxa** [pystardust/ani-cli#470]
Activation of ani-cli program is terminating the utity of following terminal commands:
 • mpv
 • termux-open

**Comment by git-anaxa** [comment]
never made an issue before sorry for the trouble.

**Comment by CoolnsX** [comment]
> Activation of ani-cli program is terminating the utity of following terminal commands: • mpv • termux-open

try 
```termux-open --content-type 'video' "$2"```

**Comment by git-anaxa** [comment]
Should i echo this in any $PREFIX/bin/{executable file}
and chmod +x that?

**Comment by CoolnsX** [comment]
Yup
