### ISSUE TITLE
Part of the menu not working

### ISSUE THREAD

**Issue by guy-732** [pystardust/ani-cli#478]
**Metadata (please complete the following information)**
Version: V 1.6.3
OS: Ubuntu 20.04
Shell: bash

**Describe the bug**
When running the script to continue watching from history, and we enter `q` or `a`, it says `Invalid number entered`
while on the menu those options are present 

**Steps To Reproduce**

1. Run `ani-cli -c`
2. Choose `a` or `q`

**Expected behavior**
Should quit without error message / jump to search for an anime

**Screenshots (if applicable)**
![image](https://user-images.githubusercontent.com/81652178/152198147-353bc0be-0157-4b12-a97b-e15469361f17.png)

**Comment by 71zenith** [comment]
It does work for me though

**Comment by RaynardGerraldo** [comment]
> It does work for me though

update it to the latest version it does say invalid number entered in the history menu when choosing a or q

**Comment by ura43** [comment]
oof
