### ISSUE TITLE
Flatpak's media players compatibility 

### ISSUE THREAD

**Issue by WanderRainID** [pystardust/ani-cli#484]
**In what category does your enhancement fall? [choose: safety, speed, ux, qa, other]**
other

ani-cli can't detect media players that are installed from flatpak. please make it can detect the media players

**Comment by ura43** [comment]
Unfortunately there is very little we can do here.
To run lets say mpv installed via flatpak you have to call it using `flatpak run io.mpv.Mpv`

**Comment by Euro20179** [comment]
you could maybe create a file in `/usr/bin/mpv` then in that file have `flatpak run io.mpv.Mpv` and `chmod +x /usr/bin/mpv`

**Comment by ura43** [comment]
There is nothing we can do about this aside from mentioning that in the installation instructions

**Comment by Euro20179** [comment]
If there's no `/usr/bin/mpv` file, then you could create that file with `flatpak run io.mpv.Mpv` in it. (idk how flatpak works though, so the `/usr/bin/mpv` file could already exist)

**Comment by Yaikava** [comment]
Had to hardcore and remove some stuff, but I got it to work with flatpak mpv.

Disabled dep checking and hard coded the player command.

**This is not good enough for an "official solution". But if someone wants to edit it themselves they can.**

This is hard coding the player command. Disabling dep checking should be self explanatory.

![image](https://user-images.githubusercontent.com/83710104/156149865-8e4d3a49-635d-44a4-97ea-9f4a0b44df69.png)

**Comment by ura43** [comment]
> Had to hardcore and remove some stuff, but I got it to work with flatpak mpv.
> 
> Disabled dep checking and hard coded the player command.
> 
> **This is not good enough for an "official solution". But if someone wants to edit it themselves they can.**
> 
> This is hard coding the player command. Disabling dep checking should be self explanatory.
> 
> ![image](https://user-images.githubusercontent.com/83710104/156149865-8e4d3a49-635d-44a4-97ea-9f4a0b44df69.png)

Thank you for sharing. Thats one of the workarounds that I expected.
Equally bad practice, but can you try putting a two line script in your path called mpv that basically runs `flatpak run io.mpv.Mpv` ?
Maybe you can explain why you have so many seemingly redundant options for flatpak run?

**Comment by ura43** [comment]
This is still wontfix, but maybe we can document the workaround. 
I'll close this once we have one that is satisfying

**Comment by ura43** [comment]
That is great news and seems like the preferable workaround for users using the mpv flatpak

**Comment by Yaikava** [comment]
oh yeah, maybe there is one issue. This is my first time using this so I do not know for sure.

I would expect mpv to show the name of the anime, but it does not. Title only has this.
![image](https://user-images.githubusercontent.com/83710104/156155144-8849f161-37aa-429a-bb9f-7f43066d001f.png)

**Comment by ura43** [comment]
Hmm, thats weird. But if thats the biggest issue for an unsupported workaround, thats a good place to be
