### ISSUE TITLE
update process

### ISSUE THREAD

**Issue by Mietek05** [pystardust/ani-cli#488]
**In what category does your enhancement fall? [choose: safety, speed, ux, qa, other]**
convenience

**Status Quo**
the way of installing is a bit wacky, it is copying the script to the binaries directory so whenever you wish to update you have to delete the copy and do it again. it's not intolerable or anything but it's a bit impractical. besides that, the commands for the installation could probably be summed up in a flag just like the updates.

**The Enhancement**
what about using a symbolic link? you may say 'well if you want to use a symlink just do it yourself' but i guess the reason why there's an 'installing' section in the readme is for people who don't exactly know how a program works. i think something like `ani-cli -i` would be cool as well as a flag for uninstalling maybe?

**Additional context**
this can hardly be called an enhancement, i know it's a very superficial suggestion but i think it's comfy.

**Comment by iamchokerman** [comment]
you can already use ```ani-cli -U``` to automatically update the script, and the -i flag is already used for iina, a media player for mac (even though right now it's broken, but we're working on a fix for it). also when it comes to making the installation process easier, a scoop or chocolatey package for windows is already planned. next time you want to update don't remove ani-cli from path, but instead use -U flag

**Comment by ura43** [comment]
To add to @iamchokerman, we tried symlinks in the past and it was a mess. I know symlinking at first glance may be a "cleaner" way to install things, but it's not practical and breaks easily.

The scoop package is already out and installable

**Comment by ura43** [comment]
I read that you mainly complained about the updating process and did so because you were unaware of our somewhat recently added `-U` option.
I'll leave this open a little longer.
Feel free to ask any further questions, or give suggestions to further improve our updating process and documentation
