### ISSUE TITLE
wayland support?

### ISSUE THREAD

**Issue by postfen** [pystardust/ani-cli#49]
works great in x11, but crashes in wayland. not sure if it's an easy fix or impossible, just curious if it will be supported.

by crashes, I mean mpv briefly comes up then closes. I'm assuming it's not getting the information needed to pull a video.

**Comment by grondilu** [comment]
It works for me on Fedora linux 35 workstation edition (Wayland/Gnome 41, ASUS Vivobook 64bits).

**Comment by VexisMorlock** [comment]
Also not having any issues on Fedora 35.  (Wayland/Gnome 41, sandy-bridge i7, gforce 1060)

**Comment by ura43** [comment]
Uhm, how is this an ani-cli issue? 
If anything, open the issue at mpvs repo
