### ISSUE TITLE
Non interactive selection broken

### ISSUE THREAD

**Issue by 71zenith** [pystardust/ani-cli#491]
**Metadata (please complete the following information)**
Version: 1.6.5
OS: Arch
Shell: dash, zsh
Anime: not applicable

**Describe the bug**
When selecting an episode and anime non-interactively, it runs into an error

**Steps To Reproduce**

1. Run `ani-cli -a 10 death note`

**Expected behavior**
It should start playing the episode

**Screenshots (if applicable)**
![15:09:54-04-02](https://user-images.githubusercontent.com/92977828/152506923-ca80b85b-ba78-4ea2-9442-b696e2b4737a.png)

**Comment by margual56** [comment]
This bug stems from _two issues_:
### 1 - Anime selection
As said in the help:
> When selecting non-interactively, the first result will be  selected, if anime is passed

Therefore, the variable `select_first` should be assigned the value `1` if either `-d` or `-p` are passed:
```diff
while getopts 'viq:dp:chDUVa:' OPT; do
     case $OPT in
         h)
             help_text
             exit 0
             ;;
         d)
             is_download=1
+            select_first=1
             ;;
         a)
             ep_choice_to_start=$OPTARG
             ;;
         D)
             : > "$logfile"
             exit 0
             ;;
         p)
             is_download=1
             download_dir=$OPTARG
+            select_first=1
             ;;
         i)
             player_fn="iina"
             ;;
         q)
             .
             .
             .
```
And fixed!

### 2 - Episode selection 
The second issue has to  appears to be in the if from [line 573](https://github.com/pystardust/ani-cli/blob/de022168abd6ef5cb7e73fb39d9d848ee096b7e7/ani-cli#L573), where it is said:
> If the variable `$ep_choice_to_start` is not empty, then set `select_first` to one

Problem is, `select_first` is not used anywhere, the only variable that "matters" is `REPLY`. Therefore, a new if statement could be introduced to check if `$select_first` is set; or alternatively, you could do:
```diff
- [ -n "$ep_choice_to_start" ] && select_first=1
+ if [ -n "$ep_choice_to_start" ] ; then
+     REPLY=1
+     select_first=1
+ fi
```
And it would function normally.


I checked and with those solutions implemented, it works just fine. I took the liberty of creating a pull request solving this issue: #494
