### ISSUE TITLE
Interactive editing of history

### ISSUE THREAD

**Issue by Duoslow** [pystardust/ani-cli#499]
**In what category does your enhancement fall? [choose: safety, speed, ux, qa, other]**
ui ux

**Status Quo**
history system should be done better

**The Enhancement**
To delete only one anime from the history, instead of deleting the entire history or editing the history file by the user. Option to interactive (selective) deletion anime from the history and delete it all should be added.

**Additional context**
It's like the -c option but for interactive deletion  
my english is not good but i hope i could explain 😃

**Comment by ura43** [comment]
Uhm :point_right: :point_left: 
Have you considered just editing the histfile?
On a serious note, this is a really unnecessary feature that would also bloat the code in an unacceptable way.
WONTFIX

**Comment by Raif1** [comment]
Do you know where its in windows ?
