### ISSUE TITLE
[Feature-Request]Ability for episode count to continue where we left off

### ISSUE THREAD

**Issue by palwd8** [pystardust/ani-cli#5]
Would it be possible for ani-cli to select the last episode we were on and play that automatically?

**Comment by pystardust** [comment]
What if we store the history in a file.
Like each anime name with the last episode the user has watched.
So when a user does ani-cli -H
Then we could show the latest episodes of the currently watching anime

**Comment by pal-wal** [comment]
Oh yeah that'd work as well
