### ISSUE TITLE
Add "resume watching" feature, saving the last known timestamp for unfinished episodes

### ISSUE THREAD

**Issue by nxfanaccount** [pystardust/ani-cli#503]
**Is your feature request related to a problem? Please describe.**
No problem. MPV has an option called `--save-position-on-quit` which is really useful to implement a "resume watching" feature.

**Describe the solution you'd like**
Add the option to the mpv call somewhat like this: https://github.com/pystardust/ani-cli/pull/502
Whether it's on by default is up to you of course.

The logfile would also have to be modified, since using `-c` always assumes the last watched episode has been finished, so something like an "unfinished" flag to mark a partially watched episode and a check for that flag in the `history)` case would do the trick.

**Comment by ura43** [comment]
> **Is your feature request related to a problem? Please describe.** No problem. MPV has an option called `--save-position-on-quit` which is really useful to implement a "resume watching" feature.
> 
> **Describe the solution you'd like** Add the option to the mpv call somewhat like this: #502 Whether it's on by default is up to you of course.
> 
> The logfile would also have to be modified, since using `-c` always assumes the last watched episode has been finished, so something like an "unfinished" flag to mark a partially watched episode and a check for that flag in the `history)` case would do the trick.

Wouldn't this work with a sophisticated mpv config?

**Comment by pystardust** [comment]
@nxfanaccount I think this approach maynot work very well.

If you just wanna save your position you could exit mpv with capital Q. Then when you open the same file(url) it would resume playback.
But the problem will occur when the link changes for the anime episode. This is very likely cause these links usually are temporary links which expire in about 12hrs. So adding this feature would not work well unless we mess with a separate timestamp value we store with the anime id and episode. Also implementing this with different players would make it very complex.

**Comment by nxfanaccount** [comment]
> @nxfanaccount I think this approach maynot work very well.
> 
> If you just wanna save your position you could exit mpv with capital Q. Then when you open the same file(url) it would resume playback. But the problem will occur when the link changes for the anime episode. This is very likely cause these links usually are temporary links which expire in about 12hrs. So adding this feature would not work well unless we mess with a separate timestamp value we store with the anime id and episode. Also implementing this with different players would make it very complex.

You make a lot of good points and I can see this would create more trouble than merit. Thanks for clearing it up!

**Comment by nightwolf3140** [comment]
if you use vlc its pretty good about it in my experience
