### ISSUE TITLE
Request to get a RSS feed Intergration

### ISSUE THREAD

**Issue by h4636oh** [pystardust/ani-cli#512]
We still need to check online if we got the new episode out and then open a terminal and watch the anime but if we could enable a RSS feed in this script or i would rather prefer an another script since it will to too bloat we can then wont have to go on web and check if the new episode is released

**Comment by CoolnsX** [comment]
Like this
https://github.com/CoolnsX/and-scripts/blob/main/rss

**Comment by ura43** [comment]
just use newsboat lol

**Comment by z8512** [comment]
> just use newsboat lol

Newsboat can't render image
