### ISSUE TITLE
Not working on Windows 10

### ISSUE THREAD

**Issue by suburbanbourbon** [pystardust/ani-cli#514]
**Metadata (please complete the following information)**
Version: 1.6.7
OS: Windows 10
Shell: Powershell
Anime: N/A

**Describe the bug**
Cannot run ani-cli through Powershell or Powershell 7. I had to add the path to the ani-cli bash script and run it using git bash. And it autocompletes to `ani-cli.ps1`. I have followed the install instructions in the README.md.

**Steps To Reproduce**
1. Run `ani-cli.ps1`

**Expected behavior**
Should show the expected cli

**Screenshots (if applicable)**
![image](https://i.nuuls.com/qWdnJ.png)

**Additional Context**
It works perfectly when I added to path and ran using git bash. Added this to path `C:\Users\Admin\scoop\apps\ani-cli\1.7`

**Comment by RaynardGerraldo** [comment]
> **Metadata (please complete the following information)** Version: 1.6.7 OS: Windows 10 Shell: Powershell Anime: N/A
> 
> **Describe the bug** Cannot run ani-cli through Powershell or Powershell 7. I had to add the path to the ani-cli bash script and run it using git bash. And it autocompletes to `ani-cli.ps1`. I have followed the install instructions in the README.md.
> 
> **Steps To Reproduce**
> 
> 1. Run `ani-cli.ps1`
> 
> **Expected behavior** Should show the expected cli
> 
> **Screenshots (if applicable)** ![image](https://camo.githubusercontent.com/3682efa3c153a5240a8283e33a97a37ab84cb526660119a4c8da6efc764896a1/68747470733a2f2f692e6e75756c732e636f6d2f676661685a2e706e67) ![image](https://camo.githubusercontent.com/a1dffceba280c07f899d609cf22e1f679cbf291e3b9380fccb3a7ceaec174039/68747470733a2f2f692e6e75756c732e636f6d2f7157646e4a2e706e67)
> 
> **Additional Context** It works perfectly when I added to path and ran using git bash. Added this to path `C:\Users\Admin\scoop\apps\ani-cli\1.7`

You dont need to run it as ani-cli.ps1, after installing it per instructions,just type in ani-cli and run it. Can you reinstall it and try again?

**Comment by suburbanbourbon** [comment]
@RaynardGerraldo it still shows me the this
![image](https://i.nuuls.com/qWdnJ.png)

**Comment by RaynardGerraldo** [comment]
> @RaynardGerraldo it still shows me the this ![image](https://camo.githubusercontent.com/577a337ef8ca61d52c774bfd64a3df0dd3d261b7f088d475923873433ade92c8/68747470733a2f2f692e6e75756c732e636f6d2f383262536b2e706e67)

How did you install git bash? Through scoop or .exe?

Can you go to C:\Users\Admin\scoop\shims and paste the contents of ani-cli.cmd here?

**Comment by suburbanbourbon** [comment]
@RaynardGerraldo through the installer. there is no `ani-cli.cmd`. only `scoop.cmd`

**Comment by RaynardGerraldo** [comment]
> @RaynardGerraldo through the installer. there is no `ani-cli.cmd`. only `scoop.cmd` ![image](https://camo.githubusercontent.com/99058c3e6c0c2dbf4c136daa43a1f7a05e29a00b174dc6f795e25c60958b2e49/68747470733a2f2f692e6e75756c732e636f6d2f4a4a374d522e706e67)

Ok can you paste the contents of ani-cli.ps1 ?

**Comment by suburbanbourbon** [comment]
`if (!(Test-Path Variable:PSScriptRoot)) { $PSScriptRoot = Split-Path $MyInvocation.MyCommand.Path -Parent }
$path = join-path "$psscriptroot" "..\apps\ani-cli\current\ani-cli"
if($myinvocation.expectingInput) { $input | & $path  @args } else { & $path  @args }
```

**Comment by RaynardGerraldo** [comment]
> `if (!(Test-Path Variable:PSScriptRoot)) { $PSScriptRoot = Split-Path $MyInvocation.MyCommand.Path -Parent } $path = join-path "$psscriptroot" "..\apps\ani-cli\current\ani-cli" if($myinvocation.expectingInput) { $input | & $path @args } else { & $path @args }`

Uninstall ani-cli,and reinstall ani-cli with -g flag,

`scoop install ani-cli -g`, run this as administrator in powershell

Then re run it again
