### ISSUE TITLE
Unable to view an episode

### ISSUE THREAD

**Issue by suburbanbourbon** [pystardust/ani-cli#515]
**Metadata (please complete the following information)**
Version: 1.6.7
OS: Windows 10
Shell: Git Bash 
Anime: enen-no-shouboutai-ni-no-shou

**Describe the bug**
Only this episode doesn't work the rest seem to work. Shows `Video URL not found`. Was able to replicate it on Termux.

**Steps To Reproduce**

1. Run `ani-cli`
2. Search fire force
3. Choose 4
4. Choose episode 1

**Expected behavior**
Video should play

**Screenshots (if applicable)**
![image](https://i.nuuls.com/h6T6_.png)

**Comment by CoolnsX** [comment]
I checked it.. only the first episode is not working.. rest all the episode is parsing properly

**Comment by iamchokerman** [comment]
please re-open the issue if the problem persists
