### ISSUE TITLE
exit option not working in main menu

### ISSUE THREAD

**Issue by freezboltz** [pystardust/ani-cli#518]

**Comment by iamchokerman** [comment]
?

**Comment by RaynardGerraldo** [comment]
Is this a joke?

**Comment by freezboltz** [comment]
commit hash: 0379eb1f45db2f778d81602f70e1d1ede481aa8e testing is required

**Comment by freezboltz** [comment]
exit option not working

**Comment by iamchokerman** [comment]
can you fill in the issue template that is provided?

**Comment by freezboltz** [comment]
commit hash: 22e1dc5489f4df44df7b52e477c29c89a0c68895
![invalid](https://user-images.githubusercontent.com/58996975/153074185-29d5d0f7-b247-401a-84fd-7c767c499756.png)

**Comment by iamchokerman** [comment]
can you make an actual issue, using the issue template? also, make its title relevant

**Comment by iamchokerman** [comment]
also this is expected behavior

**Comment by iamchokerman** [comment]
if you have an actual issue, fill in the template that's provided and use a relevant title
