### ISSUE TITLE
Illegal number error after successful download

### ISSUE THREAD

**Issue by rbjnazz** [pystardust/ani-cli#522]
Version: v1.7.0
OS: Linux Mint 20.2 uma
Shell: zsh
Anime: one piece

**Output**
``` bash
[#0e6b6f 63MiB/64MiB(98%) CN:1 DL:1.5MiB]
02/10 17:44:36 [NOTICE] Download complete: ./one-piece-674.mp4
Downloaded episode: 674
/usr/local/bin/ani-cli: 632: wait: Illegal number:
```

**Steps To Reproduce**

1. ani-cli -q 480 -d "one piece"
2. Choose 1
3. Choose episode 674

**Note:** Downloaded file had no problem but it produce the file **"a"**

``` bash
a
one-piece-672.mp4
one-piece-673.mp4
one-piece-674.mp4
```

**Comment by Derisis13** [comment]
fixed in #520
