### ISSUE TITLE
Rejected Feature Requests

### ISSUE THREAD

**Issue by justchokingaround** [pystardust/ani-cli#523]
**1. Have a makefile** _#417_ 

**2. Resume playback from timestamp you were at last time** _#503_ 

**3. Change provider** _#383_ 

**4. Editing the hist file** _#499_ 

**5.  RSS feed integration** _#512_ 

**6.  Anilist / MAL sync** _(check out [trackma](https://github.com/z411/trackma))_

**7.  flatpak playersupport** _#484 (workaround available)_

**8.  Adding providers with a different language** _#593_

**9.  Extra options for mpv/vlc (eg. auto-fullscreen)** _#594_,_#598_

**10. Autocomplete** _#859_

**11. Flag for custom external downloader** _#854_

**Comment by ura43** [comment]
8. RSS feed integration

**Comment by Derisis13** [comment]
This should be reconsidered:
1: we did it anyway
6: --dub flag
9: done, default on steamdeck
10: idk if allanime has it, but the option is there if yes
11: possible with custom player function
13: same as 11

**Comment by justchokingaround** [comment]
yep, i updated the text accordingly

**Comment by Derisis13** [comment]
rip longest open issue

**Comment by justchokingaround** [comment]
#i-was-there

**Comment by justchokingaround** [comment]
auto complete sounds kinda interesting, shell completions are not hard to implement, i have a few ideas and resources

**Comment by port19x** [comment]
> rip longest open issue

I figured pinned and closed is a thing, so that's neat.
That way we can get to zero open issues :smile:

**Comment by justchokingaround** [comment]
clean

**Comment by CoolnsX** [comment]
> 7 is already implemented. pls remove it

do you know, you can directly update other's messages?
