### ISSUE TITLE
android termux issues

### ISSUE THREAD

**Issue by Crisp-Casper** [pystardust/ani-cli#526]
I received the error /data/data/com.termux/files/usr/bin/ani-cli: 475: cannot create /data/data/com.termux/files/home/.cache/ani-hsts: Is a directory, this was fixed with a "rm -rf /data/data/com.termux/files/home/.cache/ani-hsts" and script will run however mpv will not (when running mpv i get the error bash: /data/data/com.termux/files/usr/bin/mpv: Permission denied and I don't have super user to fix it)

**Comment by Crisp-Casper** [comment]
> > I received the error /data/data/com.termux/files/usr/bin/ani-cli: 475: cannot create /data/data/com.termux/files/home/.cache/ani-hsts: Is a directory, this was fixed with a "rm -rf /data/data/com.termux/files/home/.cache/ani-hsts" and script will run however mpv will not (when running mpv i get the error bash: /data/data/com.termux/files/usr/bin/mpv: Permission denied and I don't have super user to fix it)
> 
> line 475 issue will be fixed by #527, as for "bash: /data/data/com.termux/files/usr/bin/mpv: Permission denied" can you try `chmod +x /data/data/com.termux/files/usr/bin/mpv`

ther termux chooser opens however on selecting either mpv or vlc

**Comment by Crisp-Casper** [comment]
it crashes the android system... that close was on accident

**Comment by RaynardGerraldo** [comment]
> it crashes the android system... that close was on accident

it crashes after selecting the players?

**Comment by Crisp-Casper** [comment]
> > it crashes the android system... that close was on accident
> 
> it crashes after selecting the player?

I belive i changed a prefix attempting to find a solution after running "rm -rf ani-cli" and re-running the install script it works flawlessly

**Comment by Crisp-Casper** [comment]
thank you very much for your help! very excited to have this on my phone

**Comment by Crisp-Casper** [comment]
is there a way to support this project? I ain't looking to be a part of the team just pay for a coffee lol

**Comment by RaynardGerraldo** [comment]
no problem, you can support ani-cli by simply starring the repo👍

**Comment by ura43** [comment]
> is there a way to support this project? I ain't looking to be a part of the team just pay for a coffee lol

Follow the maintainers, it boosts our ego :)

If you really want to throw money at us, gift discord nitro to a maintainer
