### ISSUE TITLE
Error during installation on macOS

### ISSUE THREAD

**Issue by iamcodernitesh** [pystardust/ani-cli#539]
OS: macOS Monterey 12.2.1
Shell: zsh

**Describe the bug**
Installation issue.
`Error: An exception occurred within a child process:
  RuntimeError: /usr/local/opt/mpv not present or broken`

**Steps To Reproduce**

brew tap iamchokerman/ani-cli
brew install ani-cli

**Expected behavior**
ani-cli should install without any issue.
Note : I tried the same yesterday and it worked without any issue.

**Screenshots :**
![Screenshot 2022-02-15 at 11 46 38 PM](https://user-images.githubusercontent.com/73643989/154124034-cb209109-ee53-4e41-a77e-d07a97dde86e.png)

**Additional context**
MPV is already install using `brew install --cask mpv`

**Comment by iamchokerman** [comment]
can you try ```brew install mpv```without the --cask flag?

**Comment by iamcodernitesh** [comment]
> can you try `brew install mpv`without the --cask flag?

Same issue.
Output:
`Warning: Treating mpv as a formula. For the cask, use homebrew/cask/mpv
Warning: mpv 0.34.1_1 is already installed, it's just not linked.
To link this version, run:
  brew link mpv
`

**Comment by iamchokerman** [comment]
and what about ```brew link mpv```?

**Comment by iamcodernitesh** [comment]
Same as before. But I don't understand why but it's working now.
`brew link mpv`didnot had any effect. mpv was located in `/usr/local/opt/`earlier but it was not identifying it.
