### ISSUE TITLE
403 forbidden due to missing referer

### ISSUE THREAD

**Issue by Crisp-Casper** [pystardust/ani-cli#543]
**Metadata (please complete the following information)**
Version: 1.8.0
OS: [droid]
Shell: termux-bash
Anime: [e.g. flcl] (if applicable) any

**Describe the bug**
video can't be played, I get the error 
Error 1020
Ray ID: 6dfe0c5688927ae3 • 2022-02-19 08:15:35 UTC
Access denied
What happened?

This website is using a security service to protect itself from online attacks.
moving it too Firefox idk if that means anything

**Steps To Reproduce**

1. Run `ani-cli'
2. opens mpv
3. black screen then file selection screen

**Expected behavior**
should play video

**Screenshots**
[image](https://imgur.com/a/pSoQXCJ)
[image](https://imgur.com/a/VDmuG06)

**Additional context**
sorry if this is deemed not yalls problem I just wanna watch my Anime man...

**Comment by Crisp-Casper** [comment]
this is a full install + run attempt for mpv and vlc

https://streamable.com/rvxzzx

**Comment by CoolnsX** [comment]
they put the referer link back for streaming video.. and we cannot pass both video link and referer link to mpv.. cause android problems.. we cannot do much here..

**Comment by ura43** [comment]
Ran into the same issue with ani-sync yesterday

**Comment by Crisp-Casper** [comment]
> they put the referer link back for streaming video.. and we cannot pass both video link and referer link to mpv.. cause android problems.. we cannot do much here.. downloading works though.. so you can download then watch.. :)

so android is kinda fucked? I'll swap references to include -d now thanks

**Comment by CoolnsX** [comment]
> so android is kinda fucked? I'll swap references to include -d now thanks
I saw the video... is your android rooted??

**Comment by Crisp-Casper** [comment]
> > so android is kinda fucked? I'll swap references to include -d now thanks
> 
> I saw the video... is your android rooted??

no I'm afraid the oem is permanently locked

**Comment by stl3** [comment]
Ok, no wonder. This seems to also affect my ytfzf as well. For now, I have to do it the ugly way by doing
```echo 'termux-open --view "$1"' > $PREFIX/bin/mpv```
and then watching it using newpipe or something.

**Comment by Soviena** [comment]
Adding referrer="https://gogoanime.fi" to mpv.conf in android mpv settings work for me

**Comment by iamchokerman** [comment]
@Soviena is right, this is a referrer issue, so just adding referrer="https://gogoanime.fi/" to mpv.conf will fix it. alternatively you can pass that as an mpv argument i.e: ```mpv --referrer="https://gogoanime.fi/" <video_url>``
might be useful to someone for future reference

**Comment by Crisp-Casper** [comment]
> @Soviena is right, this is a referrer issue, so just adding referrer="https://gogoanime.fi/" to mpv.conf will fix it. alternatively you can pass that as an mpv argument i.e: ```mpv --referrer="https://gogoanime.fi/" <video_url>`` might be useful to someone for future reference

pardon my asking but mpv.conf? I can't seem to find it on termux

**Comment by Soviena** [comment]
> pardon my asking but mpv.conf? I can't seem to find it on termux

Not on termux, but in android mpv app setting

**Comment by stl3** [comment]
Open mpv, goto three dots top right->Settings->Advanced-->Edit mpv.conf

**Comment by Crisp-Casper** [comment]
> 

right i found it with @Soviena 's comment can confirm this works! and ig its pretty cool mpv can do that ik vlc can as well by default

**Comment by CoolnsX** [comment]
> right i found it with @Soviena 's comment can confirm this works! and ig its pretty cool mpv can do that ik vlc can as well by default

Vlc doesn't have referrer link option...

**Comment by stl3** [comment]
Would having gogo as the singular referrer in mpv.conf not affect other sites that require referrer usage (I mean outside of ani-cli of course)?

**Comment by ura43** [comment]
> Would having gogo as the singular referrer in mpv.conf not affect other sites that require referrer usage (I mean outside of ani-cli of course)?

It would. If you have other scrapers that need referers, things will get messy

**Comment by ura43** [comment]
Solved with #559
