### ISSUE TITLE
Better resume playback 

### ISSUE THREAD

**Issue by ZastianPretorius** [pystardust/ani-cli#557]
**Is your feature request related to a problem? Please describe.**
Currently how the app is written if you end an episode somewhere in the middle it doesn't know that you didn't finish the episode.

**Describe the solution you'd like**
I am proposing that every second or so run  `playerctl position` to get the current time of the player and save that with the info of the history this will allow us to see if the episode is done or not and when `ani-cli -c` is ran run `playerctl position $time+` to append the time and leave off where we ended.

**Additional context**
I know we don't want to add to many dependencies so we can make it an optional dependency by seeing if there is a printout when running `whereis playerctl`. I can try and add this my self But I am not the best with bash scripting so If you have any pointers that would be amazing.

**Comment by ZastianPretorius** [comment]
The way the ani-hist file is now is for example: bleach 2
What I am proposing is getting the length of the episode with `playerctl metadata --format "{{duration(mpris:length)}}"` then when The episode is about 85% complete only then do we save the hist file with the next episode.  we can also try and save the hist file like: bleach 2 101.20833 (anime episode time)

**Comment by ZastianPretorius** [comment]
I was mostly going off of how other people like Aniyomi handle this. But yea a set time could also be a good Idea.

**Comment by ZastianPretorius** [comment]
> > I would personally set an absolute limit, for a 10+ minute episode a 2 minute ED + epilogue is typical, and for a 2 hours movie to have an 18 minute credit roll is extremely unlikely.

I was thinking how other projects handle this like for example aniyomi there default is 85% but this works as well.

**Comment by ura43** [comment]
This is definitely one of the harder things one could work on, as it would likely require histfile modifications.
I definitely see the value in it, but am skeptical if it will be worth the effort.
Could you elaborate on the needed extra dependencies?
Just playerctl? 
Maybe there is a mpv native workaround

**Comment by ZastianPretorius** [comment]
Yes with player ctl you could track the. Time of the episode. As well as make the player navigate to a specific time. In the loop we can add 
`playerctl position` to track the position of the episode.

And when we start the episode get the position from hist file and running
`playerctl position $position+`
Where `&position` is the time gotten out of the hist file.

**Comment by ZastianPretorius** [comment]
Ill go and look at the man page for mpv and see if there is a work around.

**Comment by ZastianPretorius** [comment]
3 things I found in the man page is 
`--start=<relative time>`

Seek to given time position.

The general format for times is [+|-][[hh:]mm:]ss[.ms]. If the time is prefixed with -, the time is considered relative from the end of the file (as signaled by the demuxer/the file). A + is usually ignored (but see below).

The following alternative time specifications are recognized:

pp% seeks to percent position pp (0-100).

#c seeks to chapter number c. (Chapters start from 1.)

none resets any previously set option (useful for libmpv).

If --rebase-start-time=no is given, then prefixing times with + makes the time relative to the start of the file. A timestamp without prefix is considered an absolute time, i.e. should seek to a frame with a timestamp as the file contains it. As a bug, but also a hidden feature, putting 1 or more spaces before the + or - always interprets the time as absolute, which can be used to seek to negative timestamps (useful for debugging at most).


`--save-position-on-quit`
Always save the current playback position on quit. When this file is played again later, the player will seek to the old playback position on start. This does not happen if playback of a file is stopped in any other way than quitting. For example, going to the next file in the playlist will not save the position, and start playback at beginning the next time the file is played.

This behavior is disabled by default, but is always available when quitting the player with Shift+Q.

 
And
`stream-pos` 
Raw byte position in source stream. Technically, this returns the position of the most recent packet passed to a decoder.

**Comment by ura43** [comment]
> Yes with player ctl you could track the. Time of the episode. As well as make the player navigate to a specific time. In the loop we can add `playerctl position` to track the position of the episode.
> 
> And when we start the episode get the position from hist file and running `playerctl position $position+` Where `&position` is the time gotten out of the hist file.

Could you elaborate on this?
I have now installed playerctl and can't get it to detect mpv when testing with `flcl-dub ep 1`.
`playerctl position` just returns `No players found`
Am I missing an additional dependency?

**Comment by ZastianPretorius** [comment]
Mpv requires `mpv-mpris` plugin I forgot about that vlc will work out of the box.

**Comment by ura43** [comment]
seems not worth it overall, sorry
