### ISSUE TITLE
Episode is not opened in mpv player after its selection

### ISSUE THREAD

**Issue by xlryegor** [pystardust/ani-cli#566]
**Metadata**
Version: v1.9.0 
OS: Android 10 QKQ1.200114.002
Shell: /data/data/com.termux/files/usr/bin/bash
Anime: bleach

**Describe the bug**
The mpv player with the selected episode does not start after the episode is selected.

**Steps To Reproduce**

1. In Termux, run `ani-cli bleach`
2. Choose 1 (bleach)
3. Choose episode 73

**Expected behavior**
The selected episode starts playing in the mpv player.

**Screenshots (if applicable)**
![android_mpv_not_starting](https://user-images.githubusercontent.com/60843251/156754767-56f1e30b-fbfb-4a0a-a804-f6ec4aa3ef0e.jpg)

**Additional context**
1. The issue is reproduced with any anime title / episode I've tried so far.

**Comment by CoolnsX** [comment]
Uploading screen-20220304-204320.mp4…

Working fine with me

**Comment by CoolnsX** [comment]
https://user-images.githubusercontent.com/76195824/156789207-889c3aca-202f-4e9e-916e-6a042da5e1de.mp4

Working fine with me

**Comment by 71zenith** [comment]
@xlryegor did you follow the new install instructions. mpv won't open the url if a referrer link is not passed

**Comment by Huffinator9** [comment]
there is an ongoing issue w/ decryption, from what i can understand. they are working on it and will update.

**Comment by xlryegor** [comment]
> @xlryegor did you follow the new install instructions. mpv won't open the url if a referrer link is not passed

I think I did. Here's a short video including the mpv.conf file

https://user-images.githubusercontent.com/60843251/156820651-5d1d9a9f-d4d2-4ab7-b46e-89f66f272b3c.mp4

**Comment by xlryegor** [comment]
> screen-20220304-204320.mp4
> 
> Working fine with me

Is this some modified version of Termux? Mine is not the same

**Comment by RaynardGerraldo** [comment]
> > @xlryegor did you follow the new install instructions. mpv won't open the url if a referrer link is not passed
> 
> I think I did. Here's a short video including the mpv.conf file
> 
>  demo_mpv_config.mp4

What happens when you type "mpv" ?

**Comment by xlryegor** [comment]
> > > @xlryegor did you follow the new install instructions. mpv won't open the url if a referrer link is not passed
> > 
> > 
> > I think I did. Here's a short video including the mpv.conf file
> > demo_mpv_config.mp4
> 
> What happens when you type "mpv" ?

```
~ $ mpv
usage: am [subcommand] [options]
usage: am start [-D] [-N] [-W] [-P <FILE>] [--start-profiler <FILE>]
               [--sampling INTERVAL] [-R COUNT] [-S]
               [--track-allocation] [--user <USER_ID> | current] <INTENT>
       am startservice [--user <USER_ID> | current] <INTENT>
       am stopservice [--user <USER_ID> | current] <INTENT>
       am broadcast [--user <USER_ID> | all | current] <INTENT>
       am to-uri [INTENT]
       am to-intent-uri [INTENT]
       am to-app-uri [INTENT]

am start: start an Activity.  Options are:
    -D: enable debugging
    -N: enable native debugging
    -W: wait for launch to complete
    --start-profiler <FILE>: start profiler and send results to <FILE>
    --sampling INTERVAL: use sample profiling with INTERVAL microseconds
        between samples (use with --start-profiler)
    -P <FILE>: like above, but profiling stops when app goes idle
    -R: repeat the activity launch <COUNT> times.  Prior to each repeat,
        the top activity will be finished.
    -S: force stop the target app before starting the activity
    --track-allocation: enable tracking of object allocations
    --user <USER_ID> | current: Specify which user to run as; if not
        specified then run as the current user.
    --stack <STACK_ID>: Specify into which stack should the activity be put.
am startservice: start a Service.  Options are:
    --user <USER_ID> | current: Specify which user to run as; if not
        specified then run as the current user.

am stopservice: stop a Service.  Options are:
    --user <USER_ID> | current: Specify which user to run as; if not
        specified then run as the current user.

am broadcast: send a broadcast Intent.  Options are:
    --user <USER_ID> | all | current: Specify which user to send to; if not
        specified then send to all users.
    --receiver-permission <PERMISSION>: Require receiver to hold permission.

am to-uri: print the given Intent specification as a URI.

am to-intent-uri: print the given Intent specification as an intent: URI.

am to-app-uri: print the given Intent specification as an android-app: URI.


<INTENT> specifications include these flags and arguments:
    [-a <ACTION>] [-d <DATA_URI>] [-t <MIME_TYPE>]
    [-c <CATEGORY> [-c <CATEGORY>] ...]
    [-e|--es <EXTRA_KEY> <EXTRA_STRING_VALUE> ...]
    [--esn <EXTRA_KEY> ...]
    [--ez <EXTRA_KEY> <EXTRA_BOOLEAN_VALUE> ...]
    [--ei <EXTRA_KEY> <EXTRA_INT_VALUE> ...]
    [--el <EXTRA_KEY> <EXTRA_LONG_VALUE> ...]
    [--ef <EXTRA_KEY> <EXTRA_FLOAT_VALUE> ...]
    [--eu <EXTRA_KEY> <EXTRA_URI_VALUE> ...]
    [--ecn <EXTRA_KEY> <EXTRA_COMPONENT_NAME_VALUE>]
    [--eia <EXTRA_KEY> <EXTRA_INT_VALUE>[,<EXTRA_INT_VALUE...]]
        (mutiple extras passed as Integer[])
    [--eial <EXTRA_KEY> <EXTRA_INT_VALUE>[,<EXTRA_INT_VALUE...]]
        (mutiple extras passed as List<Integer>)
    [--ela <EXTRA_KEY> <EXTRA_LONG_VALUE>[,<EXTRA_LONG_VALUE...]]
        (mutiple extras passed as Long[])
    [--elal <EXTRA_KEY> <EXTRA_LONG_VALUE>[,<EXTRA_LONG_VALUE...]]
        (mutiple extras passed as List<Long>)
    [--efa <EXTRA_KEY> <EXTRA_FLOAT_VALUE>[,<EXTRA_FLOAT_VALUE...]]
        (mutiple extras passed as Float[])
    [--efal <EXTRA_KEY> <EXTRA_FLOAT_VALUE>[,<EXTRA_FLOAT_VALUE...]]
        (mutiple extras passed as List<Float>)
    [--esa <EXTRA_KEY> <EXTRA_STRING_VALUE>[,<EXTRA_STRING_VALUE...]]
        (mutiple extras passed as String[]; to embed a comma into a string,
         escape it using "\,")
    [--esal <EXTRA_KEY> <EXTRA_STRING_VALUE>[,<EXTRA_STRING_VALUE...]]
        (mutiple extras passed as List<String>; to embed a comma into a string,
         escape it using "\,")
    [-f <FLAG>]
    [--grant-read-uri-permission] [--grant-write-uri-permission]
    [--grant-persistable-uri-permission] [--grant-prefix-uri-permission]
[--debug-log-resolution] [--exclude-stopped-packages]
    [--include-stopped-packages]
    [--activity-brought-to-front] [--activity-clear-top]
    [--activity-clear-when-task-reset] [--activity-exclude-from-recents]
    [--activity-launched-from-history] [--activity-multiple-task]
    [--activity-no-animation] [--activity-no-history]
    [--activity-no-user-action] [--activity-previous-is-top]
    [--activity-reorder-to-front] [--activity-reset-task-if-needed]
    [--activity-single-top] [--activity-clear-task]
    [--activity-task-on-home]
    [--receiver-registered-only] [--receiver-replace-pending]
    [--receiver-foreground] [--receiver-no-abort]
    [--receiver-include-background]
    [--selector]
    [<URI> | <PACKAGE> | <COMPONENT>]

Error: unknown command '--user'
```

**Comment by CoolnsX** [comment]
@xlryegor it seems u install it from pkg... uninstall it if u dont use it.. and run this in terminal
```
echo 'am start --user 0 -a android.intent.action.VIEW -d "$2" -n is.xyz.mpv/.MPVActivity' > $PREFIX/bin/mpv
chmod +x $PREFIX/bin/mpv
```

**Comment by CoolnsX** [comment]
you have done everything right.. so it seems to be android problem..

**Comment by RaynardGerraldo** [comment]
> > > > @xlryegor did you follow the new install instructions. mpv won't open the url if a referrer link is not passed
> > > 
> > > 
> > > I think I did. Here's a short video including the mpv.conf file
> > > demo_mpv_config.mp4
> > 
> > 
> > What happens when you type "mpv" ?
> 
> ```
> ~ $ mpv
> usage: am [subcommand] [options]
> usage: am start [-D] [-N] [-W] [-P <FILE>] [--start-profiler <FILE>]
>                [--sampling INTERVAL] [-R COUNT] [-S]
>                [--track-allocation] [--user <USER_ID> | current] <INTENT>
>        am startservice [--user <USER_ID> | current] <INTENT>
>        am stopservice [--user <USER_ID> | current] <INTENT>
>        am broadcast [--user <USER_ID> | all | current] <INTENT>
>        am to-uri [INTENT]
>        am to-intent-uri [INTENT]
>        am to-app-uri [INTENT]
> 
> am start: start an Activity.  Options are:
>     -D: enable debugging
>     -N: enable native debugging
>     -W: wait for launch to complete
>     --start-profiler <FILE>: start profiler and send results to <FILE>
>     --sampling INTERVAL: use sample profiling with INTERVAL microseconds
>         between samples (use with --start-profiler)
>     -P <FILE>: like above, but profiling stops when app goes idle
>     -R: repeat the activity launch <COUNT> times.  Prior to each repeat,
>         the top activity will be finished.
>     -S: force stop the target app before starting the activity
>     --track-allocation: enable tracking of object allocations
>     --user <USER_ID> | current: Specify which user to run as; if not
>         specified then run as the current user.
>     --stack <STACK_ID>: Specify into which stack should the activity be put.
> am startservice: start a Service.  Options are:
>     --user <USER_ID> | current: Specify which user to run as; if not
>         specified then run as the current user.
> 
> am stopservice: stop a Service.  Options are:
>     --user <USER_ID> | current: Specify which user to run as; if not
>         specified then run as the current user.
> 
> am broadcast: send a broadcast Intent.  Options are:
>     --user <USER_ID> | all | current: Specify which user to send to; if not
>         specified then send to all users.
>     --receiver-permission <PERMISSION>: Require receiver to hold permission.
> 
> am to-uri: print the given Intent specification as a URI.
> 
> am to-intent-uri: print the given Intent specification as an intent: URI.
> 
> am to-app-uri: print the given Intent specification as an android-app: URI.
> 
> 
> <INTENT> specifications include these flags and arguments:
>     [-a <ACTION>] [-d <DATA_URI>] [-t <MIME_TYPE>]
>     [-c <CATEGORY> [-c <CATEGORY>] ...]
>     [-e|--es <EXTRA_KEY> <EXTRA_STRING_VALUE> ...]
>     [--esn <EXTRA_KEY> ...]
>     [--ez <EXTRA_KEY> <EXTRA_BOOLEAN_VALUE> ...]
>     [--ei <EXTRA_KEY> <EXTRA_INT_VALUE> ...]
>     [--el <EXTRA_KEY> <EXTRA_LONG_VALUE> ...]
>     [--ef <EXTRA_KEY> <EXTRA_FLOAT_VALUE> ...]
>     [--eu <EXTRA_KEY> <EXTRA_URI_VALUE> ...]
>     [--ecn <EXTRA_KEY> <EXTRA_COMPONENT_NAME_VALUE>]
>     [--eia <EXTRA_KEY> <EXTRA_INT_VALUE>[,<EXTRA_INT_VALUE...]]
>         (mutiple extras passed as Integer[])
>     [--eial <EXTRA_KEY> <EXTRA_INT_VALUE>[,<EXTRA_INT_VALUE...]]
>         (mutiple extras passed as List<Integer>)
>     [--ela <EXTRA_KEY> <EXTRA_LONG_VALUE>[,<EXTRA_LONG_VALUE...]]
>         (mutiple extras passed as Long[])
>     [--elal <EXTRA_KEY> <EXTRA_LONG_VALUE>[,<EXTRA_LONG_VALUE...]]
>         (mutiple extras passed as List<Long>)
>     [--efa <EXTRA_KEY> <EXTRA_FLOAT_VALUE>[,<EXTRA_FLOAT_VALUE...]]
>         (mutiple extras passed as Float[])
>     [--efal <EXTRA_KEY> <EXTRA_FLOAT_VALUE>[,<EXTRA_FLOAT_VALUE...]]
>         (mutiple extras passed as List<Float>)
>     [--esa <EXTRA_KEY> <EXTRA_STRING_VALUE>[,<EXTRA_STRING_VALUE...]]
>         (mutiple extras passed as String[]; to embed a comma into a string,
>          escape it using "\,")
>     [--esal <EXTRA_KEY> <EXTRA_STRING_VALUE>[,<EXTRA_STRING_VALUE...]]
>         (mutiple extras passed as List<String>; to embed a comma into a string,
>          escape it using "\,")
>     [-f <FLAG>]
>     [--grant-read-uri-permission] [--grant-write-uri-permission]
>     [--grant-persistable-uri-permission] [--grant-prefix-uri-permission]
> [--debug-log-resolution] [--exclude-stopped-packages]
>     [--include-stopped-packages]
>     [--activity-brought-to-front] [--activity-clear-top]
>     [--activity-clear-when-task-reset] [--activity-exclude-from-recents]
>     [--activity-launched-from-history] [--activity-multiple-task]
>     [--activity-no-animation] [--activity-no-history]
>     [--activity-no-user-action] [--activity-previous-is-top]
>     [--activity-reorder-to-front] [--activity-reset-task-if-needed]
>     [--activity-single-top] [--activity-clear-task]
>     [--activity-task-on-home]
>     [--receiver-registered-only] [--receiver-replace-pending]
>     [--receiver-foreground] [--receiver-no-abort]
>     [--receiver-include-background]
>     [--selector]
>     [<URI> | <PACKAGE> | <COMPONENT>]
> 
> Error: unknown command '--user'
> ```

can you try this instead?

`echo 'am start -n is.xyz.mpv/.MPVActivity "$2"' > $PREFIX/bin/mpv`

`chmod +x $PREFIX/bin/mpv`

**Comment by xlryegor** [comment]
@RaynardGerraldo, thank you! I've tried your script and now it works like charm.

I think I'll try installing termux from scratch following the guide in 'readme' once again. Then, I'll write a comment about how it went and close the issue. This way it will benefit the people who may encounter the same problem in the future, I suppose.

**Comment by xlryegor** [comment]
@RaynardGerraldo , @CoolnsX one more question for you, guys.

As far as I get it, you both suggested almost the same script, but still they differ. Would you mind explaining to me briefly how your scripts differ (what do they do exactly in terms of the current issue) ?

**Comment by RaynardGerraldo** [comment]
> @RaynardGerraldo , @CoolnsX one more question for you, guys.
> 
> As far as I get it, you both suggested almost the same script, but still two scripts differ from one another. Would you mind explaining to me briefly how your scripts differ (what do they do exactly in terms of the current issue) ?

The only difference is that i removed  ` --user 0 -a android.intent.action.VIEW -d` which was somehow broken for you,this is probably caused by a broken termux installation,sorry I cant really go down to the details because I myself dont really know why its happening. @CoolnsX may have an answer

**Comment by CoolnsX** [comment]
Every smartphone has its own way of handling request between apps.... so somethings working on one android doesn't mean that it will work on another one.... 
Also which termux version r u running??

**Comment by xlryegor** [comment]
> Every smartphone has its own way of handling request between apps.... so somethings working on one android means that it may(may not) work on another one.... Also which termux version r u running??..type in termux `termux-info` And send the ss

```
~ $ termux-info
Application version:
0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://grimler.se/termux-packages-24/ stable main
Updatable packages:
All packages up to date
Android version:
10
Kernel build information:
Linux localhost 4.14.117-perf-gf905233 #1 SMP PREEMPT Mon Jul 19 17:26:28 CST 2021 aarch64 Android
Device manufacturer:
Xiaomi
Device model:
Redmi Note 8T
```

**Comment by edl2** [comment]
I am getting this same problem, I am making the selection, yet no mpv window is showing up. Does ani-cli have a conflict with the dwm swallow patch or is this something else? Is there anyway to fix this?

**Comment by xlryegor** [comment]
> I am getting this same problem, I am making the selection, yet no mpv window is showing up. Does ani-cli have a conflict with the dwm swallow patch or is this something else? Is there anyway to fix this?

Have you tried the scripts above?

**Comment by CoolnsX** [comment]
> I am getting this same problem, I am making the selection, yet no mpv window is showing up. Does ani-cli have a conflict with the dwm swallow patch or is this something else? Is there anyway to fix this?

U taking about mpv not working on your PC right??

**Comment by xlryegor** [comment]
@CoolnsX, I've tried reinstalling termux and do everything from scratch. It works. I suppose my initial problem was that I've run this script 
```
echo 'am start -n is.xyz.mpv/.MPVActivity "$2"' > $PREFIX/bin/mpv

chmod +x $PREFIX/bin/mpv
```
BEFORE installing the mpv app. I guess the current issue can be closed now.

**Comment by CoolnsX** [comment]
> BEFORE installing the mpv app. I guess the current issue can be closed now.

we can't because @edl2 is still having problems.. can't close until he gives the reply

**Comment by ura43** [comment]
> I am getting this same problem, I am making the selection, yet no mpv window is showing up. Does ani-cli have a conflict with the dwm swallow patch or is this something else? Is there anyway to fix this?

reopen if you have further issues.

@CoolnsX as a good rule of thumb, if the user doesn't respond in 1-2 days you can close the issue
