### ISSUE TITLE
Taiga Naming support

### ISSUE THREAD

**Issue by Mrbroggle** [pystardust/ani-cli#569]
**Is your feature request related to a problem? Please describe.**
File names don't work with taiga

**Describe the solution you'd like**
make file work with taiga or have an option to make file names work with taiga using format of
"name of anime"  - "episode number"
for example 
Jusjutsu Kaisen - 001

**Describe alternatives you've considered**
Maybe a script could work that removes dashes and dub name and adds dash between episode number

**Additional context**
link for taiga
https://taiga.moe/

**Comment by Derisis13** [comment]
This is not something we want to spend time developing. Either implement it yourself, ask the developers of taiga to support more naming conventions or just use a bulk rename tool like this one: https://github.com/Jim-Shaddix/bulkrename

**Comment by ura43** [comment]
Just to give further context before closing, this would not be a one line fix.
We would need to go out of our way and actively rename downloaded files.
In essence, just use a bulk renaming tool

**Comment by vvirtues** [comment]
I know this is old, but what if I preferred to stream titles instead of downloading them?
