### ISSUE TITLE
scoop install ani-cli -g; "Couldn't find manifest for 'ani-cli'."

### ISSUE THREAD

**Issue by hi-im-aj** [pystardust/ani-cli#570]

**Comment by ura43** [comment]
You probably just forgot to add the extra bucket

**Comment by hi-im-aj** [comment]
> You probably just forgot to add the extra bucket

Thank you 😄

**Comment by FireTonnor** [comment]
What platform are you installing it on

**Comment by FireTonnor** [comment]
@hi-im-aj

**Comment by hi-im-aj** [comment]
> What platform are you installing it on

Windows 10

**Comment by Woolton** [comment]
Im getting this issue when trying to reinstall, I already have the bucket https://i.imgur.com/mvF5sQD.png

**Comment by Woolton** [comment]
Solutions: uninstall and reinstall the extras bucket
