### ISSUE TITLE
Episode doesn't open Windows 10 / Linux

### ISSUE THREAD

**Issue by Breach344** [pystardust/ani-cli#572]
**Metadata (please complete the following information)**
Version: 1.9.0
OS: Windows 10
Shell: /bin/bash
Anime: Bleach

**Describe the bug**
When attempting to start an episode no tab is opened starting it despite it saying "Currently playing bleach episode 1/366".
It does this for all shows and episodes I try.

**Steps To Reproduce**

1. `ani-cli`
2. `bleach`
3. `1`
4. `1`

**Expected behavior**
Starts playing episode

**Additional context**
In case it matters I am mainly attempting to run in Kali Linux. Was having same issue in Windows. I have all dependencies installed. I have tried running `chmod +x ani-cli` with no difference. When I run `mpv` it returns:
mpv 0.34.1 Copyright © 2000-2021 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
FFmpeg library versions:
   libavutil       56.70.100
   libavcodec      58.134.100
   libavformat     58.76.100
   libswscale      5.9.100
   libavfilter     7.110.100
   libswresample   3.9.100
FFmpeg version: 4.4.1-3

Usage:   mpv [options] [url|path/]filename

Basic options:
 --start=<time>    seek to given (percent, seconds, or hh:mm:ss) position
 --no-audio        do not play sound
 --no-video        do not play video
 --fs              fullscreen playback
 --sub-file=<file> specify subtitle file to use
 --playlist=<file> specify playlist file

 --list-options    list all mpv options
 --h=<string>      print options which contain the given string in their name

**Comment by Breach344** [comment]
MIGHT have found the issue. Tried actual using running a youtube video with the mpv to test it and it returned: "error: XDG_RUNTIME_DIR not set in the environment." I used `echo $DISPLAY` and it returns nothing. It's just blank. If there's a fix for that maybe it'll fix this problem with ani-cli for Kali Linux.

**Comment by ura43** [comment]
This is likely to be a misconfiguration on your part.
Please keep us updated

**Comment by Breach344** [comment]
Going to close this issue as I don't believe it is a problem with ani-cli. Made another thread with mpv and another site to see what people had to say and it seems to actually be an issue with my operating system no one knows how to fix. If I find a solution I may come back for an update in case anyone else with the issue ends up here but I'm kinda giving up for now. Most likely solution: buy a new computer.

**Comment by 3301n** [comment]
Are you running kali linux in a virutal environment??
