### ISSUE TITLE
The quality option doesn't work.

### ISSUE THREAD

**Issue by TedMcRamp** [pystardust/ani-cli#575]
**Metadata (please complete the following information)**
Version: 1.9.1
OS: Artix linux
Shell: bash (correction)
Anime: aot

**Describe the bug**
when trying to use a certain quality (like 360) it always defaults to best quality across some animes

**Steps To Reproduce**

1. Run `ani-cli -q 360 (or another quality)`
2. Choose onepiece (or any anime)
3. Choose episode 1 (or any episode)

**Expected behavior**
plays in 360
**what actually happend**
plays in best quality

**Comment by 71zenith** [comment]
I don't face the same problem with one piece. Any anime (for e.g. ousama-ranking) which doesn't have a 360p link, will show an error message that it defaulted to best quality

**Comment by ura43** [comment]
Can't reproduce.
Selecting the first attack on titan, I get 360p just as expected.
