### ISSUE TITLE
Just works in home bin folder

### ISSUE THREAD

**Issue by Fmert24** [pystardust/ani-cli#576]
![Screenshot_20220309-223349_Termux](https://user-images.githubusercontent.com/89682488/157520707-87e356df-8272-4a44-b900-85859f58eda5.jpg)
why its only working in bin folder ı already set the path for home bin folder to??

**Comment by CoolnsX** [comment]
type ```which ani-cli``` in termux

**Comment by Fmert24** [comment]
u0_a3160@localhost ~> which ani-cli
/data/data/com.termux/files/usr/bin/ani-cli

**Comment by Fmert24** [comment]
> type `which ani-cli` in termux

Thanks I'm banging my head on the wall saying why didn't I think of this

**Comment by CoolnsX** [comment]
Type ```echo $PATH```

**Comment by Fmert24** [comment]
> Type `echo $PATH`
I solved problem 

u0_a3160@localhost ~> echo $PATH
/data/data/com.termux/files/usr/bin /data/data/com.termux/files/home/bin

**Comment by CoolnsX** [comment]
Path should be defined like this
![Screenshot_20220310-013000-041](https://user-images.githubusercontent.com/76195824/157524094-a974d914-b25e-4d1f-b4fb-5a53abb96f57.png)

**Comment by Fmert24** [comment]
> Path should be defined like this ![Screenshot_20220310-013000-041](https://user-images.githubusercontent.com/76195824/157524094-a974d914-b25e-4d1f-b4fb-5a53abb96f57.png)

Fishs path puts an empty space betwen when echoed so coment section wraps it around and bash path is
u0_a3160@localhost ~ [1]> bash
~ $ echo $PATH
/data/data/com.termux/files/usr/bin:/data/data/com.termux/files/home/bin:/data/data/com.termux/files/home/bin
