### ISSUE TITLE
Rapid resume skips menu

### ISSUE THREAD

**Issue by Derisis13** [pystardust/ani-cli#577]
**Metadata (please complete the following information)**
Version: 1.9.1
OS: Pop!_OS 21.10
Shell: dash
Anime: any

**Describe the bug**
rapid resume quits after playing the episode

**Steps To Reproduce**

1. have one unfinished anime in history
2. run ani-cli -c
3. no menu appears, program quits

**Expected behavior**
menu should have been displayed to navigate the script

**Screenshots (if applicable)**
![image](https://user-images.githubusercontent.com/66648475/157759723-fb20a084-7c6e-4fa5-aa3a-27913480cb5f.png)

**Additional context**
Sorry for not testing the feature at all beforehand, but this is still pretty embarrassing, unless if this is how it's supposed to work (this case it's only embarrassing for me)

**Comment by ura43** [comment]
Thats exactly the expected behaviour :sweat_smile: 

One could argue about exiting after the episode has played, but I think thats preferable

**Comment by ura43** [comment]
Because that perfectly suits my anime "workflow" of watching one ep per day
