### ISSUE TITLE
Download error: unrecognised URI (v2 branch)

### ISSUE THREAD

**Issue by CubeyAlchemist** [pystardust/ani-cli#580]
**Metadata (please complete the following information)**
Version: V2.0.0
OS: Linux Mint 20.2 Cinnamon
Shell: /bin/bash
Anime: Arpeggio of Blue Steel, Log Horizon (that i've tested)

**Describe the bug**
When attempting to download episodes from the above two titles, it reports an exception (see screenshot).
```
Exception caught
Exception: [download_helper.cc:451] errorCode=1 Unrecognized URI or unsupported protocol: 16
Download failed episode 002 , please retry or check your internet connection
```
All episodes of these two anime titles report the exact same error. Have not tried other titles as of yet.

**Steps To Reproduce**

1. Run `ani-cli -d log horizon` / `ani-cli -d arpeggio`
2. Choose episodes `1 25` / `1 12`

**Expected behavior**
Downloading should work

**Screenshots (if applicable)**
![image](https://user-images.githubusercontent.com/8694934/158058468-ee28e9d4-1946-4e7b-aac0-1c209a886cf9.png)

**Additional context**
I updated to the v2 branch to resolve the cryptography issue I was having, but I am no longer able to download episodes from these anime titles. On the master branch, I was able to download episodes 2-12 of the Arpeggio of Blue Steel without issue - only Ep.1 was problematic due to the crypto issue.

**Comment by Derisis13** [comment]
How do you think it relates to #567? It appears to be the same issue, with possibly different frequencies of occurance...

**Comment by Derisis13** [comment]
> How do you think it relates to #567? It appears to be the same issue, with possibly different frequencies of occurrence...

I did some investigating and I was wrong. I'm getting vidstreaming links but download still doesn't work. The same referrer works for mpv so I don't quite understand why it doesn't work. 
It might very well be that gog*play has an extra layer of defence against downloads (or even aria2 specifically?) that gog*anime has not. 
It would be worth trying to replace aria2 with ffmpeg that mpv uses.

**Comment by CoolnsX** [comment]
It's the human bug in script.. I will discuss about it with other maintainers...
