### ISSUE TITLE
Wrong error when episode isn't released

### ISSUE THREAD

**Issue by Crisp-Casper** [pystardust/ani-cli#582]
**Metadata (please complete the following information)**
Version: 1.9.1
OS: arch BTW
Shell: bash
Anime: one piece

**Describe the bug**
cant watch episode 590 

Getting data for episode 590
bad decrypt
140021041857792:error:0606506D:digital envelope routines:EVP_DecryptFinal_ex:wrong final block length:crypto/evp/evp_enc.c:599:
base64: invalid input
bad decrypt
139696369562880:error:0606506D:digital envelope routines:EVP_DecryptFinal_ex:wrong final block length:crypto/evp/evp_enc.c:599:

**Steps To Reproduce**

1. Run `ani-cli "one piece"`
2. select 4 (one piece dub)
3. enter episode 590

**Expected behavior**
should work

**Screenshots (if applicable)**

![Screenshot_~ : fish_1](https://user-images.githubusercontent.com/88099085/158127454-11afc59b-ff52-46d9-b1f1-c03edcf085e7.png)

**Additional context**
love ani-cli <3

**Comment by Crisp-Casper** [comment]
the pull request "https://github.com/pystardust/ani-cli/pull/581" (fix:cryptography issue) does not fix the problem
![Screenshot_ani-cli : fish_1](https://user-images.githubusercontent.com/88099085/158129360-89489c0e-acd4-4576-8289-bb629377fa2a.png)
 sorry i tried

**Comment by CoolnsX** [comment]
```One piece Dub ep 590``` doesn't exist in gogoanime site.. so there is no link...

**Comment by Derisis13** [comment]
It's still a problem, it should display "episode not yet released" message if the page doesn't exist

**Comment by CoolnsX** [comment]
> It's still a problem, it should display "episode not yet released" message if the page doesn't exist

It exists in non-dub anime.. but not in dubbed one
