### ISSUE TITLE
Download is broken??? I think...or I am dumb.

### ISSUE THREAD

**Issue by Reaper176** [pystardust/ani-cli#583]
**Metadata (please complete the following information)**
Version: 1.9.1
OS: garuda linux aka arch
Shell: fish
Anime: [e.g. flcl] (if applicable)

**Describe the bug**
Download is broken.
When using the commands ani-cli -d 'animename' it just selects the first season and asks what episode I would like to start on, if I do ani-cli 'animename' -d it will ask prompt for what season but instead of downloading it will also just start playing it.

**Steps To Reproduce**

1. Run `ani-cli -d animename`
OR
2. Run 'ani-cli animename -d

**Expected behavior**
for 1 it should prompt the season followed by asking the episode range and start downloading
for 2 it should prompt the season followed by asking the episode range and start downloading

**Screenshots (if applicable)**

This is very odd to me, this had been working until I did ani-cli -U. Also when did they change it to "ani-cli animename -D" almost nothing commonly uses that. Is it a windows thing. I feel like that's a windows thing.

**Comment by Reaper176** [comment]
OK. I am about to smart way outside of my IQ so stand back there is going to be smoke. 

We don't need to change from aria2c. Aria2c has the option to download the file parts and then combine them. 
1. Download the m3u8 file.
- I suggest a simple wget. This will give you a file with the .m3u8 format.
2. Call aria2c with the -i flag and the files name.
- IE "aria2c -i 345nnfi-skdnbt-sneinsld.m3u8"
- This will download all the stream parts.
3.You need to make a list of all these files so do
```
print "file '%s'\n" *.ts > fukin.txt 
```
4. Take the output file fukin.txt and do
```
ffmpeg -f concat -i fukin.txt -c copy fukin.ts
```
5. Now do 
```
ffmpeg -i fukin.ts -acodec copy -vcodec copy fukin.mp4
```
And that's all you need to do to get a fukin.mp4 out of gogoanime. 


I have no idea how to do it but I am sure that someone else can dink with it. 
note that this works in bash. some other shells have fucked up rules so they might not work with those commands as written. 
also, note that I have not the slightest clue how to actually program it to do all that.
also, also, note that any other way might be better.
also, also, also, note that this could have all been written for no reason as aria2c is supposed to be getting something going with proper .m3u8 downloads so...yeah

**Comment by CoolnsX** [comment]
#567

**Comment by Reaper176** [comment]
yeah...but ffmpeg as a downloader instead of area2c.....I mean I could ram a flag poll up my own ars to go poll-vaulting but I would rather have someone build me a ladder.

**Comment by Reaper176** [comment]
Yeah but if you are going to switch to ffmpeg as the downloader you might as well just extract the URL and use XDM to download it as an mp4 to start with.

**Comment by Reaper176** [comment]
Could also pass the link to yt-dlp.
