### ISSUE TITLE
quality setings are not sported or something?

### ISSUE THREAD

**Issue by Fmert24** [pystardust/ani-cli#585]
**Metadata (please complete the following information)**
Version: v1.9.2
OS: Android
Shell: fish
Anime: arifureta-shokugyou-de-sekai-saikyou-2nd-season 

**Describe the bug**
Nothing downloading and last message number keep increasing

**Steps To Reproduce**

1. Run `ani-cli -dq360`
2. Choose 2 (fooly-cooly)
3. Choose episode 1

**Expected behavior**
Downloading should work

**Additional context**
![Screenshot_20220316-162534_Termux](https://user-images.githubusercontent.com/89682488/158600109-f62f9a20-7f1d-4652-aeab-f90b63ab2078.jpg)

**Comment by 71zenith** [comment]
Update to the latest version

**Comment by Fmert24** [comment]
> Update to the latest version

I checked Updated and problem remains Version: 1.9.2

**Comment by 71zenith** [comment]
Can you show the error this time?

**Comment by Fmert24** [comment]
> Can you show the error this time?

I just typed vrong version on meta data part ı just fixed now 
That screen shot is from version 1.9.2 not 1.2.9

**Comment by Fmert24** [comment]
> This seems like a dependency issue. do you have them all installed and at the latest version? Try running `pkg up` to update all installed packages (in termux)

checking dependencies
Looks like I have uninstalled openssl

**Comment by Fmert24** [comment]
thank you for all your help (no pun)

**Comment by Fmert24** [comment]
Getting data for episode 5
Current video quality is not available (defaulting to best quality)
Downloading episode 5 ...
[tls @ 0xf2a56020] An unexpected TLS packet was received.
    Last message repeated 123 times
[hls @ 0xf2a38600] Error when loading first segment 'https://a01-g-naver-vod.pstatic.net/grafolio/c/read/v2/VOD_ALPHA/grafolio_2022_03_11_14/hls/fd526b6a-a0e3-11ec-bafd-625f9a4201fc-000000.ts?__gda__=1647454323_0a245d0efc1cb6c43bbb8db26c29e78c'
https://peliscdn.net/travis/a4cc76a6cd1984e2635e6c1180879025/playlist.m3u8: Immediate exit requested
u0_a3160@localhost ~ [1]> ani-cli -dq360 arif

**Comment by Derisis13** [comment]
You know that there are more versions of openssl in termux? The one you need is `openssl-tool`
