### ISSUE TITLE
Video URL not found

### ISSUE THREAD

**Issue by dusklight00** [pystardust/ani-cli#592]
**Version:** v1.6.7
**OS:** Windows 10
**Shell:** bash
**Anime:** death note, your name, naruto and many more

When I search for an anime, it always fails at the last step, when it is extracting the video links with an error "Video URL not found"

**Steps To Reproduce**

1. Run `ani-cli`
2. Search `your name` or `death note` or `naruto`
3. Choose the any anime from the result (in my case I chosed `kimi-no-na-wa`)
4. Choose episode 1 (or any episode)

**Expected behavior**
It should get the video-link and start playing it

**Screenshots**
![image](https://user-images.githubusercontent.com/71203637/159194518-d1872271-cb44-4f14-8c37-158420243c6e.png)

**Additional context**
Maybe there is some changes in the gogo-anime download page.

**Comment by ZastianPretorius** [comment]
You have an old version of ani-cli. Update to 1.9.2

**Comment by dusklight00** [comment]
Yes, my bad, my version was running behind. Updating ani-cli solved it. Thank Zastian for your time!
