### ISSUE TITLE
Make Available On Other Media Players

### ISSUE THREAD

**Issue by createvi** [pystardust/ani-cli#595]
**Describe the solution you'd like**
Please Make The Animes available to play on other media players (option to choose which media player to use)

**Describe alternatives you've considered**
VLC Media Player, MPlayer And Others

**Comment by ZastianPretorius** [comment]
It is available with vlc if you look at `ani-cli -h` it will show you that there is an option `ani-cli -v` to open it in vlc instead of mpv. Also if you want to change it even more you can look at line 491 `player_fn="mpv"` change mpv to whatever and see if it works.

**Comment by createvi** [comment]
Well i get "command not found" when i type "ani-cli" in terminal. anyway i changed the code as you said and it works

**Comment by ZastianPretorius** [comment]
Then `ani-cli` is not in your PATH. If you cant run it by just typing `ani-cli`. Don't know what OS you're running so that is as far as I can help. But in the readme the instructions for all the supported OS's are there.

**Comment by createvi** [comment]
OS = Manjaro Linux
I Can Run It By Going To The Directory And Running ./ani-cli and it works i just don't have a command called ani-cli

**Comment by createvi** [comment]
I deleted and installed through yay. now here can i edit the default media player. that file

**Comment by ArekkusuMagni** [comment]
This issue should be closed. More of a troubleshooting/tutorial situation than a issue.
