### ISSUE TITLE
Can't Play Any Anime In VLC Media Player

### ISSUE THREAD

**Issue by createvi** [pystardust/ani-cli#596]
**Metadata (please complete the following information)**
Version: 1.9.0 
OS: Manjaro Linux KDE Plasma 64 Bit
Shell: zsh
Anime: All

**Describe the bug**
When i start ani-cli with `ani-cli -v` i get the intractive terminal where i can search and play anime but i need to play it in VLC Media Player instead of mpv but when i start any anime the VLC opens and don't show anything. i am not able to watch any Anime. I Can Watch in mpv.

**Steps To Reproduce**

1. Run `ani-cli -v`
2. Search For Any Anime (In My Case Naruto)
3. Choose Any Episode 

**Expected behavior**
I Should Be Able To Play It In VLC Media Player But I can't

**Screenshots (if applicable)**
https://i.imgur.com/f9BhwHN.png

**Comment by ura43** [comment]
![2022-04-01-142824_2099x1736_scrot](https://user-images.githubusercontent.com/82055622/161263351-dd304701-ac65-4e03-98a0-30ce1255b5a6.png)

can't reproduce

**Comment by ura43** [comment]
At least on v2 branch

**Comment by ura43** [comment]
Nope, works on master too

**Comment by ura43** [comment]
You're running 1.9.0, please reopen the issue if your problem persists, especially with the hopefully soon to be released v2 branch

**Comment by createvi** [comment]
I Updated `ani-cli` to `1.9.3` and it still don't play it.
[Screen Record](https://imgur.com/QLxfZoW)

**Comment by createvi** [comment]
Anyone Have Any idea How To Fix This?

**Comment by Derisis13** [comment]
Which version of vlc do you have?
Also you can run the script with `sh -x /usr/local/bin/ani-cli` and see if you find anything of interest there

**Comment by ura43** [comment]
> I Updated `ani-cli` to `1.9.3` and it still don't play it. [Screen Record](https://imgur.com/QLxfZoW)

You may also want to update to the new 2.0.2
Sometimes bugs magically disappear
