### ISSUE TITLE
not working on i3wm Ubuntu 20.04

### ISSUE THREAD

**Issue by kevinmaxihu** [pystardust/ani-cli#599]
**Metadata (please complete the following information)**
Version: 1.9.2
OS: Ubuntu 20.04
Shell: zsh
Anime: suisei-no-gargantia

media player window start and not playing anything, then close by itself.

**Steps To Reproduce**

1. ./ani-cli
2. gargantia
3. 2

**Expected behavior**
Anime should Play

**Comment by iamchokerman** [comment]
what's your output of ./ani-cli -V ?

**Comment by kevinmaxihu** [comment]
it's `1.9.2`

**Comment by iamchokerman** [comment]
update to 1.9.3 with `sudo ani-cli -U`

**Comment by kevinmaxihu** [comment]
i updated and am now at `2.0.2` and it still not working i sill got a window opening with the anime name dot mpv then after three second widow goes off. may this because im on i3wm ?
