### ISSUE TITLE
Problem setting up in windows. Help

### ISSUE THREAD

**Issue by deveshk103** [pystardust/ani-cli#60]
Whenever I am trying to make it, it throws me some error.
![Screenshot 2021-10-18 232653](https://user-images.githubusercontent.com/66843808/137782769-97e13ce2-d236-49cb-af99-038e1df51d0b.png)
Please look into the matter.

**Comment by deveshk103** [comment]
If I need to install a wsl then there's no point making this version.

**Comment by asciiden** [comment]
Hey, I believe this is because you don't have a .cache folder under /c/Users/deves/

Try running the following to create the directory:
```
mkdir /c/Users/deves/.cache
```

Try running ani-cli again
```
./ani-cli
```

**Comment by FayneAldan** [comment]
> I am running the original script (not windows fork) and it works just fine. The steps are below to make it work. Try this once.

That's what I did btw. I installed MPV using Scoop so it's automatically added to path. However, I'm using WSL (which btw is incredibly easy to install and doesn't require a VM 🙂) and had to add `.exe` to the mpv path at the top. I also added an `ani-cli.bat` that just runs `bash ani-cli %*` so I can run the command from Windows. c:

**Comment by LemonJuicer96** [comment]
> > I am running the original script (not windows fork) and it works just fine. The steps are below to make it work. Try this once.
> 
> That's what I did btw. I installed MPV using Scoop so it's automatically added to path. However, I'm using WSL (which btw is incredibly easy to install and doesn't require a VM 🙂) and had to add `.exe` to the mpv path at the top. I also added an `ani-cli.bat` that just runs `bash ani-cli %*` so I can run the command from Windows. c:

@FayneAldan I tried doing that but mpv doesn't start for me when using ani-cli. Works if I try to play a file manually though.

**Comment by FayneAldan** [comment]
Are you able to open MPV from WSL Bash by typing mpv.exe?
