### ISSUE TITLE
Gogo got new keys again *sigh*

### ISSUE THREAD

**Issue by Vincent-A-Rage** [pystardust/ani-cli#600]
**Metadata (please complete the following information)**
Version: [1.9.2]
OS: [ Windows 10 ]
Shell: [usr/bin/bash]
Anime: [Demon slayer]
**Describe the bug**
wont play video
it says "
base64: invalid input
bad decrypt
24832:error:0606506D:digital envelope routines:EVP_DecryptFinal_ex:wrong final block length:../openssl-1.1.1m/crypto/evp/evp_enc.c:599:
Video URL not found"

**Steps To Reproduce**

1. Run `ani-cli demon slayer`
2. Choose 1 (Kimetsu no yaiba)
3. Choose episode 7

**Expected behavior**
episode should play

**Screenshots (if applicable)**
![unknown](https://user-images.githubusercontent.com/102579027/160552763-61c679ba-0cf2-4f4e-87d4-814b5df6ef52.png)

**Additional context**

**Comment by JediEthan** [comment]
Just got the bug on Steins Gate. Once I tried to watch episode 8, none of the other episodes worked and it returned the same error. No other anime will work as well.

**Comment by 71zenith** [comment]
So, I can't play any anime not just demon slayer

**Comment by grigoriynikolaev** [comment]
Same here.

**Comment by ura43** [comment]
Fix is available at animdl, now we port it to shell

**Comment by nightser727** [comment]
same for me

**Comment by ura43** [comment]
Update, fix is merged.
