### ISSUE TITLE
No video link found

### ISSUE THREAD

**Issue by Sakibul706** [pystardust/ani-cli#602]
**Metadata**
Version: ani-cli v`1.9`
OS: arch Linux
Shell: Bash

**Describe the bug**
base64: invalid input
bad decrypt
F834CA3974000000:error:1C80006B:Provider routines:ossl_cipher_generic_block_final:wrong final block length:providers/implementations/ciphers/ciphercommon.c:429:
Video URL not found

Every time I I wanna play any anime this comes up. Yesterday morning it was working fine but after 12 in the morning it is not working. My friend also got the same issue. I don't know it's a problem only for us.

**Comment by CoolnsX** [comment]
It seems u r using old version of ani-cli... Latest version is 1.9.3
Update it by typing ```sudo ani-cli -U```

**Comment by Sakibul706** [comment]
My bad. I installed Ani cli with yay it installed a older version

**Comment by nkone** [comment]
The window 10 version I installed via scoop is still 1.9. I've tried reinstalled and update but it's stuck at the 1.9 ver.
