### ISSUE TITLE
bad decrypt

### ISSUE THREAD

**Issue by dave-vd** [pystardust/ani-cli#607]
**Metadata (please complete the following information)**
Version: 1.9.0
OS: arch linux with openbox
Shell: zsh
Anime: all but started with one piece episode 986

**Describe the bug**
Getting data for episode 986 
bad decrypt
140608626788160:error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt:crypto/evp/evp_enc.c:610:
base64: invalid input
bad decrypt
139855608080192:error:0606506D:digital envelope routines:EVP_DecryptFinal_ex:wrong final block length:crypto/evp/evp_enc.c:599:
Video URL not found

**Steps To Reproduce**

1. Run ani-cli
2. type one piece
3. select 1 for subbed episodes
4. Choose episode 986
5. (but i have this problem with any anime and every episode since yesterday)

**Expected behavior**
should play the episode

**Screenshots (if applicable)**

**Additional context**
i downloaded ani-cli from the aur

**Comment by mrfluffy-dev** [comment]
`ani-cli -U` you are running an old version

**Comment by dave-vd** [comment]
then i get this
File /usr/bin/ani-cli is read-only; trying to patch anyway
patch: **** Can't create temporary file /usr/bin/ani-cli.ouNO3Gz : Permission denied
Can't update for some reason!

**Comment by dave-vd** [comment]
nvm sry sudo xp

**Comment by mrfluffy-dev** [comment]
`sudo ani-cli -U`

**Comment by dave-vd** [comment]
thx it works fine now :D
