### ISSUE TITLE
VIDEO URL not found 

### ISSUE THREAD

**Issue by Narchy666** [pystardust/ani-cli#608]
**Metadata (please complete the following information)**
Version: 1.5.0
OS: Arch Linux
Shell: Bash
Anime: Any

**Describe the bug**
Downloading is broken.
Can't get VIDEO URL'S

**Expected behavior**
Get The video URL and open it with mpv

**Screenshots (if applicable)**
![Screenshot_906](https://user-images.githubusercontent.com/86563312/161112462-51c18fb6-b606-4285-9c69-19f7b5d56be7.png)
ontent.com/82055622/151030428-2e78d15f-4ba9-4d86-b6f3-8307557b4b29.png)

**Comment by mrfluffy-dev** [comment]
Your version is super old please run `ani-cli -U` if you get permission error use sudo. If the -U option doesn't exist then uninstall ani-cli and reinstall it.
