### ISSUE TITLE
"bad decrypt error, Video URL not found"

### ISSUE THREAD

**Issue by Gokurockx9** [pystardust/ani-cli#610]
Version: 1.9.3.
  OS: Windows 11 Build 20000.556
  Shell: git Bash
 Anime: Steins;Gate

Upon selecting any episode, it gives a bad decrypt error and it's unable to find the URL to the video. It was working a few days ago. 

Steps to reproduce is to select any episode, just as you normally would, to stream using mpv using Windows 11.

![Screenshot 2022-03-31 193248](https://user-images.githubusercontent.com/61856572/161166224-187c1465-f1cb-446e-a66a-aaac7511fd14.png)

**Comment by vishal2376** [comment]
Getting same error in Ubuntu 20.04

**Comment by HaibaoM55** [comment]
me too, but in windows 10

**Comment by NotYasho** [comment]
same issue on Manjaro, tried reinstalling and deleting the config files, nothing changed. Any fixes?

**Comment by NotYasho** [comment]
Solved it by updating to the latest version with the command
```console
sudo ani-cli -U
```

**Comment by ura43** [comment]
Keep this one open for at least a few more days so we don't get more unnecessary duplicates

**Comment by YuleTomalin** [comment]
Tried `scoop status` to see what the problem was. 
It says that **"aria2"** is outdated. Tried updating and reinstalling it, it's already in the latest version and it still didn't work. Any chance for a fix? Tried on both Powershell and Git Bash.

**Comment by mexicancrisp** [comment]
based on earlier comment, `ani-cli -U` on Windows 10 in git bash worked for me as well

**Comment by THEGOLDENPRO** [comment]
> Tried `scoop status` to see what the problem was. It says that **"aria2"** is outdated. Tried updating and reinstalling it, it's already in the latest version and it still didn't work. Any chance for a fix? Tried on both Powershell and Git Bash.
> 
> Edit: `ani-cli -U` on Windows 10/11 using Git Bash w/ Admin Privileges worked for me.

Thank you, that worked

**Comment by ArekkusuMagni** [comment]
After adding sudo to ani-cli -U it was update & fixed for me.

**Comment by HaibaoM55** [comment]
> After adding sudo to ani-cli -U it was updated & fixed for me. 

For windows is ./ani-cli -U

**Comment by GetDeleted20454** [comment]
> Solved it by updating to the latest version with the command
> 
> ```
> sudo ani-cli -U
> ```

I love you <3
