### ISSUE TITLE
An automatic version check

### ISSUE THREAD

**Issue by rakusan2** [pystardust/ani-cli#615]
**Is your feature request related to a problem? Please describe.**
As PR #601 has shown, the keys can change and as Issue #610 has shown, this is something that the users should be informed about.
To solve this, there should be an automatic version check 

**Describe the solution you'd like**
Possible ways to go about it:
- Same as the current update mechanism, but done every start with a prompt for an update if there is any
- [Latest Release](https://docs.github.com/en/rest/reference/releases#get-the-latest-release) API request
  - if `"tag_name"` does not match the version number, then prompt the user and run the standard update function
  - Benefit is a smaller download size if there is no change

This can be done either:
- Every run
  - Can be limited to once an hour
- When decryption fails

**Describe alternatives you've considered**
- Mention this issue in the readme with a request to update
- Check if decryption failed and ask the user to check for updates

**Comment by ura43** [comment]
> **Is your feature request related to a problem? Please describe.** As PR #601 has shown, the keys can change and as Issue #610 has shown, this is something that the users should be informed about. To solve this, there should be an automatic version check
> 
> **Describe the solution you'd like** Possible ways to go about it:
> 
> * Same as the current update mechanism, but done every start with a prompt for an update if there is any
> * [Latest Release](https://docs.github.com/en/rest/reference/releases#get-the-latest-release) API request
>   
>   * if `"tag_name"` does not match the version number, then prompt the user and run the standard update function
>   * Benefit is a smaller download size if there is no change
> 
> This can be done either:
> 
> * Every run
>   
>   * Can be limited to once an hour
> * When decryption fails
> 
> **Describe alternatives you've considered**
> 
> * Mention this issue in the readme with a request to update
> * Check if decryption failed and ask the user to check for updates

I am highly sceptical of this. If at all, I'd see prompting the user to check github on decrypt fail as an okay option
