### ISSUE TITLE
Manual option -M "everything you need to know"

### ISSUE THREAD

**Issue by TommiRommi** [pystardust/ani-cli#616]
adds a new option -M that prints out the entire table of context.
[ani-cli.zip](https://github.com/pystardust/ani-cli/files/8403511/ani-cli.zip)

**Comment by Derisis13** [comment]
Submit your code like it's written here:
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request
