### ISSUE TITLE
Can't play anime with Termux

### ISSUE THREAD

**Issue by createvi** [pystardust/ani-cli#620]
OS - Android 11
Device - Realme
ani-cli Version - 2.0.2
Termux Version - 0.118.0
MPV Version - 2022-03-23 release

**Issue**
Can't play any anime using termux.
When plying an anime it says `No file given, exiting`.

**How to reproduce**
Play any anime using Termux.

**Comment by stl3** [comment]
When you installed, did you remember to `Add referrer="https://gogoanime.fi" to mpv.conf (Open mpv app, goto three dots top right->Settings->Advanced-->Edit mpv.conf)`?
Also, what is the contents of your `$PREFIX/bin/mpv` file?

**Comment by CoolnsX** [comment]
@createvi run this command
```sh
echo 'am start --user 0 -a android.intent.action.VIEW -d "$1" -n is.xyz.mpv/.MPVActivity' > $PREFIX/bin/mpv
```
And then try..
