### ISSUE TITLE
Termux errors when launching ep

### ISSUE THREAD

**Issue by stl3** [pystardust/ani-cli#623]
**Metadata (please complete the following information)**
OS: Termux on Android 

Application version:
0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://grimler.se/termux-packages-24/ stable main
# x11-repo (sources.list.d/x11.list)
deb https://dl.kcubeterm.com/termux-x11 x11 main
Updatable packages:
All packages up to date
Android version:
9
Kernel build information:
Linux localhost 4.4.111-21737876 #1 SMP PREEMPT Thu Jul 15 19:28:19 KST 2021 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-N950F

Shell: zsh
ani-cli: 2.0.2
Anime: Berserk

**Describe the bug**
A few errors are popping up with the latest update. Playing brings 1 error, and "q" pops up 2
When playing an ep
`ani-cli:  334:  [: Illegal number:`
Note: The episode still played
When quitting
`ani-cli:  592: te_ep_list: not found`
`ani-cli:  595: Syntax error: "else" unexpected`

**Steps To Reproduce**

1. Run `ani-cli -q 1080`
2. Type in `Berserk`
3. Select `(1) Berserk (episode 25)` from the list
4. Choose episode 1
5. Go back to Termux, select `q` to quit

**Expected behavior**
Playing the episode and quitting should not bring up any errors

**Screenshots (if applicable; you can just drag the image onto github)**
![SmartSelect_20220404-132037_Termux.jpg](https://user-images.githubusercontent.com/32008952/161481148-ccc17122-0961-4463-b0d4-c2128d471467.jpg)

**Additional context**
I cannot reproduce the 2nd issue when I quit Termux, it seemed random. I tried replaying my file like the steps in pic but it did not reoccur.

**Comment by CoolnsX** [comment]
There is no line no. 592 and 595.. exist in Ani-cli l...
Last line number is 591🙂
Did u change something in ani-cli??

**Comment by CoolnsX** [comment]
Also there is no te_ep_list variable in script..

**Comment by stl3** [comment]
I'll have to recheck, thanks for reminding me I might have done something but off the top of my head I usually rename the file. I had also just ran `ani-cli -U` when this issue popped up after the file was updated/replaced

**Comment by stl3** [comment]
I haven't refreshed the file yet, but it seems that te_ep_list belonged to part of line 584 in my ani-cli  which is `generate_ep_list`
I just fetched a fresh ani-cli and it is still doing the same thing. both updated versions have 592 lines, which version is your ani-cli?

**Comment by CoolnsX** [comment]
Oo.. that pops up when u don't specify range.. it can be ignored.. like last ep no.. it's fine.. though u said script is working fine even with that message..

**Comment by stl3** [comment]
Ah, yeah, it seems pretty much just cosmetic and doesn't seem to impact the playing at all. I shall just ignore it then, thank you :)
