### ISSUE TITLE
Black screen on Media Player and shut down itself

### ISSUE THREAD

**Issue by kevinmaxihu** [pystardust/ani-cli#624]
**Metadata (please complete the following information)**
OS: Ubuntu 20.04
Shell: zsh
Anime: shingeki

**Describe the bug**
player window open and stay black for a while then disapear.

**Steps To Reproduce**

1. Run `./ani-cli`
2. Enter `Shingeki`
3. Choose 1
4. Choose Episode 1

**Expected behavior**
Player should play my anime

**Screenshots (if applicable; you can just drag the image onto github)**

**Additional context**
Version is `2.0.2`
im on i3 (Windows Manager for linux)

**Comment by iamchokerman** [comment]
did you follow the install instructions properly? do you understand what you're doing by running ./ani-cli?

**Comment by Derisis13** [comment]
I'd also be interested of the full output of `mpv --version`

**Comment by kevinmaxihu** [comment]
yes sure this is the output
```➜  ~ mpv --version
mpv 0.33.0 Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
 built on Thu Nov 26 06:59:44 UTC 2020
FFmpeg library versions:
   libavutil       56.60.100
   libavcodec      58.112.103
   libavformat     58.64.100
   libswscale      5.8.100
   libavfilter     7.90.100
   libswresample   3.8.100
FFmpeg version: git-2020-11-22-9208b72```

**Comment by kevinmaxihu** [comment]
yo, what's goin' on ? nobody's gonna help ?

**Comment by CoolnsX** [comment]
We need more info.. cause it's working fine for us...

**Comment by kevinmaxihu** [comment]
[](url
![screenshot-2022-04-13-11:17:40](https:
![screenshot-2022-04-13-11:18:09](https://user-images.githubusercontent.com/51885296/163144297-a3fa84d3-8be6-46dc-a742-c88b3dc6f60c.png)
//user-images.githubusercontent.com/51885296/163144278-38880183-12d5-4332-979d-b6642d8f239a.png)
)

**Comment by kevinmaxihu** [comment]
also if you can tell me what is your's environnement like version of ubuntu, your windows manager ?

**Comment by CoolnsX** [comment]
i use arch with bspwm...

**Comment by iamchokerman** [comment]
mac os with amethyst for me

**Comment by port19x** [comment]
arch, debian stable, debian arm64 unstable with awesomewm

**Comment by port19x** [comment]
reclassifying as a support ticket, but happy to help

**Comment by port19x** [comment]
Feel free to reopen if you still need help
