### ISSUE TITLE
Video URL not found 

### ISSUE THREAD

**Issue by mohamadali-halwani** [pystardust/ani-cli#628]
**Metadata (please complete the following information)**
Version: [1.8.0]
OS: [Debian 11 Bullseye ]
Shell: [zsh]
Anime: [all] 

**Describe the bug**
Downloading is broken. No episodes are being fetched. saying that the url not found.

**Steps To Reproduce**

1. Run `ani-cli `
2. Choose 2 (boruto) for example
3. Choose episode 1

**Expected behavior**
Downloading should work

**Here's a screen shot**
![image](https://user-images.githubusercontent.com/68155980/162060872-5c9f7c40-4fcb-4a14-8490-e6b95cf517bf.png)

**Comment by mrfluffy-dev** [comment]
`ani-cli -U` you are running an old version
