### ISSUE TITLE
mpv black screen, closes itself on android

### ISSUE THREAD

**Issue by qube-03** [pystardust/ani-cli#629]
**Metadata (please complete the following information)**
Version: 2.0.2
OS: Android 12 / Samsung Galaxy S20 FE
Shell: bash / termux
Anime: all, tested with One Piece

**Describe the bug**
mpv doesnt play any video and stays on a black screen. After some time the window will close itself and return to termux.

**Steps To Reproduce**

1. Run `ani-cli`
2. Search for an Anime
3. Choose an Anime and an Episode
4. Let it (not) play

**Expected behavior**
The Video should play in the mpv window

**Screenshots (if applicable; you can just drag the image onto github)**
https://user-images.githubusercontent.com/92535344/162064455-9e93619b-0336-482a-a27b-d0bad6f01a50.mp4

**Additional context**
I followed the steps of installing mpv and ani-cli properly and my mpv config also has referrer="https://gogoplay5.com" in it. changing it to gogoplay4 doesnt change anything.

**Comment by CoolnsX** [comment]
Wait for it.. mpv-android takes time to buffer..

**Comment by ntford** [comment]
I am experiencing the same issue on a galaxy tab 7. MPV player closes instantly. Please let me know If I can supply information to help.

**Comment by CoolnsX** [comment]
Run this first... And then run the script again....
```echo 'am start --user 0 -a android.intent.action.VIEW -d "$1" -n is.xyz.mpv/.MPVActivity' > $PREFIX/bin/mpv```

**Comment by ntford** [comment]
That fixed the issue for me. Thanks!

**Comment by qube-03** [comment]
nope, for me it still stays a blackscreen and eventually crashes.

**Comment by THEGOLDENPRO** [comment]
> Run this first... And then run the script again.... `echo 'am start --user 0 -a android.intent.action.VIEW -d "$1" -n is.xyz.mpv/.MPVActivity' > $PREFIX/bin/mpv`

thank you, that fixed it for me

**Comment by CoolnsX** [comment]
> nope, for me it still stays a blackscreen and eventually crashes.

Maybe a problem on ur side.. like some permission problems...

**Comment by Derisis13** [comment]
Is the device rooted by chance?

**Comment by qube-03** [comment]
nope, however i removed most things google with adb, including play services

**Comment by port19x** [comment]
@CoolnsX feel free to reclassify this as a support ticket since your fix seemed to work for multiple users.
Android support will always be a bit weird
