### ISSUE TITLE
Considering alternative platforms to discord

### ISSUE THREAD

**Issue by port19x** [pystardust/ani-cli#631]
![2022-04-07-143250_1272x758_scrot](https://user-images.githubusercontent.com/82055622/162200244-92267643-a42b-49b0-83e3-fa3a5fe7b169.png)

Yeah, this just happened.
After falsely flagging me as a potential spammer, I just got locked out of my account.
Discords incompetence is baffeling. Just send me that damn verification code instead of just pretending to.
I'm unsure if I want to open another one.

For now, and more relevant to us, who became the server owner?
I'd prefer chokerman as the owner, but maybe KR got it because he was the first to join the server.

I'll take this opportunity to touch some grass

**Comment by iamchokerman** [comment]
you're still the owner

**Comment by RaynardGerraldo** [comment]
^ 
yup

**Comment by iamchokerman** [comment]
gg

**Comment by iamchokerman** [comment]
![Screenshot_20220407-173631_Gmail.jpg](https://user-images.githubusercontent.com/44473782/162237819-5f927533-6c77-4551-abd5-4fe79d2f8582.jpg)

**Comment by iamchokerman** [comment]
it looks looks i have admin permissions

**Comment by iamchokerman** [comment]
actually no, i don't have admin permissions. i have everything except admin

**Comment by port19x** [comment]
The maintainer role has all permissions except admin, priority speaker (idk, weird thing), and a third one I forgot.
I'll contact discord support sooner or later, just don't expect me to be back tomorrow

**Comment by iamchokerman** [comment]
yep, except there is no 3rd one, its all the permissions possible, except admin and priority speaker

**Comment by port19x** [comment]
I'll send them an email this evening

**Comment by CoolnsX** [comment]
We r missing u...

**Comment by port19x** [comment]
Just sent the email.
Since the contents are all public knowledge, I might as well share what I wrote:
![2022-04-13-220611_1750x1124_scrot](https://user-images.githubusercontent.com/82055622/163261495-3b3db538-a6c6-4d5c-b913-06b01a69798d.png)

Now we wait. I hope not for too long

**Comment by port19x** [comment]
![reeee](https://user-images.githubusercontent.com/82055622/163262922-3a891881-80b6-4747-96a3-5642aa9ea5ae.png)

**Comment by port19x** [comment]
![2022-04-13_22-16](https://user-images.githubusercontent.com/82055622/163263048-9de23438-9701-4b6f-9c66-ad5cd5e06410.png)

Selected the wrong category. frustrating experience

**Comment by port19x** [comment]
lets check "missing/delayed emails" "hacked account" could also be promising as an entry point to get my account back

**Comment by iamchokerman** [comment]
discord :)

**Comment by port19x** [comment]
@iamchokerman You know you're the admin of a certain matrix channel

**Comment by port19x** [comment]
Bridging at least the more important channels seems like a worthwhile investment of time. 
Matrix gives you real security and privacy as opposed to the hand holding BS security that made discord lock me out of my own account.

I can't exactly say I miss discord. I wasted a lot more time than I should idleing and chatting in various channels of our server. But sure, we need some line of more direct communication.
Having some plattform redundancy additionally provides some protection against discord wiping us out because we're dirty pirates or sth

**Comment by port19x** [comment]
for now I have gotten through clyde and am awaiting review of my request by a human.
I'm rather pessimistic and unhappy with the whole situation

**Comment by port19x** [comment]
Of course a matrix bridge isn't our only option. I'm open to alternatives

**Comment by iamchokerman** [comment]
> @iamchokerman You know you're the admin of a certain matrix channel

ye so i am admin of ani-cli general, but there's also ani-cli support which im not admin of. as for matrix bridging i've never tried it before, so i'll try to look into it, see what can be done. i'll also study alternatives in the upcoming days, will keep u updated here

**Comment by iamchokerman** [comment]
i'm also not expecting much from discord when it comes to the server and ur account, tbh

**Comment by iamchokerman** [comment]
currently taking a look at [https://github.com/revoltchat/revolt](https://github.com/revoltchat/revolt)

**Comment by iamchokerman** [comment]
[https://app.revolt.chat/invite/8KQYT0ah](https://app.revolt.chat/invite/8KQYT0ah)

**Comment by FireTonnor** [comment]
To be honest I think we should just move the discord server to another platform or just make our own

**Comment by iamchokerman** [comment]
hence this discussion

**Comment by port19x** [comment]
I have joined the revolt for now

**Comment by relejek** [comment]
> currently taking a look at https://github.com/revoltchat/revolt

Why are you considering a totally new platform when we already have a channel on matrix, plus it could be bridged with discord when it gets back to normalcy. what does revolt has that matrix doesn't?

**Comment by port19x** [comment]
> what does revolt has that matrix doesn't?

Good UI / UX that closely resembles that of discord

**Comment by port19x** [comment]
I have used both matrix (element) and discord extensively.
Matrix bridging is non-trivial, but @iamchokerman is looking into it and it does sound like a viable solution

**Comment by port19x** [comment]
renaming the issue

**Comment by iamchokerman** [comment]
i believe for matrix bridging you need to be "admin" on the discord server but i might be wrong

**Comment by port19x** [comment]
:grimacing:

**Comment by FireTonnor** [comment]
guys i was think can we move the server to guilded

**Comment by FireTonnor** [comment]
if you have any question about guilded you can text me in discord

**Comment by port19x** [comment]
> if you have any question about guilded you can text me in discord

On that note: still haven't heard back from those guys.
So no, I for one can't text you on discord

**Comment by FireTonnor** [comment]
Guilded is like discord I can share my screen on YouTube and you can see what guilded looks like or you can watch a video about guilded on YouTube https://youtu.be/zRu_NtpLqT4

**Comment by FireTonnor** [comment]
@port19x

**Comment by FireTonnor** [comment]
I like Martix and Revolt but it your choice @port19x

**Comment by port19x** [comment]
> Guilded is like discord I can share my screen on YouTube and you can see what guilded looks like or you can watch a video about guilded on YouTube https://youtu.be/zRu_NtpLqT4

I will. No need to rush a choice, I haven't heard back from discord yet

**Comment by port19x** [comment]
Guilded is focussed way to heavily on gaming.
Guilded is propietary.
Guilded is slow.
Guilded has a ton of channel types that would be useful ... if I was running a ctf team and not moderating a support server.
calendar, scheduling, docs, lists, all very useful but not for us.
Guilded is off the table

**Comment by iamchokerman** [comment]
agreed

**Comment by port19x** [comment]
> agreed

come online on revolt pls

**Comment by FireTonnor** [comment]
I had a discord account once that was disabled for some reason that i do not remember i went to contact discord about 3 years ago about my account that i lost it has been more then 3 years and they still have not contacted me the only thing i was doing with the discord account was playing some games so i have moved on from my old account and created a new one i hope you understand that @port19x will probable not get his account back

**Comment by whinee** [comment]
I also have an account disabled on discord, but I know some of you might already know why so I won't talk about it in this comment. What's important though is the fact that I appealed the disablement of my account to discord exactly 1 month after it had been disabled, and I got a reply within that day containing the following statement:

> To protect our users' privacy and security, we're only able to discuss account details with the email associated with that account. Unfortunately, we aren't able to locate an account with the email address you're currently writing in from. If you're referring to an account associated with a different email address, please send us a new ticket through that other email address instead.
> 
> Furthermore, please note that all data associated with deleted accounts are deleted or anonymized 14-30 days after beginning the deletion process for that account. If you delete your own account or if your account was disabled for a violation of our [Terms of Service](https://discordapp.com/terms) and [Community Guidelines](https://discordapp.com/guidelines), we'd have no record of that account existing.

How unlucky of me. In any case, the retrieval of @port19x' discord account is slim at this point.

**Comment by port19x** [comment]
I opened this ticket minutes after my account got disabled, so who I still have 5 days worst case.
But tbh I'm not really actively fighting to get it back.
Dislike that plattform anyway and I'll take any excuse I can get to get away from it

**Comment by YusufKhan-gamedev** [comment]
Just use irc

**Comment by iamchokerman** [comment]
not noob friendly

**Comment by YusufKhan-gamedev** [comment]
> not noob friendly

heh?

**Comment by iamchokerman** [comment]
if only you could see what the support channel looks like on discord

**Comment by relejek** [comment]
ani-cli has noob friendly interface thanks to you all. IRC doesn't have that. Some of us don't  mind which platform you devs use, as long as community-admins here are willing to bridge those chat-groups with matrix chat-group. Thank you for taking this in consideration.

**Comment by iamchokerman** [comment]
we will bridge our next platform, unfortunately that is currently impossible to do with discord since the owner is banned, and nobody has admin perms

**Comment by YusufKhan-improves-shit** [comment]
> ani-cli has noob friendly interface thanks to you all. IRC doesn't have that. Some of us don't mind which platform you devs use, as long as community-admins here are willing to bridge those chat-groups with matrix chat-group. Thank you for taking this in consideration.

Libera chat webchat anyone?!?!?!?!

Very simple!

**Comment by port19x** [comment]
> > ani-cli has noob friendly interface thanks to you all. IRC doesn't have that. Some of us don't mind which platform you devs use, as long as community-admins here are willing to bridge those chat-groups with matrix chat-group. Thank you for taking this in consideration.
> 
> Libera chat webchat anyone?!?!?!?!
> 
> Very simple!

sometimes too simple makes things harder again.
Yes, IRC would be the simplest solution, but then we loose virtually all features under the sun

**Comment by port19x** [comment]
IRC and Matrix should be very easy to bridge, so we could offer it anyway

**Comment by Spaxly** [comment]
Revolt and IRC is great alternatives

**Comment by port19x** [comment]
![lesgo](https://user-images.githubusercontent.com/82055622/164194088-0945d56c-b8cc-4ab1-b941-ca2a93e5153f.png)

**Comment by iamchokerman** [comment]
ayo, no way
discord brain moment?!
(i can't believe it)

**Comment by FireTonnor** [comment]
Lucky I have got no email from them

**Comment by port19x** [comment]
![2022-04-20_15-28](https://user-images.githubusercontent.com/82055622/164241360-f305ad6c-ab21-4a66-950f-3c6a9388b89c.png)

Guess who is getting no mail again

**Comment by brahmkshatriya** [comment]
Coping be like

**Comment by iamchokerman** [comment]
oh no

**Comment by iamchokerman** [comment]
@port19x managed to bridge matrix and discord, it doesn't require admin on discord…my bad, i probably did smtg wrong on my first try. anw, can we host a new ani-cli space so that we can have admin on matrix, and add more rooms there?

**Comment by whinee** [comment]
Bridging introduces some problems. Some of them are users who circumvent blocks.

Well, you could argue that there are a plethora of extensions that could negate that. That effort though should be placed on something important such as enjoying life. Unfortunately, I do not have that kind of privilege, and I am too lazy to do it.

Switching to another application just to put your mind at rest? That's too much effort.

Rejoice, as this snowflake of a femboy will leave the app's discord support guild if this is the chosen alternative.

**Comment by port19x** [comment]
> @port19x managed to bridge matrix and discord, it doesn't require admin on discord…my bad, i probably did smtg wrong on my first try. anw, can we host a new ani-cli space so that we can have admin on matrix, and add more rooms there?

Just ping the current admin, he seems to be on every once in a while
A new space would be more trouble than it's worth

**Comment by port19x** [comment]
> Bridging introduces some problems. One of them are users who circumvent blocks.
> 
> Well, you could argue that there are a plethora of extensions that could negate that. That effort though should be placed on something important such as enjoying life. Unfortunately, I do not have that kind of privilege, and I am too lazy to do it.
> 
> Switching to another application just to put your mind at ease? Too much effort.
> 
> Rejoice, as this snowflake of a femboy will leave the app's support Discord guild.

I understood only half of that, but I don't really care about the occasional spammer. or people doing ban evasion. I'm glad stuff is getting bridged.

Would an additional bridge to revolt or maybe irc for important channels be worth the trouble?
If not I don't mind making a matrix account again

**Comment by whinee** [comment]
> I understood only half of that
Oh, no problems. Just doing a lil' bit of nonsense ranting. In any case, the bridge is definitely a-okay.

**Comment by iamchokerman** [comment]
> > @port19x managed to bridge matrix and discord, it doesn't require admin on discord…my bad, i probably did smtg wrong on my first try. anw, can we host a new ani-cli space so that we can have admin on matrix, and add more rooms there?
> 
> Just ping the current admin, he seems to be on every once in a while A new space would be more trouble than it's worth

ye

**Comment by iamchokerman** [comment]
> > Bridging introduces some problems. One of them are users who circumvent blocks.
> > Well, you could argue that there are a plethora of extensions that could negate that. That effort though should be placed on something important such as enjoying life. Unfortunately, I do not have that kind of privilege, and I am too lazy to do it.
> > Switching to another application just to put your mind at ease? Too much effort.
> > Rejoice, as this snowflake of a femboy will leave the app's support Discord guild.
> 
> I understood only half of that, but I don't really care about the occasional spammer. or people doing ban evasion. I'm glad stuff is getting bridged.
> 
> Would an additional bridge to revolt or maybe irc for important channels be worth the trouble? If not I don't mind making a matrix account again

irc x discord bridging should be okay, but idk about revolt briding, not sure it's even a thing yet, will look into it

**Comment by iamchokerman** [comment]
this looks like it should be okay to setup
[https://github.com/ServerNetBot/revoltdiscordbridge](https://github.com/ServerNetBot/revoltdiscordbridge)

also, i am highly in favor of keeping the revolt server alive, since it's a good project that i'd like to support, and hopefully it'll grow bigger

**Comment by Derisis13** [comment]
I like Matrix and Revolt, however I think that 80m CW is the definitive solution to our needs.
It's simple to use: you only need an 80m antenna, a radio transmitter+receiver and a morse key. Bridging to discord would be trivial with an autonomous radio station. 
It's highly secure, considering everyone who wants to join needs expensive equipment, a HAM license, and morse proficiency. The only downside is that the connection is only full duplex at most (although this can be enhanced by splitting into channels), and that during the day solar activities prevent intercontinental connections.
It's also very private: unless someone captures the unencrypted radio trafic, there's no trace of the emmission once it's over.

**Comment by YusufKhan-gamedev** [comment]
lgtm! Can we bridge to https://web.libera.chat/ for some of the people running freedos?

**Comment by port19x** [comment]
> lgtm! Can we bridge to https://web.libera.chat/ for some of the people running freedos?

I fail to see the connection, does freedos come without a webbrowser?

**Comment by YusufKhan-gamedev** [comment]
> > lgtm! Can we bridge to https://web.libera.chat/ for some of the people running freedos?
> 
> I fail to see the connection, does freedos come without a webbrowser?

There are web browsers but unfortunately they are quite bad, just enough to view the instructions for installing ani-cli though!

**Comment by port19x** [comment]
renaming the issue and opening a followup one

**Comment by 4cecoder** [comment]
fuc those data mining and selling hoes
