### ISSUE TITLE
/usr/bin/ani-cli: line 395: [: : integer expression expected

### ISSUE THREAD

**Issue by KingWaffleIII** [pystardust/ani-cli#633]
**Metadata (please complete the following information)**
Version: 2.0.0
OS: Arch Linux
Shell: zsh
Anime: N/A

**Describe the bug**
When playing a range of episodes, `/usr/bin/ani-cli: line 395: [: : integer expression expected` is printed when it plays them. This does not happen with the first episode in the range - it only happens with the rest of the episodes. This bug doesn't affect playback - the application still works and the video is fine.

**Steps To Reproduce**

1. Run `ani-cli` and search for some anime.
2. When it asks for how many episodes, enter a range (e.g. `1 10`).
3. It should print this error message when playing episodes after the first in the range.

**Expected behavior**
This message should not be printed.

**Screenshots (if applicable; you can just drag the image onto github)**
First episode in range:
![image](https://user-images.githubusercontent.com/43790097/162232001-ea694098-2839-4a03-9d05-5382898f20f6.png)

Subsequent episode(s) in range:
![image](https://user-images.githubusercontent.com/43790097/162232177-0d35e84b-1b76-4bce-b9b8-a7031835cf65.png)

**Additional context**
N/A

**Comment by port19x** [comment]
Can't reproduce when playing flcl-dub `1 3`

**Comment by KingWaffleIII** [comment]
Hmm, are you using arguments? I got the error by using the application interactively with no arguments. If this is not the case, it must be platform specific.

**Comment by iamchokerman** [comment]
try updating to version 2.0.2

**Comment by KingWaffleIII** [comment]
This version isn't in the Arch User Repository but I'll try the got version.

**Comment by iamchokerman** [comment]
you can simply update with `sudo ani-cli -U`

**Comment by KingWaffleIII** [comment]
Alright, I can confirm that this issue no longer exists on v2.0.2. I apologise - I didn't realise v2.0.0 wasn't the latest version. I'll close this issue now.
