### ISSUE TITLE
ani-cli -c Not working as intended

### ISSUE THREAD

**Issue by PetkoPetkov03** [pystardust/ani-cli#634]
Version: 2.0.2
OS: Linux Debian 10
Shell: zsh
![loginscreen](https://user-images.githubusercontent.com/80581005/162290480-07177fc2-30c0-4766-9260-20a0bce21875.png)

The continue history option is broken

**Comment by PetkoPetkov03** [comment]
my bad forgot to remove the template

**Comment by iamchokerman** [comment]
this is happening because you are using the old history file. in the current repository there is a history transition script, you can use it to convert your old hist file into the new format. let me know if u need further assistance with it

**Comment by PetkoPetkov03** [comment]
Thanks, that worked!
