### ISSUE TITLE
base64: invalid input, bad decrypt, no such file or directory

### ISSUE THREAD

**Issue by foxTr0t1178** [pystardust/ani-cli#635]
**Metadata (please complete the following information)**
Version: [e.g. 2.0.2]
OS: [e.g. Windows 10 / Linux Mint 20.3]
Shell: [e.g. zsh, run `readlink /bin/sh` to get your shell]
Anime: [e.g. flcl] (if applicable)

Fails to play episodes, returns with `ase64: invalid input
bad decrypt
140645198894400:error:0606506D:digital envelope routines:EVP_DecryptFinal_ex:wrong final block length:../crypto/evp/evp_enc.c:599:
Downloading episode 1 ... 
: No such file or directory
Download failed episode: 001 , please retry or check your internet connection
`

**Steps To Reproduce**

1. Run `ani-cli -d neon-genesis`
2. Choose 1 (neon-genesis-evangelion-dub)
3. Choose episode 1

**Expected behavior**
Downloading should work

![Screenshot from 2022-04-08 17-01-29](https://user-images.githubusercontent.com/74384614/162537807-22b12826-310d-4a5c-9890-6c3f055b7e55.png)

**Additional context**

**Comment by rakusan2** [comment]
I don't have this issue
Try updating the script to the latest version
To do that, just run `ani-cli -U`

The keys were changed in version 1.9.3

**Comment by CoolnsX** [comment]
> **Metadata (please complete the following information)** Version: [e.g. 2.0.2] OS: [e.g. Windows 10 / Linux Mint 20.3] Shell: [e.g. zsh, run `readlink /bin/sh` to get your shell] Anime: [e.g. flcl] (if applicable)
> 
> Fails to play episodes, returns with `ase64: invalid input bad decrypt 140645198894400:error:0606506D:digital envelope routines:EVP_DecryptFinal_ex:wrong final block length:../crypto/evp/evp_enc.c:599: Downloading episode 1 ... : No such file or directory Download failed episode: 001 , please retry or check your internet connection `
> 
> **Steps To Reproduce**
> 
> 1. Run `ani-cli -d neon-genesis`
> 2. Choose 1 (neon-genesis-evangelion-dub)
> 3. Choose episode 1
> 
> **Expected behavior** Downloading should work
> 
> ![Screenshot from 2022-04-08 17-01-29](https://user-images.githubusercontent.com/74384614/162537807-22b12826-310d-4a5c-9890-6c3f055b7e55.png)
> 
> **Additional context**

It seems u r running an older version of ani-cli.. please update it latest one by typing ```sudo ani-cli -U```

**Comment by 71zenith** [comment]
Update by running `sudo ani-cli -U`
