### ISSUE TITLE
Supporting the project financially

### ISSUE THREAD

**Issue by AndrewNoonan2004** [pystardust/ani-cli#639]
Hello, I was wondering if it is possible to donate to the project. This project allows me to use free software rather than proprietary software to watch anime, for which I am grateful. Thanks for the project, and for any replies in advance.

**Comment by Derisis13** [comment]
Sorry, as of today we don't have a way to accept donations. This is a project we do for fun and learning. If you want to thank us, star the repo and follow the maintainers.
