### ISSUE TITLE
Pretty Sure Encryption Keys Changed Again

### ISSUE THREAD

**Issue by Huffinator9** [pystardust/ani-cli#640]
**Metadata (please complete the following information)**
Version: [e.g. 2.0.2]
OS: Arch and Garuda
Shell: zsh and bash
Anime: so far, only Shingeki no Kyojin S4 Part2 (all episodes)

**Describe the bug**
Starting download, but getting network error on each episode

**Steps To Reproduce**

1. Run `ani-cli -p attack.on.titan shingeki no kyojin'
2. Choose 6 (snk part 2)
3. Choose episodes 2-9

**Expected behavior**
Downloading should work

**Comment by port19x** [comment]
![xdoubt](https://user-images.githubusercontent.com/82055622/163265291-a93d161b-3bc9-49b6-a13c-a82ca00cdb74.png)

**Comment by port19x** [comment]
can't reproduce label more to not alarm the others, someone should investigate your download issue

**Comment by Huffinator9** [comment]
![image](https://user-images.githubusercontent.com/100958203/163279820-a655bbea-9edb-4cbc-b614-f050ed4f3442.png)

**Comment by Huffinator9** [comment]
hmmm. interesting. ill do more digging, thanks.
