### ISSUE TITLE
Are we alpine linux compatible?

### ISSUE THREAD

**Issue by port19x** [pystardust/ani-cli#641]
**Is your feature request related to a problem? Please describe.**
no, not really

**Describe the solution you'd like**
can someone run the script and give it some testing (refer to contributing.md) on alpine linux?
I mostly care about compatibility with busybox and alpine is generally the furthest away from default linux that you'll get

**Describe alternatives you've considered**
Tell me it works on you obscure gentoo setup and void linux too.
Do we have a BSD user or two?

**Additional context**
We strive for maximum portability, as long as it's reasonably achievable.
With this issue I want to initiate some quality control in regards to portability.
I'll close the issue after a few reports of obscure setups where it works

**Comment by gagero** [comment]
Will running the OSes in a VM be sufficient testing, or do you need bare metal?

**Comment by port19x** [comment]
> Will running the OSes in a VM be sufficient testing, or do you need bare metal?

VMs are sufficient

**Comment by Euro20179** [comment]
I believe if you install busybux, run `sudo ln -sf $(which busybox) /bin/sh`, then when you run a script with the `#!/bin/sh` or similar shebang, it will run busybox sh, *and* I'm fairly certain busybox will use it's utils instead of the ones you have installed.

**Comment by iamchokerman** [comment]
i believe for matrix bridging you need to be "admin" on the discord server but i might be wrong

**Comment by sgtxd** [comment]
![image](https://user-images.githubusercontent.com/41518455/163473885-25e65429-e73a-4709-955a-e51ab3c56bc1.png)
I am able to confirm that ani-cli runs inside Alpine Linux

**Comment by port19x** [comment]
> ![image](https://user-images.githubusercontent.com/41518455/163473885-25e65429-e73a-4709-955a-e51ab3c56bc1.png) I am able to confirm that ani-cli runs inside Alpine Linux

funny timing, just checked back after a long gaming session
