### ISSUE TITLE
Encription keys was changed again.

### ISSUE THREAD

**Issue by grigoriynikolaev** [pystardust/ani-cli#642]
**Metadata (please complete the following information)**
Version: 2.0.2
OS: Debian GNU/Linux 11(stable)
Shell: fish, also bash
Anime: all
**Describe the bug**
Downloading and streaming are both broken, see screenshot.

**Steps To Reproduce**

1. Run `ani-cli usagi drop`
2. Choose 1 (Usagi Drop)
3. Choose episode 3(just because it's on screenshot)
![2022-04-14 15-26-59](https://user-images.githubusercontent.com/47868839/163346701-08156a98-3d1b-4969-81ae-fc1b8dd95e8f.png)

**Expected behavior**
Downloading and streaming should work

**Screenshots (if applicable; you can just drag the image onto github)**

**Additional context**
Tested on bash. The problem and output is the same.

**Comment by port19x** [comment]
This is a better report of the issue first raised in #640

It's weird how downloading is broken but streaming isn't.
A cryptography bug should affect both downloads and streaming.
Do you feel comfortable giving some relevant `bash -x` output?

Can I assume you didn't properly modify the issue template?
3. choose episode 1 leading to "loading episode 3" seems wrong.
Please edit your bug report if that is the case

**Comment by grigoriynikolaev** [comment]
> Can I assume you didn't properly modify the issue template?
I apologize. I fixed it, and also tested bash and some other anime titles, but the problem still exist.

**Comment by port19x** [comment]
Even streaming is broken?

**Comment by port19x** [comment]
![confirmation](https://user-images.githubusercontent.com/82055622/163354104-062a6de2-d834-47b4-99f7-e1e8016475b6.png)
The issue being present at [animdl](https://github.com/justfoolingaround/animdl) supports this being new keys

**Comment by mdrokz** [comment]
> ![confirmation](https://user-images.githubusercontent.com/82055622/163354104-062a6de2-d834-47b4-99f7-e1e8016475b6.png) The issue being present at [animdl](https://github.com/justfoolingaround/animdl) supports this being new keys

Is there any way to get new keys?

**Comment by port19x** [comment]
> > ![confirmation](https://user-images.githubusercontent.com/82055622/163354104-062a6de2-d834-47b4-99f7-e1e8016475b6.png) The issue being present at [animdl](https://github.com/justfoolingaround/animdl) supports this being new keys
> 
> Is there any way to get new keys?

Of course, this is the third time our keys broke

**Comment by mdrokz** [comment]
> > > ![confirmation](https://user-images.githubusercontent.com/82055622/163354104-062a6de2-d834-47b4-99f7-e1e8016475b6.png) The issue being present at [animdl](https://github.com/justfoolingaround/animdl) supports this being new keys
> > 
> > 
> > Is there any way to get new keys?
> 
> Of course, this is the third time our keys broke

my flutter app also stopped working due to this, so what is the process of getting new keys ?

**Comment by port19x** [comment]
> > > > ![confirmation](https://user-images.githubusercontent.com/82055622/163354104-062a6de2-d834-47b4-99f7-e1e8016475b6.png) The issue being present at [animdl](https://github.com/justfoolingaround/animdl) supports this being new keys
> > > 
> > > 
> > > Is there any way to get new keys?
> > 
> > 
> > Of course, this is the third time our keys broke
> 
> my flutter app also stopped working due to this, so what is the process of getting new keys ?

It's not automated and probably not feasible to automate.
First time a fix arrived afte 2 days, last time we had it fixed in ~12 hours.
KR will likely PR

**Comment by nightser727** [comment]
> Even streaming is broken?

yes

**Comment by port19x** [comment]
Please test with the linked PR and report there
