### ISSUE TITLE
Automatic encryption keys

### ISSUE THREAD

**Issue by Derisis13** [pystardust/ani-cli#649]
*Gogo likes to ruin our fun more and more often.*
There's a [pseudo-api](https://raw.githubusercontent.com/justfoolingaround/animdl-provider-benchmarks/master/api/gogoanime.json) for it already, we just need to use it. This api is updated automatically.
**Pros**: The current way we deal with key changes is PRs and updates. This is a lot of work and a lot of delay compared to fetching the keys every time the script starts.
**Cons**: We'd be relying on an external provider, when it'll end up breaking, it'll be more work to fix/figure out what to do. Also the codebase would grow.

**Comment by Shinyzenith** [comment]
I was thinking of writing a go binary to automatically scrape this every other hour or so using CI/CD and then push it to a file on a repo acting as an API.

I already asked around in an issue and a PR as to how I'm supposed to get the keys but alas I got no reply.

**Comment by nemo256** [comment]
This might be of some help.
https://github.com/riimuru/gogoanime

**Comment by port19x** [comment]
> This might be of some help. https://github.com/riimuru/gogoanime

I'm aware of the api and have confirmed over a month ago they could easily handle our traffic: https://github.com/riimuru/gogoanime/issues/5

**Comment by port19x** [comment]
> _Gogo likes to ruin our fun more and more often._ There's a [pseudo-api](https://raw.githubusercontent.com/justfoolingaround/animdl-provider-benchmarks/master/api/gogoanime.json) for it already, we just need to use it. This api is updated automatically. **Pros**: The current way we deal with key changes is PRs and updates. This is a lot of work and a lot of delay compared to fetching the keys every time the script starts. **Cons**: We'd be relying on an external provider, when it'll end up breaking, it'll be more work to fix/figure out what to do. Also the codebase would grow.

The pseudo api seems promising.
I think transitioning to scrape animixplay is preferable tho

**Comment by Shinyzenith** [comment]
```py
#!/usr/bin/python3.10
import json
import os
import re
import requests

def main():
    res = requests.get("https://goload.pro/streaming.php?id=MTgxNzk2").text
    keys = re.findall(r"(?:container|videocontent)-(\d+)", res)
    if not keys:
        return
    key, iv, second_key = keys
    out = {"key":key, "second_key":second_key, "iv": iv}

    with open("./keys.json", "w") as current_keys:
        json.dump(out, current_keys, indent=4, sort_keys=True)

if __name__=='__main__':
    main()
```
I extracted the key section from animdl repo, it's quite small and easy to maintain. This can run in CI and then ani-cli can just wget at runtime.

**Comment by Splodienyancat** [comment]
I remember seeing something about pulling the keys every other hour but why cant there just a command to pull the keys exist too.
**This may be a security issue though.**

**Comment by mdrokz** [comment]
```js
const CryptoJS = require('./crypto');
const $ = require('cheerio').load(require('fs').readFileSync('./streaming.php').toString());


const secret_value = $(`script[data-name="episode"]`).attr('data-value');

const key_iv = $("div[class*='container-']").attr('class').split('-').pop();
const second_key_id = $("div[class*='videocontent-']").attr('class').split('-').pop();
const key_id = $("body[class^='container-']").attr('class').split('-').pop();

const iv = CryptoJS.enc.Utf8.parse(key_iv);
const key = CryptoJS.enc.Utf8.parse(key_id);
const second_key = CryptoJS.enc.Utf8.parse(second_key_id);


const value = CryptoJS['AES'].decrypt(secret_value, key, { iv: iv });

const value_str = CryptoJS.enc.Utf8.stringify(x);

const alias = value_str.substr(0, value_str.indexOf("&"));

const id = CryptoJS['AES'].encrypt(alias, key, { iv: iv }).toString();

console.log(alias, id, iv, key, second_key);
```
I also wrote this simple code in js to get the keys.

**Comment by mdrokz** [comment]
I implemented the same code in my flutter app https://github.com/mdrokz/ani_mobile/blob/d3299bf9bcbd5bd26863b232ee46e1cadd8ed291/lib/utils.dart#L54-L98

https://github.com/mdrokz/ani_mobile/blob/d3299bf9bcbd5bd26863b232ee46e1cadd8ed291/lib/scraper.dart#L86-L111

the extracted keys work and im able to decrypt the stream link

**Comment by relejek** [comment]
> This might be of some help. https://github.com/riimuru/gogoanime

just throwing an idea in the mix. will it be practice  to build our own method for 'automatic encryption keys' yet have [riimuru/gogoanime](https://github.com/riimuru/gogoanime
) 's pseudo api as back up when any issue arises. we can remove the dependency on pseudo api after a few months of reliable run of native method.
