### ISSUE TITLE
vlc not playing video

### ISSUE THREAD

**Issue by hackedXD** [pystardust/ani-cli#650]
Version: 2.0.4
OS: Android 11
Shell: Termux

**Describe the bug**
Broken encryption keys. Same base 64 error.

**Steps To Reproduce**

1. Run `ani-cli -d Boku no hero`
2. Choose 3 (season 5)
3. Choose episode 15

Happens with everything else as well

**Expected behavior**
Get anime and run mpv

**Comment by TheGlockMisc** [comment]
Tf? its just been some several hours since they changed.
Gogo really mocking us

**Comment by hackedXD** [comment]
Really pushing for #649, like they'll keep on trolling us

**Comment by rakusan2** [comment]
Should we set the agent header so that we at least don’t announce ourselves as curl traffic?

**Comment by port19x** [comment]
This is the third time this week, damn

**Comment by port19x** [comment]
Before that it was 3 times total

**Comment by iamchokerman** [comment]
*this day

**Comment by EsmailELBoBDev2** [comment]
Can confirm, can't watch jojo :(

**Comment by iamchokerman** [comment]
xd

**Comment by EsmailELBoBDev2** [comment]
Still does not work with me :(

**Comment by iamchokerman** [comment]
```sudo ani-cli -U```

**Comment by EsmailELBoBDev2** [comment]
Oh I did that, encryption problem solved but now nothing plays. uploading a video

**Comment by EsmailELBoBDev2** [comment]
https://user-images.githubusercontent.com/28893833/163691978-26e90c83-d444-4f12-9f0f-d64d2850073c.mp4

**Comment by iamchokerman** [comment]
might be a referrer issue, i'll look into it

**Comment by EsmailELBoBDev2** [comment]
Well I visited the domain inside script and I can play with it normally so it's not blocked.
Because of your title, I tried MPV and it works but still something wrong with the quality (as you saw in my video) so I think something off when it tries to grab URLs to play it

**Comment by iamchokerman** [comment]
it's an issue on ur side, working fine for me, what's the output of `ani-cli -V` ?

**Comment by EsmailELBoBDev2** [comment]
weird...
```bash
esmailelbob in ~ 
$ ani-cli -V
Version: 2.0.5                                                                                                                                   0.0s
```

**Comment by port19x** [comment]
I'll be closing this in favor of #661 
Expect a lot more "new key" type issues in the coming days
We're looking into alternatives
