### ISSUE TITLE
video Url not found in window

### ISSUE THREAD

**Issue by Sag5206** [pystardust/ani-cli#654]
**Metadata (please complete the following information)**
Version: [e.g. 2.0.2]
OS: [e.g. Windows 10 / 
Shell:git bash
Anime: any

**Describe the bug**
base64: invalid input
bad decrypt
7416:error:0606506D:digital envelope routines:EVP_DecryptFinal_ex:wrong final block length:../openssl-1.1.1m/crypto/evp/evp_enc.c:599:
Video URL not found

Downloading is broken.
It says something about an unsupported protocol, see screenshot.

**Steps To Reproduce**

1. Run `ani-cli -d flcl`
2. Choose 2 (fooly-cooly)
3. Choose episode 1

**Expected behavior**
Downloading should work

**Screenshots (if applicable; you can just drag the image onto github)**
![image](https://user-images.githubusercontent.com/82055622/151030428-2e78d15f-4ba9-4d86-b6f3-8307557b4b29.png)

**Additional context**
base64: invalid input
bad decrypt
7416:error:0606506D:digital envelope routines:EVP_DecryptFinal_ex:wrong final block length:../openssl-1.1.1m/crypto/evp/evp_enc.c:599:
Video URL not found

**Comment by FireTonnor** [comment]
Sorry but right now gogoanime has changed there encryption keys 3 times today so right now the script is broken the eta of the fix is unknown if you have a more question please go to our discord server and ask for help if you need help

**Comment by FireTonnor** [comment]
@Sag5206

**Comment by TheGlockMisc** [comment]
Try my fork for temporary
