### ISSUE TITLE
any chance for movies scraper

### ISSUE THREAD

**Issue by Aneeqasif** [pystardust/ani-cli#655]
is there any chance that we make a movie scrapper similiar to this that scrapes **https://fmovies.to/** this site has a large collection of movies and series.

considering the fact that we have implemented major components of ani-cli modifieng it to scrape other website might be a worth to go to add functionality for movies to ani-cli it-self or make another script : )

**Comment by CoolnsX** [comment]
There is a development on scraping movies site going on..
https://github.com/mov-cli/mov-cli
u can check it out.. and also give them suggestion for adding this site.. they will happily add it..

**Comment by relejek** [comment]
I recommend that mov-cli should be added to ani-cli's project README file to redirect people there, who want something ani-cli like for movies and tv-shows. sort of a sister project and cross publicity. @CoolnsX

**Comment by FireTonnor** [comment]
Sorry @relejek mov-cli is not really made by the owners so if we add it we will need to contact our team that was making it

**Comment by port19x** [comment]
Tho we could invite the devs to pirate kings

**Comment by CoolnsX** [comment]
> Tho we could invite the devs to pirate kings

And put the pirate kings links in README
