### ISSUE TITLE
is it possible to add a progressing system

### ISSUE THREAD

**Issue by Raif1** [pystardust/ani-cli#658]
**Describe the solution you'd like**
A progress system which will update it self after watching an episode , completing a series 

**Describe alternatives you've considered**
None

**Comment by iamchokerman** [comment]
you mean as in tracking your progress? because that's what the history file and -c flag do. if you want sync with your mal or anilist account then it's a different story

**Comment by port19x** [comment]
Yep, we literally have this and we have it ridicolously polished

**Comment by port19x** [comment]
Closing since you're literally referring to `-c`
If you know of an alternative UX approach we could be following, feel free to mention it
