### ISSUE TITLE
sed: -e expression #1, char 1: unknown command: `,'

### ISSUE THREAD

**Issue by kalyan2012** [pystardust/ani-cli#659]
**Metadata (please complete the following information)**
Version: 2.0.5
OS: Arch
Shell: zsh
Anime: -

**Describe the bug**
Gives
"sed: -e expression #1, char 1: unknown command: `,'"
while accessing the history
**Steps To Reproduce**
just type ani-cli -c

**Expected behavior**
Show anime where they are left off

**Comment by 71zenith** [comment]
Use the `hist_transition.sh` script to convert the old format into new ones

**Comment by kalyan2012** [comment]
Working FIne :)
