### ISSUE TITLE
Encryption Keys brokey again

### ISSUE THREAD

**Issue by YusufKhan-gamedev** [pystardust/ani-cli#661]
Same thing

Loading episode 7... 
base64: invalid input
bad decrypt
140134390953792:error:0606506D:digital envelope routines:EVP_DecryptFinal_ex:wrong final block length:crypto/evp/evp_enc.c:599:
Video URL not found

Love Live Sunshine Episode 7

**Comment by hackedXD** [comment]
Mhm, can confirm

**Comment by iamchokerman** [comment]
for the future, put priority 1 for this pls

**Comment by chemicalzen** [comment]
so, I got this issue two days ago, then it worked fine all day today...and now its back to :
base64: invalid input
bad decrypt
140189941110080:error:0606506D:digital envelope routines:EVP_DecryptFinal_ex:wrong final block length:../crypto/evp/evp_enc.c:599:

There any chance that this isn't gogo screwing with us and them just breaking their own crap, fixing it, and breaking it again...?

**Comment by port19x** [comment]
> for the future, put priority 1 for this pls

I don't believe they can put the labels.
It might show that @YusufKhan-gamedev added the two labels, but that was the issue template

**Comment by NotYasho** [comment]
Any solutions guys? coz the next time this happens, I'll download all the episodes beforehand xD

Does downgrading the version help? or is it a gogoanime problem?

**Comment by CoolnsX** [comment]
Gogoanime problem..

**Comment by NotYasho** [comment]
I see, so workaround for now is to just watch it on gogoanime

**Comment by port19x** [comment]
> Any solutions guys? coz the next time this happens, I'll download all the episodes beforehand xD
> 
> Does downgrading the version help? or is it a gogoanime problem?

Downgrading definitely won't help and I think there has been only one time in the past 6 months were it has for a few hours

**Comment by port19x** [comment]
> I see, so workaround for now is to just watch it on gogoanime

Check out some of our homies in the readme.
animdl and kaa.si-cli are both very strong projects leveraging different providers

**Comment by NotYasho** [comment]
Thanks, but for now, i guess GoGo Anime is fine :)

**Comment by RaynardGerraldo** [comment]
As of now its fixed so im closing

Lets just hope they dont fuck us up again
