### ISSUE TITLE
Only audio playing

### ISSUE THREAD

**Issue by kalyan2012** [pystardust/ani-cli#665]
Version: 2.1.1
OS: Arch
Shell: zsh
Anime: any anime

**Describe the bug**
On playing the anime only sound plays in the background not the video
**Steps To Reproduce**
Just watch any anime

**Expected behavior**
Video and audio should be played

**Comment by iamchokerman** [comment]
that sounds like an issue on your side, not with the script. what video player are you using with ani-cli: mpv or vlc?

**Comment by kalyan2012** [comment]
In mpv only sound is played
In VLC just a new window opens no video no audio

**Comment by iamchokerman** [comment]
what's the output of ````mpv --version``` and ```alias mpv```?

**Comment by kalyan2012** [comment]
mpv --version
mpv 0.34.1-dirty Copyright © 2000-2021 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
FFmpeg library versions:
   libavutil       57.17.100
   libavcodec      59.18.100
   libavformat     59.16.100
   libswscale      6.4.100
   libavfilter     8.24.100
   libswresample   4.3.100
FFmpeg version: n5.0

alias mpv
no output

**Comment by iamchokerman** [comment]
looks correct

**Comment by iamchokerman** [comment]
try reinstalling ani-cli, also have you changed anything in the script itself?

**Comment by kalyan2012** [comment]
ok ill try reinstalling, but will it effect my history?
I did not change

**Comment by iamchokerman** [comment]
no it won't affect your history

**Comment by kalyan2012** [comment]
For arch which might be good ani-cli or ani-cli-git?

**Comment by iamchokerman** [comment]
ani-cli-git

**Comment by kalyan2012** [comment]
Tried reinstalling but didnt work :(

**Comment by kalyan2012** [comment]
Hey found some more details about the bug.
If i try to watch any anime from history the described problem is occurring
But if i start fresh it doesnt cause any problems. I guess i have to add them by rewatching into history

**Comment by iamchokerman** [comment]
you could use the history transition script i suppose

**Comment by Derisis13** [comment]
This could also be an m3u8 quality setting issue. Can you try playing the episodes that only had sound with `-q worst`?

**Comment by kalyan2012** [comment]
> This could also be an m3u8 quality setting issue. Can you try playing the episodes that only had sound with `-q worst`?

Yup playing fine with worst quality. But why not with best?

**Comment by MushroomEnder** [comment]
I am experiencing the same problem. I have ani-cli updated to the latest version (I like how it looks and feels now btw)

My OS is arch linux, with the KDE desktop (if that helps), and it is virtualized. When I play Date a Live Season 4 episode 1 it works, but when I play the second episode, it doesn't.

The problem: The window does not appear, yet the audio is played.

**Comment by port19x** [comment]
> For arch which might be good ani-cli or ani-cli-git?

During these wild times, definitely ani-cli-git

**Comment by port19x** [comment]
Edited title as to not imply this means the whole thing doesn't work

**Comment by MMOOBB** [comment]
I had this same issue happen to me on the anime "Shokei Shoujo no Virgin Road" episode 2, on two systems. Worked for episode 1 and 3. Was going to report it, but figured it was unique to this specific anime episode only.

**Comment by muflona11** [comment]
> Version: 2.1.1
> OS: Arch
> Shell: zsh
> Anime: any anime
> 
> **Describe the bug**
> On playing the anime only sound plays in the background not the video
> **Steps To Reproduce**
> Just watch any anime
> 
> **Expected behavior**
> Video and audio should be played
