### ISSUE TITLE
Encryption keys are broken

### ISSUE THREAD

**Issue by DecayingEagle** [pystardust/ani-cli#667]
Version: 2.0.2
OS: Windows 11
Shell: powershell
Anime: Durarara episode 1

**Describe the bug**
encryption keys are broken

```
base64: invalid input
bad decrypt
16900:error:0606506D:digital envelope routines:EVP_DecryptFinal_ex:wrong final block length:../openssl-1.1.1m/crypto/evp/evp_enc.c:599:
Video URL not found
```

**Steps To Reproduce**

1. Run `ani-cli durarara`
2. Choose 1 (Durarara (episode 25))
3. Choose episode 1

**Expected behavior**
The anime should play

**Comment by Derisis13** [comment]
Update ani-cli: see [fixing errors](https://github.com/pystardust/ani-cli#Fixing-errors) in the readme. Also use gitbash instead of powershell, poweshell may or may not work.
