### ISSUE TITLE
Problem with VLC (mpv works fine)

### ISSUE THREAD

**Issue by NotYasho** [pystardust/ani-cli#668]
**Metadata**
Version: 2.1.1
OS: Linux Manjaro LTS 5.15.32-1
Shell: zsh
Anime: Any anime

**Describe the bug**
It works fine with mpv, with VLC it just loads forever.
Here's a GIF demonstrating the issue

**Steps To Reproduce**

1. Run `ani-cli -v` (-v for vlc)
2. Search any anime (for example: `jujutsu kaisen`)
3. Choose any number (2)
4. Choose any episode (7) lol

**Expected Behaviour**
The video should play as it does with mpv.

![output](https://user-images.githubusercontent.com/90166733/163763151-418af530-82c3-4140-ac0e-193f56fd03fa.gif)

Is this a problem with VLC or with ani-cli. 
P.S: Youtube videos do work, command:
```
vlc https://www.youtube.com/watch\?v\=kSZddHca0ME
```

**Comment by MMOOBB** [comment]
Seems like an issue with your instance of vlc, works fine on my end. Maybe try a fresh install of vlc.

**Comment by NotYasho** [comment]
i'll try

**Comment by NotYasho** [comment]
Nope, didn't work.

Commands

```sh
sudo pacman -R vlc
sudo pacman -S vlc
```

**Comment by iamchokerman** [comment]
did you install youtube-dl ??

**Comment by CoolnsX** [comment]
> did you install youtube-dl ??

Vlc uses its own library.. so that won't do anything

**Comment by NotYasho** [comment]
> did you install youtube-dl ??

yes, I did

**Comment by iamchokerman** [comment]
> > did you install youtube-dl ??
> 
> Vlc uses its own library.. so that won't do anything

oh well

**Comment by Justaus3r** [comment]
can confirm this behavior on my end on archcraft .latest vlc version from aur.seems like arch specific vlc problem

**Comment by NotYasho** [comment]
Dude how do you even install vlc-git, I tried installing it from AUR with the command
```
yay -S vlc-git
```
damn, it took 20 minutes and failed ultimately

**Comment by Justaus3r** [comment]
if its a mirror problem. try **upgrading** manjaro using ``sudo pacman -Syu``(and not ``-Sy`` since it just updates the repo list and partial upgrades are not supported on arch).it should solve the issue.

**Comment by port19x** [comment]
Relabeling as support, hope you can get this fixed

**Comment by NotYasho** [comment]
Reinstalled VLC, the problem seems to be fixed now :)

**Comment by Derisis13** [comment]
Good, I'm closing the issue
