### ISSUE TITLE
Video URL not found, base64, bad decrypt error

### ISSUE THREAD

**Issue by canosaur** [pystardust/ani-cli#669]
**Metadata (please complete the following information)**
Version: 2.1.1
OS: Debian 11
Shell: bash
Anime: Any anime searched until now

**Describe the bug**
Everything works fine until the episode is selected to watch anime. It shows base64 and bad decrypt error, and then a
video URL not found. This has happened before too but updating the script patches it. 
It says something about an unsupported protocol, see screenshot.

**Steps To Reproduce**

1. Run `ani-cli`
2. Search any anime
3. Choose anime
4. select episode

**Expected behavior**
mpv should open and no error to be seen on terminal

**Screenshots (if applicable; you can just drag the image onto github)**
![image](https://user-images.githubusercontent.com/97674455/163800282-b38cf9d3-bdf0-4e93-96d3-673aa44713cf.png)

**Additional context**

**Comment by matiziol** [comment]
on windows its the same thing, "ani-cli -U" says its up to date
![image](https://user-images.githubusercontent.com/86927247/163801212-c3aa5870-f2a2-47f1-a0e3-0c8914c81574.png)

**Comment by grigoriynikolaev** [comment]
I have the same issue.

**Comment by TheGlockMisc** [comment]
Omw to PR

**Comment by port19x** [comment]
thx @TheGlockMisc 
good timing as per usual
