### ISSUE TITLE
[Feature Request] Downloading multiple episodes in parallel?

### ISSUE THREAD

**Issue by Nyaaboron** [pystardust/ani-cli#67]
Is it possible to have an option about how many episodes I want to download at the same time?
For example, if I was downloading 6 episodes, I can have 3 episodes downloading in parallel instead of just downloading one episode at a time.
I have no experience in programming shell scripts so I don't know if this feature is even possible but if it is, it might really speed up download times.

**Comment by ura43** [comment]
Good idea, but hard to implement properly

**Comment by CoolnsX** [comment]
It is possible... But it may make the downloading slower... For e.g.-if u download one episode... 
Then started downloading another episode..
Then all bandwidth will be taken by another episode... Sometimes bandwidth gets distributed equally.. and many times it's not.. so we can do that.. but it will not work right now..

You can check it by running 2 ani-cli scripts side by side... And download it..

**Comment by ura43** [comment]
I trust @CoolnsX with his assessment
