### ISSUE TITLE
Error while loading any episode

### ISSUE THREAD

**Issue by darkwolf1000** [pystardust/ani-cli#672]
**Metadata**
Version: 2.1.2
OS: Linux Mint 20.3
Shell: dash (zsh 5.8)
Anime: all i tested was AOT the final season part 2 ep 5 and to test toradora,serial experiments lain

**Describe the bug**
Loading episode 1... 
hex string is too short, padding with zero bytes to length
hex string is too short, padding with zero bytes to length
base64: ungültige Eingabe
hex string is too short, padding with zero bytes to length
hex string is too short, padding with zero bytes to length
bad decrypt
140703262053696:error:0606506D:digital envelope routines:EVP_DecryptFinal_ex:wrong final block length:../crypto/evp/evp_enc.c:599:
Video URL not found

**Steps To Reproduce**

1. Run `ani-cli`
2. enter one of the mentioned titels above
3. start any episode

**Expected behavior**
MPV opens and you could watch.

p.s. I hope that is enough to find the problem good luck Jan ^^

**Comment by Derisis13** [comment]
I think this is just our daily treat... Do you by chance know when it first started to missbehave?

**Comment by somethingrandom2121** [comment]
same here, i think its starting to happen daily

**Comment by Derisis13** [comment]
Fixed in 2.1.3, please update.
