### ISSUE TITLE
Video URL not found

### ISSUE THREAD

**Issue by icedgreen** [pystardust/ani-cli#675]
**Metadata (please complete the following information)**
Version: 2.1.3
OS: Arch Linux
Shell: bash
Anime: any

**Describe the bug**
Video does not open. I am using ani-cli-git.
```
base64: invalid input
bad decrypt
139686919444288:error:0606506D:digital envelope routines:EVP_DecryptFinal_ex:wrong final block length:crypto/evp/evp_enc.c:599:
Video URL not found
```

**Steps To Reproduce**

1. Run `ani-cli naruto`
2. Choose 1 (Naruto)
3. Choose episode 1

**Expected behavior**
mpv should open

**Screenshots (if applicable; you can just drag the image onto github)**
![image](https://user-images.githubusercontent.com/104019026/164042439-01a18323-117f-4a87-8f50-d76895c224dd.png)

**Additional context**

**Comment by JungerBoyo** [comment]
same here

**Comment by TheGlockMisc** [comment]
Aight imma go find ways..
They added another layer of security to their api, Damn Gogo been active at changing keys lately

**Comment by Spaxly** [comment]
This is still an issue at the moment. Manually installing ani-cli does not work either.

**Comment by Bumpkin-Pi** [comment]
`ani-cli -U` possibly

**Comment by mrfluffy-dev** [comment]
Gogoanime has been changing their encryption method a lot the past couple of days. So it sadly will brake from time to time we are working on solutions for this.

**Comment by Spaxly** [comment]
possibly change to 9anime or add it as an option

**Comment by mrfluffy-dev** [comment]
Refer to #383

**Comment by Spaxly** [comment]
Well, gogoanime has been stepping up there encryption which will most likely slowly break ani-cli so adding a different provider may be required

**Comment by TheGlockMisc** [comment]
Omw to PR

**Comment by emoisback** [comment]
looks like we can directly access encrytion.php anymore, its give us 403 forbidden, unless we knew what encryption.php doing.

**Comment by Spaxly** [comment]
works now with pull request #677 merged. update ani-cli
