### ISSUE TITLE
Switch to 9anime or Kissanime from Gogoanime.

### ISSUE THREAD

**Issue by MysteriousK69** [pystardust/ani-cli#676]
**Is your feature request related to a problem? Please describe.**
The encryption keys breaking again and again is really annoying. Maybe we could fix it by switching to something else?

**Describe the solution you'd like**
We could maybe switch from gogoanime to 9anime or kissanime? Since gogoanime really likes to be party poopers and take away our fun from us. Though it will need a rewrite for most parts, so it's gonna be a lot of work sadly.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by Derisis13** [comment]
Please discuss in #383
