### ISSUE TITLE
cryptographic incompatibility with libressl

### ISSUE THREAD

**Issue by dvogiye** [pystardust/ani-cli#679]
**Metadata**
Version: latest from `master` branch; commit `48f2e20042945ee5298d92e6fab1cd1b21c414ee` (2.1.4)
OS: OpenBSD 7.1-beta
Shell: `/bin/sh` (`pdksh`)
Anime: Lain :)

**Describe the bug**
Guessing from the older reports and from the error message, it seems that the provider's keys have changed? 

**Steps To Reproduce**
For example, Lain :)
1. Run `ani-cli -d lain`
2. Choose 3 (Serial Experiments Lain)
3. Choose any #, i've tested with 5, 6, 7

**Expected behavior**
The script usually does work, even while using OpenBSD, with it's default LibreSSL and `pdksh` preferences. (btw, the script does in fact load with `pdksh`, I don't have `bash` installed on my system) I guess the answer to this is "it should work".

**Screenshots**
```
Loading episode 7... 
bad decrypt
9159946231440:error:06FFF06D:digital envelope routines:CRYPTO_internal:wrong final block length:/usr/src/lib/libcrypto/evp/evp_enc.c:540:
Downloading episode 7 ... 
: No such file or directory
Download failed episode: 007 , please retry or check your internet connection
(n) next
(p) previous
(r) replay
(s) select
(q) exit
> q
```

**Comment by CoolnsX** [comment]
Working fine for me

**Comment by muflona11** [comment]
> **Metadata**
> Version: latest from `master` branch; commit `48f2e20042945ee5298d92e6fab1cd1b21c414ee` (2.1.4)
> OS: OpenBSD 7.1-beta
> Shell: `/bin/sh` (`pdksh`)
> Anime: Lain :)
> 
> **Describe the bug**
> Guessing from the older reports and from the error message, it seems that the provider's keys have changed? 
> 
> **Steps To Reproduce**
> For example, Lain :)
> 1. Run `ani-cli -d lain`
> 2. Choose 3 (Serial Experiments Lain)
> 3. Choose any #, i've tested with 5, 6, 7
> 
> **Expected behavior**
> The script usually does work, even while using OpenBSD, with it's default LibreSSL and `pdksh` preferences. (btw, the script does in fact load with `pdksh`, I don't have `bash` installed on my system) I guess the answer to this is "it should work".
> 
> **Screenshots**
> ```
> Loading episode 7... 
> bad decrypt
> 9159946231440:error:06FFF06D:digital envelope routines:CRYPTO_internal:wrong final block length:/usr/src/lib/libcrypto/evp/evp_enc.c:540:
> Downloading episode 7 ... 
> : No such file or directory
> Download failed episode: 007 , please retry or check your internet connection
> (n) next
> (p) previous
> (r) replay
> (s) select
> (q) exit
> > q
> ```

**Comment by port19x** [comment]
openbsd very based

**Comment by Tyecon** [comment]
Was getting same problem on Windows, version 2.1.0. Doing ani-cli -U to 2.1.5 fixed it.

**Comment by dvogiye** [comment]
just updated, same issue, but `ani-cli` now exits when error occurs

```
Loading episode 5... 
bad decrypt
2018804669400:error:06FFF06D:digital envelope routines:CRYPTO_internal:wrong final block length:/usr/src/lib/libcrypto/evp/evp_enc.c:540:
Current video quality is not available (defaulting to best quality)
Video URL not found
```

**Comment by Derisis13** [comment]
Are you sure it's not libreSSL? Also if pdksh has a -x option, it could help to see what is the input that creates the bad decrypt.

**Comment by kuba300game** [comment]
> Was getting same problem on Windows, version 2.1.0. Doing ani-cli -U to 2.1.5 fixed it.

thanks, it helped

**Comment by xKirtle** [comment]
Was experiencing the same problem on Arch, version 2.1.0. Uninstalled the package and installed the latest one (version 2.1.5) and it seems to work now. Not sure what was causing it

**Comment by port19x** [comment]
> Are you sure it's not libreSSL? Also if pdksh has a -x option, it could help to see what is the input that creates the bad decrypt.

Idk, would be weird if OpenBSD refused to use their own cryptography library

**Comment by port19x** [comment]
> Was experiencing the same problem on Arch, version 2.1.0. Uninstalled the package and installed the latest one (version 2.1.5) and it seems to work now. Not sure what was causing it

Most linux users will have this same issue due to outdated keys and upgrading to latest fixes the issue.
When he opened the issue 2.1.4 was latest, so this is likely to be due to an incompatibility with his ssl library

**Comment by port19x** [comment]
> > Are you sure it's not libreSSL? Also if pdksh has a -x option, it could help to see what is the input that creates the bad decrypt.
> 
> Idk, would be weird if OpenBSD refused to use their own cryptography library

look at me making a fool of myself. @dvogiye said it's libressl

**Comment by dvogiye** [comment]
tested with replacing `openssl` with `eopenssl11` (portable cringe OpenSSL), still doesn't work

```
bad decrypt
0:error:0606506D:digital envelope routines:EVP_DecryptFinal_ex:wrong final block length:crypto/evp/evp_enc.c:599:
Current video quality is not available (defaulting to best quality)
Video URL not found
```

**Comment by dvogiye** [comment]
just tested again with latest commit, seems to be working now
i may just look at commits to see what happened between the 4 days
