### ISSUE TITLE
ani-cli does nothing but returns 0

### ISSUE THREAD

**Issue by YusufKhan-gamedev** [pystardust/ani-cli#683]
ani-cli just returns

yusufkhan@yusufkhan ~> ani-cli 
yusufkhan@yusufkhan ~> ani-cli -d flcl
yusufkhan@yusufkhan ~> ani-cli -U
yusufkhan@yusufkhan ~> ani-cli -h
yusufkhan@yusufkhan ~> ani-cli --help
yusufkhan@yusufkhan ~> 

With nothing else

**Comment by Derisis13** [comment]
Please clarify: your problem is that every run exits eiter with 1 (unsuccesful) or 0 (succesful) in which case this is a feature request or enhancement; or that the program doesn't run at all.
In the latter case I'd suggest checking if `/bin/sh` exists.

**Comment by Derisis13** [comment]
Also please fill in the issue template that you were so kind and deleted

**Comment by YusufKhan-gamedev** [comment]
**Metadata (please complete the following information)**
Version: 2.1.3??? Cant tell but it was one of yesterdays
OS: Arch Linux LTS
Shell: fish, bash, sh
Anime: [e.g. flcl] (if applicable)

**Describe the bug**
ani-cli return code 0 when executing with ANY args

**Steps To Reproduce**

1. Run `ani-cli `

**Expected behavior**
Prompt appears to chose anime

**Comment by Derisis13** [comment]
What you should do is reinstall the script. It's possible that it was corrupted.

**Comment by iamchokerman** [comment]
also, use `ani-cli -V` to check version

**Comment by port19x** [comment]
> also, use `ani-cli -V` to check version

Don't think that will work when every other flag exits without doing anything

**Comment by SloppyPuppy** [comment]
`~ λ cat /usr/local/bin/ani-cli 
~ λ 
`
The script inside /usr/local/bin/ani-cli is empty, /bin/ani-cli isn't empty but it appears the installer adds /usr/local/bin to $PATH instead.

**Comment by SloppyPuppy** [comment]
Fixed it by removing the empty script file in /usr/local/bin/
I believe this happens because this is what $PATH prints for me
`~ λ echo $PATH`
`/usr/local/sbin /usr/local/bin /usr/bin /opt/android-sdk/platform-tools /opt/android-sdk/tools /opt/android-sdk/tools/bin /usr/lib/jvm/default/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl`
It looks for ani-cli in /usr/local/bin first and since it found it but its an empty file it just doesnt work.

**Comment by YusufKhan-gamedev** [comment]
> Fixed it by removing the empty script file in /usr/local/bin/ I believe this happens because this is what $PATH prints for me `~ λ echo $PATH` `/usr/local/sbin /usr/local/bin /usr/bin /opt/android-sdk/platform-tools /opt/android-sdk/tools /opt/android-sdk/tools/bin /usr/lib/jvm/default/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl` It looks for ani-cli in /usr/local/bin first and since it found it but its an empty file it just doesnt work.

Worked! Corruption when ani-cli updated?
