### ISSUE TITLE
Continue watching from timestamp

### ISSUE THREAD

**Issue by PetkoPetkov03** [pystardust/ani-cli#686]
I don't quite like that when you close ani-cli in the middle of an episode next time you use the -c flag it starts in the beginning of the next episode.

I have found that mpv at least has a way to start at a specific timestamp and is also able to log out the current timestamp of the current playing video. Can we make it  update the timestamp in the logs every 10 seconds or something like that? I also feel like it should be a different flag in case there's some kind of a bug. Maybe -ct(continue timestamp)

**Comment by TheGlockMisc** [comment]
It was on "Rejected Feats." #523
