### ISSUE TITLE
Honzuki no Gekokujou ep one is always selected

### ISSUE THREAD

**Issue by imsamuka** [pystardust/ani-cli#687]
**Metadata**
Version: 2.1.5 (aur/ani-cli-git)
OS: ArchLinux
Shell: bash
Anime: Honzuki no Gekokujou Shisho ni Naru Tame ni wa Shudan wo Erandeiraremasen 3rd Season

**Describe the bug**
Trying to watch any episode, always opens the episode 1 instead.
I couldn't reproduce with other anime.

**Steps To Reproduce**
1. Run `ani-cli -a 3 Honzuki no Gekokujou Shisho ni Naru Tame ni wa Shudan wo Erandeiraremasen 3rd Season`

**Expected behavior**
Watch the 3 episode from the 3 season. The 1 episode from the 3 season appears instead.

**Comment by iamchokerman** [comment]
just checked the anime on goload.pro, looks like this anime has 0.x episodes, which might be the cause for this behavior. [episode link](https://goload.pro/videos/honzuki-no-gekokujou-shisho-ni-naru-tame-ni-wa-shudan-wo-erandeiraremasen-3rd-season-episode-1)

**Comment by CoolnsX** [comment]
![Screenshot_20220426-144918-885](https://user-images.githubusercontent.com/76195824/165267847-eeb20652-432f-4682-a684-81729e3beaa3.png)

**Comment by port19x** [comment]
Can reproduce
![2022-04-28_14-44](https://user-images.githubusercontent.com/82055622/165754730-d95413f9-d368-49e5-8813-3e9ab77d487d.png)

**Comment by iamchokerman** [comment]
> 

same for me

**Comment by port19x** [comment]
> ![Screenshot_20220426-144918-885](https://user-images.githubusercontent.com/76195824/165267847-eeb20652-432f-4682-a684-81729e3beaa3.png)

Does this indicate this anime has another weird episode naming scheme?
We may or may not want to support `0-1` episodes.
We should look into it, but disregard it if it's too complicated or takes many loc

**Comment by CoolnsX** [comment]
Yup it's those 0.5 like episodes..

**Comment by iamchokerman** [comment]
#523
