### ISSUE TITLE
Can we mainline ani-sync?

### ISSUE THREAD

**Issue by port19x** [pystardust/ani-cli#688]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to watch anime with my friend again. Ani-sync was a great project, but has been archived about a month ago. I assume it may have been difficult and/or inconvenient to keep updated

**Describe the solution you'd like**
If this doesn't bloat the code in an unreasonable way, a `-s` for sync would be a great addition.

**Describe alternatives you've considered**
Consider resurrecting the third party repo and maintain it as a patch set over mainline ani-cli.

**Additional context**
syncplay would become an additional optional dependency.
I consider up to 100 loc reasonable for such a game changing feature.

**Comment by iamchokerman** [comment]
that's actually a very interesting idea, @kalix123 aka Neptune and I were considering resurrecting ani-sync on his fork for ease of maintaining, but directly merging this into main as a new argument actually sounds much better. i'll look into it in the next few days, and implement it on a new branch, and will do some testing

**Comment by YusufKhan-gamedev** [comment]
Please!

**Comment by port19x** [comment]
@iamchokerman just pr the thing already :sweat_smile: 
Doesn't have to be range compatible on initial merge, we can patch that in shortly afterwards

**Comment by iamchokerman** [comment]
ye sorry, i forgor 💀
