### ISSUE TITLE
Bridge irc too

### ISSUE THREAD

**Issue by port19x** [pystardust/ani-cli#689]
**Is your feature request related to a problem? Please describe.**
As detailed in #631 I got locked out of discord and have no way to get back in.
Beyond my own misfortune, we should aim to eliminate discord as a single point of failure to our communications and support.
A recent community poll indicated a preference for matrix over discord.
Since that one has been held on discord after my lockout, I'd appreciate a screenshot for documentation.

**Describe the solution you'd like**
A bridged matrix space with discord as a second class citizen and revolt and irc as less active fallbacks.

The matrix space already exists and @iamchokerman is the admin of #general  

**Describe alternatives you've considered**
We should continue preliminary support of revolt and maybe irc, meaning just have support and a general chat on those platforms while matrix should become the bridged flagship standard

**Additional context**
iina is just an mpv frontend and accepts its flags.
Needless to say it can play urls.

**Comment by iamchokerman** [comment]
<img width="684" alt="image" src="https://user-images.githubusercontent.com/44473782/165341095-5b75eaf9-637f-4023-974f-4905dc8a263b.png">

a big problem with that matrix space, is that i'm not admin in the support room, so i can't invite the bot for the bridge and consequently can't bridge that room. i pinged the owner last week but no signs of him yet

**Comment by port19x** [comment]
I think I waited about a month until I heard back from him, lets be patient

**Comment by iamchokerman** [comment]
ye

**Comment by port19x** [comment]
A first step would be to incorporate links to revolt and matrix into the readme and advertise those as alternatives, we can do that already

**Comment by iamchokerman** [comment]
will look into ways to use embeds or smtg along those lines tomorrow

**Comment by port19x** [comment]
Very nice embeds. As those alterative communities grow, we could place discord as just another icon besides the other two

**Comment by iamchokerman** [comment]
ye i'll do it, will be easy

**Comment by iamchokerman** [comment]
le matrix has now been bridged for support, general and dev lounge (i sent u an invite @port19x ). ill do the sleepy time now and prolly fully bridge it tomorrow

**Comment by iamchokerman** [comment]
oh yeah, i have admin for everything thats needed on the matrix side, rip discord for now

**Comment by port19x** [comment]
> le matrix has now been bridged for support, general and dev lounge (i sent u an invite @port19x ). ill do the sleepy time now and prolly fully bridge it tomorrow

I'm in, great to see us making progess

**Comment by port19x** [comment]
I'm happy to see that many more channels have been bridged.
For now I'm missing the following:

- [ ] hardware

**Comment by port19x** [comment]
Let's bridge IRC and drop Revolt from our official networks.
I'm not sure anyone uses revolt but I'll definitely also use irc, even if only due to the irc client built into emacs.
It's also very easy to bridge, while revolt exists as a seperate desert island

**Comment by port19x** [comment]
nvm
