### ISSUE TITLE
Audio only on MPV

### ISSUE THREAD

**Issue by Daiatt** [pystardust/ani-cli#691]
**Metadata (please complete the following information)**
Version: 2.1.5
OS: Arcolinux
Shell: ZSH 
Anime: Initial D First Stage

**Describe the bug**
MPV only outputting audio in the background, not even the player window is opened. Using VLC the audio and video are played normally

**Steps To Reproduce**
1. Run ani-cli initial
2. choose (3) initial D First Stage (episode 26)
3. choose 12 

**Expected behavior**
MPV should open and play audio + video normally

**Additional context**
mpv --version output
> mpv 0.34.0-280-g6605b6d619 Copyright © 2000-2022 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
FFmpeg library versions:
   libavutil       57.24.101
   libavcodec      59.27.100
   libavformat     59.23.100
   libswscale      6.6.100
   libavfilter     8.37.100
   libswresample   4.6.100
FFmpeg version: N-106684-g1da3394adb

**Comment by Daiatt** [comment]
i did a bit more testing and found that it's only happen on some anime that i tested such as,
- one room s2
- gintama s1
- yuru camp s2
- pui pui molcar
- naruto shippuden

interestingly i able to play those anime fine on my ani-cli install on termux but  on my wndows install it's the same as my linux install. Both are on the 2.1.5 version and using mpv.

**Comment by port19x** [comment]
Can*t reproduce, but we have been getting a few "audio only" reports recently.
Maybe gogo is trying some new shenanigans
![2022-04-28_14-51](https://user-images.githubusercontent.com/82055622/165756115-3566b493-2596-43d5-8c23-49ab6d326239.png)

**Comment by CoolnsX** [comment]
Nope.. it's a problem on our side..
