### ISSUE TITLE
offline update corrupts script

### ISSUE THREAD

**Issue by YusufKhan-gamedev** [pystardust/ani-cli#692]
**Metadata (please complete the following information)**
Version: 2.1.5
OS: Arch lts kernel
Shell: fish
Anime: N/A

**Describe the bug**
Updates that occur during a loss of internet connectivity can cause the ani-cli script to be corrupted on more likely be emptied. 

**Steps To Reproduce**

1. Run `ani-cli -U` during a internet outage

**Expected behavior**
Update failure is reported

**Additional context**
N/A

**Comment by port19x** [comment]
Can reproduce, this is very troubleing
![pepecross](https://user-images.githubusercontent.com/82055622/165757788-5e3fad41-42fd-4a31-b0dc-be19a1b7aecf.png)

**Comment by port19x** [comment]
It's not just if you loose internet during the update, but also if you run ani-cli -U while offline

**Comment by Derisis13** [comment]
I think this can be solved by checking the exit value of `curl` during the update process(and exiting if not 0). Yes, this would mean that we probably need another line for piping into `diff`, but one line to fix this issue is pretty good imo
