### ISSUE TITLE
Let's make a pull request template

### ISSUE THREAD

**Issue by port19x** [pystardust/ani-cli#693]
**Is your feature request related to a problem? Please describe.**
Currently our PR workflow feels kinda incomplete / awkward, a template could enrich it.

**Describe the solution you'd like**
Just have a checklist as detailed in the Contributing.md under Merge checklist

**Describe alternatives you've considered**
Adding the releases checklist seems like a good idea if we can communicate that it's not needed for every PR.
Additionally we could add a modified metadata section from the bug report template.

**Additional context**
I've had the idea for several weeks now.
A short ~google~ duckduckgo search gave me the following promising [article](https://embeddedartistry.com/blog/2017/08/04/a-github-pull-request-template-for-your-projects/
)

**Comment by iamchokerman** [comment]
.github is probably a better location for "PULL_REQUEST_TEMPLATE.md" 🤔

**Comment by port19x** [comment]
yes, definitely
