### ISSUE TITLE
Moar packages

### ISSUE THREAD

**Issue by Derisis13** [pystardust/ani-cli#697]
**Is your feature request related to a problem? Please describe.**
I want to get into application packaging, that's all.

**Describe the solution you'd like**
Since my system has flatpaks and debs the options I feel motivation towars are a ppa and a flathub user repo.

**Describe alternatives you've considered**
SNAPs are not ideal for scripts (I'm not even sure if containerizing would even work for ani-cli) and I have no experience nor knowledge with rpm packages.

**Additional context**

We already have a brew tap, a scoop bucket and an AUR package.
Also having a flatpak (that depends on flatpak mpv) might be the solution for flatpak mpv support

**Comment by port19x** [comment]
If someone can package an apk for fdroid or research how you get into termux repos that would be great

**Comment by Derisis13** [comment]
Termux has its own package management and as far as I can tell it's a modified apt. I think we cna do that too.
I don't think we should start to distribute termux apks, it will be hard enough to package our code

**Comment by Derisis13** [comment]
Also I looked into the fedora user repository, and [copr](https://copr.fedorainfracloud.org/) looks quite a promising platform

**Comment by port19x** [comment]
> Also I looked into the fedora user repository, and [copr](https://copr.fedorainfracloud.org/) looks quite a promising platform

maybe we can even get into their regular repos, they seem a lot less strict than debian

**Comment by port19x** [comment]
https://repology.org/project/ani-cli/versions

**Comment by port19x** [comment]
I think we might already be in the termux repos 👀

**Comment by WillPower3309** [comment]
Nix package: #707

**Comment by port19x** [comment]
Why do we depend on ncurses-tools for termux?
Works without it (the menu at least)
I opened a PR upstream to fix some weird dependencies https://github.com/termux/termux-packages/pull/10485

**Comment by Derisis13** [comment]
As much as I would like to publish a package compatible package for all the distros via flatpak, it turns out since it's sandboxed we can't just run other applications (ffmpeg, aria2, mpv, vlc, ect...), not even their flatpak versions. Should I try my luck with regular packaging tools (debs and maybe rpms) or should I keep flatpak as a priority?

**Comment by port19x** [comment]
Try some regular packages. Looks like flatpaks isolation doesn't go well with a package that likes to interact with its platform

**Comment by Wiener234** [comment]
Just out of curiosity are you planing to build a package for debian that is simple and dose its job or are you doing it like the debian doc (https://www.debian.org/doc/manuals/maint-guide/start.en.html) say's it has to be done? @Derisis13

**Comment by Derisis13** [comment]
> Just out of curiosity are you planing to build a package for debian that is simple and dose its job or are you doing it like the debian doc (https://www.debian.org/doc/manuals/maint-guide/start.en.html) say's it has to be done? @Derisis13

Thanks for presenting this resource, I have found a different documentation, but this one seems to apply more to us. I plan to keep conventions as long as it doesn't require changing anything (major) in the project.
Also if you have experience in debian packageing you're more than welcome to maintain our debian package (which is yet to be made).

**Comment by Wiener234** [comment]
> > Just out of curiosity are you planing to build a package for debian that is simple and dose its job or are you doing it like the debian doc (https://www.debian.org/doc/manuals/maint-guide/start.en.html) say's it has to be done? @Derisis13
> 
> Thanks for presenting this resource, I have found a different documentation, but this one seems to apply more to us. I plan to keep conventions as long as it doesn't require changing anything (major) in the project. Also if you have experience in debian packageing you're more than welcome to maintain our debian package (which is yet to be made).

I have not much experience with debian packaging. But played around with it a little and got a package that works but i am not sure when it comes to some files (like copyright and the build in source control) so it will be by no means perfect. If you want to have a look at it https://github.com/Wiener234/ani-cli/tree/master/builds/deb feel free to.

**Comment by Derisis13** [comment]
> I have not much experience with debian packaging. But played around with it a little and got a package that works but i am not sure when it comes to some files (like copyright and the build in source control) so it will be by no means perfect. If you want to have a look at it https://github.com/Wiener234/ani-cli/tree/master/builds/deb feel free to.

I checked your repo, and it seems promising and I'd prefer to work on that instead of creating an own package.
I'm still thinking how it would best be executed and there are changes I'd like to see.

**Comment by Wiener234** [comment]
You can do what you think is right with that repo. If you need something just say so.

**Comment by port19x** [comment]
- [ ] .deb

**Comment by port19x** [comment]
We should focus on the important package formats first
- [ ] .deb (Debian) as ppa or in a repo
- [ ] .rpm (Fedora) in copr

And later, or if a user on such a distro exists, support more niche distros
- [ ] xbps (Void) package
- [ ] apk (Alpine) package
- [ ] eopkg (Solus) package

**Comment by Wiener234** [comment]
Is there a real value behind getting the .deb package into a ppa?
I mean that the only thing that needs to be updated is the ani-cli script and that is already build into it (`ani-cli -U`). 

While the point of easy install with a ppa is not realy given 'cause you need to find the link for the ppa and add the ppa. You can also just download the .deb and install it with `apt install /location/to/.deb`.

**Comment by port19x** [comment]
> Is there a real value behind getting the .deb package into a ppa? I mean that the only thing that needs to be updated is the ani-cli script and that is already build into it (`ani-cli -U`).
> 
> While the point of easy install with a ppa is not realy given 'cause you need to find the link for the ppa and add the ppa. You can also just download the .deb and install it with `apt install /location/to/.deb`.

I mean we need the .deb first anyway.
After that our own repo / ppa would be an optional intermediate step before we get into downstream repos

**Comment by Wiener234** [comment]
Could someone check over the content of the copyright file to make sure there is no mistake. https://github.com/Wiener234/ani-cli/blob/build-deb/debian/copyright

If there are non then the Debian package would be ready and i would go ahead and create a ppa for it and see how to get it into the Debian repo.

**Comment by Derisis13** [comment]
I'll check it, but I want to do it more thoroughly, so it'll take some time.

**Comment by YusufKhan-gamedev** [comment]
Extension: Ubports support

**Comment by Derisis13** [comment]
Experimental .rpm packages are available from https://copr.fedorainfracloud.org/coprs/derisis13/ani-cli/

**Comment by Wiener234** [comment]
Short update on the .deb package. I'm looking for a sponsor right now. If i found one the package should land in the official repo.

**Comment by Derisis13** [comment]
> Short update on the .deb package. I'm looking for a sponsor right now. If i found one the package should land in the official repo.

Wow, nice! What kind of sponsor are you looking for and why is it a prequisite for having a package in the official repo?

**Comment by Wiener234** [comment]
> Wow, nice! What kind of sponsor are you looking for and why is it a prequisite for having a package in the official repo?

A sponsor is someone who has the rights to upload a package to the official repo when the person packaging doesn't have it.

**Comment by Wiener234** [comment]
Regarding the ani-cli package in the offical repos, someone else is also working on that and i will leave it up to that person. https://mentors.debian.net/package/ani-cli/ 

I will continue to maintain the PPA until the package gets accepted into the offical repos.

**Comment by cprin21** [comment]
> Also having a flatpak (that depends on flatpak mpv) might be the solution for flatpak mpv support

It would be fantastic to have a flatpak with all optional dependencies for ani-cli such as VLC installed alongside for the same feature list as the current non containerized version.

**Comment by Derisis13** [comment]
Unfortunately the sandbox nature of flatpaks makes it difficult to package ani-cli without modification. I want to give it another shot, however it'll take me some research and even then I don't know if its possible.

**Comment by werdahias** [comment]
Official debian package is live

**Comment by 71zenith** [comment]
Ubuntu package is live as well

**Comment by werdahias** [comment]
Just Mantic though, it got synced from debian. I uploaded 4.4 earlier today, it should hit the mirrors soon

**Comment by 71zenith** [comment]
> Just Mantic though, it got synced from debian. I uploaded 4.4 earlier today, it should hit the mirrors soon
hey, can u upload the latest version 4.5? we released it around 2 weeks ago

**Comment by werdahias** [comment]
@71zenith  done. next time please use reportbug and open a bugreport for it.

**Comment by 71zenith** [comment]
sure, ill do that from next time

**Comment by port19x** [comment]
I'll be looking into an alpine package

**Comment by port19x** [comment]
Btw I'm pretty sure we can get into homebrew by now, since we have a full non-interactive usage option now.
That was the main issue, since homebrew downstream is to stupid to grasp how an interactive program works, v1.6 was unfit for inclusion like 1.5 years ago

**Comment by samejima-san** [comment]
downloading a season would be nice

**Comment by port19x** [comment]
That's important enough for it's own issue probably, will do

**Comment by port19x** [comment]
Closing in favor of #1203
