### ISSUE TITLE
[Feature request] Add `-` flag for stdin

### ISSUE THREAD

**Issue by paniash** [pystardust/ani-cli#7]
Adding a `-` flag for stdin would be useful for scripting.

**Comment by pystardust** [comment]
unfortunately, since this script is interactive, and takes stdin from the user, it won't work in a pipeline. So stdin would not work, unless something like dmenu is integrated for the anime-selection and the episode selection

**Comment by ura43** [comment]
As pystardust said, this option conflicts with the scripts interactive nature. 
Before this issue can be resolved, a major rewrite enabling non-interactive usage would be nescessary.
Such a rewrite isn't managable in the foreseeable future
