### ISSUE TITLE
Anime Resolutions

### ISSUE THREAD

**Issue by Narchy666** [pystardust/ani-cli#702]
I noticed that when it migrated from gogoanime to gogoplay some animes atleast for me only load in 360p resolution, is this an issue with the website, or the video player? is there any way to request for an specific resolution ?

**Comment by CoolnsX** [comment]
Is ur internet connection is fast??
Also if u r watching older anime.. they are in 360p resolution maybe

**Comment by toxicduccinator** [comment]
you can do `ani-cli -q best -c` to specify the best quality, but its probably just the anime is in 360p resolution on the website.
