### ISSUE TITLE
error /usr/bin/ani-cli: line 234: [ : auto: integer expression expected with any anime

### ISSUE THREAD

**Issue by toxicduccinator** [pystardust/ani-cli#703]
**Metadata**
Version: r560.f7d65fd-1 / currently latest git version
OS: manjaro
Shell: bash 5.1.16
Anime: any

**Describe the bug**
the fix for audio only completely breaks playing, no video, no audio, mpv doesn't show up on htop.
returns error /usr/bin/ani-cli: line 234: [ : auto: integer expression expected
replacing "auto" with "$links_count" on lines 232, 236 fixes the error, but makes the audio only bug come back (on naruto_shippuden ep 79-80 and some more)
**Steps To Reproduce**

1. run `ani-cli` and play any anime

**Expected behavior**
not getting an error, and mpv opening up

**Screenshots (if applicable; you can just drag the image onto github)**
getting the error with any anime
![screenshit2](https://user-images.githubusercontent.com/60573914/166141270-8e5354c6-df95-4ff5-8cd1-470d50d04cf1.png)
![screenshit1](https://user-images.githubusercontent.com/60573914/166141271-4ebc93ec-46c4-4fa2-9785-c9dcd61093df.png)

"auto" replaced with "$links_count" on lines 232, 236, no error, but only audio is playing, and no mpv window is popping up
![screenshit3](https://user-images.githubusercontent.com/60573914/166141268-d2b7faa0-de9c-4289-aa5a-504004e22fdb.png)

**Comment by iamchokerman** [comment]
(by version we mean ani-cli version)

**Comment by CoolnsX** [comment]
I already got the bug.. I just need more time cause I m busy somewhere..

**Comment by savantshuia** [comment]
The big (I think) arises from the video quality variable in the script called `idx`.
this is line 234 (the line the error is complaining about). 
This isn't a fix per-say, but you can prevent is my setting the quality manually using the `-q` flag, but if the selected resolution is not available, it will fallback to the best quality.

`Invalid Choice`
`Current video quality is not available (defaulting to best quality)`

So choose a resolution that is available and you can circumvent this bug.

It's this `if block` in the script btw, lines 234-237:
`
	if [ "$idx" -lt 1 ] || [ "$idx" -gt "$links_count" ];then
		err "Current video quality is not available (defaulting to best quality)"		 
		idx="auto"
	fi
`

**Comment by iamchokerman** [comment]
should be fixed in #704
