### ISSUE TITLE
"Video URL not found error"

### ISSUE THREAD

**Issue by forsyth47** [pystardust/ani-cli#710]
Version: [2.1.0]
OS: [ Windows 10 ]
Shell: [ Gitbash, Powershell-admin ]
Anime: literally every single one! [Checked: Naruto, Serial Experiment lain, One piece and many more]

The Anime Doesn't loads, I've installed mpv too, kindly check the screenshot
after selecting the anime and episode, it jus say "Video URL not found!"

`base64: invalid input`
`bad decrypt`
`7160:error:0606506D:digital envelope routines:EVP_DecryptFinal_ex:wrong final block length:../openssl-1.1.1n/crypto/evp/evp_enc.c:599:`
`Video URL not found`

**Steps To Reproduce**

1. Run `ani-cli Naruto`
2. Choose 1 (Naruto)
3. Choose episode 1 [or any]

![image](https://user-images.githubusercontent.com/88034696/166649400-4e1b8f37-f7aa-483b-9890-5a6ad6d71c54.png)

**Comment by port19x** [comment]
You had me worried there for a second...
Since you're running v2.1.0 this is expected
`ani-cli -U` should resolve the issue
