### ISSUE TITLE
Downloads not working while connected to the internet...

### ISSUE THREAD

**Issue by Breadleaf** [pystardust/ani-cli#711]
**Metadata (please complete the following information)**
Version: 2.1.0
OS: 5.10.109-1-MANJARO
Shell: bash
Anime: all that I have tried in the past week have this issue

**Describe the bug**
Downloading is broken.

**Steps To Reproduce**

1. Run `ani-cli -d dbz`
2. Choose 1 (Dragon Ball Kai 2014 Dub)
3. Choose episode 1

**Expected behavior**
Downloading should work

**Screenshots**
![Screenshot from 2022-05-04 14-51-02](https://user-images.githubusercontent.com/62030791/166823810-e9e0ee86-2384-44bb-88d3-5fc704ed2b41.png)

**Comment by iamchokerman** [comment]
update ani-cli with `ani-cli -U`

**Comment by Breadleaf** [comment]
Oh that did the trick. unsure if I was supposed to update with root privilege but it wouldn't work without them. anyways that fixed it :) thank you
