### ISSUE TITLE
patch: command not found

### ISSUE THREAD

**Issue by BRINGit34** [pystardust/ani-cli#714]
Version: [1.0.0]
OS: [Fedora 35]
Shell: [Bash]
Anime: [Spirited Away] 

**Describe the bug**
Video url not found 
Even after running sudo ani-cli -U I get the error
When I ran the update command is says /usr/local/bin/ani-cli: line 78: patch: command not found 

**Steps To Reproduce**

1. Run `ani-cli spirited away`
2. Choose 2 (Spirited-away-dub)

**Expected behavior**
Video plays

**Screenshots 
![2022-05-05T21:41:13,364802110-05:00](https://user-images.githubusercontent.com/67086183/167059189-b9f5dd47-84a2-4fcf-b84d-94628b44a816.png)
![2022-05-05T21:49:09,043039635-05:00](https://user-images.githubusercontent.com/67086183/167059191-5f211078-93b4-4b83-ada1-e49f27a6397a.png)

**Comment by blycr** [comment]
Same bug

**Comment by Derisis13** [comment]
This is because you're missing the patch tool. Install it (`# dnf install patch` on fedora 35) and run `ani-cli -U` again.

**Comment by BRINGit34** [comment]
ahhh. I don't believe patch is listed in your dependencies but I should have assumed I needed to install it. I didn't realize it was a package. But yes that solved my problem. Thank you
