### ISSUE TITLE
slow loading of old anime

### ISSUE THREAD

**Issue by Filthyhqhq** [pystardust/ani-cli#717]
Version: [e.g. 2.0.2]
OS: [Artix Linux]
Shell: [zsh]

**Describe the bug*
When searching for an anime like end of evangelion or cowboy bebop mpv doesn't load but when I search for new anime like komi-san can't communicate it works fine. I tried updated the script but nothing changed

**Steps To Reproduce**

1. Run `ani-cli cowboy bebop`
2. Choose 2 (cowboy bebop)
3. Choose episode 1

**Expected behavior**
Episode should start in mpv

**Comment by toxicduccinator** [comment]
can't reproduce with latest version(2.2.0) but episode took 20 seconds to load, maybe it just takes a while to load for you.

**Comment by CoolnsX** [comment]
We know the issue here.. it's just for old anime.. cause the alternative providers we scrape from doesn't have links.. so script fallbacks to gogoanime direct links.. which are slow..

**Comment by Derisis13** [comment]
I also had an issue with the first ep. of Kaguya s3, where it was a valid link with invalid content. To prevent this happening either we can implement a `safe-replay` (always selects goload, found in the menu, used on a per episode basis) or an entire safemode (program argument, selects goload for that instance of the script). I'd personally prefer the first, if the two solutions are similar in complexity

**Comment by port19x** [comment]
Just to document, it took 4 seconds to get the link and another 9 for mpv to start playing. This is with cowboy bebop ep1
