### ISSUE TITLE
Can't watch anime from the new termux pkg

### ISSUE THREAD

**Issue by TheRealOne78** [pystardust/ani-cli#718]
**Metadata (please complete the following information)**
Version: 2.2
OS: Termux android 12
Shell: zsh
Anime: any

**Describe the bug**
The old md file explained how to link mpv with the android installed mpv. Now the md file only explains how to install the pkg file, but not how to link mpv(from termux) to mpv(android)

**Steps To Reproduce**

1. Install ani-cli from pkg and apt with `pkg install ani-cli`
2. Search anime from ani-cli and play it
3. Mpv android does not open anymore, only audio plays

**Expected behavior**
ani-cli should have opened the anime in mpv android

**Comment by TheRealOne78** [comment]
It also looks like this issue would be somewhat related to #697

**Comment by port19x** [comment]
@CoolnsX Is this on your radar?
I hope we can semi-automate installation via the termux package, so I still believe the solution is a better termux package and not completely reverting to the previous termux install

**Comment by CoolnsX** [comment]
Yup..

**Comment by TheRealOne78** [comment]
Until the problem is solved, the readme.md could still contain 
```
echo 'am start --user 0 -a android.intent.action.VIEW -d "$1" -n is.xyz.mpv/.MPVActivity' > $PREFIX/bin/mpv
```

**Comment by port19x** [comment]
We need to add the following to the termux build.sh
```
echo 'am start --user 0 -a android.intent.action.VIEW -d "$1" -n is.xyz.mpv/.MPVActivity' > $PREFIX/bin/mpv
```
In the process we can remove the mpv dependency, since we use the external mpv dependency.
We may also want to print a notice to the screen that the external mpv android app is required

**Comment by CoolnsX** [comment]
U do it... I m currently analysing how to scrape animixplay..

**Comment by CoolnsX** [comment]
Also I will be busy for 1 month cause semester exam...

**Comment by port19x** [comment]
> U do it... I m currently analysing how to scrape animixplay..

Alright

**Comment by port19x** [comment]
PR opened

**Comment by port19x** [comment]
Should be fixed now, can someone confirm?

**Comment by TheRealOne78** [comment]
Indeed it works as expected, very nice :D
