### ISSUE TITLE
Option to know if an episode is a filler 

### ISSUE THREAD

**Issue by akash-258** [pystardust/ani-cli#723]
**Is your feature request related to a problem? Please describe.**
Needed some way to know if an episode is a filler in the script itself.
Currently, I have to open a filler-site page for that anime and search for that episode, if it's filler or not, currently watching detective Conan, and it's very irritating.

**Describe the solution you'd like**
Something like `Loading episode 219...(Filler)`, usually it takes about 3-4 sec for an episode to appear after this shows up in terminal, will give anyone enough time to know if the episode is filler.
The 'Filler' tag can be of a different color if needed.

**Describe alternatives you've considered**
A custom command while launching script to skip fillers, eg `ani-cli -f detective conan`. Launching any anime with this sub-command skips fillers.

**Comment by Derisis13** [comment]
This is not in the scope of the project, we won't implement a system for this (in the forseable future at least). 

This could be a separate project: program that scrapes the filler list and edits your ani-hsts file, skipping over the fillers on demand.

**Comment by MitchMarq42** [comment]
Hey @akash-258 

For Conan specifically you can use something like:
```sh
curl -s 'https://www.xerblade.com/p/detective-conan-important-episode-list.html?m=0' | sed 's/></>\n</g' | sed -nE 's/^.*dc-list-no.>([0-9]*(-[0-9]*)?).*span.*$/\1/p'
```
to get a list of non-filler episodes. I ran into this a while back and thought I may as well share it somewhere.
You can probably make that output a whole lot prettier and expand the ranges for interoperability.

**Comment by akash-258** [comment]
@MitchMarq42 Thank you so much for the amazing list of important episodes, will learn shell scripting for trying out the things done in the script.

**Comment by iamchokerman** [comment]
```sh
curl -s 'https://www.xerblade.com/p/detective-conan-important-episode-list.html?m=0'|grep -Eo "dc-list-no\'>[0-9].*?<"|sed -nr 's/.*>(.*)<.*/\1/p'
```
this will fix the empty lines and not skip a few edge cases
