### ISSUE TITLE
Syncplay doesn't work with old anime

### ISSUE THREAD

**Issue by Wiener234** [pystardust/ani-cli#724]
**Metadata (please complete the following information)**
Version: 2.2
OS: Windows10/11; Arch
Shell: bash; cmd( or whatever is used under windows)
Anime: Attack on Titan season 1, One Piece early episodes, Naruto

**Describe the bug**
When using Syncplay with Animes that are loaded from urls similar to www05.gogocdn.stream the anime wont open in mpv and isn't watchable this way.

Syncplay opens with no issue. And other urls can still be loaded after.

**Steps To Reproduce**

1. Run `ani-cli -s One Piece`
2. Choose 1 (One Piece)
3. Choose episode 1

**Expected behavior**
Start Syncplay (works)
open mpv (works)
play episode (doesn't work)

**Screenshots (if applicable; you can just drag the image onto github)**
![image](https://user-images.githubusercontent.com/70913337/169525285-25e051be-c877-4909-ab4b-0623019eca6c.png)

**Additional context**
When choosing the url manually it still wont open. (No issue with trusted domains)

**Comment by iamchokerman** [comment]
also broken for me, i'll see what can be done

**Comment by iamchokerman** [comment]
could you test it out and tell me if it works with spy x family ep1? @Wiener234

**Comment by Wiener234** [comment]
For spy x family it works. It also uses a different url for it.

**Comment by iamchokerman** [comment]
yep, i'm just troubleshooting rn, so wanted to make sure

**Comment by iamchokerman** [comment]
looks like this only happens with m3u links, so mostly for old animes. i'll probably not be fixing this anytime soon, but instead you'll have to wait for ani-cli v3 where we'll scrape animixplay, since there the links will be mp4
