### ISSUE TITLE
Can't open anime

### ISSUE THREAD

**Issue by NaufalF22** [pystardust/ani-cli#725]
**Metadata (please complete the following information)**
Version: Latest
OS: ANDROID 11
Anime: Shachiku-san

**Describe the bug**
Just can't open any anime

**Steps To Reproduce**

1. Run `ani-cli -d flcl`
2. Choose 2 (fooly-cooly)
3. Choose episode 1

**Expected behavior**
Downloading should work

**Screenshots (if applicable; you can just drag the image onto github)**
![Screenshot_2022-05-21-18-36-31-270_com termux](https://user-images.githubusercontent.com/63091744/169649967-ac0476f0-8fed-4924-986b-2103923d6c1f.jpg)

**Additional context**

**Comment by iamchokerman** [comment]
can't reproduce (in Termux), update ani-cli with `ani-cli -U`

**Comment by NaufalF22** [comment]
> can't reproduce (in Termux), update ani-cli with `ani-cli -U`

After update termux just doesn't recognize mpv anymore

**Comment by iamchokerman** [comment]
```sh
echo 'am start --user 0 -a android.intent.action.VIEW -d "$1" -n is.xyz.mpv/.MPVActivity' > $PREFIX/bin/mpv
```

**Comment by NaufalF22** [comment]
> 

![Uploading Screenshot_2022-05-21-19-58-16-272_com.termux.jpg…]()
Still error

**Comment by CoolnsX** [comment]
Do u hv mpv-android installed??

**Comment by CoolnsX** [comment]
https://play.google.com/store/apps/details?id=is.xyz.mpv

**Comment by CoolnsX** [comment]
> After update termux just doesn't recognize mpv anymore

We need more info.. like do u hv external mpv installed right?? And check for other anime..

**Comment by NaufalF22** [comment]
> > After update termux just doesn't recognize mpv anymore
> 
> We need more info.. like do u hv external mpv installed right?? And check for other anime..

![Screenshot_2022-05-22-12-16-06-845_com termux](https://user-images.githubusercontent.com/63091744/169679935-5a8a11d5-3bdf-4f76-95ce-bfb26702cc88.jpg)
Yes mpv is installed 
![Screenshot_2022-05-22-12-17-57-854_com termux](https://user-images.githubusercontent.com/63091744/169679981-03e7bbd4-fe86-4c40-a8a1-8d138c45db1a.jpg)
I tried another anime and still gave me same result

**Comment by CoolnsX** [comment]
do one thing.. run this step wise..
1. ```script````
2. ``` ani-cli -a1000 one piece```
3. ```exit```

there is a file called ```typescript``` in current directory.. send me that file..

**Comment by CoolnsX** [comment]
> do one thing.. run this step wise..
> 
> 1. `script`
> 2. ` ani-cli -a1000 one piece`
> 3. `exit`
> 
> then there will be a file created called `typescript` in current directory.. send me that file..

Nvm.. we Found the bug and patched it.. turns out u need to add referrer to your mpv.conf.. see readme
