### ISSUE TITLE
Automatically detect video player using xdg-mime

### ISSUE THREAD

**Issue by HiNice2MeetU** [pystardust/ani-cli#728]
**Is your feature request related to a problem? Please describe.**
Can we have an option to automatically figure out the video player you want to use using the xdg preferences?

**Describe the solution you'd like**
like maybe -x to automatically detect video player using something like `xdg-mime query default "video/mp4"`

**Describe alternatives you've considered**
Maybe you could also have a flag to specify a video player by name, but that seems annoying to type in every time and this seems easier

**Comment by CoolnsX** [comment]
We can't.. cause we pass multiple things to video player along with url.. like referrer, display name etc.. also some video player doesn't support referrer links..

**Comment by HiNice2MeetU** [comment]
oh ok thx anyways :)
