### ISSUE TITLE
Connection Problems on version (2.2) - Windows Git-Bash

### ISSUE THREAD

**Issue by HayateLaTech** [pystardust/ani-cli#729]
**Metadata (please complete the following information)**
Version: 2.2
OS: Windows 10
Shell: Git Bash
Anime: any

**Describe the bug**
Anime-Searching results in "No search results found"
ani-cli -U results in "Connection Error"

**Steps To Reproduce**

1. Run `ani-cli -U`
2. Run `ani-cli`
3. get prompted with connection errors

**Expected behavior**
Updating as well as searches should work.

**Additional context**
I use Terminal (installed from Microsoft Marketplace) to handle console sessions - including Git Bash.
I also installed ani-cli to my WSL and searches + updating work like a charm there. (but hooking that into my Windows MPV doesn't work, so I had to use scoop after all.)
The git-bash session is able to ping google.com, so internet connection should be possible.

I tried re-installing ani-cli through scoop already but that didn't help. Scoop is also able to connect to the internet through git-bash.

On the first day of installation, ani-cli worked perfectly fine. I was able to search + view anime via mpv on said first day. Problems began after rebooting.

**Comment by HayateLaTech** [comment]
> Can you ping `goload.pro`? It might have been blocked somewhere upstream.

I am able to ping `goload.pro` via git-bash.

**Comment by RaynardGerraldo** [comment]
> **Describe the bug** Anime-Searching results in "No search results found" ani-cli -U results in "Connection Error"

`ani-cli -U` makes a request to github, so this shouldnt be a problem. 
Is this the error message: "Can't update for some reason!"? If not then its not an ani-cli error, you can also share a screenshot

**Comment by HayateLaTech** [comment]
I found the Issue.

When starting a laravel docker image using [Sail](https://laravel.com/docs/9.x/sail) (which itself starts services like a php, mysql, redis server etc.) it for some reason blocks ani-cli from connecting anywhere XD

I'm not sure why this happens but I can only assume a port getting blocked by a service or maybe the bridge network adapter causing shit x3
It works flawlessly once the docker image is turned off.
