### ISSUE TITLE
.cache/ani-hsts: No such file or directory

### ISSUE THREAD

**Issue by salaadas** [pystardust/ani-cli#73]
I went through the process on Windows, installing vlc and git clone the ani-cli-win branch although I couldn't run the "make" command. It worked although when playing the video it doesn't show the menu option and also show the No such file or directory message, couldn't scrub the video either.

**Comment by Inn0360** [comment]
Works as suggested

**Comment by Jonathan-K88** [comment]
I'm having the same issue. I clone the git request, cd into ani-cli, and run sudo make, but when I try to run ./ani-cli, I receive ./ani-cli: line 149 /Users/<my_user_name>/.cache/ani-hsts: No such file or directory.

**Comment by ura43** [comment]
This seems to be a windows compatibility issue. The script shouldn't expect a unix directory structure on a windows host.
