### ISSUE TITLE
VLC sound issues

### ISSUE THREAD

**Issue by McUberStein** [pystardust/ani-cli#731]
**Metadata**
Version: 2.2.0
OS: Gentoo Linux
Shell: Bash
Anime: Shingeki no Kyojin The Final Season part 2

**Describe the bug**
When playing any episode of the final season part 2 of Aot, VLC starts acting weird. Seeking or skipping ahead by any amount breaks sound, and then I am completely unable to change the player position with the video playing. Seems to only happen with this anime.

**Steps To Reproduce**

1. Run `ani-cli`
2. Choose AOT Final Season part 2
3. Select any episode
4. Skip ahead or seek

**Expected behavior**
Sound and player position should work fine

**Comment by McUberStein** [comment]
I have tried clearing history, reinstalling ani-cli and removing the whole cache directory, but nothing helped. VLC works just fine with local videos and with other anime titles available with ani-cli.

**Comment by Derisis13** [comment]
Are you sure this is not a VLC bug? Can you check if the same happens with other internet streams that are played in VLC?

**Comment by McUberStein** [comment]
Yeah, it might just be a VLC bug. My bad. Works just fine with MPV. It's just strange that every network stream I have tried playing with VLC works perfectly, the majority of titles on ani-cli works just fine, except for the final season of Aot.
