### ISSUE TITLE
search doesn't work in English

### ISSUE THREAD

**Issue by The-Deepest-Net** [pystardust/ani-cli#738]
**Metadata**
Version: 2.2.0
OS: [Arco Linux   `linux version: 5.15.36-1-lts`]
Shell: [dash]
Anime: [tested on "attack on titan"]

**Describe the bug**
when I search on Anime in **English** like (attack on titan) it returns `"No search results found"`, but when the search is in original name in **Japanese** it works normally, but with other animes, it works perfectly like (Death Note).

**Expected behavior**
Searching should work

**Screenshots**
![ani-cli_bug](https://user-images.githubusercontent.com/75685524/171465065-e14ef98b-81ff-4020-9056-100c9850d04c.png)

**Additional**
What  I was wondering was that in older versions, it was working perfectly, but I don't know why it doesn't work now.

**Comment by justchokingaround** [comment]
goload's fault (the provider we're scraping), not ours. expect this to be fixed in v3 when we switch to animixplay
