### ISSUE TITLE
Episode selection problem

### ISSUE THREAD

**Issue by guy-732** [pystardust/ani-cli#740]
Version: 2.2
OS: Ubuntu 20.04
Shell: bash
Anime: Tensei Shitara Slime Datta Ken

**Describe the bug**
So as you can see here, there are 2 episodes marked as `24.5` and `24.9` respectively
![image](https://user-images.githubusercontent.com/81652178/172032617-9c65c451-0e2b-4f56-b33f-c1ecbb0cbc26.png)
Now problem is, ani-cli can only see those 2, the others don't exist

**Steps To Reproduce**

1. Run `ani-cli Tensei Shitara Slime Datta Ken`
2. Choose 1 (this)
![image](https://user-images.githubusercontent.com/81652178/172032682-eff74c47-7b6e-4132-8f5e-e37a88e7b327.png)
I can only select 5-9... note 6, 7 and 8 do not exist when I try them and 5 leads to 24.5, 9 leads to 24.9

**Expected behavior**
I should be able to select episode 1-24
24.5 and 24.9 should not even be accessible as said in #523 however, I can only select those 2

**Comment by ames0k0** [comment]
It starts from here: https://github.com/pystardust/ani-cli/blob/master/ani-cli#L366

- [ ] parse the `last_ep_number` from the url itself ?!
```sh
# okay: tensei-shitara-slime-datta-ken-2nd-season-part-2-episode-12
# not okay: tensei-shitara-slime-datta-ken-episode-24-9
last_ep_number="$(printf "%s" "$selection_id" | sed 's/-episode-/ /g' | awk '{ print $NF }' | cut -d'-' -f1 ))"
```
- [ ] `first_ep_number=1` or it needs any checks (`check_episode`) ?!
- [ ] for loop per *ep_number to check *sub_ep_numbers ?!

Fixing by Brute-Force the *sub_ep_numbers :)
-or parsing the whole *ep_numbers and store only *sub_ep_numbers to check on updating the *ep_number (`episode + 1`)

**Comment by justchokingaround** [comment]
@guy-732 this will be fixed in v3, where we switch to animixplay (no .x episodes)
also @ames0k0 shouko's sister = mega valid pp <3
