### ISSUE TITLE
Add suggestions 

### ISSUE THREAD

**Issue by CaffeineB34r** [pystardust/ani-cli#747]
**Is your feature request related to a problem? Please describe.**
Sometimes I want to watch something new, 
but don't want to search suggestions online to then open the cli

**Describe the solution you'd like**
Please add a flag `-s` to list about `10` or so of the front page or popular suggestions

**Describe alternatives you've considered**
Just play something random that is not in my history.

**Comment by junguler** [comment]
this is an amazing idea, i would love such an option too

**Comment by port19x** [comment]
If there is a way to integrate a more sophisticated recommender than just including the top10 of whatever site I'd use it too.
My watch list is shrinking...

**Comment by justchokingaround** [comment]
i'll look into it 👍

**Comment by CoolnsX** [comment]
I think this is already been integrated as ```-n``` args... So closing this issue now
