### ISSUE TITLE
Don't auto-play from -c if there's only one unfinished anime in history

### ISSUE THREAD

**Issue by IsHARI** [pystardust/ani-cli#754]
**Is your feature request related to a problem? Please describe.**
Currently, if I use the `-c` flag, the behavior is different depending on whether I have one or more show with unwatched episodes in my history. If it's more than one, a list of shows with unwatched episodes is displayed. But if it's only one, the new episode automatically plays. Let's say I watch two shows. Show A is still coming out, while show B is already finished. Sometimes I want to see if there's a new episode of show A, but if there isn't, the `-c` flag will automatically play show B, which I'm not in the mood for right now. So I have to close the episode and edit the history file so that I can watch that episode of B another time. A workaround I've been using is just keeping a third show that I'm not going to watch anyway in my history, but that's a bit annoying.

**Describe the solution you'd like**
Change the behavior of `-c` to always show the list of unwatched shows.

**Describe alternatives you've considered**
Maybe instead of changing the behavior of `-c` add a separate flag that always lists the shows (maybe `-H` for history) or a flag that can be combined with `-c` to suppress auto-play (maybe `-x`).

**Comment by port19x** [comment]
> **Is your feature request related to a problem? Please describe.** Currently, if I use the `-c` flag, the behavior is different depending on whether I have one or more show with unwatched episodes in my history. If it's more than one, a list of shows with unwatched episodes is displayed. But if it's only one, the new episode automatically plays. Let's say I watch two shows. Show A is still coming out, while show B is already finished. Sometimes I want to see if there's a new episode of show A, but if there isn't, the `-c` flag will automatically play show B, which I'm not in the mood for right now. So I have to close the episode and edit the history file so that I can watch that episode of B another time. A workaround I've been using is just keeping a third show that I'm not going to watch anyway in my history, but that's a bit annoying.
> 
> **Describe the solution you'd like** Change the behavior of `-c` to always show the list of unwatched shows.
> 
> **Describe alternatives you've considered** Maybe instead of changing the behavior of `-c` add a separate flag that always lists the shows (maybe `-H` for history) or a flag that can be combined with `-c` to suppress auto-play (maybe `-x`).

Thank you for giving such a detailed description of your usecase and workaround.
This behaviour has been introduced because it suits my anime habits quite well, but I'm willing to look into a compromise.

I like to watch one show at a time and never watch airing stuff. On top of that, I try to stick to 1 episode a day. I generally find less keystrokes superior to more keystrokes so in my usage scenario the current behaviour is ideal.

For some history:
Rapid resume got introduced in #555 
And caused confusion at least 2 other times in #577 and #701
