### ISSUE TITLE
Error detecting mpv player on v3

### ISSUE THREAD

**Issue by franl08** [pystardust/ani-cli#755]
**Metadata**
Version: 3.0.0
OS: Arch Linux
Shell: `/bin/bash`

**Explanation**

When trying to run ani-cli (even to see its version), it tells me that doesn't exist any file or directory with the desired path (`/usr/bin/players/player_mpv`). 

**Steps To Reproduce**

1. Run ani-cli with or without any flag.

**Expected behavior**
Doesn't get the error

**Screenshots**
![image](https://user-images.githubusercontent.com/62014132/173462432-72209cb3-38d7-4b1e-b8ed-402aec94e77e.png)

**Additional Context**
On the previous version, it worked perfectly normal.

**Comment by Derisis13** [comment]
Fix described in #748. Or you can wait for the AUR version to release.

**Comment by DaBigBlob** [comment]
@franl08 
anyone on Linux and MacOS can use this:
https://github.com/DaBigBlob/ani-cli/tree/fixed

do not use the main branch on my repo; use the fixed brance;
the main branch id for the pull request: https://github.com/pystardust/ani-cli/pull/753
