### ISSUE TITLE
`/usr/bin/ani-cli: line 470: /usr/bin/players/player_mpv: No such file or directory`

### ISSUE THREAD

**Issue by createvi** [pystardust/ani-cli#759]
Version: Latest on AUR (i can't use the --version flag)
OS: Manjaro Linux
Shell: zsh

ani-cli is not working.
when i run `ani-cli` on  terminal it returns `
/usr/bin/ani-cli: line 470: /usr/bin/players/player_mpv: No such file or directory`

**Steps To Reproduce**

1. Install ani-cli using yay
2. Run `ani-cli`
3. See error

**Expected behavior**
ani-cli should work

**Comment by MushroomGecko** [comment]
I'm getting the same error. I'm also running Manjaro and it also won't even let me see the version or anything without erroring out with that message

**Comment by NaufalF22** [comment]
Same log but with wsl ubuntu

**Comment by DaBigBlob** [comment]
@createvi 
https://github.com/DaBigBlob/ani-cli

**Comment by createvi** [comment]
Your script seems to have issues. i can't search for any anime
![image](https://user-images.githubusercontent.com/93326280/173871317-2b7c6890-500a-4211-8807-3a817d4f19fa.png)

**Comment by DaBigBlob** [comment]
> I'm on linux atm and in ani-cli's code, this seems to happen when the os is detected as darwin.

we're fixing it right now
mean while you can use my fork: https://github.com/DaBigBlob/ani-cli

**Comment by etisHere** [comment]
To fix this just [ sudo cp usr/local/share/ani-cli /usr/local/bin/ ]

**Comment by justchokingaround** [comment]
closing this now, after the readme update, if you get this error check https://github.com/pystardust/ani-cli#Fixing-errors
