### ISSUE TITLE
ani-cli: no search results found

### ISSUE THREAD

**Issue by Ruzie** [pystardust/ani-cli#763]
**Metadata**
Version: 3.0
OS: Debian 11
Shell: zsh
**Describe the bug**
Tried out v3 ani-cli but when I search most recent and known anime's, it didn't found  any results. When I tried that same anime on v1.x I can able to see the search results showed as expected.

**Steps To Reproduce**

1. Grab the latest (v3) ani-cli
2. Run it, and try to search an anime

**Expected behavior**
It should show up most relevant search results.

v3.0 (latest)
![image](https://user-images.githubusercontent.com/71683721/173876528-8e77571f-1c8d-4d2f-ad38-f252552121e8.png)

But it didn't, at last I end up with v1.9.0 which looks like working just fine
![image](https://user-images.githubusercontent.com/71683721/173876672-85acff50-b203-49a7-80e0-bb1f83d06a37.png)

**Comment by justchokingaround** [comment]
fixed with #764
