### ISSUE TITLE
Using && when you can just use ;

### ISSUE THREAD

**Issue by etisHere** [pystardust/ani-cli#765]
I never post on github so my bad if this isn't where to post this but you can swap out the && for simply using a ;  aka [ cmd1 ; cmd2] not [cmd1 && cmd2]

**Comment by justchokingaround** [comment]
they are logically different operators,  `&&` only runs if the previous command succeeded, whereas `;` runs even if the previous fails

a more suitable place to post this kind of comment would be in the Discussions tab https://github.com/pystardust/ani-cli/discussions
