### ISSUE TITLE
Subbed & Dubbed options no longer available

### ISSUE THREAD

**Issue by tpeacock19** [pystardust/ani-cli#766]
**Describe the bug**
Subtitle & Dubbed options no longer available in v3+

**Steps To Reproduce**

1. Run `ani-cli`
2. Search "Spy Family"
3. Results only show subbed versions

**Expected behavior**
Options for subs & dubs should be available

**v3**
```sh
 ❯ ani-cli                                                                                 
Search Anime
> Spy Family
Query Results >> 
(1) Spy x Family
(2) Spy x Family Part 2
(3) Emiya-san Chi no Kyou no Gohan
```
**v2**
```sh
 ❯ ani-cli                                                                                 
Search Anime
> Spy Family
Query Results >> 
(1) spy-x-family
(2) spy-x-family-dub
(3) glass-no-kamen-desu-ga-the-movie-onna-spy-no-koi-murasaki-no-bara-wa-kiken-na-kaori
(4) crayon-shin-chan-arashi-wo-yobu-ougon-no-spy-daisakusen
```
**Additional context**
The recent commit https://github.com/pystardust/ani-cli/pull/764 does not provide Sub/Dub options since it is using MAL and not a streaming provider.

**Comment by justchokingaround** [comment]
#764 introduced the --dub argument, but we forgot to add it to the help menu and readme, will add it in the next commit (today~tomorrow)

to watch spy x family in sub u can use:
```sh
ani-cli spy family
```
and to watch spy x family in dub u can use:
```sh
ani-cli --dub spy family
```

**Comment by tpeacock19** [comment]
great, thank you.

**Comment by CoolnsX** [comment]
fuck.. we are going back to showing dubs in query results..
