### ISSUE TITLE
Dub anime isn't showing while searching

### ISSUE THREAD

**Issue by VasuRamani** [pystardust/ani-cli#772]
**Metadata (please complete the following information)**
Version: 3.0.2
OS: Garuda Linux (Arch based linux fyi)
Shell: fish
Anime: Hellsing ultimate , Naruto

**Describe the bug**
I updated my system with pacman and it fetched update for ani-cli package from AUR maybe and after that some error was showing and i checked issue section and it says reinstall it
so i did reinstall and searched Hellsing anime and there is no dubbed in english for cross check i checked naruto which i have seen and know that it is dubbed also naruto doesn't show dubbed only japanese audio

**Steps To Reproduce**

1. Run ani-cli

**Expected behavior**
anime should show dub version in query list

**Screenshots (if applicable; you can just drag the image onto github)**
![Screenshot_20220617_171105](https://user-images.githubusercontent.com/83487465/174291570-e8355f94-e86f-43b9-9e75-bafcfb9397d5.png)

**Additional context**

**Comment by Derisis13** [comment]
fixed via #767

**Comment by VasuRamani** [comment]
@Derisis13 Arigattou
