### ISSUE TITLE
File System Hierarchy

### ISSUE THREAD

**Issue by tpeacock19** [pystardust/ani-cli#773]
I mentioned this in a recent PR (https://github.com/pystardust/ani-cli/pull/767) but I will expand upon it here. I do not agree with placing internal modules/libraries in the bin directory.

It does not align with the [linux foundation spec](https://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch03s04.html):
> **3.4. /bin : Essential user command binaries (for use by all users)**
> **3.4.1. Purpose**
> /bin contains commands that may be used by both the system administrator and by users, but which are required when no other filesystems are mounted (e.g. in single user mode). It may also contain commands which are used indirectly by scripts. [1]
> **3.4.2. Requirements**
> There must be no subdirectories in /bin.

It also does not follow the Arch Linux [file-heirarchy man page](https://man.archlinux.org/man/file-hierarchy.7#VENDOR-SUPPLIED_OPERATING_SYSTEM_RESOURCES):
> **VENDOR-SUPPLIED OPERATING SYSTEM RESOURCES**
> **/usr/bin/**
> Binaries and executables for user commands that shall appear in the $PATH search path. It is recommended not to place binaries in this directory that are not useful for invocation from a shell (such as daemon binaries); these should be placed in a subdirectory of /usr/lib/ instead.
> **/usr/lib/**
> Static, private vendor data that is compatible with all architectures (though not necessarily architecture-independent). Note that this includes internal executables or other binaries that are not regularly invoked from a shell. Such binaries may be for any architecture supported by the system. Do not place public libraries in this directory, use $libdir (see below), instead.

Please consider reinstating an ani-cli folder in either the `/usr/share` or  the `/usr/lib` directories. @DaBigBlob's PR fixed ani-cli "project root" definition with `project_root="$(dirname "$0" | sed 's/....$//')/share/ani-cli"` which worked just fine. Was there a technical reason as to why this was changed?

**Comment by CoolnsX** [comment]
Yup.. there is..
1. Script debug doesn't work on development ```git clone``` version because of this method..
2. we have to install everytime we make changes to ani-cli for testing and as a developer u know better..
3. Also shell debug doesn't work in installed ani-cli too unless we specifically ```cd``` to that directory and run debug...

P.S. :- I know it's against the rules of file system..  and this comment seems to be biased towards developers.. If I said something wrong somewhere I m very sorry...

**Comment by Derisis13** [comment]
That regex (`....$`) is the worst of all. If we wanted it to work at all we should have used `sed -E 's|\/[^\/]+$||'` for portability.
Even then `dirname $0` returns `.` if the location of the file is the same as the directory you're in, so using a regex to determine the other file's location is problematic to say the least.
Having it hardcoded (eg. to `/usr/lib`) would not allow us to debug the supplementary files without the need to write files in a privileged location (and away from the working directory). This sucks form a development point, as does having to edit the script for development.
The most plausible option for me seems to be to have an environment variable (eg. `$ANI_CLI_LIBS`) which if set overwrites the path set by the regex. This could be done easily (but not simply) trough parameter expansion. The caveat is that it still needs testing on other platforms: termux, git bash and OSX. If it works stably there, I'm open to implementing it.

**Comment by Derisis13** [comment]
If we structure the project to `/bin` (or whatever we call it) and `/lib` folders we might not even need to implement the environment variable.

**Comment by tpeacock19** [comment]
I think that would be the best approach  then using something like this should work in most cases:

```bash
project_root="$(cd "$(dirname "$0")" && pwd)"

bin_dir="$project_root"/bin

lib_dir="$project_root"/lib
players_dir="$lib_dir"/players
# or
share_dir="$project_root"/share
players_dir="$lib_dir"/players
```

I will probably update mine locally here and see if there are any further issues if it helps.

**Comment by Derisis13** [comment]
I like the idea of using cd and pwd, however it needs to be done with caution not to overwrite the download directory. This should be possible.
Corrected version: 
```sh
bin_dir="$(dirname "$0")"
lib_dir="$(cd "$bin_dir" && pwd | sed -E 's|\/[^\/]+$||')/lib"
...
```
I'll go test this version, to see if it works. Yours probably failed, because `dirname "."` returns `.`

**Comment by tpeacock19** [comment]
Yeah I used a combination of our two examples and this seems to work on my fork

```bash
project_root="$(cd "$(dirname "$0")"/../ && pwd)"
bin_dir="${project_root}/bin"
lib_dir="${project_root}/lib/ani-cli"
case "$(uname)" in
	Darwin*) . "$lib_dir/player_iina" || die "No iina player script found";; #MacOS specific
	*) . "$lib_dir/player_mpv" || die "No mpv player script found";;
esac
```

Folder Structure
```bash
 src/github/ani-cli 
 ❯ tree                                                                                                                                         master 4h ● ⬡
.
├── bin
│   └── ani-cli
├── CONTRIBUTING.md
├── disclaimer.md
├── hist_transition.sh
├── lib
│   └── ani-cli
│       ├── player_download
│       ├── player_iina
│       ├── player_mpv
│       ├── player_syncplay
│       ├── player_vlc
│       └── UI
├── LICENSE
├── Makefile
└── README.md

3 directories, 13 files
```

Though I have not looked into update() function.

**Comment by Derisis13** [comment]
I'm gonna yoink that solution, thank you very much. Way cleaner then what I could come up with.
