### ISSUE TITLE
Script unable to locate it's own libraries on windows..

### ISSUE THREAD

**Issue by THEGOLDENPRO** [pystardust/ani-cli#775]
Version: 3
OS: Windows 10
Shell: git bash (as recommended to)
Anime: None

**New v3 ani-cli won't work on windows 10. I've uninstalled the previous ani-cli version and followed the readme install steps to install the new version 3 but I get this error when running:**
```
C:\ProgramData\scoop\apps\ani-cli\current\ani-cli: line 470: C:\ProgramData\scoop\apps\ani-cli\current/players/player_mpv: No such file or directory
C:\ProgramData\scoop\apps\ani-cli\current\ani-cli: line 53: err: command not found
```
I can confirm that this is indeed version 3, version 1.9 worked fine. I can also confirm that I updated on my android phone and it worked completely fine, just on windows I'm having this issue.🙁

- I followed these steps: https://github.com/pystardust/ani-cli/tree/master#windows
- I also installed it via scoop using these steps: https://github.com/pystardust/ani-cli/tree/v3#windows

![image](https://user-images.githubusercontent.com/66202304/174459992-9959f9f1-d321-4f2c-9d59-1527ea085e16.png)
![image](https://user-images.githubusercontent.com/66202304/174460013-ea9b8772-e1f4-4d12-9391-ca71910fb7b7.png)

**Comment by Derisis13** [comment]
Can you try running `/usr/local/bin/ani-cli` in git bash?

**Comment by YuleTomalin** [comment]
I don't know if this will work for you cause it did work for me, but you could try copying the files from the folder where git installed ani-cli from (in this case the Program Files/Git/usr/local/bin/ani-cli) to the scoop folder like I did here:
![image_2022-06-21_015107228](https://user-images.githubusercontent.com/79254980/174655758-bd18fe9d-c887-43db-b4e2-9cee410a8f94.png)
I removed them from their respective folders and placed them all at the same folder, which in this case the "current" or "3.0" folder, they're the same I think. This is just a temporary fix though, so this will only work for now. (Tested this on Windows 11 21H2)

**Comment by THEGOLDENPRO** [comment]
> Can you try running `/usr/local/bin/ani-cli` in git bash?

Umm, it says no directory found, I knew the directory didn't exist.
![image](https://user-images.githubusercontent.com/66202304/174679791-fbd2a7c9-81bf-45d9-a902-0ff22dcc4435.png)

**Comment by THEGOLDENPRO** [comment]
> I don't know if this will work for you cause it did work for me, but you could try copying the files from the folder where git installed ani-cli from (in this case the Program Files/Git/usr/local/bin/ani-cli) to the scoop folder like I did here: ![image_2022-06-21_015107228](https://github.com/assets/79254980/bd18fe9d-c887-43db-b4e2-9cee410a8f94) I removed them from their respective folders and placed them all at the same folder, which in this case the "current" or "3.0" folder, they're the same I think. This is just a temporary fix though, so this will only work for now. (Tested this on Windows 11 21H2)

Thanks, I'm going to try this.

**Comment by THEGOLDENPRO** [comment]
@YuleTomalin Thanks so much, that worked. Turns out scoop only downloaded the "ani-cli" file and ignored the rest of the files, I've never used this kind of stuff so I'm not quite sure why but hey git cloning and moving the files to the scoop files worked.

**When I Installed it [this way](https://github.com/pystardust/ani-cli/tree/v3#windows):**
![image](https://user-images.githubusercontent.com/66202304/174680579-52b159bf-34ef-4b7f-8ec4-2fbd2af7e053.png)

**Just moving the files in myself:**
![image](https://user-images.githubusercontent.com/66202304/174680728-7e30d330-ed4a-4204-a18e-83cd095525da.png)

I hope you guys can find out the issue, if you want me to provide anything else to help just ask.

**Comment by Derisis13** [comment]
So did it turn out to be a scoop issue? If so you can try contacting the scoop package maintainer to issue a fix

**Comment by xxiz** [comment]
### I had the same problem and this is how I resolved it, incase it helps someone

![image](https://user-images.githubusercontent.com/69374625/175440123-ff5ff8e2-d100-4c59-ab46-5fdeddc02d37.png)

- Downloaded the [lastest source code](https://github.com/pystardust/ani-cli/releases)

- Navigate to the directory where it says the file is missing `C:\Users\Ashwi\scoop\apps\ani-cli\` in my case
![image](https://user-images.githubusercontent.com/69374625/175440278-675b10a7-6af4-41c5-8e32-3feb808b599f.png)

- Copy the libraries from the _lib_ folder in the source code
![image](https://user-images.githubusercontent.com/69374625/175440238-7bf14926-cbf6-4df1-bf97-620cdee3a0ee.png)

- Create a folder called _players_ in the _current_ folder, and copy everything to the _players_ folder as well as the _current_ folder. 
![image](https://user-images.githubusercontent.com/69374625/175440546-c0abdff1-f47f-4fd1-af0d-a84154dfed95.png)

**Comment by THEGOLDENPRO** [comment]
@xxiz yep can confirm that temporary fixes the issue.

**Comment by THEGOLDENPRO** [comment]
> So did it turn out to be a scoop issue? If so you can try contacting the scoop package maintainer to issue a fix

Yeah but also idk if it's just me, but when I followed the windows install instructions on the repo I couldn't install as I stated in my original message so I used scoop instead. It said it couldn't find that ``usr`` folder as stated here: https://github.com/pystardust/ani-cli/issues/775#issuecomment-1160860989

**Comment by hamedrajhi** [comment]
I ran into the same issue using macOS as well, the previous version  was working fine though.

**Comment by justchokingaround** [comment]
> I ran into the same issue using macOS as well, the previous version was working fine though.

just follow the macOS instructions from the readme and everything should be fine

**Comment by hamedrajhi** [comment]
It's an issue with the latest version, after updating the script I ran into this error message
"/usr/local/bin/ani-cli: line 1: 404:: command not found"
<img width="501" alt="Screen Shot 2022-07-16 at 9 53 42 PM" src="https://user-images.githubusercontent.com/66348992/179371654-993354a6-75c9-4634-a4c0-74e37b4e6033.png">

I reinstalled ani-cli following the instructions in the redeem but the issue remains. 

so I tried installing version 2 instead and it worked fine, updated the script for the second time just to test it and it broke again.

**Comment by CoolnsX** [comment]
We are now back to onefile.. please follow new installation commands again... Or better wait for scoop package.. closing this issue now
