### ISSUE TITLE
What is /usr/local/bin supposed to be in windows?

### ISSUE THREAD

**Issue by ash-hashtag** [pystardust/ani-cli#777]
Version: 3.0
OS: [e.g. Windows 11
Shell: git bash
Anime: 

installation instruction on windows doesn't work

**Comment by Derisis13** [comment]
What exactly did you do and what errors do you get?
/usr/local/bin should be set by git bash, if you want to get the exact location it points to, take a look at their documentation.

**Comment by YusufKhan-gamedev** [comment]
Same issue on arch linux with fish here, updating bricks ani-cli, /usr/local is set for the place that ani-cli is updated even though I dont have ani-cli there, I dont even have /usr/local on my system.

This isnt the least of my problems, I suggest @ash-hashtag just use ani-cli v2 as that is not broken, maybe when v4 comes out switch to that, or maybe all of the bugs will be ironed out in a couple months.
