### ISSUE TITLE
Some anime's doesn't show up in the search

### ISSUE THREAD

**Issue by daromer** [pystardust/ani-cli#783]
**Metadata (please complete the following information)**
Version: 2.2.0
OS: Linux Mint 20.3
Shell: [e.g. zsh, run `readlink /bin/sh` to get your shell]
Anime: Overlord Ple Ple Pleiades

**Describe the bug**
Search is broken
Doesn't show up the first season of overlord ple ple pleiades, but shows up the 2nd and 3rd season

**Steps To Reproduce**

1. Run `ani-cli -d Overlord Ple Ple Pleiades`

**Expected behavior**
Show up all Overlord Ple Ple Pleiades Seasons

**Screenshots (if applicable; you can just drag the image onto github)**
![image](https://user-images.githubusercontent.com/2442458/174858751-30659344-1f58-4276-b123-0fac1e139516.png)

**Additional context**

**Comment by CoolnsX** [comment]
we are on version v3.2 which is using new site for scraping... please upgrade to latest by following readme instructions..

**Comment by daromer** [comment]
followed instructions for installation again, got an error, documented it in the following https://github.com/pystardust/ani-cli/issues/791

**Comment by justchokingaround** [comment]
fixed in #797
