### ISSUE TITLE
slow caching when watching anime, some anime start at worst quality.

### ISSUE THREAD

**Issue by amonull** [pystardust/ani-cli#785]
**Metadata (please complete the following information)**
Version: 3.2.0
OS: Void Linux
Shell: bash
Anime: komi cant speak, spy x family, one piece

**Describe the bug**
slow cache when watching anime, some anime (like spy x family) starts in extremely low quality unless -q 1080 tag is specified.

**Steps To Reproduce**
1. Run `ani-cli`
2. Choose spy x family
3. Choose episode 11

**Expected behavior**
mpv should open anime in best available quality and cache speeds shouldn't be extremely slow.

**Additional context**
i attempted to watch different anime in high resolutions and every time that i was watching it in 1080 resolution the caching would be extremely slow, with resolution set to 720 the caching is faster.
sometimes some anime opens in the worst possible resolution.

i've attempted to watch anime using a vpn to see if anything changed but i got the exact same results with the caching slowing down in the exact same spots. this made me think  maybe my internet was the problem so i went to animixplay.to and had no issues with buffering or resolution, and my internet works fine doing anything else.

this issue is recent to me and everything was working fine around 11-12 june.

i've tried downloading the anime which has worked as it is supposed to and i've had no problems with the download speeds, but i did get some errors show up when i was downloading which i've attached below.

![image](https://user-images.githubusercontent.com/90932550/174860984-0fd226bd-51d5-480d-80f2-ec8400feaae9.png)

**Comment by CoolnsX** [comment]
that error can be neglected as long as your video is downloading...

and some providers stores anime in 720p while some stores 1080p and some stores multi quality links..

**Comment by CoolnsX** [comment]
also please refer to this discussion for more info..
#786

**Comment by amonull** [comment]
> also please refer to this discussion for more info.. #786

thanks for the reply choosing a new provider fixed my issue.
