### ISSUE TITLE
cp: cannot stat '/lib/ani-cli': No such file or directory

### ISSUE THREAD

**Issue by llkkdb** [pystardust/ani-cli#788]
running into the above error when installing.
I think we should remove the slash
`sudo cp -a /lib/ani-cli /usr/local/lib` -> `sudo cp -a lib/ani-cli /usr/local/lib`

**Comment by Za-rodnuiu** [comment]
I faced the same issue. Your fix worked perfectly

**Comment by tnjongrosok2** [comment]
yep fixed immediately!
thanks!

**Comment by sajidsarker** [comment]
Alternatively:
`sudo cp -a ./lib/ani-cli /usr/local/lib`
