### ISSUE TITLE
/usr/local/bin/ani-cli: 474: .: Can't open /usr/local/lib/ani-cli/player_mpv

### ISSUE THREAD

**Issue by daromer** [pystardust/ani-cli#791]
**Metadata (please complete the following information)**
Version: don't know, broken
OS: Linux Mint 20.3
Shell: bash
Anime: n/a

**Describe the bug**
app appears to be broken after unistalling and installing it

**Steps To Reproduce**

1. Follow unistall and install instructions
2. Run 'ani-cli'

**Expected behavior**
ani-cli to run ( show the help page at least )

**Screenshots (if applicable; you can just drag the image onto github)**
![image](https://user-images.githubusercontent.com/2442458/175188955-e8544625-28ba-4c4a-9a61-20400b953cba.png)

**Additional context**

**Comment by daromer** [comment]
disregard, following the changes in https://github.com/pystardust/ani-cli/pull/790 for installation fixed this issue

**Comment by justchokingaround** [comment]
#790
