### ISSUE TITLE
/usr/local/bin/ani-cli: line 473: /usr/local/lib/ani-cli/player_iina: No such file or directory

### ISSUE THREAD

**Issue by CannedFoodU** [pystardust/ani-cli#792]
i have followed the installation instructions to install on mac however am getting the issue in the title. is there a way to fix this?

**Comment by CannedFoodU** [comment]
fixed it, issue was no ani-cli directory had been made in /usr/local/lib. made a directory and copied the player files into it as a fix.

**Comment by Derisis13** [comment]
Sorry, the installation instructions are flawed. Should be fixed in #790

**Comment by Derisis13** [comment]
Also you have some extra files in `"$(brew --prefix)"/lib/ani-cli`

**Comment by CannedFoodU** [comment]
yes i think so. those were the files i moved into the directory i made.
