### ISSUE TITLE
Constantly getting "no search result found"

### ISSUE THREAD

**Issue by dusklight00** [pystardust/ani-cli#795]
**Metadata**
Version: 3.2
OS: Windows 10
Shell: Git Bash
Anime: Your Name, Kimi no Na Wa, Death Note, Sword Art Online much more....

**Describe the bug**
Any anime I search it says no search results found, see the screenshot below

**Steps To Reproduce**

1. Run `ani-cli`
2. Search any anime
3. ani-cli replies with "no search result found"

**Expected behavior**
It should return a list of search result to choose from.

**Screenshots**
![image](https://user-images.githubusercontent.com/71203637/175777451-941995bb-2ae2-4a81-9c1b-c3beffde411f.png)

**Additional context**
I followed instructions on ani-cli README.md to install ani-cli

**Comment by paniash** [comment]
Same issue here. Getting it on linux.

**Comment by JonLit** [comment]
same, ani-cli Version: 3.2.0, OS: Garuda Linux, the rest of the internet works (ping, websites, etc.)

**Comment by FilipLac** [comment]
Same issue, didn't update and if I tried to update it just said that is it up to date :/

**Comment by FilipLac** [comment]
Issue is present on termux and WSL 2.0 (ubuntu)

**Comment by Daggerfellar** [comment]
same issue here on Raspian Bullseye. i think there might be a problem with the search engine that searches up anime.

**Comment by justchokingaround** [comment]
yes, the search engine is rate limiting the requests, think of a fix atm

**Comment by FilipLac** [comment]
What about fallback search engine ?

**Comment by CoolnsX** [comment]
Change the url in [line 95](https://github.com/pystardust/ani-cli/blob/91715248d028eaa714edd1ae4075a5e45c87a474/bin/ani-cli#L95) to
```https://cachecow.eu/api/search``` for temporary fix

**Comment by FilipLac** [comment]
Tried that but it didn't help me :/

**Comment by PsyPyr0mancer** [comment]
Man I just managed to get this working on FreeBSD and this happens.

**Comment by FilipLac** [comment]
Any hints for at least temporary fix :D ?
Tried changing line 95 but it didn't help

**Comment by justchokingaround** [comment]
fixed in #797
