### ISSUE TITLE
Audio is streaming, but no video and black window. Won't switch to VLC from MPV.

### ISSUE THREAD

**Issue by sajidsarker** [pystardust/ani-cli#799]
```bash
Version: 3.2
OS: Linux Fedora 36
Shell: GNU bash
Anime: All
```
To install dependencies, I run in terminal:
```bash
sudo dnf install grep sed awk curl openssl mpv aria2 ffmpeg -y
```
To install ani-cli, I run in terminal:
```bash
sudo rm -rf "/usr/local/share/ani-cli" "/usr/local/bin/ani-cli" "/usr/local/bin/UI" /usr/local/bin/player_*
git clone "https://github.com/pystardust/ani-cli.git" && cd ./ani-cli
sudo cp ./bin/ani-cli /usr/local/bin
sudo cp -a ./lib/ani-cli /usr/local/lib
cd .. && rm -rf "./ani-cli"
```
ani-cli installs correctly as does mpv.

ani-cli runs correctly, I am able to search all anime and launch anime episodes without issue.

When mpv runs or loads, I immediately hear audio but I cannot see any controls. The window that opens is just black. If I right click the black window (no video), I can pause or unpause it. The scroll wheel allows me to scrub through the video.

**I do not know how to switch it to vlc from mpv even though vlc is installed (dnf).**

Audio is streaming correctly, but no video and black window.

**Comment by Derisis13** [comment]
Did you try overwriting providers with `-f[1-7]`? I'd try going trough them.
Sidenote: we have an rpm package of ani-cli on copr, you can try your luck with that too.

**Comment by CoolnsX** [comment]
> ```shell
> Version: 3.2
> OS: Linux Fedora 36
> Shell: GNU bash
> Anime: All
> ```
> 
> To install dependencies, I run in terminal:
> 
> ```shell
> sudo dnf install grep sed awk curl openssl mpv aria2 ffmpeg -y
> ```
> 
> To install ani-cli, I run in terminal:
> 
> ```shell
> sudo rm -rf "/usr/local/share/ani-cli" "/usr/local/bin/ani-cli" "/usr/local/bin/UI" /usr/local/bin/player_*
> git clone "https://github.com/pystardust/ani-cli.git" && cd ./ani-cli
> sudo cp ./bin/ani-cli /usr/local/bin
> sudo cp -a ./lib/ani-cli /usr/local/lib
> cd .. && rm -rf "./ani-cli"
> ```
> 
> ani-cli installs correctly as does mpv.
> 
> ani-cli runs correctly, I am able to search all anime and launch anime episodes without issue.
> 
> When mpv runs or loads, I immediately hear audio but I cannot see any controls. The window that opens is just black. If I right click the black window (no video), I can pause or unpause it. The scroll wheel allows me to scrub through the video.
> 
> **I do not know how to switch it to vlc from mpv even though vlc is installed (dnf).**
> 
> Audio is streaming correctly, but no video and black window.

first use ```ani-cli -h``` for all the info about arguments..
