### ISSUE TITLE
Where does downloaded anime is stored?

### ISSUE THREAD

**Issue by Haikal-Ravendy** [pystardust/ani-cli#80]
I download an anime but I don't know where to find it within my drive, where it is store our downloaded anime by default?

**Comment by lewdpatriot** [comment]
If you're on Linux just make an alias to where you want to download , you can even specify your preferred quality  
mine looks like this 
alias anid="cd /home/srk/Videos/anime && ani-cli -d -q 720"

**Comment by ura43** [comment]
I guess this is resolved?
