### ISSUE TITLE
android installation maybe needs an update?

### ISSUE THREAD

**Issue by Fmert24** [pystardust/ani-cli#800]
**Is your feature request related to a problem? Please describe.**

Termux 0.118 and possibly later does not provide access to external applications by default A.K.A android MPV player,VLC player etc.

  To grant access to mpv android application
  echo "external-apps=true" >> ~/.termux/termux.properties

Please add this to android install

**Comment by CoolnsX** [comment]
My Termux app works seemlessly.. and I never came across this problem.. Though I will look into it more deeply..
