### ISSUE TITLE
MAL integration

### ISSUE THREAD

**Issue by JonLit** [pystardust/ani-cli#803]
**Integration with MyAnimeList**
I have no idea how difficult it would be or if it would even work, but MAL integration would be pretty nice

**Describe the solution you'd like**
ability to log into MAL and automatically update watching status of anime

**Describe alternatives you've considered**
Manually updating MAL works

**Comment by Skepller** [comment]
Although I would really like that, I believe this feature is already on the Reject pile in [Issue #523 ](https://github.com/pystardust/ani-cli/issues/523)

**Comment by Derisis13** [comment]
Although it's poorly documented, the script is supposed to be trackma compatible. Just play the videos, and trackma will pick up on them. It supports MAL and more.
Read further: https://github.com/z411/trackma
Direct MAL integration is rejected.
