### ISSUE TITLE
Won't download or stream anime

### ISSUE THREAD

**Issue by IZenithy** [pystardust/ani-cli#807]
Version: [3.2.1]
OS: [Arch linux]
Shell: [Fish]
Anime: [Anything]

**Describe the bug**
Downloading and streaming is broken.

**Steps To Reproduce**
Use ani-cli

**Expected behavior**
Downloading and streaming should work

**Screenshots (if applicable; you can just drag the image onto github)**
![2022-07-05_10:49:28](https://user-images.githubusercontent.com/82327047/177277622-1b073e6e-5b2c-4dec-8bb2-34cd2befdb02.jpg)

**Comment by IZenithy** [comment]
I don't think it's an internet issue, here is my speed test result:
![2022-07-10_14:04:15](https://user-images.githubusercontent.com/82327047/178142239-8ab77c44-cb3b-460c-9c22-d529f328d8e8.jpg)

and even if I don't specify a dir it fails again:
![2022-07-10_14:07:09](https://user-images.githubusercontent.com/82327047/178142344-a54c7820-dad8-4dac-984b-e8108a3ef6c1.jpg)

**Comment by IZenithy** [comment]
And when I want to watch anime it gives me this message:
![2022-07-10_14:17:35](https://user-images.githubusercontent.com/82327047/178142655-0b2e03a0-5e7e-4b99-abc4-6686185a6a12.jpg)
without viewing anything

**Comment by justchokingaround** [comment]
try running it with the `-x` to get all the links and then manually using them, to see if it works

**Comment by IZenithy** [comment]
Yes, it works

**Comment by CoolnsX** [comment]
did u properly installed ani-cli like placing a files in their correct place..
Like putting ani-cli in /bin/ani-cli
And libraries in /lib/ani-cli
?? 
Cause that maybe the problem u r facing..

**Comment by IZenithy** [comment]
I installed it from the AUR

**Comment by port19x** [comment]
I also ran into this behaviour trying to download bakemonogatari

**Comment by CoolnsX** [comment]
> I also ran into this behaviour trying to download bakemonogatari

which episode??

**Comment by CoolnsX** [comment]
Hopefully this now is fixed.. closing this issue
