### ISSUE TITLE
Cut-off subtitles

### ISSUE THREAD

**Issue by freakmanu** [pystardust/ani-cli#810]
**Metadata**
Version: 3.2.1
OS: Windows 10
Shell: Git-Bash
Anime: Starwars Visions

**Describe the bug**
Subtitles are cut off, im not sure if its an issue of Ani-cli or stream, but it looks like the widescreen of that anime is what causes it.
on animixplay it seems to be fine atleast.

**Steps To Reproduce**

1. Run 'ani-cli Star Wars Vision'
2. Chose 1
3. Choose episode 1 (i checked 1 and 2 and its on both)

**Screenshots**

![2022-07-07_00-51-39](https://user-images.githubusercontent.com/10727536/177657295-e82cbee6-46a0-4b47-aae7-9ecd6c0c2e37.png)

**Comment by justchokingaround** [comment]
```sh
ani-cli -f5 star wars visions
```
will fix the issue

this is an issue with streamlare's video link

streamlare is the default video provider, in the code you can see it on line 238: `provider=2`

by using -f5 u choose the 5th provider which is animixplay's direct links

u can use ani-cli -x to see the providers available

**Comment by freakmanu** [comment]
oh i see, thanks!
