### ISSUE TITLE
Anime with 1 episode doesn't launch

### ISSUE THREAD

**Issue by nullchilly** [pystardust/ani-cli#811]
**Metadata (please complete the following information)**
Version: git
OS: Arch linux
Shell: zsh
Anime: class elite, kanokari

**Describe the bug**
Anime with 1 episode doesn't launch

**Steps To Reproduce**

1. Run `ani-cli`
2. Type in `class elite`
3. Choose 3
mpv is nowhere to be found

**Expected behavior**
mpv should launch

**Screenshots (if applicable; you can just drag the image onto github)**

https://user-images.githubusercontent.com/56817415/177921888-1bdbdc30-a80c-4c6b-8831-80d66d3b1aba.mp4

**Additional context**
I have to use `ani-cli -x` open one of the link to download and manually open mpv for these

**Comment by stl3** [comment]
I don't know what the cause is, but there is (for me) sometimes issues with playing the 1st episode of random anime. Whenever this happens, I play the next episode, and if it succesfully loads, I quit mpv and then select previous to go back to the 1st ep and it works. Also, weirdly enough when this works on one anime, it seems to fix all other ep1's that have playing issues, including the one in your post (it played fine on my end).

**Comment by justchokingaround** [comment]
are you on the latest version? it works just fine for me

**Comment by nullchilly** [comment]
@justchokingaround I am on git version
```
git rev-parse --verify HEAD
3da894148b395078c3e8673e5a6535dfb215f893
```
Today both anime I tested has updated their episode 2

I searched for a 1 episode `Chirin no Suzu` anime and it works correctly. I think it's the same behavior as @stl3, not sure what version you are on?

**Comment by stl3** [comment]
> git rev-parse --verify HEAD

I was on gitbash 2.36.1/win10 using:
Administrator@ /h/Programming/GitHub/ani-cli (master *=) [03:59]
$ git rev-parse --verify HEAD
3da894148b395078c3e8673e5a6535dfb215f893

I did not test on my Termux or rpi4 yet however. Sorry for late reply guys.

**Comment by justchokingaround** [comment]
that's strange, @nullchilly you're on the latest version, so there should be no problems whatsoever, and the first ep of cote s2 worked fine for me, it opened instantly. idk what to do yet atm, but i'll try to reproduce it and get more info on the issue

**Comment by nullchilly** [comment]
Okay I found out the cause on my end

It's https://1.1.1.1/ (I am using [cloudflare-warp-bin](https://aur.archlinux.org/packages/cloudflare-warp-bin) package for arch)

Basically `warp-cli connect` and ani-cli won't open

Downloading still works however when I do `ani-cli -x` and copy streamlare link it isn't working `ffmpeg: https: HTTP error 410 Gone` (It opens with `warp-cli disconnect`)

**Comment by justchokingaround** [comment]
oh wow

**Comment by justchokingaround** [comment]
done ✅ @nullchilly
