### ISSUE TITLE
Anime searching not working

### ISSUE THREAD

**Issue by icedgreen** [pystardust/ani-cli#818]
**Metadata (please complete the following information)**
Version: 3.2.0 (AUR)
OS: Arch Linux
Shell: zsh
Anime: any

**Describe the bug**
No search results for any anime query. Was working fine yesterday.

**Steps To Reproduce**

1. Run `ani-cli naruto`
2. `No search results found`

**Expected behavior**
There should be a result.

**Comment by justchokingaround** [comment]
update to 3.2.2

**Comment by icedgreen** [comment]
> update to 3.2.2

Thanks that worked!

**Comment by ant0n-anon** [comment]
i'm updated and unable to have any search results :(

**Comment by ant0n-anon** [comment]
okay, i had to switch to ani-cli-git and now it's working fine (from the AUR).
