### ISSUE TITLE
First episode is automatically selected on Black Clover

### ISSUE THREAD

**Issue by Zexsch** [pystardust/ani-cli#821]
**Metadata (please complete the following information)**
Version: 3.2.2
OS: Windows 10
Shell: Git-Bash
Anime: Black Clover

**Describe the bug**
Automatically selects the first episode without an option to select any other.

**Steps To Reproduce**

1. Run `ani-cli Black clover`
2. Choose 1 (black clover)
3. Automaticallz chooses episode 1. Same as issue #743 

**Expected behavior**
It should prompt an episode selector.

**Comment by justchokingaround** [comment]
choose the second one: `black clover tv`, this is a problem on animixplay's side, since they display the special episode as `Black Clover`, u'll encounter the same problem on the website, we can't do anything about it
