### ISSUE TITLE
im probably just stupid

### ISSUE THREAD

**Issue by Crisp-Casper** [pystardust/ani-cli#822]
after i run the install command on the git bash it says i dont have mpv... i installed mpv but it wont detect it so i tried to download it instead and i just dont have ffmpeg

i don't really mess with windows or this git bash im just installing a windows game since my poor Linux doesn't run a few elements as good

**Comment by justchokingaround** [comment]
you should probably just install mpv and ffmpeg using scoop, and you'll have no problems

**Comment by Crisp-Casper** [comment]
> you should probably just install mpv and ffmpeg using scoop, and you'll have no problems

yeah that did it just fine! now i got something to do on windows lol

**Comment by CoolnsX** [comment]
Closing this now..
