### ISSUE TITLE
History is broken on macOS

### ISSUE THREAD

**Issue by FahimAnayet** [pystardust/ani-cli#828]
**Metadata**
Version: 3.2.3
OS: macOS
Shell: zsh
Anime: N/A

**Describe the bug**
History is broken on macOS
It says something about integer expression expected, see screenshot.

**Steps To Reproduce**

1. Run `ani-cli -c`

**Expected behavior**
There should be a history log or something, I don't know.
However, dra-cla which is a modified version of ani-cli does work fine with history.

**Screenshots**
![Screen Shot 2022-07-18 at 2 40 33 PM](https://user-images.githubusercontent.com/48918937/179479899-f0086ce9-f601-4458-992f-f0119f4fba53.png)

**Comment by justchokingaround** [comment]
update ani-cli to v3.2.3

**Comment by FahimAnayet** [comment]
I believe I am indeed using v3.2.3
![Screen Shot 2022-07-18 at 3 43 40 PM](https://user-images.githubusercontent.com/48918937/179485771-ce127f57-4fcf-4f4d-baa3-d7a1b3960e03.png)

**Comment by FahimAnayet** [comment]
I am using v3.2.3

**Comment by CoolnsX** [comment]
Is your problem still persists?? @FahimAnayet

**Comment by FahimAnayet** [comment]
> Is your problem still persists?? @FahimAnayet

Unfortunately yes.
Current installed Version: 3.3.0

**Comment by justchokingaround** [comment]
can you show what your history file looks like, by showing the output of `cat ~/.cache/ani-hsts` ? this might be caused bc u have an outdated history file from an old version (before 2.0 iirc)

**Comment by FahimAnayet** [comment]
I've deleted the history an hour ago. This is how it looks like.
`hataraku-maou-sama-2nd-season	3`

**Comment by justchokingaround** [comment]
second season only has 2 episodes tho?

**Comment by FahimAnayet** [comment]
> second season only has 2 episodes tho?

Yes. That is kinda weird. :v

**Comment by justchokingaround** [comment]
the way the script works, is that it saves the last episode and adds 1 to it. if the last episode watched is the last episode of the season, the entry is deleted. i can't reproduce ur issue unfortunately

**Comment by FahimAnayet** [comment]
Thanks anyway. I can find history using `fzf < ~/.cache/ani-hsts` I am closing the issue. If anyone can reproduce the issue or may have solution please open the thread.
