### ISSUE TITLE
FR / Things.....

### ISSUE THREAD

**Issue by Reaper176** [pystardust/ani-cli#83]
K so don't know if this is the correct place to put this. But I thought I might be able to make a request or find out that I'm dumb and it already does what I want....XD

maybe the error:

    When I use the -d tag to download an episode outside of the ani-cli directory by doing ani-cli -d "URL"  it does
      1. Have me put in the number of the series/episode I want.
      2. Says downloading episode .....
      3. Takes about 2 seconds and then reports the download as complete
      Issue: The download is not "complete" or readable. 
Yes I did the add the two lines thing for FFmpeg, double-checked, and that is what allowed the next section to work at all.
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Maybe the FR

After adding the lines for ffmpeg the following started to work.....ish.

    When I do the same thing from inside the ani-cli directory by doing ./ani-cli -d "URL" It
      1. Has me put in the number of the series/episode I want.
      2. Says downloading episode.....
      3. Shows no further status update. 
     FR: Show a download indicator or inform me that I am doing something wrong XD.
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Just a suggestion
     Put a few screenshots up on the made page so we have an idea of how it's supposed to look. I don't know about everyone but I know that at least a few people like me would benefit greatly from having a visual cue/ reference to see what we are doing.

If I am just the big dumb and all of this stuff is already addressed/done somewhere else then feel free to give the rere headstamp and send me on my way. <3

EDIT: FR: Support for external downloaders like aria2c or....something.

**Comment by ura43** [comment]
Please open another issue.
This one is really incoherent :sweat_smile:
