### ISSUE TITLE
Running the given install shell script causes /usr to be deleted on linux

### ISSUE THREAD

**Issue by Cricketjds3** [pystardust/ani-cli#830]
**Metadata (please complete the following information)**
Version: 5.4
OS: Arch Linux
Shell: zsh
Anime: N/A

**Describe the bug**
After cloning of repo, running the given installation shell script (by copy and paste of all commands) causes /usr to be deleted. Likely due to this being a fresh install and thus /usr/local/share/ani-cli does not exist.
As /usr is permanently deleted, I have had to reinstall OS.
**Steps To Reproduce**

1. Install repo
2. Copy and paste following into shell (sudo rm -rf "/usr/local/share/ani-cli" "/usr/local/bin/ani-cli" "/usr/local/bin/UI" /usr/local/bin/player_* 
git clone "https://github.com/pystardust/ani-cli.git" && cd ./ani-cli
sudo cp ./bin/ani-cli /usr/local/bin
sudo cp -a ./lib/ani-cli /usr/local/lib
cd .. && rm -rf "./ani-cli")
3. Hit enter

**Expected behavior**
Installs ani-cli into bin without problems

**Additional context**
Could be I am an idiot and shouldn't have ran the rm -rf in the first line if I know it doesn't exist. Just thought it should be made clear for others who don't know.

**Comment by CoolnsX** [comment]
@Cricketjds3 
![image](https://user-images.githubusercontent.com/76195824/179765122-6dd36e30-d96b-48a7-a2dc-fe126db04c16.png)

**Comment by port19x** [comment]
No it doesn't. Rip to your system
