### ISSUE TITLE
Downloading for kaguya is broken

### ISSUE THREAD

**Issue by FilipLac** [pystardust/ani-cli#833]
**Metadata (please complete the following information)**
Version: 3.3.0
OS: Ubuntu 20.04
Shell: dash
Anime: Kaguya-sama: Love Is War -Ultra Romantic-

**Describe the bug**
Before updating to version 3.3.0 (from 3.2.1), it would download episodes with some of them being duplicates and some missing (same as in issue #813). After updating it just says "Video URL not found". I also tried all 3 providers using -r [1-3] but it didn't help.
Also tried reinstalling ani-cli because it was showing an error 404 on line 1 after running ani-cli -U

**Steps To Reproduce**

1. Run `ani-cli -d -q best Kaguya`
2. Choose 5 (kaguya sama wa kokurasetai ultra romantic)
3. Choose episode 1 or try to download whole season (it throws this on both) -- also here it shows wrong range (last episode is 13 but range is from 1 to 14).

**Expected behavior**
Downloading should download all 13 episodes without any duplicates or any error like "Video URL not found".

**Other**
Also tried downloading Jahy as example and downloading for this started as it should. So maybe only kaguya has some issues...

**Comment by Quicksilver151** [comment]
searching in animixplay, i found that ep 1 is a PV and is a youtube embeded video
that might be the cause of the issues with kaguya sama ultra romantic
idk how the devs are handling searching for episodes but hope this helps somehow

**Comment by FilipLac** [comment]
Looks like you are right, didn't check the animixplay and when I skipped E1 it started downloading E2 how it should've. I'll give it some time to download and then check if it downloaded all episodes how it should without any duplicates. Thanks for a tip tho
