### ISSUE TITLE
Downloading progress is cursed

### ISSUE THREAD

**Issue by AlexFreik** [pystardust/ani-cli#835]
**Metadata (please complete the following information)**
Version: 3.3.0
OS: macOS Monterey 12.4
Shell: zsh

**Describe the bug**
Downloading progress is cursed 

**Steps To Reproduce**

1. Run `ani-cli -d kekkai`
2. Choose 4 
3. Choose episode 1

**Expected behavior**
Downloading progress looks normal

**Screenshots (if applicable; you can just drag the image onto github)**
<img width="830" alt="Screenshot 2022-07-20 at 20 26 03" src="https://user-images.githubusercontent.com/61039123/180044816-5b1593b2-a924-4e15-8f69-8370dccbf561.png">

**Comment by CoolnsX** [comment]
this is how new download manager axel works..

**Comment by AlexFreik** [comment]
> this is how new download manager axel works..

I see... haha
