### ISSUE TITLE
Doesn't support series with non-standard number 10.5

### ISSUE THREAD

**Issue by AlexFreik** [pystardust/ani-cli#836]
**Metadata (please complete the following information)**
Version: 3.3.0
OS: macOS Montrey 12.4
Shell: zsh
Anime: kekkai-sensen-dub

**Describe the bug**
Doesn't support weird series like 10.5

**Steps To Reproduce**

1. Run `ani-cli -d kekkai`
2. Choose 4
3. Choose range 10 11

**Expected behavior**
It should download episode 10.5 as well.

<img width="846" alt="Screenshot 2022-07-20 at 20 37 09" src="https://user-images.githubusercontent.com/61039123/180047337-e79e722b-d82c-4ff3-86bd-1a4306dbc6f7.png">

**Comment by CoolnsX** [comment]
afaik we don't support 0.5 episode too... also we are scraping animixplay not gogoanime.. and animixplay doesn't keep those episodes..

**Comment by AlexFreik** [comment]
> afaik we don't support 0.5 episodes too... also we are scraping animixplay not gogoanime.. and animixplay doesn't keep those episodes.

I see, it was gogoanime half a year ago) then it is fine I guess
