### ISSUE TITLE
number of episodes no longer displayed in query results intended?

### ISSUE THREAD

**Issue by lasmate** [pystardust/ani-cli#837]
just updated to latest version(v3.3) and i was wondering if the number of episodes not being displayed next to results of search queries was something definite or just an on/off type of option

**Comment by Derisis13** [comment]
That is expected, it's a feature, that was intentionally removed.

**Comment by CoolnsX** [comment]
It's due to shifting to another site.. in V2 we scrape the Gogoanime backend site which is gogoplay.. that has no of episode functionality in searches.. the script just scrapes the site.. nothing more..
