### ISSUE TITLE
"Episodes not released yet!" Error For All Anime

### ISSUE THREAD

**Issue by LittleTimmy63** [pystardust/ani-cli#840]
Version: Latest
OS: Manjaro Linux for x64
Shell: Bash

Attempting to view any anime results in the error described in the title.
I can search for anime just fine, but once I select one and the program searches for episodes,
it errors out.

The program worked completely fine yesterday, so I believe that this is an issue with the providers that we scrape. I have already tried reinstalling.

**Steps To Reproduce**

1. Run the program.
2. Search for anime.
3. Select one.

**Expected behavior**
A list of episodes should be shown

**Comment by CoolnsX** [comment]
It's due to main site is not working.... Also whenever this type of error occurs in the future.. then check if the episode is on main site..

**Comment by CoolnsX** [comment]
Site is now online... Closing this..

**Comment by LittleTimmy63** [comment]
Thanks, man!
