### ISSUE TITLE
why no windows version without manually installing git bash?

### ISSUE THREAD

**Issue by candrapersada** [pystardust/ani-cli#844]
will there be direct ani-cli use without manually installing git bash?

**Comment by justchokingaround** [comment]
bc this is a script written in posix shell, which isn't natively supported by windows. if u want native windows support, *simply* port the script to powershell

**Comment by candrapersada** [comment]
how to port the script to powershell?

**Comment by CoolnsX** [comment]
Rewrite the whole code in powershell
