### ISSUE TITLE
ani-cli Video player not opening issue

### ISSUE THREAD

**Issue by khansaad1275** [pystardust/ani-cli#847]
**Metadata (please complete the following information)**
Version: [e.g. 3.3.1]
OS: [Android-Termux]
Shell: [bashl]

**Describe the bug**
ani-cli is not asking which video player to use, it shows the video is playing and i have multiple video player in my phones but ani-cli is not even opening one of them. so all i have is a screen that is showing me option to quit,next, previous.

**Steps To Reproduce**

1. Run `ani-cli`
2. select anime and episode number

**Expected behavior**
A video player should play the anime.

**Screenshots (if applicable; you can just drag the image onto github)**
![image](https://user-images.githubusercontent.com/32749921/181510647-2a0f0980-af15-49b5-8711-fab546c62db0.png)

So this is all i am getting, and no video player is starting to play the anime.

**Comment by justchokingaround** [comment]
do you have mpv installed, and if so, is it the playstore or the fdroid version?

**Comment by khansaad1275** [comment]
You need to install either VLC-Media-player in your phone or you need to install mpv-android from playstore. If you have VLC then u just need to use `ani-cli -v` to run the tool and it will open the vlc player everytime you will try to watch anything.
