### ISSUE TITLE
Cannot search new anime

### ISSUE THREAD

**Issue by Upsurge-11** [pystardust/ani-cli#848]
Version: 3.3.1
OS: Endeavour OS
Shell: Bash

Cannot search any new anime.

**Steps To Reproduce**
1. Run `ani-clil`
2. search anime

It is showing No search results found

![image](https://user-images.githubusercontent.com/57493726/181512935-18e8d79b-24f9-48d9-ad51-eb93076cb219.png)

**Comment by joocoo** [comment]
Are you blocking the url "gogoanime.lu"?

I had the same issue then I searched into the script and saw it was using that url to search.

Pi-Hole was blocking the domain for me but now I can search just fine.

**Comment by WeaselGuns** [comment]
I use it on windows 10 using git bash. This happens to me when I run ani-cli -U to update where I get an error then suddenly it can't search anything anymore. Hopefully that helps.

**Comment by port19x** [comment]
> I use it on windows 10 using git bash. This happens to me when I run ani-cli -U to update where I get an error then suddenly it can't search anything anymore. Hopefully that helps.

This sounds familiar to a bug we had in the past. Can you verify that it didn't erase parts of the script because of an internet outage while updating?
The line count would be helpful here

**Comment by port19x** [comment]
This isn't reproducible, please reopen if you can provide further context.
