### ISSUE TITLE
Axel messes up video encoding

### ISSUE THREAD

**Issue by TheTrveAnthony** [pystardust/ani-cli#849]
**Metadata (please complete the following information)**
Version: 3.3.1
OS: manjaro stable
Shell: dash

**Describe the bug**
Hi,
I have had some encoding issues since you switched from `aria` to `axel` for downloading episodes, what happens exactly is that sometimes video freezes for a few seconds and then speeds up until it catches up with audio. It happened with episodes of Diamond is Unbreakable (with quite big video files, over 1GB). This issue doesn't happen when I watch episodes directly online so it definitely comes from axel  (or my internet connection?).

**Steps To Reproduce**

1. Run `ani-cli -d`
2. Download a Diamond is unbreakable episode
3. Watch and see

So, maybe switch back to aria ?

**Comment by justchokingaround** [comment]
have you tried out redownloading it, and downloading the same file with aria2c ?

**Comment by TheTrveAnthony** [comment]
I haven't, I'll try and let you know (some episodes were properly downloaded btw)

**Comment by CoolnsX** [comment]
Nope.. don't do it.. it's not axel problem.. it's custom code one..

**Comment by CoolnsX** [comment]
implemented for downloading m3u8 links

**Comment by justchokingaround** [comment]
oh well

**Comment by TheTrveAnthony** [comment]
So I did as you suggested and redownloaded it, and strangely the new file is larger than the original one (1.44GB vs 1.41GB). Also I still got video freezes but at different times.
I also tried to download it with `yt-dlp`, the file is much smaller (323MB) but it's correctly encoded, and the quality is still good, so I guess I'll simply modify the script to use it.

Thank you

**Comment by candrapersada** [comment]
is it possible to add an option to use external downloader like `-e N_m3u8DL`?

**Comment by TheTrveAnthony** [comment]
Just in case the answer is no, you can still use the `-x` option to get the video link and then download it, it's a bit annoying but it still works.

**Comment by CoolnsX** [comment]
Fixed in #846.. please update and confirm.. then close this issue

**Comment by TheTrveAnthony** [comment]
I downloaded and watched 2 episodes with your patch, everything was perfectly smooth, and loading speed seemed faster, fixed !!
