### ISSUE TITLE
Downloading broken [Windows]

### ISSUE THREAD

**Issue by taep96** [pystardust/ani-cli#85]
Using on windows. When trying to `ani-cli -d` files are created and It says that episodes are downloaded but there is nothing in those files? Also everything is happening too fast for a download.

**Comment by Tuchan** [comment]
> 
> 
> > Error on linux it might be connected to outdated `setsid` version. Can you try `$ setsid -V`? It should be 2.32 or higher, if I am not mistaken
> 
> It's not an issue with `setsid`. There is already a PR for download fix #35
> 
> Hopefully @pystardust will merge this soon

So... even after that it seems that `-d` does not work properly... It shows that I apparently `Downloaded episode: 001`, but when I view the file, its 1kb in size >:(
It might be connected to #32, but honestly... idk

**Comment by Dink4n** [comment]
Try to use the latest version. Gogoanime recently moved to gogoanime.cm

**Comment by Tuchan** [comment]
> 
> 
> Try to use the latest version. Gogoanime recently moved to https://gogoanime.cm
> 
> ```
> git pull
> ./install
> ```
> 
> Pull the latest changes by the above command

im so slow at responding wtf

I'm already using the latest version... but the problem keeps occurring

**Comment by ura43** [comment]
> I recommend creating a separate issue for linux to avoid confusion

I like the spirit but in this case its very likely to be an issue related to gogoanime url extraction.
See #221
