### ISSUE TITLE
Resume interrupted downloads ?

### ISSUE THREAD

**Issue by Albnu14** [pystardust/ani-cli#853]
**Is your feature request related to a problem? Please describe.**
When a download is interrupted and the user reuses ani-cli to download the same episode it gets overwritten
**Describe the solution you'd like**
Not sure if there is a solution, i would like this feature for animixplay mainly.

**Describe alternatives you've considered**
Putting the url generated with -x in the downloader (axel) but it can't download it without ffmpeg so not sure if resuming is possible

**Additional context**
This problem is caused by my slow internet connection which gets disconnected frequently.

**Comment by Quicksilver151** [comment]
resuming works only when downloading from xtreamcdn servers
you can select that server to download from when you use `-r1` flag

**Comment by port19x** [comment]
I'm merging this into #860
