### ISSUE TITLE
add an option to use external downloader

### ISSUE THREAD

**Issue by candrapersada** [pystardust/ani-cli#854]
**Is your feature request related to a problem? Please describe.**
is it possible to add another external downloader besides axel and ffmpeg.

**Describe the solution you'd like**
Please add external downloader, maybe through a `-e <external_downloader>`

**Comment by port19x** [comment]
I don't believe the value added by this is significant enough to integrate that as an option.

Anyone knowledgable enough to care about the particular download accelerator being used should also be capable in replacing the line where we currently call axel with the download accelerator of their choice.

If you're aware of a download accelerator that isn't ffmpeg that can handle m3u8 links, please let us know. I'm not aware of one
