### ISSUE TITLE
why ani-cli can't use select link option in goload 

### ISSUE THREAD

**Issue by candrapersada** [pystardust/ani-cli#857]
why ani-cli can't use link selection option manually in https://goload.pro or https://goload.io
![goload](https://user-images.githubusercontent.com/36833664/182493825-35f6ce49-d391-4af4-bcaf-bffab1d1ac11.PNG)
![182496778-7a0a5edc-ef82-475a-abe9-9fb3dbb3108e](https://user-images.githubusercontent.com/36833664/182497262-10ce59c1-a5a5-44ae-a791-07515cfb7553.png)
![image](https://user-images.githubusercontent.com/36833664/182497075-b5ed32fc-05ca-46cb-b8af-bc538d7b4968.png)
![image](https://user-images.githubusercontent.com/36833664/182738762-1a4ce63e-8308-4aa0-a3ae-8e2e55a50052.png)

**Comment by CoolnsX** [comment]
You can.. also we don't scrape goload now.. just use it's search engine only.. we now scrape animixplay.. also we already implemented the scraping of alternative links.. refer to #786

**Comment by candrapersada** [comment]
what I mean is why does the link change every episode?
![image](https://user-images.githubusercontent.com/36833664/182818221-3ea896ef-5567-4cfa-b8f0-4ef4a30fb136.png)
![image](https://user-images.githubusercontent.com/36833664/182818567-d8a082d3-1ce4-4c28-b094-91dd0ba812f4.png)
![image](https://user-images.githubusercontent.com/36833664/182819066-4fbb435f-88bd-410c-947a-b9e5828ec669.png)

**Comment by port19x** [comment]
It's not uncommon to have several content delivery networks providing the files, especially in the case of video services.
This is expected behaviour and shows good practices being followed at animixplay

**Comment by candrapersada** [comment]
is there a way to prevent the link from changing www06.gogocdn.stream to storage.googleapis.com or v.vrv.co on Animixplay

**Comment by port19x** [comment]
I don't think there is.
More importantly, what benefit would that serve?
Is that the only host getting through a restrictive school firewall?
