### ISSUE TITLE
[Feature request] add autocomplete and history

### ISSUE THREAD

**Issue by CountOmega** [pystardust/ani-cli#859]
When searching for anime, it would be nice to add autocomplete and a history which can be accessed by arrow up.

**Comment by justchokingaround** [comment]
history is already implemented in the `-c` argument

**Comment by CoolnsX** [comment]
And for auto-completion.. there is not enough documentation on it.. to implement in shell

**Comment by port19x** [comment]
> And for auto-completion.. there is not enough documentation on it.. to implement in shell

Agreed. Autocomplete is outside of the scope of this project

**Comment by 4censord** [comment]
Would you accept a pull request for basic (flags only, no anime names) autocomplete?

**Comment by Derisis13** [comment]
Well as long as it's not part of the scipt, but a shell config option I'm open to it. I think what auto-completion was discarded here is auto-completion inside the script.
