### ISSUE TITLE
add a flag to auto restart downloads

### ISSUE THREAD

**Issue by Quicksilver151** [pystardust/ani-cli#860]
**Is your feature request related to a problem? Please describe.**
connection terminates too often for me when downloading
mostly due to my crap internet connection

**Describe the solution you'd like**
add a flag that auto restarts the download if download fails
i suggest `-R`
when downloading from a range, it would help to restart the download of the episode that failed to download rather than move onto the next episode

**Describe alternatives you've considered**
ani-cli offers to re download whenever download fails by inputing `r`
so i just enter a bunch of `r` for every download hoping it gets enough retries to finish downloading

**Comment by port19x** [comment]
A temporary solution, but `watch -n 10 xdotool type r` will simulate a keypress on `r` every 10 seconds. `xdotool` may or may not be preinstalled on your distro, but it should be available.

If auto restart or autoresume of downloads is possible it should be implemented by default for all users as that is desired behaviour, so no extra flag

**Comment by Quicksilver151** [comment]
just checking on this again since its not been implemented yet

**Comment by CoolnsX** [comment]
restart download can be implemented but resuming download can be a bit challenging cause only one provider has that type of link which can be resumed others don't.. so it's like an hit or miss

**Comment by Quicksilver151** [comment]
just dont have it enabled by defualt
add a flag for it. and people that use that source will simply use that flag thats all

**Comment by port19x** [comment]
I don't see this feature being implemented in the foreseeable future. 
I'm closing this to reflect that

**Comment by Quicksilver151** [comment]
sad
:(
