### ISSUE TITLE
option to allow for max number of connections when downloading

### ISSUE THREAD

**Issue by xxiz** [pystardust/ani-cli#865]
**Is your feature request related to a problem? Please describe.**
When I normally download anime with ani-cli axel tries to download an episode it gets limited as the max connections are too high and it creates a bug where I cannot download anything and it simply repeats `50%` and `Connection 0 finished` forever. However, when I changed the number of connections in the axel download command to 10 and it worked perfectly. I've tried using axel to download other things with the same parameters and it works fine.

**TLDR;** _30 max connections is too much. And axel gets limited, causing it to not download anything. Changing it to 10 fixes it_

**Describe the solution you'd like**
A flag that changes the number of connections made to the site when downloading. For example: `-n specify number of connections when downloading`

**Describe alternatives you've considered**
Manually update the download parameters as needed, and it works just fine. However, I wanted to create a feature request in case in the future anyone has similar issues.

**Additional context**
I think generally for most locations 30 max connections works just fine, but for the rare use cases like myself, it might be helpful to add on for anyone in the future to prevent this bug.

**Comment by port19x** [comment]
30 connections is suboptimal in any case. We should regard this as a bug and reduce to 10

**Comment by candrapersada** [comment]
is there a way to get the latest version of axel on windows?

**Comment by port19x** [comment]
I'm not sure there is: https://github.com/axel-download-accelerator/axel

**Comment by xxiz** [comment]
> 30 connections is suboptimal in any case. We should regard this as a bug and reduce it to 10

That sounds good to me. I'll try with connections varying from 30 - 10 and let you know if there is a specific number that it limits.

**Comment by CoolnsX** [comment]
It even breaks at 20 so the sweet spot will be 10..

**Comment by xxiz** [comment]
> It even breaks at 20 so the sweet spot will be 10..

That makes sense
