### ISSUE TITLE
Create directory if needed

### ISSUE THREAD

**Issue by Derisis13** [pystardust/ani-cli#868]
**Is your feature request related to a problem? Please describe.**
Currently if you want to download to a specified folder (flag `-p`) and the folder doesn't exist, the download fails

**Describe the solution you'd like**
Detect if folder doesn't exist, and create it (using `mkdir -p`). Or we don't create a folder at all, but exit right on startup with an error message. Or default to current folder (with a verbose warning).

**Describe alternatives you've considered**
Using `mkdir` without the `-p` flag might be more stable

**Additional context**
Feature was discussed on [discord](https://discord.com/channels/931186431215435807/932006490703822938/1008361758341222521)

**Comment by port19x** [comment]
`mkdir` without `-p` is considerably worse since in a directory tree `A/B/C` `mkdir A/B/C/D/E` will fail while with `mkdir -p` it will create any intermediary folders without problem

**Comment by CoolnsX** [comment]
One line is..
```[ -d dummy ] || mkdir dummy```

**Comment by candrapersada** [comment]
how to use `mkdir -p` in windows?
