### ISSUE TITLE
Download not working (Axel isn't getting right URL?)

### ISSUE THREAD

**Issue by Panzer-Slasher125** [pystardust/ani-cli#869]
**Metadata (please complete the following information)**
Version: [e.g. 2.0.2]
OS: Windows 10
Shell: Gitbash?
Anime: Made in Abyss

**Describe the bug**
Downloading is broken. Sometimes it downloads half an episode (like MIA sub episode 13 for me)
It only says to retry or check my internet connection, but the axel help options appears above it. 

**Steps To Reproduce**

1. Run `ani-cli -d made in abyss'
2. Choose 1, 2, or 3 (sub, dub, retsujitsu***)
3. Choose 1 -1 (any episode)

**Expected behavior**
Downloading should work normally.

**Screenshots (if applicable; you can just drag the image onto github)**
Episode 13 of the first subbed season
![MIASub1Epi13](https://user-images.githubusercontent.com/111416486/185056469-66f9d893-5adc-4db3-8c1b-9fb298aad7ed.png)
Episode 1 of the second subbed season
![MiaSub2Epi1](https://user-images.githubusercontent.com/111416486/185056681-c5e41478-cda2-4ca8-8da4-f84086727728.png)
The code that decodes the link on my machine in case it was porked somehow (I guess it works since it sometimes downloads half episodes)
![LinkGenCode](https://user-images.githubusercontent.com/111416486/185057082-eda576a1-3e86-4fb8-b877-1e0b41c628d9.png)
These are the links for a failed episode download
![VerbooseLinkForFailedEpisode](https://user-images.githubusercontent.com/111416486/185058187-b6f9b386-8eaf-46e9-be29-8f349a105c14.png)
These are the links for a half episode download (which may be my internet)
![VerbooseLinkForHalfEpisode](https://user-images.githubusercontent.com/111416486/185058237-37969634-5416-41bc-a210-b7b3da054cc5.png)

**Additional context**
If you copy the link from a failed episode download into a normal browser, the episode shows up and you can just download it from there. I've reinstalled ani-cli and all of it's dependencies, I'm definitely running the bash with admin. 

Streaming episodes works fine. Using axel manually on the link after pasting it into a browser works fine (And it gives me a full episode).

This (vvv) should download the full episode of (ani-cli -d made in abyss, choosing 1 then 1) season 1 subbed (which fails if using ani-cli)

'axel https://www907.ff-02.com/token=BsV8W6y5bznd_INaXGUJHQ/1660735970/71.205.0.0/173/d/0d/6c08a01b8ff5d097bc72c49df88440dd-720p.mp4'

 I tried one piece episode one and it got a half downloaded, so I really have no idea what's going on. Seems like it's just my install since there isn't an issue for it open (nor closed from what I could tell, I'm new to github).

**Comment by port19x** [comment]
![swappy-20220904_211203](https://user-images.githubusercontent.com/82055622/188329772-4a75b0d0-1285-4912-ad0c-c33a11ca3156.png)

Bug confirmed

**Comment by port19x** [comment]
This is likely to be fixed along the way with the current breakage

**Comment by CoolnsX** [comment]
it's fixed in current version.. @Panzer-Slasher125 pls confirm it and if it works, close this issue..

**Comment by Panzer-Slasher125** [comment]
After some fiddling around I got it to work. For future reference, make sure to completely uninstall ani-cli from source, scoop, and chocolatey. After that, install it using scoop. If you still get errors reinstall axel. If that isn't working, make sure to uninstall axel via chocolatey and install it via scoop. Hope this helps! (TLDR make sure to uninstall everything via scoop and chocolatey before trying again)
