### ISSUE TITLE
Use /tmp/ Dir When download and Move Complete

### ISSUE THREAD

**Issue by candrapersada** [pystardust/ani-cli#871]
is it possible Use /tmp/ Dir When download and Move Complete like `-p <download_dir>` `-t <temp_dir>`

**Comment by port19x** [comment]
:thinking: 
assuming you want to download to `~/dl` on completion:
`ani-cli -p $(mktemp -d) && find /tmp/ -name "*.mp4" +exec mv {} $HOME/dl \;` or sth similar should work

**Comment by candrapersada** [comment]
after download, move complete from temp to external harddisk like `ani-cli -t $(mktemp -d) && find /tmp/ -name "*.mp4" -p D:\Video` for Windows

**Comment by candrapersada** [comment]
after download, move complete from temp to external harddisk like `ani-cli -t $(mktemp -d) && find /tmp/ -name "*.mp4" -p D:\Video` for Windows

**Comment by port19x** [comment]
Temp directories work different in Linux and Windows then. 
I don't like platform based branching in our code so I'll have to reject your request
