### ISSUE TITLE
Add some way to let mpv control the terminal.

### ISSUE THREAD

**Issue by TheHattedKid** [pystardust/ani-cli#876]
**Is your feature request related to a problem? Please describe.**
When I tried to use ani-cli with Yaft, mpv opens(by default in sixel mode on my PC), but just not on the terminal.

**Describe the solution you'd like**
A flag, like `-n`, to let mpv control the terminal, without displaying the menu.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by justchokingaround** [comment]
i don't really understand how this is related to the ani-cli script itself ngl

**Comment by port19x** [comment]
> i don't really understand how this is related to the ani-cli script itself ngl

Yeah, me neither.
What do you mean by controlling the terminal?
Do you want functional mpv bindings for next / previous as they exist in the playlist context?
Those should already be working with range selection iirc and expanding their availability would require undesireable readahead.
Closing as unplanned until you explain your request more verbosely, but even then we're unlikely to expand on our existing mpv integration
