### ISSUE TITLE
BNHA 5th Season Dub 8th Ep no link

### ISSUE THREAD

**Issue by DFireTech** [pystardust/ani-cli#877]
**Metadata**
Version: 3.3
OS: [Ubuntu Server
Shell: bash
Anime: My Hero Academia 5th Season Dub

**Describe the bug**
Could not download episode 8, said "Could not find link" Ran -dx, link was not there for all three providers. Can manually grab from animix.

**Steps To Reproduce**

1. Run `ani-cli -d boku no hero academia 5th season dub`
2. Choose episode 8

**Expected behavior**
Downloading should work

**Comment by Derisis13** [comment]
duplicate of #878

**Comment by DFireTech** [comment]
This wasnt a dupe, im still having this issue despite ani-cli being able to download episodes otherwise.
