### ISSUE TITLE
Unable to download any BNHA episodes from all referrers

### ISSUE THREAD

**Issue by DFireTech** [pystardust/ani-cli#878]
## Metadata

Version: 3.3
OS: Ubuntu Server 20.04
Shell: Bash
Anime: BNHA Dub 5th Season

## Description

Downloading is broken.
"Episodes not released yet!"

**Steps To Reproduce**

1. Run `ani-cli -d -rX boku no hero academia 5th season`
2. Choose 2 (*Dub)
3. Loads and gives above message in Description

**Expected behavior**
Downloading should work

## Additional Context

I tried with Ergo Proxy, just to make sure it would load episodes. Thus far, that one works just fine.

**Comment by TheGlockMisc** [comment]
Animix is apparently down.
![Screenshot_20220831_112212](https://user-images.githubusercontent.com/93582751/187578778-ffe97c51-d70a-4708-a738-9ba74773882d.JPG)

**Comment by DFireTech** [comment]
> Animix is apparently down.
> ![Screenshot_20220831_112212](https://user-images.githubusercontent.com/93582751/187578778-ffe97c51-d70a-4708-a738-9ba74773882d.JPG)
> 

I tried -r2 and -r3 and got same result. Gogoanime was up, but, the flag must have pulled from animix

**Comment by ExistingProgrammer** [comment]
> I tried -r2 and -r3 and got same result.
This flag just means which provider will be scraped **first**, and not that **only** the specific provider will be scraped. This should probably be changed to stop stuff like this occuring.

**Comment by Skepller** [comment]
Seems to be back now, ani-cli too of course.

**Comment by Derisis13** [comment]
Since there has been no update on this, I claim this solved
