### ISSUE TITLE
Episode doesn't exist but title will increment and play latest episode

### ISSUE THREAD

**Issue by lndexNull** [pystardust/ani-cli#881]
Version: 3.3.1
OS: EndeavourOS 5.19.6-arch1-1
Shell: zsh
Anime: One Piece (first occurence, works with every anime)

**Describe the bug**
When watching the last episode of any anime that is currently out and you press 'Enter', or prompt it to start the next episode, 
the last aired episode will start playing with the episode title showing an incremented episode count.

the 'Episode doesn't exist' warning does appear at the top of the terminal prompt btw.

**Steps To Reproduce**

1. Run `ani-cli' 
2. Choose any anime
3. Choose the last episode
4. press enter in the open terminal / prompt it to start the next episode

**Expected behavior**
'Episode doesn't exist' warning should appear and no Episode will be played

FYI: One Piece currently has 1031 episodes
![image](https://user-images.githubusercontent.com/58121540/188328260-cba2f791-f00f-4929-8b8c-d151868968de.png)

![image](https://user-images.githubusercontent.com/58121540/188328414-4f41536e-d929-4d89-9ed2-35dbae4fe885.png)

**Comment by port19x** [comment]
Tested with v3.3 (aka 3.3.1) v3.3.2 and v3.3.3 (current master)
Can't seem to reproduce the error.

Tested with one piece as provided in the bug report

**Comment by port19x** [comment]
Just reproduced. 
When on the last episode, (n) is not displayed as a possible next action but accepts it as an input anyway.
Once out of bounds the menu will continue to look like in the provided screenshot.

See the asciinema recording below
https://asciinema.org/a/ZnVpMEjbt7biOAuZeBYLWltuB

**Comment by port19x** [comment]
Pressing enter always defaults to (n). I think thats a good design descision.
Maybe we should exit on anime completion?

**Comment by justchokingaround** [comment]
ye, we should add a check to exit on completion

**Comment by Derisis13** [comment]
> Pressing enter always defaults to (n). I think thats a good design descision. Maybe we should exit on anime completion?

I don't think exit on completion is a good idea. I would consider quit as the default option though to avoid this situation.
