### ISSUE TITLE
Request - Include list of anime that's popular, new, etc

### ISSUE THREAD

**Issue by daromer** [pystardust/ani-cli#89]
Not an issue, but a request.  Can you add an option to get a list of new and popular anime?  That way we can check which one to look for to watch/download, for example, if new episodes are added.

**Comment by r4vanan** [comment]
hmm intresting i may be consider this

**Comment by ura43** [comment]
This could be part of a larger move to integrate with a tracking provider like Anilist.
@r4vanan if you want to investigate our options there, I'd appreciate the help

**Comment by ura43** [comment]
The checking for new episodes of shows you already watch is handled in #86 
Everything beyond that would require integration with some database service like anilist which is very out of scope.
This could be its own application actually.
I hope you understand me closing this for the time being
