### ISSUE TITLE
Non-zero exit code when using `-h` flag

### ISSUE THREAD

**Issue by xezo360hye** [pystardust/ani-cli#891]
**Metadata (please complete the following information)**
Version: 3.4.0 (AUR ani-cli-git)
OS: Arch Linux (btw)
Shell: zsh
Anime: None

**Describe the bug**
Using `ani-cli -h` exits with code 1 because flag `-h` is NOT handled in `while getopts` loop and goes straight to `*)` case. Also should be greate to add long flags support (e.g. `--help`), but that's a feature request and I probably should open another issue for that?

**Steps To Reproduce**

1. Run `ani-cli -h`

**Expected behavior**
It should exit with code 0 as most software does when invoking help/usage flag

**Screenshots (if applicable; you can just drag the image onto github)**
![image](https://user-images.githubusercontent.com/79970533/189489732-335f1594-be49-4581-83ca-32b3513e451d.png)

**Additional context**
None

**Comment by mrfluffy-dev** [comment]
Can't reproduce.

**Comment by xezo360hye** [comment]
> Can't reproduce.

You mean it exits normally (0) for you? In that case you're probably using "patched" version or something as there is literally no handler for `-h` flag - just checked the master branch

**Comment by mrfluffy-dev** [comment]
OO no I see I did not run the echo my bad.

**Comment by justchokingaround** [comment]
yes, this we've already thought about that actually. it's indeed very bad practice, and i think we should probably restructure the way the arguments in the script work completely. right now `--help` will work because `*) ` handles it, but to get actual full support for long args we would need to change the whole args code (which i'm in favor of)

**Comment by port19x** [comment]
I remember we had both `h)` which exited with zero exit code and `*)` which exited with 1 exit code, but otherwise the two were calling the same function. We removed explicit `h)` during some refactoring, but might as well add it again
