### ISSUE TITLE
Missing Dependency "Axel"

### ISSUE THREAD

**Issue by Khoomn** [pystardust/ani-cli#892]
**Metadata**
Version: 2.2
OS: Windows 10
Shell: Git Bash

**Describe the bug**
Originally was trying to watch lycoris recoil, it then never showed the name of the show at all so I decided to update using "ani-cli -U" and it said updated but missing axel. I tried uninstalling and reinstalling it and it is still missing axel dependency. Cannot find how to install axel or find the package at all when using "scoop install axel"

**Steps To Reproduce**

Follow install steps

scoop bucket add extras
scoop install ani-cli

**Expected behavior**
Program properly installing

**Screenshots (if applicable; you can just drag the image onto github)**
![image](https://user-images.githubusercontent.com/20747451/189515048-13720501-6013-431d-bd32-e02bf991897b.png)

**Comment by port19x** [comment]
Thats weird, let me check the scoop repos.
If axel really isn't packaged by them we need to document that more carefully.
2.2 still works?

**Comment by port19x** [comment]
Axel does indeed seem to be missing

**Comment by port19x** [comment]
Except it doesn't. It's in their main repos, not in extra

**Comment by Khoomn** [comment]
> Thats weird, let me check the scoop repos. If axel really isn't packaged by them we need to document that more carefully. 2.2 still works?

2.2 does not work. I tried it on my windows pc and my linux VM so for both of them it gives the same error

**Comment by Khoomn** [comment]
![image](https://user-images.githubusercontent.com/20747451/189597790-0d29c08d-f4fd-4995-87f4-bbb48346a7f6.png)

**Comment by port19x** [comment]
> > Thats weird, let me check the scoop repos. If axel really isn't packaged by them we need to document that more carefully. 2.2 still works?
> 
> 2.2 does not work. I tried it on my windows pc and my linux VM so for both of them it gives the same error

can confirm 2.2 doesn't work anymore.
Axel is supposed to be in the scoop main bucket [link](https://github.com/ScoopInstaller/Main/blob/master/bucket/axel.json)

**Comment by port19x** [comment]
Closing this issue as it's not reproducible. Raise an issue with scoop if this persists
