### ISSUE TITLE
no anime in list - android

### ISSUE THREAD

**Issue by TheRealOne78** [pystardust/ani-cli#893]
**Metadata**
Version: 2.2.0 
OS: termux
Shell: zsh
Anime: any

**Describe the bug**
When I search for any anime, ani-cli will return only:
```
(1)
(q) exit
>
```
It's not even returning "Not found" or something, just a blank first option which will return
```
Loading episode 1...
Episode doesn't exist!!
Video URL not found
```
and exit option.

**Steps To Reproduce**

1. Run `ani-cli` with any anime

**Expected behavior**
It should give me a list of anime or return me with 404 if anime does not exist.

**Screenshots**
![Screenshot_20220911-221416_Termux.png](https://user-images.githubusercontent.com/53640879/189545069-6663c685-733d-4b9d-b1e2-bfb7061d3801.png)
![Screenshot_20220911-221356_Termux.png](https://user-images.githubusercontent.com/53640879/189545074-797fb802-16dd-447f-a428-4ecb65be2638.png)

I've made sure it's up-to-date.

**Comment by CoolnsX** [comment]
Well first update to latest version(v 3.4)
And second.. the url in ur version is expired and should be change to gogohd.net if u want to continue using that version

**Comment by TheRealOne78** [comment]
> Well first update to latest version(v 3.4)
> And second.. the url in ur version is expired and should be change to gogohd.net if u want to continue using that version

This is kinda weird, my packages are up-to-date, yet ani-cli is still 2.2.0.
Is ani-cli in termux's repo really up to date?
![Screenshot_20220911-234236_Termux.png](https://user-images.githubusercontent.com/53640879/189548131-363348b2-16e2-4cbb-a00c-0b675016c533.png)

**Comment by port19x** [comment]
I'll make a PR downstream

**Comment by port19x** [comment]
v3.4 is in termux

**Comment by TheRealOne78** [comment]
thx bro

![Screenshot_20220912-192102_Termux.png](https://user-images.githubusercontent.com/53640879/189705597-b3ec96f9-c11c-4655-984d-68b3bd60726a.png)
