### ISSUE TITLE
Episodes not released yet

### ISSUE THREAD

**Issue by Marguesto** [pystardust/ani-cli#898]
**Metadata (please complete the following information)**
Version: [e.g. 3.4.0]
OS: [e.g. Void Linux]
Shell: [e.g. dash]
Anime: [any anime e.g. neon genesis evangelion] 

**Describe the bug**
whenever I select an anime, it says _Episodes not released yet!_. 

 

**Steps To Reproduce**

1. Run `ani-cli (any anime e.g. neon genesis evangelion)`
2. Choose (any number e.g. 1) 

**Expected behavior**
The anime's episodes should appear

**Screenshots**

![ani-cli](https://user-images.githubusercontent.com/70781290/190276718-aae81ba7-6f95-48ce-8eaf-4ecd9cad0fcf.png)

**Comment by Derisis13** [comment]
Can't reproduce - are you sure you're on 3.4.0?

**Comment by CoolnsX** [comment]
![Screenshot_20220916-124713-485](https://user-images.githubusercontent.com/76195824/190579519-8ba7291a-9ad4-454d-8af1-e26c3d260a50.png)

**Comment by Marguesto** [comment]
> Can't reproduce - are you sure you're on 3.4.0?
yeah
 I have also checked the dependencies and they all work fine!

**Comment by justchokingaround** [comment]
does animixplay in the browser work for u?

**Comment by wasteOfOxygen001** [comment]
I have the same issue

I have run reinstalled and still have the issue

I am on version 3.4.1

**Comment by wasteOfOxygen001** [comment]
It was because I was in Japan, a vpn fixes the issue

I realised that it only stopped working after I went to Japan

In Japan, the animix thing says that the site is closed

**Comment by gnoirzox** [comment]
I am located in the UK and I do have the exact same issue on version 3.4.0.

**Comment by port19x** [comment]
> I am located in the UK and I do have the exact same issue on version 3.4.0.

Check out the v4 branch, we're still working on a breakage that started when animixplay ceased to exist on christmas '22

**Comment by narrative-duck** [comment]
sudo ani-cli -U
