### ISSUE TITLE
Can i change anime site?

### ISSUE THREAD

**Issue by HavaliRumuz** [pystardust/ani-cli#899]
Can i change anime site?

**Comment by Derisis13** [comment]
Yes, if you edit the script. Otherwise we don't plan to change providers, but we're open to the discussion.

**Comment by HavaliRumuz** [comment]
> Evet, betiği düzenlerseniz. Aksi takdirde sağlayıcıları değiştirmeyi planlamıyoruz, ancak tartışmaya açığız.

Thanks.

**Comment by mercifulboss** [comment]
> Yes, if you edit the script. Otherwise we don't plan to change providers, but we're open to the discussion.

would it be possible to allow the user to change providers directly from cli (like implement a function to parse one provider to another) directly from the app?
