### ISSUE TITLE
Download fails on episode 5

### ISSUE THREAD

**Issue by Wolf220** [pystardust/ani-cli#900]
*Metadata*
Version: [e.g. 2.0.2]
OS: Arch Linux and Android (thanks to mrfluffy#3489 for testing on android)
Shell: zsh
Anime: Banana Fish and Erased

**Describe the bug**
Episode 5 of the listed animes, maybe more, fail to download. All episodes download successfully, until it gets to the "initializing download" stage, and doesn't do anything from there.

**Steps To Reproduce**

1. Install latest version of ani-cli
2. Run ani-cli -p [directory] -q best
3. Search one of the listed animes, select the undubbed version
4. select either a variety of episodes containing 5, or just 5.

**Expected behavior**
Downloading should work for all selected episodes

**Comment by Derisis13** [comment]
You're running a severely outdated version of the script, please upgrade. 
Do note that because of the changes made to the project structure you may or may not have  to reinstall the whole program.

**Comment by port19x** [comment]
> sorry, i'm running the latest version, pulled from github yesterday, i just forgot to update the number. Funny thing is, i tried an older version after i found the bug, and it worked fine.

Could you fill us in on what older version worked? 
There seem to be some regressions recently and we need to track those down

**Comment by Wolf220** [comment]
I don't remember what old version I downloaded, I think it was something in July (wasn't sure how old the bug was) but I didn't find the error until using the version I downloaded about 3-4 days ago, if I remember correctly

**Comment by Wolf220** [comment]
I don't remember what old version I downloaded, I think it was something in July (wasn't sure how old the bug was) but I didn't find the error until using the version I downloaded about 3-4 days ago, if I remember correctly

**Comment by port19x** [comment]
works on my machine :shrug: 

![e1](https://user-images.githubusercontent.com/82055622/190699250-28e52cbf-646c-4489-97d6-8e360964ae8a.png)
![e2](https://user-images.githubusercontent.com/82055622/190699257-5e738f00-8bca-4a32-8048-1b434b3a38da.png)

**Comment by mrfluffy-dev** [comment]
![Screenshot_20220916_183818_com termux](https://user-images.githubusercontent.com/53239525/190699884-416f4ec1-fd25-4c9d-8b90-ff3e563d4adb.jpg)
Yeah no seems to work again yesterday when I tested it, it didn't work at all.

**Comment by Wolf220** [comment]
Huh, just tried it again, it's working for me too now. must have been a server issue or something. Thanks anyways, sorry to waste your time.
