### ISSUE TITLE
grep and history file error

### ISSUE THREAD

**Issue by Daiatt** [pystardust/ani-cli#901]
Version: 3.4.0
OS: Arcolinux
Shell: zsh
Anime: Code Geass Lelouch of The Rebelion R2

**Describe the bug**
*grep error (invalid argument) after selecting episode (video still playing fine) 
*duplicating entry in history file (in this case Code Geass Lelouch of The Rebelion R2).

**Steps To Reproduce**
1. Run ani-cli code geass
2. Choose 8 (Code Geass Lelouch of The Rebelion R2)
3. Choose episode 1

**Expected behavior**
No grep and history file error 

**Screenshots**
![ani-cli](https://user-images.githubusercontent.com/100219005/190858802-890837be-26f5-47f3-a4ad-c362e9c6647b.png)
grep error

![anihist](https://user-images.githubusercontent.com/100219005/190858812-de5282e4-a813-4115-9c81-4a46ab765306.png)
duplication in history file

**Comment by justchokingaround** [comment]
maybe this is an issue that happened after using different versions of ani-cli. have you tried deleting the history file and using the script again? if you still encounter the issue can you send me the output of `sh -x $(which ani-cli) -c` so that i can see where it breaks

**Comment by justchokingaround** [comment]
nvm my comment, i get the issue now, working on it

**Comment by 0WN463** [comment]
@justchokingaround , are you still working on this? Otherwise I've already created a PR which addresses the issue

**Comment by justchokingaround** [comment]
will check it out later today :+1: thanks

**Comment by Derisis13** [comment]
#920
