### ISSUE TITLE
Can't load anime even though the script is up to date

### ISSUE THREAD

**Issue by p0lq** [pystardust/ani-cli#902]
**Metadata (please complete the following information)**
Version: 20.3
OS: Linux Mint 20.3
Shell: Bash 5.0.17
Anime: Berserk, happened with other titles aswell, such as K-on! or Rurouni Kenshin

**Describe the bug**
When I start to search for anime, it doesn't list them as it previously did. Ani-cli now shows only 2 selections, 1 with blank and Q for quit. I did sudo ani-cli -U and the script is up to date.

**Steps To Reproduce**

1. Run `./ani-cli`
2. Look for any anime, on my case it was Berserk, K-on! or Rurouni Kenshin
3. Choose episode 1
![ani-cli_problem2](https://user-images.githubusercontent.com/94566300/190923590-46963985-a474-4d1f-b5a3-bd9b0da5f204.png)
![ani-cli_problem](https://user-images.githubusercontent.com/94566300/190923592-bdac48bd-aba4-4007-8f54-1efd7a57333a.png)

**Comment by justchokingaround** [comment]
run `ani-cli` not `./ani-cli`. u updated the script u have in /usr/local/bin not the one u have in ~/Documents. otherwise clone the repo if u haven't and use git pull. if u do `./ani-cli -V` u'll see it's outdated

**Comment by p0lq** [comment]
Ah, I see! It works like it should now.
