### ISSUE TITLE
Use global environment variables instead of some options

### ISSUE THREAD

**Issue by TheTrveAnthony** [pystardust/ani-cli#903]
Hi,

I'd like to be able to use fzf without having to type the `-f` option (yes I am lazy), so I thought about using a global environment variable for this. This could also be used for those who don't use mpv.

So basically the user who have to set them like this :
```bash
# enable fzf
export ANICLI_FZF=1  # or true
# use vlc
export ANICLI_PLAYER="vlc"  
```

Could this be added this to the script ?

**Comment by justchokingaround** [comment]
why not just make an alias?
```sh
alias ani-cli="ani-cli -vf"
```

**Comment by TheTrveAnthony** [comment]
In deed, I had not thought about this

**Comment by justchokingaround** [comment]
>leaves
