### ISSUE TITLE
after selecting a anime, player does not open and quiting gives a error

### ISSUE THREAD

**Issue by silverhikari** [pystardust/ani-cli#904]
**Metadata (please complete the following information)**
Version: 3.4.1
OS: manjaro
Shell: bash
Anime: tested onepiece and onigamiden

**Describe the bug**
as stated above when playing any anime, the player will not launch and after quiting a error appears 

```
/usr/bin/ani-cli: line 645: 676106 Floating point exception(core dumped) nohup "$player_fn" "$video_url" --referrer="$refr" --force-media-title="$trackma_title" > /dev/null 2>&1
```

**Steps To Reproduce**

1. Run `ani-cli one piece
2. Choose 1
3. Choose episode 1

**Expected behavior**
mpv opens playing video

**Comment by Derisis13** [comment]
Please run `which mpv` and `mpv --version` and share the output here.

**Comment by silverhikari** [comment]
which mpv gives /usr/bin/mpv and mpv version gives me this 
```
mpv 0.34.1-dirty Copyright © 2000-2021 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
FFmpeg library versions:
   libavutil       57.17.100 (runtime 57.28.100)
   libavcodec      59.18.100 (runtime 59.37.100)
   libavformat     59.16.100 (runtime 59.27.100)
   libswscale      6.4.100 (runtime 6.7.100)
   libavfilter     8.24.100 (runtime 8.44.100)
   libswresample   4.3.100 (runtime 4.7.100)
FFmpeg version: n5.1.1
```

**Comment by silverhikari** [comment]
i found out the issue was a problem with hwdec in mpv, removing that allowed videos to appear and play
