### ISSUE TITLE
How to Play anime on VLC on Termux (android)

### ISSUE THREAD

**Issue by FrankensteinEvil0069** [pystardust/ani-cli#908]
Hi, 
I was having this issue of not getting to play anime on Vlc on Termux on android 

ani-cli had mentioned that they had vlc working but I can't seem to figure out if it's there on android yet 
If not, I would highly request you to add this feature on termux android.

If yes, then could please help how to properly set it up on termux android 
Thanking you in anticipation.

PS: Ani cli is just amazing

**Comment by CoolnsX** [comment]
```ani-cli -v```
always check the help menu with
```ani-cli -h```

**Comment by FrankensteinEvil0069** [comment]
Thanks it worked
