### ISSUE TITLE
Wrong error message for the missing path when using -p argument.

### ISSUE THREAD

**Issue by ahmadjehad** [pystardust/ani-cli#910]
**Metadata**
Version: 3.4.1
OS: Windows 11
Shell: windows terminal PowerShell
Anime: fist of the north star

**Describe the bug**
Downloading is broken.
It says "please retry or check your internet connection" see screenshot.

**Steps To Reproduce**

1. Run `ani-cli.cmd -p fist of the north star`
2. Choose 1
3. Choose episode 1 or  any number

**Expected behavior**
It should display a relative error message like eg. "missing download path" or something similar

**Screenshots**

![2022-10-10_18-19-28](https://user-images.githubusercontent.com/45077440/194937329-761d8444-662c-4a0d-867e-231cfb32bc27.jpg)

**Comment by port19x** [comment]
In your provided example the download path isn't missing.
"fist" gets parsed as the download path and "of the north star" remains as the search string.
It then fails due to #868

**Comment by ahmadjehad** [comment]
it is still a wrong error message and should be fixed
