### ISSUE TITLE
Adding a function to discover new anime without having to go external site

### ISSUE THREAD

**Issue by mercifulboss** [pystardust/ani-cli#911]
**Is your feature request related to a problem? Please describe.**
Its related to inconvenience - it makes little sense to need to go to external sites to discover new animes and then play it from the CLI. It would be nice (and convenient) to be able to discover new animes from the CLI as well. 

**Describe the solution you'd like**
Please add a scraper that gathers information on the latest (or most popular) animes and adds a description that allows us to discover new animes to watch straight from the CLI. 

Maybe even add a filter option to discover new animes by genre or something. Not sure how difficult this would be to implement

**Describe alternatives you've considered**
Adding links to trailers to play directly from mpv on linux or even album art or IMBD ratings

**Comment by CoolnsX** [comment]
We don't have popular anime but we have latest releases anime option..
Use ```ani-cli -n```

**Comment by port19x** [comment]
Anime discovery does not fit the scope of the project.
Closing as unplanned
