### ISSUE TITLE
Manpage missing on Arch Linux-based systems

### ISSUE THREAD

**Issue by olddesklamp** [pystardust/ani-cli#916]
Version: 3.4.2
OS: EndeavourOS
Shell: fish, bash

No manpage despite being there being one present in the source code.

**Steps To Reproduce**

1. Run `man ani-cli` 
2. <details><summary>Get error message stating there's no manual entry for ani-cli.</summary>
    <p>

    ![image](https://user-images.githubusercontent.com/74428438/196329128-67dd0d7f-43b0-45a9-9df5-3f1ea2cabed8.png)

    </p>
    </details>

**Expected behavior**
The manpage written for Debian systems to appear.

**Additional context**
I've previously used ani-cli on Kubuntu where this wasn't an issue. I'm aware that the manpage was intended for use on Debian systems, but [it states that it can be used for any system](https://github.com/pystardust/ani-cli/blob/955a603602f28dde6995ecd530f897d6625e1bb8/ani-cli.1.gz#L91).

**Comment by Derisis13** [comment]
What is your installation method? Did you get it from the AUR or did you install it by downloading (cloning) and moving to path?

**Comment by olddesklamp** [comment]
It was installed manually from the AUR without a helper.

**Comment by Derisis13** [comment]
Looking at the PKGBUILD it is clear that the manpage is not copied in case of an arch installation. I'll signal the issue to the AUR maintainer and see what we can come up with. There might be a reason he didn't include the man page.

**Comment by sgtxd** [comment]
The changes have been made to the PKGBUILD to also copy the man page over
