### ISSUE TITLE
Hex string is too short, padding with zero bytes to length - bad decrypt

### ISSUE THREAD

**Issue by rgm89git** [pystardust/ani-cli#919]
**Metadata (please complete the following information)**
Version: 3.4
OS: Windows 10
Shell: Git Bash

**Describe the bug**
Doesn't open, because of hex string errors.
`hex string is too short, padding with zero bytes to length`

**Steps To Reproduce**

1. Run `ani-cli`
2. Search for "kodocha"
3. Choose 2 (kodomo no omocha tv dub)
4. Choose episode 21

**Expected behavior**
The hex string doesn't do errors and the episode is working

**Screenshots (if applicable; you can just drag the image onto github)**
![image](https://user-images.githubusercontent.com/40833244/197245736-9d6dc0d6-a3cb-48a7-924d-9626f53760e3.png)

**Additional context**

**Comment by CoolnsX** [comment]
run ```ani-cli -U``` in git-bash

**Comment by rgm89git** [comment]
```
patching file /usr/local/bin/ani-cli
Hunk #1 FAILED at 1 (different line endings).
1 out of 1 hunk FAILED -- saving rejects to file /usr/local/bin/ani-cli.rej
Can't update ani-cli for some reason!
```

**Comment by CoolnsX** [comment]
> ```
> patching file /usr/local/bin/ani-cli
> Hunk #1 FAILED at 1 (different line endings).
> 1 out of 1 hunk FAILED -- saving rejects to file /usr/local/bin/ani-cli.rej
> Can't update ani-cli for some reason!
> ```

send that /usr/local/bin/ani-cli.rej file

**Comment by rgm89git** [comment]
[ani-cli.rej.zip](https://github.com/pystardust/ani-cli/files/9840959/ani-cli.rej.zip)

**Comment by CoolnsX** [comment]
can u still able to run ur ani-cli fine??

**Comment by rgm89git** [comment]
Yeah, but the error is still going

I suppose is from the `Fetching Goload Direct links...` or something...

**Comment by rgm89git** [comment]
I will try to reinstall through Scoop

**Comment by rgm89git** [comment]
Ok, it worked just deleting the /usr/local/bin ani-cli files and reinstalling through Scoop.

That's strange LOL
But, hey, @CoolnsX , thanks for the great help.

**Comment by CoolnsX** [comment]
Noice.. thanks
