### ISSUE TITLE
Place history file in $XDG_STATE_HOME

### ISSUE THREAD

**Issue by microo8** [pystardust/ani-cli#923]
The history file is now by default in `$XDG_CACHE_HOME` (`~/.cache/`). Which is a problem, because the cache folder is just for caching data. When I run BleachBit it deleted my history file :(

The better approach would be to save the history file in `$XDG_DATA_HOME` (`~/.local/share`) or even better in `$XDG_STATE_HOME` (`~/.local/state`) where also nvim, pipewire, tofi and others store history and logs.

**Comment by Derisis13** [comment]
`$XDG_STATE_HOME` is a good idea. Can we squeeze it into #922 ?

**Comment by CoolnsX** [comment]
Yus we can.. we hv to Provide the documentation on moving the history file to that location..

**Comment by Derisis13** [comment]
On a second thought maybe we shouldn't just shove it into a minor release. This would require some interaction from the users and should get a separate version.

**Comment by port19x** [comment]
I doubt the inconvenience of the history file being in the `$XDG_CACHE_HOME` is even remotely as big as the inconvenience of moving the history file on a version upgrade.

The only way this would get implemented is if we either find a way to move the history file in a non-disruptive way, or if we need to restructure the history file in the future

**Comment by port19x** [comment]
This could be done by checking for an existing file in `$XDG_CACHE_HOME` and creating a hardlink to that file.
If such a file does not exist, fresh history files would be placed in `XDG_STATE_HOME`

**Comment by Derisis13** [comment]
fixed by #955

**Comment by Derisis13** [comment]
This was done in v4, along with overwritable history path.
