### ISSUE TITLE
How to configure Path of MPV manually in Windows

### ISSUE THREAD

**Issue by PhoenixCODE2322** [pystardust/ani-cli#925]
**Metadata (please complete the following information)**
Version: 3.4
OS: Windows 11 22H2
Shell: bash

**Describe the bug**
mpv command not found

**Steps To Reproduce**

1. Run windows Terminal
2. Open Git Bash Profile
3. type mpv

**Expected behavior**
it list mpv commands

**Screenshots (if applicable; you can just drag the image onto github)**
![image](https://user-images.githubusercontent.com/75798544/200124965-ebe0994a-3c43-4cd6-a05c-c7c17991d56a.png)
![image](https://user-images.githubusercontent.com/75798544/200124983-dfd1be54-35a2-4fdf-8939-733b321edaab.png)

**Additional context**
I am already using MPV with alot of plugins. So i want to use that mpv files instead of installing one through scoop.
But nonetheless , i installed scoop , installed mpv and it is working . I wanted to see how scoop sets path so i can mimic that. 
But failed. As you can see in the screenshot , Powershell detects mpv but Git bash fails to. Can you please tell how should i add MPV to path in windows 11.

**Comment by Derisis13** [comment]
https://stackoverflow.com/questions/45980107/extend-path-variable-in-git-bash-under-windows

**Comment by PhoenixCODE2322** [comment]
Thank you .. will look into this.
