### ISSUE TITLE
Episodes not released yet! for all anime on WSL2 Windows 11 (Ubuntu)

### ISSUE THREAD

**Issue by AviVarma** [pystardust/ani-cli#926]
**Metadata (please complete the following information)**
Version: [e.g. 2.0.2]
OS: [Windows 11,  Ubuntu 22.04.1 LTS]
Shell: [bash]
Anime: [Naruto] (if applicable)

**Describe the bug**
![image](https://user-images.githubusercontent.com/22505740/200435454-4cdf8294-8268-4771-a237-57a04ea311b0.png)

**Steps To Reproduce**

run the following:

1.  `ani-cli naturo`
2. 1

**Expected behavior**
I should be able to stream the anime.

**Screenshots (if applicable; you can just drag the image onto github)**
![image](https://user-images.githubusercontent.com/22505740/200435454-4cdf8294-8268-4771-a237-57a04ea311b0.png)

**Additional context**
I am in the UK and am able to connect to 9Anime manually using firefox.

**Comment by justchokingaround** [comment]
we are scraping animixplay not 9anime. if you can't access it through a browser (which is most likely the case), then you need to use either a vpn or a proxy, i'd recommend going to the website: 1.1.1.1

**Comment by Derisis13** [comment]
If this is really version 2.0.2, then it won't work. You have to upgrade to the latest release using `ani-cli -U`. Also we're not sure if the script works well in WSL at all (it most certainly won't use your windows executables for playback, so you need to have at least x11 set up), you have much better chances with git bash (see: readme)

**Comment by AviVarma** [comment]
I am able to watch anime on animixplay in my browser, this does seem to be an intermitent failure because when I query `spy x family` I get "no episodes released yet" for season 1 but I am able to find and watch episiodes for season 2!
![image](https://user-images.githubusercontent.com/22505740/200678864-3195c1bb-e6f5-4d0e-9457-e217fb5998e4.png)

> Also we're not sure if the script works well in WSL at all (it most certainly won't use your windows executables for playback, so you need to have at least x11 set up), you have much better chances with git bash (see: readme)

Im on Windows 11, x11 tunneling is now enabled by default so you can run linux GUI programs under windows!

**Comment by Derisis13** [comment]
Have you tried running `ani-cli -U`?

Also I checked, the sub of spy x fam has no Xstreamcnd link whereas the dub has. This is the difference I could find between them.

**Comment by AviVarma** [comment]
Yes, I ran ani-cli -U before running ani-cli shown in the screenshot from my previous reply.

**Comment by AviVarma** [comment]
Strange, I've tested watching naruto, naruto shippuden and Spy X family, and all queries worked correctly with a successful stream. I guess it might have been a animixplay / VPN issue.
