### ISSUE TITLE
Error while searching anime

### ISSUE THREAD

**Issue by stonedseeker** [pystardust/ani-cli#929]
**Metadata (please complete the following information)**
Version: [e.g. 2.0.2]
OS:  Windows 11 / Debian
Shell: cmd/bash
Anime: All of them

**Describe the bug**
As soon as I enter an anime name, search query starts and soon it tells "No search results found" (check screen shot)
I tried installing in WSL Debian too, but the issue still persists. 

**Steps To Reproduce**

1. Run `ani-cli -d flcl`
2. Choose 2 (fooly-cooly)
3. Choose episode 1

**Expected behavior**
Downloading should work

**Screenshots (if applicable; you can just drag the image onto github)**
![image](https://user-images.githubusercontent.com/93109628/202456092-ccae5d3e-982e-4f49-ae02-67941c22f43e.png)

**Comment by Derisis13** [comment]
2.0.2 is a severely outdated version. Run `sudo ani-cli -U` on linux to update and `ani-cli -U` on windows in git bash ran as administrator to fix.
