### ISSUE TITLE
"ani-cli" Command Not Found

### ISSUE THREAD

**Issue by Inferius7809** [pystardust/ani-cli#93]
I'm fairly certain I've followed the installation instructions for Windows, but after running the GitBash commands to install, whenever I try to use the script, it keeps saying the "ani-cli" command isn't found.

**Comment by Inferius7809** [comment]
> Try use `./ani-cli-win` within the directory

That command Worked. Thank you! I have to use it within GitBash, and not Windows Command Prompt. But it works, it gets the episode data and pulls up VLC. Thank you for the help. 

Is this just a newbie issue? Like is it pretty universal knowledge that for Windows and GitBash, you have to use "./" in front of commands?

**Comment by Shulkk** [comment]
> > Try use `./ani-cli-win` within the directory
> 
> That command Worked. Thank you! I have to use it within GitBash, and not Windows Command Prompt. But it works, it gets the episode data and pulls up VLC. Thank you for the help.
> 
> Is this just a newbie issue? Like is it pretty universal knowledge that for Windows and GitBash, you have to use "./" in front of commands?

Nope, it's just because there's no environment variable set, you have to set that yourself, and running bash programs (on unix-like systems start with ./<program_here> if it's not set as an env variable.
