### ISSUE TITLE
Add feature to be able to use 9anime as provider

### ISSUE THREAD

**Issue by vvirtues** [pystardust/ani-cli#932]
**Is your feature request related to a problem? Please describe.**
I believe you should be able to switch to 9anime cuz why not

**Describe the solution you'd like**
add 9anime as stream link

**Describe alternatives you've considered**
- Ignoring this and using other sites already supported

**Additional context**
idk I just like it better but no one likes ads 🤷🏿‍♂️

**Comment by justchokingaround** [comment]
#523 4th point
