### ISSUE TITLE
Request for implementation of ani-skip feature for auto-skipping opening sequences in ani-cli

### ISSUE THREAD

**Issue by synacktraa** [pystardust/ani-cli#939]
As a user of the **ani-cli**, I am requesting the implementation of a new feature called [**ani-skip**](https://github.com/synacktraa/ani-skip). This feature would allow users to choose whether or not they want to automatically skip the opening sequences of an anime episode when using the **ani-cli**.

This feature would be especially useful for those who have already watched the opening sequence or simply want to get to the main content of the episode as quickly as possible. It would save users time and make the viewing experience more efficient.

I suggest that this functionality could be accessed using some flag. For example, `ani-cli -flag` would enable the feature, while `ani-cli` would disable it. This would allow users to easily toggle the feature on or off as needed.

Thank you for considering this feature request.

**Comment by CoolnsX** [comment]
It may be impossible cause the source we scrape now, doesn't use MAL ID..

**Comment by trueauracoral** [comment]
If you use mpv, check out https://github.com/rui-ddc/skip-intro it works wonderfully. It jumps to a place where the audio is silent. That is most likely when the intro ended.

**Comment by synacktraa** [comment]
> It may be impossible cause the source we scrape now, doesn't use MAL ID..

I revised the script so that it can now retrieve the MAL ID based on a specified anime title.
Check it out: <a href="https://github.com/synacktraa/ani-skip">ani-skip</a>

**Comment by port19x** [comment]
> If you use mpv, check out https://github.com/rui-ddc/skip-intro it works wonderfully. It jumps to a place where the audio is silent. That is most likely when the intro ended.

If this works as well as I think it does, skip-intro is a suitable stopgap solution.

ani-skip would be a very worthwhile addition to ani-cli. Maybe we can can make it happen in late march

**Comment by synacktraa** [comment]
> ani-skip would be a very worthwhile addition to ani-cli. Maybe we can can make it happen in late march

I would be happy to open a pull request for the feature enhancement, but it might take me some time to complete it. Before I start, I'll need to familiarize myself with how everything works in ani-cli.

**Comment by port19x** [comment]
In case you're still having some trouble I can walk you through the codebase on discord or jitsi if you'd like.
It's shell, so it's always going to be a bit hard to read

**Comment by synacktraa** [comment]
Actually, I'm busy with uni exams rn, I'll start working on it next week...If I encounter any problem I'll ping you

**Comment by port19x** [comment]
Reopen if you still have interest in impelementing
