### ISSUE TITLE
"Episodes not released yet!" error

### ISSUE THREAD

**Issue by notdexterslab** [pystardust/ani-cli#944]
**Metadata (please complete the following information)**
Version: 3.4.0
OS: EndeavourOS x86_64
Shell: `bash`
Anime: Blue Gender

**Describe the bug**
Unable to connect to scrape site when trying to watch/download an anime.

**Steps To Reproduce**

1. Run `ani-cli -d blue gender` (or run without `-d`)
2. Choose 1 (blue gender)

**Expected behavior**
Downloading/watching should work.

**Additional context**
Attempting to connect to https://animixplay.to/ gives the following error page on Firefox (tested with an arkenfox profile as well as a fresh profile):

```
An error occurred during a connection to animixplay.to. SSL received a record that exceeded the maximum permissible length.

Error code: SSL_ERROR_RX_RECORD_TOO_LONG
```

I have also tried this with other shows (e.g. `ani-cli -d mobile suit gundam`) and receive the same error.

**Comment by Derisis13** [comment]
I have just attempted to reproduce, but it works fine. I can access animixplay from my browser as well. Please try it again, if it works, it was a temporary outage, otherwise you're behind some sort of network filtering that disallows animixplay.

**Comment by notdexterslab** [comment]
Wow turns out my internet service was blocking the site without telling me. I had to download a whole separate app in order to even see what sites it was automatically blocking.
