### ISSUE TITLE
Episodes not released yet! Error on any anime I tried

### ISSUE THREAD

**Issue by Aroko-RO** [pystardust/ani-cli#947]
**Metadata (please complete the following information)**
Version: 3.4
OS: Ubuntu 22.10
Shell: Dash
Anime: not applicable

**Describe the bug**
Episodes not released yet! error on all anime I tried to view.

**Steps To Reproduce**

1. Run `ani-cli example:spy x family`
2. Choose Any Options
3. Error appers

**Expected behavior**
Anime to be released and viewed.

**Screenshots 
![Screenshot from 2022-12-23 12-53-32](https://user-images.githubusercontent.com/88131513/209323945-364541a1-930d-46d9-9feb-2a8f14b7962d.png)

**Comment by devraza** [comment]
This is because the first provider `ani-cli` scrapes (https://animixplay.to) has shutdown. Forever. See https://github.com/pystardust/ani-cli/issues/948

**Comment by Fmert24** [comment]
so source of one is not usable ok then r1 or 3 must work right then why i cant download any episode then
-r1 -r2 -r3 flags gives the episode not released yet error 
![Uploading Screenshot_20221223-192845_Termux.jpg…]()

**Comment by port19x** [comment]
I'd prefer to track this issue in #948 
Closing for now
