### ISSUE TITLE
Animixplay EOL / Episode not released yet

### ISSUE THREAD

**Issue by docfaizal** [pystardust/ani-cli#948]
![Screenshot_12](https://user-images.githubusercontent.com/107258640/209325024-260a97d2-bf33-47aa-990f-03bdcf368f30.png)
Please add either 9anime or zoro as sources

**Comment by port19x** [comment]
I'll actively manage this outage once I get home.
For now rest assured I'm aware of it and thinking of options

**Comment by port19x** [comment]
For those who want to read the farewells themselves: [animixplay](https://animixplay.to/)

**Comment by port19x** [comment]
ani-cli's `-r` flag is ignored.
`bash -x ani-cli -r n flcl` returns the below screenshot for any n ∈ {1,2,3}

![2022-12-23_17-48](https://user-images.githubusercontent.com/82055622/209371924-5bfc947e-fc63-42ad-bf20-21d703fda9a8.png)

**Comment by port19x** [comment]
`bash -x ani-cli -a 1 -r 3 flcl`
[debug log](https://oshi.at/MCNa/debug-log.txt
)

**Comment by port19x** [comment]
In the meantime you might as well use @justchokingaround's [jerry](https://github.com/justchokingaround/jerry)

**Comment by docfaizal** [comment]
> I'll actively manage this outage once I get home. For now rest assured I'm aware of it and thinking of options

Thanks

**Comment by Arcaly** [comment]
Hey just wanted to ask if there is already a plan/fix in development or decided on. No pressure, just wondering.

**Comment by AlexFreik** [comment]
I would suggest adding "Episodes not released yet" , so new people don't get confused and don't create a new issue

**Comment by letomarancais** [comment]
@docfaizal
> Please add either 9anime or zoro as sources

How does one do that?

**Comment by CoolnsX** [comment]
> How does one do that?
It's simple, go through the request and response made by websits u prefer.
Then after figuring out each and every important thing u need, write a logic in ur preferred language.
then test it thorougly for each and every edge cases.
then after getting some confidence, push it on ur github or other option is make it properitory and make some money..

**Comment by docfaizal** [comment]
> > How does one do that?
> 
> It's simple, go through the request and response made by websits u prefer. Then after figuring out each and every important thing u need, write a logic in ur preferred language. then test it thorougly for each and every edge cases. then after getting some confidence, push it on ur github or other option is make it properitory and make some money..

Any ETA on PR merge?

**Comment by port19x** [comment]
> > > How does one do that?
> > 
> > 
> > It's simple, go through the request and response made by websits u prefer. Then after figuring out each and every important thing u need, write a logic in ur preferred language. then test it thorougly for each and every edge cases. then after getting some confidence, push it on ur github or other option is make it properitory and make some money..
> 
> Any ETA on PR merge?

Some components already work quite well, but the rewrite is still incomplete and not very coherent.
I expect it to be mergable on the weekend.
Best case thursday

**Comment by docfaizal** [comment]
> 

Gambare :)

**Comment by docfaizal** [comment]
> > > > How does one do that?
> > > 
> > > 
> > > It's simple, go through the request and response made by websits u prefer. Then after figuring out each and every important thing u need, write a logic in ur preferred language. then test it thorougly for each and every edge cases. then after getting some confidence, push it on ur github or other option is make it properitory and make some money..
> > 
> > 
> > Any ETA on PR merge?
> 
> Some components already work quite well, but the rewrite is still incomplete and not very coherent. I expect it to be mergable on the weekend. Best case thursday

Gambare :)

**Comment by prorounak2005** [comment]
I would highly recommend you guys to scrape anime from gogoanime. https://gogoanime.news/ is their official website where they inform you about latest anime news and if u scroll down a little bit you will get list of all the official domains they use. Believe it or not [most of the anime website scrapes anime from gogoanime](https://c-v.sh/greensickgnawing.png). I know the website has ads but that is their only way to earn money. It has a huge disqus community , reddit community and also a discord community with more than 26000 members !!

**Comment by niveK77pur** [comment]
Hello, I have seen scraping gogoanime come up in another issue here as well a few days ago, so I thought I might share this. Hopefully it could help in or give some ideas for creating a gogoanime scraper to get the actual episodes (if not done so yet, I am not following the developments too closely).

A little over a year ago I wrote a [gogoanime scraper](https://github.com/niveK77pur/gogoanime) myself in Python, which would simply extract the download links when you click on the yellow download button on an episode. These links were meant to be used by aria2 to actually download stuff, so downloading was not part of my scraper.

I have stopped working on it a long time ago because I was not able to circumvent the captcha anymore (they have become more and more tricky to deal with). At some point I had to use selenium for this but even that is probably still broken by now. Also, since I have switched to ani-cli in the meantime, I don't even know if my scraper still functions at all (i.e. properly traverses the HTML tags, links, etc).

Just dropping this here in case it could be of any use to resolve the issue.

**Comment by justchokingaround** [comment]
Thank you guys for your input, but the scraping part is already finished. Gogoanime is just a frontend for gogoplay which is one of the most prominent providers for anime. In v4 gogoplay is one of the sources that we scrape, however there are several other better sources which will be priority, since they give back mp4 links instead of m3u8. No need to worry about the scraping part, but thank you for trying to help anyways 👍

**Comment by MrSmoer** [comment]
in v4 on android (git, not package) mpv does not start the link properly, in case you didnt notice. It works without the `--force-media-title="${allanime_title}episode..`
Should I open an entire issue for that? (It feels bad for the unreleased branch) if you dont answer, I just wont open one :)

**Comment by Derisis13** [comment]
> in v4 on android (git, not package) mpv does not start the link properly, in case you didnt notice. It works without the `--force-media-title="${allanime_title}episode..` Should I open an entire issue for that? (It feels bad for the unreleased branch) if you dont answer, I just wont open one :)

If you look at the PR, you'll see that android support is still missing. The way it used to work on android is using `am start` to launch the android version of mpv/vlc. It is not implemented yet, but we're working on it. Thanks for the heads up!

**Comment by docfaizal** [comment]
![2023-01-04-183846_1366x768_scrot](https://user-images.githubusercontent.com/107258640/210562176-1118164a-a155-419f-b809-85adb53a3717.png)
So i just got time today to try the v4 branch and it's damn good,Great work guys

**Comment by prorounak2005** [comment]
> ![2023-01-04-183846_1366x768_scrot](https://user-images.githubusercontent.com/107258640/210562176-1118164a-a155-419f-b809-85adb53a3717.png) So i just got time today to try the v4 branch and it's damn good,and i love the way that it fetch all the sources at once,Great work guys

Gentoo users - big pp

**Comment by BeauTaapken** [comment]
i've been trying v4 for a bit now, but the feature i was using most doesn't work that nicely anymore, downloading. now i can only select 1 episode at a time and I have to keep pressing next to download more. when selecting an episode i can't select multiple at once anymore either. Are there any plans to get the bulk selecting of episodes back into v4?

**Comment by Derisis13** [comment]
> i've been trying v4 for a bit now, but the feature i was using most doesn't work that nicely anymore, downloading. now i can only select 1 episode at a time and I have to keep pressing next to download more. when selecting an episode i can't select multiple at once anymore either. Are there any plans to get the bulk selecting of episodes back into v4?

It's on our checklist, we're aware, but it's a little complicated with fzf

**Comment by candrapersada** [comment]
why is `-r select provider to scrape first` missing
![gambar](https://user-images.githubusercontent.com/36833664/211050071-bac29633-4846-4044-858c-534695a81c4a.png)

**Comment by Derisis13** [comment]
Because it's not necessary, the requests go out at the same time. The results are compiled into a list from where the desired quality is selected. Priority of providers is hard-coded and would require an extensive effort to change. This is the trade-off for being faster and always getting the desired quality, even if only the 2nd provider would have its link.

**Comment by prorounak2005** [comment]
Btw how can I download v4 ? It is not in the official release yet ig ?

**Comment by redragerover** [comment]
Is there a new referral link we have to add to mpv.conf to get the links to open on mpv-android?

> Btw how can I download v4 ? It is not in the official release yet ig ?

It's in the v4 branch. Clone the repo and `git checkout v4`

**Comment by Quicksilver151** [comment]
> Because it's not necessary, the requests go out at the same time. The results are compiled into a list from where the desired quality is selected. Priority of providers is hard-coded and would require an extensive effort to change. This is the trade-off for being faster and always getting the desired quality, even if only the 2nd provider would have its link.

do all the sources have download resumeability?

**Comment by Derisis13** [comment]
> > Because it's not necessary, the requests go out at the same time. The results are compiled into a list from where the desired quality is selected. Priority of providers is hard-coded and would require an extensive effort to change. This is the trade-off for being faster and always getting the desired quality, even if only the 2nd provider would have its link.
> 
> do all the sources have download resumeability?

Currently there's no "resumeability" at all, even history is to be implemented, but it'll be the same for all of them.

**Comment by KurosakiHT** [comment]
Confirmed that ani-cli v4 now work with mpv on android

**Comment by candrapersada** [comment]
Why did the name of the anime I downloaded change from `Majin Bone Episode 40` to `majin-bone-episode-40-sub`?

**Comment by fold-squirrel** [comment]
> Why did the name of the anime I downloaded change from `Majin Bone Episode 40.mp4` to `majin-bone-episode-40-sub.mp4`?

because that's is how ani-cli does it and there's no reason to change it

```bash
name=majin-bone-episode-40-sub.mp4 mv $name $( echo $name | sed -e 's/\(\w\)\(\w\)*-/\U\1\L\2 /g' -e 's/ sub//' )
```

replace the majin-bone-episode-40-sub.mp4 with any anime name and this one liner will rename it for you, you can put it in a loop or use xargs to rename all anime at once

**Comment by candrapersada** [comment]
> ```shell
> name=majin-bone-episode-40-sub.mp4 mv $name "$( echo $name | sed -e 's/\(\w\)\(\w*\)-/\U\1\L\2 /g' -e 's/ sub//' )"
> ```
> 
> replace the majin-bone-episode-40-sub.mp4 with any anime name and this one liner will rename it for you, you can put it in a loop or use xargs to rename all anime at once

can it be used on windows?

**Comment by CoolnsX** [comment]
> ~Is there a new referral link we have to add to mpv.conf to get the links to open on mpv-android for v4?~
> 
> > Btw how can I download v4 ? It is not in the official release yet ig ?
> 
> It's in the v4 branch. Clone the repo and `git checkout v4`
> 
> Edit: Working for me using VLC android. Just deleted the MPV app and ran the VLC script found in the Discord. Thanks guys loving v4!
> 
> `echo 'am start --user 0 -a android.intent.action.VIEW -d "$1" -n org.videolan.vlc/org.videolan.vlc.gui.video.VideoPlayerActivity' \> $PREFIX/bin/vlc && chmod +x $PREFIX/bin/vlc`

this feature is now baked in.. no need to do this..

**Comment by CoolnsX** [comment]
> > ```shell
> > name=majin-bone-episode-40-sub.mp4 mv $name "$( echo $name | sed -e 's/\(\w\)\(\w*\)-/\U\1\L\2 /g' -e 's/ sub//' )"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > replace the majin-bone-episode-40-sub.mp4 with any anime name and this one liner will rename it for you, you can put it in a loop or use xargs to rename all anime at once
> 
> can it be used on windows?

will discuss about it with other maintainers..

**Comment by fold-squirrel** [comment]
> > ```shell
> > name=majin-bone-episode-40-sub.mp4 mv $name "$( echo $name | sed -e 's/\(\w\)\(\w*\)-/\U\1\L\2 /g' -e 's/ sub//' )"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > replace the majin-bone-episode-40-sub.mp4 with any anime name and this one liner will rename it for you, you can put it in a loop or use xargs to rename all anime at once
> 
> can it be used on windows?

yes it will work in git bash shell, the same one you use to run ani-cli

**Comment by candrapersada** [comment]
how to download next episode automatically?

**Comment by fold-squirrel** [comment]
> how to download next episode automatically?

someone is working on implementing this rn, it the final thing we need to have ani-cli v4 ready. Also you might want to join our [discord](https://discord.gg/aqu7GpqVmR) server where you can get help easier.
