### ISSUE TITLE
Windows 11 cache building slowly and buffering

### ISSUE THREAD

**Issue by PredatoryEyesLOL** [pystardust/ani-cli#949]
Version: 3.4.0
OS: Windows 11
Shell: Bash (installed using scoop)
Anime: Tested in Mob psycho 100 III

The cache buildup is too slow it doesnot work properly. The episodes keeps buffering which was not an issue previously.

I retested the same episode in debian using wslg but there the script worked perfectly and the cache was also buiding up fast.

**Comment by port19x** [comment]
I'm suprised it worked at all as we currently have an outage due to #948 

I'll close this as it's likely related to said outage.
Rest assured we're working on it

**Comment by PredatoryEyesLOL** [comment]
> I'm suprised it worked at all as we currently have an outage due to #948
> 
> I'll close this as it's likely related to said outage. Rest assured we're working on it

This was Before the animixplay fiasco and I happened to report after it happened.

**Comment by CoolnsX** [comment]
well this issue is not relevent anymore, so..
