### ISSUE TITLE
[Feature Request] Quality/bitrate selector while in menu

### ISSUE THREAD

**Issue by stl3** [pystardust/ani-cli#95]
Something like:
```
[n] next episode
[s] select episode
[r] replay current episode
[b] select/set bitrate/quality
[q] exit
```
and perhaps also a selective option for downloading episodes using ranges or ep number (seperated by commas), for example:
`Choose episode [1-13]: 1-6, 9, 12`
1-6 would download episodes ranging from 1-6, and 9 along with 12 would be a selective single download, with entries of selection seperated by comma

I also found [https://github.com/Derisis13/ani-cli/tree/search-without-exit](url) very helpful.

**Comment by ura43** [comment]
I don't really see the use of a bitrate selector, but episode ranges like you described sound like a good and somewhat easy to implement idea

**Comment by ura43** [comment]
Oh, had a brainfart earlier. Of course a quality selector would be awesome. I for some reason think you just wanted bitrate while not providing choice on resolution
