### ISSUE TITLE
Problems with anime episodes

### ISSUE THREAD

**Issue by mizet12** [pystardust/ani-cli#950]
When I try to watch anime for example: "greate teacher onizuka", when I pick a anime from the list i cannot pick a episode. It just says that there are no episodes avaiable.
![image](https://user-images.githubusercontent.com/73276769/209397059-ba9bd556-042f-4a7e-8a18-f8ac5c445520.png)

**Comment by justchokingaround** [comment]
duplicate of #948

**Comment by devraza** [comment]
#948
