### ISSUE TITLE
Episodes not released yet!

### ISSUE THREAD

**Issue by theAnaKen** [pystardust/ani-cli#954]
Version: 3.4.7
OS: Windows 10
Shell: git bash
Anime: all i searched for

every time i search for an anime and select the title it gives the error "Episodes not released yet!"

**Steps To Reproduce**
1. Run `ani-cli `
2. search for an anime
3. Choose any one

**Expected behavior**
it should ask for the episode number

**Screenshots (if applicable; you can just drag the image onto github)**
![image](https://user-images.githubusercontent.com/80813371/209447377-2c8d283a-3227-4468-b984-b96999b3afb2.png)

**Comment by icedgreen** [comment]
Yeah this is due to animixplay EOL (see issues).

**Comment by port19x** [comment]
Yeah, we're working on a new and improved version. Should be done by the time christmas is over.
Closing as duplicate in favor of #948
