### ISSUE TITLE
GogoAnime as host instead of AnimixPlay

### ISSUE THREAD

**Issue by rbjnazz** [pystardust/ani-cli#960]
![IMG_20221228_233350](https://user-images.githubusercontent.com/85556041/209837770-af7b5274-4117-4732-a012-fad6bf0f5151.jpg)

Since AnimixPlay is gone forever,
please update the stdout from:

`Episodes not released yet!`
to
`Animixplay.to is no longer available. Please wait until we change the web scraper to a different domain. We apologize for the inconvenience.`

there's no other choice than gogoanime. 😅

**Comment by justchokingaround** [comment]
>wrong
>doesnt elaborate further
>leaves
but in all seriousness, we're scraping allanime.site now, which scrapes other sources such as 9anime and gogoanime, you can check out the v4 branch for that, although its still a wip

**Comment by rbjnazz** [comment]
> > wrong
> > doesnt elaborate further
> > leaves
> > but in all seriousness, we're scraping allanime.site now, which scrapes other sources such as 9anime and gogoanime, you can check out the v4 branch for that, although its still a wip

Your right. Any major updates?

**Comment by 71zenith** [comment]
> > > wrong
> > > doesnt elaborate further
> > > leaves
> > > but in all seriousness, we're scraping allanime.site now, which scrapes other sources such as 9anime and gogoanime, you can check out the v4 branch for that, although its still a wip
> 
> Your right. Any major updates?
Check the v4 branch
