### ISSUE TITLE
Error : Episodes not released yet! While it should have Episodes

### ISSUE THREAD

**Issue by realitymolder** [pystardust/ani-cli#966]
**Metadata (please complete the following information)**
Version: 3.4.7
OS: MacOS 13.1
Shell: zsh
Anime: any anime

**Describe the bug**
When trying to watch any anime, the program spits `Episodes not released yet!`
This is a wrong.

**Steps To Reproduce**
1. Remove ani-cli and reinstall it again to make sure you are using the latest version
2. Run `ani-cli -U` to make sure there is no update
3. Run `ani-cli one piece`
4. Choose 1 (one piece)
5. Choose episode 1

**Expected behavior**
MPV / iina Should pop out and run the episode + a new episode cli menu.

**Screenshots (if applicable; you can just drag the image onto github)**
![image](https://user-images.githubusercontent.com/26459151/210793665-b4dc7d13-ff3a-426e-a356-b45c55851215.png)

**Comment by mindstormjak** [comment]
animixplay has shutdown so wait for v4 of ani-cli to be released or try the v4 branch #955

**Comment by realitymolder** [comment]
sorry seems like i missed this one
