### ISSUE TITLE
[Request] other website sources & linux VLC option

### ISSUE THREAD

**Issue by jonvfb** [pystardust/ani-cli#97]
Since these "watch free anime" websites usually come and go, it would be nice to have multiple sources from where to pull the videos from. Maybe an option that lists all the supported sites; also in that same menu an option to choose the preferred player between VLC and mpv player.

I think this feature could add some scalability, and longevity to this project since at the moment depends only on gogoanime.

PS: This project is great! thanks for sharing it!

**Comment by Shulkk** [comment]
It would be nice to have multiple website anime sources, however i don't know if other anime sites offer an api or not, and a linux vlc option is pretty pointless imo.

**Comment by shulkk** [comment]
There seems to be good news for a linux VLC option. [Check out this (currently open as of writing) PR!](https://github.com/pystardust/ani-cli/pull/172)

**Comment by ura43** [comment]
The PR for vlc is merged, and other website sources will be essential in fixing many of the current issues.
I'm closing this issue because it will likely be resolved while trying to solve bigger problems
