### ISSUE TITLE
ani-cli v4 does not work in git bash

### ISSUE THREAD

**Issue by Rusomati** [pystardust/ani-cli#970]
basically v4 needs fzf in order to work however fzf does not work in git bash i found a workaround for the fzf problem which is to add "alias fzf  ="winpty fzf"" to .bashrc.. this made fzf work but ani-cli still does not works (it halts)

**Comment by port19x** [comment]
Can you try if [gum](https://github.com/charmbracelet/gum) works on git bash?

**Comment by Derisis13** [comment]
An alternative is to install the "windows terminal" (preview) and install git bash with windows terminal integration. Then you can use git bash from the windows terminal where fzf works without aliasing it.

**Comment by Rusomati** [comment]
first: I am sorry that I forgot to mention that I use windows 7

gum didn't work in git bash..
i tried ``gum choose "h" "e"``
and got ``failed to get console mode for stdout: The handle is invalid.
failed to get console mode for stderr: The handle is invalid.
failed to start tea program: prepare console: set console mode: The parameter is incorrect.
``

and as I have windows 7 I cant download the windows terminal because it is downloaded from the microsoft store even the cli download uses the microsoft store

I appreciate your help and understand that my situation is not worth looking into as windows 7 is deprecated

**Comment by sweetbbak** [comment]
There is a workaround to installing Windows terminal without the windows store. Just use a package manager like Scoop or choco. Winget didn't work for me, but I dont have windows anymore to check. I always delete the windows store and it causes some problems but that should help.

install scoop by opening a powershell prompt and running:

Set-ExecutionPolicy RemoteSigned -Scope CurrentUser # Optional: Needed to run a remote script the first time
irm get.scoop.sh | iex

go to the scoop website, download scoop, add the 'extras' bucket  with: 
"scoop bucket add extras"

and then do 'scoop install windows terminal with:
"scoop install windows-terminal"

**Comment by Rusomati** [comment]
sadly the last command gave me: ``ERROR At least Windows 10 19H1 (build 18362) is required.``

**Comment by prorounak2005** [comment]
> sadly the last command gave me: `ERROR At least Windows 10 19H1 (build 18362) is required.`

To be honest with you using git bash/WSL on windows is a horrible experience. U should simply switch to linux. Everything runs on linux like it does on windows. Linux is a just a different operating system. Bash works natively on unix like operating systems like mac and linux. If u don't want to switch to linux my advice is to watch anime on a browser with ublock origin adblock extension which can be downloaded from the extension store. To download animes you can use https://nyaa.si

**Comment by Rusomati** [comment]
sorry for the late reply..
i already use Linux ~artix btw~, and i have ani-cli on termux, i only use windows to play with my friends , test pranks and in this case ~show off~.. so yeah windows 7 is deprecated and so either its users have to use alternatives or bear the consequences so i think that it is not worth porting ani-cli assuming that windows terminal works well
