### ISSUE TITLE
Download not working

### ISSUE THREAD

**Issue by ganesh314159** [pystardust/ani-cli#98]
I was downloading steins;gate0 , it downloads mp4 but mpv cant open it. and video files are also too small, I think its not downloading real episode.

**Comment by sdshan8** [comment]
PR #35

**Comment by funisdone** [comment]
Same here

**Comment by Vit0rg** [comment]
Yes, an html file with the ERROR CODE HTTP 403 (FORBIDDEN) is now downloaded instead, indicating that authentication is required. The gogoanimes site requires an account to allow the download, perhaps the simplest solution is to edit the CURL command on the download line with the flag -u user:pass.

**Comment by Dink4n** [comment]
Working now
