### ISSUE TITLE
Go back to curl

### ISSUE THREAD

**Issue by Terraro53** [pystardust/ani-cli#984]
**Metadata (please complete the following information)**
Version: 4.0.0
OS: Debain 11(AntiX)
Shell: bash

**Describe the bug**
Versions of wget below the latest(1.21.3) dont work with the script.

**Steps To Reproduce**

1. Have older version of wget installed (eg:1.21)
2. Run `ani-cli -d flcl`
3. Script returns "No results found"

**Expected behavior**
Script should work normally.

**Additional context**
Manually upgrading Wget fixes the issue.

**Comment by ejkozan** [comment]
Bumping, not working with GNU Wget 1.19.4

**Comment by Derisis13** [comment]
I think there's a package from debian 10 called wget2 that installs wget 1.99.1, is that good for the script?

**Comment by ejkozan** [comment]
Did not helped

**Comment by ejkozan** [comment]
`+ version_number=4.0.1
+ agent='Mozilla/5.0 (X11; Linux x86_64; rv:99.0) Gecko/20100101 Firefox/100.0'
+ mode=sub
+ media_locale=en-US
+ download_dir=.
+ quality=best
+ case "$(uname -a)" in
++ uname -a
+ player_function=mpv
+ use_external_menu=0
+ '[' 0 = 0 ']'
+ multi_selection_flag=-m
+ '[' 0 = 1 ']'
+ cache_dir=/home/ejkozan/.cache/ani-cli
+ '[' '!' -d /home/ejkozan/.cache/ani-cli ']'
+ hist_dir=/home/ejkozan/.local/state/ani-cli
+ '[' '!' -d /home/ejkozan/.local/state/ani-cli ']'
+ histfile=/home/ejkozan/.local/state/ani-cli/ani-hsts
+ '[' '!' -f /home/ejkozan/.local/state/ani-cli/ani-hsts ']'
+ search=scrape
+ '[' 0 -gt 0 ']'
+ printf '\33[2K\r\033[1;34mChecking dependencies...\033[0m\n'
Checking dependencies...
+ dep_ch wget sed grep fzf
+ for dep in "$@"
+ command -v wget
+ for dep in "$@"
+ command -v sed
+ for dep in "$@"
+ command -v grep
+ for dep in "$@"
+ command -v fzf
+ case "$player_function" in
+ dep_ch mpv
+ for dep in "$@"
+ command -v mpv
+ case "$search" in
+ '[' -z '' ']'
+ '[' 0 = 0 ']'
+ printf 'Search anime: '
Search anime: + read -r query
flcl
+ '[' -z flcl ']'
++ printf %s flcl
++ sed 's| |%20|g'
+ query=flcl
++ search_anime flcl
++ wget -q -O - 'https://allanime.site/allanimeapi?variables=%7B%22search%22%3A%7B%22allowAdult%22%3Atrue%2C%22allowUnknown%22%3Atrue%2C%22query%22%3A%22flcl%22%7D%2C%22limit%22%3A40%2C%22page%22%3A1%2C%22translationType%22%3A%22sub%22%2C%22countryOrigin%22%3A%22ALL%22%7D&extensions=%7B%22persistedQuery%22%3A%7B%22version%22%3A1%2C%22sha256Hash%22%3A%229c7a8bc1e095a34f2972699e8105f7aaf9082c6e1ccd56eab99c2f1a971152c6%22%7D%7D' -U 'Mozilla/5.0 (X11; Linux x86_64; rv:99.0) Gecko/20100101 Firefox/100.0'
++ sed 's|Show|\n|g'
++ sed -nE 's|.*_id":"([^"]*)","name":"(.*)","english.*"sub":([1-9][^,]*).*|\1\t\2 (\3 episode)|p'
++ sed 's/\\//g;s/"//g'
+ anime_list=
+ '[' -z '' ']'
+ die 'No results found!'
+ printf '\33[2K\r\033[1;31m%s\033[0m\n' 'No results found!'
No results found!
+ exit 1`

**Comment by Terraro53** [comment]
> I think there's a package from debian 10 called wget2 that installs wget 1.99.1, is that good for the script?

installing wget2 and replacing every use of wget in the script with wget2 works.

**Comment by psycoxer** [comment]
> > I think there's a package from debian 10 called wget2 that installs wget 1.99.1, is that good for the script?
> 
> installing wget2 and replacing every use of wget in the script with wget2 works.

Globally aliasing wget2 to wget also works,
Otherwise ```sed -i 's/wget/wget2/g' ./ani-cli``` is simpler

**Comment by ejkozan** [comment]
Strange, replacing wget with wget2 does not work for me, still identical behaviour

**Comment by Terraro53** [comment]
> Strange, replacing wget with wget2 does not work for me, still identical behaviour

what version of wget2 do you have?

**Comment by Wiener234** [comment]
The ppa for the debian package is up to date an working with wget2.
And there was a problem with ani-cli v4.0.2 and it was reverted back to v4.0.1.
Maybe try to pull the repo again.

**Comment by trueauracoral** [comment]
Before animixplay broke, ani-cli used curl for everything. Why did ani-cli switch to wget? Is there something wget can do that curl is incapable of? I tried modified the script myself to use curl instead of wget and it didn't work. I use windows and finding a copy of wget is difficult they are all old copies. I see wget 1.11.4 on gnuwin32's site.

**Comment by CoolnsX** [comment]
trust me bro we all love curl, but the windows is giving us soo much pain

**Comment by ejkozan** [comment]
Ok, it works with NIX 2.0.1! only thing aliasing do not work, i need to modify script to wget2
Is there then possibility to detect if wget2 is present and then use it otherwise just wget for everyone convenience?
And why just curl won't work? Something with user agent?

**Comment by Derisis13** [comment]
Now this is addressed in the readme

**Comment by trueauracoral** [comment]
Can you address in the readme why wget is needed in replacement of curl? Curl is widely used software pre-installed on windows even.

**Comment by CoolnsX** [comment]
Cause curl is shit on windows..

**Comment by CoolnsX** [comment]
i will give u ss tmr

**Comment by trueauracoral** [comment]
oh. Then probably the readme should talk about how for windows users they need to install wget2 and stuff. 
https://raw.githubusercontent.com/CoolnsX/and-scripts/main/ani-new I tried your ani-new script which scrapes allanime and it appears to use curl. It worked fine on windows.

**Comment by CoolnsX** [comment]
well that still uses old animixplay.. try this
https://0x0.st/oFJU.sh

**Comment by trueauracoral** [comment]
That one does not work.

**Comment by CoolnsX** [comment]
well cause the script exits at first curl to allanime..

**Comment by CoolnsX** [comment]
well found a solution to make it work using curl.. so currently testing it and maybe add in next point release

**Comment by trueauracoral** [comment]
Awesome.

**Comment by Wiener234** [comment]
the script worked for me with older versions of wget. To be specific with 1.18.
Was there some change in the script that im not aware of?
