### ISSUE TITLE
Episode not release 

### ISSUE THREAD

**Issue by Reaper176** [pystardust/ani-cli#986]
**Metadata (please complete the following information)**
Version: 4.0.1
OS: garuda linux / arch
Shell: fish
Anime: Ningen Fushin no Boukensha-tachi ga Sekai wo Sukuu you desu

**Describe the bug**
Episode not released!

**Steps To Reproduce**

1. Run `ani-cli -d Ningen Fushin no Boukensha-tachi ga Sekai wo Sukuu you desu`
2. Choose episode 3 / 4

**Expected behavior**
should play

**Comment by Derisis13** [comment]
It appears to me your issue is fixed, reopen if not

**Comment by koyuawsmbrtn** [comment]
Doesn't work on Debian 11 on Chrome OS

**Comment by Derisis13** [comment]
> Doesn't work on Debian 11 on Chrome OS

#984

**Comment by candrapersada** [comment]
Doesn't work on windows too
