### ISSUE TITLE
[Issue] unchecked input in `open_episode( )`

### ISSUE THREAD

**Issue by Derisis13** [pystardust/ani-cli#99]
In function `open_episode( )` there's an if branch to detect if an out-of-range episode number was given, and a second selection is offerd. This second selection (line 222-223) is not checked, if you enter a number greater than `$last_ep_number` the script tries to play it.
Solution: make the if statement a while loop with the same condition.

**Comment by Derisis13** [comment]
![image](https://user-images.githubusercontent.com/66648475/139687485-1043ca5d-33ec-4494-8d30-ff210d4dc713.png)

**Comment by jnishwanth** [comment]
Issue should be fixed now. Someone should consider closing this?
