### ISSUE TITLE
"Episodes not released yet!" play error

### ISSUE THREAD

**Issue by KVince002** [pystardust/ani-cli#991]
**Metadata (please complete the following information)**
Version: [3.4]
OS: [Windows 11]
Shell: [Poweshell]
Anime: [jojo no kimyou na bouken diamond wa kudakenai dub]

**Describe the bug**
When I try to watch jojo part 5 dub suddenly, I encounter this error: "Episodes not released yet!". I check on the page and I found the episodes (I think).

**Steps To Reproduce**

1. Run ani-cli
2. jojo
3. Choose episode 15

**Expected behavior**
Start my mpv and play the episode(s).

**Screenshots (if applicable; you can just drag the image onto github)**
![image](https://user-images.githubusercontent.com/93611221/214718270-864c27b8-e7f3-4189-bb75-a52c2d3d14fa.png)

**Additional context**
I tried to run the same command on my OpenSUSE Tumbleweed laptop, but I got the same issue. (On SUSE i got ani-cli from the zypper)

**Comment by MapsKing379** [comment]
I'm getting the same thing on Debian 11 on Chrome OS

**Comment by Veroniclover** [comment]
You're probably in the Old version. Try updating it.

**Comment by Drahrekot** [comment]
I'm getting the same error on Arch too
![Screenshot_2023-01-26-07-20-59_1920x1080](https://user-images.githubusercontent.com/77320136/214739390-a272b44e-18b2-4a5f-8fa6-7a694aa70ec3.png)

**Comment by 71zenith** [comment]
update to the latest version 
for [windows](https://github.com/pystardust/ani-cli#Windows) **note**: do not use scoop as of now
for [linux](https://github.com/pystardust/ani-cli#Installing-from-source) **note**: do not use ur package manager
and install fzf

**Comment by Derisis13** [comment]
> **Additional context** I tried to run the same command on my OpenSUSE Tumbleweed laptop, but I got the same issue. (On SUSE i got ani-cli from the zypper)

The OpenSUSE package is missing the update because copr has some errors building on SUSE. I hope it's fixed soon and I can release v4 there. Other packages should be fine now that an official release was done

**Comment by Derisis13** [comment]
You can follow the [From Soruce](https://github.com/pystardust/ani-cli#from-source) segment in the readme until I get a response on my bug report. I'll also try to build you a package for leap 15.4
