### ISSUE TITLE
Termux package requires update

### ISSUE THREAD

**Issue by Crisp-Casper** [pystardust/ani-cli#992]
**Metadata (please complete the following information)**

android termux

**Describe the bug**

its v3, easy fix if you git clone and replace the installed ani-cli package

**Steps To Reproduce**

1. open termux
2. pkg install ani-cli

**Expected behavior**

profit

**Additional context**

Much <3 to ani-cli devs

tempfix:

```
pkg install git ani-cli wget fzf aria2 -y
git clone https://github.com/pystardust/ani-cli.git
cd ani-cli
cp ani-cli /data/data/com.termux/files/usr/bin/ani-cli
cd ..
rm -rf ani-cli
```

**Comment by Crisp-Casper** [comment]
im not actually sure if libxslt is required i just copy and pasted my fix for a install script i have

**Comment by port19x** [comment]
Can confirm, will PR a new termux package later today

**Comment by port19x** [comment]
Once I release v4 anyway

**Comment by port19x** [comment]
closing in favor of #997
