### ISSUE TITLE
Bump all downstream packages

### ISSUE THREAD

**Issue by port19x** [pystardust/ani-cli#997]
Please let me bump the stuff guys.

Prerequisite:

- [x] V4 Release

Repos:
![2023-01-26_14-02](https://camo.githubusercontent.com/5f58827350492adb15274121ebdd630d584c5dbc468c03163f27fb5c75e7ea4c/68747470733a2f2f7265706f6c6f67792e6f72672f62616467652f766572746963616c2d616c6c7265706f732f616e692d636c692e7376673f6d696e76657273696f6e3d342e30)

Github PRable:
- [x] 1. [nixpkgs](https://github.com/NixOS/nixpkgs)
- [x] 2. [termux](https://github.com/termux/termux-packages)
- [ ] 3. [scoop](https://github.com/ScoopInstaller/Extras) (awaiting merge)
- [x] 4. [pacstall](https://github.com/pacstall/pacstall-programs)
- [ ] 5. [slackbuilds](https://github.com/Ponce/slackbuilds) (need to contact downstream maintainer)

Otherwise updatable:
- [x] [freshcode](http://freshcode.club/projects/ani-cli)
- [x] [AUR](https://aur.archlinux.org/packages/ani-cli) (done by sgtxd)

**Comment by port19x** [comment]
I'll get to it on the weekend

**Comment by Derisis13** [comment]
Repology doesn't track copr, but it was updated there too (except for suse because suse building on copr is malfunctioning)

**Comment by TheRealOne78** [comment]
I see v4 is upstream for termux in repology, however updating the repos in termux does not show any change

![Screenshot_20230127-202523_Termux.png](https://user-images.githubusercontent.com/53640879/215165423-0cff8194-5b44-4925-a2ec-269222d0cdcd.png)

**Comment by TheRealOne78** [comment]
I also noticed there is no ani-cli in the ::gentoo repository anymore. Perhaps a ::guru update may be a good thing.

**Comment by port19x** [comment]
> I see v4 is upstream for termux in repology, however updating the repos in termux does not show any change
> 
> ![Screenshot_20230127-202523_Termux.png](https://user-images.githubusercontent.com/53640879/215165423-0cff8194-5b44-4925-a2ec-269222d0cdcd.png)

Thats because some termux maintainer thought a simple tag bump would be enough. I'm on it.

**Comment by port19x** [comment]
Dependency diff:
```diff
- axel
- curl
- awk
- openssl
+ aria2
+ fzf
+ wget
```

**Comment by port19x** [comment]
pacstall didn't even check for deps at all :skull:

**Comment by port19x** [comment]
I can't, slackbuilds only depended on `axel` and `mpv`. The heck?
